### ISSUE TITLE
Data frame conversion from IMU to ODOM

### ISSUE THREAD

**Issue by Mojojojooo** [lgsvl/simulator#1004]
1.How are the frame data of IMU and ODOM related. 
2.What can be done in the source code to convert data from IMU frame to ODOM frame.

**Comment by hadiTab** [comment]
@Mojojojooo I'd suggest reading [this page](https://www.lgsvlsimulator.com/docs/sensor-json-options/) from our documentation which explains the how to configure the sensors on the vehicle. The relative location of the sensors is defined by the `transform` in the JSON config. By default, if no `parent` is defined for the sensor, the transform will be relative to the center of the vehicle projected onto the ground. However you can add a `parent` entry for each sensor which will define where the transform is relative to. If you would like to have a random point defined in the vehicle to use as a parent for other frames, you can use the [Transform Sensor](https://www.lgsvlsimulator.com/docs/sensor-json-options/#transform-sensor) to create such a reference point and use it as `parent` for other sensors.

**Comment by Mojojojooo** [comment]
So if we define the transform sensor at the center of the car and add parent entery to all other sensors then everything will be with respect to the center. Did I get it correct ?

**Comment by hadiTab** [comment]
Yes, that is correct.
