### ISSUE TITLE
Error open localhost:8080

### ISSUE THREAD

**Issue by AlexandrZabolotny** [lgsvl/simulator#1007]
Hi team! Help me please if you can!

I see the following picture when I open the local host after starting the simulator  

![Screenshot from 2020-09-23 17-39-43](https://user-images.githubusercontent.com/61351599/94028574-9dbc4480-fdc4-11ea-8102-2910cc04639c.png)  

**Perhaps you have any ideas?**  
This happened when I added a new map to /simulator/Sim/AssetBundles/Environments

**Comment by ntutangyun** [comment]
coud you try to use another browser or do a complete reload of the website. 

for example for chrome, it's Shift + F5

**Comment by dr563105** [comment]
Clear your cache. Close your browser and reopen the link.

**Comment by EricBoiseLGSVL** [comment]
Yes, Ctrl+R will clear cache
