### ISSUE TITLE
Wrong car position in Apollo 5.0

### ISSUE THREAD

**Issue by eyadshak** [lgsvl/simulator#1013]
So I am running Apollo and LGSVL on separate machines, I'm experiencing minimum latency when moving the car manually, and while observing the traffic light recognition, but the ego car's position in Apollo's Dreamview is wrong, causing the car to crash when control is enabled. It localizes in the wrong position but continues to mirror the movement of LGSVL with no delays, 

![lgsvl](https://user-images.githubusercontent.com/51527525/94144485-3d8bd800-fe82-11ea-8e4a-be098fdfaa65.PNG)
![apollo](https://user-images.githubusercontent.com/51527525/94144535-4ed4e480-fe82-11ea-8264-c1b9466c26c3.png)

Here are the results of cyber_monitor

![apollo_monitor](https://user-images.githubusercontent.com/51527525/94144544-53010200-fe82-11ea-98f1-a46c7f6e945b.png)

I checked more than one map and they all have the same issue, the HD map annotation tool shows annotations correctly in the unity editor and the NPCs are driving in the correct lanes.

Would anyone know how to fix this? I am running Apollo 5.0, for some reason when I tested it on the current Apollo master correct localization worked with no issue on Borregas Ave.

**Comment by rongguodong** [comment]
I believe you are using 2020.06, which requires new map asset bundle. Please delete the database so that it will automatically download the new asset bundle. Or you can manually download it [here](https://content.lgsvlsimulator.com/maps/borregasave/).

**Comment by eyadshak** [comment]
It was indeed a problem with using old maps, had to replace the asset bundle and HD map info (base_map, routing_map, sim_map).
Thank you for your help!
