### ISSUE TITLE
Unity Editor with LGSVL Simulator

### ISSUE THREAD

**Issue by asifsid-32** [lgsvl/simulator#1023]
Hello LGSVL Team,

What all maps can be edited in lgsvl simulator, Is autonomous stuff is an open source map ? Can we place calibration patterns in it to calibrate the cameras ? What steps do we need to follow if we want to open certain map in unity editor and reflect the changes to executable ?

**Comment by EricBoiseLGSVL** [comment]
@asifsid-32 CubeTown, San Francisco, Shalun, Single Lane Road are open sourced to be edited.  Sorry, AutonomouStuff is not.  Yes, you can do this in Editor or a modeling application.  Please see our [documentation](https://www.lgsvlsimulator.com/docs/) on building maps but for edits you just need to re build the asset bundle and assign to the simulation.
