### ISSUE TITLE
How to load autoware_msgs? 

### ISSUE THREAD

**Issue by Amina88** [lgsvl/simulator#1029]
Hi guys, Im having issue publishing the data from topics for example vehicle cmd topic? $ rostopic echo /vehicle_cmd ERROR: Cannot load message class for [autoware_msgs/VehicleCmd]. Are your messages built? Any one has an ideas how to resolve this plzzzz. thank you
![120452847_253762439317696_878648868552781387_n](https://user-images.githubusercontent.com/9854362/94594185-5e3c9f00-0281-11eb-86f7-919573beb409.png)
@pedroexenberger any idea?

**Comment by EricBoiseLGSVL** [comment]
Any idea @cyberphysicalrobotics ?

**Comment by EricBoiseLGSVL** [comment]
@hadiTab adding you to ping @cyberphysicalrobotics

**Comment by hadiTab** [comment]
@Amina88 you can install autoware_msgs on your machine using `sudo apt install ros-$ROS_DISTRO-autoware-msgs`.
In general, if you are running Autoware inside a docker container and you want to inspect messages or launch a ros tool it is best to do that inside the same docker container.
