### ISSUE TITLE
Editing CubeTown Map in unity editor

### ISSUE THREAD

**Issue by asifsid-32** [lgsvl/simulator#1034]
Hello LGSVL team,

 Can anyone from the team please explain me how to get the mentioned file in the screen shot after building the code 

Filename - "enivronment_Moderncity" 
also what is the file format ?
![issue](https://user-images.githubusercontent.com/69885768/94683211-c2279c00-0343-11eb-8426-d01833073929.png)

**Comment by EricBoiseLGSVL** [comment]
@asifsid-32 file format is AssetBundle. This is a unity specific file format for engine assets.  You create a bundle from the Simulator -> Build...  Here you select the Assets/External/Environments/YourMap to build.  Make sure you don't build the binary at the same time or it takes a while.  Be aware that the first build will take a bit but following ones will be faster.  Also, be sure to have both windows and linux support because bundles are meant to be cross platform.

![BuildHelp00](https://user-images.githubusercontent.com/45106230/94707879-f1251a00-0311-11eb-92a4-970993b7bb5a.png)

**Comment by asifsid-32** [comment]
> @asifsid-32 file format is AssetBundle. This is a unity specific file format for engine assets.  You create a bundle from the Simulator -> Build...  Here you select the Assets/External/Environments/YourMap to build.  These are in the root of the source in the AssetBundles folder
> 
> ![BuildHelp00](https://user-images.githubusercontent.com/45106230/94708143-43663b00-0312-11eb-91c6-29cae063862c.png)
> 
> 

Sorry @EricBoiseLGSVL I didn't get you !! When we build the simulator we only have option for path where executable will build.. 

When I built the simulator I am not able to find environment_cubetown inside asset bundle.. 

What can be the issue here ??

**Comment by asifsid-32** [comment]
When i built the simulator from unity i get an asset bundle  folder with following files- 

![Screenshot (47)](https://user-images.githubusercontent.com/69885768/94712658-6a029100-0367-11eb-9525-241ceca8c562.png)

Also i got some files extracted from environment_CubeTown - 

![Screenshot (50)](https://user-images.githubusercontent.com/69885768/94712998-d7aebd00-0367-11eb-9121-05d8eb207466.png)

Any thing i am doing wrong ?

**Comment by asifsid-32** [comment]
@EricBoiseLGSVL any suggestions ?

**Comment by asifsid-32** [comment]
@EricBoiseLGSVL , @martins-mozeiko  What does navigate and save this to assetbundles means in the following screenshot - 
![Screenshot (51)](https://user-images.githubusercontent.com/69885768/94718818-e600d700-036f-11eb-92e4-94f2d0e427c4.png)

**Comment by asifsid-32** [comment]
> @EricBoiseLGSVL , @martins-mozeiko What does navigate and save this to assetbundles means in the following screenshot -
Which file do we have to save in this file path ?
> ![Screenshot (51)](https://user-images.githubusercontent.com/69885768/94718818-e600d700-036f-11eb-92e4-94f2d0e427c4.png)

**Comment by EricBoiseLGSVL** [comment]
That means in WebUI, when you are choosing the path for the map, save and paste to the map setup.

**Comment by EricBoiseLGSVL** [comment]
The file created is fine, that is what it should have.  Linux and windows textures/assets and a manifest.  Point WebUI at this file.  Why is the file name environment_CubeTown_Files?  It should be the same as the repo/asset name

**Comment by asifsid-32** [comment]
> The file created is fine, that is what it should have. Linux and windows textures/assets and a manifest. Point WebUI at this file. Why is the file name environment_CubeTown_Files? It should be the same as the repo/asset name

@EricBoiseLGSVL there was a zip file in assetbundle/environments/environment_CubeTown  which i extracted and showed you including linux and windows textures/assets and a manifest

**Comment by asifsid-32** [comment]
> That means in WebUI, when you are choosing the path for the map, save and paste to the map setup.

@EricBoiseLGSVL Sorry i am not aware of this step ....

**Comment by asifsid-32** [comment]
@EricBoiseLGSVL This is the zip file which is getting generated after the build inside the assetbundle/enviroments/ 
![Screenshot (52)](https://user-images.githubusercontent.com/69885768/94723870-08e2b980-0377-11eb-8105-ac51f5716ace.png)

**Comment by asifsid-32** [comment]
> @EricBoiseLGSVL This is the zip file which is getting generated after the build inside the assetbundle/enviroments/
> ![Screenshot (52)](https://user-images.githubusercontent.com/69885768/94723870-08e2b980-0377-11eb-8105-ac51f5716ace.png)

@EricBoiseLGSVL I solved the issue... We have to provide this zip file's path while adding new map 

Thanks for all the help :)

**Comment by EricBoiseLGSVL** [comment]
@asifsid-32 Excellent, glad to help :)
