### ISSUE TITLE
Can I know the vehicle parameter ?

### ISSUE THREAD

**Issue by Mojojojooo** [lgsvl/simulator#1042]
Hey, I need vehicle parameters to tune. eg: Vehicle Turn Radius. Can someone let me know or else where can I find it?

**Comment by EricBoiseLGSVL** [comment]
@Mojojojooo In VehicleSMI.cs.  You will need to tune the dynamics class in Editor.

**Comment by Mojojojooo** [comment]
Can I know the current dynamics of the car?

**Comment by EricBoiseLGSVL** [comment]
@Mojojojooo Sure, just read the VehicleSMI class, this is the simulated dynamics logic as well as the rigidbody settings and wheel collider settings on the vehicle prefab.  The dynamics was taken from an open source project from Jaguar, it's in the header of the class

**Comment by Mojojojooo** [comment]
@EricBoiseLGSVL Thank you.
