### ISSUE TITLE
Cannot load map

### ISSUE THREAD

**Issue by Jihwan-Seo** [lgsvl/simulator#105]
Hello, I’m a student and I’m trying to run Autoware with lgsvl_simulator. When I tried to use Rviz to view the map, but there is a problem that lanes are not loading. How can I solve this problem? Please anyone help me. Thanks.

### Expected Behavior
Map loaded from data with 734 lanes, and these are visualized in Rviz like the following picture
![image](https://user-images.githubusercontent.com/34577123/54415018-6801be80-473e-11e9-9664-b7d535ab3590.png)

 
### Actual Behavior
Map loaded from data with 1 lane, and immediately after that Rviz is closed with the following error (picture)
![image](https://user-images.githubusercontent.com/34577123/54415036-72bc5380-473e-11e9-9aa7-a108675dc468.png)

 
### Specifications
-	Ubuntu version: 16.04 LTS
-	ROS version: Kinetic
-	Autoware version: 1.10.0
-	Graphics card: NVIDIA RTX 2080 Ti
-	CUDA version: 10.0

**Comment by martins-mozeiko** [comment]
This error message about mismatched datatype/md5sum is very strange. How are you running rviz & Autoware? Do you launch both of them from inside of autoware docker container?

**Comment by martins-mozeiko** [comment]
You need to check you ROS environment. I'm not sure what is wrong with message type mismatch. This seems more of a general Autoware/ROS issue. Maybe you can try asking this question on Autoware support channels. Maybe @hakuturu583 can help here?

We only support our docker image with Autoware. As we are not developing for Autoware every day, we just set up whole Autoware & ROS environment in docker. Everything else related to Autoware setup is kind of out of scope of simulator.

**Comment by hakuturu583** [comment]
@martins-mozeiko I think @Jihwan-Seo's Autoware LaneArray message and Autoware Lane Array message in your simulator is not matched.

**Comment by hakuturu583** [comment]
@Jihwan-Seo I see.
local_trajectories topic type was changed, but Autoware rviz file still requires marker type.
So, it was conflicted.
If you use rviz file in Autoware master or develop branch, can you post issue to the Autoware??
