### ISSUE TITLE
How to simulate about autonomous driving?

### ISSUE THREAD

**Issue by Taiki02** [lgsvl/simulator#1050]
Hello, I'm master student. I'm interested in your nice lgsvl simulator!!

I have point cloud data of  a city and from the point cloud data I want to make HD map.  In addition, with your lgsvl simulator and autoware platform I will simulate autonomous driving .
Is it possible to do that things? I want you to tell me what kind of data and what procedure is needed to simulate automated driving in lgsvl.
If possible, I think I learn the operation about lgsvl simulator through the tutorial at first.  

When I started the default simulator, I operated the car manually and the simulation didn't run an automatic simulation. So, I ask the question.

**Comment by EricBoiseLGSVL** [comment]
@Taiki02 welcome to LGSVL Simulator.  Be sure to post specific questions to issues so we help others that are looking here.  We support multiple ways to simulate autonomous driving.  Make sure you have read the documentation on Autoware and LGSVL Simulator [here](https://www.lgsvlsimulator.com/docs/getting-started/).  Then we need to specify what version of Autoware you plan on using [here](https://www.lgsvlsimulator.com/docs/autoware-instructions/) and [here](https://www.lgsvlsimulator.com/docs/autoware-auto-instructions/).

There are quite a few steps to get Autoware working and you will need to be sure you are asking questions on running Autoware on their forums.  We will be happy to answer any questions on running LGSVL Simulator here (and try help with autoware questions when we can).

As for not being able to run the simulation, what problems are you having? Errors or crashes?  When posting issues it is best to state what OS, hardware, simulator version and AD stack type.  If you have errors, you will need to look for the Player.log Unity creates when running the application.  This logs errors and helps immensely in finding solutions quickly.
