### ISSUE TITLE
Simulator does not start on Ubuntu 18.04?

### ISSUE THREAD

**Issue by User-712** [lgsvl/simulator#1053]
Hi Team,

I tried to run the LGSVL Simulator on Ubuntu 18.04 system, but the simulator does not start. 
System Specifications:
OS: Ubuntu 18.04
Processor: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Graphics: llvmpipe(LLVM9.0, 256 bits)

![image](https://user-images.githubusercontent.com/71029042/95672657-628d8400-0bc0-11eb-9cd0-9cb3b333818e.png)

what might be the issue?

Thanks!

**Comment by martins-mozeiko** [comment]
`llvmpipe` means that it is using software rendering and does not have access to GPU rendering. Make sure that OpenGL & Vulkan can use GPU for rendering. Run `glxgears -info` and check that it shows your GeForce GPU under `OpenGL renderer string` - if it doesn't that means your X11 configuration does not allow access to GPU driver for rendering. Check the comments in #708 issue on how to run simulator with NoMachine.
