### ISSUE TITLE
LGSVL does not start on Ubuntu 18.04.

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#1057]
When starting the pre-compiled version downloaded from the release section it fails to start. I only get those messages and nothing else : 

```
$ ./simulator          
Set current directory to /home/maxandre/Downloads/lgsvlsimulator-linux64-2020.06
Found path: /home/maxandre/Downloads/lgsvlsimulator-linux64-2020.06/simulator
```
The process stops and nothing.

Specifications : 
 - Ubuntu 18.04
 - Ryzen 9 3900
 - RTX 2080 Super
 - Nvidia driver version: 450.51.06

A colleague at work has the same problem. Any idea ? 
Thanks

**Comment by EricBoiseLGSVL** [comment]
@MaxandreOgeret please post the player.log to help debug the issue.

**Comment by duongnxptit** [comment]
> @MaxandreOgeret please post the player.log to help debug the issue.

i have same problem like @MaxandreOgeret . Can you tell me where i can find  log file to show it for you?

**Comment by EricBoiseLGSVL** [comment]
@duongnxptit and @MaxandreOgeret Player.log [here](https://docs.unity3d.com/Manual/LogFiles.html)

**Comment by MaxandreOgeret** [comment]
@EricBoiseLGSVL Here's the content of the file :+1: 


```
Mono path[0] = '/home/maxandre/lgsvlsimulator-linux64-2020.06/simulator_Data/Managed'
Mono config path = '/home/maxandre/lgsvlsimulator-linux64-2020.06/simulator_Data/MonoBleedingEdge/etc'
Preloaded 'liblaszip.so'
Preloaded 'libpng.so'
Preloaded 'libsqlite3.so'
Preloaded 'libturbojpeg.so'
Display 0 '0': 1920x1080 (primary device).
Loading player data from /home/maxandre/lgsvlsimulator-linux64-2020.06/simulator_Data/data.unity3d
Unable to load player prefs
Desktop is 1920 x 1080 @ 60 Hz
Vulkan detection: 0
No supported renderers found, exiting
(Filename:  Line: 618)
```

Nvdia drivers are installed properly and working. Docker version works fine also.

**Comment by EricBoiseLGSVL** [comment]
@MaxandreOgeret Thanks for the log, this helps.  Looks like you need to install the nvidia drivers and force simulator application to use the GPU.  Please look at similar issue posts about like #1076 #879 #753 and documentation [here](https://www.lgsvlsimulator.com/docs/getting-started/)
