### ISSUE TITLE
Help me with path planning  in Autoware function 

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#106]
I want to use  path planning function to autoware_car on LGsimulator by autoware.
I followed below steps for it.

input:
   cd autoware/docker/generic
   ./build.sh kinetic

result:
   ![image](https://user-images.githubusercontent.com/17079475/54414215-bcf00580-473b-11e9-9540-84a640073682.png)

input:
		cd ~/autoware/docker/generic
		./run.sh kinetic	

result:		
![image](https://user-images.githubusercontent.com/17079475/54414236-d09b6c00-473b-11e9-8ff8-4ce61bc26b36.png)
![image](https://user-images.githubusercontent.com/17079475/54414238-d3965c80-473b-11e9-88b5-218ab200b62c.png)
![image](https://user-images.githubusercontent.com/17079475/54414243-d6914d00-473b-11e9-8b32-c96bfeb2b0a4.png)

Click on the 'Map' button for Autoware
![image](https://user-images.githubusercontent.com/17079475/54414251-db560100-473b-11e9-8c69-6428ea28bbfb.png)
![image](https://user-images.githubusercontent.com/17079475/54414253-dd1fc480-473b-11e9-9cd2-c876a3c2c85b.png)
The error was ignored.

Run Simulator
![image](https://user-images.githubusercontent.com/17079475/54414276-f32d8500-473b-11e9-8568-dfea366e62fe.png)

Click on the 'Sensing' button for Autoware
![image](https://user-images.githubusercontent.com/17079475/54414279-f759a280-473b-11e9-9eb7-8f9224a92241.png)

Click on the ‘Enable_LIDAR’ & ‘Enable_GPS’ button for Simulator
![image](https://user-images.githubusercontent.com/17079475/54414286-fcb6ed00-473b-11e9-8947-9d546653d602.png)
The LADAR has been modified to 64 Chenels and added two cameras.

Click on the ALL button for Autoware
![image](https://user-images.githubusercontent.com/17079475/54414292-03ddfb00-473c-11e9-829b-803e19f2ca61.png)

Specify '2D Nav Goal'
![image](https://user-images.githubusercontent.com/17079475/54414307-0b9d9f80-473c-11e9-909f-d572c911cecb.png)

result(Yellow sign)
![image](https://user-images.githubusercontent.com/17079475/54414319-16583480-473c-11e9-9e6e-c68aab5704b0.png)

Here has some problem that I couldn't see way point line(Orange) below the capture image unlike other user's case and path planning function doesn't work.
![image](https://user-images.githubusercontent.com/17079475/54414389-528b9500-473c-11e9-9288-14f04ad9371c.png)
└source: https://github.com/lgsvl/Autoware/blob/lgsvl_develop/docs/images/readme-rviz.png

computer spec
![image](https://user-images.githubusercontent.com/17079475/54414560-ebbaab80-473c-11e9-8997-d6bc90d99592.png)

**Comment by martins-mozeiko** [comment]
I think lane information is not displayed because it is still loading. Our current SanFrancisco map is pretty big for Autoware so it can take many minutes to actually load all map in rviz. Can you try waiting few minutes before specifying 2D nav goal?

Another option is to load our previous vector map map which will have smaller area. You can go to shared_dir folder and checkout one of previous commits from [autoware-data](https://github.com/lgsvl/autoware-data) repository. Try using `93d92d6becc8dbced0a588aadcf0cee18e2c2429` or `e3cfe709e4af32ad2ea8ea4de85579b9916fe516` commits.

**Comment by ehduk90** [comment]
No matter where the 2D Nav Goal is, this is the result.
![image](https://user-images.githubusercontent.com/17079475/55459196-f07ecb00-5629-11e9-8e87-da2518aff5e1.png)

**Comment by ehduk90** [comment]
No matter where the 2D Nav Goal is, this is the result.
![image](https://user-images.githubusercontent.com/17079475/55459445-8a467800-562a-11e9-8ee4-1a8d4bc0a857.png)
If the 2D Nav Goal is specified in the green area(very short path plannig), the first time the vehicle stops normally after driving.
However,
 1. Try to return to the starting point from the target point.
 2. Look ahead distance is put behind the vehicle.

───────────────────────────────────────────────────────────────
![1](https://user-images.githubusercontent.com/17079475/55524334-f2976700-56c7-11e9-8605-d0074651e189.gif)

![2](https://user-images.githubusercontent.com/17079475/55524336-f3c89400-56c7-11e9-918c-8fa8fe2857ad.gif)

![3](https://user-images.githubusercontent.com/17079475/55524338-f4f9c100-56c7-11e9-8d5f-6d14c8c83175.gif)

**Comment by martins-mozeiko** [comment]
Did you try checking out autoware map from commit I wrote above?
I think your issue is that VectorMap is not loading into rviz. Not sure why... Are you using Autoware from our docker container? Or have you built something else from master (maybe something change there).

**Comment by ehduk90** [comment]
Yes, I used the things you suggested.

I've tried  3 versions of "autowere". One version was from LG and the other two, the latest and the older versions, were from autowere site

**Comment by ehduk90** [comment]
It's working normally now.
The used version is 824d8f2047caaea 983372cbeb107ea1201509e36c
