### ISSUE TITLE
How to colorize the Shalun map

### ISSUE THREAD

**Issue by kotakky** [lgsvl/simulator#1060]
I'm learning editing annotation from tutorial of "map annotation".
・I cannot understand which folder's data I should edit for annotation's change(Shalun All or Map Shalun).
・I cannnot understand the above two data's role and difference.
So,I want to tell you answer the two questions
![map_annotaion3](https://user-images.githubusercontent.com/45957491/95979282-5c183a00-0e56-11eb-85ba-e46e34273fe0.JPG)
.

**Comment by EricBoiseLGSVL** [comment]
@kotakky ShalunAll is the holder object for the map meshes.  If you select this object, you can see the meshes highlight in the scene view panel.  The MapShalun is the annotation holder.  This holds the annotation objects with the annotation classes attached.
