### ISSUE TITLE
Lane following new docker image with ros2-lgsvl-bridge

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#1064]
I'd like to request new lanefollowing docker image with ros2-lgsvl-bridge. Current version uses the old ros2-web-bridge. Is it possible to change that and upload a new image, please? Thanks.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 Thanks for the heads up.  We will try to update this soon

**Comment by EricBoiseLGSVL** [comment]
@lishammel can you add this please?

**Comment by lishammel** [comment]
Will do.

**Comment by daviduhm** [comment]
Hi @dr563105, the docker image for the lane following model has been updated with ros2-lgsvl-bridge and is available in Docker hub here: https://hub.docker.com/r/lgsvl/lanefollowing
