### ISSUE TITLE
How to use g29 steering wheel on windows

### ISSUE THREAD

**Issue by pdcxs** [lgsvl/simulator#1068]
I buy a g29 steering wheel, but the simulator cannot detect it. I'm on windows platform, the drivers is properly installed. I have tried rebuild the simulator from source codes, but the vehicle still cannot be controlled by the g29 steering wheel.

Is there any simple method to enable g29 controller?

**Comment by EricBoiseLGSVL** [comment]
did you add the WheelControlSensor [here](https://www.lgsvlsimulator.com/docs/sensor-json-options/#wheel-control)?

**Comment by pdcxs** [comment]
> did you add the WheelControlSensor [here](https://www.lgsvlsimulator.com/docs/sensor-json-options/#wheel-control)?

Yes, I've already added WheelControlSensor in the vehicle sensor settings.

**Comment by EricBoiseLGSVL** [comment]
@pdcxs I have seen Unity not be able to recognize the wheel, are you able to open the Editor and then the InputSystem debug.  You should see the wheel in this menu.  If not you may still have driver issues
![WheelHelp00](https://user-images.githubusercontent.com/45106230/96298003-bbde2480-0fbf-11eb-8489-540370e50654.png)

**Comment by pdcxs** [comment]
> @pdcxs I have seen Unity not be able to recognize the wheel, are you able to open the Editor and then the InputSystem debug. You should see the wheel in this menu. If not you may still have driver issues
> ![WheelHelp00](https://user-images.githubusercontent.com/45106230/96298003-bbde2480-0fbf-11eb-8489-540370e50654.png)

Yes, in the Unity editor, the steering wheel is in the device list. But still, the vehicle in the simulator has no response for the steering wheel input.

**Comment by EricBoiseLGSVL** [comment]
- Double click the wheel in the Input Debugger and see if the inputs are being received
- If so, screen shot the vehicle with the wheel control sensor attached
- Check the console panel to see if there are any errors and post them if so
- We will need more info to debug this, please add debug logs to capture input in Wheel control sensor and post the player.log to see if inputs are being received at runtime.

**Comment by pdcxs** [comment]
> * Double click the wheel in the Input Debugger and see if the inputs are being received
> * If so, screen shot the vehicle with the wheel control sensor attached
> * Check the console panel to see if there are any errors and post them if so
> * We will need more info to debug this, please add debug logs to capture input in Wheel control sensor and post the player.log to see if inputs are being received at runtime.

I double click the wheel in the input debugger, but nothing has happened. I try to double click the keyboard and mouse, a little window will pop up, but the wheel not show this window. So, is this the problem of the driver?

**Comment by pdcxs** [comment]
I find when I double click the wheel, it reports that "NotImplementedException: Reading int stradding int boundary"
![QQ截图20201020153716](https://user-images.githubusercontent.com/3760797/96555425-599c6100-12ea-11eb-8071-7cd98e97e5fc.png)

**Comment by EricBoiseLGSVL** [comment]
Yes, this seems like an issue with the driver.  Do you have the logitec software installed, not just drivers?  If not I would remove drivers and just use software to install correct drivers

**Comment by pdcxs** [comment]
I'm tired of trying fix this problem. I just write a little code, first read the inputs of the G29 with pygame_sdl2 and then use the inputs to control the vehicles. Thanks for your answers any way.
