### ISSUE TITLE
How can a radar sensor attached to autoware_car?

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#107]
I copied the radar sensor from the lgsvl vehicle and pasted it into the autoware_car and set it as follows:
![image](https://user-images.githubusercontent.com/17079475/54415104-9bdce400-473e-11e9-88c5-d92c08dfec19.png)
![image](https://user-images.githubusercontent.com/17079475/54415108-9da6a780-473e-11e9-94b2-3664d339dafb.png)

By the way, sensor effects are not visible in the simulator, and they are not on topics.
![image](https://user-images.githubusercontent.com/17079475/54415132-b4e59500-473e-11e9-886e-dc612264fa76.png)

**Comment by martins-mozeiko** [comment]
You will need to edit Radar sensor to support Autoware. Current implementation of Radar publishes ROS message with Apollo protobuf message type. Autoware does not understand Apollo messages. You will need to understand what ROS message type Autoware expects/needs, and then prepare data in this format.

Sending radar data to Apollo is done in [RadarSensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/RadarSensor.cs#L251) file. You can see example of how to prepare ROS message differently for Apollo or Autoware in [ImuSensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/ImuSensor.cs#L123) file.
