### ISSUE TITLE
New ego vehicle is stuck and doesn't move during simulation. 

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1072]
Hi, I am running on 2020.06 release and I have just created a new ego vehicle starting from the Jaguar2015XE reference model, following all the steps (Unity 2019.3.15f1). 
As I start the simulation though, the vehicle can't move, neither with keyboard control nor with G920 Steering wheel (I have added both the sensors to the vehicle). All components and features seems to be exactly the same as the Jaguar, but still I have this problem. 

PS: I have checked and with other vehicles I have no problems.

**Comment by EricBoiseLGSVL** [comment]
You most likely do not have the axles set right in the VehicleSMI.cs, please check this.
You also may have moved or edited the wheels and their pivots are not correct.  Please highlight these elements in the scene view in the editor and post screen shots so we can see.

**Comment by nike-96** [comment]
![Screenshot 2020-10-20 093930](https://user-images.githubusercontent.com/71270688/96555905-a109f980-12b8-11eb-8829-c0fb9af73e4f.png)
![Screenshot 2020-10-20 094019](https://user-images.githubusercontent.com/71270688/96555913-a404ea00-12b8-11eb-9889-677ae2de64fe.png)
![Screenshot 2020-10-20 094038](https://user-images.githubusercontent.com/71270688/96555921-a5cead80-12b8-11eb-9e03-dfdfaec66f46.png)
![Screenshot 2020-10-20 094059](https://user-images.githubusercontent.com/71270688/96555925-a6ffda80-12b8-11eb-9f8f-0e655ef44e16.png)
![Screenshot 2020-10-20 094114](https://user-images.githubusercontent.com/71270688/96555928-a7987100-12b8-11eb-9d4f-96c41ee61c76.png)

Here they are, the axles of VehicleSMI.cs and all the wheels. I still can't find the issue, I hope you can help me.

**Comment by EricBoiseLGSVL** [comment]
Please highlight these elements in the scene view in the editor and post screen shots so we can see like so
![PanelHelp00](https://user-images.githubusercontent.com/45106230/96603541-1deda100-12c2-11eb-8d65-fd4b92adb4d8.png)
![EGOHelp00](https://user-images.githubusercontent.com/45106230/96603549-204ffb00-12c2-11eb-9aa1-9493c0106b18.png)
![EGOHelp01](https://user-images.githubusercontent.com/45106230/96603554-2219be80-12c2-11eb-8746-fbab705c4e3c.png)
![EGOHelp02](https://user-images.githubusercontent.com/45106230/96603559-234aeb80-12c2-11eb-8f10-591a541b5bc0.png)

Another thing, be sure to tag the top object Player and the Layer and all children Agent like so
![EGOHelp03](https://user-images.githubusercontent.com/45106230/96603866-73c24900-12c2-11eb-8334-7cd4659db71a.png)

**Comment by nike-96** [comment]
Here you go 
![Screenshot 2020-10-21 092836](https://user-images.githubusercontent.com/71270688/96687582-679cc100-1380-11eb-9ec9-fc01687c7318.png)
![Screenshot 2020-10-21 093008](https://user-images.githubusercontent.com/71270688/96687589-68355780-1380-11eb-9af7-765f1415d505.png)
![Screenshot 2020-10-21 093044](https://user-images.githubusercontent.com/71270688/96687600-6a97b180-1380-11eb-8d3a-6a9bea2d346c.png)
![Screenshot 2020-10-21 093153](https://user-images.githubusercontent.com/71270688/96687604-6bc8de80-1380-11eb-91e5-c05f3c2507d9.png)
![Screenshot 2020-10-21 093236](https://user-images.githubusercontent.com/71270688/96687608-6c617500-1380-11eb-9636-a6d5248f0004.png)

**Comment by EricBoiseLGSVL** [comment]
This is a problem.  Why is the center pivot so far off?
![EGOHelp04](https://user-images.githubusercontent.com/45106230/96738839-23fc8400-138d-11eb-82e8-795daa991802.png)

Please look at how the original ego is created.  You can drag it in scene to compare to the one you created.
![EGOHelp05](https://user-images.githubusercontent.com/45106230/96738945-4098bc00-138d-11eb-8e7b-57edc758bedf.png)
![EGOHelp06](https://user-images.githubusercontent.com/45106230/96738947-42627f80-138d-11eb-9a69-c08b1571a5d8.png)
![EGOHelp07](https://user-images.githubusercontent.com/45106230/96738954-442c4300-138d-11eb-8fc6-f1cbb30d7bb2.png)

You need meshes and holder object for wheel colliders zero'd to parent.  Please check this for body and wheel collider holder.

**Comment by nike-96** [comment]
I did check the meshes but I didn't find anything strange. If you look at the center pivot of the Jaguar2015XE.prefab, it is in the same position as the mine one. I didn't understand your suggestion probably.

**Comment by EricBoiseLGSVL** [comment]
From your image, the vehicle mesh is not aligned at the parents origin.  You can see the gizmo.  This makes me think other children are not aligned.  Please each gameobject in the hierarchy to make sure they are at origin.  (vehicle mesh and wheel collider holder)

**Comment by nike-96** [comment]
![Screenshot 2020-10-22 120308](https://user-images.githubusercontent.com/71270688/96856815-a0ab6300-145e-11eb-980e-e38165a20962.png)

This is the original ego vehicle of the Jaguar, I just re-cloned it from git-hub to be sure but as you can see the pivot is in a different position from yours one. Where did you take the vehicle model? From https://github.com/lgsvl/Jaguar2015XE/tree/master ?

**Comment by nike-96** [comment]
I have found the issue. I had followed the step 14 of https://github.com/lgsvl/simulator/issues/401, but not for the root of the prefab. Indeed, it was empty. After properly changing it, it worked. Thank you so much for the support.

**Comment by EricBoiseLGSVL** [comment]
No problem, glad to help.  FYI we have a youtube video [here](https://youtu.be/R_Z65kimCII) for steps and we will be updating our docs on this very soon.
