### ISSUE TITLE
How to do the "Render Pipeline" if there is no .mat files in the custom assets

### ISSUE THREAD

**Issue by qiongwu1003** [lgsvl/simulator#1074]
System : Win10
Unity version : 2019.3.15f1
Simulator code version : master

I export a map scene from RoadRunner, the exports includes a Filmbox (.fbx) file containing the 3D objects in a scene along with an additional XML file to hold extra data for materials and traffic signals in the scene.
On the Unity side, a set of scripts are included in the RoadRunnerUnityTool asset package to help import the FBX® file using the information stored in the XML file. The script handles the following details:
 Setting up materials
 Adding colliders to roads and terrain
 Setting up the components of traffic signals

The scene imported using the RoadRunnerUnityTool plugin and works fine in a normal Unity project, but when imported into the simulator project they become pink. 

I saw it needs to do "Render Pipeline" thing in [here](https://github.com/lgsvl/simulator/issues/666).  But there is no .mat files in my scene assets. Is there another way to do that?

I am attaching pictures to help explain the situation better.

In the normal Unity project:
![image](https://user-images.githubusercontent.com/65001214/96544356-01a92e80-12d9-11eb-91d1-ed738c4c7466.png)

In the simulator project:
![image](https://user-images.githubusercontent.com/65001214/96544439-2a312880-12d9-11eb-91a9-5625a993a099.png)

Ps : when I search "All Materials" I can see bellow : 
![image](https://user-images.githubusercontent.com/65001214/96544494-4208ac80-12d9-11eb-91da-bdf3d698d51e.png)

Any tips or help on this would be great, Thanks!

**Comment by EricBoiseLGSVL** [comment]
Roadrunner does not support HDRP shaders and this is why the materials are pink.  If you use roadrunner, you will need to the conversion manually and it is not easy.  We also do not support the other RoadRunner features, e.g., custom signal lights
- Export imported meshes materials here to a Materials folder right next to mesh
![RRHelp00](https://user-images.githubusercontent.com/45106230/96604472-285c6a80-12c3-11eb-9aac-4267f9313f53.png)

- Then convert materials to HDRP like so and reassign Textures and values.  Roadrunner does not support HDRP and shaders are very different.  All these material parameters will need to be adjusted.
![RRHelp01](https://user-images.githubusercontent.com/45106230/96604743-71acba00-12c3-11eb-8325-68824ef8301c.png)

- Again, RoadRunner is using old Unity render pipeline and is not supporting HDRP, you will need to manually make the conversions.  Also, RR uses multiple meshes and materials with lots of alpha for roads, lines, oil marks, etc.  This is not performant for game engines, causes issues with alpha clipping and has many issues using LGSVL Simulator features.  We expect one mesh with one material for road surfaces.  Then, we use Unity's new shader graph shader to apply wetness, puddles, intensity and damage onto this one mesh.  This is more performant and looks more realistic.

- I recommend cleaning up the mesh in Maya or Blender and setting default Unity shaders before importing in Simulator projects.  This gives you more control and you can cleanup the multiple meshes and materials.
- If this is not possible, then I recommend using our HDMap importer that then can convert the map to a mesh.  Then you can add decoration to the environment.

**Comment by qiongwu1003** [comment]
Thanks for your reply.

And I tried the HDMap importer way.

step1: Export OpenDRIVE(.xodr) file from RoadRunner.
step2: Import the OpenDRIVE file to simulator. And I referenced [this](https://www.youtube.com/watch?v=bZk5kY-YgEM) vedio.
           There is nothing but only the MapSignal in the scene, and with errors. Does that mean the RR OpenDRIVE file can not be used in the simulator?
![image](https://user-images.githubusercontent.com/65001214/96670753-beab9180-1392-11eb-9836-2d366ce78387.png)

Plus, in my simulator there is no "Build HD Map Mesh" item, how do i fix it?
![image](https://user-images.githubusercontent.com/65001214/96670971-514c3080-1393-11eb-956e-d1148bd57a6b.png)

Thanks.

**Comment by luqiang21** [comment]
@qiongwu1003 I see you are using code from `master` branch which is not the latest release. You should use branch `release-2020.06` for the most recent release. You should be able to find `Build HD Map Mesh` button in the simulator.

**Comment by qiongwu1003** [comment]
@luqiang21 Thanks your reply, I will try the release-2020.06 code. And about the "HDMap importer" question, any suggestion?

**Comment by luqiang21** [comment]
@qiongwu1003 We have several fixes for the HD map importer, you can try it as well. Let me know if you still have problems.

**Comment by qiongwu1003** [comment]
@luqiang21 
Hi, I tried the release-2020.06 code,  and I imported the map success. But I still can  not find the "Build HD Map Mesh" item.
And i also checked the "simulator\Assets\Scripts\Editor" path, there is no file about "Build HD Map Mesh" item. 

![image](https://user-images.githubusercontent.com/65001214/96828732-bcb50180-146a-11eb-9dc8-f52c851e57a0.png)

Thanks.

**Comment by luqiang21** [comment]
@qiongwu1003 That's great to hear you can import the HD map. Sorry I was mistaken that as you can in the title of the [video](https://www.youtube.com/watch?v=bZk5kY-YgEM), Build Mesh from HDMap is one of premium features which you need to contact our team (contact@lgsvlsimulator.com) for more details if you want to try or use it.

**Comment by qiongwu1003** [comment]
@luqiang21 Thank you very much. And there is no more question.
