### ISSUE TITLE
Map data

### ISSUE THREAD

**Issue by SkylerJin** [lgsvl/simulator#108]
Hi,

I know how to create a small map, but I am not sure how the San Francisco map is created with exact correct coordinate(I mean x, y, z coordinate for each object in reality). Do you use point cloud data for reference?

Thank you.

**Comment by martins-mozeiko** [comment]
The map was created as part of [GENEVI vehicle simulator](https://github.com/GENIVI/genivi-vehicle-simulator) project. I'm not sure what was their workflow for creating this.

Currently we are developing process that will allow using point cloud as input/reference for map to be created. This is still work in progress and I'm not sure when this will be ready.

I can suggest you to take screenshot of map from any mapping application (such as Google Maps), and then apply this image as texture on a horizontal plane inside Unity. This will allow you to see where to place other objects/obstacles to have same placement as real world. If you need more complex 3d geometry then you should import this texture into any 3d modelling software (maya, 3dsmax, blender...) and proceed creating environment there before importing result into Unity.
