### ISSUE TITLE
How to change the message type of GPS on ROS2?

### ISSUE THREAD

**Issue by francis0407** [lgsvl/simulator#1084]
https://www.lgsvlsimulator.com/docs/simulator-messages/#ros2-message-types mentions that the simulator supports both `nmea_msgs/Sentence` and `sensor_msgs/NavSatFix` message types for GPS.

Currently, the default message type of the GPS on ROS2 is `sensor_msgs/NavSatFix`. So, how to change this message type to `nmea_msgs/Sentence`?

**Comment by dr563105** [comment]
You would need change 3 files -- Ros2Conversions, GpsData, and Ros2BridgeFactory.

[This file](https://github.com/lgsvl/simulator/blob/release-2020.06/Assets/Scripts/Bridge/Ros2/Ros2Conversions.cs#L245) has to be changed to use `nmea_msgs/Sentence`. You need to assign variables to the structures defined in [here](https://github.com/lgsvl/simulator/blob/release-2020.06/Assets/Scripts/Bridge/Data/GpsData.cs#L12). You need to change that class to reflect Sentence data type. You can either replace or add new class structure. 

Then add that class definition type [here](https://github.com/lgsvl/simulator/blob/release-2020.06/Assets/Scripts/Bridge/Ros2/Ros2BridgeFactory.cs#L40)

I think these changes are enough to help your need. There may be some other problems.

**Comment by francis0407** [comment]
@dr563105  Thanks!
