### ISSUE TITLE
Error when starting simulation: VehicleOdometryData used for publisher in ROS2 bridge

### ISSUE THREAD

**Issue by sgermanserrano** [lgsvl/simulator#1085]
Hi,

I'm trying to run a simulation using the lgsvl simulator and the ROS2 bridge using the `Lexus2016RXHybrid (Autoware)` Vehicle. 
I have updated the sensors on the default vehicle with the settings from [AutowareAuto lgsvl-sensors.json](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/lgsvl-sensors.json) but when trying to run the simulation I get the following error message: 
```
Invalid: Unknown data type VehicleOdometryData used for publisher in ROS2 bridge
```

Below is a screenshot of the error message.

![Screenshot from 2020-10-22 10-51-43](https://user-images.githubusercontent.com/43142004/96855926-4bb71f00-1455-11eb-94d4-7549ab75ff97.png)

**Comment by EricBoiseLGSVL** [comment]
@hadiTab any idea?  Is VehicleOdometrySensor using old ROS2 bridge?

**Comment by hadiTab** [comment]
@sgermanserrano the VehicleOdometry message isn't supported by the bridge in that release (but we will be bringing it back). If you don't care about getting vehicle odometry data you can just remove the Vehicle Odometery sensor from the vehicle's JSON configuration and things should work.

**Comment by sgermanserrano** [comment]
@hadiTab thanks for the info. yeah, I just removed it for the time being.

**Comment by nnmm** [comment]
@hadiTab @EricBoiseLGSVL I have the same problem. When will the next release be, and is there a way to get the functionality back now (e.g. by building some development branch)?

**Comment by EricBoiseLGSVL** [comment]
@nnmm You can update the bridge and add back the VehicleOdomData conversions, then make a new build.

in RosConversions.cs
```
public static Lgsvl.VehicleOdometry ConvertFrom(VehicleOdometryData data)
        {
            return new Lgsvl.VehicleOdometry() // not in 06 release
            {
                header = new Ros.Header()
                {
                    stamp = ConvertTime(data.Time),
                },
                velocity = data.Speed,
                front_wheel_angle = UnityEngine.Mathf.Deg2Rad * data.SteeringAngleFront,
                rear_wheel_angle = UnityEngine.Mathf.Deg2Rad * data.SteeringAngleBack,
            };
        }
```

VehicleOOdometryData.cs
```
namespace Simulator.Bridge.Data
{
    public class VehicleOdometryData
    {
        public double Time;
        public float Speed; // in meters per second
        public float SteeringAngleFront;
        public float SteeringAngleBack;
   }
}
```

in RosBridgeFactory.cs
```
typeof(VehicleOdometryData),
```

This is all the conversions I can find but I'll need @hadiTab to confirm.  We are working to get the release out as soon as possible.

**Comment by manonechu** [comment]
Hi @EricBoiseLGSVL, I am having a similar issue, please take a look at the screenshots. I checked the RosConversions.cs, it contains the DetectedRadarObjectData. Could you please advise me? Thanks a lot!
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/19791379/111019052-65b0ba00-8382-11eb-9603-ff1f8d2838d4.png)
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/19791379/111019057-6b0e0480-8382-11eb-851e-60c60b29c436.png)
![Kazam_screenshot_00002](https://user-images.githubusercontent.com/19791379/111019058-6f3a2200-8382-11eb-8c12-1262f0144955.png)

**Comment by EricBoiseLGSVL** [comment]
@manonechu what do you mean you are having similar issues?  Are the Radar msg not working with ROS2 bridge? @hadiTab is this supported?

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your reply. I added Radar to the JSON just like I added GPS Device and IMU on Vehicles, when I continued to the Simulations and clicked the green play button, it showed me "Invalid: Unknow data type DetectedRadarObjectData used for publisher in ROS2 bridge".

**Comment by EricBoiseLGSVL** [comment]
Yes, you will need to add the bridge conversions for ROS2 since the RadarSensor does not support

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your reply. Would you be able to share any tutorials for adding the bridge conversions for ROS2? I was checking the RosConversions.cs, it contains the DetectedRadarObjectData already. Thanks a lot!

**Comment by EricBoiseLGSVL** [comment]
Sure, we will try to get some information on how to do this.  We are trying to get the new release out, but after that we will look into more detailed docs.

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your rapid reply. Sounds great! I am really looking forward to it. Are there any workaround methods I can do now? Because I have to use the Radar sensor for simulation.

**Comment by EricBoiseLGSVL** [comment]
sure look to the above code posted and find all references to the bridge type and add the conversions.

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your reply. 
I followed the above code and rebuilt it. Now it doesn't show any error when I run the simulation. But when I do "ros2 topic echo /radar", the objects array is empty. Please see the attached screenshot. I am not sure why. Do I need to turn on anything? Thanks a lot. I am looking forward to your help!
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/19791379/111403498-12e54400-869b-11eb-9d45-ae7f20495451.png)

**Comment by EricBoiseLGSVL** [comment]
No radar should show the vehicle in a bounding box.  This is a bug that we have fixed in the next release.  Change this:
```
var npcC = mesh.gameObject.GetComponentInParent<NPCController>();
var va = mesh.GetComponent<VehicleActions>();
```
to this
```
var npcC = mesh.GetComponentInParent<NPCController>();
var va = mesh.GetComponentInParent<VehicleActions>();
```
not sure on line numbers because I did some formatting fixes to the class

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you very much for your help!
I did the above change and rebuilt it, now I can see both vehicles in bounding boxes. However, when I did "ros2 topic echo /radar", there is nothing getting published. Before I made this change, the vehicles were not in bounding boxes, but the /radar topic got published though the objects array was empty, please see above: https://github.com/lgsvl/simulator/issues/1085#issuecomment-800736914.
Could you give me some instructions on this issue? Thank you again. I am looking forward to your reply. 
![Screenshot 2021-03-17 20:59:40](https://user-images.githubusercontent.com/19791379/111562810-d0883980-8764-11eb-9490-b03ca83b0dd1.png)

**Comment by EricBoiseLGSVL** [comment]
Hmm, not sure why the data would stop sending.  Can you debug the objects array and see if the data matches the ros2 conversion methods?

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you very much for your help.
![Screenshot 2021-03-18 21:23:17](https://user-images.githubusercontent.com/19791379/111722802-8f5d5b80-8830-11eb-9b16-5608cc486db5.png)
![Screenshot 2021-03-18 21:21:47](https://user-images.githubusercontent.com/19791379/111722807-8ff5f200-8830-11eb-893c-5b35f4230d38.png)
I followed your instructions by making the two changes, as shown in the above two screenshots.
The Ros2Conversions.cs seems right to me, as shown in the below screenshot. Are there any places I need to make changes? Thanks a lot!
![Screenshot 2021-03-18 21:24:24](https://user-images.githubusercontent.com/19791379/111722921-be73cd00-8830-11eb-8abc-8ea70b0977b6.png)

**Comment by EricBoiseLGSVL** [comment]
Can you debug the radar Detected dictionary? That way you can see if the issue is with the sensor or the bridge.

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your reply. What is this radar Detected dictionary for? Where can I locate this dictionary? Thank you!

**Comment by EricBoiseLGSVL** [comment]
It's called detected
```
private Dictionary<Collider, DetectedRadarObject> Detected = new Dictionary<Collider, DetectedRadarObject>();
```

**Comment by manonechu** [comment]
@EricBoiseLGSVL, thank you for your reply. I did a careful check but couldn't find any bugs.
When will the new version be released? Thank you!

**Comment by EricBoiseLGSVL** [comment]
No problem, we are finalizing docs now, very soon ;)

**Comment by MisterioRemo** [comment]
@manonechu hello!
I have the same problem with radar sensor.
In `Lgsvl.DetectedRadarObjectArray ConvertFrom(DetectedRadarObjectData data)` function in Ros2Conversions.cs I change this 
```c#
var r = new Lgsvl.DetectedRadarObjectArray()
{
   header = new Ros.Header()
  {
      stamp = Convert(data.Time),
      frame_id = data.Frame,
   },
};
```
to this
```c#
var r = new Lgsvl.DetectedRadarObjectArray()
{
   header = new Ros.Header()
  {
      stamp = Convert(data.Time),
      frame_id = data.Frame,
   },
   objects = new List<Lgsvl.DetectedRadarObject>()
};
```
And now radar topic works correctly.

**Comment by EricBoiseLGSVL** [comment]
@MisterioRemo We have changed the sensor in the next release with something similar.  Thanks for the fix in the meantime, sorry for the confusion, we didn't realize this was missing.

**Comment by manonechu** [comment]
@MisterioRemo, thank you! It works for me now.
