### ISSUE TITLE
Problem with fmu vehicle 

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1086]
Hi, I followed the procedure at https://www.lgsvlsimulator.com/docs/ego-vehicle-dynamics/ to use an fmu vehicle, but I have a problem at the WebUI. After I have added the new vehicle, the simulation doesn't start sending the following error. 
![Screenshot 2020-10-22 160146](https://user-images.githubusercontent.com/71270688/96882757-ec223900-147f-11eb-97a6-594bd76ff3fe.png) 
In the documentation there is nothing about the creation of a zip. I tried to put the assetbundle of the vehicle in a zip with all the files which are contained in Assets\External\Vehicles\FMU\ExampleFMU (through which there is the .dll file which is required in the error message) but another error comes up: 
![Screenshot 2020-10-22 160406](https://user-images.githubusercontent.com/71270688/96883243-7bc7e780-1480-11eb-8be2-f4fc07aeeef5.png)
I don't know what this error is about, can you help me? 
Thanks

**Comment by EricBoiseLGSVL** [comment]
@nike-96 ExampleFMU.dll should be in the Resources folder.  This looks like a bug and we will look into it.  Thanks for letting us know.

**Comment by nike-96** [comment]
Ok, let me know if you guys solve the issue.

**Comment by nike-96** [comment]
Hi, I wanted to see the dll file so I opened it with VisualStudio and it appears like this. It seems to contain another folder (which I can't open or doing anything else); anyway it's an empty file I think and this could be the reason behind the error I get. 

![Screenshot 2020-10-26 123243](https://user-images.githubusercontent.com/71270688/97167642-74a61f80-1787-11eb-8807-f1ac985421c7.png)

**Comment by nike-96** [comment]
Hi, did you manage to solve the issue?

**Comment by EricBoiseLGSVL** [comment]
Sorry, still looking into it.  We have added it to the backlog to fix.  I'll update here once we have a fix

**Comment by nike-96** [comment]
Any chance you solved this? Thanks

**Comment by EricBoiseLGSVL** [comment]
we are still looking into it.  Sorry, next release is going to be big :)

**Comment by EricBoiseLGSVL** [comment]
@nike-96 I have reviewed the code and it seems a refactor broke this.  I'll see if I can fix today or tomorrow.  I'll post code here and next release will have the fix.

**Comment by nike-96** [comment]
Ok thank you!

**Comment by EricBoiseLGSVL** [comment]
@nike-96 Ok all fixed.  Looks like Build.cs was missing the vehicle name folder to parse for the fmu and I also fixed a the example FMU class having odd list display issues.  Here is the patch file.  This fix will also be in the next release.  Thanks for finding this bug.

[patch.zip](https://github.com/lgsvl/simulator/files/5823270/patch.zip)

**Comment by nike-96** [comment]
Thank you for your support! Is that file describing what we need to change (.diff) in the old Build.cs?

**Comment by nike-96** [comment]
Furthermore, do you happen to know the date of the next release?

**Comment by EricBoiseLGSVL** [comment]
@nike-96 yes the diff is the changes needed.  The path is missing the name of the vehicle and the other is just fixing issues displaying the axle info in the editor.  FYI, the ExampleFMU is very rough just to show how to implement base functionality.  Release is set for Feb.
