### ISSUE TITLE
Can not see the mesh clearly after importing fbx file.

### ISSUE THREAD

**Issue by wangludong** [lgsvl/simulator#1088]
Hi there
I'd like to make a annotation for my map.
But when I dragged the fbx into the scene for reference, I only saw a vague contour of my mesh.

![vague](https://user-images.githubusercontent.com/167162/96946064-eb39e780-1511-11eb-8906-72f09f29e135.JPG)

While I created a new project and dragged the same fbx, I can see the details clearly.

![clear](https://user-images.githubusercontent.com/167162/96946162-23412a80-1512-11eb-94df-c386ebaddff5.JPG)

So what is the problem here?

**Comment by EricBoiseLGSVL** [comment]
If you are creating a mesh and importing into Simulator, materials need converted to HDRP.  When you select the mesh materials, are they pink?

**Comment by wangludong** [comment]
@EricBoiseLGSVL 

Thanks for your answer.
Actually, I've already turned the lighting on before, but it had no effect.
You can see I added a Directional Light into the scene.
But I noticed that the light attributes here are quite different from those in the new project.
And when I zoomed in for a specific level, the mesh began to blur, even disappeared and only my annotation left.
![vague2](https://user-images.githubusercontent.com/167162/97249790-86e39480-183f-11eb-8933-07333f1c77a9.JPG)
![clear2](https://user-images.githubusercontent.com/167162/97249801-8ba84880-183f-11eb-9a38-8c716498f191.JPG)

**Comment by EricBoiseLGSVL** [comment]
Can you open the mesh in the inspector panel to see the material and shader being used?  Is your mesh just lines?  Did you export the materials in the fbx importer and convert to HDRP materials?

**Comment by wangludong** [comment]
In fact I don't have the original mesh file.
What I did is exporting the mesh from a Unreal Engine asset without choosing any option, since there are no options.
To be honest I'm not familiar with Unity, so I'm not quite sure about you mentioned here about material and shader.
From the picture below you can see the properties of the mesh in two projects.

![vague3](https://user-images.githubusercontent.com/167162/97394132-3a22bb00-191e-11eb-887a-0e57c5307250.JPG)
![clear3](https://user-images.githubusercontent.com/167162/97394246-40b13280-191e-11eb-883d-bdc4dbaaccaa.JPG)

By the way, I also take a snap of the mesh in Unreal Engine.
Hope this will be helpful.

![ue snap](https://user-images.githubusercontent.com/167162/97395049-05633380-191f-11eb-97ca-893f31b74918.JPG)

**Comment by wangludong** [comment]
Well, I find a makeshift method.
As I toggle off the scene lighting, it looks clearer.
So that's it.Thank you.
