### ISSUE TITLE
not running with ubuntu

### ISSUE THREAD

**Issue by kotakky** [lgsvl/simulator#1098]
I installed unity hub and unity(2019.3.3f1) in order to launch default simulation.
However, Many Error occurred as shown below image .As a result,I cannot render the map in  unity with linux  
Please help me What I should do.

![image](https://user-images.githubusercontent.com/45957491/97406184-2ab26a80-193c-11eb-9ad5-f84ed671bd76.png)
![image](https://user-images.githubusercontent.com/45957491/97407279-ce504a80-193d-11eb-9cdc-d02984961eb9.png)

**Comment by EricBoiseLGSVL** [comment]
Did you enable git lfs before you cloned?

**Comment by kotakky** [comment]
Yes,git lfs is installed.
However, The errors are not resolved.   
![image](https://user-images.githubusercontent.com/45957491/98071618-63f05a80-1ea7-11eb-8fbb-ab92ed7c8c93.png)

**Comment by kotakky** [comment]
In addition, when I enter playmode, the below message is received .
"All compiler errors have to be fixed before you can enter playmode!"

**Comment by martins-mozeiko** [comment]
Did you install & initialize git-lfs before cloning repository? Because git lfs does its work during fetch/checkout process, not aftwerwards.

Try running `git lfs ls-files`. All files should have asterix (`*`) next to name. If you see dash (`-`) that means you did not have git lfs properly configured when cloning repository. Run `git lfs fetch && git lfs checkout` to get LFS files in proper state.

https://www.lgsvlsimulator.com/docs/faq/#why-are-assets-scenes-missing-empty-after-cloning-from-git

**Comment by kotakky** [comment]
When I run git lfs ls-files, nothing is shown (Not in a git repository) .
![image](https://user-images.githubusercontent.com/45957491/98100836-c57aee00-1ed4-11eb-9d06-4f2d9b6bd700.png)

**Comment by EricBoiseLGSVL** [comment]
open terminal in the root location simulator in cloned and then run the commands @martins-mozeiko has posted please.  You can also tell if files are not pulled from git lfs if you navigate to Assets/UI/Images and see that the files are not images but text files in the Unity editor.  Do this for External cloned repos as well (vehicle/maps/etc)

**Comment by kotakky** [comment]
Thank you for your support.
git lfs  can work properly.However, I get the below message.I want to know how to address that.
![unty_1](https://user-images.githubusercontent.com/45957491/98188066-af614200-1f55-11eb-984c-af7da5d666fb.JPG)

**Comment by EricBoiseLGSVL** [comment]
You need to use Vulkan, OpenGL is not supported for Linux

**Comment by kotakky** [comment]
As you said, Simulator say Vulkan on the top of the Unity Editor.
But, the Shalun's scene does not colorize.
![image](https://user-images.githubusercontent.com/45957491/98190452-6495f900-1f5a-11eb-969c-2795da131b95.png)
![image](https://user-images.githubusercontent.com/45957491/98190381-3e705900-1f5a-11eb-8e95-20018010b77b.png)

**Comment by martins-mozeiko** [comment]
By default scenes do not have any light in them. Light is added only when scene is loaded in simulation during normal run - this is done so light system is common across all scenes.

If you want to see scene in the editor, disable lighting - click lightbulb icon next to `2D` text in the toolbar.

**Comment by kotakky** [comment]
I clicked the bulb icon and so, the scene is like below.
But I got the message "NO camera rendering".
Is this message normal?I think I sholud resolve the problem.
![image](https://user-images.githubusercontent.com/45957491/98250273-950d7f80-1fba-11eb-8903-590ac701aefe.png)

**Comment by EricBoiseLGSVL** [comment]
Yes, this is fine.  The camera is added at runtime but you are trying to load the map without loading simulator objects.  To test in editor you need to build the bundle, run Loader.scene, create a new simulation and map in WebUI (point map to new created bundle in repo/AssetBundles or where ever you placed it). Then select run the new simulation with the new map.  This will let you run in editor.  We do have Developer Settings in Simulator menu in between Window and Help at the top.  This will let you run the simulator from the new map scene you are working on but it limited in scope.  Next release we will have more options with this feature.
