### ISSUE TITLE
Issue with Unity 2019.3.15f1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1099]
Hi, I am having textures problems with Unity. The version I am using is 2019.3.15f1 and I am running on Ubuntu 20.04. The problem is in the visualization of the vehicle, which appears like this: 

![Screenshot from 2020-10-28 10-31-06](https://user-images.githubusercontent.com/71270688/97418500-2e78c980-1909-11eb-8554-3610300cc4da.png)

Could it be a problem of compatibility between Unity's version and Ubuntu's one? Or a problem of the git clone of the car (Jaguar2015XE) taken from github? I am totally lost. 
Thanks

**Comment by hadiTab** [comment]
I think this is just lighting. Try toggling the lighting button at the top of the scene view (it's the button with a lightbulb on it).

**Comment by EricBoiseLGSVL** [comment]
![InkedEGOHelp00_LI](https://user-images.githubusercontent.com/45106230/97510143-80960b00-195a-11eb-8557-0b69983fecfc.jpg)
