### ISSUE TITLE
Build issue with Unity 2019.3.3f1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by dmlachap** [lgsvl/simulator#1106]
I have followed the [build instructions](https://www.lgsvlsimulator.com/docs/build-instructions/) and the [instructions for Ubuntu](https://www.lgsvlsimulator.com/docs/faq/#how-do-i-setup-development-environment-for-unity-on-ubuntu) exactly as specified. 

I am able to build the Web UI without error, I get a number of "build failed" messages stating "Error building Player because scripts had compiler errors in the editor."

How can I resolve this?

**Comment by EricBoiseLGSVL** [comment]
Current release is 2019.3.15f1

**Comment by dmlachap** [comment]
Thanks, switching to the 2020.06 release and Unity 2019.3.15f1 resolved the issue.
