### ISSUE TITLE
Can I control the NPC by keyboard

### ISSUE THREAD

**Issue by qwetqwe** [lgsvl/simulator#1107]
It is difficult to use python api to realize some complicated behaviors of NPC. Is there any way to use keyboard to drive NPC?

**Comment by ntutangyun** [comment]
How about adding multiple EGO vehicles with distributed simulation, and use them as NPCs vehicles. Then you could have full control over them with API, Keyboard or ROS/CyberRT bridges.

**Comment by qwetqwe** [comment]
@ntutangyun  That's a good way， thanks!

**Comment by duong-pa** [comment]
> How about adding multiple EGO vehicles with distributed simulation, and use them as NPCs vehicles. Then you could have full control over them with API, Keyboard or ROS/CyberRT bridges.

This is a good solution, but how can I control pedestrian?
