### ISSUE TITLE
Can I use Apollo 6 with the simulator?

### ISSUE THREAD

**Issue by nniranjhana** [lgsvl/simulator#1108]
I see there are forks for using the simulator with Apollo 3.5 and Apollo 5. If I want to use it with the latest version, how would I go about it? Do I have to wait until an Apollo 6 fork is released?

**Comment by ntutangyun** [comment]
the latest version supports Apollo 6 master branch already.

**Comment by lemketron** [comment]
You can find instructions for working with the latest upstream Apollo master here:
https://www.lgsvlsimulator.com/docs/apollo-master-instructions/
