### ISSUE TITLE
how to deal with mismatch between map annotation and actual road?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1112]
as you can see in the picture there is a a little slop in actual road (shown in point cloud data).
All the traffic lanes (map annotation), point cloud render and 3D plan are align (having same height, y-axis ), but the map annotation can been seen clear in some part (left side of picture) but can not be seen on the right side. Which means the actual road having slop.

Now the question is After map annotation When i upload the hd map to apollo dreamview, There is a mismatch between hd map and actual road. 
![Screenshot from 2020-11-06 18-50-58](https://user-images.githubusercontent.com/61130487/98331695-0d665600-2038-11eb-9a17-8d7da5bc7469.png)
![Screenshot from 2020-11-03 19-12-40](https://user-images.githubusercontent.com/61130487/98331887-7e0d7280-2038-11eb-81fd-a3cc4aa3a40f.png)

**Comment by luqiang21** [comment]
I think you need to have correct mesh based on the point cloud with actual height instead of a plane. The annotations won't have correct height if your mesh doesn't have. Once you got the correct mesh, you can use following button to snap annotations to the road.
![image](https://user-images.githubusercontent.com/9755042/98394254-55bd4e00-200f-11eb-88b1-e7fa29ef089a.png)

**Comment by Addi2020** [comment]
@luqiang21 , Sorry i didn't understand about this mesh? (I think you need to have correct mesh based on the point cloud with actual height instead of a plane.) could you please explain how to do it?

**Comment by luqiang21** [comment]
@Addi2020 I mean you should have mesh collider to be correct as in real world, not 
>  3D plan are align (having same height, y-axis )

Otherwise, you can't have correct height for the map annotations.

**Comment by Addi2020** [comment]
@luqiang21 got it. Thanks!
