### ISSUE TITLE
how to create L shape pole with horizontal traffic lights? 

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1114]
i created the traffic light by using "SignalTrafficVerticalModel", i did not find any L shap or horizontal model in Asstets--Models--TrafficControl

**Comment by EricBoiseLGSVL** [comment]
@Addi2020 we will be releasing new traffic signal models in the next release.  You can always add your own from Unity asset store or create one in Maya/Blender

**Comment by Addi2020** [comment]
@EricBoiseLGSVL Got it . thanks
