### ISSUE TITLE
Ground Truth Visualizer is not working

### ISSUE THREAD

**Issue by ideasplus** [lgsvl/simulator#1120]
Hi, I want to visualize bounding boxes of  the obstacles as detected by the AD stack which running perception module. According to the official documentation, I add the **3D Ground Truth Visualizer sensor** and **2D Ground Truth Visualizer sensor** to the vehicle sensor configuration. However, I can't see the detected obstacles on the simulator as shown in the figure.

![Screenshot from 2020-11-10 11-28-37](https://user-images.githubusercontent.com/24294571/98624148-2462bc00-2348-11eb-8bf5-493fe02b16c0.png)

**Comment by EricBoiseLGSVL** [comment]
Enable the 3D Ground Truth and 2D ground truth in the visualize panel

**Comment by lemketron** [comment]
It looks like you enabled the (2D and) "[3D Ground Truth Visualizer](https://www.lgsvlsimulator.com/docs/sensor-json-options/#3d-ground-truth-visualizer)" sensors which are intended to visualize bounding boxes as supplied by an external AD stack. 

You need to instead add and enable the "[3D Ground Truth](https://www.lgsvlsimulator.com/docs/sensor-json-options/#3d-ground-truth)" sensor and enable visualization for that sensor. Sorry for the confusion, but please refer to the linked docs (above) for more details on each.

**Comment by ideasplus** [comment]
@EricBoiseLGSVL @lemketron
Thank you for your replay.  But the `3D Ground Truth` and `2D Ground Truth` sensors return 3D and 2D ground truth data without running perception module. What I want to do is **visualize the output of the perception module** instead of ground truth data.  

Here is the screenshot without running any AD stack, I only run the simulator  and enable the  3D Ground Truth and 2D Ground Truth sensors.
![Screenshot from 2020-11-11 16-18-27](https://user-images.githubusercontent.com/24294571/98788185-78020200-243b-11eb-88ac-8d8134114b66.png)

**Comment by lemketron** [comment]
> What I want to do is **visualize the output of the perception module** instead of ground truth data.

Sorry, I missed that. In that case, I believe you need to publish to the specified topic name (the example in the documentation is `/simulator/ground_truth/3d_visualize`), or change the topic name to match the topic from your AD stack.

**Comment by ideasplus** [comment]
@lemketron 
>  or change the topic name to match the topic from your AD stack.

Hi, I'm using Apollo, I want to know which apollo's topic should be matched. I change `/simulator/ground_truth/3d_visualize` to `/apollo/perception/obstacles`, but it does't work. Correct me if I'm wrong. Looking forward to your reply.

**Comment by EricBoiseLGSVL** [comment]
@lemketron is this the topic you use?

**Comment by lemketron** [comment]
This is the correct topic, but unfortunately that sensor was created for autoware and has not yet been updated to support apollo perception output. In addition, it should be renamed as it is intended to be a "perception visualizer" not a "ground truth visualizer" and now that we have a "ground truth sensor" it is even more confusing.

I have filed a bug internally to fix the name and also add support for visualizing apollo perception output, but cannot promise when this will be addressed. Sorry for the confusion!

**Comment by ideasplus** [comment]
@EricBoiseLGSVL @lemketron  Thanks for your clarification. Looking forward to the new feature.

**Comment by lemketron** [comment]
Please refer to the Apollo Perception Visualizer 3D sensor here:
https://www.svlsimulator.com/docs/simulation-content/sensors-list/#apollo-perception-visualizer-3d
