### ISSUE TITLE
Sensor plugin communicating with Matlab

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1121]
Hi, is there a way to create a sensor which communicates with matlab? I would like to have some data reguarding the simulation  (eg vehicle dynamics, battery and others) and analyze them in matlab.

**Comment by EricBoiseLGSVL** [comment]
Yes, we are working on this currently.  We use a custom sensor that communicates over web socket.  You can create the same thing.

**Comment by nike-96** [comment]
Is there an example of a sensor communicating over web socket?

**Comment by EricBoiseLGSVL** [comment]
We do not have an opensource example at this time sorry.  Here is a [link](https://answers.unity.com/questions/22582/unity3d-and-sockets-c.html) to some useful resources.

**Comment by nike-96** [comment]
Ok thank you!
