### ISSUE TITLE
unity editor compile error

### ISSUE THREAD

**Issue by Michealhao1991** [lgsvl/simulator#1127]
when  i open unity editor (2020.1.0b4) it has some compile error about "documentation.version"

![2020-11-16 13-21-22屏幕截图](https://user-images.githubusercontent.com/46957559/99216991-f7178180-2811-11eb-9c30-b6541e3c87b2.png)

**Comment by martins-mozeiko** [comment]
That's a wrong Unity version. Required version is in `ProjectSettings/ProjectVersion.txt` file, for example - for 2020.06 branch [here](https://github.com/lgsvl/simulator/blob/release-2020.06/ProjectSettings/ProjectVersion.txt).

If you want to use different version you'll need to upgrade HDRP package manually as Simulator has done some modifications there - check the git [history on folder](https://github.com/lgsvl/simulator/commits/release-2020.06/Packages/com.unity.render-pipelines.high-definition) if you want to see what was modified.

**Comment by Michealhao1991** [comment]
@martins-mozeiko  thank you very much
