### ISSUE TITLE
How to add new camera to lgsvl simulator 

### ISSUE THREAD

**Issue by ShubM7** [lgsvl/simulator#1129]
Hi LGSVL Team,

Can we add a new camera(Top View) to simulator. Currently there are 3 views Follow,Cinematic and Free in simulator, is there any way to add a custom view?

**Comment by EricBoiseLGSVL** [comment]
Sure you can. There are three scripts to edit
1) SimulatorCameraController.cs  This is where you add the new CameraStateType to the enum, Create the UpdateNewState method that controls or sets the position, and call the method in LateUpdate switch statement.  Also create the SetNewStateMethod for step 2. 
2) CameraManager.cs  Edit the ToggleCameraState method to call the set in step 1
3) Edit UIManager.cs SetCameraState method to set the UI name and you can add any new UI images you want in the UIManager prefab.
4) Boom, new simulator camera state :)
