### ISSUE TITLE
Problem of  rendering point cloud data

### ISSUE THREAD

**Issue by kotakky** [lgsvl/simulator#1130]
I follow the instruction (https://www.youtube.com/watch?v=6r7K3-dV1iM&t=22s).
I could import point cloud (.las). 
But, I got the error message below and cannot show the point cloud.
How can I do for resolving this error?

![image](https://user-images.githubusercontent.com/45957491/99479859-54d6d580-299a-11eb-9650-bb8064585747.png)

**Comment by EricBoiseLGSVL** [comment]
- First off, you can't import a point cloud and just press play in the editor.
- Once you import the point cloud, you need to create an asset bundle.  Please see the documentation on this.
- Then you need to run the Loader scene or a built binary and point this new asset to a new map entry.
- Create a new simulation with the new map
