### ISSUE TITLE
About default Control

### ISSUE THREAD

**Issue by blackJack12345** [lgsvl/simulator#114]
hi!
    What about the default control mode of the simulator?
    When I send start point and end point,the auto car can get a routing path from dreamviewer.But
I saw the car zigzagging to its destination, I think it was weird.Something wrong with it?
    Thank you in advanced!

**Comment by martins-mozeiko** [comment]
Hello.

We've look into this and it seems that following commit makes this behavior happen: dfe5a8ca8c529262c9ce25e59c756251768902bd

Please try to revert it and check if vehicle drives correctly. We will fix this in master shortly.

**Comment by martins-mozeiko** [comment]
This should be fixed in latest source code on master.
