### ISSUE TITLE
Additional vehicles in Unity Editor

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1141]
Hi, I would like to know if there are other available repositories of vehicles in order to be able to edit them in Unity Editor or is the Jaguar2015XE the only one? I am referring to the vehicles which can be used in the simulation so the ones through contents of the simulator (https://content.lgsvlsimulator.com/vehicles/).

**Comment by EricBoiseLGSVL** [comment]
@nike-96 The Jaguar2015XE is the only open source repository available at this time.  We have instructions on how to create your own vehicle in our documentation and there are many websites to purchase vehicles.  Just be sure that the model is game ready so you don't have an excessive amount of polygons.
