### ISSUE TITLE
CanBus data logging

### ISSUE THREAD

**Issue by nike-96** [lgsvl/simulator#1144]
Hi, is there the possibility of getting data of the CanBus sensor on Python API? I tried the attribute "data" which is available for the GPS, but it's not an attribute of the object CanBusSensor.

**Comment by EricBoiseLGSVL** [comment]
@nike-96 Yes, I have MRs in review now and it will be in our next release.  I can post the patch files here if you don't want to wait

**Comment by nike-96** [comment]
Don't worry, I can wait. Thank you very much

**Comment by EricBoiseLGSVL** [comment]
Sorry this issue slipped through the cracks.  Sorry for the confusion. After reviewing all the sensors that would need to be added and the performance issues, we decided to not support api for data collection. Please use the bridge for data collection. You can change the source code to add canbus but we do not recommend. You will need to change the python api and api commands in simulator source.  Maybe @cubrink would be able to work with you from this issue #1278
