### ISSUE TITLE
Question about NPC vehicle type

### ISSUE THREAD

**Issue by yanjiren** [lgsvl/simulator#1145]
1. Will new NPC types be released in the next version, such as bicycles and motorcycles ,etc?
2. How to add a new vehicle type like motocycle? I see there is a tutorial about creating a new vehicle but four wheel nodes.

**Comment by EricBoiseLGSVL** [comment]
@yanjiren 
1) sorry, not yet.  We are implementing a way to be able to select and use specific NPCs through the WebUI.  It's almost done and will be available in a future release.
2) We will have an example of a motorcycle as an NPC.  We do not support a motorcycle as an EGO vehicle.  You would need to create a new IVehicleDynamics class.  It can be very similar to VehicleSMI.cs just supporting 2 wheels.  Build the simulator with the new dynamics class and then create a motorcycle asset bundle with the new dynamics class attached.

Here is our motorcycle example.
![MotorcycleExample00](https://user-images.githubusercontent.com/45106230/100264425-ae438500-2f03-11eb-8836-be20e30e7c95.png)
