### ISSUE TITLE
question about import map and  VSE(visual openscenario editor)

### ISSUE THREAD

**Issue by leibu777** [lgsvl/simulator#1146]
1.import opendrive  map  ，to build mesh（*）  ready  open source next version？，free？ (steve lemke say in china unity tech week)
2.VSE(visual openscenario editor) ready  Open source next version？ is free ？
3.VSE : i want to import openscenario xml to Generate random traffic incidents in unity , 
   for example: ego distance npc > 100m —— overtake  
  and use VSE create event  ，export to scenario xml?
4.  When will the next version be released？
  thanks~

**Comment by EricBoiseLGSVL** [comment]
@leibu777 Welcome to LGSVL Simulator and thanks for watching @lemketron 's Unity talk.  Yes we plan on releasing VSE as soon as possible with our next release.  We are working on it now and should be in December
