### ISSUE TITLE
Read and save Radar and IMU data from bridge with Python API

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1150]
Hello all,

I run the simulator together with Apollo and try to get the data collected by different sensors with Python API. After going through the documentation I found that the way to save camera and Lidar information is well documented, but not the method to get data from Radar, IMU and CanBus etc. So how could I get these information from cyberRT? 

Thanks in advance.

**Comment by EricBoiseLGSVL** [comment]
@Yimags We are adding the ability to get data with the api for these sensors.  Is Radar, IMU and CanBus the only sensors needed?

**Comment by Yimags** [comment]
> @Yimags We are adding the ability to get data with the api for these sensors.  Is Radar, IMU and CanBus the only sensors needed?

Yeah, these will be enough for me. Thx!

**Comment by Yimags** [comment]
> @Yimags We are adding the ability to get data with the api for these sensors.  Is Radar, IMU and CanBus the only sensors needed?

@EricBoiseLGSVL btw, how could I subscribe topics and save relevant data, in, for example, txt format? Considering the API is not available for now...

**Comment by EricBoiseLGSVL** [comment]
traffic light is not a sensor.  It would be better to use the bridge and save the data with that.  This is the way we designed it for data collection.

**Comment by Yimags** [comment]
> traffic light is not a sensor. It would be better to use the bridge and save the data with that. This is the way we designed it for data collection. Using the API to get this data will be very slow.
> [Here](https://www.lgsvlsimulator.com/docs/lgsvl-msgs/) is the link to use lgsvl messages.

Is it possible to use bridge (cyberRT) to get these data within Python API? Actually I am considering using Python API together with both lgsvl and apollo to save data when running simulations. Would you provide me some more information about how to integrate Python API and CyberRT-based data collection?

**Comment by EricBoiseLGSVL** [comment]
So the bridge is used with the python API.  Api is just to control the simulation while the sensors send the data through the optimized bridge.  Run the bridge, listen to topics and you are good.  Right @hadiTab ?

**Comment by hadiTab** [comment]
Pretty much. You can use the Cyber recorder to save data in Apollo.

**Comment by Yimags** [comment]
> Pretty much. You can use the Cyber recorder to save data in Apollo.

Thx for the brief guidance! And here is the case I came across with when I try to run with cyber_recorder. Could you point me out about how could I fix it?
![error_recorder](https://user-images.githubusercontent.com/64920943/101965006-85193900-3c13-11eb-90f2-ff28f80db38f.png)

**Comment by EricBoiseLGSVL** [comment]
@Yimags after creating data collection with the API we found many issues with performance.  We will not be releasing get data API commands because the bridge was designed to do this.  As for the error, @hadiTab or @luqiang21 do you know why the cyber recorder is having this error?  Is this still an issue @Yimags ?

**Comment by Yimags** [comment]
> @Yimags after creating data collection with the API we found many issues with performance. We will not be releasing get data API commands because the bridge was designed to do this. As for the error, @hadiTab or @luqiang21 do you know why the cyber recorder is having this error? Is this still an issue @Yimags ?

Thx for the information!
And my issue has been solved [here](https://github.com/ApolloAuto/apollo/issues/13178#issue-764275547).

**Comment by EricBoiseLGSVL** [comment]
Excellent.  Glad it was solved
