### ISSUE TITLE
Is it possible to launch ground truth 3d sensor through python api?

### ISSUE THREAD

**Issue by bojanykc** [lgsvl/simulator#1156]
I go through the python api sensor file and it seems ground truth sensors are not included. I wonder if it is possible to launch them through python api?

**Comment by EricBoiseLGSVL** [comment]
@bojanykc What do you mean launch them?  You add the 3d GT sensor to your vehicle sensor parameters.  When you load that vehicle with the API, the GT sensor is enabled.

**Comment by bojanykc** [comment]
I believe the problem is solved, thank you for your help.

**Comment by crankler** [comment]
It seems  that "GPS Odometry" just as a odom, Is it right?
Should I use the tf  to publish  this data  in the tf tree?
