### ISSUE TITLE
Ubuntu 18.04 Simulator stuck at localhost web loading

### ISSUE THREAD

**Issue by Jiaqing-Cao** [lgsvl/simulator#1161]
Hi, I am using 2020.06 Simulator on Ubuntu 18.04, the Simulator works fine on Windows. 

However, when I ran it on Ubuntu, it will stuck at localhost web loading or keep going between loading and account,lgsvlsimulator.com.

It look like the image below:
![Screenshot from 2020-12-03 15-16-23](https://user-images.githubusercontent.com/52268935/100978336-33badb00-357d-11eb-94d8-56d321a674d3.png)

I have tried other localhost port like 8081 and 8800, also tired to use Ctrl+r to reload page. it still look like above.
[Player.log](https://github.com/lgsvl/simulator/files/5634422/Player.log)
Also attach the Player.log.
Could you please tell me which part is wrong?

**Comment by EricBoiseLGSVL** [comment]
@zelenkovsky  Looks like this is the issue
```
WebException: Error: NameResolutionFailure
```
Any ideas on how to resolve this?

**Comment by Jiaqing-Cao** [comment]
@zelenkovsky

Could you please give me some help on this issue ?

Thank you!

**Comment by EricBoiseLGSVL** [comment]
@Jiaqing-Cao Have you looked at this [issue](https://github.com/lgsvl/simulator/issues/859)?

**Comment by Jiaqing-Cao** [comment]
Hi @EricBoiseLGSVL ,

I have looked at the issue you shared, and I tried all the methods David provides, it did not work on my PC.

I also tried GuoliangPeng's "Turn off automatic proxy setting and manual proxy setting", then it will stuck at the LG account sign in page like:

![Screenshot 2020-12-11 10:07:32](https://user-images.githubusercontent.com/52268935/101852723-4181e900-3b99-11eb-82ed-5be8056f3bcf.png)

This way I am not able to even get to page localhost.

Do you have any ideas about that?

**Comment by EricBoiseLGSVL** [comment]
@thisisdavidfrank do you have any idea how to further troubleshoot this?

**Comment by EricBoiseLGSVL** [comment]
@Jiaqing-Cao did you clear cookies yet?

**Comment by Jiaqing-Cao** [comment]
@EricBoiseLGSVL ， I tried to clear cookies, it still did not work.

**Comment by thisisdavidfrank** [comment]
Hey @Jiaqing-Cao, so looks like if you remove your Proxy settings, the site is stuck at the Accounts page, correct? So, can you sent the Network Logs when you are on this page and try to Sign In?

It looks like either the Sign In API is not working, or it is working but is not able to set Cookies. So, your Network Logs might help us debug this problem.

**Comment by Jiaqing-Cao** [comment]
Hi @thisisdavidfrank ,

Yes，if I remove my Proxy settings, the site is stuck at the Accounts page.

And I get my Network Logs, It looks like that github do not support HAR file type, I will just paste it here:

**{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": []
  }
}**

It only has those lines above, no other logs.

Does that means the Sign In API is not working?

**Comment by thisisdavidfrank** [comment]
Hi @Jiaqing-Cao,

Looks like the complete network logs were not captured due to the browser refreshing. 

Can you do the following steps, please?
1. Open a Chrome browser and then Open Developer Tools, and click on the Network tab.
2. Check the two options: Preserve Logs and Disable Cache (Screenshot attached).
3. Close the browser.
4. Now, launch the localhost from the Simulator.
5. After you see the same problem, please download the Network Logs.
6. You can change the extension of the file to .txt and attach it here.

![image](https://user-images.githubusercontent.com/55010181/102260276-17943380-3ec5-11eb-958a-81dd268507b8.png)

Thank you.

**Comment by Jiaqing-Cao** [comment]
Hi @thisisdavidfrank , I followed your step and get:
[account.lgsvlsimulator.com.txt](https://github.com/lgsvl/simulator/files/5699183/account.lgsvlsimulator.com.txt)
![Screenshot 2020-12-16 06:54:33](https://user-images.githubusercontent.com/52268935/102282956-72349a80-3f6c-11eb-891d-7f746931f551.png)
The first log is I stuck at sign in and get.

[account.lgsvlsimulator.com1.txt](https://github.com/lgsvl/simulator/files/5699189/account.lgsvlsimulator.com1.txt)
![Screenshot 2020-12-16 06:55:54](https://user-images.githubusercontent.com/52268935/102283076-a4de9300-3f6c-11eb-8dfc-d7edce9a0327.png)
The second log is after I stuck, I used Ctrl+R to reload and get.

Do those logs help you debug?

**Comment by thisisdavidfrank** [comment]
Hi @Jiaqing-Cao, thank you for the logs. Unfortunately, I do not see the 'login' API going out in your logs. Can you capture the logs when you also click on the Sign In button, please? That's the only way that I can compare the token being returned by the 'login' API with the token that you have during the redirect.
Thank you.

**Comment by Jiaqing-Cao** [comment]
Hi @thisisdavidfrank ,

[account.lgsvlsimulator.com2.txt](https://github.com/lgsvl/simulator/files/5699401/account.lgsvlsimulator.com2.txt)
![Screenshot 2020-12-16 08:00:13](https://user-images.githubusercontent.com/52268935/102287396-55509500-3f75-11eb-9840-12cd1821015a.png)

I think this log capture the Sign in click.
Will this log help you ?

**Comment by thisisdavidfrank** [comment]
Hi @Jiaqing-Cao, thank you again for your log. I've examined it extensively and it seems that the problem is that your API calls for 'token' and 'sign-in' are not reaching the server. If you notice the response size, starting from the 'token' API, all the responses have 0B sizes. The most likely reason for this is that the Linux machine has a restriction on the number of concurrent outgoing TCP connections, and this is causing the connections to fail. Can you increase the number of outgoing TCP connections, and try again?

Note: For security reasons, please **delete** the log attachment in your previous response.

**Comment by Jiaqing-Cao** [comment]
Hi @thisisdavidfrank , thanks for your reply.

I followed [this link](https://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux)
The top answer to increase the number of outgoing TCP connections.
However, still that problem is not fixed.

And I delete the log attachment in my previous response.

**Comment by martins-mozeiko** [comment]
@thisisdavidfrank fyi, you cannot delete attachments in your comments. They will be always available in history ("edited" link).

@Jiaqing-Cao I suggest you to change your password (`139Fal...`), as that is visible in plain text in the attachment you posted. And in case you are using this password in other services, change it there ASAP.

**Comment by Jiaqing-Cao** [comment]
@martins-mozeiko , okay, thanks for that.

**Comment by zelenkovsky** [comment]
I apologize for inconvenience. Our server went down around 4 hours ago. But now problem is solved. Please try to login again.

**NO NEED TO CLEAR COOKIES**

![image](https://user-images.githubusercontent.com/10243884/102870258-a509e300-43f1-11eb-91a5-75535b774478.png)
