### ISSUE TITLE
Where can I find assets used in environmental examples such as borregas ave. san francisco?

### ISSUE THREAD

**Issue by Akyeast** [lgsvl/simulator#1163]
I want to create a new environment for the experimental environment.
I would like to use the assets used in the example.

**Comment by lemketron** [comment]
Not all of the sample environments have source available but you can find source on github for the [CubeTown](https://github.com/lgsvl/CubeTown) and [San Francisco](https://github.com/lgsvl/SanFrancisco) example environments.
