### ISSUE TITLE
Module malfunction in modular testing with apollo

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1170]
Hello all,

I ran the modular test with apollo and came with the problem that all module except for localization and chasis did not work at all (no perception, prediction, 
planning, control etc.). I followed the instructions and built apollo again and again step by step. But it still shows the same result. So I was wondering if you could help to localize the problem. Thanks in advance!
![shutdown](https://user-images.githubusercontent.com/64920943/101657197-e7bbda80-3a43-11eb-8587-28df5339540f.png)
![shutdown2](https://user-images.githubusercontent.com/64920943/101657213-ebe7f800-3a43-11eb-842e-b50ffddf0225.png)

**Comment by Yimags** [comment]
And here is the log recorded.
![log](https://user-images.githubusercontent.com/64920943/101661223-53a04200-3a48-11eb-8085-c924f105cc84.png)

**Comment by luqiang21** [comment]
@Yimags It looks like you didn't add modular testing sensors. You need to add them in your sensor configuration.

**Comment by Yimags** [comment]
> @Yimags It looks like you didn't add modular testing sensors. You need to add them in your sensor configuration.

Ahh exactly, I have changed it to my personal settings. Thx!

I am also wondering to what extent I could customize the sensor settings without causeing the malfunction of Apollo? Or how could I modify Apollo if I want to change sensors in lgsvl?

**Comment by luqiang21** [comment]
@Yimags You just need to list which sensors are needed by those apollo modules, make sure those sensors are added in your sensor configuration. If an Apollo module is not working, you can first check the existence of the corresponding sensor. Then check apollo module's log file.

What do you mean?
> Or how could I modify Apollo if I want to change sensors in lgsvl?

**Comment by Yimags** [comment]
> @Yimags You just need to list which sensors are needed by those apollo modules, make sure those sensors are added in your sensor configuration. If an Apollo module is not working, you can first check the existence of the corresponding sensor. Then check apollo module's log file.
> 
> What do you mean?
> 
> > Or how could I modify Apollo if I want to change sensors in lgsvl?

I meant whether newly added senors (apart from those of modular test) will influence influence the functionality or not. If it does, how could I modify apollo code to make new sensor work well with apollo?

**Comment by luqiang21** [comment]
@Yimags It should depend on the topic name of the sensor you add. If they are different from what Apollo is using, then it won't influence.

**Comment by Yimags** [comment]
> @Yimags It should depend on the topic name of the sensor you add. If they are different from what Apollo is using, then it won't influence.

Got it. Thank you for your help！

**Comment by roshambo919** [comment]
nvm. user error. for future users, configuration is located in the vehicle library on wise.svlsimulator.com
