### ISSUE TITLE
Error of missing module when trying to get data from cyberRT with pythonAPI

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1174]
Hello all,

I am now running lgsvl with apollo and trying to get data from cyberRT with pythonAPI. However I come across an error when running [listener.py](https://github.com/ApolloAuto/apollo/blob/master/cyber/python/cyber_py3/examples/listener.py). Any suggestion or solution will be appreciated. Thx in advance!
![error_no module](https://user-images.githubusercontent.com/64920943/102089801-fed04300-3e1c-11eb-9844-acd664146bbc.png)

**Comment by ntutangyun** [comment]
you should probably ask this question at [Apollo's repo](https://github.com/ApolloAuto/apollo/issues)

**Comment by luqiang21** [comment]
@Yimags Are you running listener.py inside apollo docker?

**Comment by Yimags** [comment]
> @Yimags Are you running listener.py inside apollo docker?

Not quite. I tried it outside the docker. Is it necessary to run the cyber python API inside the docker?

And now I run it inside the docker but another missing module occurs:

![error_missingmodule](https://user-images.githubusercontent.com/64920943/102122800-4fa86180-3e46-11eb-89c1-eab1ca288df0.png)

**Comment by Yimags** [comment]
The python files in apollo are managed by bazel. So instead of running it directly, running `bazel run //cyber_py3/examples:listener` should work.
For [details](https://github.com/storypku/CyberRT/tree/master/cyber_py3).
