### ISSUE TITLE
Start the Autoware.Auto containers with NVIDIA setup stuck

### ISSUE THREAD

**Issue by qiongwu1003** [lgsvl/simulator#1179]
Hi 
LGSVL team

I built the environment of Autoware.Auto with LGSVL Simulator followed [here](https://www.lgsvlsimulator.com/docs/autoware-auto-instructions/).
When I step into "Start the Autoware.Auto containers with NVIDIA setup:", I am stuck on the "Creating volume container for nvidia/cuda:latest". The ade version is 4.2.0. Could someone give me some advice?
![98_stuck_on_cuda](https://user-images.githubusercontent.com/65001214/102433888-ae402c00-404e-11eb-8422-c6402f5bc1e9.png)

All things went well except when I first started ade.
When I first started I met the "token" event as below, and I created myself a token. But I met the problem above.
![token_error](https://user-images.githubusercontent.com/65001214/102434475-ccf2f280-404f-11eb-91c3-73bfa2970cd9.png)

I think it might be the "token" problem,  so I delete the ade(I am not sure if deleting it directly is correct) and reinstall it. This time I did not meet the "token" event. But I still met the problem above.

Moreover, my Nvidia driver message is as below. And I automatically install it using the PPA repository.
![98_nvidia_smi](https://user-images.githubusercontent.com/65001214/102435557-c36a8a00-4051-11eb-9593-fd80d4336afa.png)

**Comment by EricBoiseLGSVL** [comment]
@qiongwu1003 I am concerned you are using a 1060 GPU, this might have issues running simulator.

**Comment by qiongwu1003** [comment]
@EricBoiseLGSVL 
Thanks for your reply.
I changed a newer 2070 GPU, and still have the same issue. 
![98_Nvidia_2070](https://user-images.githubusercontent.com/65001214/102561419-9ed4e780-410f-11eb-8618-fa4d80e59bd1.png)

**Comment by qiongwu1003** [comment]
@EricBoiseLGSVL 
I turned off my network and tried again. It needs "username" and "token", once I enter them it gives out bellow. And I do not think the "username" and "token" are correct since I created them myself.
![98_ade_start_username](https://user-images.githubusercontent.com/65001214/102571696-13fee780-4125-11eb-9ef3-d1e1466ad213.png)

Have any ideas according to this output?

**Comment by lemketron** [comment]
> When I first started I met the "token" event as below, and I created myself a token. But I met the problem above.

Is "mcw" your gitlab username? Did you create a personal access token on the page shown in the screen shot (https://gitlab.com/-/profile/personal_access_tokens)?

**Comment by qiongwu1003** [comment]
@lemketron 

>Is "mcw" your gitlab username? Did you create a personal access token on the page shown in the screen shot
No, it is my system name. 
Yes, I create a personal access token.
You mean I should enter the gitlab username in the "Username:" location?

**Comment by hadiTab** [comment]
@qiongwu1003 it seems like it's asking for username and password to pull the docker images from the gitlab registry. Now, I would have assumed that it wouldn't need credentials to pull the image, but maybe I'm wrong. But the credentials, for whatever reason they are being requested, would be your gitlab credentials.

Overall, this seems like an issue with setting up the ADE containers in AutowareAuto, so it's probably best to try to get help from the Autoware people. Best way to get help is to post a question on answers.ros.org and add a tag for autoware.auto. Josh from AWF is usually pretty quick to respond.

**Comment by qiongwu1003** [comment]
@hadiTab 
Thank you very much. I will try to get help from Autoware and close the issue here.
