### ISSUE TITLE
Issues related to traffic lights? 

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1183]
I am facing may problems while creating traffic lights. Your response is highly appreciated.
1. I changed the height of traffic light by changing Y-axis of Position (Pic-1), but it does not effect in real world (pic-2).
2.  what bound offset and bound scale means (Pic-1)? 
3. I create traffic light with signal type MIX_3_Horizontal , but signal light Mesh is Vertical, so when I upload it to Dreamview (Pic-3), It creates Vertical model of Traffic light rather then horizontal. 

Pic-1
![Screenshot from 2020-12-18 14-23-47](https://user-images.githubusercontent.com/61130487/102584880-4834d100-4142-11eb-9415-94d8971edaa3.png)

Pic-2
![Screenshot from 2020-12-18 15-06-44](https://user-images.githubusercontent.com/61130487/102585101-b5486680-4142-11eb-934c-79276822f889.png)

Pic-3
![Screenshot from 2020-11-19 13-53-05](https://user-images.githubusercontent.com/61130487/102584927-5be03780-4142-11eb-9c77-86fc1ae1d6ce.png)

**Comment by EricBoiseLGSVL** [comment]
1) If you rotate the mesh Y is no longer height.  Prob -+X
2) Bounding box for the light mesh for the AD stack
3) we only support 3 vertical in the HDmap export.  You just need to edit to be able to add horizontal

**Comment by Addi2020** [comment]
@EricBoiseLGSVL , can you please explain your answers?
1. you mean height of traffic light depends on X prob?
2. AD stack?
3. do i need to edit signal mesh script?

**Comment by EricBoiseLGSVL** [comment]
1) I mean that X is up down after you rotate the light on the mesh.  Did you export the map and convert to .bin files for apollo after adjusting?  Is the signal in the correct position in the scene?  Are you correctly localizing the video to the scene, scale, position, rotation, camera properties (focal length, etc)

2) BoundScale is the bounding box around the traffic signal.  This is used by the AD stack (Autonomous Driving) Apollo, Autoware, etc.

3) In our exporter we default to Vertical 3 type.  If you want to use a horizontal, you need to edit the exporter to support this.  It is in the HDMap exporter code for the AD stack you use

![TrafficSignalHelp01](https://user-images.githubusercontent.com/45106230/102802553-adb7d600-436b-11eb-898e-37ff09c9a1a6.png)

**Comment by Addi2020** [comment]
@EricBoiseLGSVL  got it. Thanks
