### ISSUE TITLE
Orientation of NPC vehicles 

### ISSUE THREAD

**Issue by MartinaB85** [lgsvl/simulator#1187]
Good morning,

we've been adding a new custom map to the lgsvl simulator and when connecting it to Apollo 5.0 the orientation of the spawned NPC vehicles is wrong as you can see in the video in attached. The NPC are correctly moving forward but their orientation and the bounding boxes detected by Apollo are horizontally oriented going in the left direction.

Is it something due to wrong annotation map? How can we fix this?

Thank you very much,

Martina

https://user-images.githubusercontent.com/73334464/102770945-4149d080-4385-11eb-9575-f094bdfd6923.mp4

**Comment by EricBoiseLGSVL** [comment]
@MartinaB85 Morning, I think this is an issue with the map not being rotated correctly.  @hadiTab ?

**Comment by hadiTab** [comment]
@MartinaB85 as @EricBoiseLGSVL pointed out this is likely an issue with map orientation. The map is expected to be orientated in the Unity editor such that the world z-axis is pointing East. It's common for people to orient it so that Z points North, which will cause issues in orientation measurements.

**Comment by MartinaB85** [comment]
Thank you so much, that solved the issue.

I would like to ask you also...I want to create a scenario with traffic cones but after building the asset bundle as explained in https://github.com/lgsvl/TrafficCone, changed the name as it is used in the python API, i.e. "TrafficCone", I keep getting Unknown 'TrafficCone' controllable prefab. I have tried rebuilding several times but it does not work. 
Attached are some screenshot of what it has been created in the controllable folder and the name it is called in the code.

Hopefully you can help me.

Thank you very much,

Martina
![Controllable_Folder](https://user-images.githubusercontent.com/73334464/102986620-6bc89480-4511-11eb-8075-58c76db10525.png)
![Error_Cone](https://user-images.githubusercontent.com/73334464/102986624-6c612b00-4511-11eb-9082-370e14927d84.png)
![Python_Code](https://user-images.githubusercontent.com/73334464/102986626-6cf9c180-4511-11eb-8060-49023067d42f.png)

**Comment by EricBoiseLGSVL** [comment]
You have not built the controllable correctly if the name of the file is TrafficCone.pdb.  Did you have errors when you built the controllable in the Unity Editor Simulator -> Build... menu?
It should look like this...
![ControllableHelp00](https://user-images.githubusercontent.com/45106230/103233904-1fa39880-48f3-11eb-999d-d710d2b1d4e6.png)

Also, if you want to create a new controllable, don't name it exactly the same as the one you already have loaded.  Please Prepend with MyTrafficCone or something.  I have a feeling there are class name conflicts here.

**Comment by MartinaB85** [comment]
Thank you. The problem apparently was the name I was using in python.
Thank you very much.! :)
