### ISSUE TITLE
No module named 'lgsvl' when running simulation in docker

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1194]
Hello all,

I ran the simulation with apollo and wanna get data from cyberRT for PythonAPI. I tried to combine PythonAPI script with `listener.py` and ran it in docker. But it gives a `No module named 'lgsvl'` error. How could I fix this?

**Comment by ntutangyun** [comment]
it's probably mot related to docker. it's just your python environment does not have the lgsvl PythonAPI installed. 

you could try to install by following: 

cd PythonAPI
pip install .

**Comment by Yimags** [comment]
Thx for the quick response!
Actually in works well when I run python standalone. However the error takes place when I build it with bazel.
![error bazel](https://user-images.githubusercontent.com/64920943/103341147-59f16f00-4a86-11eb-8c42-dbf294d7ca60.png)

**Comment by hadiTab** [comment]
Your PythonApi scripts shouldn't be placed inside the Apollo docker container as it doesn't have the Api installed by default.

**Comment by Yimags** [comment]
Then I can't merge `listener.py` with Python script outside the docker which controls the simulation. How could I make use of the real time data from bridge during simulation?
