### ISSUE TITLE
Traffic light Direction?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1195]
I created a traffic light  in one direction and when upload it to dreamview, it show another direction (90 degree right).  how to change the direction of light? 

pic1 for Map_Signal
![asdasd](https://user-images.githubusercontent.com/61130487/103348908-34cc2300-4abd-11eb-8912-86d25960fedd.JPG)

pic2 for Map_Signal_Mesh
![safdsadfsa](https://user-images.githubusercontent.com/61130487/103348912-37c71380-4abd-11eb-866a-4bd95eca7a14.JPG)

**Comment by EricBoiseLGSVL** [comment]
If you want a new light mesh with a different rotation, you need to bring the fbx into a modeling software like Maya or Blender and rotate/delete history then export out as a new traffic signal mesh.  Then replace the signal in the scene with your new one.  Be sure to keep the source files in the new map you are making so it builds with the bundle.
