### ISSUE TITLE
Simulator opens and closes suddenly

### ISSUE THREAD

**Issue by FitashUlHaq** [lgsvl/simulator#1197]
I have downloaded LGSVL 2020.06 version for linux and when i run it from terminal it closes suddenly without giving any error. I have attached picture of nvidia-smi

![Screenshot from 2021-01-03 10-29-52](https://user-images.githubusercontent.com/15017524/103475595-b6b69780-4dae-11eb-8f60-d32283354cd5.png)

any leads? what might be causing this error?

**Comment by EricBoiseLGSVL** [comment]
Can you please post the player.log?  This will have the error that is crashing the application.

**Comment by FitashUlHaq** [comment]
Hi Thank you for your reply. I reinstalled Ubuntu and nvidia drivers and it worked.

Many thanks!
