### ISSUE TITLE
Apollo stack unable to receive messages generated by LGSVL

### ISSUE THREAD

**Issue by vin-cloud** [lgsvl/simulator#1200]
I have setup my environment as per instructions detailed in LGSVl documentation below.
a. https://www.lgsvlsimulator.com/docs/build-instructions/
b. https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/
Issue:
As seen from the picture (1) below, the simulator seems to have established a connection with Apollo, but the messages generated by the simulator LGSVL is not received by the Apollo stack(Build: Passed) as seen in picture (2). Kindly help!

1.   
![image](https://user-images.githubusercontent.com/61731065/103638586-7747a100-4f90-11eb-94be-9c798621887a.png)
2.
![image](https://user-images.githubusercontent.com/61731065/103638639-89294400-4f90-11eb-8569-e09489f0b62f.png)
3.
![image](https://user-images.githubusercontent.com/61731065/103638694-980ff680-4f90-11eb-936f-617b7019e7f9.png)
4.
![image](https://user-images.githubusercontent.com/61731065/103638714-a1995e80-4f90-11eb-9af1-7f2845af01db.png)
5.
![image](https://user-images.githubusercontent.com/61731065/103638770-b4ac2e80-4f90-11eb-84f5-3805cdca51e9.png)

**Comment by EricBoiseLGSVL** [comment]
@luqiang21 @hadiTab any idea or needed logs?

**Comment by lemketron** [comment]
Is this all running on the same machine, with the simulator configured to connect to the bridge on localhost? It's almost as if the simulator is somehow connecting to a different bridge. It looks like the bridge is running correctly but once you've started the simulator (pressing "play" which shows the "pause" button like in your screen shot) some of the topics in cyber_monitor should immediately turn green.

**Comment by vin-cloud** [comment]
> Is this all running on the same machine, with the simulator configured to connect to the bridge on localhost? It's almost as if the simulator is somehow connecting to a different bridge. It looks like the bridge is running correctly but once you've started the simulator (pressing "play" which shows the "pause" button like in your screen shot) some of the topics in cyber_monitor should immediately turn green.

Yes, the entire package(simulator and Apollo stack) is running on the same machine! That's the main concern, that the topics when pressed play on simulator should have turned green, unlike the result above!

**Comment by lemketron** [comment]
Can you share the Player.log file for the simulator and also the /apollo/data/log/cyber_bridge.INFO log file?

If everything has been running for a while you might want to try shutting down, rebooting, and starting everything again. The log files should be smaller too.

**Comment by vin-cloud** [comment]
> Can you share the Player.log file for the simulator and also the /apollo/data/log/cyber_bridge.INFO log file?
> 
> If everything has been running for a while you might want to try shutting down, rebooting, and starting everything again. The log files should be smaller too.

There seems to be 'connection refused' statement within the Player.log file
1. player.log 
[Player.log](https://github.com/lgsvl/simulator/files/5773912/Player.log)

2.cyber_bridge.INFO (PS: kindly remove the .txt extension)
file:///home/spring/cyber_bridge.INFO.txt

**Comment by vin-cloud** [comment]
> Can you share the Player.log file for the simulator and also the /apollo/data/log/cyber_bridge.INFO log file?
> 
> If everything has been running for a while you might want to try shutting down, rebooting, and starting everything again. The log files should be smaller too.

There seems to be 'connection refused' statement within the Player.log file
Well, have tried the shutdown/reboot routine with re-installation from scratch!

1. Player.log
[Player.log](https://github.com/lgsvl/simulator/files/5773921/Player.log)

2.cyber_bridge.INFO 
[cyber_bridge.log.](https://github.com/lgsvl/simulator/files/5773926/cyber_bridge.log)

Thanks!

**Comment by EricBoiseLGSVL** [comment]
Yes, looks like you can't connect.  Do you have any other software using the same ports?  Do you have software managing connection permissions?

**Comment by vin-cloud** [comment]
> Yes, looks like you can't connect. Do you have any other software using the same ports? Do you have software managing connection permissions?

I am not using any other software on the same port!

**Comment by EricBoiseLGSVL** [comment]
Any idea @lemketron ?  This looks like an issue with apollo

**Comment by lemketron** [comment]
> Any idea @lemketron ? This looks like an issue with apollo

I don't know if it's an apollo issue or docker connectivity. It's interesting that the initial connection from LGSVL to the cyber_bridge appears to succeed but then packets don't seem to flow afterwards. We're unable to reproduce this, and I'm not sure how to troubleshoot it. @martins-mozeiko might have a suggestion?

**Comment by hadiTab** [comment]
@vin-cloud I don't think this is a simulator/bridge issue. I suspect that Apollo is not starting up properly. Some of those cyber channels are published directly from Apollo and do not need any bridge connection to work (for example `apollo/monitor`). I suspect that Apollo was not built successfully on your machine. I'd suggest trying a clean rebuild. You could also dig through the logs located in data/logs/ to see if you find anything as well.

**Comment by vin-cloud** [comment]
> @vin-cloud I don't think this is a simulator/bridge issue. I suspect that Apollo is not starting up properly. Some of those cyber channels are published directly from Apollo and do not need any bridge connection to work (for example `apollo/monitor`). I suspect that Apollo was not built successfully on your machine. I'd suggest trying a clean rebuild. You could also dig through the logs located in data/logs/ to see if you find anything as well.

Thanks! I have actually tried deleting the docker files and then build it (recommended [Apollo 5.0](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/)) from scratch, the only option i haven't tried yet is to format on OS level and retry!

**Comment by vin-cloud** [comment]
Re-installation from scratch was the only option! Closing the issue!
Thanks!
