### ISSUE TITLE
The SanFrancisco map doesn`t have no rain effect

### ISSUE THREAD

**Issue by CurlyWei** [lgsvl/simulator#1203]
I set up weather at the edit form WebUI. 

![image](https://user-images.githubusercontent.com/27539904/103734329-b4f70900-5026-11eb-8a11-b93798822498.png)

The  simulator showed the condition

![image](https://user-images.githubusercontent.com/27539904/103734821-b1b04d00-5027-11eb-9b85-0d5026b36162.png)

And only the floor has raindrops,Can you help me this issues?

**Comment by EricBoiseLGSVL** [comment]
Sorry, I think the latest release didn't have the needed component added.
We will have a new VFX rain effect in our next release that will not need a component added to objects in the scene.

In the meantime you can add this to the scene.  Unzip
[SFRainVolumePrefab.zip](https://github.com/lgsvl/simulator/files/5777399/SFRainVolumePrefab.zip)

Right click in Project panel and select Import Package -> Custom Package...
Then place in SF scene here at this position/rotation like so
![RainHelp00](https://user-images.githubusercontent.com/45106230/103804228-9aad3300-5006-11eb-92ae-7657c27aa7e3.png)

Then save and build the bundle, rain will then work.  Let me know if you have any issues and sorry about missing this.
