### ISSUE TITLE
if there are two trrafic lights on one pole, then we need to create one or two?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1204]
if there are two traffic lights on one pole, then we need to create one or two?

1.If we create one signal then what if one pole having one signal for go_stright and one for Left_or_Right_turn?

2. if we create two signal separately then it will overlap with each other, due to red box detection. Then how to solve overlap issue?

 
In the picture below
1. blue box is Traffic light created by Unity
2. Red box is for Traffic light detection (created by perception)
3. green box is real world signal. 

![Screenshot from 2021-01-06 16-38-20](https://user-images.githubusercontent.com/61130487/103757777-301ee600-504c-11eb-83eb-1543bfcf281f.png)

**Comment by EricBoiseLGSVL** [comment]
@Addi2020 We currently support multiple traffic lights but they are the same state.  On the next release, we will provide many different traffic light models and multiple arrows/X/Uturn emission textures.
1) We do not yet have the logic for different states on the same roadway. You will need to create this logic or wait until we are able to implement
1.2) sounds like an issue with apollo.  We annotate the exact dimensions of the signal mesh. right @luqiang21 ?

**Comment by luqiang21** [comment]
@EricBoiseLGSVL You are right. The overlapping issue should be an issue with apollo. @Addi2020 Did you try to annotate both traffic lights and change the `Signal Type` to `MIX_3_HORIZONTAL`?
