### ISSUE TITLE
Jaguar and San Francisco map missing meshes??

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1207]
I just downloaded the  vehicle and map assets from github and put it in the vehicle and environment folders as described in the instructions. But when I load them in unity the meshes seem to be missing
![Untitled](https://user-images.githubusercontent.com/67900559/103971898-5359aa80-519e-11eb-8195-164d40dc57e3.png)
![sadfgsafdgsdafasdf](https://user-images.githubusercontent.com/67900559/103971902-5785c800-519e-11eb-99cc-5f0c40cb644e.png)

**Comment by EricBoiseLGSVL** [comment]
It looks like gitlfs might have messed up.  Close unity and run git lfs pull.  Open unity.  If this doesn't work, delete the repo and re clone.

**Comment by duongtran11** [comment]
Just figured out this only happens when I downloaded the .zip file. Everything is fine when I clone it using git clone. But before that I did reinstall gitlfs

**Comment by EricBoiseLGSVL** [comment]
Yes, the zip file doesn't have the assets, you must clone and have git lfs installed.
