### ISSUE TITLE
When I launch the Autoware in Docker, I can't open RVIZ, but the process crashes.

### ISSUE THREAD

**Issue by fengsiyu** [lgsvl/simulator#121]
Hello,everyone!
when I enter the  LGSVL Autoware Docker image,running as follows to launch autoware:

cd autoware/ros/
./run

appearing that an dialog box: 
"Failed to run /home/autoware/autoware/ros/run_proc_manager as user root
Unable to copy the user's Xauthorization file."
![无标题窗口_001](https://user-images.githubusercontent.com/16290673/55326889-6c0e3a00-54bb-11e9-8d20-549f977bedf1.png)

After loading all launch files, I press the "RVIZ" button, the window of RVIZ crashed and shutdown as follow.
![Runtime Manager_002](https://user-images.githubusercontent.com/16290673/55327298-58af9e80-54bc-11e9-8e3b-3fe081d51103.png)

Then I saw the command line shows as follows:
"Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface."
"(core dump) rosrun rviz rviz  Segment Fault"
![-home-autoware-shared_dir-autoware-data-my_launch_sf_map-my_motion_planning launch http:--localhost:11311_003](https://user-images.githubusercontent.com/16290673/55327578-f905c300-54bc-11e9-8f36-f38766ad3713.png)

So, I can't launch the RVIZ to set the goal destination as the instructions.
How should I solve it?

The picture below is the picture of RVIZ in instructions:
![readme-rviz](https://user-images.githubusercontent.com/16290673/55328038-07a0aa00-54be-11e9-8a42-2eaf33c68303.png)

**Comment by martins-mozeiko** [comment]
Hello.

I think your Nvidia driver is not installed (or is installed incorrectly). Please check that you can run `nvidia-smi` command on your host and inside docker. It should show available GPU model and driver version.

Or run `glxinfo | grep version` - this should show something like this:

    OpenGL core profile version string: 4.6.0 NVIDIA 418.56

If any of these two does not happen then you need to install driver. For Ubuntu you can gen Nvidia driver here: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by bl4ckrid3r** [comment]
I'm having the same issue, so I still couldn't figure out the problem. My NVIDIA drivers are working fine, but I still get that same error. Any help ?

**Comment by daviduhm** [comment]
@bl4ckrid3r Which Ubuntu version are you running on your host machine? If you are running Ubuntu 18.04, chances are your `Xauthority` file is not in your home directory on your host machine. In [run.sh](https://github.com/lgsvl/Autoware/blob/lgsvl_develop/docker/generic/run.sh), Autoware assumes that your `Xauthority` file is located in `/home/$USER/.Xauthority`, and it will fail to copy it if it's not there. If this is your case, you can try #231.

**Comment by martins-mozeiko** [comment]
We have released new version of simulator [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) that works with latest Autoware release 1.12 without any changes to Autoware code. Please check that this crash is still happening with latest Autoware.
