### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by ghoulich** [lgsvl/simulator#1217]
After I downloaded newest release (lgsvlsimulator-windows64-2020.06), then ran simulator.exe, clicked "Open Browser" button, I met "504 Gateway Time-out" in my Chrome browser, what happened to lgsvl account website?
![image](https://user-images.githubusercontent.com/3353241/104703631-87127280-5752-11eb-82e4-02653621ed06.png)

**Comment by zelenkovsky** [comment]
Sorry, server went down, could you please try again. We've restarted server.

Please re-open if there are any issues.
