### ISSUE TITLE
How to make sure our LiDAR is used GPU not CPU version?

### ISSUE THREAD

**Issue by KentTeng11** [lgsvl/simulator#122]
Since we use the LG simulator of the old version. We're not sure the version includes this feature of GPU LiDAR or not.

Thanks.

**Comment by martins-mozeiko** [comment]
GPU lidar was added on December 4. With some improvements few days later.
If you are using any commit or release after middle of December then you are using GPU for lidar.

You can check in source code - if you have Assets\Scripts\Lidar\LidarSensor.cs file which inside has `AsyncTextureReader` string, this means it is using GPU.
