### ISSUE TITLE
Off Screen Mode to Speed up Training Process

### ISSUE THREAD

**Issue by abhkri** [lgsvl/simulator#1226]
I am using python APIs to connect to LGSVL simulator. Usually, graphical display of simulator screen is not required during model training. Is there any way to run the simulator in the background without displaying it on screen. Apart from display, everything else should be working normal. This should be able to free up memory and in turn speed up training.

**Comment by EricBoiseLGSVL** [comment]
@abhkri we have a headless mode in WebUI that disables the main camera.  Unfortunately, HDRP still requires cameras to render.  We are looking at solutions currently
