### ISSUE TITLE
Error message importing xodr file

### ISSUE THREAD

**Issue by thkted** [lgsvl/simulator#1227]
Hi! 
I'm trying to import xodr file in lgsvl but keep popping up error messeges like below.

Failed to update map: You must specify a valid AssetBundle
Missing or wrong Map AssetBundle. Please check content website for updated bundle or rebuild the bundle

The file I'm trying to import is from OpenDrive file from the content tab in lgsvl site.
I appreciate to comment about this problem.
Thank you.
![Screenshot from 2021-01-26 00-00-18](https://user-images.githubusercontent.com/71545340/105785104-77e6bc80-5fbd-11eb-8d16-991894a8c98f.png)
![Screenshot from 2021-01-26 09-57-21](https://user-images.githubusercontent.com/71545340/105785109-7a491680-5fbd-11eb-95cc-84aec62313b7.png)

**Comment by EricBoiseLGSVL** [comment]
@thkted You cannot load a OpenDrive file this way.  Please see our documentation [here](https://www.lgsvlsimulator.com/docs/map-annotation/#import-map-annotations) and [here](https://www.lgsvlsimulator.com/docs/add-new-map/#video) on creating a new map.  You need the Unity editor, import the HDmap, create a mesh and then output a asset bundle that is linked in the WebUI like above.

FYI, next release will have the feature to auto create a mesh from the HDMap and a future release will support maps that are just HDMaps.
