### ISSUE TITLE
I want to know the performance of the computer that captured the video that ROSCON 2018 showed.

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#123]
https://www.youtube.com/watch?v=NgW1P75wiuA

What are the specifications of the computer you used to demonstrate here?

> [Recommended system](https://github.com/lgsvl/simulator):
> 4 GHz Dual core CPU
> Nvidia GTX 1080
> Windows 10 64 Bit

I think my specifications are higher than the recommended ones.
However, it doesn't work like a video.

 1. Try to return to the starting point from the target point.
 2. Look ahead distance is put behind the vehicle.

───────────────────────────────────────────────────────────────
Try to return to the starting point from the target point.
Look ahead distance is put behind the vehicle.
![1](https://user-images.githubusercontent.com/17079475/55524334-f2976700-56c7-11e9-8605-d0074651e189.gif)

![3](https://user-images.githubusercontent.com/17079475/55524338-f4f9c100-56c7-11e9-8d5f-6d14c8c83175.gif)

Stops on a short path.
![2](https://user-images.githubusercontent.com/17079475/55524336-f3c89400-56c7-11e9-918c-8fa8fe2857ad.gif)

**Comment by martins-mozeiko** [comment]
That video was recorded on Alienware desktop with Intel i7-7700 CPU and Nvidia 1080 GTX.
