### ISSUE TITLE
PythonAPI spawned NPC vehicles remain at the border of Map

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1233]
Hello Team,

I tried to use the function of pythonAPI to randomly spawn NPC vehicles in map of BorregasAve. However, they will not disappear like in the interactive mode when coming to the border of the map . How could I change the code to fix this? Thx in advance!

**Comment by EricBoiseLGSVL** [comment]
If you look in NPCManager, the API mode restricts despawning, just comment out the check for API mode

**Comment by Yimags** [comment]
Thx, it works for me.
