### ISSUE TITLE
Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:64)

### ISSUE THREAD

**Issue by wkuznik** [lgsvl/simulator#1234]
Can't build the simulator with Ubuntu 20 and node --version
v15.7.0

Error building WebUI
UnityEngine.Debug:LogError(Object)
Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:64)

**Comment by EricBoiseLGSVL** [comment]
did you install WebUI before trying to build the binary?  Please see #1188.  Are you able to run simulator in Editor with your changes?
