### ISSUE TITLE
What is recommended PC spec for Autoware & lgsvl

### ISSUE THREAD

**Issue by Hwang-Jongrak** [lgsvl/simulator#124]
I want to play Autoware & lgsvl on 1 PC.
What is recommended PC spec for Autoware & lgsvl.

**Comment by martins-mozeiko** [comment]
For best experience it is recommended to run simulator on Windows machine, as Unity and Nvidia drivers are more optimized on Nvidia. But it is possible to run everything on Linux. I recommend using 4 core CPU ~4GHz with Nvidia 1080 or similar GPU. Depending on how many sensors or how many pedestrians or other vehicles you want at same time, the specs can be lower.
