### ISSUE TITLE
Error in the intersection of the HD map in customer map

### ISSUE THREAD

**Issue by qiongwu1003** [lgsvl/simulator#1241]
Hi,
LGSVL team

I draw my own 3D map and HD map for Apollo. And I meet some errors in the HD map when I run simulator with Apollo. I use the "Modular" mode, refer to this [video](https://www.youtube.com/watch?v=781zkzN2xMg&feature=youtu.be). 
I drew HD map before and I do not met the issue. Could some give me some advice?

The issue is described bellow.
In some intersections, they always show like bellow. The vehicle will never move again.
![green_never_start](https://user-images.githubusercontent.com/65001214/106992683-09231380-67b4-11eb-8933-4ae2bbcaba22.png)
![green_stop](https://user-images.githubusercontent.com/65001214/106992686-0aecd700-67b4-11eb-96b0-479cbfe6376c.png)

And in some intersections even can not regonize the traffic lights.
![no_signal](https://user-images.githubusercontent.com/65001214/106992693-0d4f3100-67b4-11eb-80fc-44092082616d.png)

**But in some intersections do not have the issue, and they all drew in the same method as the error ones.**

The bellow is my HD map and the traffic light mesh.
![HD_map](https://user-images.githubusercontent.com/65001214/106992703-117b4e80-67b4-11eb-9667-0c3ee6e41b5b.png)
![trafficlight](https://user-images.githubusercontent.com/65001214/106992709-14763f00-67b4-11eb-9e3d-135236f16647.png)
![lightmesh](https://user-images.githubusercontent.com/65001214/106992714-16d89900-67b4-11eb-8996-c79f6d2c1fe2.png)

Thanks.

**Comment by EricBoiseLGSVL** [comment]
Any idea @lemketron ?

**Comment by qiongwu1003** [comment]
I met the "Pesdestrian NavMesh" error when I build and run the simulator. Is it related to the issue above?
![pedestrian NavMesh_error](https://user-images.githubusercontent.com/65001214/107137107-15d67180-6944-11eb-8ca5-182dea41b500.png)

**Comment by EricBoiseLGSVL** [comment]
No, you just can't spawn pedestrians.  You should create the NavMesh to remove this LogError.  What version of Apollo are you using?  There are issues currently with Apollo master and perception.

**Comment by qiongwu1003** [comment]
@EricBoiseLGSVL Thanks for your reply.

I use the Apollo simulator, but not the latest version. And I compared the newest with mine. The "generate_map" scriptor is not changed.

**Comment by EricBoiseLGSVL** [comment]
Yes, I think modular perception is only on Apollo 06.  Right @lemketron ?

**Comment by lemketron** [comment]
> Yes, I think modular perception is only on Apollo 06.  Right @lemketron ?

Modular testing should work on Apollo 5.0 as well as 6.0 and master.

Traffic lights may not be detected if the exported Apollo HD map does not have signal IDs that match those in the Simulator map.

Try exporting the Apollo HD map then building the asset bundle and then saving the environment. This should preserve the generated signal IDs as long as you're on 2020.06 or later. 

You could also try assigning the Signal IDs manually before exporting and building.

**Comment by EricBoiseLGSVL** [comment]
Ah, that's what I was missing.  Yes, if you manually annotate, you need to make sure all signals have signalIDs.  This should solve your issue.  Thanks @lemketron !

**Comment by qiongwu1003** [comment]
@EricBoiseLGSVL @lemketron 
Thank you very much, the issue has been solved.
