### ISSUE TITLE
Query on Velocity published from state function

### ISSUE THREAD

**Issue by abhkri** [lgsvl/simulator#1245]
Hi,

I am connecting to lgsvl simulator through Python APIs. If 'obs' is a NPC agent added to map environment, then we are accessing its velocity using obs.state.velocity. It has velocity is vx, vy and vz direction. Is this value published in m/s or is it in kmph?.

**Comment by EricBoiseLGSVL** [comment]
@abhkri Unity uses m/s for rigidbody velocity

**Comment by abhkri** [comment]
Thanks for the clarification.
