### ISSUE TITLE
new ego vehicle(simulator release 20.06)

### ISSUE THREAD

**Issue by junhyeokgang** [lgsvl/simulator#1258]
unity v 19.3.15
simulator release 20.06

hi,
i tried to create new ego vehicle Following tutorial video (https://www.youtube.com/watch?v=R_Z65kimCII)

after building my new vehicle

i got this error code : 

![1](https://user-images.githubusercontent.com/79246575/108477866-21784f80-72d7-11eb-8bfd-84a9a81f20dd.png)

i did googling and someone said you get a linux module.

but i remember when i installed unity 3.15, i checked both window(mono) and linux(mono).

could you please give some instruction  : (

thank you.

**Comment by lemketron** [comment]
In the [building an asset](https://www.lgsvlsimulator.com/docs/assets/#building-an-asset) documentation it says:

> IMPORTANT Windows and Linux support must be installed with Unity to build asset bundles.


In the simulator [build instructions](https://www.lgsvlsimulator.com/docs/build-instructions/) documentation (just after step 20) it says:
> NOTE You will get an error when building AssetBundles if either Windows or Linux support is not installed in Unity
> Open Unity Hub and go to the Installs tab
> Click the vertical 3-dots next to the Unity version of the Simulator
> Click Add Modules
> Check Windows Build Support (Mono) or Linux Build Support (Mono)
> Click Done

**Comment by junhyeokgang** [comment]
Open Unity Hub and go to the Installs tab 
-> i can't this method because when i installed unity 19.3.15 without unity hub.(my computer network has google download error) 

![2](https://user-images.githubusercontent.com/79246575/108487487-ac127c00-72e2-11eb-9266-69daf59b2633.png)

unity hub - >installs -> vertical 3-dots->there's no add module botton..

well, what your saying is that i reinstall unity 3.15v?  right?

thank you a lot

**Comment by junhyeokgang** [comment]
i do reinstall using unity hub. that error fixed
