### ISSUE TITLE
lgsvl_msgs object cannot be fetched for latest apollo-3.5 release

### ISSUE THREAD

**Issue by ankita9017** [lgsvl/simulator#126]
Cloning of submodule `lgsvl_msgs` for the latest `apollo-3.5` repo gives following error:
```
error: Server does not allow request for unadvertised object aa3eba60dc508f39e3049da7498530f8ae8373f7
Fetched in submodule path 'lgsvl_pkgs/lgsvl_msgs', but it did not contain aa3eba60dc508f39e3049da7498530f8ae8373f7. Direct fetching of that commit failed.
```

I check the commit history for the `lgsvl_msgs` repo and cannot find this commit. Is this commit published?

**Comment by martins-mozeiko** [comment]
Sorry about this. Submodules were not fully pushed to GitHub. Now everything is pushed correctly. Please try fetching latest code.
