### ISSUE TITLE
Cant not view images on Rviz when with 360 camera

### ISSUE THREAD

**Issue by Michealhao1991** [lgsvl/simulator#1274]
Hello i use the CameraSensorBase.cs  in #778  to creat a 360 camera ,but i cant not view the image in  Rviz ,
it seems  to have some problems with the size of the imageData.
Is there anything I haven't noticed？
![image](https://user-images.githubusercontent.com/46957559/109611389-1fc94a00-7b69-11eb-9d00-bdd49d4d1069.png)

![image](https://user-images.githubusercontent.com/46957559/109611198-d5e06400-7b68-11eb-9271-1082002374e3.png)

**Comment by EricBoiseLGSVL** [comment]
This seems like an issue with RViz.  Have you looked in the ROS forums?

**Comment by Michealhao1991** [comment]
> 这似乎是RViz的问题。您看过ROS论坛吗？
I have solved problem 
i set DistortedTexture = EquirectTexture in CameraSensorBase.CS and it worked.

**Comment by EricBoiseLGSVL** [comment]
Awesome and thanks for posting a solution for others.  You rock :)
