### ISSUE TITLE
Build WebUI Error

### ISSUE THREAD

**Issue by 201520906050** [lgsvl/simulator#1281]
I just followed the build instruction of the official doc，but when i came to the step 12 and 13, error occured like this：
![image](https://user-images.githubusercontent.com/54359641/110065929-4d9dd100-7dab-11eb-88e5-1a99389bb605.png)
and i tried the way to build it manually with `npm install` and `npm run pack`, but soon it came to this:
![image](https://user-images.githubusercontent.com/54359641/110066295-12e86880-7dac-11eb-9e6d-9d0f9382af17.png)
So could anyone help me with this annoying problem ?

**Comment by EricBoiseLGSVL** [comment]
Please see #1188 and see if that helps

**Comment by ZhenshengLee** [comment]
`npm run pack` did not work, `npm pack` just works.
