### ISSUE TITLE
Create map via API?

### ISSUE THREAD

**Issue by GiteZz** [lgsvl/simulator#1285]
We are thinking about using the simulator for testing our formula student autonomous car. Therefore we would like to test on many different maps to find the edge cases and racing performance. These maps are simple because they only consist of a concrete floor with cones marking the edges. How would you go about creating maps dynamically? Would this be possible via the python API?

**Comment by EricBoiseLGSVL** [comment]
@GiteZz It is not possible to create a map via API.  We require creating map assets with the Unity editor and then exporting as a asset bundle.  Although, we do have plans to make this possible in the near future ;)
