### ISSUE TITLE
map asset bundle is empty

### ISSUE THREAD

**Issue by auqdah** [lgsvl/simulator#1287]
hi!

I am trying to use a terrain map as a map object for the simulator but when attempting to build the asset bundle it says that it was formed incorrectly and has 0KB. Any ideas on where I went wrong?

**Comment by EricBoiseLGSVL** [comment]
@auqdah sorry terrains are not supported.  You can modify the bundle build code but even then, the terrain shader is not supported for lidar/depth/segmentation sensors.
