### ISSUE TITLE
Questions about weather factors

### ISSUE THREAD

**Issue by Yimags** [lgsvl/simulator#1289]
Hello Team,

I have 2 questions about weather factors.

1. I have noticed in the code of Python API that two new facters (cloudiness and damage) are available. I am wondering how they could  influence the simulation and behavior of the vehicle?

2. For rain and wetness etc. how is the value from 0 to 1 related to real-world physical values (humidity, friction of road)?

**Comment by EricBoiseLGSVL** [comment]
@Yimags 
1. These effects are for perception only at the moment.  We have plans to effect geometry and physics materials in the future.
2. It does not

**Comment by Yimags** [comment]
Thank you for response! 
`We have plans to effect geometry and physics materials in the future.`
Is there any documentations or instructions on how to realize it? It will be much useful for my work, thanks in advance!

**Comment by EricBoiseLGSVL** [comment]
[Here](https://assetstore.unity.com/packages/tools/physics/impact-deformable-4799) is one asset on the Unity Asset Store.
Just look up runtime mesh deformation.  As for physics materials, look up the Unity api for them.  You can create and add to the mesh colliders.  Then you can adjust the settings at runtime.
