### ISSUE TITLE
Simulator doesn't sent vehicle steering percent for apollo 3.5

### ISSUE THREAD

**Issue by kkhitsko** [lgsvl/simulator#129]
LGSLV simulator don't sent vehicle steering percent if simulator don't receive driving instruction to turn to the left or right.

This makes difficult to debug apollo 3.5 control algorithms using LSSVL simulator.

**Comment by martins-mozeiko** [comment]
Do you mean `steering_percentage` field on `/apollo/canbus/chassis` topic?

I can see it being set to correct values when either you are driving manually or Apollo is controlling the car.

In what situation it is not being set?

**Comment by kkhitsko** [comment]
> Do you mean steering_percentage field on /apollo/canbus/chassis topic?

Yes

> In what situation it is not being set?

When I drive vehicle manually and don't press left or right button, then steering_percenage field is not represented in  /apollo/canbus/chassis topic.

**Comment by hadiTab** [comment]
@kkhitsko the steering_percentage field disappears when the steering percentage is zero. When you are not pressing the left or right key the steering percentage will quickly go back to zero. We implemented it this way to make it easier to drive with the keyboard.

**Comment by martins-mozeiko** [comment]
Steering value should be published to Apollo in latest [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) release.
