### ISSUE TITLE
Exception: PLY file has unsupported property type int

### ISSUE THREAD

**Issue by Michealhao1991** [lgsvl/simulator#1294]
hello, I can not import ply file ,and there is a error in editor
"Exception: PLY file has unsupported property "
![image](https://user-images.githubusercontent.com/46957559/110922169-574ea800-835a-11eb-93f4-a13942abe1b6.png)
 
But i cant open it on CloudViewer
![image](https://user-images.githubusercontent.com/46957559/110922546-c3c9a700-835a-11eb-9a2a-177100e98c91.png)

**Comment by EricBoiseLGSVL** [comment]
@kamkolak Is this fixed in latest as far as you know?
@Michealhao1991 can you post the file here for us to try parsing it?

**Comment by Michealhao1991** [comment]
> @kamkolak Is this fixed in latest as far as you know?
> @Michealhao1991 can you post the file here for us to try parsing it?

I downland from this adress: https://github.com/lgsvl/simulator/issues/1294#issuecomment-797828337

**Comment by Michealhao1991** [comment]
ply adress  : https://www.cc.gatech.edu/projects/large_models/dragon.html
I try to convert ply to pcd  and  it worked.

**Comment by EricBoiseLGSVL** [comment]
Ah, yes we have updates in the next release to support .ply files but pcd are only working in this release

**Comment by Michealhao1991** [comment]
> Ah, yes we have updates in the next release to support .ply files but pcd are only working in this release

I found another problem in my pointcloudRender ，there is no vertical mesh was generated:
![image](https://user-images.githubusercontent.com/46957559/111100080-e558a780-8581-11eb-8da4-665aa18a40c3.png)

**Comment by EricBoiseLGSVL** [comment]
@Michealhao1991 what do you mean vertical mesh?  The point cloud is rendering the data provided.  Maybe the conversion to pcd is not working correctly?
