### ISSUE TITLE
LGSVL with SUMO 

### ISSUE THREAD

**Issue by LEE-HONGGYU** [lgsvl/simulator#1304]
Hello

I have a question.
I have even tried to run SUMO and UNITY (2019.3.3f1) simultaneously through UDP communication, which I would like to expand and apply to LGSVL.  

I would like to integrate or synchronize SUMO's TRAFFIC vehicles with LGSVL through any form of communication. Is this possible? If possible, I would appreciate it if you could tell me in detail what kind of method there is.

(PLUS) Earlier, another person asked this question, so please add an answer to it.. #779 

Thanks a lot

**Comment by lokesku** [comment]
Please follow discussion here: https://github.com/lgsvl/simulator/issues/779
