### ISSUE TITLE
Seems to be there is problem with the loading of vector map.

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#131]
1. Is the vector map you gave normal?
Even though i have followed the suggestion as mentioned in the previous comment, but still couldn't able to load vector map. #106

2. Is there a problem with the compatibility of the simulator? 
      Below are the things I've tried.
	 **Commits**
-93d92d6becc8dbced0a588aadcf0cee18e2c2429
-e3cfe709e4af32ad2ea8ea4de85579b9916fe516
-d71dfdcb2cee3103cc3fd9e25107e7813ac3100d 
	 **Cuda**
-9.0
-8.0
	 **GPU**
-NVIDIA 1070Ti
-NVIDIA TITAN X(Pascal)
**Autoware**
One version was from LG and the other two, the latest and the older versions, were from autowere site.

**Comment by martins-mozeiko** [comment]
Can you try with e3cfe709e4af32ad2ea8ea4de85579b9916fe516 commit for autoware-data repository?
I just tried with this one and it loaded smaller part of SF in rviz.

The problem with later commits is that they work, but they are super slow. Depending on computer (CPU, not GPU) it may take few minutes to load all information of vector map. But the map data files itself are correct and usable.

I cannot speak for code from autware github, it may or may not work - as they are modifying autoware and we are currently not rebasing our fork on top of their master.

**Comment by ehduk90** [comment]
It's working normally now.
The used version is 824d8f2047caaea 983372cbeb107ea1201509e36c

**Comment by yangjiongfeng** [comment]
@ehduk90 
I made the same mistake as you.
How did you solve it?
Where can I download your autoware-data files?
