### ISSUE TITLE
Error when signing up a new SVL 2021.1 cloud account

### ISSUE THREAD

**Issue by AIasd** [lgsvl/simulator#1310]
![example](https://user-images.githubusercontent.com/12670254/112661827-54a98380-8e2d-11eb-85dd-817b5869f822.png)

Hi team,

I am encountering error when trying to sign up an account. Any ideas on this error?

Thanks!

**Comment by TrentWeiss** [comment]
I am also noticing the new cloud-based system is quite buggy (although I was eventually able to create an account).

Most of the features spelled out in the docs result in the system just hanging for a few minutes, possibly followed by a largely unhelpful error message like "'asdf' was not created" (where 'asdf' is the name of the new Sensor config I was trying to make).

Perhaps their cloud-based backend is overwhelmed by people excited to use the new release?

**Comment by AIasd** [comment]
After trying again several times at different time, I succeeded creating the account finally.

**Comment by lokesku** [comment]
Thanks for your report. We are continuously improving and with cloud based web user interface, we will be able to roll out updates with fixes more often now.
