### ISSUE TITLE
Indianapolis Motor Speedway map GPS coordinates are not correct

### ISSUE THREAD

**Issue by mslavescu** [lgsvl/simulator#1312]
The GPS orientation and  origin of the map seems to be off, compared with iRacing track right side, that can be downloaded from Z1 Dashboard (part of the txt file also).

Z1: The Dashboard & Telemetry Analysis Suite For Every Sim and Real World Racer!
https://z1simwheel.com/dashboard/index.cfm

Indianapolis Motor Speedway map
https://wise.svlsimulator.com/maps/profile/62765742-57bf-4ccd-85e5-db8295d34ead

Here you can see some of my calculations trying to reposition a GPS trace captured by doing a few laps on the new LGSVL 2021.1 simulator.

[indianapolis-iRacing-ovalTrackDataRight-vs-LGSVL-driving-keyboard.xlsx](https://github.com/lgsvl/simulator/files/6218307/indianapolis-iRacing-ovalTrackDataRight-vs-LGSVL-driving-keyboard.xlsx)

Here is the GPS trace from the driving around, you can see how off is the LGSVL trace (red line) vs iRacing (blue):

[0328165256-74178.txt](https://github.com/lgsvl/simulator/files/6218335/0328165256-74178.txt)

![Screenshot_20210328_195252](https://user-images.githubusercontent.com/461669/112772525-52971e80-8fff-11eb-8f31-c7944a38d1e5.png)

Best position I could get:

[0328163806-74178.txt](https://github.com/lgsvl/simulator/files/6218309/0328163806-74178.txt)

![Screenshot_20210328_194323](https://user-images.githubusercontent.com/461669/112772296-f5e73400-8ffd-11eb-94f2-4a105f6b1a80.png)

You can load the TXT files here to analyze:
https://www.gpsvisualizer.com/draw/?api=g&bg=h&z=20&c=39.799438,-86.230606&marker=

**Comment by EricBoiseLGSVL** [comment]
@mslavescu This seems like a bug with the position of the map origin.  We will look into this

**Comment by mslavescu** [comment]
@EricBoiseLGSVL do you have any update on this issue?

**Comment by EricBoiseLGSVL** [comment]
It is fixed and will be in the next release.  Thanks for your patience and letting us know.  It is still a bit off but since the map is not an exact digital twin, it is more precise.

**Comment by mslavescu** [comment]
@EricBoiseLGSVL I extracted the coordinates from Lanet2 file from SVL IMS map:
[IndianapolisMotorSpeedway-gps.txt](https://github.com/lgsvl/simulator/files/6761493/IndianapolisMotorSpeedway-gps.txt)

Can be loaded here and viewed, just set max 1500 point before click Import:

https://www.gpsvisualizer.com/draw/?api=g&bg=h&z=20&c=39.799438,-86.230606&marker=

This should help with tuning of the algorithm for the SVL map, which is not accurate, as you can see here:

![Screenshot_20210704_232212](https://user-images.githubusercontent.com/461669/124415139-31db1500-dd22-11eb-822f-a99de2abe821.png)
![Screenshot_20210704_232150](https://user-images.githubusercontent.com/461669/124415142-330c4200-dd22-11eb-9e2a-62ba160c36ba.png)

Would be possible to update the IMS map to match as close as possible the actual left/right sides of the track?

**Comment by EricBoiseLGSVL** [comment]
In our next release we have a tool that can try to reduce errors with map origin.  This is the best we can do since this map is not a digital twin but an approximation.  We don't have plans currently to redo this map sorry.

**Comment by lemketron** [comment]
I'd be curious to hear more about why the exactness of the track matters. Are you trying to do some training that is location-specific? 

We do not expect (or support) the exported HD maps from this environment to be used in any real world in-vehicle testing, so hopefully that's not it...
