### ISSUE TITLE
Run Simulation,but could not connect to SVLSimulator, and SVLSimulator becomes Offline.

### ISSUE THREAD

**Issue by zhp-ncu-dev** [lgsvl/simulator#1316]
The error tips are " Error on latest run: Simulator aa6fe61b-48b0-4b72-ab94-82711e9cf645 unresponsive during starting. "

**Comment by ruoxianglee** [comment]
Hi, I got the same problem after clicking Run Simulation, have you fixed the problem? Could you please give me some advice on that? Thanks.
