### ISSUE TITLE
 Would like to create scenarios with the pedestrian in cross walk which is currently not included in the simulator.

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#132]
The current simulator doesn't included pedestrian crossing the road in crosswalk.
Although there are pedestrian  walking in the sidewalk, but not on the crosswalk.
It will be more helpful, if the simulator includes pedestrian on the crosswalk scenarios.

**Comment by martins-mozeiko** [comment]
We have plans to make pedestrians walk on the crosswalk. But I don't have more detailed timeline on this feature.

**Comment by ehduk90** [comment]
> We have plans to make pedestrians walk on the crosswalk. But I don't have more detailed timeline on this feature.

Thank you very much for your prompt reply.

**Comment by outmanlol** [comment]
@martins-mozeiko I want to build a senerio that pedestrian walk cross the road ,but the pedestrian can not move on the road area. I dont know why? Is it a bug?

**Comment by martins-mozeiko** [comment]
@outmanlol Please see this answer how to modify areas where pedestrian can walk: 
#170
