### ISSUE TITLE
rain is not visible with python api control 

### ISSUE THREAD

**Issue by 20171CSE0680** [lgsvl/simulator#1320]
I am trying to simulate all weather conditions but rain is not working with API but with normal simulation, it is changeable and visible.

i am using version 2021.1 (because version 2020.6 is not connecting to python API
![Screenshot 2021-03-30 131323](https://user-images.githubusercontent.com/60212283/112952461-2217c780-915a-11eb-8670-43a69571a910.png)
![Screenshot 2021-03-30 131539](https://user-images.githubusercontent.com/60212283/112952498-2e9c2000-915a-11eb-9e89-ad69a85a3572.png)
![Screenshot 2021-03-30 131601](https://user-images.githubusercontent.com/60212283/112952502-3065e380-915a-11eb-8343-8c009bfb4bf0.png)

)

**Comment by mslavescu** [comment]
For 2020.06 use the corresponding tag from PythonAPI, master works only with 2021.1:
https://github.com/lgsvl/PythonAPI/tree/2020.06

**Comment by EricBoiseLGSVL** [comment]
@20171CSE0680 we will look into the API weather control with API, thanks for the heads up.  @mslavescu Thanks for helping with 06 API issue.

**Comment by rajeshjoshi8792** [comment]
i m getting same problem. rain is not working using api.

**Comment by EricBoiseLGSVL** [comment]
fixed and will be in next release.  Thank you for posting this issue.  Rain changed to use the visual effect graph particle system and needed a change to the way it is initialized.
