### ISSUE TITLE
How to make the vehicle move backward through the keyboard control？

### ISSUE THREAD

**Issue by ideasplus** [lgsvl/simulator#1333]
I encountered a strange problem where I can't make the vehicle move backward through the keyboard control while other commands work well such as moving forward, truning left. When I press the ↓ button the car just slow down and then stop still.

**Comment by lemketron** [comment]
You'll need to use the page-up and page-down commands to shift to forward and reverse, respectively.
https://www.svlsimulator.com/docs/user-interface/keyboard-shortcuts/

**Comment by ideasplus** [comment]
> You'll need to use the page-up and page-down commands to shift to forward and reverse, respectively.
> https://www.svlsimulator.com/docs/user-interface/keyboard-shortcuts/

Thank you so much for your feedback。
