### ISSUE TITLE
svlsimulator-linux64-2021.1与Autoware1.14联合仿真网页无法接收topic / vehicle_cmd

### ISSUE THREAD

**Issue by Stuare8** [lgsvl/simulator#1348]
svlsimulator-linux64-2021.1
仿真器Info
中报错如下图所示：

![2021-04-08 11-29-23 的屏幕截图](https://user-images.githubusercontent.com/64180095/113966056-03ec4e80-9861-11eb-98ff-a58d8c340266.png)
![2021-04-08 11-30-04 的屏幕截图](https://user-images.githubusercontent.com/64180095/113966057-03ec4e80-9861-11eb-8e6f-402a3f30c8a3.png)
![2021-04-08 11-31-08 的屏幕截图](https://user-images.githubusercontent.com/64180095/113966077-09499900-9861-11eb-8dd2-e968f1e665a8.png)
![2021-04-08 11-31-45 的屏幕截图](https://user-images.githubusercontent.com/64180095/113966086-0c448980-9861-11eb-964d-486784fbd730.png)
![2021-04-08 11-44-46 的屏幕截图](https://user-images.githubusercontent.com/64180095/113966095-0d75b680-9861-11eb-88fb-731dd43821de.png)

**Comment by EricBoiseLGSVL** [comment]
Hello, please describe your issue in english.  Also post your player.log so we can see the stack trace or grab the details from the first null error and trace and post here.

**Comment by Stuare8** [comment]
@EricBoiseLGSVL The problem has been solved.Thank you

**Comment by EricBoiseLGSVL** [comment]
Excellent, glad you were able to solve
