### ISSUE TITLE
How to get Stop Line Sensor Callbacks by Python API?

### ISSUE THREAD

**Issue by ssbse2021** [lgsvl/simulator#1358]
Hello team,
I checked the [Test Results webUI page](https://www.svlsimulator.com/docs/user-interface/web/test-results/), shown below:
![image](https://user-images.githubusercontent.com/78254341/114301407-49c24480-9af7-11eb-9da1-08cf281833af.png)
and I want to get the callbacks by python APIs,  and I followed the [instructions](https://github.com/lgsvl/ComfortSensor) of how to get [Comfor Sensor](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#comfort-sensor) Callback by on_custom() API, and I successed to get the Comfort Sensor Callbacks.
![image](https://user-images.githubusercontent.com/78254341/114301452-9279fd80-9af7-11eb-83f0-272f9b40c84a.png)
But when I added [Stop Line Sensor](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#stopline-sensor) and tried to get the StopLineViolation Callbacks, I found there is no data when the ego viloated the red light.
Anyone know what's the problem? Thanks in advance.

**Comment by EricBoiseLGSVL** [comment]
What do you set the stop line sensor threshold in the sensor parameters?  You may need to increase.  Do you have any errors in the playerlog?

**Comment by DeepCollision** [comment]
> What do you set the stop line sensor threshold in the sensor parameters? You may need to increase. Do you have any errors in the playerlog?
Hi @EricBoiseLGSVL , I set the threshold to 1, and the sensor setting can be seen in the following:
![image](https://user-images.githubusercontent.com/78254341/114645884-d4c85800-9d0c-11eb-9fdb-a5e50e94b47e.png)
 
I collected the Stop Line Callbacks following the steps below:

1. Added a Stop line Sensor to the vehicle using the WebUI configuration page, see following picture:
![image](https://user-images.githubusercontent.com/78254341/114647228-528d6300-9d0f-11eb-97e6-1e7485790c2a.png)
2. Created a simulation in API Only mode, see following picture:
![image](https://user-images.githubusercontent.com/78254341/114647473-bd3e9e80-9d0f-11eb-92dc-45c2867eed57.png)
3. Wrote the Callback function for Stop Line Sensor,
![image](https://user-images.githubusercontent.com/78254341/114647763-3c33d700-9d10-11eb-961b-d9f9079779c2.png)
4. Then I called the function on_custom() to caputure the Callbacks:
![image](https://user-images.githubusercontent.com/78254341/114647968-8fa62500-9d10-11eb-80ff-510daf8593ab.png)
5. I ran the script and control the vehicle to violate red light, but there was no message printed. I visualized the sensor message in the simulator and the violation is indeed true.
![image](https://user-images.githubusercontent.com/78254341/114648554-a39e5680-9d11-11eb-8f74-aae778d11abe.png)
6. Then I checked the WebUI to see the test results, all the stop line violations were recorded.
![image](https://user-images.githubusercontent.com/78254341/114648724-e06a4d80-9d11-11eb-8b38-5fa116eb13c3.png)

- But it confused me a lot why there is messge output in my python script. 
- I followed your suggestion to increase the stop line threshold to 10, but the result remained the same as before.
- You suggested to check the playerlog, do you mean i need to check the WebUI of LGSVL?

**Comment by EricBoiseLGSVL** [comment]
Ah, I see, sensor is working but the api custom callback is not working.  The custom callback is called in simulator and sends to api.  It's not called in API.  Why are you editing the python api code?

**Comment by DeepCollision** [comment]
> Ah, I see, sensor is working but the api custom callback is not working. The custom callback is called in simulator and sends to api. It's not called in API. Why are you editing the python api code?
Hi @EricBoiseLGSVL, I followed the instruction of [API EXAMPLE](https://github.com/lgsvl/ComfortSensor) in Comfort Sensor to write the api code. See below:
![image](https://user-images.githubusercontent.com/78254341/114961696-eb50e980-9e9b-11eb-82d7-7e36ba13537c.png)

To answer your question about why am I editing the python api code, i just want to get the callback of Stop Line Sensor in my python scripts. Is there any method to get the callbacks by calling apis in python scripts?

**Comment by EricBoiseLGSVL** [comment]
Hmm, that looks right and should work.  We'll need to look into this more.  Thanks for clarifying.

**Comment by DeepCollision** [comment]
> Hmm, that looks right and should work. We'll need to look into this more. Thanks for clarifying.

Thanks, hope for your reply

**Comment by ssbse2021** [comment]
> > Hmm, that looks right and should work. We'll need to look into this more. Thanks for clarifying.
> 
> Thanks, hope for your reply

@EricBoiseLGSVL Hi, is there any method to get the stopline callback by python API? any progross of that?

**Comment by EricBoiseLGSVL** [comment]
Sorry, we are trying to get the next release out the door.  We will look into this @revati-naik can you log a bug please?

**Comment by revati-naik** [comment]
@ssbse2021 The bug has been reported. Will follow up here if we have any findings. Thanks.

**Comment by gorkemkrdmn** [comment]
Would it be possible to use Bridge to access Stop Line Sensor? For example, maybe one can implement a sensor plugin and inside that plugin, it can subscribe to a topic of Bridge.

**Comment by EricBoiseLGSVL** [comment]
Yes, that is the best way.  We haven't released source code for stopline sensor, I'll check if we plan to.  In the meantime, yes, create the sensor with the logic and be sure to include the conversion data types/factory type for the bridge.  See DifferentialDriveControlSensor.

**Comment by KarByc** [comment]
Hello @ssbse2021 

We've just fixed issue with the StopLineSensor not calling custom callbacks.
It will be available in the next release.
The kind value for the StopLineSensor in the PythonAPI is "stopLineSensor".

Thanks for your detailed report, it was really useful!

**Comment by JasonBourne1998** [comment]
> Hello @ssbse2021
> 
> We've just fixed the issue with the StopLineSensor not calling custom callbacks. It will be available in the next release. The kind value for the StopLineSensor in the PythonAPI is "stopLineSensor".
> 
> Thanks for your detailed report, it was really useful!

Since I konw there would be no more update right now, could you please give me some advices then I can try to fix it by myself?

**Comment by KarByc** [comment]
> > Hello @ssbse2021
> > We've just fixed the issue with the StopLineSensor not calling custom callbacks. It will be available in the next release. The kind value for the StopLineSensor in the PythonAPI is "stopLineSensor".
> > Thanks for your detailed report, it was really useful!
> 
> Since I konw there would be no more update right now, could you please give me some advices then I can try to fix it by myself?

This issue should be already fixed. AFAIK all the updates were released before closing the project. Are you not getting the custom callbacks on the latest version?

**Comment by JasonBourne1998** [comment]
> > > Hello @ssbse2021
> > > We've just fixed the issue with the StopLineSensor not calling custom callbacks. It will be available in the next release. The kind value for the StopLineSensor in the PythonAPI is "stopLineSensor".
> > > Thanks for your detailed report, it was really useful!
> > 
> > 
> > Since I konw there would be no more update right now, could you please give me some advices then I can try to fix it by myself?
> 
> This issue should be already fixed. AFAIK all the updates were released before closing the project. Are you not getting the custom callbacks on the latest version?
![2022-06-19 21-28-08 的屏幕截图](https://user-images.githubusercontent.com/51346614/174483556-cda19cd9-8960-45ba-b8ad-99259e725e01.png)

I guess there is no callbacks since I only get comfort sensor

![2022-06-19 21-20-05 的屏幕截图](https://user-images.githubusercontent.com/51346614/174483534-34c636b1-a329-43cf-ad5e-68bd47acf087.png)
![2022-06-19 21-22-30 的屏幕截图](https://user-images.githubusercontent.com/51346614/174483545-a5821c34-c2d0-4f7c-93bb-ebe1d7a88db0.png)
