### ISSUE TITLE
Can't create a writer with empty channel name!

### ISSUE THREAD

**Issue by DeepCollision** [lgsvl/simulator#1359]
I am running Apollo following these steps:
./docker/scripts/dev_start.sh
./docker/scripts/dev_into.sh
bootstrap.sh
When i want to enable the cyber bridge by typing:
bridge.sh
there came an error saying 'E0411 21:16:49.980556 8788 node_channel_impl.h:154] [cyber_bridge] Can't create a writer with empty channel name!'
![image](https://user-images.githubusercontent.com/78254341/114306921-0e803f80-9b10-11eb-9fa0-4b75cfe9fc19.png)

Anyone know what's the problem?

**Comment by DeepCollision** [comment]
I got the answer. The sensor deployed on the vehicle need to have a channel name! I will close the issue.

**Comment by enginlien** [comment]
Hi DeepCollision

I also encountered the same problem,
can you teach me,
how can i fix this problem.

thanks

![Screenshot from 2021-07-29 18-40-16](https://user-images.githubusercontent.com/87757542/127482133-4151d9fb-5e3d-4df7-917e-4313cc8786cf.png)

**Comment by lemketron** [comment]
Channel names are configured in the sensor json file (see `Topic`), as documented here:
https://www.svlsimulator.com/docs/simulation-content/sensors-list/#how-to-specify-a-sensor
