### ISSUE TITLE
Collecting data from camera and sensor

### ISSUE THREAD

**Issue by kk2491** [lgsvl/simulator#136]
Hi Guys,

Thanks for this wonderful simulator. 

Could you please let me know is there a way I can collect Image data and sensor (lidar) data from the simulator by running it in standalone mode. (not with Apollo or Autoware)

Thank you,
KK

**Comment by martins-mozeiko** [comment]
This is possible with our newly released Api. Check the readme in [Api](https://github.com/lgsvl/simulator/tree/master/Api) folder. Small examples how to saving lidar data and camera image are available under [quickstart](https://github.com/lgsvl/simulator/tree/master/Api/quickstart) folder - check the [06-save-camera-image.py](https://github.com/lgsvl/simulator/blob/master/Api/quickstart/06-save-camera-image.py) and [07-save-lidar-point-cloud.py](https://github.com/lgsvl/simulator/blob/master/Api/quickstart/07-save-lidar-point-cloud.py) files.

We are currently writing documentation for this with more details.

**Comment by kk2491** [comment]
@martins-mozeiko Thats great. That would be really useful. Just wanted to know if the prebuilt version is released with Python API ? 

Thank you,
KK

**Comment by shmily-skx** [comment]
> This is possible with our newly released Api. Check the readme in [Api](https://github.com/lgsvl/simulator/tree/master/Api) folder. Small examples how to saving lidar data and camera image are available under [quickstart](https://github.com/lgsvl/simulator/tree/master/Api/quickstart) folder - check the [06-save-camera-image.py](https://github.com/lgsvl/simulator/blob/master/Api/quickstart/06-save-camera-image.py) and [07-save-lidar-point-cloud.py](https://github.com/lgsvl/simulator/blob/master/Api/quickstart/07-save-lidar-point-cloud.py) files.
> 
> We are currently writing documentation for this with more details.

This is great, so can I use this API directly in windows or ubuntu? How is the lgsvl library file imported? Still need to use rosbridge?

**Comment by martins-mozeiko** [comment]
Yes, API can be used on any platform - regardless of where simulator is running. "lgsvl" library is our Python API module.

rosbridge is needed only if you are interacting with AD stack. API itself communicates directly to simulator.

**Comment by Martin20** [comment]
Is that possible to change the camera scene size? If so, where?

**Comment by Barburat** [comment]
I'm trying to open the links to the Api readme folder and the quickstart folder but it only leads to a 404 page not found. Is there another way of getting the info?

**Comment by Martin20** [comment]
Did you try this:

https://github.com/lgsvl/PythonAPI
