### ISSUE TITLE
Issue importing Blender .fbx into SVL simulator

### ISSUE THREAD

**Issue by sisaha9** [lgsvl/simulator#1360]
Follow up from #1337

I created a small road network for a track we were planning to use and tried importing into SVL. The textures come out all blackened even after setting materials to use external and take names from model's materials.

Here is how it's appearing on the SVL software

![Screenshot from 2021-04-11 22-38-53](https://user-images.githubusercontent.com/49205122/114345506-b6007080-9b16-11eb-84ab-e08d78c65fbc.png)

Attached below is a link to the .fbx file. It has been exported from Blender with experimental transform and textures embedded (done by enabling Copy and Embed during export). I have provided the .blend too if it helps in debugging. Thanks!

https://drive.google.com/drive/folders/1jk-k7Qfmz6B3HZ4Y6fOOl3eO3uM8cwIN?usp=sharing

**Comment by EricBoiseLGSVL** [comment]
Do you have the editor light feature on?

![image](https://user-images.githubusercontent.com/45106230/114477486-1b08a480-9bb1-11eb-89eb-43ea85dd0c2e.png)

**Comment by sisaha9** [comment]
Ah that did reduce the effect a bit but the textures still don't load

![Screenshot from 2021-04-12 17-24-47](https://user-images.githubusercontent.com/49205122/114478837-0974cc00-9bb4-11eb-9500-ca3446040eff.png)

**Comment by EricBoiseLGSVL** [comment]
Are the textures embedded in the fbx?  If so, you will need to extract from the model.
![image](https://user-images.githubusercontent.com/45106230/114488991-2ff03280-9bc7-11eb-810e-095d70c4d688.png)

If not you will need to import and create materials to apply the textures.  Then you need to apply the textures to the mesh.
![image](https://user-images.githubusercontent.com/45106230/114489038-48f8e380-9bc7-11eb-9b28-69a34343601d.png)
![image](https://user-images.githubusercontent.com/45106230/114489087-6332c180-9bc7-11eb-882e-6975318b8e05.png)

**Comment by sisaha9** [comment]
I think the issue was my materials were textures. I created new materials with the HDRP pipeline and embedded my textures into it. After that updated all the objects. My grass plane was still not loading. The Unity HDRP template came with a ground object so I modified it to use my material. It is now working

![Screenshot from 2021-04-13 00-13-12](https://user-images.githubusercontent.com/49205122/114517374-22e93880-9bf3-11eb-85be-9e9cfbf299b3.png)

This screenshot was taken from the default HDRP project but the textures load in the simulator project as well. However, while following the video here: https://www.svlsimulator.com/docs/simulation-content/add-new-map/. I am stuck on the Play button. It shows no cameras rendering and stays

![Screenshot from 2021-04-13 00-58-21](https://user-images.githubusercontent.com/49205122/114517612-5e840280-9bf3-11eb-86e6-f2d2b6a24035.png)

Is there anything I am doing wrong?

**Comment by EricBoiseLGSVL** [comment]
You need to start with Loader scene.  You create the asset bundle with your new map and add it to the simulation you create in WebUI.  Then you can run the map in editor.

**Comment by sisaha9** [comment]
Is there a video showing how to start with Loader scene? The video I linked above just created a new scene, added the prefab and running worked

**Comment by EricBoiseLGSVL** [comment]
This was made with an older version of simulator.  With the new WebUI you need to run from Loader.scene in Editor.  Just search Loader or go to Assets/Scenes folder.  We have development settings to run from scene but we need more work to support cloud webui.

**Comment by sisaha9** [comment]
Is there updated documentation I can follow for building a map then? Or are all the steps in the forementioned video and just for loading I need to take the prefab elsewhere

**Comment by EricBoiseLGSVL** [comment]
Documentation is [here](https://www.svlsimulator.com/docs/user-interface/web/library/) for uploading maps.  You need to create asset bundles of the map and upload to webui and add to a simulation to run. Run loader scene, open WebUI, upload map, make simulation with the map, run simulation.

**Comment by sisaha9** [comment]
Sorry I should have added. I wanted ways to test during development. I was able to build and successfully run on simulation but everytime I wanted to make a change I would have to go back to the scene, republish, re-add and try which was getting cumbersome

**Comment by lemketron** [comment]
You might want to check out the "[Developer Mode](https://www.svlsimulator.com/docs/running-simulations/developer-mode/)" and "[Testing Custom Assets with the Unity editor](https://www.svlsimulator.com/docs/installation-guide/build-instructions/#testing-custom-assets-with-the-unity-editor)" documentation.

**Comment by sisaha9** [comment]
I see. I was able to successfully convert the .fbx into a map so that's the end of this issue. Thanks for the resources and all the help in this thread!
