### ISSUE TITLE
How to fix the seed inside the code?

### ISSUE THREAD

**Issue by MartinaB85** [lgsvl/simulator#1361]
Good morning,

I'm using your simulator through PythonAPI and I would need to fix the seed inside the code (i.e. in the NPCLaneFollowController.cs script or any other related script) and not through the http://localhost:8080/.

How can I do that?

Thank you in advance for your help,

Martina

**Comment by EricBoiseLGSVL** [comment]
@MartinaB85 Hello, you can hardcode this value in Loader.cs on line 125.

**Comment by MartinaB85** [comment]
How am I supposed to code it?
The seed is defined inside other functions..should I put simulation.seed = 2020 for example before return in line 125?
Should I change it instead at line 858 ?

Thank you very much,

Martina

**Comment by lemketron** [comment]
> I'm using your simulator through PythonAPI and I would need to fix the seed inside the code (i.e. in the NPCLaneFollowController.cs script or any other related script) and not through the http://localhost:8080/.

@MartinaB85 If you're using Python API, you can set the seed in `sim.load` as documented here: https://www.svlsimulator.com/docs/python-api/python-api/#simulation

**Comment by EricBoiseLGSVL** [comment]
@lemketron yeah I thought that @MartinaB85 didn't want to use the api but yes it is there
