### ISSUE TITLE
Problems with generating map in lgsimulator

### ISSUE THREAD

**Issue by lovebigwei** [lgsvl/simulator#1376]
HI, I am following the guide to import hd map from apollo5.0 to lgsimulator and generate it's correspondent map used in lg. I have build the map using unity. Bet when I upload the map to lg, it says the folloing error.
Unexpected error occurred. Please try again later or contact administrator
![Screenshot from 2021-04-16 11-05-12](https://user-images.githubusercontent.com/59685771/114965814-ef810500-9ea3-11eb-98bf-2aa1ccb7fbe5.png)

**Comment by EricBoiseLGSVL** [comment]
can you post the asset bundle here so I can look?

**Comment by lovebigwei** [comment]
> can you post the asset bundle here so I can look? or open in zip program and screen shot so I can see the contents?

![Screenshot from 2021-04-16 11-32-42](https://user-images.githubusercontent.com/59685771/114967707-8602f580-9ea7-11eb-8a85-6620ffb5d08e.png)
![Screenshot from 2021-04-16 11-32-49](https://user-images.githubusercontent.com/59685771/114967713-88fde600-9ea7-11eb-8a4e-0c1ab7d6b37e.png)
here it is

**Comment by lovebigwei** [comment]
or may be you are refering to this ?
![Screenshot from 2021-04-16 11-34-42](https://user-images.githubusercontent.com/59685771/114967874-cf534500-9ea7-11eb-8c25-16914f30a511.png)

**Comment by EricBoiseLGSVL** [comment]
Open environment_newmap so we can see if the required data is correctly built.

**Comment by lovebigwei** [comment]
> Open environment_newmap so we can see if the required data is correctly built. Also, details on the size of the file helps.

When I try to extract files in environment_newmap, it says error ,the size of the file is 445.0 kB.
![Screenshot from 2021-04-19 08-54-18](https://user-images.githubusercontent.com/59685771/115168306-036b7780-a0ed-11eb-8ea5-2b8d036882df.png)
![Screenshot from 2021-04-19 08-54-24](https://user-images.githubusercontent.com/59685771/115168309-05353b00-a0ed-11eb-88b9-a324eceb13ca.png)

**Comment by EricBoiseLGSVL** [comment]
Can you post the file here?  If not, use 7zip to look inside without extracting

**Comment by lemketron** [comment]
This sounds like it may be related to https://github.com/lgsvl/simulator/issues/1364 (and tracked as AUTO-6845).
