### ISSUE TITLE
ROS2 Bridge Issue from Rviz after setting up TFTree

### ISSUE THREAD

**Issue by sisaha9** [lgsvl/simulator#1384]
This is a followup from #1378

After setting the required map -> odom -> base_link transformations (and sensors linked to base_link) I have the following tf_tree
![Screenshot from 2021-04-19 12-40-18](https://user-images.githubusercontent.com/49205122/115297235-d5982a00-a110-11eb-96b8-c5da10c6e442.png)

Base link to sensor transforms are currently done by a robot_state_publisher while the map -> odom and odom -> base link are done by dual ekf, navsat configurations. I can verify that the /tf is indeed getting transform data published as well

However, Rviz still seems to be giving the errors
![Screenshot from 2021-04-19 13-13-45](https://user-images.githubusercontent.com/49205122/115297474-16903e80-a111-11eb-987d-c1a92d660f25.png)

What could be causing this?

**Comment by EricBoiseLGSVL** [comment]
Are you converting the data to send to Rviz correctly?

**Comment by sisaha9** [comment]
I would guess that's the issue. Currently I just take the received messages and send to robot_localization for generating the TF Tree. I don't have any preprocessing of the sort on the messages (treated it like a Gazebo simulation). Is there somewhere I can read up on to better handle the conversion?

**Comment by sisaha9** [comment]
Just realized I didn't specify. But I wasn't trying to view the custom messages defined in lgsvl_msgs. I was referring to standard types like PointCloud2 provided by ROS2 as default

**Comment by EricBoiseLGSVL** [comment]
I'm not sure we support all ROS2 types out of the box.  You may need to write the conversion code for ones we don't support.  Right @hadiTab @lemketron ?

**Comment by sisaha9** [comment]
I agree. I would probably need to make plugins for the lgsvl_msgs but the main issue was these ROS2 types were not working out of the box

**Comment by sisaha9** [comment]
Let me know if I can help in any way

**Comment by sisaha9** [comment]
I noticed that the lane following demo given by SVL has a ros2_message_filters package added: https://github.com/lgsvl/lanefollowing/tree/master/ros2_ws/src. Is that something I would need to add? I also found a relevant issue here: https://github.com/ros2/rviz/issues/511 which states that the messages being broadcasted have to have relevant frame information attached to the messages. Is there a way to add that for the SVL?

**Comment by EricBoiseLGSVL** [comment]
@daviduhm ?

**Comment by sisaha9** [comment]
I think I have found the issue. SVL simulator takes nearly 100% of all 8 of my CPU cores (i7) and only 2GB from the GPU which is causing the ROS transform publishing to lag and inconsistently publish. I tried using the Clock Sensor to circumvent this but it didn't work. This CPU usage seems extremely unnatural though for a Unity simulation. I tried it on a slightly weaker Windows build with an i5 and it ran perfectly fine there. I think this is an issue with the Linux release of the simulator

**Comment by EricBoiseLGSVL** [comment]
Yes, windows is always more performant.  Next release uses a new version of Unity that is much better on Linux.

**Comment by sisaha9** [comment]
Great! Will wait for that. Closing this issue for now then

**Comment by sisaha9** [comment]
@EricBoiseLGSVL Just wanted to know but when would the next release be out approximately?

**Comment by EricBoiseLGSVL** [comment]
Next release is being tested now but it is small. We will have a larger update soon after
