### ISSUE TITLE
How to get the ground truth of traffic road lines, parking lines. etc.?

### ISSUE THREAD

**Issue by zengtaiping** [lgsvl/simulator#1385]
I want to build a map with road lines. How to get the ground truth of traffic road lines, parking lines. etc.?
The Segmentation Camera Sensor only shows the information about the ground, tree, and grassland, like the following:
![Selection_018](https://user-images.githubusercontent.com/33126567/115375028-58e87700-a208-11eb-92a3-c313e0d77592.png)

**Comment by EricBoiseLGSVL** [comment]
This map is not open source so you cannot create the lane/line meshes.
In your own map, you can open Simulator -> Detect Lane Lines.
See documentation [here](https://www.svlsimulator.com/docs/simulation-content/lane-line-detector/)

**Comment by zengtaiping** [comment]
Thank you so much for your explanation @EricBoiseLGSVL .

**Comment by EricBoiseLGSVL** [comment]
@zengtaiping no problem and glad to help
