### ISSUE TITLE
About custom map download

### ISSUE THREAD

**Issue by qiongwu1003** [lgsvl/simulator#1387]
Hi, SVL team

In the 202101 SVL simulator, I add a custom map to the cloud. When I run the simulations I need to download the map first. When the map is large or the network is slow, the download is very slow and aften fails.
Can I put the custom map file in the locally in advance? Then the simulator will run directly and over the download step.

Thanks.

**Comment by EricBoiseLGSVL** [comment]
@qiongwu1003 sorry we are in the process of adding the feature for resume downloads.  We hope to have it done soon.  You can use developer settings in the simulator settings but it is still work in progress.  Open the scene in Unity editor, open development settings, select a local vehicle, paste json sensor config in the settings, run from scene in editor.  It has bugs but it will let you test until we can implement resume download.

**Comment by qiongwu1003** [comment]
@EricBoiseLGSVL Thank you very much for your reply, it is of great help to me. And I also look forward to the feature for resume downloads.
