### ISSUE TITLE
How to add my own Vehicle Model.

### ISSUE THREAD

**Issue by majichang** [lgsvl/simulator#139]
Hi, LG simulator guys. I am working on Autoware with LG simulator,and I have a problem to solve it, someone can do me a favior!
     When i excute ./simulator in the terminal, in the "Free Roaming" page, how can I add my own Vehicle model in the simulate environment, and can select it  in the Vehicle texttable. very thanks for your help.

**Comment by martins-mozeiko** [comment]
If you have already created 3d model and imported it into simulator Unity project, then you need to add the prefab to list in ROSAgentManager object. Search for it in project and add new vehicle to list of available prefabs. Here's a screenshot of how it looks currently:

![](https://user-images.githubusercontent.com/49008516/55428759-ae2c8f80-553e-11e9-9ec2-a6710efcd34c.png)

Drag your prefab into new element.

**Comment by lemketron** [comment]
Check out this new document recently added to the LGSVL Simulator web site that describes [how to add a new ego vehicle](https://www.lgsvlsimulator.com/docs/add-new-ego-vehicle/).

**Comment by yangjiongfeng** [comment]
@martins-mozeiko i also want to add my own Vehicle Model.

this is my robot 
![mecanun](https://user-images.githubusercontent.com/27730697/62264525-d677bc80-b452-11e9-8aa5-528deb559691.png)
i use solidworks save ase a .stl file.

1.What is the format of your robot model? .urdf or .stl?
2.and i wan to know How do you load the model into unity?
Looking forward to your reply!

**Comment by EricBoiseLGSVL** [comment]
@yangjiongfeng 

1) Unity accepts multiple file formats for 3D geometry; .fbx, .dae (Collada), .3ds, .dxf, and .obj files.  I recommend always using .fbx
2) If your model is not one of these, use Blender (free) or Maya (paid) to import file, make sure geometry is correct (center pivot to bottom of model, make sure z forward is set) and then export as .fbx
