### ISSUE TITLE
Map is missing annotation MapHolder and child holders!

### ISSUE THREAD

**Issue by cxf99** [lgsvl/simulator#1391]
Map is missing annotation MapHolder and child holders! Please add to scene and set holder transforms
UnityEngine.Debug:LogError(Object)
Simulator.Map.MapManagerData:.ctor() (at Assets/Scripts/Map/MapManagerData.cs:25)
Simulator.Editor.MapMeshes.MapMeshBuilder:BuildMesh(GameObject, MapMeshMaterials, Boolean, LaneLineOverride) (at Assets/Scripts/Editor/Map/Meshes/MapMeshBuilder.cs:266)

**Comment by cxf99** [comment]
@lemketron Sorry, how to solve this problem，thank you，How to  annotation MapHolder and child holders？

**Comment by EricBoiseLGSVL** [comment]
If you create a new scene, we include this automatically.  If you already have a scene, you can manually create this.
Please see CubeTownMap as an example on how this is setup.

![image](https://user-images.githubusercontent.com/45106230/115887724-10e37300-a407-11eb-8c49-11b9e73208e3.png)
![image](https://user-images.githubusercontent.com/45106230/115887855-32445f00-a407-11eb-9289-40e25d8c5dbe.png)
![image](https://user-images.githubusercontent.com/45106230/115887975-4ab47980-a407-11eb-8ceb-9e28795a6c0f.png)
![image](https://user-images.githubusercontent.com/45106230/115888068-5b64ef80-a407-11eb-972c-cf968e8adb10.png)
![image](https://user-images.githubusercontent.com/45106230/115888178-7afc1800-a407-11eb-8abc-c95a5d5ad203.png)

Please look at the annotation documentation [here](https://www.svlsimulator.com/docs/simulation-content/map-annotation/).
