### ISSUE TITLE
How to restart simulation in Python API

### ISSUE THREAD

**Issue by 1Jyfc** [lgsvl/simulator#1394]
Hello!

I'm recently working on Python API. I'd like to generate test cases autonomously, and make the ego run several times in different scenarios, so I need to know how to restart Python API simulation with all things initialized. The introduction of interfaces in this [document](https://www.svlsimulator.com/docs/python-api/dreamview-api/#example) seems unable to do that. So is there any way rather than rerunning the python file to restart the simulation and reinitialize ego, scenario and destinations?

**Comment by EricBoiseLGSVL** [comment]
are you referring to api.reset()?

**Comment by 1Jyfc** [comment]
Well I think that's right. Thanks!
