### ISSUE TITLE
Missing NHTSA maps

### ISSUE THREAD

**Issue by ebadi** [lgsvl/simulator#1399]
Apollo : master
SVLsimulator : svlsimulator-linux64-2021.1
Python API: 2021.1 and master

```
/examples$ python3 NHTSA/Vehicle-Following/VF_S_45_Slow.py
[ ERROR] [lgsvl.dreamview.dreamview] HD Map Straight1LaneSame was not set. Verify the files exist in /apollo/modules/map/data/Straight1LaneSame and restart Dreamview -- Aborting...
```

I tried to download apollo50 map(base_map.bin) from wise.svlsimulator.com and place it in the specified folder with no success.

**Comment by revati-naik-lgsvl** [comment]
Hi @ebadi, could you please confirm the folder name for the map? Make sure it is renamed as "Straight1LaneSame". The path to the map should look something like this "apollo-5.0/modules/map/data/Straight1LaneSame/base_map.bin".

**Comment by ebadi** [comment]
![image](https://user-images.githubusercontent.com/1111940/116609800-183ddb80-a935-11eb-9182-56600db90674.png)

![image](https://user-images.githubusercontent.com/1111940/116609960-47544d00-a935-11eb-9d61-695350908e11.png)

![image](https://user-images.githubusercontent.com/1111940/116610065-6521b200-a935-11eb-9573-209981093fd2.png)

![image](https://user-images.githubusercontent.com/1111940/116609882-31468c80-a935-11eb-8274-3c323d6ed948.png)

![image](https://user-images.githubusercontent.com/1111940/116610469-c21d6800-a935-11eb-86f2-891cba5a4a8e.png)

Now I get another error. Do you have any idea what has been wrong ?

**Comment by lemketron** [comment]
It looks like you launched a simulation (maybe random traffic simulation) in interactive mode and pressed the "play" triangle button?

You need to launch an API-Only simulation to run Python scripts.

https://www.svlsimulator.com/docs/running-simulations/running-simulator/#apionlysimulation

**Comment by ebadi** [comment]
Thanks@lemketron I actually used the API only mode: 
![image](https://user-images.githubusercontent.com/1111940/116612096-69e76580-a937-11eb-963d-0091efdc1800.png)

**Comment by lemketron** [comment]
Can you post the Player.log file then? (Read through it first and see if you spot any clues.) It will be shorter if you quit and restart the simulator before testing the script.

**Comment by ebadi** [comment]
I took a look at it but I see no problem with it. 

[Player.TXT](https://github.com/lgsvl/simulator/files/6401587/Player.TXT)

**Comment by ebadi** [comment]
I restarted my PC several times yesterday and it didn't work. It is now working today and I have no idea why! I close this issue for now. 
Thanks for your help.

**Comment by ebadi** [comment]
I found out the issue.
Apollo crashes when an invalid map is given by `dv.set_hd_map('mapname')`. I am still struggling to find out what the problem is with the map.

**Comment by Yuchen413** [comment]
> I found out the issue.
> Apollo crashes when an invalid map is given by `dv.set_hd_map('mapname')`. This means Apollo, the bridge and svl have to be restarted.
> 
> I am still struggling to find out what the problem is with the map.

The map folder name in Apollo is "apollo-5.0/modules/map/data/straight1lanesame" (All lower case). Copy the map folder and rename it as Straight1LaneSame (with uppercase letter) solved my problem.

**Comment by revati-naik-lgsvl** [comment]
@ebadi Please rename your map folder name to match with the map name shown in the LGSVL map store/map library.

**Comment by ebadi** [comment]
Thanks, I will try this and come to you. I close the issue for now.
