### ISSUE TITLE
how to config the sensor and vehicle

### ISSUE THREAD

**Issue by gogojjh** [lgsvl/simulator#14]
As the title says, how can I set a different vehicle with different sensors in your simulator? LIke I want to design a car/bus with lidars and cameras at different positions.
Thanks!

**Comment by gogojjh** [comment]
Yes, based on Apollo. I find a problem with the lidar data, Like the below figure, there exists a distortion of the point cloud when the car is moving. How I fix this problem? Increase the frequency of lidar?
Thanks!
![screenshot from 2018-10-18 23-20-15](https://user-images.githubusercontent.com/11897988/47165470-9e244900-d32c-11e8-8a8f-b968567b9fdf.png)

**Comment by andytolst** [comment]
in general our point cloud is perfectly compensated for the motion of the car, i.e. points are exactly where they are in the real world, and this is what Apollo is doing in a special subnode in the Lidar driver (see "compensated" topic vs raw point cloud).

"sector" distortions you see are happening because points are collected in batches between the frames and these are visible on the high speeds when objects move faster between the frames. 
We are trying to improve our Lidar model in future releases to be more "smooth", meanwhile you also can try to play with Lidar parameters like resolution, number of rays of frequency. Disabling other sensors and decreasing resolution (to increase FPS) could also help.

**Comment by gogojjh** [comment]
Sorry that I have another question. You mentioned that we can modify the current car/sensor setup in "Prefabs/RobotCandidates/XE_Rigged-apollo.prefab". Here I tried to modify the number of rays and frequency, but it did not change in the simulation. So there are any other steps I should take? 
![screenshot from 2018-10-19 09-50-31](https://user-images.githubusercontent.com/11897988/47193268-a0b28d00-d384-11e8-9e32-9a0315728795.png)

Thanks!
Sorry again that I have too many problems TAT

**Comment by gogojjh** [comment]
I just follow these steps and create a new prefab in the "RobotCandidates" fold. But when I run the simulator again, I still can not load the new robot. What can I do next? 
Thanks!

**Comment by martins-mozeiko** [comment]
By "can not load" you mean it does not appear in combobox? The combobox in main menu is populated from RosRobot object. Open MainMenu scene, select RosRobots game object, and in inspector extend "Robot Candidates" array.

**Comment by gogojjh** [comment]
My problem is this:
1. I created a robot based on the "XE_Rigged-autoware" like this:
![screenshot from 2018-10-22 15-04-17](https://user-images.githubusercontent.com/11897988/47281125-18deb400-d60c-11e8-96de-23b95c7cefe9.png)
2. I saved this robot model in the "Assets/Prefabs/RobotCandidates" fold
![prefab](https://user-images.githubusercontent.com/11897988/47281141-2bf18400-d60c-11e8-88fe-ed55ebd0bfa3.png)
3. I opened the simulator, SanFrancisco scene, the robot I created cannot be loaded (the model "XE_Rigged-jjiao_stareo_lidar" doesn't appear).
![screenshot from 2018-10-22 15-05-40](https://user-images.githubusercontent.com/11897988/47281193-63603080-d60c-11e8-83e6-948201141cd1.png)

You mentioned "MainMenu scene" and "RosRobots game object", where can I find them? 
Thanks!

**Comment by gogojjh** [comment]
Let me explain this problem a bit clearer, for example
1. I created a robot model based on autoware like this,
![screenshot from 2018-10-22 15-04-17](https://user-images.githubusercontent.com/11897988/47282050-51808c80-d610-11e8-813f-81b5a2a7ffe6.png)
2. I saved this model in the "Assets/Prefabs/RobotCandidates"
![prefab](https://user-images.githubusercontent.com/11897988/47282053-534a5000-d610-11e8-8aea-31ba012afae4.png)
3. When I run the simulator and select the SanFrancisco map, I could not find the model I created here.
![screenshot from 2018-10-22 15-05-40](https://user-images.githubusercontent.com/11897988/47282054-547b7d00-d610-11e8-860e-abd03a613fb5.png)
**So what additional steps should I take?
Moreover, you mentioned "RosRobot object" and "MainMenu scene", where can I find them?**
I hope these problems won't cost you much time ...
Thanks!

**Comment by gogojjh** [comment]
Let me explain this problem a bit clearer, for example
1. I created a robot model based on autoware like this,
![screenshot from 2018-10-22 15-04-17](https://user-images.githubusercontent.com/11897988/47282050-51808c80-d610-11e8-813f-81b5a2a7ffe6.png)
2. I saved this model in the "Assets/Prefabs/RobotCandidates"
![prefab](https://user-images.githubusercontent.com/11897988/47282053-534a5000-d610-11e8-8aea-31ba012afae4.png)
3. When I run the simulator and select the SanFrancisco map, I could not find the model I created here.
![screenshot from 2018-10-22 15-05-40](https://user-images.githubusercontent.com/11897988/47282054-547b7d00-d610-11e8-860e-abd03a613fb5.png)
**So what additional steps should I take?
Moreover, you mentioned "RosRobot object" and "MainMenu scene", where can I find them?**
I hope these problems won't cost you much time ...
Thanks!

**Comment by gogojjh** [comment]
> By "can not load" you mean it does not appear in combobox? The combobox in main menu is populated from RosRobot object. Open MainMenu scene, select RosRobots game object, and in inspector extend "Robot Candidates" array.

**Comment by gogojjh** [comment]
Let me explain this problem a bit clearer, for example
1. I created a robot model based on autoware.
2. I saved this model in the "Assets/Prefabs/RobotCandidates"
![prefab](https://user-images.githubusercontent.com/11897988/47282053-534a5000-d610-11e8-8aea-31ba012afae4.png)
3. When I run the simulator and select the SanFrancisco map, I could not find the model I created here.
![screenshot from 2018-10-22 15-05-40](https://user-images.githubusercontent.com/11897988/47282054-547b7d00-d610-11e8-860e-abd03a613fb5.png)
**So what additional steps should I take?
Moreover, you mentioned "RosRobot object" and "MainMenu scene", where can I find them?**
I hope these problems won't cost you much time ...
Thanks!

**Comment by martins-mozeiko** [comment]
See following screenshot.

![image](https://user-images.githubusercontent.com/39178216/47307146-26337880-d5e3-11e8-8534-d2196ca17e4f.png)

1. open MainMenu scene (double-click)
2. select RosRobots game object (single-click)
3. edit RosRobot properties in inspector - add new entry by dragging your prefab from Project window (where you selected scene)

**Comment by gogojjh** [comment]
It can work, thanks a lot!
