### ISSUE TITLE
Pre-built model with API - Latest release

### ISSUE THREAD

**Issue by kk2491** [lgsvl/simulator#140]
Hi Guys,

Could you please let me know when the latest pre-built simulator package would be released with Python API functionality.

Thank you,
KK

**Comment by martins-mozeiko** [comment]
Python API for simulator was released last week. You can it with v2019.04 binary build or just use master of git repository.

**Comment by kk2491** [comment]
@martins-mozeiko I was not able to find ```v2019.04``` in the latest release / download section. Could you please let me know when it would be released?

**Comment by martins-mozeiko** [comment]
It is available in releases page: https://github.com/lgsvl/simulator/releases
Here's a direct link: https://github.com/lgsvl/simulator/releases/tag/2019.04-rc1

**Comment by kk2491** [comment]
@martins-mozeiko Thats great. Now I am able to download the latest release. Thanks for the help.
