### ISSUE TITLE
Graphical database

### ISSUE THREAD

**Issue by Thinsheep** [lgsvl/simulator#1410]
Hi,
Is that OpenDrive format .xodr/.xml stores the database of the road network? which one stores the graphical database of the virtual world, is that the asset bundle?

**Comment by EricBoiseLGSVL** [comment]
@Thinsheep yes, the asset bundle saves the textures, materials and meshes.  Some, like sensors, contain logic assemblies as well.

**Comment by Thinsheep** [comment]
Thanks
