### ISSUE TITLE
More details on articulated trailer work?

### ISSUE THREAD

**Issue by henrychoi** [lgsvl/simulator#1411]
Hello, I am looking to simulate a tractor-trailer.  I see you are working on it https://github.com/lgsvl/simulator/issues/745.  Can you please explain your roadmap?
- Will the trailer be a multi-axle?
- Will the trailer have brake capability? Could it have throttle capability also?  Can L/R independently controllable?

**Comment by EricBoiseLGSVL** [comment]
We are working on articulated body support in our next release.  Not sure when we will get a working example of the trailer, maybe the release after.

**Comment by henrychoi** [comment]
Thanks for a quick reply Eric.  Can you please provide more details so I can plan better:
Since you just released 2021.1 release, are you talking about 2021.6 release?  Would this be enough for me to implement my trailer vehicle type, or would I have to wait for the 2022 release?  Would the trailer have independently controllable braking / torque?  If it takes too long, I think I would just have to pay for the TruckSim

**Comment by EricBoiseLGSVL** [comment]
We are trying to get back to more frequent releases but we will not be able to create the features you are asking for for a while.  I'd go with Truck sim.  The articulated body feature is just to help create better joints and support robotics.  It will take too long I think.

**Comment by MarkusKramer1** [comment]
Hello,
we are also interested in simulating semi trucks in the LGSVL simulator. As trucksim supports the export of an fmu, is it possible to integrate that model into the simulator?

Our research is in the field of cooperative path planning and driving of several vehicles.
If the above is not possible, is it possible in general to just use a simpler kinematic model to control vehicle assests?
I know that NPC vehicles can be controlled by publishing a list of waypoints, which could be calculated in any way, but is it possible to get sensor data of these vehicles?

**Comment by EricBoiseLGSVL** [comment]
1) Yes, we do support FMU but it is a very basic example.
2) Also, yes.  Our vehicle dynamics is a simplified C# implementation.
3) Sensor data? how so?  You can use ground truth, lidar, radar, and any sensor you want to create.  Is that what you mean?
4) @lokesku @lemketron "Our research is in the field of cooperative path planning and driving of several vehicles."

**Comment by henrychoi** [comment]
Thanks for the discussion Eric.  Will circle back in a year.  I guess it makes sense to model the articulated joint as a ball joint, and model the trailer's brake and throttle separately.  It would be awesome if you could allow flexible dimension of the trailer wheels and independent brake throttle (that is my research area).
