### ISSUE TITLE
how to remove unwanted boundary lines? 

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1422]
How to remove unwanted boundary lines, as shown in the picture below.
![remove](https://user-images.githubusercontent.com/61130487/117637912-ba628c80-b19b-11eb-9488-8d4c230dad95.png)

**Comment by EricBoiseLGSVL** [comment]
remove from hdmap annotation before running hd map mesh tool

**Comment by Addi2020** [comment]
@EricBoiseLGSVL  This solution  do not work. I want to remove one side of the boundary of  lane and then export HD map but it gives an error that (value cant be null).

![Screenshot from 2021-05-31 17-03-26](https://user-images.githubusercontent.com/61130487/120190555-33508380-c232-11eb-939f-ffa4e79881e7.png)

**Comment by EricBoiseLGSVL** [comment]
From our research, the hdmap formats we support require boundry lines.  Why are you trying to remove them?

**Comment by Addi2020** [comment]
@EricBoiseLGSVL As you can see in the first picture , I just want to remove the boundary lines that overlaps with other lane.  Because in real world there is no such lines. 
picture 1= (the boundary lines that are noted by an orange line are unwanted)

**Comment by EricBoiseLGSVL** [comment]
- I'm sorry but I am confused.  Are you trying to edit the hdmap for export or are you trying to edit the hdmap mesh generated?
- Why can't you separate the lines out, build the mesh and then add back the lines for export?  You can even make a copy in editor and delete lines as needed for the mesh generation.  You can also export the mesh from the Unity editor and edit the mesh to remove the lines.
- HDmap mesh tool is not meant to be a high fidelity mesh but a simple mesh for users that don't have the resources to create 3d meshes.
- The HDmap tools are not meant to be a stand alone hdmap tool.  It is for simulation of npcs, peds and export to the AD stacks we support.
- Please explain further what you are trying to accomplish so I can help.

**Comment by Addi2020** [comment]
1. i am trying to edit the hdmap for export . (base_map.bin file)
2. how to build mesh and separate lines?  can you explain please? 

You can see the yellow boundary line (left boundary lane of MapLane2 (4) ) , overlap on MapLane2 (3). So i just want to remove that yellow boundary line and then export HD map (base_map.bin file). This base_map.bin file will be use to upload in dreamview.

![line](https://user-images.githubusercontent.com/61130487/120565245-12e91a80-c426-11eb-99fd-533c8be8ea0b.png)

**Comment by EricBoiseLGSVL** [comment]
So you need to edit the annotation.  Here is an example from Borregas Ave annotation.
![image](https://user-images.githubusercontent.com/45106230/120701807-2d43e800-c468-11eb-950c-b5571d0b6ac5.png)

You can see that the Yellow line is split off and a white boundary line is added to be the left of the traffic lane.  Is this what you are trying to do?
