### ISSUE TITLE
standalone simulator to support command line map & vehicle input

### ISSUE THREAD

**Issue by ZJLi2013** [lgsvl/simulator#143]
hey, LG team,

        I am new to Unity and built the simulator in Ubuntu and it run fine.  
       does it support command line arguments now, specially for map and vehicle type choose.  thanks for any suggestions

**Comment by martins-mozeiko** [comment]
You can do that with our static config file.
You need to prepare simulator configuration in yaml text file - which includes map name to load and what vehicles to instantiate. Then run simulator with `--config filename.yml` argument.
Example of this config file can be seen here: [static_config_sample.yaml](https://github.com/lgsvl/simulator/blob/master/static_config_sample.yaml)
