### ISSUE TITLE
Wrong NPC vehicles moving direction

### ISSUE THREAD

**Issue by yejw5** [lgsvl/simulator#1434]
Environments:
```
Ubuntu 18.04
LGSVL 2021.1
Apollo 5.0
```

I have created a BorregasAve test map following steps in https://www.svlsimulator.com/docs/simulation-content/hd-map-mesh-generation/ . 

But in modular testing, the moving direction of NPC vehicles showing on dreamview seems contrarotating with 90 degree to the real driving direction.
![2021-05-14 16-43-01屏幕截图](https://user-images.githubusercontent.com/9035475/118246394-7d1c3880-b4d4-11eb-882b-db69f4d233aa.png)

Is there some critical steps omitted by me?

**Comment by EricBoiseLGSVL** [comment]
Yes, maps are rotated -90 degrees.  See [here](https://www.svlsimulator.com/docs/getting-started/conventions/)

**Comment by yejw5** [comment]
> Yes, maps are rotated -90 degrees. See [here](https://www.svlsimulator.com/docs/getting-started/conventions/)

@EricBoiseLGSVL Thanks for your reply. As my understanding, the [Conventions docs](https://www.svlsimulator.com/docs/getting-started/conventions/#map-origin) explains the diff coordinate systems of map view in unity?

But I'm still confused... In my case, with modular testing, it seems that the perception of NPC vehichles and moving prediction rotated (-)90 degrees in dreamview page. And the docs only show a method to switch Unity Editor scene view to a familiar orientation? Is there any detailed steps to fix the moving direction of random traffics in the dreamview page?

**Comment by yejw5** [comment]
@EricBoiseLGSVL I have figured it out.... This case can be fixed by rotate the orientation of MapOrigin. Thanks for your reply!
