### ISSUE TITLE
Random pedestrians not work in imported road network

### ISSUE THREAD

**Issue by yejw5** [lgsvl/simulator#1437]
I have created NavMesh for pedestrians following [Road network generation -> Creating NavMesh for pedestrians](https://www.svlsimulator.com/docs/simulation-content/hd-map-mesh-generation/#top)

Then, enable`Random pedestrians` and  `Random traffic` in simulation creating. When the test started,  there are non pedestrian walking in the sideroad. Otherwise,  the `Random traffic` option can work correctly. Is there any step missed?

**Comment by EricBoiseLGSVL** [comment]
Do you have a nav mesh at 0,0,0?  Please see this issue #1427

**Comment by yejw5** [comment]
I have set position of SpawnInfo to a road mesh, but the random pedestrians still not work. And my building logs have no error message like issue https://github.com/lgsvl/simulator/issues/1427. Is there something I misunderstand?

**Comment by yejw5** [comment]
My test use default `Apollo 6.0 (modular testing)` sensor configure. If running on `BorregasAve` map, it works well. So it shouldn't be the wrong sensors.

In the sreenshot of MapOrigin, the nav mesh is set to 0, 0, 0:
![image](https://user-images.githubusercontent.com/9035475/119253589-87c98280-bbe4-11eb-8ed0-17497fd4f9e2.png)

And the SpawnInfo have been above the ground:
![image](https://user-images.githubusercontent.com/9035475/119253619-aa5b9b80-bbe4-11eb-8512-5ef73f9ba22d.png)

![image](https://user-images.githubusercontent.com/9035475/119253651-cbbc8780-bbe4-11eb-8094-03b65e15161f.png)

**Comment by EricBoiseLGSVL** [comment]
That spawn point seems too high.  Can you move it closer to the mesh?  We assume you put the spawn info object as close as possible so the vehicle doesn't fall on start.  The check only raycasts for one meter.

**Comment by EricBoiseLGSVL** [comment]
Also, do you have any pedestrian annotation?  The pedestrians need annotation to follow in the map.  They don't follow vehicle annotation.

**Comment by yejw5** [comment]
> That spawn point seems too high. Can you move it closer to the mesh? We assume you put the spawn info object as close as possible so the vehicle doesn't fall on start. The check only raycasts for one meter.

I have put the spawn info object on the mesh, and still no pedestrian generated. Besides, if setting the spawn point in current height, all functions work well excepting random pedestrian.



> Also, do you have any pedestrian annotation? The pedestrians need annotation to follow in the map. They don't follow vehicle annotation.

Yes, I have created NaveMesh for pedestrians following [docs](https://www.svlsimulator.com/docs/simulation-content/hd-map-mesh-generation/#creating-navmesh-for-pedestrians). Is there any other steps missed?

**Comment by EricBoiseLGSVL** [comment]
No the pedestrian annotation, not just nav mesh.  Sorry, this is not clear in the docs, we will update.  Look at CubeTown, it has an example and [here](https://www.svlsimulator.com/docs/simulation-content/map-annotation/#create-pedestrian-path-sidewalk) in docs.

**Comment by yejw5** [comment]
> No the pedestrian annotation, not just nav mesh. Sorry, this is not clear in the docs, we will update. Look at CubeTown, it has an example and [here](https://www.svlsimulator.com/docs/simulation-content/map-annotation/#create-pedestrian-path-sidewalk) in docs.

The imported map in my case is downloaded from https://wise.svlsimulator.com/ . Random pedestrians works well in the origin map. And it means that the pedestrian annotation haven't imported completely. So I need to create pedestrian annotation?

**Comment by EricBoiseLGSVL** [comment]
Yes, annotation is Unity feature only. You need to create those.
