### ISSUE TITLE
Scene blacks out after build completed

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1438]
After every successful builds, my scene just blacks out. When I restart the Editor, it comes back like nothing happens.
![Screenshot from 2021-05-17 15-44-25](https://user-images.githubusercontent.com/67900559/118462853-50ad2a00-b729-11eb-8388-e0e6f1cf7539.png)

What is happening here?

**Comment by EricBoiseLGSVL** [comment]
Yes, this is a Unity Editor bug.  Very annoying.
