### ISSUE TITLE
ArgumentException: Getting control 0's position in a group with only 0 controls when doing mouseDrag

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1439]
This exception or error raises up when I drag the Build window after finishing building simulator.
![Screenshot from 2021-05-17 15-33-14](https://user-images.githubusercontent.com/67900559/118463119-99fd7980-b729-11eb-82fd-68021ba4a636.png)
Is this something I should concern about? How to fix it or toggle it off?

**Comment by EricBoiseLGSVL** [comment]
Yes this is a Unity Editor bug.  Next months release has many improvements for Linux.

**Comment by duongtran11** [comment]
Thank you. Is this an autoupdate or how do I update the next month release? I'm using svl simulator 2021.1

**Comment by EricBoiseLGSVL** [comment]
We have a patch first and then 2021.2 release.  Probably next month.

**Comment by duongtran11** [comment]
You can see that I have already docked the editor window. This error happens only when I drag the Build window (or the Development Setting window) around

**Comment by EricBoiseLGSVL** [comment]
Yep, any window (build/dev settings) that is not docked has this issue on linux.  Just a Unity editor bug and you can ignore.  Seems Unity changed some EditorWindow api's for Linux.

**Comment by duongtran11** [comment]
I got it, thank you!
