### ISSUE TITLE
How to change the lidar configuration

### ISSUE THREAD

**Issue by khaledelmadawi** [lgsvl/simulator#144]
Hi All,
First I would like to thank you again for this outstanding framework, second how can I change the configuration of lidar sensor as shown in Lidar demo presented in youtube?

![Screenshot from 2019-04-28 14-01-49](https://user-images.githubusercontent.com/13773937/56864071-6e7e8980-69be-11e9-8760-4aed617bf5fb.png)

Thanks

**Comment by khaledelmadawi** [comment]
I could figure out how it works, but I found that the maximum number of layers is 128, can it be extended in the coming releases?

**Comment by martins-mozeiko** [comment]
This is only limitation in UI. You can change max number in [LidarSensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/LidarSensor/LidarSensor.cs#L25) file.
We put 128 there as it is pretty reasonable number. But even at 128 rays simulation will have very low performance. It requires extra optimizations that we'll need to do. Going higher than that will pretty unusable for real-time simulation.

**Comment by khaledelmadawi** [comment]
Thank you martin for your answer, how do you recommend he applied optimizations would be?

**Comment by martins-mozeiko** [comment]
First you need to measure performance to understand where time is spent. Is it more GPU or CPU. Then think about how to change to reduce it, maybe use multiple threads, maybe some extra native code to calculate result faster. Not sure yet.

**Comment by martins-mozeiko** [comment]
With our new simulator [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) release we have greatly optimized lidar performance. It is now able to do 128 ray lidar simulation in real time. Try it out and if you see any other problems feel free to open a new issue.
