### ISSUE TITLE
Cannot load scene: Invalid scene name (empty string) and invalid build index -1

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1440]
This error pops out when I hit play button. Below is picture of Scene and Game display. I dont know what is wrong here. Couldn't really find anything helpful in the internet.
![Screenshot from 2021-05-17 16-08-19](https://user-images.githubusercontent.com/67900559/118463962-8868a180-b72a-11eb-9dae-00a1a8ab73f3.png)
![Screenshot from 2021-05-17 16-09-17](https://user-images.githubusercontent.com/67900559/118463968-8999ce80-b72a-11eb-9bb6-6e0472711e96.png)

**Comment by EricBoiseLGSVL** [comment]
You are trying to run the scene and this is not supported.  You need to start with LoaderScene.scene and load map from WebUI.  We have DeveloperSettings in the Simulator menu that you can start a sim from the scene but it only loads local assets and is still wip.

**Comment by duongtran11** [comment]
I made it works. It run just like in the older version (LGSVL Simulator)
I had to download JaguarXE2015 prefab from the internet then put it to Assets/Externals/Vehicles
Then in the Development Settings that car appears in the ego vehicles
But the Pedestrian NavMesh still missing

**Comment by EricBoiseLGSVL** [comment]
You need to place a nav mesh under the spawn info object.  Did you do this?

**Comment by duongtran11** [comment]
Here is the solution #1427
