### ISSUE TITLE
Simulation with test case only runs for 20 seconds

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1453]
I created some scenarios to run on simulator. 
Work  fine.
But the simulation runs with those test cases (scenarios) only for 20 seconds, even if the NPCs had not reach the last waypoint.
I would like to run the simulation for longer period of time (e.g. 60 seconds)

**Comment by EricBoiseLGSVL** [comment]
Yes, this is a bug and the latest release has the fix. 2021.1.1
