### ISSUE TITLE
Unable to set directions in RVIZ

### ISSUE THREAD

**Issue by AKSHATA-MK** [lgsvl/simulator#1454]
Hi,

I'm trying to run LGSVL with autoware. Have setup in different machines. LGSVL is running on windows and autoware on ubuntu. Able to connect both . Launching RVIZ and simulator.Maps and vehicles are loading properly in RVIZ. But I'm not able to set the directions for the vehicle in RVIZ. https://www.svlsimulator.com/docs/system-under-test/autoware-instructions/ I have followed these steps . I'm not able to perform the last step Driving the vehicle by vector map. I'm unable to set the directions for the vehicle in RVIZ . so that vehicle moves automatically . Please help

**Comment by EricBoiseLGSVL** [comment]
What errors do you have in Rviz?  Can you screen shot your UI so our devs can see?

**Comment by AKSHATA-MK** [comment]
> What errors do you have in Rviz? Can you screen shot your UI so our devs can see?

Thank you for the reply.
I'm sharing the screenshots.
![error](https://user-images.githubusercontent.com/57988299/119813482-db83e680-bed8-11eb-9c02-e3adc7e0ccf7.png)
![error_2](https://user-images.githubusercontent.com/57988299/119813483-db83e680-bed8-11eb-9af3-76d28e97bc20.png)
![error_3](https://user-images.githubusercontent.com/57988299/119813684-19810a80-bed9-11eb-82b6-51fa8e71083d.jpeg)

I think map,localisation,sensing and detection are loading well
Let me know what has to be done

**Comment by EricBoiseLGSVL** [comment]
@AKSHATA-MK thanks for the images, that helps.  @hadiTab or @lemketron do we support pure-pursuit or any idea what could be wrong?

**Comment by AKSHATA-MK** [comment]
Hi 
Now I'm able to set the directions for the vehicle in Rviz
![Direction](https://user-images.githubusercontent.com/57988299/120638550-c7536280-c45f-11eb-9e29-c5f7a8764b55.png)

But the vehicle is stuck 
vehicle is not moving even after the motion planning is launched
I'm sharing some error messages that I'm getting once I'm loading the files, not sure what is effecting the vehicle motion
Once I launch the map.launch file. getting the error as follows, but still then then map is loading , Point cloud is appearing, I'm able to set the directions so not sure if this error is affecting.
![Map](https://user-images.githubusercontent.com/57988299/120638915-4c3e7c00-c460-11eb-8352-4467aa98b852.png)

And after I load the localization the timing is not appearing on the right.
After I load the detection.launch the following error is coming.
![Detection](https://user-images.githubusercontent.com/57988299/120639130-8dcf2700-c460-11eb-88ef-f726222bfe26.png)

Not sure what  is affecting the vehicle movement. It is stuck.
Please Help
Thank you

**Comment by AKSHATA-MK** [comment]
I just solved the issue
Thank you

**Comment by lemketron** [comment]
Looks like it was missing the ".launch" file?
