### ISSUE TITLE
Creating and running API-only simulation results in logout

### ISSUE THREAD

**Issue by krtt** [lgsvl/simulator#1457]
In the webUI, after creating an API-only simulation following [this guide here](https://www.svlsimulator.com/docs/running-simulations/running-simulator/#apionlysimulation), running this sim will briefly show the status as "API ready!" but then goes to logout and offline. Resulting status snapshot:
![image](https://user-images.githubusercontent.com/22684441/119694593-0711bd00-be56-11eb-8587-6eb974324d8c.png)

**Comment by EricBoiseLGSVL** [comment]
Do you have the player.log so we can see the error?  You can also see an error in webui with f12

**Comment by krtt** [comment]
No player.log any more unfortunately. But I have a new problem. Will post as a separate issue..

**Comment by krtt** [comment]
I have used the API Only sim for a while now and the problem has not appeared any more. It's ok to close this issue.
