### ISSUE TITLE
What is the interface to get sensor raw data

### ISSUE THREAD

**Issue by DanielTian90** [lgsvl/simulator#1459]
Hi LGSVL,
I am prepared to use lgsvl as simlation scenario to inject data to my adas ECU. But I didn't find the interface of data from sensor(eg. radar/camera/lidar) of lgsvl simulator. Could you please to tell me regarding detailed definition for these data? Documantation or source code.
Many thanks.

**Comment by EricBoiseLGSVL** [comment]
ROS, ROS2, CYBER bridge.  Documentation is [here](https://www.svlsimulator.com/docs/system-under-test/simulator-messages/).

**Comment by DanielTian90** [comment]
I want to know detailed definition for each topic, eg. for lgsvl_msgs/DetectedRadarObject, I want to know definition for data format.

**Comment by EricBoiseLGSVL** [comment]
For that you can look at the source code.  These are defined in the bridge code.
![image](https://user-images.githubusercontent.com/45106230/119920494-4a852d80-bf21-11eb-9ddb-59a71892add3.png)

**Comment by DanielTian90** [comment]
OK.
Regarding attributes in lgsvl_msgs/DetectedRadarObject, these data is for detection point level before classification? or after classification(eg. attributes for car/pedestria/bicycle)?

**Comment by EricBoiseLGSVL** [comment]
No classification is done on radar objects.  This is just the raw data from detected objects as you can see from the data class.  positions, velocities, angles and size, no classification.
