### ISSUE TITLE
Problem about map annotation

### ISSUE THREAD

**Issue by wobushigaoying** [lgsvl/simulator#1461]
Hello team,

I am using map annotation tools following the instruction.

I cloned the CubeTown from the github for the test. I opened the CubeTown.scene in Unity editor.

As the below figure indicates, I clicked "View All" in "View mode", and "Lane/Line" in "Create Modes". TARGET_WAYPOINT is then showed up in the hierarchy tab, but no yellow indicator in my scene. If I click TARGET_WAYPOINT in the hierarchy tab, it disappeared.

 I checked the "Road" and "Mesh collider" had been attached yet. What's wrong with this??

![image](https://user-images.githubusercontent.com/18672103/120130587-22cfe700-c1f9-11eb-96e3-1f7617f9c4a0.png)

![image](https://user-images.githubusercontent.com/18672103/120130927-e0f37080-c1f9-11eb-970e-e1eabd7e37a2.png)

**Comment by wobushigaoying** [comment]
Hello, I have solved this problem. I enabled the Gizmos button in the Unity editor, and then the WAYPOINT appeared. I have successfully created my own MapLanes. I am going to create MapLanes in our own Maps.  :)

![image](https://user-images.githubusercontent.com/18672103/120132528-1483ca00-c1fd-11eb-9206-28c90bdfad2a.png)

**Comment by EricBoiseLGSVL** [comment]
Nice, sorry that this was not toggled by default.  We will update the docs as soon as we can. Thanks for letting us know.
