### ISSUE TITLE
SVLSimulator Docker

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#1462]
Hi,

I run SVLSimulator with run.sh in docker.
![image](https://user-images.githubusercontent.com/23841025/120154988-16e42500-c1f9-11eb-87ca-65e477686178.png)

I can't reach localhost.
![image](https://user-images.githubusercontent.com/23841025/120155079-2bc0b880-c1f9-11eb-930c-55feed1df5ae.png)

There is no error in docker terminal.

What could be the problem?

**Comment by EricBoiseLGSVL** [comment]
@eagafonovlge ?

**Comment by clepz** [comment]
Problem is resolved.
