### ISSUE TITLE
Cannot correctly stop the Python Test Case Simulation

### ISSUE THREAD

**Issue by krtt** [lgsvl/simulator#1463]
I followed the manual [here](https://www.svlsimulator.com/docs/running-simulations/running-simulator/#pythontestcasesimulation) to test the "Cut-in Scenario" and when I get to the end of point 7 (click Run simulation), then the sim starts, but after ca 10-20 seconds it stops in the sim window (and displays the 'Open browser' and 'Visual scenarios' buttons), but at the same time in the browser web UI, it shows still 'running' and the stop button there does not work. 
![image](https://user-images.githubusercontent.com/22684441/120211744-f12b4000-c239-11eb-8f21-2ed56562ac9c.png)

The error on the sim name (in the web UI) says 'Error: Cluster is currently running another simulation'.
Under the exclamation mark it says 'Error on latest run: Bridge socket was unexpectedly disconnected'
If I close everything and run again, same result.

If I close only web UI browser and open it again, the stop button still does not do anything but the 'Error' has changed to 'Stopping' and it will be like this forever (or until unknown long time):
![image](https://user-images.githubusercontent.com/22684441/120212442-abbb4280-c23a-11eb-9769-05f336e34b2b.png)

At this point I did not even get to the point nr 9 in the guide (to go to Apollo Dreamview to configure it).

**Comment by EricBoiseLGSVL** [comment]
Are you using 2021.1.1 release?

**Comment by krtt** [comment]
Yes, I am using 2021.1.1, prebuilt (downloaded from svlsimulator.com page)

**Comment by EricBoiseLGSVL** [comment]
First, do you have the bridge started before you run the simulation? Second, please post your player.log to see any errors that you have.  Lastly, what OS are you using?
@eagafonovlge @thisisdavidfrank

**Comment by krtt** [comment]
Yes, the bridge was started before running the sim.
Player.log attached.
[Player.log](https://github.com/lgsvl/simulator/files/6607420/Player.log)
Ubuntu 18.04.

**Comment by EricBoiseLGSVL** [comment]
```
SocketException: Connection refused
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <ef151b6abb5d474cb2c1cb8906a8b5a4>:0 
  at Simulator.Bridge.Cyber.CyberBridgeInstance.OnConnectionComplete (System.IAsyncResult ar) [0x00000] in <07e3d881d39e45158bcdba3f8cecc23d>:0 
```

This is the error.  Any idea why the connection is refused on your machine?  Are you using Apollo 5.0?

**Comment by krtt** [comment]
No idea why connection refused. In some other cases it runs fine. Yes, Apollo 5.0.

**Comment by EricBoiseLGSVL** [comment]
does this happen after running a sim?  We have seen apollo need to be completely closed before another run.  Right @hadiTab @lemketron ?

**Comment by krtt** [comment]
I have not been able to reproduce this situation any more. It´s now stuck in a new situation. I will put a separate issue about this.
