### ISSUE TITLE
Problem about connecting two lanes

### ISSUE THREAD

**Issue by wobushigaoying** [lgsvl/simulator#1464]
Hello team... 

I am using CubeTown as a case study for map annotation.

The two lanes are surely connected in the scene as shown in Figures 1 and 2.  Could you please help me connecting the lanes as shown in Figure 3. I tried to add a junction between these two lanes, but it seemed not to work ( I added two waypoints on the two waypoints of these two lanes, however, the "Connect" button did not work. ). 

Many thanks!!!

![image](https://user-images.githubusercontent.com/18672103/120275069-571fd200-c2e3-11eb-8b05-9af569da9e8a.png)

![image](https://user-images.githubusercontent.com/18672103/120275120-6c94fc00-c2e3-11eb-91d9-cdc6c7636675.png)

![image](https://user-images.githubusercontent.com/18672103/120276457-4a03e280-c2e5-11eb-9c97-5f7cacef2290.png)

**Comment by EricBoiseLGSVL** [comment]
connect button is for two temp waypoints to make one lane.  Not to connect two lanes together.  If you want to extend the lane, select the maplane object and enable display handles so you can move the point to where you want.  If you want two separate lanes, then move the first index point to overlap the last index point of the prev lane.  Like so:
![image](https://user-images.githubusercontent.com/45106230/120406784-8abd2500-c300-11eb-9bad-238135f06167.png)

**Comment by wobushigaoying** [comment]
OK!!!  Thanks for your kindly reminder. ~  :)
