### ISSUE TITLE
3D Bounding box wrong classificaion

### ISSUE THREAD

**Issue by khaledelmadawi** [lgsvl/simulator#147]
Hi All,
the classification of the 3D bounding box is always a car
![image](https://user-images.githubusercontent.com/13773937/57008278-3611c200-6bef-11e9-97c2-560562873f9e.png)
is this an issue?
NB: printed(classification, size_x,size_y)
![image](https://user-images.githubusercontent.com/13773937/57008293-593c7180-6bef-11e9-856d-fb9e0fec4750.png)

**Comment by martins-mozeiko** [comment]
That's right, currently we use `car` label for all vehicles. This happens in [GroundTruthSensor3D.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/GroundTruthSensor3D.cs#L244) file.

You can change this code to get type of object from `detect.gameObject` if you want different labels for different type of vehicles.
