### ISSUE TITLE
 how to a simple planning(lane change, lane follow) for ego vehicle in standalone

### ISSUE THREAD

**Issue by kissofwind** [lgsvl/simulator#148]
hey, lg team,

I see there is a npc vehicle follow lane API, is there similar for ego vehicles ?  or will there be a simple planning for ego vehicle in future ?

**Comment by martins-mozeiko** [comment]
Currently EGO vehicle can follow only list of custom waypoints.
To make it follow lane best option is to connect vehicle to AD stack like Apollo and make AD to control the vehicle.

**Comment by kissofwind** [comment]
got it, thanks
