### ISSUE TITLE
Binary Options (not bundle)

### ISSUE THREAD

**Issue by NataliaSanchezSan** [lgsvl/simulator#1483]
I have a problem in the build simulator: "Binary Options (Not bundles)" and I can't add a New vehicle.

![unknown](https://user-images.githubusercontent.com/71804093/121253343-9ebbd600-c86e-11eb-895a-449b20b87d52.png)

**Comment by Yuchen413** [comment]
Same problem though have already added assets by git clone in External/environment/...

**Comment by EricBoiseLGSVL** [comment]
You need to open the drop down menu.  See the arrow pointing right?  Click that.

**Comment by EricBoiseLGSVL** [comment]
What do you mean by add a new vehicle? If you are building a binary, that is all you can do, build the binary.  If you are building a vehicle, environment, etc. you need to open the drop down and if you cloned the repo correctly, you will have a toggle to select one item to build a bundle. This bundle is built and placed in AssetBundles folder.  This must be uploaded to the web ui to be added to your simulation.  Please look at documentation [here](https://www.svlsimulator.com/docs/installation-guide/build-instructions/).

**Comment by Yuchen413** [comment]
> You need to open the drop down menu. See the arrow pointing right? Click that.

Thanks for your reply. I tried before but it didn’t work, there was no response when clicking the arrow.

**Comment by NataliaSanchezSan** [comment]
If I select the build file:

![error2](https://user-images.githubusercontent.com/71804093/121585280-03566c80-c9f8-11eb-8f0a-936cba42b0ab.png)

But, I don´t know how to disable binary options.

**Comment by NataliaSanchezSan** [comment]
Literally, it is not possible to select the vehicle, whether or not the build simulator is activated. 

![error](https://user-images.githubusercontent.com/71804093/121592315-22f19300-ca00-11eb-9493-f969cf519fd6.png)

**Comment by EricBoiseLGSVL** [comment]
It says you are missing Golfinho.prefab.  Do you have the prefab in the root of the asset folder like the documentation says?

**Comment by NataliaSanchezSan** [comment]
I created the prefab as indicated in the documentation in the assets / external / vehicles / Golfinho / Models / folder, I also tried to move Golfinho from the Models folder but it didn't work.

![error3](https://user-images.githubusercontent.com/71804093/121593912-08b8b480-ca02-11eb-99c5-8d0be0e7ff33.png)

**Comment by EricBoiseLGSVL** [comment]
Assets/External/Vehicles/Golfinho/Golfinho.prefab. Please also clone Jag repo to refer and see if you are missing class components on the vehicle prefab.

**Comment by NataliaSanchezSan** [comment]
During this time I tried to add a new vehicle, with the advice you told me, but it was not possible.
So I decided to download the Jaguar repository, to check if any component is missing in the prefab, but it is not, I find everything correct, in addition the simulator still does not allow me to build the vehicle, in this case you cannot even select the Jaguar vehicle.

![error4](https://user-images.githubusercontent.com/71804093/122662475-dc670b80-d158-11eb-9e40-2d617d87c58e.png)

**Comment by EricBoiseLGSVL** [comment]
Again, you have the prefab in the models folder.  Take the prefab and put in the root golfinho folder.

**Comment by NataliaSanchezSan** [comment]
Thank you very much for your recommendations, the car is already integrated. I had to migrate to the Windows system because on Linux this integration was not possible.
