### ISSUE TITLE
Modifying Post Processing 

### ISSUE THREAD

**Issue by RobShewagaUHN** [lgsvl/simulator#1485]
I'm running the SanFrancisco map with a Jaguar under keyboard control and trying to modify the post processing while running in the editor.

- Editing the PostProcessingVolume object in the scene doesn't change anything
- Editing the PostProcessingVolumeProfile set as the Default Volume Profile Asset in Settings/HDRP Default Settings doesn't change anything
- Adding a volume to the camera in the scene with a post processing profile doesn't change anything

Is a script running somewhere that is changing the post processing extensively?

Additionally, the version of HDRP in the project (7.5.2) apparently doesn't use the Post Processing V2 stack, so why is that package included in the project?

Thanks

**Comment by EricBoiseLGSVL** [comment]
- PostProcessingVolume is a prefab that you need to edit before running simulator (all prefab changes need to happen before running playmode) Changing at runtime is only temporary.
- It can be found by searching in the project panel or at Assets/Prefabs/Environment
- It needs to be the prefab loaded at runtime.  They are global so adding one at runtime will conflict
- EnvironmentalEffectsManager.cs does apply changes to the volume in scene
- Post Processing V2 was included in some effect experiments that are ongoing.
