### ISSUE TITLE
Building Simulator From Source

### ISSUE THREAD

**Issue by doesnotconverge** [lgsvl/simulator#1490]
Hello all,

I am following the installation from source tutorial here https://www.svlsimulator.com/docs/installation-guide/build-instructions/

I don't see documentation as to when the simulator began supporting unity 2020.3.3f1, but after cloning the 2021.1 SVL release I was prompted to download this version of unity (instead of 2019.4.18f1).

I was able to build the simulation successfully, however I have a few version mismatch errors which is preventing the simulation from running.

1. My bundle format versions are com.svlsimulator.2, expected com.svlsimulator.3 for each map.
2. Manifest version format com.svlsimulator.3, expected com.svlsimulator.5

Is this due to the version of the simulator I cloned? Do I have to clone specific versions of these bundles to use (not the ones from the store in the WebUI?) 

Any help would be appreciated. Thank you!

**Comment by zelenkovsky** [comment]
Please read the following blog post: https://www.svlsimulator.com/news/2021-06-08-weekly-pushes

We've started to push the code weekly to the GitHub master branch. If you build asset bundles using master - you should *NOT* upload them to the production website (https://wise.svlsimulator.com).

**IMPORTANT**: Please use the latest 2021.1.1 release tag to build your own asset bundles.

Unless you are interested in a cutting-edge master, then use https://wise.preview.svlsimulator.com. Update your config.yml file for pointing to this URL.
