### ISSUE TITLE
fisheye distortion

### ISSUE THREAD

**Issue by selfsimulator** [lgsvl/simulator#1498]
Hello, lgsvl team. 
I'm trying to extract the fisheye module of SVL simulator separately, so I deleted other codes that have little relevance. However, when the lensdistortion.cs and lensdistortion.compute files are identical, the image appears abnormal distortion. I also found other script data streams that are the same as those in SVL simulator. I will give abnormal pictures, hope to get your enthusiastic answer.
![11](https://user-images.githubusercontent.com/85266706/122323596-e8d14580-cf59-11eb-8df4-911389d97b17.png)
![12](https://user-images.githubusercontent.com/85266706/122323604-ed95f980-cf59-11eb-9f7a-595d57ce7b03.png)

**Comment by EricBoiseLGSVL** [comment]
Why are you extracting SVL distortion source code?

**Comment by selfsimulator** [comment]
> Why are you extracting SVL distortion source code?

Because I just want to have an in-depth understanding of the fisheye realization process, But I didn't understand the distortion model and its principle of distortion calculation in "lensdistortion. Compute" and "lensdistortion. CS"！ So I would like to ask if there is any relevant article on the “calculation model of fish eye distortion” used by the simulator?
And thank you for your attentin on my problem!

**Comment by EricBoiseLGSVL** [comment]
These issues will help #1047 #1009

**Comment by selfsimulator** [comment]
Thank you again for your reply?
I have some questions for you.
The distortion parameter k1k2k3k4 in the document is reflected in the code as b1b2b3b4 calculated by a1a2a3a4. According to what calculation?
![image](https://user-images.githubusercontent.com/85266706/124546477-466ff800-de5d-11eb-9e2a-a1d56a027a84.png)
![image](https://user-images.githubusercontent.com/85266706/124546535-5ab3f500-de5d-11eb-9366-14ae73a8e5f6.png)
![image](https://user-images.githubusercontent.com/85266706/124546559-630c3000-de5d-11eb-8cdf-35b6fd2b0312.png)
And I know that undistortedPos is the distortion polynomial in the document? The Parameter Xi is not specified in the document. What does this parameter mean? What is his geometric relationship with cubetexcoord`s XYZ?

**Comment by selfsimulator** [comment]
> These issues will help #1047 #1009

Thank you again for your reply?
I have some questions for you.
The distortion parameter k1k2k3k4 in the document is reflected in the code as b1b2b3b4 calculated by a1a2a3a4. According to what calculation?
![1](https://user-images.githubusercontent.com/85266706/124622263-8a8ae900-dead-11eb-9d4a-4bc52eedd883.png)
![2](https://user-images.githubusercontent.com/85266706/124622301-92e32400-dead-11eb-9805-0dd185715a7f.png)
![3](https://user-images.githubusercontent.com/85266706/124622329-97a7d800-dead-11eb-9761-c64f4f9029d3.png)
And I know that undistortedPos is the distortion polynomial in the document? The Parameter Xi is not specified in the document. What does this parameter mean? What is his geometric relationship with cubetexcoord`s XYZ?

**Comment by lemketron** [comment]
@kamkolak-lge ?

**Comment by selfsimulator** [comment]
> @kamkolak-lge ?

I mean, I want to know how to convert a1a2a3a4 to b1b2b3b4 in fisheye? And why do this? Where does its algorithm come from?

Then another question is what does the parameter "Xi" in distortion calculation mean? Where does the algorithm it participates in come from?

I didn't find any of the above explanations  in the document.

**Comment by selfsimulator** [comment]
> @kamkolak-lge ?

This is my case code address“ https://github.com/selfsimulator/Fishey ”。 After it clicks the fish eye, the image quality will be particularly blurred, and then the cube box analysis is particularly large, and its splicing is wrong. But there is no change in the code algorithm of computeshader, so the cause of the error has not been found. What's more, I don't understand "undistortuvunified projection" in lensdistortion.compute. Where does the algorithm formula used come from?
