### ISSUE TITLE
Why the width of lane cannot be changed?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1501]
I changed the Display lane width in inspector tab while doing map annotation but when i export base_map.bin file and upload it to dream view, It always display the same width (by default = 3.5). 

Is it wrong way to change the width of lane?

**Comment by EricBoiseLGSVL** [comment]
The exporter defaults to 3.5. See line 547 in ApolloMapTool.cs.  You could extend the code to use this value in apollo export.  We will support sometime soon.

Display Lane Width is just a visualizer in map.  Lanelet2 is the only exporter that uses this value.

**Comment by Addi2020** [comment]
where do I find ApolloMapTool.cs.? in apollo code?

**Comment by ntutangyun** [comment]
> where do I find ApolloMapTool.cs.? in apollo code?

Assets/Scripts/Editor/ApolloMapTool.cs

**Comment by Addi2020** [comment]
@EricBoiseLGSVL Thanks. Its working great to change the width of lane. 

But I have another issue that it changes the width of all the Maplanes together. Is there any way to change width of only one Maplane separately?

**Comment by EricBoiseLGSVL** [comment]
I recommend a new property in the class and you write code to use this new property.  Without seeing what you changed, it is hard to tell.
