### ISSUE TITLE
(Feature Suggestion) svlsimulator with XRDP support

### ISSUE THREAD

**Issue by tic-toc-developer** [lgsvl/simulator#1503]
Many high performance machines are headless, thus  remote access is important.
However, currently the svlsimulator is not compatible with XRDP service. 

Several issues indicated about the incompatibility. (e.g. [issue 1479](https://github.com/lgsvl/simulator/issues/1479), [issue 1431](https://github.com/lgsvl/simulator/issues/1431))

[This page](https://askubuntu.com/questions/1231155/vulkan-driver-stops-working-when-running-in-google-remote-desktop) talks about the Vulkan and  XRDP's rendering mechanism.

Is there any workaround for using XRDP with svlsimulator simultaneously? 
VNC is an option but the quality is not as good as RDP.

**Comment by EricBoiseLGSVL** [comment]
Unity does not support this at this time.  You can post an issue on their forum and request this feature but I have seen many try already.  Maybe they will when they expand Unity cloud services. We will keep an eye out because we know that this is a requested feature.
