### ISSUE TITLE
Ubuntu 20.04 - No Simulator menu on top toolbar

### ISSUE THREAD

**Issue by kk2491** [lgsvl/simulator#1505]
Hi Guys,

Good Day.

Ubuntu version : 20.04   
LGSvl Simulator Git branch used : Master
Unity Hub version : 2019.4.18f1 

I am trying to build SVLSimulator from source on Ubuntu 20.04. I am following the documentation given [here](https://www.svlsimulator.com/docs/installation-guide/build-instructions/#installing-unity-editor).  

I am not getting the **Simulator** option in the Unity editor. 

1. Installed Linux support and Windows support in Unity hub. 
2. As per the documentation I made sure Git LFS is initialized before cloning the repository.
3. Added the project by selecting the cloned repository directory.   
![image](https://user-images.githubusercontent.com/38481564/122590848-bc174e00-d07f-11eb-94ae-9e3064cbc516.png)
4. This is the Unity editor screen I get once I open the project.   ![image](https://user-images.githubusercontent.com/38481564/122590997-f385fa80-d07f-11eb-95ce-608f299d2eab.png) 
5. There is no **Simulator** option in the Unity editor.
6. Console.  
![image](https://user-images.githubusercontent.com/38481564/122591099-1dd7b800-d080-11eb-82af-056d536003bb.png)
7. Project.  
![image](https://user-images.githubusercontent.com/38481564/122591240-4d86c000-d080-11eb-93c1-aa73d9620dbb.png)

I have tried the suggestions given in [Issue361](https://github.com/lgsvl/simulator/issues/361). However, I am still not able to fix the issue.

It would be great if you could guide me in the right direction. 

Thank you,  
KK

**Comment by EricBoiseLGSVL** [comment]
please check that you have installed git lfs before you cloned.  There are many issues here if you have questions. To check read the documentation [here](https://www.svlsimulator.com/docs/installation-guide/build-instructions/). verify that you have image files and not text files.

**Comment by kk2491** [comment]
Hi @EricBoiseLGSVL  Thanks for your reply. 
I followed the documentation step by step. And also made sure I have installed ```git lfs``` before cloning the LGSvl repository. 
Not sure what is going wrong here. 

Thank you

**Comment by EricBoiseLGSVL** [comment]
I see you are on master.  This is a preview release branch for users that are familiar with simulator already and want to preview new features not released yet.  The version for master unity is 2020.3.3f1, you should see this in Unity Hub when you open the project. Never change the version of Unity for the branch, this will break... everything :). You are using the wrong unity version.  Please only use official release branches.  release-2021.1.  That will work with 2019.4.18f1 and with documentation.  I would re-clone because Unity fails when you downgrade a project version.  Sorry about the confusion on master, we will improve our messaging on this.

**Comment by kk2491** [comment]
Thank you so much for the detailed description. Let me give a quick try and come back. 
Please keep the issue open until then.

**Comment by kk2491** [comment]
@EricBoiseLGSVL Thanks, your suggestions helped me to get the Simulator up and running. 
As you suggested I used 2020.3.3f1 and found the ```Simulator``` option in the menu. 

Thanks again for your help.

**Comment by EricBoiseLGSVL** [comment]
Great, my post states to use official release tags but glad it worked.  FYI master is not stable so we don't recommend development on this branch.  It will make it easy to use our new release out soon though ;)
