### ISSUE TITLE
504 Gateway Time-out while visit localhost:8080

### ISSUE THREAD

**Issue by chenxinxu333** [lgsvl/simulator#1510]
While I start lgsvl (2020.06) in ade environment.  I met "504 Gateway Time-out" in my Chrome browser. I also cannot visit the url “
account.lgsvlsimulator.com”.
![image](https://user-images.githubusercontent.com/69612456/122853921-8c00d100-d345-11eb-9c58-0b1056f8fb1a.png)

The same situation like https://github.com/lgsvl/simulator/issues/1217 . Does it mean the upstream server went down?

**Comment by michael2012z** [comment]
Same to me. The web site has been inaccessible since yesterday.

**Comment by chenxinxu333** [comment]
Now, it works again.

**Comment by iKoltcov** [comment]
> Now, it works again. No timeout.

2 hours ago it was working but now there is an error again

**Comment by chenxinxu333** [comment]
> > Now, it works again. No timeout.
> 
> 2 hours ago it was working but now there is an error

**Comment by chenxinxu333** [comment]
Now, it still works. @iKoltcov. I found that once you visit the localhost:8080 successfully, there are some cache in your browser. And if you enter ade environment in the same adehome direcotory, you can visit localhost:8080 again and start lgsvl successfully even if the upstream server went down.

**Comment by EricBoiseLGSVL** [comment]
Sorry, we had an issue but it should be resolved.
