### ISSUE TITLE
OpenDRIVE lane width and spacing issues

### ISSUE THREAD

**Issue by honey5967** [lgsvl/simulator#1512]
![image](https://user-images.githubusercontent.com/56637176/123022122-43fab080-d410-11eb-9de0-ce18f02dc029.png)
 only the line width and spacing defined in "Hd Map Mesh Builder" are applied, not the lane width or type defined in the OpenDRIVE file. On this matter I don't know...
I want to create additional Objects models, can I add a .fbx file with the same name as the OpenDRIVE objects name to the simulator resource?
Thank you..!

**Comment by honey5967** [comment]
A lane at an intersection is not a lane belonging to OpenDRIVE lanes, but a vehicle guideline represented by objects.

**Comment by honey5967** [comment]
It wasn't about the intersection. I'm sorry

**Comment by EricBoiseLGSVL** [comment]
@honey5967 no worries, I think I get what you mean.  HD Map Mesh builder is just to help users that don't have access to 3d modeling tools.  We don't support OpenDrive lane width at this time, sorry.  You can create/add any objects you want to the scene, just be sure to add all assets in the Assets/External/Environments/YourMap folder so they are bundled correctly and save the scene.  Look at CubeTown repo to see how the scene is organized in the folder and in the unity scene.  Have fun creating and let us know if you need help.

**Comment by honey5967** [comment]
Thank you..! curiosity has been resolved
