### ISSUE TITLE
The apollo-5.0  can't show the other vehicles  When I run the lgsvl simulator (version 2021.01.01))

### ISSUE THREAD

**Issue by luogyu7** [lgsvl/simulator#1519]
The apollo platform 5.0  with lgsvl  2021.0101 version could normal  running . As the following pictures:
![4](https://user-images.githubusercontent.com/67385330/123549796-1e1d3500-d79d-11eb-91d0-67ab8a1848b4.png)
![5](https://user-images.githubusercontent.com/67385330/123549804-25dcd980-d79d-11eb-97bd-06dca6e476c0.png)

And I can see the screen scene synchronization .  As the following picture:
![6](https://user-images.githubusercontent.com/67385330/123549869-6177a380-d79d-11eb-9074-4610b3f612a5.png)

I got the result picture with the following  cammands  step by step.
1. pull the docker image with the docker command:  "docker pull lgsvl/apollo-5.0";
2. "git clone --recurse-submodules https://github.com/lgsvl/apollo-5.0.git"
3. "docker/scripts/dev_start.sh";
4. "docker/scripts/dev_into.sh";
5. "./apollo.sh build_opt_gpu";
6. I run "exit" command exit the docker container and run "docker/scripts/dev_into.sh"  reenter the container;
7. "bootstrap.sh";
8. "bridge.sh";

SO, what  wrong is I haven't realize? 

could any  lgsvl&apollo experts help me?

Many thanks .

**Comment by EricBoiseLGSVL** [comment]
@cyberphysicalrobotics @revati-naik ?

**Comment by lemketron** [comment]
What is the problem you are having?  Looks like you're doing great so far. 

Continue on with the Apollo 5.0 instructions, from where it says "Create a simulation" here: https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/#launching-apollo-alongide-the-simulator

Then continue with "Open Apollo 5.0 Dreamview in a browser" and "Select a destination by clicking on a lane-line and clicking Submit Route" and finally "Watch the vehicle navigate to the destination."

**Comment by EricBoiseLGSVL** [comment]
I think they are missing ground truth in dreamview, right @luogyu7 ?

**Comment by lemketron** [comment]
@luogyu7 Can you show the Module Controller view from Dreamview?

**Comment by luogyu7** [comment]
Very thanks for your reply.
When I run  the vehicles at the Dreamview with the ip localhost:8888 . I can get the init  
web page  with the message " please send the car init position and map data. "
![1](https://user-images.githubusercontent.com/67385330/123772949-d7dfe700-d8fe-11eb-93a7-db271eae4018.png)

and  after I run the commands as following:
1. at the "apollo" folder run :" ./scripts/bootstrap.sh";
2. input the address "localhost:8888"  (  when I input "localhost:9090"  ,It didn't work. I don't know the reason.)
3. run the command "./scripts/bridge.sh",I can see the terminal like the following picture:
![3](https://user-images.githubusercontent.com/67385330/123773983-9b60bb00-d8ff-11eb-8cc0-a4a12e41d44c.png)

4. then, I run the simulator client (version 2021.01.01),and  select a simulator I have set the configuation.
![4](https://user-images.githubusercontent.com/67385330/123774253-d19e3a80-d8ff-11eb-9ed2-3387a25fb338.png)

And the left column  is the situation after I click the button like the  letter "i":
![5](https://user-images.githubusercontent.com/67385330/123774498-0c07d780-d900-11eb-87b7-e3d543f9e8b6.png)

the message is showling in the picture:
![7](https://user-images.githubusercontent.com/67385330/123774770-538e6380-d900-11eb-8d40-cfa5bcfd9e72.png)

5. now  the situation of the simulator and Dreamview is like:
![8 1](https://user-images.githubusercontent.com/67385330/123776616-09a67d00-d902-11eb-9f2a-d587c1ed5138.png)

![8 2](https://user-images.githubusercontent.com/67385330/123776620-0b704080-d902-11eb-9996-b7d86e213a7d.png)
![8 3](https://user-images.githubusercontent.com/67385330/123776628-0d3a0400-d902-11eb-88cc-23c32e361dc3.png)

The above pictures show the “Module Controller view”  by move the simulator，And move the car via the simulator  and show the result at the dreamview(localhost:8888).
I will upload  a  short video by a link to express the situation clearly.

Here ,I thanks the reply of @EricBoiseLGSVL  . I will learn the tutorial of https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/#launching-apollo-alongide-the-simulator . I may not completely learn the second  half of the tutorial.  But ,I not sure if I will found the answers .But I will learn it carefully.
  
Thanks @lemketron 's reply . The Module Controller view  like following picture:
![9](https://user-images.githubusercontent.com/67385330/123778747-044a3200-d904-11eb-9392-2c5c450502cb.png)

except it I add other view picture at the following :
![9](https://user-images.githubusercontent.com/67385330/123778916-32c80d00-d904-11eb-99bd-9edff72b6f2a.png)
![9 1](https://user-images.githubusercontent.com/67385330/123778942-3a87b180-d904-11eb-9bac-ec613ff4880f.png)
![9 2](https://user-images.githubusercontent.com/67385330/123778963-42dfec80-d904-11eb-9365-a3c858f35b58.png)
![9 3](https://user-images.githubusercontent.com/67385330/123778976-46737380-d904-11eb-9625-b4ae4e599e41.png)


About the “ground truth” ，where should I set at the web page dreamview  to found the ground truth?

This reply have so many pictures , many thanks for your patience.
Thanks a lot.

**Comment by luogyu7** [comment]
Maybe I  have many error to debug.
I have so much content to learn.


And  about the "Select a destination by clicking on a lane-line and clicking Submit Route"
I have select the initial point and the destination point on the map  like the following picture:
![9 3](https://user-images.githubusercontent.com/67385330/123781596-0366cf80-d907-11eb-80fd-dd02794365a0.png)
After I click the "Send routing request" button .  The dreaview show a red line from the intial position to  the destination point.  BUT the car can't move automaticlly.
![10](https://user-images.githubusercontent.com/67385330/123781797-3a3ce580-d907-11eb-8b86-703f864d2547.png)

Where  is the worry  that I haven‘t  realized ?
Thank you very much.

**Comment by EricBoiseLGSVL** [comment]
Planning should show a green line if everything is correct.  Any ideas @lemketron ?

**Comment by lemketron** [comment]
> About the “ground truth” ，where should I set at the web page dreamview to found the ground truth?

The information about other vehicles in the scene either comes from the simulator (ground truth) or from the output of Apollo's perception module. You are running apollo 5.0 with perception disabled which would explain why you're not seeing the other vehicles in the scene.

Do you need to run apollo 5.0 for some specific reason? I would suggest running newer Apollo as documented here:
https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/

Running perception (and traffic light perception) requires a lot of CPU/GPU resources and makes it difficult to run on a single computer with the simulator. For that case I recommend you check out the "modular testing" documentation which shows how to use the "3D ground truth" and "signal" sensors in the simulator to provide the output that those Apollo modules would have generated.

**Comment by lemketron** [comment]
> Planning should show a green line if everything is correct. Any ideas @lemketron ?

When first trying to set a destination, I recommend clicking "remove all points" and then click once somewhere across the intersection. You should have one red dot there and you can zoom in to see it using the mouse scroll wheel. Then click "Send routing request" and you should see a red path to the destination. There are other paths that also need to appear, like the outputs of routing and planning modules.

This video from the [modular testing documentation](https://www.svlsimulator.com/docs/tutorials/modular-testing/) shows a pretty good overview of what this all looks like when it's working properly: https://youtu.be/7JpxbXf8oZM

**Comment by luogyu7** [comment]
Thanks for your reply and your patience.
I will try the link tutorial and research it carefully. 
Currently I'm not very clear about the   technical detail. If I have new issues to produce I will show it .
Many thanks.

**Comment by luogyu7** [comment]
> > About the “ground truth” ，where should I set at the web page dreamview to found the ground truth?
> 
> The information about other vehicles in the scene either comes from the simulator (ground truth) or from the output of Apollo's perception module. You are running apollo 5.0 with perception disabled which would explain why you're not seeing the other vehicles in the scene.
> 
> Do you need to run apollo 5.0 for some specific reason? I would suggest running newer Apollo as documented here:
> https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/
> 
> Running perception (and traffic light perception) requires a lot of CPU/GPU resources and makes it difficult to run on a single computer with the simulator. For that case I recommend you check out the "[modular testing](https://www.svlsimulator.com/docs/tutorials/modular-testing/)" documentation which shows how to use the "3D ground truth" and "signal" sensors in the simulator to provide the output that those Apollo modules would have generated.

I just realized the significance of this reply.  Perception  of  apollo  is a must for me. I need to test the  algorithms in perception.   This is an very important need for me.  SO, I may run perception module in my workstation（display card 2080TI x 1 ， memory:30G ）  .  Are there any methods  to run apollo's perception module?   It means a lot to me. 
Hope for your reply.
Thanks a million.

**Comment by luogyu7** [comment]
> > About the “ground truth” ，where should I set at the web page dreamview to found the ground truth?
> 
> The information about other vehicles in the scene either comes from the simulator (ground truth) or from the output of Apollo's perception module. You are running apollo 5.0 with perception disabled which would explain why you're not seeing the other vehicles in the scene.
> 
> Do you need to run apollo 5.0 for some specific reason? I would suggest running newer Apollo as documented here:
> https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/
> 
> Running perception (and traffic light perception) requires a lot of CPU/GPU resources and makes it difficult to run on a single computer with the simulator. For that case I recommend you check out the "[modular testing](https://www.svlsimulator.com/docs/tutorials/modular-testing/)" documentation which shows how to use the "3D ground truth" and "signal" sensors in the simulator to provide the output that those Apollo modules would have generated.

I just realized the significance of this reply.  Perception  of  apollo  is a must for me. I need to test the  algorithms in perception.   This is an very important need for me.  SO, I may run perception module in my workstation（display card 2080TI x 1 ， memory:30G ）  .  Are there any methods  to run apollo's perception module?   It means a lot to me. 
Hope for your reply.
Thanks a million.

**Comment by lemketron** [comment]
> I just realized the significance of this reply. Perception of apollo is a must for me. I need to test the algorithms in perception. This is an very important need for me. SO, I may run perception module in my workstation（display card 2080TI x 1 ， memory:30G ） . Are there any methods to run apollo's perception module? It means a lot to me.

You can run perception in Apollo 5.0 (though 5.0 is very old) or you can try running perception in latest Apollo (master). If you have problems with perception in Apollo you might ask for help on the [Apollo issues](https://github.com/ApolloAuto/apollo/issues) page.

**Comment by luogyu7** [comment]
Thanks very much.
