### ISSUE TITLE
signaldata.csv and vector.csv in the map of SanFrancisco is empty

### ISSUE THREAD

**Issue by windwolf9** [lgsvl/simulator#1533]
hello,
I'm testing the traffic light module，but i Can't get the effect,and I debug the program and found the reason is signaldata.csv and vector.csv in the map of SanFrancisco is empty. 
I downloaded it from : https://github.com/lgsvl/autoware-data .Can you provide the data?
The platform I use：autoware1.13 + lgsvl2020.06 (SanFrancisco)
Thank you very much！

**Comment by EricBoiseLGSVL** [comment]
@windwolf9 If you are using 06 release, and following current release documentation you won't be able to use some features.  What documentation are you following?

**Comment by windwolf9** [comment]
@EricBoiseLGSVL Thank you for your reply, What you replied may not be the cause of the problem. I run the trafficlight_recognizer in autoware1.13.0 , the node of  “feat_proj” need signaldata.csv and  vector.csv,but i open " /shared_dir/autoware-data/SanFrancisco/data/map/vector_map/signaldata.csv",it is empty. 
I run with  ” BorregasAve ”map, it is ok, I checked the BorregasAve map(/autoware-data/BorregasAve/data/map/vector_map/signaldata.csv), it is not empty.
Thank you very much！

**Comment by EricBoiseLGSVL** [comment]
What version of simulator are you using?  In older versions of simulator, signaldata.csv will be empty for SF map and not Borregas. What version are you using?  Once we confirm this we can look into why this is missing for you.

**Comment by windwolf9** [comment]
@EricBoiseLGSVL Thank you for your reply!  I use the simulator version is “lgsvlsimulator-linux64-2020.06”.
You are right ,autoware-data( https://github.com/lgsvl/autoware-data) is too old, signaldata.csv and vector.csv in the vector_map of SanFrancisco is empty, only  signaldata.csv and vector.csv in ” BorregasAve ”map is not empty.

**Comment by EricBoiseLGSVL** [comment]
Autoware vector maps do not have signal data supported. I think this is an older format that we haven't added to in a while.  I'll ask internally on this. Please do not post duplicate issues.

**Comment by windwolf9** [comment]
ok , thank you very much，If there is any new progress, would you please reply here, thanks!

**Comment by EricBoiseLGSVL** [comment]
No problem.  Missing signaldata is expected for autware vector map.  Since Autoware.AI is near end of life, we put work into supporting Autoware.Auto and lanelet2 for this data.
