### ISSUE TITLE
Some questions for sensor coordinate systems in simulator 

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1534]
**### For Lidar Sensor**
"Lidar sensor" will create "PointCloudData" from simulator.
![Screenshot from 2021-06-30 19-53-28](https://user-images.githubusercontent.com/5969040/123956082-e270ae00-d9dc-11eb-9e53-cd97fa6a42e7.png)

1. "Points" ( xyz are coordinates in world space )
    Does the world space mean that use the HD map origin as ( 0, 0, 0) ?

2. "Transform" ( world to lidar space transform )
    Does the lidar space mean that use the Sensor Configuration (X,Y,Z) as (0, 0, 0) ?
    

**### For  3D Ground Truth Sensor**
"3D Ground Truth Sensor" will create "Deteced3DObject" from simulator.
![Screenshot from 2021-06-30 20-00-37](https://user-images.githubusercontent.com/5969040/123957044-ef41d180-d9dd-11eb-9735-47549156b82d.png)

1. "Position"
    What is the space used in "Postion" ?
    I guees it use the Sensor Configuration (X,Y,Z) as (0, 0, 0).
 

As I know that All Sensor data use [the Unity Coordinate System](https://github.com/siemens/ros-sharp/wiki/Dev_ROSUnityCoordinateSystemConversion) 

Is that correct ?

**Comment by EricBoiseLGSVL** [comment]
1) yes
2) lidar sensor transform
3) yes
Yeppers

**Comment by joeking11829** [comment]
Thank you.
