### ISSUE TITLE
Error while Save/restore vehicle position.

### ISSUE THREAD

**Issue by kkhitsko** [lgsvl/simulator#154]
There is some error while I try to reset to last saved position of vehicle by pressing F9 button. Restored position is different from last saved position.

**Comment by martins-mozeiko** [comment]
By "saved position" you mean position when you press F5?
How different is the restored position? Is it nearby where you saved, somewhere else completely?

**Comment by kkhitsko** [comment]
> By "saved position" you mean position when you press F5?

Yes

> How different is the restored position? Is it nearby where you saved, somewhere else completely?

x and y coordinates of restored position almost equal to the saved position, by z is mush less than zero and constantly decreasing. It's looks like that car falls.

![position restore](https://user-images.githubusercontent.com/1698696/57669989-f8ad2b80-7615-11e9-9110-4f219b2ca85a.png)

But If I press "Vehicle position reset" button, vehicle position is restored correctly.
