### ISSUE TITLE
Should EGO drive after a collision or not

### ISSUE THREAD

**Issue by JuliaEmelianova** [lgsvl/simulator#1543]
Could you clarify please what is an expected behavior of EGO after it collides with a pedestrian, NPC or some object? Should it continue its movement or should it remain be stopped?

**System details**
Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Nvidia GeForce GTX 1080 Ti (GPU memory 11GB)
Ubuntu 20.04.2 LTS
Apollo master (latest Apollo was cloned at 2021-06-05)
Docker version: apolloauto/apollo:dev-x86_64-18.04-20210517_1712
SVL Simulator 2021.1.1
Browser: Chrome

**Comment by lemketron** [comment]
Usually a collision indicates the end of a failed test and should reported as such in the [test results](https://www.svlsimulator.com/docs/user-interface/web/test-results/).

**Comment by JuliaEmelianova** [comment]
@lemketron Thanks for the reply. If I understand correctly, it is not important at current stage of project, isn't it? Such a question arised due to the possible tests related to an expected behavior of EGO vehicle after a collision.

**Comment by lemketron** [comment]
SVL Simulator is intended for testing of autonomous vehicles (and other robots) and not so much for accurate accident reconstruction (after the point of impact) but I believe there are other tools used (e.g. by insurance companies and others) to recreate what happens after a collision.

**Comment by JuliaEmelianova** [comment]
@lemketron Thanks for the explanation
