### ISSUE TITLE
I can't find scenic file

### ISSUE THREAD

**Issue by blufissure** [lgsvl/simulator#1545]
I read the documentation,you have introduced Scenario Runner,but when i installed the svlsimulator,i can't find scenic file,i find the scenario_runner.sh file and the docker directory,can you tell me how i can find the  scenarios/Scenic directory?thank you very much

**Comment by lemketron** [comment]
The document you are referring to is out of date and not relevant for SVL Simulator 2021.1.x. Sorry for the confusion.

Please refer to the #1334 for more information on using Scenic with SVL Simulator.

**Comment by blufissure** [comment]
thank you very much
