### ISSUE TITLE
EGO incorrectly detects rotation of NPC vehicles at Highway101GLE and Shalun maps

### ISSUE THREAD

**Issue by JuliaEmelianova** [lgsvl/simulator#1546]
**Description**
When I run a simulation with random traffic and use Highway101GLE map, EGO incorrectly detects rotation of NPC vehicles:

![incor_detect_rot_1](https://user-images.githubusercontent.com/80924057/124476754-48ca4780-ddb4-11eb-8b0b-d0bb994706d9.png)

I have downloaded HD Map (apollo 50) for Highway101GLE from the Web UI Store and used a script generate_map.sh to generate map files. I use Apollo 6.0 (modular testing) for sensor configuration.

**System details**
Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Nvidia GeForce GTX 1080 Ti (GPU memory 11GB)
Ubuntu 20.04.2 LTS
Apollo version: master-2021-07-01-9120b75d4a
Docker version: apolloauto/apollo:dev-x86_64-18.04-20210517_1712
SVL Simulator 2021.1.1
Browser: Chrome

**Comment by JuliaEmelianova** [comment]
EGO incorrectly detects rotation of random NPC vehicles also when I use Shalun map:

![incor_detect_rot_Shalun](https://user-images.githubusercontent.com/80924057/124513216-551dc700-ddeb-11eb-9296-6cad16cd3afa.png)

**Comment by EricBoiseLGSVL** [comment]
Hmm, might be a map origin issue.  Thanks for posting.

**Comment by EricBoiseLGSVL** [comment]
This has been fixed and will be in our next release.  Thanks for posting
