### ISSUE TITLE
How get the map of com.svlsimulator.4?

### ISSUE THREAD

**Issue by DZiYou** [lgsvl/simulator#1550]
I use the simulator build from source 2021.2,but when I run it ,there is a error : BUndleFormat: CUbe Town is for bundl version com.svlsimulator.2 but currently running simulator supports only com.slvsimulator.4 bundle version.
I can't found com.slvsimulator.4 map in map store,how could I get it?Thank you .
![Screenshot from 2021-07-06 14-37-22](https://user-images.githubusercontent.com/15259566/124554017-1417c800-de68-11eb-810d-65198d6cc637.png)

**Comment by zelenkovsky** [comment]
*IMPORTANT* Please read https://www.svlsimulator.com/news/2021-06-08-weekly-pushes

Do not upload asset bundles built using cutting edge master to https://wise.svlsimulator.com production cloud deployment. Use wise.preview.svlsimulator.com instead.

**Comment by DZiYou** [comment]
> _IMPORTANT_ Please read https://www.svlsimulator.com/news/2021-06-08-weekly-pushes
> 
> Do not upload asset bundles built using cutting edge master to https://wise.svlsimulator.com production cloud deployment. Use https://wise.preview.svlsimulator.com instead.

 So ， How to link 2021.2 SImulator to https://wise.preview.svlsimulator.com ?
          and https://wise.preview.svlsimulator.com  map is com.slvsimulator.3,not equla com.slvsimulator.4
thank you

**Comment by lokesku** [comment]
2021.2 is still not released. We have just pushed the spurces, but we will be updating the production and preview deployments this week to add support for 2021.2 release. Please wait for few days till we announce 2021.2 release.
