### ISSUE TITLE
Custom map asset bundle upload error

### ISSUE THREAD

**Issue by vin-cloud** [lgsvl/simulator#1555]
Hello, facing issues with uploading generated asset bundle of custom map.
Process followed as below
a. Created Custom map based on Roadrunner tool
b. Unity import and build
c. AssetBundles generated -> can extract the contents
d. Upload on svlsimulator.com portal -> error as seen below
![image](https://user-images.githubusercontent.com/61731065/124690748-9a3e1800-df15-11eb-9ba1-c51880e05ece.png)
AssetBundle file link: http://naver.me/5DHtMdRI

**Comment by EricBoiseLGSVL** [comment]
What version of simulator are you building assets with?

**Comment by vin-cloud** [comment]
> What version of simulator are you building assets with?
Please find the details below:
![image](https://user-images.githubusercontent.com/61731065/124695173-a8903200-df1d-11eb-9a7a-65268980a31c.png)

**Comment by EricBoiseLGSVL** [comment]
Since you are using the latest release (that really shouldn't have gone out yet). You will need to make a new bundle with the latest simulator source code.  Please build a new bundle and use preview webUI see #1550 .  Sorry about the confusion

**Comment by vin-cloud** [comment]
> e build a new bundle and use

The _master_ version?

**Comment by EricBoiseLGSVL** [comment]
ah ok, master is latest so you will need a new version of Unity.  Please see the #1550 issue. master is preview and uses the latest changes.  Unity version is 2020.3.3f1.  Not sure what version you were using before because latest release was 2019.4.18?
Release tags are our official release with docs (except for 2021.2 bc it was released early on accident) that state the Unity version
Master is a preview for users that want to see in progress work and only work on wise.preview. If you are not familiar with the simulator I recommend you stick with 2021,1 release and use unity 2019.4.18f1 until our backend is up and running for release 2021.2. Sorry about the confusion.

**Comment by vin-cloud** [comment]
@EricBoiseLGSVL Tried generating Asset Bundle using the version you mentioned,
LGSVL: 2021.1 and Unity 2019.4.18f1.
**Issues:**
a. **Cannot generate Asset Bundle (Build has Binary Options (Not Bundles))**
![image](https://user-images.githubusercontent.com/61731065/124720587-434f3780-df43-11eb-963b-02b4ba277eb0.png)

b. **Error while building** 
![image](https://user-images.githubusercontent.com/61731065/124720472-24e93c00-df43-11eb-87b1-c261818ea65c.png)

**Comment by EricBoiseLGSVL** [comment]
You have an error in the map annotation.  You also need to delete the directional light in scene when you build.
```
var firstPt = lane.transform.TransformPoint(lane.mapLocalPositions[0]);
```
You probably have a lane with 0 local positions.

**Comment by bluecar12** [comment]
@EricBoiseLGSVL Hey, I'm having the same issue as referenced here, but I'm using the versions you suggested here: 2021,1 release and unity 2019.4.18f1. To eliminate the possibility that it is my project that is the issue, I am using the CubeTown example project. Do you have any suggestions to solve this? Screenshots below
![image](https://user-images.githubusercontent.com/87210454/125139769-fd6eac80-e0c5-11eb-91b8-d32bdef4b042.png)
![image](https://user-images.githubusercontent.com/87210454/125139898-39a20d00-e0c6-11eb-85ce-d738a238ca2a.png)
![image](https://user-images.githubusercontent.com/87210454/125140007-72da7d00-e0c6-11eb-84bb-a46d692d8c91.png)

**Comment by EricBoiseLGSVL** [comment]
Please post the modified cubetown so I can see if the bundle is correct. Do you have errors when you try to build it?

**Comment by bluecar12** [comment]
@EricBoiseLGSVL
I solved the issue and was able to get it uploaded. 
>Do you have errors when you try to build it?
For future reference, fixing all build errors is crucial to getting the assetbundle to upload. This seems fairly obvious in retrospect, but I assumed build errors were somewhat ignorable like other large projects.

Thanks for your help

**Comment by EricBoiseLGSVL** [comment]
Ah, good that you solved it.  Yes, nothing will work if you have compile errors. That is why I always pull the console panel right next to the project panel on the bottom of the editor to always see errors.  Warnings and logs are fine but red == must fix :)

**Comment by EricBoiseLGSVL** [comment]
@vin-cloud were you able to solve your issue as well?
