### ISSUE TITLE
I got an error when i use "Lane Line Detector" after i remove a BoundryLine from annotation.

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1561]
Hi LGSVL Teams,

I remove the "BoundaryLine_221" from the Shalun map, because it is an incorrect annotation.

![image](https://user-images.githubusercontent.com/5969040/124871149-48b98a00-dff6-11eb-956e-420043249899.png)

After that, I use the LaneLine Detector to re-generate lane-line information.
But I got an error
![image](https://user-images.githubusercontent.com/5969040/124871995-4f94cc80-dff7-11eb-8929-3db431bc3469.png)

I add some debug message, and I found that it seems to leave an null object.
![image](https://user-images.githubusercontent.com/5969040/124872302-aac6bf00-dff7-11eb-978c-f63a586fa377.png)

How could I completely remove the BoundaryLine and let "LaneLine Detector" works correctly.

Thanks

**Comment by luqiang21** [comment]
Looks like "BoundaryLine_221" is the right boundary line of a lane. You need to find out that lane and make sure to have the correct right boundary line for that lane after you remove "BoundaryLine_221".

**Comment by joeking11829** [comment]
> Looks like "BoundaryLine_221" is the right boundary line of a lane. You need to find out that lane and make sure to have the correct right boundary line for that lane after you remove "BoundaryLine_221".

Thanks for the reply.

What is the meaning of left/right boundary line ?

**Comment by luqiang21** [comment]
> BTW, What is the meaning of left/right boundary line ?

The region between left and right boundary line is the actual area of that lane. The boundary lines may be shared with two adjacent lanes.

**Comment by joeking11829** [comment]
> > BTW, What is the meaning of left/right boundary line ?
> 
> The region between left and right boundary line is the actual area of that lane. The boundary lines may be shared with two adjacent lanes.

I got it.
Thank you.
