### ISSUE TITLE
Self-build simulator cannot connect to WebUI server

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1562]
I found that self-build simulator cannot connect to WebUI server.
But I could connect it yesterday.

![image](https://user-images.githubusercontent.com/5969040/124878414-a94cc500-dffe-11eb-8e3b-a47926bc098a.png)

**Comment by lemketron** [comment]
Could you try unlinking your simulator (menu in the upper right corner) and then (make sure simulator is online and then) click "link to cloud" again, and make a new cluster for it and see if that works? You'll also need to update your simulations to use the new cluster.

**Comment by zelenkovsky** [comment]
If you are modifying the simulator code, making it incompatible with the official release or/and build your own assets, please update ```config.yml``` to use https://wise.preview.svlsimulator.com

Read more here: https://www.svlsimulator.com/news/2021-06-08-weekly-pushes

**Comment by joeking11829** [comment]
> Could you try unlinking your simulator (menu in the upper right corner) and then (make sure simulator is online and then) click "link to cloud" again, and make a new cluster for it and see if that works? You'll also need to update your simulations to use the new cluster.

I unlink the cloud and create a new cluster.
I found that when I use self-build simulator to create a new cluster, the simulator version is empty.
![image](https://user-images.githubusercontent.com/5969040/125025745-ce503f00-e0b5-11eb-8fc3-8d1352a63f0d.png)

And when I create a new simulation with the cluster, It show some errors.
![image](https://user-images.githubusercontent.com/5969040/125025980-428ae280-e0b6-11eb-9a5f-2ac838ba4051.png)
just like the issue #1566 


But when I use the official release simulator (svlsimulator-windows64-2021.2), It will show the simulator version.
![image](https://user-images.githubusercontent.com/5969040/125026174-9d243e80-e0b6-11eb-8791-bb78cde7a82d.png)
Everything will be fine with the Cluster which has simulator version.

Any idea to fix that ?
Thanks.

**Comment by EricBoiseLGSVL** [comment]
@thisisdavidfrank

**Comment by joeking11829** [comment]
reference to #1574 .
Now I can create new cluster for self-build simulator ( Simulator version: dev ).
![image](https://user-images.githubusercontent.com/5969040/125548394-051b145e-8337-4174-978f-de0ba6d5d3aa.png)

Thanks for fixed the issue.
