### ISSUE TITLE
Vehicle state sensor not publishing

### ISSUE THREAD

**Issue by luym11** [lgsvl/simulator#1565]
From the [description](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#vehicle-state), it is expected that the vehicle state sensor publishes to a topic such as "/svl/vehicle_state". However, when adding this sensor on the vehicle model and run, this sensor seems to be subscribing from its corresponding topic, rather than publishing. 

Version: 2021.1
Platform: Ubuntu x86

**Comment by revati-naik** [comment]
@luym11 The vehicle state sensor is supposed to be subscribing to the lgsvl/vehicle_state topic. The docs for this would be updated soon. Thanks.
