### ISSUE TITLE
Keyboard Control Sensor  - Sensor is not compatible with the vehicle's version

### ISSUE THREAD

**Issue by nparkstar** [lgsvl/simulator#1568]
All simulations are invalid with message "Keyboard Control Sensor -Sensor is not compatible with the vehicle's version" after using new version(2021.2).
Anybody tell me the way to fix it please?

**Comment by JWishere** [comment]
Did you set bridge to any thing but no-bridge? In my case, I could solve that by setting ROS2 brige and ROS2 autopilot. I don't know why.

**Comment by zelenkovsky** [comment]
Please provide Keyboard Control Sensor version, version of your Vehicle asset bundle and Version of the Simulator you are using. Make sure your final sensor configuration is compatible with at least one version of the simulator.

What assets are default and what assets were built custom?
Was simulator re-built or you are using pre-built binary?

**Comment by nparkstar** [comment]
> Please provide Keyboard Control Sensor version, version of your Vehicle asset bundle and Version of the Simulator you are using. Make sure your final sensor configuration is compatible with at least one version of the simulator.
> 
> What assets are default and what assets were built custom?
> Was simulator re-built or you are using pre-built binary?

Thank you for your answer.
I used binary simulator(svlsimulator-windows64-2021.2.zip).
I just used pre-configured simulation(Local-Random: Cubetown (Manual Drive)) with changing cluster(my cluster) and Sensor Configuration to Keyboard Control.

That's all.

**Comment by EricBoiseLGSVL** [comment]
Be sure to clear local assets with clear cache to make sure you aren't loading an old asset.

**Comment by nparkstar** [comment]
> Be sure to clear local assets with clear cache to make sure you aren't loading an old asset. It's in the main menu in the top right drop down.

-> I tried, but it didn't work. Did you run simulator with 'Keyboard Control' ?
I want to know everybody run with 'Keyboard Control' successfully on release-2021.2.

**Comment by nparkstar** [comment]
![keyboard-control-error](https://user-images.githubusercontent.com/52224980/125158746-13f03300-e1ae-11eb-8fb8-28c72095322d.PNG)

I see this message always.

**Comment by Maestroxr** [comment]
I am having the same issue as described by 'nparkstar'.

**Comment by EricBoiseLGSVL** [comment]
You need to remove the old sensors from the vehicle configuration.  Sorry, we had some issues migrating with the latest release. Just create a new vehicle and a new sensor config with the updated sensors.  If you clear cache, you need to update webui to use new sensors.  We are working to fix this issue for next release.

**Comment by nparkstar** [comment]
> You need to remove the old sensors from the vehicle configuration. Sorry, we had some issues migrating with the latest release. Just create a new vehicle and a new sensor config with the updated sensors. If you clear cache, you need to update webui to use new sensors. We are working to fix this issue for next release.


Thank you for your answer, and I hope you fix it asap.
But I don't understand exactly what you said.
Would you tell me more details?

**Comment by EricBoiseLGSVL** [comment]
Are you building a new binary?  If so you will need to wait until we can release a fix for users that are building binaries locally.
If not, you need to unlink the simulator in webui and then run the simulator and relink.  This should fix the issue.  Be sure your old vehicle config is not used, this is what I am going through.  Make a new vehicle and add the latest sensors from webui.

**Comment by DZiYou** [comment]
> Are you building a new binary? If so you will need to wait until we can release a fix for users that are building binaries locally.
> If not, you need to unlink the simulator in webui and then run the simulator and relink. This should fix the issue. Be sure your old vehicle config is not used, this is what I am going through. Make a new vehicle and add the latest sensors from webui.

Sorry.
I made the following attempts:
Step 1: delete all simulation, clusters, vehicle and plugins from webui.
Step 2: close webui and SVL simulator.
Step 3: delete the folder "~ /. Config / unity3d / lgelectronics / svlsimulator"
Step 4: start the downloaded svlsimulator 2021.2 (the downloaded binary file, not the source code)
Step 5: rerun link to cloud, add new vehicles that have never been used before, add new sensor configuration, including keyboard control.
But there is no solution. My question is, why can't I download the binary source code? Do I need to wait for the server to update?

**Comment by EricBoiseLGSVL** [comment]
Wait, you can't run the binary source code?  Please post your player.log here so I can see the errors

**Comment by DZiYou** [comment]
> Wait, you can't run the binary source code? Please post your player.log here so I can see the errors

There seems to be no problem now. But I didn't do anything, I just repeated the previous operation.
thank you!

**Comment by EricBoiseLGSVL** [comment]
back-end pushed a fix :)

**Comment by nparkstar** [comment]
> back-end pushed a fix :)

Thank you very much! 
It works!
