### ISSUE TITLE
Failed to launch TestCase runtime 

### ISSUE THREAD

**Issue by blxl909** [lgsvl/simulator#1571]
When I use the runtime template Python API, I get the error Failed to launch TestCase runtime 
![QQ图片20210712145651](https://user-images.githubusercontent.com/61344726/125244022-6867ef80-e321-11eb-8a70-494cecd37e57.png)
![D8{ B~}X_%S2T1~_D X%FNR](https://user-images.githubusercontent.com/61344726/125244239-a9f89a80-e321-11eb-8c26-2ed9d7837424.png)

maybe I should modified the code?

by the way, when I use API Only,(05-ego-drive-in-circle.py), I can only move the cemare, the vehicel can't move after I pressing the enter button, how can I deal with it?

**Comment by Gastastrophe** [comment]
Did you close this because you fixed the issue? I am having the same problem

**Comment by blxl909** [comment]
> Did you close this because you fixed the issue? I am having the same problem
 Yes, I fixed it. But this error may result from many reasons. At this time , it's because I use the offline cluster. But if you are using windows platfrom, since the simulator folder doesn't have a folder named TestCase, it will also cause this error. So you should using Linux instead. Maybe there still other reason, but that what I know for now.
