### ISSUE TITLE
Does Visual Scenario Editor simulation without autopilot run on windows?

### ISSUE THREAD

**Issue by dheerajakula** [lgsvl/simulator#1581]
Hi, I am trying to run a Visual Scenario editor template simulation in widows with sensor configuration as key-board control. 
**OS: windows
LGSVL version: 2021.1**

But I am getting this error:
**Error on latest run: Failed to launch TestCase runtime.**

![image](https://user-images.githubusercontent.com/25077150/125547224-44a86e21-f67c-4a0c-a77a-fb9c83862648.png)

**Comment by EricBoiseLGSVL** [comment]
VSE templates are only available on Linux.  We are working on windows support currently and hope to release it soon. See [here](https://www.svlsimulator.com/docs/running-simulations/runtime-templates/).
