### ISSUE TITLE
Random Traffic is not working with self-build simulator

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1582]
Hi LGSVL Teams,

Reference to #1562
self-build simulator from branch: release-2021.2  ( only modify some tag configuration. )

I found that random traffic is not working, when I use the self-build simulator.

![image](https://user-images.githubusercontent.com/5969040/125549924-a921a79f-6f8d-40a2-8f4a-b27c517ef854.png)

![image](https://user-images.githubusercontent.com/5969040/125549434-600acc7f-1fe6-40f5-9115-a9a17545a039.png)

Any Idea to fix it ?
Thanks

**Comment by EricBoiseLGSVL** [comment]
Did you copy over the npcs and pedestrian asset bundles to the new binary you made?  If you look in the release binary, in the AssetBundles folder, we place the bundles.  Just copy the whole folder.  We hope to support in webui soon.

**Comment by joeking11829** [comment]
> Did you copy over the npcs and pedestrian asset bundles to the new binary you made? If you look in the release binary, in the AssetBundles folder, we place the bundles. Just copy the whole folder. We hope to support in webui soon.

Thanks for the reply.
It works fine after I copy the npcs and pedestrian asset bundles to self-build simulator.

BTW, the internet connection of your website (https://wise.svlsimulator.com/) is unstable today.

**Comment by EricBoiseLGSVL** [comment]
Glad to help and thanks for letting us know. @thisisdavidfrank
