### ISSUE TITLE
Cannot create a new cluster!!! 

### ISSUE THREAD

**Issue by wobushigaoying** [lgsvl/simulator#1583]
Hello

I am using the latest version of simulator version 2021.2.

I have unlinked the simulator and deleted the cluster of simulator version 2021.1. 

When I click "Create cluster" button, the website reports an error below:

![image](https://user-images.githubusercontent.com/18672103/125593042-5a0c3b2b-7c94-4864-9d3c-4535f776df89.png)

**Comment by FiIipe** [comment]
I have the same problem. I think they are changing things right now and everything is a bit unstable. The webui is also super slow and I can't delete vehicles.

**Comment by ebadi** [comment]
The same problem:
![image](https://user-images.githubusercontent.com/1111940/125631257-e0792e4a-8fc3-4d52-9608-d09fe3735f2d.png)

**Comment by ebadi** [comment]
The issue is now resolved for me.

**Comment by EricBoiseLGSVL** [comment]
@thisisdavidfrank

**Comment by wobushigaoying** [comment]
haha, I had transferred to the old version, 2021.1.  The problem has gone. :)

**Comment by zelenkovsky** [comment]
I'm closing this issue, based on the comment above. Please re-open if that happens again.

PS: we've identified the reason for the 504 HTTP error. It is temporarily patched. A proper fix is yet to come. Would you mind reporting if you see 504 HTTP errors again?

**Comment by DZiYou** [comment]
I got the same issue, cannot create a new cluster.
Is it possible to launch an offline version?

**Comment by ihsanyalcinkaya** [comment]
Same here. I cannot create a new cluster or start a new simulation.

**Comment by FiIipe** [comment]
I have the same problem. Looks like it happens from time to time.

**Comment by thisisdavidfrank** [comment]
@wobushigaoying, @FiIipe, @ebadi, @DZiYou , @ihsanyalcinkaya: Sorry about this. We've found the cause of this, and we are actively working on fixing the issue. Thank you for bringing this up.

**Comment by thisisdavidfrank** [comment]
@wobushigaoying, @FiIipe, @ebadi, @DZiYou , @ihsanyalcinkaya: The issue has been resolved and the fix has been deployed. Please let us know if you see this problem happening again. Thank you.
