### ISSUE TITLE
Cannot upload a custom plugin asset built with 2021.1

### ISSUE THREAD

**Issue by wobushigaoying** [lgsvl/simulator#1589]
Hello again...

I am using Unity 2019.4.18f1, simulator 2021.1.

When I tried to add a new plugin, the WebUI reported an error below:

![image](https://user-images.githubusercontent.com/18672103/125744825-883ab9f3-74a8-4c03-903b-5c011a70a718.png)

I added several versions of one same plugin last month with the same operation and that plugin uploaded successfully. 

What happened???

**Comment by wobushigaoying** [comment]
Resolved after I inherit the abstract class of SensorBase.

**Comment by zelenkovsky** [comment]
Great! Thanks, I'm closing this issue. Please re-open in case of other related questions.
