### ISSUE TITLE
Bridge ROS already registered, ignoring duplicate(?) plugin

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1591]
I build a customized version of Ros bridge then upload to cloud, then add it to the vehicle, run the simulator, then got this error
![Screenshot from 2021-07-15 18-07-09](https://user-images.githubusercontent.com/67900559/125778734-a702d253-b266-4779-b123-03ae661fc38a.png)

**Comment by mark-gerow-lge** [comment]
Delete your ROS bridge bundle from your build assetbundles at Assets/Bridges in the root of your project. It's attempting to load both the local and the download which is leading to this issue. We will have a change to alleviate this in the next release.
