### ISSUE TITLE
Simulation on remote computer

### ISSUE THREAD

**Issue by arudomanenko** [lgsvl/simulator#1604]
Hi! I have a two computers: powerful one and mine) I configured cluster on the first and now I can to run simulation on it. Its is great. But I want to run simulation on my computer. Where can I find the tutorial about how can I do it? It seems that I should to add cluster from first PC, but I can't do it (I just can't see option like that).
Lgsvl version: 2021.1 (on both computers)
Thanks

**Comment by arudomanenko** [comment]
The solution is VERY easy - just log in by you account on server and run lgsvl_bridge in your computer

**Comment by roshambo919** [comment]
@arudomanenko does this procedure require a GUI, or can it be accomplished with only terminal access (SSH) to a powerful machine? I'm not able to figure out how to link a remote computer through ssh.
