### ISSUE TITLE
Create a new ROS2 message type

### ISSUE THREAD

**Issue by DZiYou** [lgsvl/simulator#1607]
I notice here that [ROS2MessageTypes](https://www.svlsimulator.com/docs/system-under-test/simulator-messages/#ros2-message-types) list the message types that ros2 supports.
But I need some other message types. For example, lane line information, or other map information.
I want to ask how to add message type by myself. What are the steps? Do I need to modify [lgsvl_msgs](https://www.svlsimulator.com/docs/system-under-test/lgsvl-msgs/)

**Comment by EricBoiseLGSVL** [comment]
Hello, you will need to edit the ROS2 bridge.  See [here](https://www.svlsimulator.com/docs/plugins/bridge-plugins/).
Follow other types and write the ones you need.  Then you can make a new bridge, upload to webui and then run simulations with the new bridge.  We have a small bug so I would wait until 2021.2.1 release out very very soon.  You may need to edit the simulator core as well but it depends on the data and conversions you need.  @hadiTab knows more on this
