### ISSUE TITLE
An error occurred while retrieving the map.

### ISSUE THREAD

**Issue by yanghyunseok3** [lgsvl/simulator#1608]
Hello.
To use the maps used in previous versions of LGSVL, I installed 2020.3.3 Unity, loaded CubeTown (tutorial), built AssetBundles, uploaded to LGSVL, and ran CubeTown.
However, when executed, the floor(ground) does not appear. And, The cube and the vehicle will drop vertically at the same time. Even the traffic lights are still in the air.
And when I open the CubeTown in Unity, there are each objects, but I can't see all the sights (especially the ground) at once. I wonder if there was an error in the installation process or if I made any mistakes.
First of all, GIT LFS is installed normally, and nodejs is also installed.
The specifications of the computer are satisfying all the conditions.

Also, as an additional question, I wonder if I can use the Unity map that I made with the previous LGSVL version as the current version. From what I've read, Unity's version will be changed from 19 to 20, and SVL's version has been changed, so it is not possible. But I'm asking if there's a way.
Thank you so much for reading it.
![afterplaysimulator](https://user-images.githubusercontent.com/79189689/126314416-6824fa98-89d0-496b-bc5a-9e609ab84403.png)
![beforeplaysimulator](https://user-images.githubusercontent.com/79189689/126314421-a6d62690-db68-4060-95dd-c7d7ba04ceec.png)
![installedfile](https://user-images.githubusercontent.com/79189689/126314423-cf93f796-e3f7-41f5-b3aa-d7dd22126dbc.png)
![unity](https://user-images.githubusercontent.com/79189689/126314424-37ee0d53-0575-4dcb-8e7e-d720350eeae8.png)

**Comment by EricBoiseLGSVL** [comment]
You did not have git lfs installed when you cloned cubetown.  That is why you see simulator traffic lights but no assets in cubetown.
