### ISSUE TITLE
readme has wrong file extension

### ISSUE THREAD

**Issue by joespeed** [lgsvl/simulator#1619]
readme has extension ".txt" but is actually HTML content so should be ".html". this causes it to be opened in the wrong reader when clicked

svlsimulator 2021.2, Windows 10

**Comment by lokesku** [comment]
Hi @joespeed < if you referring to README file of lgsvl/simulator, then its a markdown. You need to use markdown editor if you want to visualize it locally. (eg: mkdocs)
https://github.com/lgsvl/simulator/blob/master/README.md
