### ISSUE TITLE
How to fully utilize gpu lidar

### ISSUE THREAD

**Issue by bigsheep2018** [lgsvl/simulator#162]
Hello lgsvl team @martins-mozeiko,

I am writing to check about how to fully utilize GPU for lidar computation (raycast i guess) or do I miss any lidar configuration setup for GPU-based lidar?
I checked the GPU situation while I am running the newly released simulator (v2019.04). It seems the GPU is not fully loaded during runtime. In fact, I found the only difference is 100mb+ more occupation of GPU memory while I turn on a 128-lidar.  
Besides, the 128-lidar is quite slow in Unity Editor game mode.
Please check the following pics for the GPU situation on my desktop while running the simulator:

1) without lidar
![no_lidar](https://user-images.githubusercontent.com/45345643/57860135-dc340d80-7826-11e9-9859-b0c7a7ca3c89.png)

2) with lidar (128 channel)
![lidar](https://user-images.githubusercontent.com/45345643/57860144-e0f8c180-7826-11e9-8c7b-559477fc4fad.png)

If possible, please give more details if there is a way figure this problem out (I am quite new to Unity3d and c#).
Thanks in advance.

**Comment by martins-mozeiko** [comment]
The lidar implementation we have is not fully optimized. While currently it works well for lower ray & measurement count, it requires too much computations on higher numbers. We plan to optimize it, but best you currently can have for real time lidar simulation is around 32 rays.

**Comment by opoppo** [comment]
Seems that in Editor game mode it will always be 3 fps with lidar on, but after complied into standalone executable fps would be improved significantly.

**Comment by martins-mozeiko** [comment]
With have greatly optimized lidar simulation performance in our new simulator [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) release. It is able to run 128 ray lidar simulation realtime.

If you have any more questions on this please open a new issue.
