### ISSUE TITLE
When export HD Map (autoware vector map),some csv is empty

### ISSUE THREAD

**Issue by windwolf9** [lgsvl/simulator#1620]
Hello @EricBoiseLGSVL,
When i export by(Unity: Simulator->Export HD Map->(select: Autoware Vector Map)),and the signaldata.csv,vetor.csv,pole.csv is
empty,but other is not。 Can you tell me the reason ,thanks!
![unity](https://user-images.githubusercontent.com/17972452/126861658-1418ea4d-2eba-4246-ba30-04b49f438bb6.png)

![csv](https://user-images.githubusercontent.com/17972452/126861676-d9e84849-53d6-4077-9dc3-2c3e09b98091.png)

**Comment by windwolf9** [comment]
I use :simulator-2020.06  unity version 2019.3.15f1

**Comment by EricBoiseLGSVL** [comment]
please see #1533

**Comment by windwolf9** [comment]
Thank you for your reply! it  means that the latest version can export data normally? But when i use simulator-2021.2，it also can not export signaldata.csv,vector.csv,pole.csv. It seems the function of  Export HD Map(Autoware Vector Map) has some problem ?

**Comment by EricBoiseLGSVL** [comment]
hmm, it should but it could be bugged.  We'll look into it.
