### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by shivpip131** [lgsvl/simulator#1624]
Hi lg team,
I am running simulator as a container by the below command

$ docker run -ti
--gpus=all
--net=host
-e DISPLAY
-e XAUTHORITY=/tmp/.Xauthority
-v ${XAUTHORITY}:/tmp/.Xauthority
-v /tmp/.X11-unix:/tmp/.X11-unix
-v ~/.config/unity3d:/root/.config/unity3d
svlsimulator[:]

Now when I am access the container by the command
Docker exec -it containerid /bin/bash
And running inside container ./simulator
Getting the below error:-
segmentation fault(core dumped)

**Comment by EricBoiseLGSVL** [comment]
Please do not create new issues when you already have one open.  See #1602
