### ISSUE TITLE
Failed to import OpenDrive map

### ISSUE THREAD

**Issue by OYhhh2** [lgsvl/simulator#1627]
hi,when i import the opendirve map in unity ,there is an error
![捕获](https://user-images.githubusercontent.com/86667465/127092626-9b53d5d1-b8a4-42c5-b4c0-5c03662e4c60.PNG)
![捕获](https://user-images.githubusercontent.com/86667465/127092775-9580c7c6-aea4-4597-b414-f203e3370afe.PNG)

**Comment by luqiang21** [comment]
It tells you what is wrong. Please delete `MapHolder` object in Unity scene and then try to import the map.

**Comment by EricBoiseLGSVL** [comment]
Hey @luqiang21! (wave)
