### ISSUE TITLE
A few days ago, I was asked about the CubeTown example.

### ISSUE THREAD

**Issue by yanghyunseok3** [lgsvl/simulator#1629]
Hello.
First of all, thank you very much for your detailed reply.
I'm writing this because I have additional questions.

1. As I remember, I installed 'gif-lfs' first, then lgsvl and unity. And to make sure that the installation was complete, I checked the picture and it was opened as follows. I think it's well-established enough. Therefore, I wonder if you have any other problems that you expect.

2. I would like to know how to load the files created in Unity19.3.3 from 20.3.3 and build them with LGSVL Simulator in detail. The files that were built from the previous version were copied to version 2020.3.3 External/environments and built. However, it is not executed for unknown reasons in LGSVL. I'd appreciate it if you could let me know the detailed process.

3. As an answer to the previous question, I remember you said that we can set up the lighting. But I can't check where the item is. I'd appreciate it if you could tell me where it is.

4. Please let me know if you have a link that describes how to create and build a map, and a link that explains how to use it in LGSVL.

Thank you so much.

![Screenshot from 2021-07-27 16-11-06](https://user-images.githubusercontent.com/79189689/127112751-40a3b2cb-d177-4ec0-85d7-a0226edd9252.png)

![Screenshot from 2021-07-27 16-04-40](https://user-images.githubusercontent.com/79189689/127112864-72d2414e-804b-4111-b97c-098e7b4748f5.png)

![Screenshot from 2021-07-27 16-08-01](https://user-images.githubusercontent.com/79189689/127112877-ac9bc9a7-0321-4d88-bae1-75306a2503a7.png)

![Screenshot from 2021-07-27 16-08-01](https://user-images.githubusercontent.com/79189689/127113131-3021f7d1-c62e-4762-b688-f37d7a6548c4.png)

**Comment by EricBoiseLGSVL** [comment]
Do not make duplicate issues.
