### ISSUE TITLE
Color camera SensorDistributionType set to Mainonly, it fails to start the simulation.

### ISSUE THREAD

**Issue by deepalcoholic** [lgsvl/simulator#1630]
when the Color camera SensorDistributionType set to Mainonly, 
it fails to start the simulation.
Would anyone can help?

**Comment by EricBoiseLGSVL** [comment]
- What version of simulator are you on?
- What OS are you on?
- What errors are you getting from player.log?

**Comment by deepalcoholic** [comment]
> * What version of simulator are you on?
> * What OS are you on?
> * What errors are you getting from player.log?

@EricBoiseLGSVL 
version:2021.21.
OS: Ubuntu18.04
log: 
[Player.log](https://github.com/lgsvl/simulator/files/6892108/Player.log)

**Comment by deepalcoholic** [comment]
> * What version of simulator are you on?
> * What OS are you on?
> * What errors are you getting from player.log?

@EricBoiseLGSVL  
version: 2021.2.1
OS: Ubuntu18.04

**Comment by EricBoiseLGSVL** [comment]
Did you find a solution to the issue?

**Comment by Just1045523143** [comment]
@EricBoiseLGSVL Do you have any ideas? i also meet this question. ubuntu20.04, lgsvl 2021.3 and 2021.2.1 both try.
