### ISSUE TITLE
Asset Bundle uploads failed

### ISSUE THREAD

**Issue by kruztw** [lgsvl/simulator#1634]
I know this issue is duplicated, but many of them are closed without solutions.

Error:
![image](https://user-images.githubusercontent.com/38398190/127251646-918825fe-7d17-4e48-8e01-986309841dee.png)

Asset Bundle is downloaded from:
https://content.lgsvlsimulator.com/maps/cubetown/

Any advice is appreciated.

**Comment by EricBoiseLGSVL** [comment]
What cloud url are you using for these 06 bundles?

**Comment by kruztw** [comment]
@EricBoiseLGSVL 
https://wise.svlsimulator.com/maps/profile/add

**Comment by kruztw** [comment]
If I could, I would like to run on localhost, like [this video](https://www.svlsimulator.com/docs/simulation-content/add-new-map/) at 6:18.
But it seems link the recent versions of SVL simulator can only link to the cloud.

**Comment by EricBoiseLGSVL** [comment]
- The 2020.06 maps are not compatible with wise.svlsimulator.com. This is a very old version of simulator.  If you want to use these assets you need to use the 06 release binary or the release tag for editor.
- This is the same step in the latest as in the video.  You need to open the LoaderScene in Unity and hit play.  It will behave just like the video and run like a binary in the Editor.
- I recommend you move to the latest release 2021.2.1 and unity 2020.3.3f1 as per our docs [here](https://www.svlsimulator.com/docs/getting-started/introduction/).

**Comment by kruztw** [comment]
@EricBoiseLGSVL 

Let me clear something.
wise.svlsimulator.com is for 2021.x (included 2021.1 and 2021.2)
The [assetBundle link](https://content.lgsvlsimulator.com/maps/cubetown/) is for 2020.06 which is not compatiable with wise.svlsimulator.com.
Is that right ?

However, I use latest-2021.1 simulator and unity 2020.3.3f1.
![image](https://user-images.githubusercontent.com/38398190/127535060-d18a81f3-695c-436f-a816-58b171496c46.png)

And build the assetBundle, then upload to the cloud.
It still complains the same error.
![image](https://user-images.githubusercontent.com/38398190/127535386-4125ce05-82ca-4bcf-9743-355acfd3652e.png)

I don't know why, maybe l should try latest-2021.2

**Comment by EricBoiseLGSVL** [comment]
- Yes, 06 is not compatible.
- You have two annotation holders in the scene.  Please delete one that is not needed and build again.

**Comment by kruztw** [comment]
@EricBoiseLGSVL 

I delete the MapShalun (1) and rebuild, but it still pops the same error when upload to cloud.
So I try to use 2021.2.1
![image](https://user-images.githubusercontent.com/38398190/127539098-3e1a5a8b-9e62-42f1-915d-c6c4d9f0ace7.png)

And add it in Unity hub with unity 2020.3.3f1
![image](https://user-images.githubusercontent.com/38398190/127539246-07e02fd9-e7fc-4838-82eb-ed927da08f06.png)

And the error occur
![image](https://user-images.githubusercontent.com/38398190/127539376-d48ad58c-5390-414f-a389-03b21b3944c7.png)

I click ignore
![image](https://user-images.githubusercontent.com/38398190/127539582-c8695ee9-0246-45df-bd0e-eae2bd84e2f7.png)

and there is no simulator in the bar.

**Comment by EricBoiseLGSVL** [comment]
this means you have errors in the scripts and Unity can't compile. Be sure all your repos that you have cloned are at the same release tag.
Also, since you have been switching unity versions, you may have corrupted Unity's Library files. (cached shaders).  If all else fails:
1) Close unity
2) Delete the Library folder in the unity root folder of the project
3) Open Unity, let it recompile the shaders.
4) Close Unity
5) Open Unity again.  You may see cyan shaders on meshes when you open scenes/prefabs. this is fine, let Unity recompile the shaders before building again.

**Comment by kruztw** [comment]
@EricBoiseLGSVL 
Thanks for your help, the unity works great !

For those who met the same problem :

the following commands are not recommend
**git clone https://github.com/lgsvl/simulator  
git checkout 2021.2.1**

I removed the older simulator, and 
**git clone https://github.com/lgsvl/simulator --branch release-2021.2 --single-branch**

the errors were all disappeared.
( I cloned cube Town in the Assets/External/Environments )
![image](https://user-images.githubusercontent.com/38398190/127593045-fecb0a21-14af-4a3b-8915-cc78b380d9f0.png)

However after building the Asset, and upload it to the cloud, the error pops up.

Firefox:
![image](https://user-images.githubusercontent.com/38398190/127593239-5ab62028-7541-4864-bf83-c587fcbd454f.png)

Chrome:
![image](https://user-images.githubusercontent.com/38398190/127593313-22af1954-8d37-4256-a471-725847170b73.png)

**Comment by kruztw** [comment]
more detail:
![image](https://user-images.githubusercontent.com/38398190/127593665-cfca9a7e-c027-4dee-b36e-914bcbf5c1bc.png)

**Comment by EricBoiseLGSVL** [comment]
Hmm, @thisisdavidfrank what could cause the Gateway timeout?  @heeen was this fixed with the websocket sharp update?

**Comment by kruztw** [comment]
@EricBoiseLGSVL
Is therer any progress ?

**Comment by heeen** [comment]
@EricBoiseLGSVL websocketsharp is only used by API mode and ROS bridge

**Comment by heeen** [comment]
It appears your asset bundle was not built correctly, as it should unzip without errors. I assume that the wise site also has issues unpacking it. can you try to rebuild it and look at the console window after the build finishes to check for errors from the build process?

**Comment by heeen** [comment]
After a successful build a popup like this should appear:
![image](https://user-images.githubusercontent.com/1699754/127841692-e9b5ee68-22cc-404a-96cb-23cf27e47aac.png)

there should not be errors from unzipping
```
$ mkdir tmp
$ cd tmp/
$ unzip ../environment_CubeTown 
Archive:  ../environment_CubeTown
 extracting: hdmaps/lanelet2/CubeTown.osm  
 extracting: hdmaps/opendrive/CubeTown.xodr  
 extracting: hdmaps/apollo50/base_map.bin  
 extracting: hdmaps/apollo30/base_map.bin  
 extracting: hdmaps/autoware/AutowareVectorMap.zip  
 extracting: images/preview-1.png    
 extracting: 5e793b6a-4f4d-4fd3-ad83-b4f89b5f614f_environment_main_linux  
 extracting: 5e793b6a-4f4d-4fd3-ad83-b4f89b5f614f_environment_textures  
 extracting: 5e793b6a-4f4d-4fd3-ad83-b4f89b5f614f_environment_main_windows  
 extracting: manifest.json           
```

@eagafonovlge can you check  if broken zip files could cause above error messages?

**Comment by kruztw** [comment]
@heeen 
Looks like it lacks of Linux Module.
![image](https://user-images.githubusercontent.com/38398190/127843232-dcd9d097-bcde-49c5-9ea2-861070ca4807.png)

**Comment by heeen** [comment]
Install it from unity hub
![image](https://user-images.githubusercontent.com/1699754/127855617-29a98683-bfc4-4232-8463-dea2f9ef6fc5.png)
![image](https://user-images.githubusercontent.com/1699754/127855662-b4a97ef9-5746-4d23-87bf-c975780707a9.png)

**Comment by kruztw** [comment]
It works ! Thanks for all your helps.
