### ISSUE TITLE
Exception: Simulator is not linked. Enter play mode to re-link.

### ISSUE THREAD

**Issue by kruztw** [lgsvl/simulator#1636]
I followed this guide, and used branch 2021.1
https://www.svlsimulator.com/docs/running-simulations/developer-mode/

But when I clicked play button, the error popped up.
![image](https://user-images.githubusercontent.com/38398190/127301684-10cab89f-c43b-4a1f-a3cb-195eed19ac9b.png)

Please help. Thanks!

**Comment by kruztw** [comment]
This is what I expected
![image](https://user-images.githubusercontent.com/38398190/127302661-b46d5a15-af9a-46d1-9516-19a5a6655df6.png)

**Comment by dogukannn** [comment]
https://github.com/lgsvl/simulator/issues/1446#issuecomment-843656375

**Comment by kruztw** [comment]
Thanks for your help, the problem is solved.

For those who met the same issue, click File -> Open Scene -> select simulator\Assets\Scenes\LoaderScene.unity -> Open, then it is good to go.
