### ISSUE TITLE
When is Map Editor feature open?

### ISSUE THREAD

**Issue by ehduk90** [lgsvl/simulator#164]
Hi, I want to see around me in LG simulator.

However, I have never used unity, and I am not confident in making maps, even with the guidance of "https://www.lgsvlsimulator.com/docs/map-annotation/#creating-a-new-map"

![image](https://user-images.githubusercontent.com/17079475/57904465-c61d6000-78ad-11e9-9566-0bc682b507ce.png)
Is the map made easier than the unity through the Map Editor of the simulator?
For example, I can satisfy even a map of low quality by adding a box to the location of the building in the vector map.
When will this feature be open?

**Comment by martins-mozeiko** [comment]
Making 3d environment will always require to use unity. It does not make much sense to create our own 3d editor if Unity is already offering all the features.

For creating simple map all you need is to place flat plane, and put some boxes/cubes on it. And car will be able to drive on such plane. Check some unity tutorials how to create objects and position objects in scene.

We will be working on feature to import existing annotations from OpenDrive or similar format. Which wil include some kind of adjustment/editing during import process. This feature will come later this year.

**Comment by ehduk90** [comment]
Thank you.
