### ISSUE TITLE
ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by kruztw** [lgsvl/simulator#1640]
I want to create a new map, so I follow this video.
https://www.svlsimulator.com/docs/simulation-content/add-new-map/

However, modern city doesn't exist, so I cloned Shalun and Jaguar2015XE to Environments and Vehicles folders respectively.
And I clicked play button, but some errors popped up.

![image](https://user-images.githubusercontent.com/38398190/127342107-662259d2-b4bf-4ffd-b4d3-a40da2e89af8.png)
![image](https://user-images.githubusercontent.com/38398190/127342142-b84f8670-2df6-4e1f-81b2-ef0ff79a83ab.png)

Any advice is appreciated.

**Comment by EricBoiseLGSVL** [comment]
You cannot run the simulator from the scene.  You need to upload the bundle to the webui to run a simulation.  You need to start the sim in editor from the LoaderScene.  We are working on a way to run from scenes in Developer Settings but it is still a wip and has issues.  We hope to release a fix soon.

**Comment by kruztw** [comment]
Thanks for your reply.
But I still confuse how the video works at 3:09, it just hit play button without using LoaderScene.

**Comment by kruztw** [comment]
@EricBoiseLGSVL

**Comment by kruztw** [comment]
Oh, I think I got something.
The video omits the upload part.
It's not kind for newbie ...

**Comment by EricBoiseLGSVL** [comment]
- Again, this is developer settings in the UI menu, hitting play is not omitting an upload but runs from the scene.  Now that the simulator requires cloud connection, the developer settings needs a refactor to work with the new backend. Please see my response in the other issue you posted.
- Sorry about the confusion, remaking videos is very time consuming and we try to update once changes are critical.
If you are just starting, I recommend you use the latest release before jumping into development mode. You should familiarize yourself with the code base and how to work with Unity.  Still, if you are already running sims in editor you are doing great so far.  Soon you will be an expert.

**Comment by kruztw** [comment]
Thank you for your warm-heart ^^
