### ISSUE TITLE
Error about build a new map

### ISSUE THREAD

**Issue by OYhhh2** [lgsvl/simulator#1642]
Hello, I got an opendrive map file and try to  add it to the simulator,so i follow this video
![捕获2](https://user-images.githubusercontent.com/86667465/127472241-a95c5403-51f5-4f27-8d52-571c6e3cea1b.PNG)
After i click the build button,it has some error,  However i don't understand what it means and how to fix it ,can you give some advice? (my english is not very good)
Unity edition:2020.3.3f1
![捕获](https://user-images.githubusercontent.com/86667465/127473505-594cabcb-36a9-42b2-950d-229e26400686.PNG)
![捕获1](https://user-images.githubusercontent.com/86667465/127473524-6a2ce0f5-9197-46b4-979b-cf17b902559b.PNG)
![捕获3](https://user-images.githubusercontent.com/86667465/127473527-bafbc378-91f1-4f43-8b33-80f69961a23d.PNG)

**Comment by EricBoiseLGSVL** [comment]
No worries and welcome to svl simulator.  This error is pointing to problems parsing the hd map. It points to the annotation object and let's you know as best it can what is the issue.
We use annotation for NPC navigation and for export to ADstack.  Sometimes the annotation is missing key data and we require users to alter the imported map to successfully run npcs and export.
The error I can see says that a stop line needs to have a public field in the component associated with a sign annotation.  You need to select that object and drag the closest or create a stop sign annotation reference.
The value cannot be null is usually an lane with no waypoints. (usually and error in the hdmap itself). We have checks for this, is this the latest simulator version? Are you on release 2021.2.1?
Hope this helps.  HDMaps and annotation is one of the most complex features of the simulator.

**Comment by OYhhh2** [comment]
thank you very much ! Yes, I‘m using the latest simulator(2021.2.1),I have just uesd the simulator for three weeks,still a lot of work to learn
