### ISSUE TITLE
Error about Start the bridge

### ISSUE THREAD

**Issue by enginlien** [lgsvl/simulator#1643]
Hello
When i was about to start the bridge,
this error message appeared.
![Screenshot from 2021-07-29 18-40-16](https://user-images.githubusercontent.com/87757542/127480712-13baa6e6-2d7c-46c0-84b0-0e7ca7379b75.png)

**Comment by shr-project** [comment]
Why are you running "dev_into.sh" when you're already inside the docker according to "danny@in_5_0_dev_docker" in PS1 ?

**Comment by enginlien** [comment]
> Hello
> When i was about to start the bridge,
> this error message appeared.
> ![Screenshot from 2021-07-29 18-40-16](https://user-images.githubusercontent.com/87757542/127480712-13baa6e6-2d7c-46c0-84b0-0e7ca7379b75.png)

**Comment by enginlien** [comment]
> Why are you running "dev_into.sh" when you're already inside the docker according to "danny@in_5_0_dev_docker" in PS1 ?

Thanks, I have revised the screenshot. 
<img width="518" alt="截圖 2021-07-30 上午12 27 12" src="https://user-images.githubusercontent.com/87757542/127531991-6122bf0d-fc66-46a2-8143-fb7d41f83ba1.png">

**Comment by lemketron** [comment]
It's not clear what "empty" channel bridge.sh is trying to create but you might see it if you make the window bigger.

Apollo 5.0 is getting pretty old at this point so unless you have a reason to be running something so old you should consider updating to Apollo 6.0 (or master) from [Apollo upstream on github](https://github.com/ApolloAuto/apollo/).

**Comment by lemketron** [comment]
That said, it appears that this may be the same issue as #1359 where you are not specifying the `Topic` name in the sensor configuration: https://github.com/lgsvl/simulator/issues/1359#issuecomment-889381618

**Comment by enginlien** [comment]
> That said, it appears that this may be the same issue as #1359 where you are not specifying the `Topic` name in the sensor configuration: [#1359 (comment)](https://github.com/lgsvl/simulator/issues/1359#issuecomment-889381618)

Hi Lemketron

Thanks for your reply.

I try to update to Apollo 6.0,
But the dream view still shows Please send car initial position and map data,
Could you please tell me why my dream always has this problem?

![image](https://user-images.githubusercontent.com/87757542/127596836-2ba51404-9aed-4896-ade7-52152acbedc3.png)
