### ISSUE TITLE
Random Traffic isn't working on any map 

### ISSUE THREAD

**Issue by oykuyener** [lgsvl/simulator#1644]
I tried to run simulation with Random Traffic but there were no NPCs nor Pedestrians. It doesn't working on any map ( self-build or SVL-made it didn' matter).  I would be so happy with your help, thanks ! 

- P.S : the version that i used was 2021.2

**Comment by EricBoiseLGSVL** [comment]
As per documentation [here](https://www.svlsimulator.com/docs/release-notes/changelog/) and [here](https://www.svlsimulator.com/docs/plugins/npc-plugins/), you need to place npcs and pedestrians into the AssetBundles folder.
