### ISSUE TITLE
SVL new Release fails to start simulation

### ISSUE THREAD

**Issue by marcusvinicius178** [lgsvl/simulator#1646]
Hi @EricBoiseLGSVL  @lemketron I am facing this error, after install the new SVL release: 2021.2.1 or also with the previous one 2021.1.1:

**lgsvl-simulator-scenarios-runner-simulator-build__2021.2.1.tar: no such file or directory**

This is weird because this file is already there:

![image](https://user-images.githubusercontent.com/43826438/127532476-57e08af2-2489-4b97-8683-70c5bb0b73fc.png)

I have already unlinked, cleaned the cache, created a new simulation from scratch as well as the clusters...

Then I tried to use the old release = 2021.1, which was working, but not anymore. I got this error:

![image](https://user-images.githubusercontent.com/43826438/127534202-15f84c1f-2caf-47f1-8f98-e06da15b3b7e.png)

Recently I have upgraded pip version because other issues regarding Apollo...

This is my output of $pip --version
![image](https://user-images.githubusercontent.com/43826438/127533938-658b187e-a57d-46b4-80ea-5642b3461d4a.png)

and the output of $python --version

![image](https://user-images.githubusercontent.com/43826438/127534006-6e60550f-937b-4b3d-8ecf-db2f5f28124a.png)

Could you please help me to figure out how to fix these issues? What are they related to

Thanks.

**Comment by EricBoiseLGSVL** [comment]
@revati-naik any idea what is happening? If there a step missing?

**Comment by marcusvinicius178** [comment]
Thanks for the attention @EricBoiseLGSVL @revati-naik I have updated the question above...I also removed the vehicles and added again. But I am afraid that be a python issue...after I update...because any simulator version is working. I don't know how to recover the functionality

**Comment by EricBoiseLGSVL** [comment]
have you updated python?

**Comment by EricBoiseLGSVL** [comment]
Also adding @eagafonovlge

**Comment by marcusvinicius178** [comment]
Yes I did. I have already purged python and restarted the installation, also from ubuntu-dekstop (I have purged and almost lost everything on my system hehehe).
But  I jsut checked the Python 3.8 is already the standard version on ubuntu 20.04. In other words this was not the issue, because it was working last week, the 2021.1 version. Then I checked now the docker images. And I got this:

![image](https://user-images.githubusercontent.com/43826438/127539648-7b7eefdd-40f4-44cc-bb02-91af12386e2a.png)

I installed Apollo 6 today with the LGSVL tutorial: https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/

git clone https://github.com/ApolloAuto/apollo

I  am not sure why it dowloaded the docker image for the 2021.1 runner-scenarios

Shouldn'it take the newer releases?

The issue is that any release is working...

**Comment by marcusvinicius178** [comment]
Hey @EricBoiseLGSVL an update....I tried again the new svl releases: 2021.2.1 and 2021.1.1 
and again the same issue of :

**lgsvl-simulator-scenarios-runner-simulator-build__2021.2.1.tar: no such file or directory**

However now the old simulator release started to work again...

I believe is something related to the docker image....would you know the how to dowload the docker images from the new releases...I mean could you share the cmd?

docker pull ....svl-2021.2.2 ???? 

Something like that could fix this issue I believe, and the scenarios could be built...I hope..

**Comment by EricBoiseLGSVL** [comment]
We will look into this, thanks for posting @marcusvinicius178

**Comment by lemketron** [comment]
> I installed Apollo 6 today with the LGSVL tutorial: https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/
> 
> git clone https://github.com/ApolloAuto/apollo
> 
> I am not sure why it dowloaded the docker image for the 2021.1 runner-scenarios

I believe you're seeing leftover docker images cached on your machine from having previously used the scenario runner in SVL Simulator. This is not related to apollo and should not affect it.

It sounds like you are changing simulator and/or apollo versions around, and it's not entirely clear which kind of simulation you are trying to run.  Which runtime template are you trying to use? Are you using `Python API` (which uses a built-in python scripts) or `API-only` mode? If you are trying to run a local python script with the simulator, then you'll need to use `API-only` mode in your simulation. This cannot be changed once you have created a simulation but you should be able to make a new `API-only` simulation. At that point the errors related to the runner container should go away.

**Comment by marcusvinicius178** [comment]
Hi @lemketron  I am using the Python API . It runs with the old release, but not with the newer...
I runned with the standard code provided there, as well as mine, but the simulator does not start the simulation.

![image](https://user-images.githubusercontent.com/43826438/127572018-6e5c10cd-cf56-4745-9f0d-80d24c8397d1.png)

I was imagining that maybe some port or something code must be changed in Python Api code spot, however the error is the same: lgsvl-simulator-scenarios-runner-simulator-build__2021.2.1.tar: no such file or directory

Maybe I must restart the computer

> > I installed Apollo 6 today with the LGSVL tutorial: https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/
> > git clone https://github.com/ApolloAuto/apollo
> > I am not sure why it dowloaded the docker image for the 2021.1 runner-scenarios
> 
> I believe you're seeing leftover docker images cached on your machine from having previously used the scenario runner in SVL Simulator. This is not related to apollo and should not affect it.

**Here is my doubt, should I remove this docker image, or clean the cache should fix?** Do you know the directory in which this cache is stored? If I clean it maybe solve the issue...I would like to try the new release, it seems LG provides new scenarios, right? This in fact is another doubt..**.I see a lot of nice new scenarios in SVL maps, but how to add them to Apollo or Autoware folders? Are these new maps' folders located in some repo?**
> 
> It sounds like you are changing simulator and/or apollo versions around, and it's not entirely clear which kind of simulation you are trying to run. Which runtime template are you trying to use? Are you using `Python API` (which uses a built-in python scripts) or `API-only` mode? If you are trying to run a local python script with the simulator, then you'll need to use `API-only` mode in your simulation. This cannot be changed once you have created a simulation but you should be able to make a new `API-only` simulation. At that point the errors related to the runner container should go away.

**Comment by marcusvinicius178** [comment]
In addition now that I tried the old release, it is not working anymore:

![image](https://user-images.githubusercontent.com/43826438/127573814-2632ac6e-3304-48b3-a89d-d817e5f6115f.png)

Last Time I needed to purge Python 3.8 totally from my computer to make it work....but I almost lost everything and needed to reinstall Ubuntu-Desktop. But the SVL worked afterwards.

I wouldn't like to redo this uninstallation...Is there other way to work around this issue?

**Comment by EricBoiseLGSVL** [comment]
It seems you don't have access to the asset.  Is this a new asset you are trying on the older version?
We released 2021.2.1 to hopefully help with these issues.  It creates new AppData folders to hold assets for each version.  So if you open a older sim and they use 2021.1.1 assets, only that folder will be used.  I think the issue running the latest is that the api ids for the assets are not updated or wrong.  Can you replace the api ids with ids from the webui or new assets you have uploaded and see if that helps?

**Comment by marcusvinicius178** [comment]
Sorry I did not understand the idea.....is there an easy way to clean all the old assets and update to have permission to use the new assets of the new release:

Take a look please hahahahahaha:

![image](https://user-images.githubusercontent.com/43826438/127588259-7ba863cb-bbb7-478e-8267-6c288df8766d.png)


It is trying to dowload the plugins, maps for minutes...but never does... this is SVL 2021.1 

The new ones do not work because of what you have said I believe. I do not know ho to update, sorry.

**Comment by EricBoiseLGSVL** [comment]
hmm, it shouldn't take long to download the keyboard sensor.  Do you have errors in the player.log? 2021.2.1 should create a new folder so there shouldn't be any issues running besides the template issue you reported.  My question is can you run an APIOnly template that runs python locally, no runner.
- check out 2021.2.1 tag make sure all other repos are on this tag
- delete all AppData folders for simulator
- run loader scene
- link cluster
- delete all assets in your library on webui.
- add map/vehicle/keyboard sensor to library that is labeled compatible with 2021.2.1
- create random sim with these assets and run
- create APIOnly simulation and edit a quick script to use map id and vehicle sensor config id,
- run to see if that works.
- If this works, then use API only not python api template

I think this is getting worse from jumping versions.  2021.1 saves to the default place and so does 2021.2 so you could be overwriting assets.

**Comment by marcusvinicius178** [comment]
> hmm, it shouldn't take long to download the keyboard sensor. Do you have errors in the player.log? 2021.2.1 should create a new folder so there shouldn't be any issues running besides the template issue you reported. My question is can you run an APIOnly template that runs python locally, no runner.

Unfortunately not. It was possible. But not anymore take a look:

![image](https://user-images.githubusercontent.com/43826438/127590634-59d047b1-d3b5-4a73-a728-a219cbc1a837.png)

> 
> * check out 2021.2.1 tag make sure all other repos are on this tag
> * delete all AppData folders for simulator
> * run loader scene
> * link cluster
> * delete all assets in your library on webui.
> * add map/vehicle/keyboard sensor to library that is labeled compatible with 2021.2.1
> * create random sim with these assets and run
> * create APIOnly simulation and edit a quick script to use map id and vehicle sensor config id,
> * run to see if that works.
> * If this works, then use API only not python api template
> 
> I think this is getting worse from jumping versions. 2021.1 saves to the default place and so does 2021.2 so you could be overwriting assets.

**Comment by marcusvinicius178** [comment]
> > hmm, it shouldn't take long to download the keyboard sensor. Do you have errors in the player.log? 2021.2.1 should create a new folder so there shouldn't be any issues running besides the template issue you reported. My question is can you run an APIOnly template that runs python locally, no runner.
> 
> Unfortunately not. It was possible. But not anymore take a look:
> 
> ![image](https://user-images.githubusercontent.com/43826438/127590634-59d047b1-d3b5-4a73-a728-a219cbc1a837.png)
> 
> > * check out 2021.2.1 tag make sure all other repos are on this tag
I am using Apollo. You mean git checkout 2021.2.1 inside this folder?

> > * delete all AppData folders for simulator
Where is this folder located? Locally?

> > * run loader scene
What is this?

> > * link cluster
I have already unliked and linked many times
> > * delete all assets in your library on webui.

I have deleted the ones I used online, and then added again...no effect
> > * add map/vehicle/keyboard sensor to library that is labeled compatible with 2021.2.1
I jsut added automatically from the webstore in SVL website, just clicking...after remove, I clicked and added again

> > * create random sim with these assets and run
Yes I did just with a keyboard, random traffic....later with PythonAPi but any type it always starts dowloading and never ends to dowload..
> > * create APIOnly simulation and edit a quick script to use map id and vehicle sensor config id,
I did it
> > * run to see if that works.
> > * If this works, then use API only not python api template
> > 
> > I think this is getting worse from jumping versions. 2021.1 saves to the default place and so does 2021.2 so you could be overwriting assets.

YEs but is not anyway to delete everything from SVL online and locally to restart from scratch? I believe the issue is online..because it is dowloading but never finishes to dowload.


Thanks for your effort @EricBoiseLGSVL I really appreciate!

**Comment by marcusvinicius178** [comment]
The error I get:

![image](https://user-images.githubusercontent.com/43826438/127591660-b774b869-9d89-49b0-9e61-ce2459952507.png)

**Comment by EricBoiseLGSVL** [comment]
```You mean git checkout 2021.2.1 inside this folder?```
simulator.  don't trouble shoot apollo at this point. we need to reduce vars ;)

```Where is this folder located? Locally?``` it is in AppData folder see [here](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html).  If you haven't been deleting this then all old assets have been loading.  Be sure to delete this for all versions.

Try the app data delete, and relink and try again.  It seems if you can't connect you have a network error locally or server issues nearby. where are you connecting from?

I would also just make a second account to test if your backend data is messed up.  I'll ping @thisisdavidfrank and @eagafonovlge  to take a look at that

**Comment by marcusvinicius178** [comment]
> `You mean git checkout 2021.2.1 inside this folder?`
> simulator. don't trouble shoot apollo at this point. we need to reduce vars ;)
Sorry in each folder mus I git checkout? I have already removed the folders inside the ~/.config/unity3D with rm -rf command line take a look:

![mess](https://user-images.githubusercontent.com/43826438/127593701-2b1d411b-7755-4640-a0ac-e5a3d65d23f5.png)

> `Where is this folder located? Locally?` it is in AppData folder see [here](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html). If you haven't been deleting this then all old assets have been loading. Be sure to delete this for all versions.
> 
> Try the app data delete, and relink and try again. It seems if you can't connect you have a network error locally or server issues nearby. where are you connecting from?
I am from south of Brazil
> I would also just make a second account to test if your backend data is messed up. I'll ping @thisisdavidfrank and @eagafonovlge to take a look at that
> 
> No worries, I apologize for the difficulties.
Thanks very much. This time it is really being hard to solve...I have removed everythin possible as I know , dowloaded the svl simulator again...but nothing helps.

**Comment by marcusvinicius178** [comment]
This is my Player log from the folder ~/.config/unity3d/LGEletronics/SVLSimulator

```
Mono path[0] = '/home/autoware-auto-ros1/Área de Trabalho/svlsimulator-linux64-2021.2.1/simulator_Data/Managed'
Mono config path = '/home/autoware-auto-ros1/Área de Trabalho/svlsimulator-linux64-2021.2.1/simulator_Data/MonoBleedingEdge/etc'
Preloaded 'UnityFbxSdkNative.so'
Preloaded 'liblaszip.so'
Preloaded 'libpng.so'
Preloaded 'libsqlite3.so'
Preloaded 'libturbojpeg.so'
Display 0 '0': 1920x1080 (primary device).
Display 1 'SyncMaster 19"': 1360x768 (secondary device).
Loading player data from /home/autoware-auto-ros1/Área de Trabalho/svlsimulator-linux64-2021.2.1/simulator_Data/data.unity3d
Unable to load player prefs
Desktop is 1920 x 1080 @ 60 Hz
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
Vulkan detection: 2
Initialize engine version: 2020.3.3f1 (76626098c1c4)
[Subsystems] Discovering subsystems at path /home/autoware-auto-ros1/Área de Trabalho/svlsimulator-linux64-2021.2.1/simulator_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
[Vulkan init] extensions: count=17
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_display_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=1
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_surface_protected_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
[Vulkan init] SelectPhysicalDevice requestedDeviceIndex=-1 xrDevice=(nil)
[Vulkan init] Physical Device 0x1470540 [0]: "NVIDIA GeForce GTX 1050 Ti" deviceType=2 vendorID=10de deviceID=1c8c
[Vulkan init] Selected physical device 0x1470540
[Vulkan init] Graphics queue count=1
[Vulkan init] extensions: count=118
[Vulkan init] extensions: name=VK_KHR_16bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_8bit_storage, enabled=0
[Vulkan init] extensions: name=VK_KHR_bind_memory2, enabled=0
[Vulkan init] extensions: name=VK_KHR_buffer_device_address, enabled=0
[Vulkan init] extensions: name=VK_KHR_copy_commands2, enabled=0
[Vulkan init] extensions: name=VK_KHR_create_renderpass2, enabled=1
[Vulkan init] extensions: name=VK_KHR_dedicated_allocation, enabled=1
[Vulkan init] extensions: name=VK_KHR_depth_stencil_resolve, enabled=1
[Vulkan init] extensions: name=VK_KHR_descriptor_update_template, enabled=1
[Vulkan init] extensions: name=VK_KHR_device_group, enabled=0
[Vulkan init] extensions: name=VK_KHR_draw_indirect_count, enabled=0
[Vulkan init] extensions: name=VK_KHR_driver_properties, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_fence_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_fd, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_memory_requirements2, enabled=1
[Vulkan init] extensions: name=VK_KHR_image_format_list, enabled=1
[Vulkan init] extensions: name=VK_KHR_imageless_framebuffer, enabled=0
[Vulkan init] extensions: name=VK_KHR_maintenance1, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance2, enabled=1
[Vulkan init] extensions: name=VK_KHR_maintenance3, enabled=0
[Vulkan init] extensions: name=VK_KHR_multiview, enabled=1
[Vulkan init] extensions: name=VK_KHR_pipeline_executable_properties, enabled=0
[Vulkan init] extensions: name=VK_KHR_push_descriptor, enabled=0
[Vulkan init] extensions: name=VK_KHR_relaxed_block_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_sampler_mirror_clamp_to_edge, enabled=1
[Vulkan init] extensions: name=VK_KHR_sampler_ycbcr_conversion, enabled=0
[Vulkan init] extensions: name=VK_KHR_separate_depth_stencil_layouts, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_atomic_int64, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_clock, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_draw_parameters, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float16_int8, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_float_controls, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_non_semantic_info, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_subgroup_extended_types, enabled=0
[Vulkan init] extensions: name=VK_KHR_shader_terminate_invocation, enabled=0
[Vulkan init] extensions: name=VK_KHR_spirv_1_4, enabled=0
[Vulkan init] extensions: name=VK_KHR_storage_buffer_storage_class, enabled=0
[Vulkan init] extensions: name=VK_KHR_swapchain, enabled=1
[Vulkan init] extensions: name=VK_KHR_swapchain_mutable_format, enabled=0
[Vulkan init] extensions: name=VK_KHR_synchronization2, enabled=0
[Vulkan init] extensions: name=VK_KHR_timeline_semaphore, enabled=0
[Vulkan init] extensions: name=VK_KHR_uniform_buffer_standard_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_variable_pointers, enabled=0
[Vulkan init] extensions: name=VK_KHR_vulkan_memory_model, enabled=0
[Vulkan init] extensions: name=VK_KHR_workgroup_memory_explicit_layout, enabled=0
[Vulkan init] extensions: name=VK_KHR_zero_initialize_workgroup_memory, enabled=0
[Vulkan init] extensions: name=VK_EXT_4444_formats, enabled=0
[Vulkan init] extensions: name=VK_EXT_blend_operation_advanced, enabled=0
[Vulkan init] extensions: name=VK_EXT_buffer_device_address, enabled=0
[Vulkan init] extensions: name=VK_EXT_calibrated_timestamps, enabled=0
[Vulkan init] extensions: name=VK_EXT_color_write_enable, enabled=0
[Vulkan init] extensions: name=VK_EXT_conditional_rendering, enabled=0
[Vulkan init] extensions: name=VK_EXT_conservative_rasterization, enabled=1
[Vulkan init] extensions: name=VK_EXT_custom_border_color, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_clip_enable, enabled=0
[Vulkan init] extensions: name=VK_EXT_depth_range_unrestricted, enabled=0
[Vulkan init] extensions: name=VK_EXT_descriptor_indexing, enabled=0
[Vulkan init] extensions: name=VK_EXT_discard_rectangles, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_extended_dynamic_state, enabled=0
[Vulkan init] extensions: name=VK_EXT_extended_dynamic_state2, enabled=0
[Vulkan init] extensions: name=VK_EXT_external_memory_host, enabled=0
[Vulkan init] extensions: name=VK_EXT_fragment_shader_interlock, enabled=0
[Vulkan init] extensions: name=VK_EXT_global_priority, enabled=0
[Vulkan init] extensions: name=VK_EXT_global_priority_query, enabled=0
[Vulkan init] extensions: name=VK_EXT_host_query_reset, enabled=0
[Vulkan init] extensions: name=VK_EXT_image_robustness, enabled=0
[Vulkan init] extensions: name=VK_EXT_index_type_uint8, enabled=0
[Vulkan init] extensions: name=VK_EXT_inline_uniform_block, enabled=0
[Vulkan init] extensions: name=VK_EXT_line_rasterization, enabled=0
[Vulkan init] extensions: name=VK_EXT_memory_budget, enabled=0
[Vulkan init] extensions: name=VK_EXT_pci_bus_info, enabled=0
[Vulkan init] extensions: name=VK_EXT_pipeline_creation_cache_control, enabled=0
[Vulkan init] extensions: name=VK_EXT_pipeline_creation_feedback, enabled=0
[Vulkan init] extensions: name=VK_EXT_post_depth_coverage, enabled=0
[Vulkan init] extensions: name=VK_EXT_private_data, enabled=0
[Vulkan init] extensions: name=VK_EXT_provoking_vertex, enabled=0
[Vulkan init] extensions: name=VK_EXT_queue_family_foreign, enabled=0
[Vulkan init] extensions: name=VK_EXT_robustness2, enabled=0
```

And here you can check there is any sensor, environment, plugin availbale...the folder are empty

![image](https://user-images.githubusercontent.com/43826438/127594336-dd8404a6-ed04-4056-8686-7594c35d6e0c.png)


At last but not the less important...After remove the python 3.8 I had HUGE problems, to run the simulator and docker again....
I needed to reinstall my Nvidia driver, the Cuda Toolkit, restart docker, removed the mesa-vulkan-drivers, reinstalled the libvulkan1 and vulkan-tools, etc..Then the SVL start at least to open without close fast....and the apollo was built on docker...
**BUT I have done some other MISTAKE in the process...I remember to fix other issue I have removed a PPA repo to have dowload access. But I do not remember which of them.. 
May this be the issue, what do you think?**

I just think because I have read this was the solution found by this guy: https://github.com/lgsvl/simulator/issues/753
But he did not said which PPA command is...

I tried the ones below found here: https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update

I have also removed the docker image:

`docker image rm lgsvl/simulator-scenarios-runner:simulator-build__2021.1 
`

But still not success

I still have the same error...a loop in dowloading the assets...

**Comment by EricBoiseLGSVL** [comment]
Sorry I am not familiar with PPA.  @lemketron ? I do know that sudo causes issues and shouldn't be used.  I think there are a few issues about it. Sounds like something is preventing connection and download.

**Comment by lemketron** [comment]
PPAs are often used for installing pre-release software and that isn't the case for SVL Simulator.

I don't believe SVL Simulator requires (or relies on) any PPAs at this point.

Just follow the [installation instructions](https://www.svlsimulator.com/docs/installation-guide/installing-simulator/) including installing Nvidia drivers and Docker (neither of which mention any PPA repositories).

**Comment by marcusvinicius178** [comment]
I understand I have followed all these installation instructions. So, what might be the problem of assets download? I have already cleaned all the system and restarted. I cannot imagine other factor than Network. But I am just a student... don't know what is going on

**Comment by marcusvinicius178** [comment]
But now sometimes my simulation stops apparently without reasons:

And say 

![image](https://user-images.githubusercontent.com/43826438/127666821-721fffbd-7920-49c3-b0ba-1c07a47e377c.png)

Also this image when turns offline

![image](https://user-images.githubusercontent.com/43826438/127666558-4e69582d-bb78-46d7-8be9-5949c239d935.png)

**Comment by marcusvinicius178** [comment]
When the error above happens. I need to stop the Dreamview:

`./scripts/bootstrap_lgsvl.sh stop`

and stop the bridge

close the simulator, open again and restart everything...
In addition the 2021.2.1 SVL release put the car in the wrong position, when I trigger the localization module:

![image](https://user-images.githubusercontent.com/43826438/127667438-7c432785-2663-4fa0-ba58-111e20573dac.png)

In previous versions, the car always was put correctly in Dreamview when I activated the localization module...

Do you imagine what is generating this localization error?

**Comment by marcusvinicius178** [comment]
Hi @EricBoiseLGSVL sorry to reopen this issue. It is just because I am trying to standardize the simulator release I am using for all the machines I use...

And in my notebook I have redone the steps we discussed above:

1 - remove the docker image **scenarios-runner-2021.1** and the other ones
2- removed the LG folders inside **.config/unity3D**
3- Unlink cluster, clear cache, delete and dowload again all the assets (maps and vehicles)

Then I have removed and dowloaded again the PythonAPI folder and installed it. Because it seems the scenarios runner are in someway linked to it. Then I thought when I runned the installation command again inside this folder I would have the scenarios runner from the new SVL release. But I got these messages:

![image](https://user-images.githubusercontent.com/43826438/132259876-c7bf4efa-619a-4dbc-943f-821ebb09b842.png)

And now if I try any version of SVL I get the same error:

If I try with the new release (2021.2.1) I wish I get:

![image](https://user-images.githubusercontent.com/43826438/132260011-f58eee4e-7e09-4bcb-9962-90f5c321a1c4.png)


And If I try with the old one I was using (2021.1), the same error:

![image](https://user-images.githubusercontent.com/43826438/132259954-de020eb4-a948-4f8b-b395-fa707b87308a.png)

I cannot run any simulator release. Do you know what I could try to start a "fresh system" regarding simulator/linux without need to reinstall ubuntu? It seems some old " PythonAPI contents" related to the old SVL release remained on linux folders....and I am not sure if I can delete these folders the terminal displayed. Some idea?

Thanks

**Comment by marcusvinicius178** [comment]
As @lemketron said:
I installed Apollo 6 today with the LGSVL tutorial: https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/

git clone https://github.com/ApolloAuto/apollo

I am not sure why it dowloaded the docker image for the 2021.1 runner-scenarios

I believe you're seeing leftover docker images cached on your machine from having previously used the scenario runner in SVL Simulator. This is not related to apollo and should not affect it.

It sounds like you are changing simulator and/or apollo versions around, and it's not entirely clear which kind of simulation you are trying to run. Which runtime template are you trying to use? Are you using Python API (which uses a built-in python scripts) or API-only mode? If you are trying to run a local python script with the simulator, then you'll need to use API-only mode in your simulation. This cannot be changed once you have created a simulation but you should be able to make a new API-only simulation. At that point the errors related to the runner container should go away.

But If I wish to use the Python-API template how can I scape this error and run the simulation?

**Comment by marcusvinicius178** [comment]
hI @EricBoiseLGSVL I have an URGENT request please:

![image](https://user-images.githubusercontent.com/43826438/135685721-70adefde-baa9-4b15-b10a-26aed9c609bd.png)


I have created a new e-mail account: 
marcusvinilgsvl@gmail.com

To manage my final master thesis simulations...
And my limit to create clusters was reached could you please enable it as soon as possible? 

Other issue faced again is:

I need to use the LGSVL 2021.1 release instead the 2021.2.1 release, because I checked on my Notebook machine that the newer release (2021.2.1) fails to localizate the car in SanFrancisco map, take a look:

![Captura de tela de 2021-10-01 16-57-47](https://user-images.githubusercontent.com/43826438/135685918-2691a4ee-6e5c-484e-a971-811ce875afd1.png)

While the old release (2021.1) does not:

![svl_last_release](https://user-images.githubusercontent.com/43826438/135685988-355ecb10-be1f-4876-8b20-e4bec9038d45.png)


However I needed to run the old release in those rented cloud machine I told you, because on my notebook the planning module does not work (due low CPU capability).

And the **issue ** is that when I tried to install the LGSVL old release and run the simulations I am facing all those problems we discussed above....I have done everything you said:

- Removed All Assets
- Removed the LGEletronics folder inside .config/unity3D folder
- Cleared the cache
- -Unlinked and later linked the simulator with web Browser
- Created a new cluster
- Pruned dangle images

However the simulator goes offline when I run the simulations with PythonAPi Template. I cannot use the PythonOnly template in this virtual machine I  have rented, because I had lot of issues to install the PythonApi due sudo permissions not available or/and others....

Could you help me please?

**Comment by EricBoiseLGSVL** [comment]
I contacted backend to increase your clusters.  We are trying to push out the 2021.3 release right now which will fix all these issues.  Hang in there, we got you.

**Comment by marcusvinicius178** [comment]
Hi Thanks a Lot!!! I cehcked the website was in maintainance.

I hope this new release be amazing as everything LG does!!! 

Of so I will be waiting...

I have done nice simulations with Autoware.AI and Apollo....I could use almost all the planners from the 2ADS....and I am doing nice plots to compare the planners and the stacks regarding the modules (localization, perception,planning,control,etc)

Unfortunately just AutowareAuto was not used, because of those bridge issue. **Would you know if AutowareAuto is back to work with SVL???** I would like to use their AVP planner with SVL....
****

@EricBoiseLGSVL  would you know how could I produce a **Point Cloud Video** from these simulations, as the **bird-view** nice feature that the video-recording sensor plugin does?

Is this just for "Premium users" Would you suggest me something to have PCD video while the car travels?

Thanks in advance

**Comment by lemketron** [comment]
> Unfortunately just AutowareAuto was not used, because of those bridge issue. **Would you know if AutowareAuto is back to work with SVL???** I would like to use their AVP planner with SVL....

Please start a new github issue for this, but I am definitely interested in hearing more about your bridge issue with Autoware.Auto. We are actively testing Autoware.Auto with SVL Simulator and expect that 2021.3 should resolve many outstanding issues for Autoware.Auto users -- though I was not aware of any bridge issues.

Please be sure that you are using ROS2 with Autoware.Auto and not ROS (1) as with Autoware.AI. And again, if this continues to be a problem for you with 2021.3 (which you should be able to try next week) then please file a new github issue with the details (and logs). Thanks!

**Comment by marcusvinicius178** [comment]
Hi Steve I am referring about these issues https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/issues/977

I was working normally with AUTOWARE.Auto and have done simulations in Autonomous Stuff scenario with the AVP (Lanelet2) path planner. However LG discontinued the 2020.06 simulator and then the new releases were not working with Autoware.Auto as it is related in the link above....

I am happy that the new release will solve all the issues. I am just unhappy that my machine now cannot run the SVL 2021.2.1 or 2021.1 after I use them one after anothet with PythonApi. I don't understand how to fix this and be able to use more than 1 SVL version without bugs...
I am not sure now what should I do, if erase all Ubuntu and start from a clean state or what? Because deleting the LGELETRONICS folder inside the .config/ folder was done, the cache was erased, the plugins, vehicles and maps on web app was one by one all removed by me, I have unlinked the Cluster and then created new one....but anything I do is able to enable the PythonApi template back to work....☹️
Would you have some suggestion please? I would not like to erase Ubuntu from scratch

**Comment by lemketron** [comment]
You should be able to try Autoware.Auto with 2021.3 very soon (within the next few days I hope)...  :-)

I'm sorry for the troubles you had trying to use Autoware.Auto with 2021.1 and with PythonAPI with other 2021 versions. Please try all of that again with 2021.3 and let us know if you discover any new or remaining issues.  Thanks!
