### ISSUE TITLE
Default constructor not found!

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#1649]
I run the build for a Ros bridge, got no error, then I upload the bridge to webUI, but it didn't work as expected. I think there's something wrong with the build process. And there is a suspicious warning (in the below image). Is it something I should worry about?
I'm using 2021.1.1 version
![2021-07-31_223939](https://user-images.githubusercontent.com/67900559/127745223-fb2548cd-ed70-4a62-9353-7bddccf7df69.png)

**Comment by heeen** [comment]
Are you trying to build ROS Bridge as a plugin/assetbundle? I think your ROS bridge type is conflicting with the one that is part of the simulator codebase in 2021.1.1

**Comment by heeen** [comment]
FYI ROS/ROS2/CyberRT Bridges as plugins is an upcoming feature (https://github.com/lgsvl/simulator/commit/d090e920425fc14cd00763da6f479b1db39b9062)

**Comment by EricBoiseLGSVL** [comment]
Yes, @heeen is right, custom bridges need 2021.2.1 release tag.

**Comment by duongtran11** [comment]
> Are you trying to build ROS Bridge as a plugin/assetbundle? I think your ROS bridge type is conflicting with the one that is part of the simulator codebase in 2021.1.1

You're right. I had to build the whole simulator to make it work. but then I had to build a Ros bridge myself cause pre-build Ros bridge on the webUI doesn't support dev version of simulator.
Can you change that?

**Comment by EricBoiseLGSVL** [comment]
We have support for development in 2021.2.1 version of simulator.
