### ISSUE TITLE
Simulator and Rviz2 cannot run alongside on new Release?

### ISSUE THREAD

**Issue by marcusvinicius178** [lgsvl/simulator#1662]
Hi @EricBoiseLGSVL could you please assist me on this issue?

I am running the SVL 2021.1.1 release with AutowareAuto bridge on BorregasAve map. The bridge connection is working and ROS2 is subscribing the data from the simulator topics. However when I try to open rviz2 in other terminal, it does not get opened and raises a dbus_connection issue. It says that "the address is already in use" take a look:

![image](https://user-images.githubusercontent.com/43826438/128267533-9eca8a2d-275e-4939-acf2-ef750f1c03d6.png)

This was a launch file tried...However If I try to open rviz2:

![image](https://user-images.githubusercontent.com/43826438/128267652-566d6f16-07ae-4f66-84c2-acf98f162e57.png)

A similar error

**Comment by EricBoiseLGSVL** [comment]
I would first check to see if any other applications are using your ports but I'm not sure past that. @hadiTab or @cyberphysicalrobotics ?

**Comment by marcusvinicius178** [comment]
Sorry I have already solved here: https://gitlab.com/ApexAI/ade-lgsvl/-/issues/8
