### ISSUE TITLE
how to combine 5 point cloud files (map.pcd) and HD map files (base_map.bin) with different map origin.

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1667]
I have 5 .pcd files of 5 different roads that are adjacent to each other. So how can I create on HD map (base_map.bin) using these 5 files , all having different map origin. 

What I tried?
1. I import 1 .pcd file then try to import another .pcd file in the same scene or project, but it replace the old .pcd file instead of having two files. Even If i import two files then how to adjust the map origin?
2. I import 5 .pcd files all together, but it overlaps with each other and I cannot see the actual road, also I cannot move these files.
3. I also tried to import two base_map.bin files in one scene, but it give an error. I thought I can create 5 different HD maps (base_map.bin) and then i can combine these files but it is not possible.

So how to deal with this issue?

**Comment by EricBoiseLGSVL** [comment]
please do not duplicate issues.
