### ISSUE TITLE
Api code hangs if run commands after sim.run(0)

### ISSUE THREAD

**Issue by oykuyener** [lgsvl/simulator#1674]
Hi,

I want to create a GUI to control NPC's and controllable objects using python api. I've started to do that however if I send a command (e.g. traffic light policy change) that runs after sim.run(0) in another thread, code hangs.

code algorithm is like below:

Load map and agent
Start a thread which is responsible for traffic light policy changes. And wait for a policy input from user.
run simulator with sim.run(0) in main thread.
After all these steps, user selects a policy and thread continues with:
signal.control(control_policy)
and never returns.

Is It wait for a response from simulator (however response is never send because simulator is running) or what?

Thanks.

**Comment by lemketron** [comment]
Please note that sim.run() is a blocking call and does not return until a timeout or callback occurs, and you may not make other Python API calls into the Simulator from another thread. Between calls to sim.run() the simulator is not running.

Please refer to #1323 for more information on passing a timeout to sim.run() (with an example) to run a [stepped simulation](https://github.com/lgsvl/PythonAPI/blob/master/quickstart/33-ego-drive-stepped.py).

A stepped simulation will run close to real time but it depends on how much python code you execute while the simulator is paused between each step. But you will be able to change your signal policy when needed. 

I would recommend calling `sim.run(0.1)` and when that call returns, make your call to `signal.control` (if needed), and then loop to call `sim.run(0.1)` again.

From #1323:

> Check out quickstart script 33 for an example of how to do stepped simulation:
> https://github.com/lgsvl/PythonAPI/blob/master/quickstart/33-ego-drive-stepped.py
> 
> If using Apollo then you'll want to use Apollo 6.0 or master and include the clock sensor so Apollo runs with simulation clock as noted in the above script.
> https://www.svlsimulator.com/docs/simulation-content/sensors-list/#clock
