### ISSUE TITLE
map is worng in apollo's dreamview 

### ISSUE THREAD

**Issue by OYhhh2** [lgsvl/simulator#1676]
i follow the instructions to add other maps in svl to the apollo (my verision is apollo 6.0)
![2021-08-10 16-27-34屏幕截图](https://user-images.githubusercontent.com/86667465/128839606-d7c4b7d0-ae5c-445a-ac6d-b25d8fbd767b.png)

However,the map seems wrong ,the car is not in the right possition in dreamview , at the same time the simulator has no problem, It seems that the map have a problem in dreamview ? i don't know what' s the problem. the map is SanFrancisco,and Shalun also havs this problem
![2021-08-10 16-14-22屏幕截图](https://user-images.githubusercontent.com/86667465/128839605-26bb8fcd-5c37-4159-a46b-d0bab4789ffd.png)

Can you help me ?Thanks!

**Comment by jasonliu00** [comment]
@OYhhh2  I have the same problem with you

**Comment by EricBoiseLGSVL** [comment]
We are looking into this, thanks for posting

**Comment by EricBoiseLGSVL** [comment]
This has been fixed and will be in our next release.  Thanks for posting
