### ISSUE TITLE
BoundingBox2D which point does x,y refer to

### ISSUE THREAD

**Issue by sisaha9** [lgsvl/simulator#1678]
Referring to this msg: https://github.com/lgsvl/lgsvl_msgs/blob/master/msg/BoundingBox2D.msg

Hi all! I had some confusion regarding the BoundingBox2D msg. Is the x and y in the msg the center of the bounding box? Or is it one of the 4 corners. If it's the latter which one of the 4 corners is it?

**Comment by rongguodong** [comment]
The comments in the msg answered your question. :)

**Comment by sisaha9** [comment]
I am not sure how I omitted center when I was reading it... Thanks for catching my error!

**Comment by EricBoiseLGSVL** [comment]
Hey @rongguodong thanks for the help :)
