### ISSUE TITLE
Is it possible to save camera images when simulator is run()?

### ISSUE THREAD

**Issue by Tumiz** [lgsvl/simulator#168]

**Comment by martins-mozeiko** [comment]
If you need continuous stream of large data like camera image or lidar point cloud it is better to use ROS or Cyber messages to record them to rosbag. Python API is not designed to process large data. Currently it is made for controlling environment and other vehicles in scene, or something like collecting training data.

**Comment by Tumiz** [comment]
Continuity is not necessary but better for speed. We need to collect camera images and ground truth 2D/3D frame by frame for training. But ROS messages timestamp varies with topic and type.
