### ISSUE TITLE
Ego Vehicle Build and Upload

### ISSUE THREAD

**Issue by ertauren** [lgsvl/simulator#1683]
Hi, I would like to inquire about my upload problem.
I build and used my ego vehicle asset with version 2021.1. I decided to upgrade it to 2021.2 and built with it. It didn't give any errors at unity. But when i tried to upload it to website it gave "assetUploader.errors.(undefined)" once upload finished and failed.

Edit: I am able to unzip it. I tried both updating the old vehicle and adding new vehicle on website
Edit2: I will do some editing and show it to client as if it is another existing vehicle asset which i already downloaded. I will update here if it works.
Update: As workaround, I was able to use my car by editing its id to one of existing cars.

Did anyone else had this problem? Anyone have a suggestion i can try? Is there limit of car assets my account can have?

Edit3: fixed mistype on the post

**Comment by EricBoiseLGSVL** [comment]
Yes, we have this issue and should have fixes releasing soon. Sorry about the confusion.  When in doubt, delete the old vehicle and upload.  Then if prompted, make a new vehicle.

**Comment by EricBoiseLGSVL** [comment]
Please see #1706

the current maximum for the GLB size (inside the asset bundle) is set to 50 MB. But we are increasing it to 200 MB in the upcoming release (that is going out this month end).
The appropriate error message will also be available in the upcoming release.
