### ISSUE TITLE
Executing Python scripts not working

### ISSUE THREAD

**Issue by marcusvinicius178** [lgsvl/simulator#1686]
Hi I am following the tutorial: https://www.svlsimulator.com/docs/python-api/python-api/

However it is not working. The system is unable to localize the module environs:

![image](https://user-images.githubusercontent.com/43826438/129485084-f9944535-b3d7-48f8-abe4-13f7043969a7.png)

On my machine I have installed months ago and it is ok...but in the rented cloud machine that I use, which is more powerful, it is not working...

@EricBoiseLGSVL  dou you have some idea how can I fix this? I have already tried use a virtual environment but it is not working...

I get these errors when trying to install 

![image](https://user-images.githubusercontent.com/43826438/129485634-97e77dea-2599-4b5c-9170-047e7bdd13bb.png)

HERE A LIST OF THE COMPLETE TUTORIAL STEPS ATTEMPT:

![errors](https://user-images.githubusercontent.com/43826438/129486022-551e1003-5be6-4140-b3cd-2edca4fa3fce.png)

**Comment by heeen** [comment]
you are using sudo to invoke pip3, Try using pip3 without sudo.

**Comment by roshambo919** [comment]
@marcusvinicius178 do pip install using the instructions here
https://github.com/lgsvl/PythonAPI

from requirements.txt and not setup.py.

```
python3 -m pip install -r requirements.txt --user .

# install in development mode
python3 -m pip install -r requirements.txt --user -e .
```
