### ISSUE TITLE
Bag report in Shalun Map

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#169]
I found that newest release version of LGSVL Simulator,
When I select Shulan map, robots are fall into the ground.
https://youtu.be/kyeVvlE3o0Y

**Comment by martins-mozeiko** [comment]
Thanks for reporting. This will be fixed in next week.

**Comment by martins-mozeiko** [comment]
This is now fixed in latest master & 2019.05-rc1 release.
