### ISSUE TITLE
LGSVL [SEGMENTAION FAULT] quits immediately after starting

### ISSUE THREAD

**Issue by RedBlack888** [lgsvl/simulator#1698]
I tried to run it by following the steps [here](https://www.svlsimulator.com/docs/getting-started/getting-started/) but it didn't work.I chose the nvidia driver.I install ` sudo apt install libvulkan1`, and remove `sudo apt remove mesa-vulkan-drivers`. 

My sever is `Ubuntu 20.04.2 LTS` , `nvidia-smi` as shown:
![image](https://user-images.githubusercontent.com/86508671/130003539-98c46f67-aa99-453f-9a69-3b648664a5d8.png)

Review the Player.log file, as follow
![image](https://user-images.githubusercontent.com/86508671/130003629-82762780-1e02-4507-92ee-a2ca7fb04726.png)

The log file shows the issue is a bit different from issue #1431 

Could you help to find the bug?

Best.

**Comment by RedBlack888** [comment]
As shown in the player.log. I do not find path `/tmp/LGElectronics/SVLSimulator/vulkan_pso_cache.bin`.

**Comment by RedBlack888** [comment]
#1479 show the same issue while launching it through remote server. 

After testing locally, the same issue.

**Comment by EricBoiseLGSVL** [comment]
Are you running the XRDP service?  If so, it seems that this is a blocker.

**Comment by umdreamer** [comment]
> Are you running the XRDP service? If so, it seems that this is a blocker.

I have the same issue. But it is OK in another machine.  I don't know why. The two machines are with the same configuration.

**Comment by RedBlack888** [comment]
> Usually a seg fault in unity is from running out of memory. I am guessing the gpu is not loading correctly or driver has an issue. Sorry, we can't help more on your hardware. Maybe @heeen might have some debug tips?

Well, I have solve this issue by intall the right vulkan graph driver for ubuntu 20.04. 
Now, I can start the serve via VNC. 

Thanks.
Best.

**Comment by EricBoiseLGSVL** [comment]
Excellent and thanks for posting a solution for others.  Cheers.
