### ISSUE TITLE
How to input parameter values correctly

### ISSUE THREAD

**Issue by selfsimulator** [lgsvl/simulator#1700]
I want to know how to calculate the standard camera parameters and offset for center of projection (ξ, `Xi` in camera parameters) ? Because I don't know what the appropriate size of these parameters is ? Are these parameter values based on real fisheye camera data? If not, the values of these parameters can be entered by the user at will and there is no real data support, then the fisheye camera is meaningless!
![image](https://user-images.githubusercontent.com/85266706/129500521-f09876c7-5174-4a8b-b482-dad2e43e89fd.png)
![image](https://user-images.githubusercontent.com/85266706/130025196-d4f16664-8de2-40e0-88b8-e11139219af0.png)

And I want to know what this part of the code means? Is it part of a plumb bob model? I can't relate it to a plumb bob model.
![image](https://user-images.githubusercontent.com/85266706/129501964-5ff51c92-ae9a-4db4-b685-18cd0053ef1f.png)
![image](https://user-images.githubusercontent.com/85266706/129502113-65abfe2c-1d53-4a81-96df-f1e9c443e9ec.png)

**Comment by EricBoiseLGSVL** [comment]
Please do not make duplicate issues.
