### ISSUE TITLE
How to get ego vehicle position in x, y, z coordinates?

### ISSUE THREAD

**Issue by dheerajakula** [lgsvl/simulator#1702]
Hi which sensor should I use to get the ego vehicle position in x,y,z co-ordinates. I used the gps odometer sensor as mentioned in [https://github.com/lgsvl/simulator/issues/998](https://github.com/lgsvl/simulator/issues/998) but it gives me latitude and longitude globally or relative to origin. But I need the x,y,z unity coordinates like what 3d ground truth sensor gives. One way to go about it is we can spawn 2 ego vehicles and use one dummy ego vehicles 3d ground truth sensor to capture the co-ordinates of the other ego vehicle, but I was hoping some better alternative exists.

**Comment by EricBoiseLGSVL** [comment]
We recommend opening the Unity Editor and running the simulator.  Then, you can create an empty object and see the transform data. We have plans to create a transform tool for the api.  You can also create a sensor that lists all transform data to debug.logs.

**Comment by dheerajakula** [comment]
As you said I need to create a new sensor, I found the code for 3d ground truth sensor at [https://github.com/lgsvl/PerceptionSensor3D](https://github.com/lgsvl/PerceptionSensor3D) I think I could tinker this code to accommodate my scenario. 
@EricBoiseLGSVL is there any other other sensor that lists all the transform data to debug.log.

**Comment by EricBoiseLGSVL** [comment]
None debug but it would be very easy to modify to get what you want.

**Comment by dheerajakula** [comment]
Thanks for the info
