### ISSUE TITLE
Assembly loading catch in editor

### ISSUE THREAD

**Issue by alperenbayraktar** [lgsvl/simulator#1708]
I don't know if it's just me but on line 476 of Config.cs, the assembly couldn't be loaded so it would go to the catch statement and never load the NPCs, its the same for pedestrians too just below. So, I just commented it out.
![image](https://user-images.githubusercontent.com/35660502/130576380-bf5f6d29-c6af-4789-9a9b-419d364b444a.png)

**Comment by EricBoiseLGSVL** [comment]
Yes, this is fixed in 2021.3.  This should release soon.
