### ISSUE TITLE
NPCs are not loading in editor

### ISSUE THREAD

**Issue by alperenbayraktar** [lgsvl/simulator#1709]
On line 166 of NPCManager.cs, if you did not check the NPCs from the DeveloperSettings window,
![image](https://user-images.githubusercontent.com/35660502/130577350-9bdc9517-4bc2-461c-9981-447ad1af27fe.png)
DataModels.NPCs still get initialized so it can't pass the null check and can't get the NPCVehicles loaded by the Config.cs. If I just wanted to load my local NPCs in the AssetBundle, the if check could be turned into Count == 0 so it would go inside.  
![image](https://user-images.githubusercontent.com/35660502/130577454-578e23c8-211f-4ef9-be25-7bbb5895ffb7.png)

**Comment by EricBoiseLGSVL** [comment]
Thanks for posting we have fixes for development settings in 2021.3.  It is still very work in process.
