### ISSUE TITLE
traffic lights editing in VSE editor

### ISSUE THREAD

**Issue by nijilong1224** [lgsvl/simulator#1711]
Hi all:
How to edit traffic lights behavior in windows VSE, from the Python API guide, it can change its behavior by updating control policy: "trigger=50;green=1;yellow=1.5;red=2;loop", while in VSE I only can update policy in this manner.
![image](https://user-images.githubusercontent.com/42104427/130609151-edc525d0-0c53-449f-882d-7b9d2b7de8d6.png)
does that mean each state will wait for several secs specified in wait field? Also if I edit one traffic light in junctions, other lights policy will changed automatically.
![image](https://user-images.githubusercontent.com/42104427/130609635-bbca9a8c-9218-42c1-98d0-d3659a4cb554.png)
Seems it's not a correct policy.

Thanks.

**Comment by EricBoiseLGSVL** [comment]
Yes, this is the functionality that we support as of now.  We are working on supporting more but it is not ready yet.  What do you think would be the correct policy?  Any feedback is great and helps us create better features.  @KarByc

**Comment by KarByc** [comment]
Hello @nijilong1224 ,

Policy "trigger=50;green=1;yellow=1.5;red=2;loop" can be achieved by replacing the PythonAPI lights color command with a pair of "state" and "wait" commands in the VSE. Please try setting it like below:
![image](https://user-images.githubusercontent.com/13436173/130670545-791a92ab-6036-44ca-9212-0220b9a119f6.png)

If lights do not behave as expected please include videos of the expected behavior (set with the PythonAPI) and the actual behavior (set with the VSE) with their Python API code and VSE setting screenshot. That will help me to reproduce the issue.
Thanks!

**Comment by nijilong1224** [comment]
Hi @EricBoiseLGSVL and @KarByc

Thanks for your quick reply.
@KarByc, The lights behavior through Python API is right.
Since, I could not run VES template in windows simulator, so I decide to generate VSE template file, parse the file in python, then run the scenario through APIs.
my concern is if I edit only one traffic light policy in VSE, other lights in same junction will have some policy value automatically, is that correct?
![image](https://user-images.githubusercontent.com/42104427/130738172-185c229e-86bd-4592-9fcb-820317b64c60.png)
editing the middle light policy with "trigger=20;green=20;yellow=3;red=20;loop"
![image](https://user-images.githubusercontent.com/42104427/130738740-507c54b5-1632-40b1-9d3f-a3d4fa0eafcc.png)
check the right light policy
![image](https://user-images.githubusercontent.com/42104427/130739150-3b07535b-8dc8-407e-ae6d-b603e2ac8c51.png)
![image](https://user-images.githubusercontent.com/42104427/130738989-a6b17600-6e4c-47c3-b724-251b7fc3878e.png)
check the left 2 lights policy
![image](https://user-images.githubusercontent.com/42104427/130739276-4838c073-292e-4477-9549-df1b654d908f.png)
check middle light policy again, the loop tag is missing.
![image](https://user-images.githubusercontent.com/42104427/130739739-8734aa78-450f-4ea7-b6e7-e07eb32e4e1e.png)
the final VSE template file contents corresponding to lights, no "loop" action.
how to distinguish the controllable type, I only want to retrieve traffic lights info.

BTW, could I use Playback function to check traffic lights behavior in VSE editor.

Thanks a lot!
Best Regards

**Comment by nijilong1224** [comment]
Hello @KarByc 

It's great, thank you very much!

Best Regards
