### ISSUE TITLE
Autopilot not working, the bridge is connected but the car cannot move? Apollo_6.0

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1716]
Dream view console shows error while the car is stooped even the traffic signal is green and routing is successful. 
![svlerror](https://user-images.githubusercontent.com/61130487/130886628-76409385-bd47-41f0-a177-322cb06fc385.png)

![Screenshot from 2021-08-26 06-33-34](https://user-images.githubusercontent.com/61130487/130886938-d3ac399d-9ca7-435f-91c8-72fb115863b7.png)
![Screenshot from 2021-08-26 06-18-52](https://user-images.githubusercontent.com/61130487/130886979-b4719166-0165-4230-a07e-a4fefeec715c.png)

SVL simulator setting, I have tried different setting (Change sensor configuration and Autopilot) but still have same issue. 
![Screenshot from 2021-08-26 06-37-33](https://user-images.githubusercontent.com/61130487/130886767-392a824c-a16e-4570-bd35-7880826e9d71.png)

**Comment by EricBoiseLGSVL** [comment]
What version of simulator are you running and is the issue with dreamview or simulator?  I see that you have a camera sensor.  Are you aware apollo 6 perception is bugged and you need to use modular testing? You can read about it in our docs [here](https://www.svlsimulator.com/docs/system-under-test/apollo-master-instructions/).

**Comment by Addi2020** [comment]
@EricBoiseLGSVL 
1. I use simulator version Unity Hub 2.4.5.
2. It is dreamview issue as you can see the dreamview screenshot. 
3. Yes, camera sensor is working fine and i use modular testing. 

So the problem is that routing is successful but car cannot move and the dremview also also shows an error "RAW IMU message delayed............." (2nd screenshot). I guess its due to time difference error between apollo server and my PC. If i am right then how to solve time difference error.

**Comment by Addi2020** [comment]
@EricBoiseLGSVL , I am not sure about ClockSensor.

**Comment by Addi2020** [comment]
@EricBoiseLGSVL , After a long time , I am back to this issue. I set up clock sensor. but still the car can not move. 

Control, planing and routing logs

![Screenshot from 2022-01-16 21-04-26](https://user-images.githubusercontent.com/61130487/149678088-e19ee07c-a575-49cc-99d5-0dbc6c086bfc.png)
![Screenshot from 2022-01-16 21-04-34](https://user-images.githubusercontent.com/61130487/149678089-9316f54c-4339-4a4f-a90c-24438f273341.png)
![Screenshot from 2022-01-16 21-06-06](https://user-images.githubusercontent.com/61130487/149678091-dfde3857-042a-4c1c-b522-c75a588d8705.png)

**Comment by EricBoiseLGSVL** [comment]
Sorry but this seems like an issue with dreamview.  Have you posted on Apollo's issue page yet?  Maybe another user has seen this before here,
