### ISSUE TITLE
Map with point cloud data

### ISSUE THREAD

**Issue by roderauto** [lgsvl/simulator#1718]
Hi,
I want to create a map from point cloud data imported with MapToolBox 
but there is a problem.
problem is Map toolbox is not available in projects that build simulators.
So I did an export package from the project in the map toolbox and imported it into a project where I could build the file.
and Setting a mesh collider on a point cloud map saved as a prefab causes an error in upload

Please teach beginners how to create a new map using point cloud data.
![図1](https://user-images.githubusercontent.com/82795532/130920351-c10144f9-8fc7-44df-8b0d-9ec4e2e6c4bd.png)
![図2](https://user-images.githubusercontent.com/82795532/130920369-95b82959-5945-477b-ad30-83c7c79e426b.png)

**Comment by EricBoiseLGSVL** [comment]
Have you made progress on this?

**Comment by roderauto** [comment]
thank you.
However, I want to map the point cloud data imported [here](https://github.com/autocore-ai/MapToolbox).

No.1 is the point cloud imported by Map tool box
No.2 is the point cloud imported byPoint Cloud Import

I want to use number 2 because the map is cleaner

![図８](https://user-images.githubusercontent.com/82795532/131432411-21d15fcf-5c17-4fdb-80b6-35d558e0ef28.png)
![図2](https://user-images.githubusercontent.com/82795532/131432414-f0d75859-dedd-4012-b21d-11ca7e658fb9.png)

**Comment by EricBoiseLGSVL** [comment]
Are you turning on the lighting in the environment to see the actual point cloud?  This image 1, is with no lighting and no point cloud rendered.  That is just the simplified collider we provide.

**Comment by roderauto** [comment]
I turned it on but nothing is displayed

![ｌｌ](https://user-images.githubusercontent.com/82795532/131434010-d3f0d617-2660-40bd-b85a-ef5784c3dfe9.png)

**Comment by EricBoiseLGSVL** [comment]
Is there any color information in your point cloud?  I see in the MapToolBox image it has a default texture (this is used in modeling when no texture is available or to align UV's).  If you don't have any color data then there is nothing we can render.  We don't generate a mesh to render, we render the points with intensity or color themselves.

**Comment by roderauto** [comment]
Thank you very much.
Is there a way to create a mesh on the map in this image?
Because the point cloud is imported neatly.
![図2](https://user-images.githubusercontent.com/82795532/131440566-e4e13952-07a5-4d6f-8a73-e17327b913f9.png)

**Comment by roderauto** [comment]
If you select a color with the red arrow, it will be displayed like this.
![Uploading ６６６.png…]()

**Comment by EricBoiseLGSVL** [comment]
@roderauto Ah, yes! I forgot about the colorize option.  Thanks!
