### ISSUE TITLE
Abnormal Scene display in Unity

### ISSUE THREAD

**Issue by ideasplus** [lgsvl/simulator#1725]
Hi Team,

I want to modity the specific map to add some 3D cubes,  so I open the map in Unity, edit and build it according to official document.  

However, when I run simulation from the modified map, the scene display is abnormal as shown in the following. Why does this happen and how can I solve this problem? 
The second question is when I add a 3D cube to the map,  what attributes should I add to it? and how can I change the size of the cube?

Note that I'm using lgsvl 2020.06 and Unity 2019.3.15f1.

Here is the screenshot when I open CubeTown in Unity
![Screenshot from 2021-08-31 16-30-47](https://user-images.githubusercontent.com/24294571/131474845-3553c8e4-152c-4600-904a-e89c677ad004.png)

Here is the screenshot when I run simulation from the modified CubeTown map
![Screenshot from 2021-08-31 16-33-11](https://user-images.githubusercontent.com/24294571/131474869-5625f7eb-3a97-4df9-ab17-2d327eaac9cf.png)

**Comment by EricBoiseLGSVL** [comment]
Why are you using simulator 2020.06? This is very old.
What tag do you have the cubetown repo at?
Did you have git lfs running when you cloned cubetown?

**Comment by ideasplus** [comment]
> Why are you using simulator 2020.06? This is very old.
> What tag do you have the cubetown repo at? Be sure it is 2020.06
> Did you have git lfs running when you cloned cubetown?

I prefer to use the simulator 2020.06 because I've been using this version for a long time.
Thanks for your reminding. I have solved this problem.

Meanwhile, I have a new little question, How can I switch this view in simulator like this?
![图片1](https://user-images.githubusercontent.com/24294571/131645947-f0835bb7-5bef-42cd-85df-a9ee0678ad28.png)

**Comment by EricBoiseLGSVL** [comment]
Can you please post the solution to help others?
This is the driver view camera mode that is available in the latest simulator.

**Comment by ideasplus** [comment]
> Can you please post the solution to help others?
> This is the driver view camera mode that is available in the latest simulator.

Yes, I solve the problem by switch the version of the map to 2020.06

Thanks for your help.
