### ISSUE TITLE
 After the traffic crash, the npcs do not disappear

### ISSUE THREAD

**Issue by gizem-buss** [lgsvl/simulator#1726]
Hello, I am creating npc's with python api and I provide the movements of these npc's with the follow closest lane. After the traffic crash, the npcs do not disappear after a certain period of time. How can I provide?

**Comment by EricBoiseLGSVL** [comment]
You can have a callback on collision and sim.reset

**Comment by gizem-buss** [comment]
thx,@EricBoiseLGSVL . When I use sim.reset, does it disappear in all scenarios I created with the python api? What I want to do in python api is that when two npc collide or traffic jam, those vehicles are destroyed.

**Comment by EricBoiseLGSVL** [comment]
You need to change the simulator source to despawn on collision or on trigger. It's the same code that calls the ApiManager to add the call back
