### ISSUE TITLE
Change the lgsvl/apollo-3.5 bridge port

### ISSUE THREAD

**Issue by daohu527** [lgsvl/simulator#173]
The lgsvl/apollo-3.5 provide a bridge, which listens on port 9090 in default. Then I change the port to 9098 because the port in linux is occupied. The problem is that I can't find any place to change the port in the simulation.  
Could you help me to deal with that ?

**Comment by xmyqsh** [comment]
@daohu527 
`
Assets/Scripts/ROSAgentManager.cs:100:            var port = PlayerPrefs.GetInt($"ROS_AGENT_{i}_PORT", 9090);
`
`
Assets/Scripts/RosBridgeConnector.cs:25:    public const int DefaultPort = 9090;
`
change the code and recompile.

Alternatively,
Run simulator and apollo in different machine, and forwarding the port
`
ssh -L 9090:localhost:9098
`

**Comment by daohu527** [comment]
@xmyqsh Thx
I see a little about the apollo bridge code. Is there any conf in python? The bridge is translate the python message. I don't want to compile the project, or maybe later I will try.  

By the way in my case, I use a server run apollo3.5 and change the port to 9098, then open the simulation in my localhost. Have can I set the "ssh -L 9090:localhost:9098", which need a server name ?
I looked at a similar tutorial, but it was a bit confused. Where do I run the cmd, and I try "ssh -L 9090:localhost:9098 localhost" It doesn't work.

**Comment by martins-mozeiko** [comment]
No need to change code in simulator to use different port. Just enter it directly in address:

![image](https://user-images.githubusercontent.com/39178216/58497851-b0236100-8131-11e9-82e8-9e2904e8c086.png)

To make bridge to listen on different port, edit `scripts/bridge.sh` and append `-port 9098`

**Comment by daohu527** [comment]
@martins-mozeiko  Thx for you reply!
 I try to add the port in "192.168.1.102:xxxx", seems the input is not allowed to be so long? I will try again!

**Comment by martins-mozeiko** [comment]
There should not be any limit on length there. Maybe you have resized window too small? It probably does not fit on screen, but it actually stores full value. Try moving cursor left and right to see if input is scrolling for full value.

**Comment by daohu527** [comment]
@martins-mozeiko 
You are right, It work well by "192.168.1.102:xxxx", maybe some problem in “Shif” key and make some garbled in the input box. 
Thank for you job!
