### ISSUE TITLE
Question about Lidar Sensor

### ISSUE THREAD

**Issue by lorlor** [lgsvl/simulator#1734]
Hi guys,

I have a problem about simulation point cloud sending. Limited by the rosbridge_websocket bandwidth, I couldn't get image with high resolution like 1920x1080 when point cloud sending with 32 lines. How could I send simulation point cloud with higher scanning lines?

Any advice will be appreciated.

My environment:
OS: ubuntu 16.04
Simulator version : 2021.1.1
Autoware: 1.12

**Comment by EricBoiseLGSVL** [comment]
Are you using a gigabit switch/Router?

**Comment by lorlor** [comment]
Sorry, I didn't have a giga device. Can I using UDP data frame to send simulation point cloud?

**Comment by EricBoiseLGSVL** [comment]
No sorry, our docs state you need a high bandwidth switch/router.  UDP is even slower.  You can try it but we recommend the minimum requirements for data collection.  Anything slower is just too difficult to trouble shoot and we can't support.

**Comment by lorlor** [comment]
Thanks for your reply.
