### ISSUE TITLE
Asmdef file name

### ISSUE THREAD

**Issue by ertauren** [lgsvl/simulator#1739]
Hi, I would like to give feedback about Simulator.Bridge.Ros.asmdef file
it is actually Cyber bridge file but it used in correct place and doesn't cause any problem.
It is working, not bugged and so, not priority issue but still wanted to let you know for healthier project.
If it is already known feel free to close the issue.

![image](https://user-images.githubusercontent.com/40769329/132307706-0c90b1d4-5db0-4126-9d78-be5269c71542.png)
![image](https://user-images.githubusercontent.com/40769329/132307753-c02e76c5-91e7-43b8-8df1-f1e5d24791fc.png)

**Comment by heeen** [comment]
This will be fixed in an upcoming release, thank you!
