### ISSUE TITLE
Signal sensor cannot detect traffic light in a map I build.

### ISSUE THREAD

**Issue by YoshikiKccs** [lgsvl/simulator#1741]
I learned how to do  map annotation. Therefore I combined  my map with  Cube Town.
I wanted to create horizontal signal, so I replace vertical traffic light with horizontal traffic light. Next I built that map and used it in simulator. But signal sensor cannot detect that traffic light. Please teach me what I should do.

Unity version: 2019.4.18f
Svl simulator version: 2021.1
OS: Ubuntu16.04

![スクリーンショット 2021-09-08 151348](https://user-images.githubusercontent.com/90304547/132456062-90a02ef8-91db-4163-abaf-8af73249c253.png)

![スクリーンショット 2021-09-09 103028](https://user-images.githubusercontent.com/90304547/132607298-d522fc5e-a10b-4c52-96a2-be6b580940ee.png)

**Comment by heeen** [comment]
Have you linked the signal and lane/stop line? 
Looking at the source for the sensor, it seems to only detects signals that are child objects of the intersection that creates  the trigger collider volume
https://github.com/lgsvl/SignalSensor/blob/master/SignalSensor.cs

**Comment by EricBoiseLGSVL** [comment]
Like @heeen stated, it is most likely an annotation issue.  Please post a screen shot of the intersection in Unity so we can see how you annotated it.

**Comment by YoshikiKccs** [comment]
@heeen 
Thank you for teaching for me.
I will check that.

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
Thank you for working on solving the problem.
I see. I got it.
It is as shown below.
![スクリーンショット 2021-09-14 091607](https://user-images.githubusercontent.com/90304547/133176607-2addc483-d2d9-47ed-91c3-b6461f12069f.png)
![スクリーンショット 2021-09-14 091708](https://user-images.githubusercontent.com/90304547/133176629-1cb6091c-caaa-4ad3-a530-26b280fca71a.png)

**Comment by EricBoiseLGSVL** [comment]
Be sure the hdmap exporter supports the horizontal as well if you need that.

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
Thank you for your prompt response. I'm very sorry, but I don't know how to see the exporter.  I only know how to see the build settings window...  Could you please teach me how to see that hdmap exporter?

**Comment by EricBoiseLGSVL** [comment]
what hdmap type are you planning to use?

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
I want to get hdmaps for Autoware Vector Map and Apollo 5 HD Map.

**Comment by EricBoiseLGSVL** [comment]
No worries, if you look at the project panel on the bottom you can see a search panel.  Just type in AutowareMapTool or ApolloMapTool.  Open those scripts and look for signal in the code.  To add the new type, change the logic to test for the rotated signal and apply the data type the hdmap type expects, e.g., Apollo only had vertical supported when we wrote the exporter, look to apollo docs to see what they expect to have for the horizontal type and write a check (you could even add a string to the mapsignal class and check that name == horizontal). Then compile and export with your new functionality.

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
Thank you for telling me. I'll check them and add horizontal.

**Comment by YoshikiKccs** [comment]
I'm sorry for asking again.
I've been looking for problem area and checked mapsignal class.
However, I couldn't find out.
If you like, please teach me more detail such as image...
![image](https://user-images.githubusercontent.com/90304547/134301699-405971de-06ce-4086-b894-dff953481ee0.png)

**Comment by EricBoiseLGSVL** [comment]
No worries. Looks like we already added different signal types, you just need to assign in the editor.  Be sure this code is similar or you may need to wait until next release.

![image](https://user-images.githubusercontent.com/45106230/134404220-f3c9e129-6614-43e9-993e-3e381f211834.png)

![image](https://user-images.githubusercontent.com/45106230/134404328-466bc95c-6fa8-4f12-8e7d-6a68d102d14a.png)

![image](https://user-images.githubusercontent.com/45106230/134404599-e40b3794-3e34-4b1a-a994-93bcf660cfb9.png)

![image](https://user-images.githubusercontent.com/45106230/134404761-a7dc9fb7-e833-4be1-8647-c609a2b83870.png)

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
Thank you very much for teaching me details. I'll try it!

**Comment by YoshikiKccs** [comment]
@EricBoiseLGSVL 
I became to be able to detect horizontal signal. Thank you very much for your helping!!!
I really appreciate you!

**Comment by EricBoiseLGSVL** [comment]
Glad to help
