### ISSUE TITLE
NMEA Sentences are malformed when the locale is not U.S.

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#1742]
Hello, 
This problem appeared with the following configuration : 
- Sim running on **Windows 10** with **SVL v2021.2.2**
- Other computer was running the **ROS1 bridge**.

The windows computer was configured with Estonian locale with comma as decimal separator and it generated GPGGA sentence that was not in accordance with the [format](https://docs.novatel.com/OEM7/Content/Logs/GPGGA.htm).

I dont have the wrong sentence here.

When switching the windows computer to U.S. locale and number format the problem was not here anymore. When reverting to Estonian format it went back.

NMEA sentence are not supposed to depend on the emitter's locale.

Thanks for your time.

**Comment by heeen** [comment]
Thank you, I believe I found the fix for this issue and I'm hoping we can include it in the next release.

**Comment by EricBoiseLGSVL** [comment]
We have a fix for next release, thanks for posting and letting us know.
