### ISSUE TITLE
BridgeNameAttribute error when compiling custom bridges

### ISSUE THREAD

**Issue by ljjhome** [lgsvl/simulator#1744]
Hi,

 I tried to compile a custom bridge. I followed this [loggingBridge](https://github.com/lgsvl/Logging) example, but I got an error saying "BridgeNameAttribute does not contain a constructor that take 2 arguments" as shown below.
![Selection_003](https://user-images.githubusercontent.com/7417691/132643359-d57d33eb-7727-4a97-96cd-7474337371c4.png)

I also tried downloading other bridges from GitHub but got the same error.

The tree cmd display is as below. I didn't modify any of the files.
![Selection_004](https://user-images.githubusercontent.com/7417691/132648621-2e2943cd-11c3-4939-9382-24196dbefe40.png)

I am not familiar with c#. Do you know how to fix this error? 

Thank you

**Comment by heeen** [comment]
Try checking out commit 92e6538  of logging bridge, it was updated to work with an upcoming release of simulator.

**Comment by ljjhome** [comment]
Thank you @heeen, It works.
