### ISSUE TITLE
Apollo 3.5 [cyber bridge] error after bridge.sh 

### ISSUE THREAD

**Issue by ninjacoder0** [lgsvl/simulator#175]
![problem](https://user-images.githubusercontent.com/44463247/58468327-44db8e00-8135-11e9-8add-7460bea9a4e0.png)

Hi All, PLEASE HELP. Been trying to fix this for a week.

I formatted my PC, installed 3.5 correctly, it downloaded and built without any issues. Although when I run "bridge.sh" (shown in the image)and run the simulator, I get the following error appear in red....

_"E0528 10:28:02.682471 30652 client.cc:85] [cyber_bridge] Unknown operation received from client (71), disconnecting client"_ 

What am I doing wrong, how can I fix this?
Thank you.

**Comment by luqiang21** [comment]
@ninjacoder0 This error is because of the wrong vehicle selected. The bridge for apollo 3.0 and 3.5 is different. You need to change the vehicle to vehicle: `XE_Rigged-apollo_3_5`.
