### ISSUE TITLE
SanFrancisco map and simulation do not match in version 2021.2.1 and 2021.2.2 

### ISSUE THREAD

**Issue by bettertha** [lgsvl/simulator#1754]
I tried to follow the tutorial to connect apollo5.0 using both versions 2021.2.1 and 2021.2.2 .
The initial scene is:
![initial](https://user-images.githubusercontent.com/28682781/133452833-b788590c-c9f0-4cf0-9f3f-c082af9f8644.png)
The scene after the car went straight for a section of the road is as follow.
![image](https://user-images.githubusercontent.com/28682781/133453543-0e9713f0-37fb-4c33-925b-07c43a81fa56.png)

**Comment by EricBoiseLGSVL** [comment]
Yes, this is a bug and will be fixed in the upcoming release.  Thanks for posting

**Comment by daohu527** [comment]
@EricBoiseLGSVL I know LGSVL is out of maintenance now, but pls can you tell me the specific cause of this problem and I will try to fix it

**Comment by EricBoiseLGSVL** [comment]
We think this is from an issue with an outdated HDmap that Apollo is using or ignore map origin needs to be used.
