### ISSUE TITLE
I could not stop simulator

### ISSUE THREAD

**Issue by roderauto** [lgsvl/simulator#1757]
Hi,
I couldn't stop the simulation.
Please help.
I'm running in a Unity development environment

![図1](https://user-images.githubusercontent.com/82795532/133555324-d174271a-632c-43e7-bd30-8cbf94f39118.png)

I tried
・ Delete cache
・ Log out
・ Restart Unity
・ Restart your PC

**Comment by EricBoiseLGSVL** [comment]
Please use Ctrl+F5 in the WebUI with Unity Hub and Unity Editor completely closed.  This issue is fixed in the next release.

**Comment by roderauto** [comment]
I tried but couldn't stop.
Is it because you deleted the previous cluster?

**Comment by EricBoiseLGSVL** [comment]
Are you stopping the sim in the application?  I recommend stopping in the application until next release.  There is a bug with stopping in webui.  What about deleting cluster?  Are you deleting the cluster while running the simulation?

**Comment by roderauto** [comment]
I was able to stop the simulator. thank you！
