### ISSUE TITLE
Can't save Lidar pointcloud with Python API in version 2021.2

### ISSUE THREAD

**Issue by rogeherlor** [lgsvl/simulator#1758]
Hello. I have been using python API in versions 2020.06 and 2021.1 to save pointclouds without any problem, but I have errors when i use the command s.save in version 2021.2

The code is from Pythons API quickstart [Quickstart Code](https://github.com/lgsvl/PythonAPI/blob/master/quickstart/07-save-lidar-point-cloud.py)

![image](https://user-images.githubusercontent.com/8066907/133639084-e3857611-3d20-40f4-bb92-a215d413fc4f.png)

[Documentation](https://www.svlsimulator.com/docs/python-api/python-api/#lidar-sensor)

**Comment by EricBoiseLGSVL** [comment]
Yes, this is a bug and has been fixed in the next release.  Here is the diff if you want to add to the sensor now. Sorry about the regression.
![image](https://user-images.githubusercontent.com/45106230/133657993-02d1a465-b5b3-4293-bfc5-223fcefef4a7.png)
