### ISSUE TITLE
G29 doesn't control the car in Windows64 2020.05 version

### ISSUE THREAD

**Issue by chihchunhsu-dev** [lgsvl/simulator#1759]
Hello community,

I am new to LGSVL. Our team has been using LGSVL 2020.05. We bought a G29 steering wheel and tried to run it in our simulation. 
However, even though the Info panel says G29 is connected, when we step on the gas pedal or turn the wheel the car in the scene doesn't move at all. 

![image](https://user-images.githubusercontent.com/88467037/133746016-149a6bb9-ec67-4d40-98d0-159f02d0379c.png)

Does anyone ever get this problem? How did you solve it? Any advice would be appreciated.

Thanks,
Chih-Chun

**Comment by EricBoiseLGSVL** [comment]
Sorry, 05 release is very old, we recommend you update to latest simulator.  We are about to release 2021.3 that will allow you to add your own Unity input controls to a sensor.
If you can't wait/update then you will need to look at the input controls.  That version of sim is using a beta input package and might need changes.  Open the unity editor and make sure the G29 is correctly installed.  You will need the manufacturer software and drivers.  Unity editor has an input debugger. make sure all inputs are received and  the controls are mapped.

These are the windows to edit.  Make the fixes and just build a new simulator binary
![image](https://user-images.githubusercontent.com/45106230/133840623-47cece0d-24e0-489b-af64-f1a785cffa92.png)
![image](https://user-images.githubusercontent.com/45106230/133840728-60b16659-4d7c-4a49-94b7-8f92f8115d18.png)
![image](https://user-images.githubusercontent.com/45106230/133840835-7725f381-aebe-414e-8c6c-1fa4471e7104.png)

**Comment by chihchunhsu-dev** [comment]
Thank you it worked!
