### ISSUE TITLE
Customize Ros Messages

### ISSUE THREAD

**Issue by gizem-buss** [lgsvl/simulator#1764]
The ROS and ROS2 directories in the 2020.1.1.1 version are not available in the 2020.2 versions. How can we add our custom ros messages?

**Comment by EricBoiseLGSVL** [comment]
We have moved bridges out of the simulator so users can edit or create custom bridges.  Please see docs [here](https://www.svlsimulator.com/docs/plugins/bridge-plugins/) and repo [here](https://github.com/lgsvl/ROS).
