### ISSUE TITLE
Unity crashes when openning the simulator 2021.2.2

### ISSUE THREAD

**Issue by umdreamer** [lgsvl/simulator#1765]
I installed the Unity 2020.3.3f1 version as indicated in the documentation. The error occurs as follows, and then it crashed.
My system is Windows 10 64bit, 2004. The hardware configuration: ThinkPad T14 with i7 4cores, 32G memory, with Nvidia GeForce MX330.
![image](https://user-images.githubusercontent.com/15782682/134350152-dda2cae0-0428-4385-b875-5d4d44894719.png)
Any suggestion？Thanks.

**Comment by EricBoiseLGSVL** [comment]
The MX330 is an integrated graphics chip, not a GTX gpu.  This is not supported with Unity's HDRP pipeline.  Please see our docs [here](https://www.svlsimulator.com/docs/installation-guide/system-requirements/).

**Comment by umdreamer** [comment]
OK，Thanks. I'll change to better hardware to run it.
