### ISSUE TITLE
Uploading pedestrian asset on version 2021.2 results in error - assetUploader.errors.(undefined)

### ISSUE THREAD

**Issue by Maestroxr** [lgsvl/simulator#1766]
Hello,
I have tried building and uploading several pedestrian assets from the Walkers repository.
All of them result in the non-descriptive error: assetUploader.errors.(undefined)
I have tried uploading a NPC built from the DefaultNPC repository and that seems to work, I am able to upload.
I have reproduced the problem on more than one machine so I can confirm it is not local to my machine.
Any suggestions or insight as to how to handle this problem?

May I also note that error messages that have full description of the problem will be very useful,
as I have gotten the same error message in other occasions(upload size limit perhaps, hard to tell).

**Comment by EricBoiseLGSVL** [comment]
Pedestrian and NPCs and NPC behaviors are not supported in the WebUI yet.  We load the asset bundles from the AssetBundles folder locally at runtime.  Please do not upload to the webui yet. Hopefully we will have this feature soon.
