### ISSUE TITLE
How to run simulation inside Unity Editor ?

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1769]
Hi LGSVL Teams,

I would like to debug simulator inside Unity Editor.

When I run simulation inside Unity Editor, I got some errors.
![UnityErrorMessage](https://user-images.githubusercontent.com/5969040/134663160-fad2bca6-c9a1-4095-8662-d401fb92eab8.png)

How could I run simulation inside Unity Editor ?
Thanks.

**Comment by EricBoiseLGSVL** [comment]
search for the LoaderScene in unity editor project panel.  You can also open build settings and see the 0 index scene, this is a way, in Unity, to tell the entry scene to a project.

**Comment by EricBoiseLGSVL** [comment]
you can also use developer settings but you need to wait until next release bc we support cloud assets and 2021.2.2 is still WIP.  See [here](https://www.svlsimulator.com/docs/installation-guide/build-instructions/#testing-custom-assets-with-the-unity-editor).

**Comment by joeking11829** [comment]
> search for the LoaderScene in unity editor project panel. You can also open build settings and see the 0 index scene, this is a way, in Unity, to tell the entry scene to a project.

It does works.
Thank you.

**How to use load local "Environment" and "Sensors" to simulation ?**

> you can also use developer settings but you need to wait until next release

Got it.
Thanks.
