### ISSUE TITLE
Is there any fast way to assign Tag to multiple objects ?

### ISSUE THREAD

**Issue by joeking11829** [lgsvl/simulator#1771]
Hi LGSVL Teams,

Is there any fast way to assign Tag to multiple objects ?
or How can I create a tool to do it ?

Thanks.

![image](https://user-images.githubusercontent.com/5969040/134672681-f51d898d-ad37-4c90-8e0b-2c29a60e4d39.png)

**Comment by EricBoiseLGSVL** [comment]
I suggest a Editor script to do this.  You can extend EditorTools.cs, look at this and annotation tool for editor selection.  You can hold a reference to a multi selected objects and then apply a tag change.

**Comment by joeking11829** [comment]
> I suggest a Editor script to do this. You can extend EditorTools.cs, look at this and annotation tool for editor selection. You can hold a reference to a multi selected objects and then apply a tag change.

Got it, Thanks.
