### ISSUE TITLE
Uploading Custom Sensors on version 2021.2 - assetUploader.errors.(undefined)

### ISSUE THREAD

**Issue by gizem-buss** [lgsvl/simulator#1776]
Hello,
I have developed a new sensor, but I am getting "assetUploader.errors.(undefined)" while adding webUI. Can you help me?

![hata](https://user-images.githubusercontent.com/71923140/134906724-7d145970-d777-4719-a376-02e839170643.PNG)

**Comment by EricBoiseLGSVL** [comment]
Please show the bundle contents in a screen shot.  Also screen shot the name of the folder, prefab and class
