### ISSUE TITLE
Control apollo vehicle

### ISSUE THREAD

**Issue by ErijBNT** [lgsvl/simulator#178]
How can I drive the vehicle apollo using python script in ros 1 environment? 
In the lgsvl vehicle there is the publish control command. 
What about apollo.

**Comment by martins-mozeiko** [comment]
If you want Apollo to start driving, you need to enable necessary modules and send route command. Then Apollo will start sending back control command which simulator will use 

I'm not sure what exactly needs to be done in Python script if you want to do all this in in code - you'll need to check what API Apollo exposes to start routing, you probably will get better answer for this on Apollo issues/support.
