### ISSUE TITLE
NPC's states do not change after assigning new state to it using PythonAPI.

### ISSUE THREAD

**Issue by JohannesLiu** [lgsvl/simulator#1783]
Hi, there:

I encounter a problem using Python API to control NPC vehicle status. 

First, please go through the following  code quickly.
```
POV.follow_closest_lane(True, MAX_POV_SPEED, False)


POVCurrentState = POV.state

modifiedSpeed = NPCFuzzer.getSpeed(POVCurrentState.speed)
print("modifiedSpeed: {}".format(modifiedSpeed))
modifiedVelocity = Vector(modifiedSpeed * POVCurrentState.velocity.x / currPOVSpeed,
                                  modifiedSpeed * POVCurrentState.velocity.y / currPOVSpeed,
                                  modifiedSpeed * POVCurrentState.velocity.z / currPOVSpeed)
POVCurrentState.velocity = modifiedVelocity
print("modifiedVelocity: {}".format(POVCurrentState.velocity))

modifiedAngularSpeed = NPCFuzzer.getHeading(currPOVAngularSpeed)
print("modifiedAngularSpeed: {}".format(modifiedAngularSpeed))
POVCurrentState.angular_velocity.y = modifiedAngularSpeed

POV.state = POVCurrentState
```

As you can see, I want to assign a new POV state named "POVCurrentState" to the variable "POV.state". However, after the last line of the above codes  was executed, the "POV.state" did not changed. As the fig demonstrate following:
![image](https://user-images.githubusercontent.com/21165057/135377250-e4125339-19a0-4660-bfb8-a56f88f677ef.png)

**Comment by EricBoiseLGSVL** [comment]
The python api doesn't work this way.  We expect you to set state, not aspects of state.  Look at AgentState and Agent.py in the code base.
If you want to do this, you will need to edit the python api and then create commands in the simulator to effect NPCs this way.  You will also need to add/edit logic to NPCs to handle the new functionality.  See AgentSetState.cs

**Comment by JohannesLiu** [comment]
@EricBoiseLGSVL 
 Thanks for answering. Now, I can set the state.
