### ISSUE TITLE
Assets Uploader error

### ISSUE THREAD

**Issue by DestinyFrank** [lgsvl/simulator#1785]
I am trying to upload a new ego vehicle to the simulator I am following the tutorial below and have followed those steps. When I built the vehicle in unity and tried to upload it to the website it gave me the assetUploader.errors.(undefined) error. I have uploaded a new vehicle before and did not have this error before. 
![Screenshot 2021-09-30 122713](https://user-images.githubusercontent.com/86273840/135498131-439a2fe0-097b-492e-b23e-81d0abaf3e90.png)

https://www.svlsimulator.com/docs/simulation-content/add-new-ego-vehicle/

**Comment by EricBoiseLGSVL** [comment]
What is the size of the vehicle you are trying to add?

**Comment by DestinyFrank** [comment]
Here is the size of the asset bundle created in unity. @EricBoiseLGSVL 
![size](https://user-images.githubusercontent.com/86273840/135639125-4b62ab24-98fa-4e34-b0cf-7053622a1155.PNG)
 bundle created in unity.

**Comment by EricBoiseLGSVL** [comment]
Yes, that is too large.  2021.2 is limited to 50mb.  We are going to release 2021.3 today, please try to upload after the webui is updated.  We expanded it to 200mb.
Why is your vehicle so large?  What assets are you using to cause it to be so large?  Even with the update, you will need to reduce the size.

**Comment by DestinyFrank** [comment]
@EricBoiseLGSVL I was able to resize the model and go back through the process. I was then able to upload the vehicle to the simulator. Thank you for your help.

**Comment by StepTurtle** [comment]
I have a size problem like yours and I'm having a similar problem. I have vehicle model with .obj, .stl, .fbx extentions. Can you help me reduce the file size?

**Comment by EricBoiseLGSVL** [comment]
Use the fbx, don't embed any animations or textures in the model on export.  What size is it and are you on the 2021.3 release?

**Comment by StepTurtle** [comment]
Yes, I am using 2021.3 and my .fbx file size is 500mb. If I don't embed any animations or textures on the model during export, will my size drop below 200mb?

**Comment by EricBoiseLGSVL** [comment]
Depends on the size of the textures and poly count but it should help.  What is the tri count on the model?

**Comment by StepTurtle** [comment]
I had over than 100000 tri, i halved the number and it worked for me. Now I have new problem: https://github.com/lgsvl/simulator/issues/1982
