### ISSUE TITLE
Cannot start simulation gives Cannot find central directory error

### ISSUE THREAD

**Issue by bdrhnsen** [lgsvl/simulator#1799]
Hello there, I am new to the simulation I am using Ubuntu 20.04, Using nvidia rtx 2070. I installed nvidia drivers, cuda etc.
The simulation stops immidiately after I started, simulation window won't even open. I couldn't found any resource to handle the problem on the internet.
![image](https://user-images.githubusercontent.com/45562388/136538959-e916a666-8bef-4dd7-a647-859a515ab0cb.png)
When clicked on the button right to word "idle" it says:
Error on latest run: Cannot find central directory

**Comment by MaisJamal** [comment]
Can you please tell me how did you solve the problem?

**Comment by Truring** [comment]
I got the same error. How did you deal with that? Thank you for any tips.

**Comment by hanyh1191** [comment]
@Truring @MaisJamal @bdrhnsen  Hello, I also got the same error, how did you deal with it？ Thanks.
