### ISSUE TITLE
multiple egos support

### ISSUE THREAD

**Issue by ntutangyun** [lgsvl/simulator#180]
Hi, Just wondering if the lgsvl simulator supports multiple ego vehicles.

with python API, I tried to add one ego first, and another ego besides it. they both seems to run, but the simulator's screen will focus on the later ego vehicle, and the first one seemed to become an NPC vehicle...

Also, if I were to enable the Lidar for example, only the second Ego vehicle had its Lidar sensor rotating ...

**Comment by martins-mozeiko** [comment]
Simulator supports multiple vehicles.

Although API does not allow to switch focus to other vehicle, it allows to create and control second (or third, fourth, ...) ego vehicle just like first one. I'm not sure what you mean by saying that it "becomes an NPC vehicle". EGO vehicle cannot behave like NPC vehicle - it has no code to follow lanes or waypoints.

What kind of code are you using for turning on lidars?
Here's an example that will create two Apollo vehicles and turn on both lidars:
```
import os
import lgsvl

sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)
if sim.current_scene == "SanFrancisco":
  sim.reset()
else:
  sim.load("SanFrancisco")

spawns = sim.get_spawn()

state = lgsvl.AgentState()
state.transform = spawns[0]

a1 = sim.add_agent("XE_Rigged-apollo", lgsvl.AgentType.EGO, state)
for s in a1.get_sensors():
  if isinstance(s, lgsvl.LidarSensor):
    s.enabled = True
    break

state.transform = spawns[1]
a2 = sim.add_agent("XE_Rigged-apollo", lgsvl.AgentType.EGO, state)
for s in a2.get_sensors():
  if isinstance(s, lgsvl.LidarSensor):
    s.enabled = True
    break

sim.run()
```
