### ISSUE TITLE
Simulation stops immediately after Run. Error: "cannot find central directory"

### ISSUE THREAD

**Issue by MaisJamal** [lgsvl/simulator#1804]
I have built the simulator from the source following these [instructions](https://www.svlsimulator.com/docs/installation-guide/build-instructions/). I downloaded simulator release-2021.3 and Unity 2020.3.3f1. The operating system is Ubuntu 20.04.1 LTS.
When I run the simulation it stops immediately and shows the error: "Error on latest run: Cannot find central directory" in the website as well as in Unity:
![Screenshot from 2021-10-11 15-04-43](https://user-images.githubusercontent.com/17913075/136787249-56343812-8368-474f-b5da-fe60aa68513f.png)

![Screenshot from 2021-10-11 14-52-16](https://user-images.githubusercontent.com/17913075/136787258-4794b5ac-a4b9-40d1-8a67-7da84745691c.png)

I've tried the same steps in Windows, the simulation is running ok, but in Ubuntu, it's not.

Can you help me solve the issue, please?

**Comment by Truring** [comment]
@MaisJamal @EricBoiseLGSVL I got the same error:"cannot find central directory". I'm using ubuntu 18.04 and svl simulator 2021.3 release for linux. 
I deleted all files and directories in the AssetBundles folder and cleared cache, but I still got this error. Can you give me some tips to deal with this?

**Comment by EricBoiseLGSVL** [comment]
Please post the player log so we can see the errors.  What is the data path?  Do you have permission to this path?

**Comment by hanyh1191** [comment]
@MaisJamal  @EricBoiseLGSVL  I did the same thing but it still doesn't work, It seems not loading. Do you know why?
![Uploading 2022-05-04 21-16-21 的屏幕截图.png…]()

**Comment by hanyh1191** [comment]
@MaisJamal @EricBoiseLGSVL I did the same thing but it still doesn't work, It seems not loading. Do you know why?
![2022-05-04 21-16-21 的屏幕截图](https://user-images.githubusercontent.com/67039858/166693076-f7c6e03f-8619-442d-ba70-9f1757641a27.png)

**Comment by EricBoiseLGSVL** [comment]
we recommend ubuntu 20.04 and be sure you have permissions to write to the appdata directory.
