### ISSUE TITLE
Cannot upload new map to the cloud

### ISSUE THREAD

**Issue by MaisJamal** [lgsvl/simulator#1805]
I have downloaded and built the simulator from the source.
Simulator: release-2021.3
Unity 2020.3.3f1
I followed the instructions of the HD Map Mesh Generation [video](https://www.youtube.com/watch?v=bZk5kY-YgEM), downloaded the OpenDrive file of the CubeTown map(as a begining) available on your website. Imported it into Unity, fixed the error of "adjust the triggerbounds for each mapintersection" by adjusting the trigger bounds of the 2 intersections, then followed the instructions, and built the mesh and the asset.

![Screenshot (400)](https://user-images.githubusercontent.com/17913075/136789870-cf202a89-323b-4b1d-a141-9225b5200435.png)

When I try to upload the map asset to the website, I get the following error:

Required bundle files are missing for map/map: ["032e79d3-81df-49c9-b7cc-0ca2846d4eca_environment_main_windows","032e79d3-81df-49c9-b7cc-0ca2846d4eca_environment_main_linux"]

![Screenshot (399)](https://user-images.githubusercontent.com/17913075/136789840-b969e15f-00eb-4e8a-ae25-d7cff76def35.png)

Can you please explain to me what is the meaning of this error? how can I fix it?
and is there any way I can use the archive of the asset to run a local simulation of the costume map?

**Comment by MaisJamal** [comment]
I can't find it, it's not one of the options 
![Screenshot from 2021-10-11 14-59-28](https://user-images.githubusercontent.com/17913075/136843334-3e256b17-503d-43a5-8120-6e46b5d51f41.png)

**Comment by gizem-buss** [comment]
Hello, i am getting the same error. Can you help me?

![image](https://user-images.githubusercontent.com/71923140/142158526-875e61d4-7334-436b-aa0f-f65007140378.png)

![image](https://user-images.githubusercontent.com/71923140/142158562-c0dd01a2-e4ff-4b0f-84a8-b30c76ce6d3f.png)

**Comment by EricBoiseLGSVL** [comment]
@gizem-buss It looks like you failed to build the map bundle.  Please post a zip of what you are trying to upload. Do you have errors in the Console panel when you try to build?

**Comment by gizem-buss** [comment]
Hello @EricBoiseLGSVL , I am not getting any error while buiting. The zip is also attached
![hata1](https://user-images.githubusercontent.com/71923140/142359533-4696b228-fb06-4229-b852-aef8739153b4.PNG)
.
![içerik](https://user-images.githubusercontent.com/71923140/142359536-06c4c415-3a45-4cdb-ae73-7b175ea8ab40.PNG)

**Comment by gizem-buss** [comment]
I solved my problem in issue [https://github.com/lgsvl/simulator/issues/1876](url) thanks.

**Comment by alicankahraman** [comment]
Hi, 

I am trying to build a road environment for SVL 2021.3.  

Previously, I was using first version of simulator with Unity 2019.4.18f1 and had no problems. 

Now I have done my installs from Building From Source to use your version 2021.3.  My Unity version is  2020.3.19f1 version(in Windows) 

After the installation, I tried to upload the new map to SVL cloud. But I have got the following error: 
![image](https://user-images.githubusercontent.com/79085330/143937212-a282b2d4-03f7-4fe2-bed6-ae04fae320b2.png)

While creating the map, I proceeded as follows: 

To create a map, I first designed the following simple two-lane road in JOSM.
![image](https://user-images.githubusercontent.com/79085330/143937308-e32e36cf-a32a-48ce-ab6c-0864578b5952.png)

After successfully importing this designed path to Unity, I used the Build command for SVL. As you can see in the console below, the Asset Bundle was created without any problems.

![image](https://user-images.githubusercontent.com/79085330/143937357-2a29edee-1412-4026-8042-6a8926b8e12c.png)

When I check my version, it seems to have the Linux Build Support (mono) already installed. 

![image](https://user-images.githubusercontent.com/79085330/143937428-ed3005ad-4606-482a-b88c-cabad8217b92.png)

What could be the causes of the above mentioned error? 

Note: I also tried to change Unity version to 2020.3.3f1 but simulator project could not be opened. I got  following compilation error:

![image](https://user-images.githubusercontent.com/79085330/143937499-a26c5729-6dd9-49bd-8941-588e79445b70.png)

**Comment by EricBoiseLGSVL** [comment]
This is not the correct version of Unity and sim branch/tag.
See the above comments to use 2021.3.3f1 with release-2021.3... not master
![image](https://user-images.githubusercontent.com/45106230/143983543-3ea5f71a-251e-400a-aabe-57f0ae7eb39b.png)

Please remove the extra camera added to the scene you are making.
![image](https://user-images.githubusercontent.com/45106230/143983757-07b0433d-418b-4bcf-a8f5-ec5a9e8b2986.png)

Please reclone because you opened the project with a newer version of unity that can cause serious issues.  Unity is not backwards compatible.  Once you have the correct version of Unity with the release branch, try to build again.  You're installed module with linux mono is correct.  Also be sure to have gitlfs installed and pulled for assets you are cloning.

**Comment by alicankahraman** [comment]
I fixed the Unity version ( 2020.3.3f1) and created the road again, but I keep getting the same error when uploading to the cloud.
![image](https://user-images.githubusercontent.com/79085330/144259921-00a56168-41be-40a2-b787-850b069851b3.png)
![image](https://user-images.githubusercontent.com/79085330/144260082-3fa2e7f0-b4e4-4bc4-afc2-13a904bc2bf7.png)

**Comment by EricBoiseLGSVL** [comment]
Make the MapKisayol2 object a prefab, save the scene and add to the environment folder in a Prefabs folder.  Then make the bundle.  There is a bug for a scene with no prefabs.

**Comment by alicankahraman** [comment]
I did it as follows: 
 
![image](https://user-images.githubusercontent.com/79085330/144387377-73cadb47-a3f6-471f-8a1d-05716aff9482.png)

But I keep getting the same error when uploading to the cloud.
I also have another question. 
What is the easy way to make the maps created 2021.1  compatible with 2021.3 version ?

**Comment by EricBoiseLGSVL** [comment]
Can you post the file so I can look?  You can also open the bundle with 7zip to see inside and post a screen shot.

**Comment by EricBoiseLGSVL** [comment]
No you must make a new bundle for the new version.

**Comment by alicankahraman** [comment]
![image](https://user-images.githubusercontent.com/79085330/144487889-438dea62-2b28-4979-ab50-63367da9032d.png)
I opened the bundle. Windows,Linux,texture..  files are not created. What could be the reason?

**Comment by EricBoiseLGSVL** [comment]
Oh I see now.  You don't have the source materials/textures in the Map folder.  All assets need to be in the folder in Assets/External/Environments/YourMap.

This is why
![image](https://user-images.githubusercontent.com/45106230/144496115-bafb53c7-c7c2-4535-866c-ad7d6e24bdad.png)

It needs to be like this.  Clone CubeTown to see the example
![image](https://user-images.githubusercontent.com/45106230/144496318-39d44071-01a1-4960-9d58-24146623a375.png)

Simulator looks to the folder you are saving the scene to get all dependencies.  It should have prefabs, textures, materials and shaders if needed.

**Comment by alicankahraman** [comment]
I am appreciate for your  help. It solved by copying the prefab files into the folder in Assets/External/Environments/MyMap.

I didn't need to do something like this in the first version. (see below picture)
![image](https://user-images.githubusercontent.com/79085330/144607123-30195198-7c23-440f-b790-0a7cd17b5403.png)

**Comment by EricBoiseLGSVL** [comment]
Yes, assets used to all be in the simulator core code base and was changed after 2020.06 release.  Now fixes and updates can be separate from core feature releases.  Glad to help.
