### ISSUE TITLE
502 Bad Gateway in download bundle

### ISSUE THREAD

**Issue by neophack** [lgsvl/simulator#1815]
can't use

![Screenshot from 2021-10-15 14-11-37](https://user-images.githubusercontent.com/12814250/137440727-c025dc7c-320f-49fa-93f9-cec90c656c93.png)
![Screenshot from 2021-10-15 14-11-45](https://user-images.githubusercontent.com/12814250/137440730-52e6015f-7471-416e-bf05-629486324c62.png)
![Screenshot from 2021-10-15 14-12-23](https://user-images.githubusercontent.com/12814250/137440734-b0777d07-b279-4a93-8a2e-85da6e1cfd64.png)

**Comment by thisisdavidfrank** [comment]
@ @jonteca @neophack @ihsanyalcinkaya, the issue was related to one of our assets service going down. This issue has been fixed. Please try again. And, kindly let us know if you see any other issues.
Thank you.
