### ISSUE TITLE
Adding new map to apollo

### ISSUE THREAD

**Issue by zyan1234** [lgsvl/simulator#1842]
Hi,
At present Apollo dreamview has only Borregas ave map, I am trying to add straight2laneopposing map.

1. I downloaded the straight2laneopposing map from the simulator library in apollo50 format as suggested in the document https://www.svlsimulator.com/docs/system-under-test/apollo5-0-instructions/#adding-an-hd-map base_map.bin is downloaded. Created a new folder inside the path  APOLLO_ROOT/modules/map/data/ named straight2laneopposing and put the .bin file there.
2. Next I need to run generate_map.sh YOUR_MAP_FOLDER_NAME command inside the apollo container, but when I do this it's giving me an error as command not found. I even tried to run this command outside the container but still gave the same error. I am attaching the screenshot for the same.
![Apollo_map](https://user-images.githubusercontent.com/88095678/139256340-64c4a4ba-416a-41c0-b71b-cde0ebd4f2b8.PNG)
In the screenshot first I have run the command outside the container, next I have entered the container and run the command. Both times I am getting the same error.
Please let me know what mistake I am making and help me add the map successfully in the apollo

Thank you

**Comment by zyan1234** [comment]
Hi @luqiang21 
I did copy the generate_map.sh script is into latest Apollo repo folder and tried to run  generate_map.sh <map folder> ,but it still gives the same error as shown 

![image](https://user-images.githubusercontent.com/88095678/139489396-8c56fc1a-c1ef-405d-8a10-e90f5358e1b0.png)

Please help

**Comment by luqiang21** [comment]
@zyan1234 The script is probably not available in any location. Can you try to run it using absolute path to it?

**Comment by zyan1234** [comment]
@luqiang21 
I just copied the generate_map.sh from Apollo 5.0 and put it inside the script folder in cloned Apollo repo. Then I started the container, enter it and tried running the generate_map.sh directly and also tried navigating to scripts folder and then run the generate_map.sh command.But the both times getting same error. What do you mean by run it using absolute path to it exactly. can you please suggest me more.

**Comment by luqiang21** [comment]
@zyan1234 Probably you need to change the script to be executable? `chmod +x generate_map.sh` Then try to run the script.

**Comment by zyan1234** [comment]
@luqiang21 
Sure, will try that.

**Comment by zyan1234** [comment]
@luqiang21 Thank you , It worked.
