### ISSUE TITLE
How to take depth camera image by Python API?

### ISSUE THREAD

**Issue by ldt17** [lgsvl/simulator#1845]
These days I started learning LGSVL simulator. I tried to reproduce the operation of Python API in the official tutorial and intend to conduct in-depth study on this basis. When I tried to save the depth camera image, I meet some problem.  

I tried the following code:

for sensor1 in a.get_sensors():
    print(sensor1.name)
    sensor1.enabled = True  # 开启每一个 sensor
    if sensor1.name == "Main Camera":
        sensor1.save("main-camera.png", compression=0)
        sensor1_mc = sensor1
    if sensor1.name == "Depth Camera":
        sensor1_dc = sensor1
    if sensor1.name == "Segmentation Camera":
        sensor1_sc = sensor1

sensor1_dc.save("./pic_depth/1/%d.png"%i)

and I can successfully save the Main Camera image and Segmentation image, but fail to save Depth Camera image which output:

Exception: Sensor 'XXXXXX' is not a camera sensor.

I tried to solve this problem and checked other people's issues which link is:

https://github.com/lgsvl/simulator/issues/517

However, I can't find the file https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Sensors/DepthCameraSensor.cs

I try to add the code as following in SensorCameraSave.cs :

else if (sensorType.Name == "Depth Camera")
                {
                    bool result = (bool)sensor.GetType().GetMethod("Save").Invoke(sensor, new object[] { path, quality, compression });
                    api.SendResult(this, result);
                }

Finally, when I run the code to save Depth Camera image, there are not warning or error but I can't save the image as well.

**Comment by HonWek** [comment]
Hi, I am facing the exact same issue and am looking for a solution as well. And I would like to add on to this issue instead of opening a new one.

I would like to ask additionally if it is possible to achieve this (saving depth camera images using Python API) without building the simulator from source and just using the simulator binary?

Thanks in advance!

**Comment by EricBoiseLGSVL** [comment]
@ldt17 and @HonWek Thanks for posting this issue.  Unfortunately, Depth Camera Sensor Save is not supported and requires code changes with a new binary and sensor bundle.  We'll make the change and it will be in our next release.

@ldt17 you are close, but you need to also change the sensor code.  Not sure why we did this but I think it was legacy code that prevented support.  I'll outline the change we will push.

SensorCameraSave.cs
```
            if (sensor != null)
            {
                var sensorCamera = sensor.GetComponent<CameraSensorBase>();
                var path = args["path"].Value;
                var quality = args["quality"].AsInt;
                var compression = args["compression"].AsInt;

                if (sensorCamera != null)
                {
                    bool result = (bool)sensor.GetType().GetMethod("Save").Invoke(sensor, new object[] { path, quality, compression });
                    api.SendResult(this, result);
                }
                else
                {
                    api.SendError(this, $"Sensor '{uid}' is not a camera sensor");
                }
            }
```

DepthCameraSensor.cs
Delete the Save method completely and rebuild the sensor.  Build the api command changes in a new binary also (we should really move these to the sensors themselves)

Now any sensor using CameraSensorBase can save with api

**Comment by HonWek** [comment]
Hi @EricBoiseLGSVL , thank you so much for the answer. I am doing a school project which will be due and hence do not think that I can wait until the next release. I wish to proceed with building the asset bundle in this case.

Just to clarify, does "Build the api command changes in a new binary" mean building a whole new simulator binary?

Also, where do we find the DepthCameraSensor.cs file? I have been searching in this repository but was unable to find this file.

Thank you.

**Comment by EricBoiseLGSVL** [comment]
@HonWek yep, use Simulator -> Build...
Build the sensor and then the binary
https://github.com/lgsvl/DepthCameraSensor.  Clone to Assets/External/Sensors/ and you'll then see it in the sensors build menu.  Build the bundle, it will be in the AssetBundles folder in the sim repo root. Upload the the webui and set in vehicle config.  Next sim will then use the new sensor.  I recommend removing the default one from your library and make a new sensor called DepthCameraEdit or something unique. Ping if you have issues or questions, you got this.

**Comment by ldt17** [comment]
Hi @EricBoiseLGSVL  , thank you so much for the answer. Thank @HonWek  for adding some questions for me as well. Actually, I can't fully understand what you mean, but I'll try to modify it as you say. If is possible, can you give more detailed instructions or even provide some demos.

Thank you.

**Comment by HonWek** [comment]
@EricBoiseLGSVL Thank you so much for the detailed guiding steps!

Just want to make sure that my understanding is right, after uploading this new sensor to the Web UI, I can share this sensor plugin with anyone and the 'save' method for depth camera will be working fine (for anyone who uses this shared sensor) right?

This is because my Professor will also have to run the scripts after submission and I hope that he doesn't have to build the sensor and the simulator from source, which might create a lot of steps and trouble. It will be perfect if I could just share the new sensor plugin and the vehicle with him through the Web UI and everything works fine from there.

Thank you so much!

**Comment by HonWek** [comment]
Hi @ldt17 , no problem! Actually I am not 100% sure about whether my understanding is correct as I have not tried it out yet. Hope that @EricBoiseLGSVL could point out if I am wrong.

I think your changes in the SensorCameraSave.cs are fine already. What you need next is to edit the DepthCameraSensor.cs after cloning it from [here](https://github.com/lgsvl/DepthCameraSensor). If you look at line 41 to 45 of this file, it is overriding the 'save' method after inheriting it from CameraSensorBase, and this is the part hindering the 'save' method from working. According to the steps @EricBoiseLGSVL provided, we just have to delete everything from line 41 to 45 and it should work.

@EricBoiseLGSVL Please do correct me if I am wrong. Thanks!

**Comment by EricBoiseLGSVL** [comment]
@HonWek Yes, just share the sensor and be sure your professor uses the one you provide.  Hope you get some bonus points for edits :).
I would use the code I posted, it will match the next release and checks if any sensor inherits from CameraSensorBase so any new sensor someone makes will save.  If that is confusing, adding a check for the depth camera is fine also.
@HonWek is right, the biggest issue is the sensor that was blocking the method call in the base class.  By removing the method in the sensor, the base class method is used and will save correctly.
@ldt17 You got this, edit the python command in simulator code to check for depth camera, rebuild the binary, then edit the sensor to omit the save method, build the sensor and upload.  Use the sensor and save will work for depth camera.

**Comment by HonWek** [comment]
Hi @EricBoiseLGSVL I am facing issue while uploading the asset bundle to the Web UI after building it. I have already built and obtained the sensor_DepthCameraSensor file. But the Web UI returns the error "Type of Asset Bundle does not match the requested type" when I try to upload it. I attach a screenshot below. Please let me know what this error means. Thank you.

![image](https://user-images.githubusercontent.com/80387084/140862920-b6c8463e-b6c3-4381-b86f-1900b6a95691.png)

**Comment by HonWek** [comment]
Hi @EricBoiseLGSVL I am sorry for spamming. I have resolved the issue. Still, thanks a lot!

For anyone who might be interested, the issue was as mentioned in #475. I do hope that the documentation could be updated. 😃

**Comment by EricBoiseLGSVL** [comment]
@HonWek glad you got it working and thanks for posting your solution for others.  That is what the issue page is for :)
Please be sure to read docs before posting that something is missing https://www.svlsimulator.com/docs/installation-guide/build-instructions/
