### ISSUE TITLE
Add pedestrian tags

### ISSUE THREAD

**Issue by rogeherlor** [lgsvl/simulator#1849]
How can I add more tags to pedestrians as animals in the same way as to NPCs? I want to detect and classify different types of pedestrians with the 3D Ground Truth sensor

**Comment by EricBoiseLGSVL** [comment]
SegmentationIDMapping.cs and Perception3D/2D sensors will need edited.  This is tough because pedestrians have certain logic and cannot be sub classed.  You could add a data type to pedestrian controller and look up the new sub types.

**Comment by rogeherlor** [comment]
Thank you for your answer. I understand it, but i am not very familiar with the source code, so is there an easy way to concat the name of the built pedestrians (pedestrian_Bob, pedestrian_Turkey) to the same label that appears in Detection3D.msg?
