### ISSUE TITLE
Ultrasonic Sensor get the detection distance "0.0" while nearing a vehicle

### ISSUE THREAD

**Issue by PhoebeWu21** [lgsvl/simulator#1862]
Hi, 
I am trying to use the ultrasonic sensor to detect vehicles. But, I found that the distance I get is always 0.0 while nearing any kind of vehicle. My car is AWFLexus2016RXHybrid and ultrasonic sensors are set at both sides of the car and perpendicular to the side of the car, two for each side and near the wheels, the max distance is 3.5m, min distance is 0.2 and the fov is 14.6. 
![image](https://user-images.githubusercontent.com/36169304/140706083-92e23da2-b686-47bb-a07d-e95ace81e29b.png)
![image](https://user-images.githubusercontent.com/36169304/140706055-e3fe0c38-df28-45ec-9a64-e58a7f85b407.png)

And I also try to use traffic corn beside the car as the image, the distance still shows 0.0
![image](https://user-images.githubusercontent.com/36169304/140706560-908eec48-dca5-4af0-926f-cdddc50f7b3f.png)

However, when I remove the vehicle and left the traffic corn only, the distance shows correctly. 
![image](https://user-images.githubusercontent.com/36169304/140706855-7ecc55c8-1d57-4981-aeec-7982d945d73f.png)

How can I solve the issue? Any suggestion? 
Thank You!

**Comment by EricBoiseLGSVL** [comment]
Can you show the sensor setup in the webui please?
This might be a bug.  I'll ping @kamkolak-lge to see if there are any more questions and we will look into it.  Thanks for posting.

**Comment by PhoebeWu21** [comment]
Hi Eric, 
Thank you so much for replying.

These are the sensors setup.
![Screenshot from 2021-11-09 08-15-08](https://user-images.githubusercontent.com/36169304/140838503-1a5ecb5e-f386-4a73-a2c0-1f715f52a56b.png)
![Screenshot from 2021-11-09 08-15-20](https://user-images.githubusercontent.com/36169304/140838498-4709bff2-0c70-4942-ac81-27de146ea784.png)

**Comment by EricBoiseLGSVL** [comment]
Ah I see, they are very low.  Thanks for posting.  We'll look into this.

**Comment by PhoebeWu21** [comment]
> Ah I see, they are very low. Thanks for posting. We'll look into this.

Thank you so much.

**Comment by EricBoiseLGSVL** [comment]
This has been fixed and will be in the next release

**Comment by PhoebeWu21** [comment]
Got it. Thank you so much!
Looking forward to the next release!

**Comment by PhoebeWu21** [comment]
> This has been fixed and will be in the next release

Hi @EricBoiseLGSVL, I have received the notice that SVL Simulator will no longer have any new or bugfix releases.
However, my team decided to stick to LGSVL Simulator since it is the most convenient and close to reality. We are really grateful for what the SVL Simulator team has done.
Therefore, I am wondering if it's possible to let me know how and where to fix this bug. 
Thank you so much.

**Comment by EricBoiseLGSVL** [comment]
Glad you like the work done with simulator.  We wish it could continue.
Here are the files that need changed with a txt file letting you know what path to replace
[ultrasonicfixes.zip](https://github.com/lgsvl/simulator/files/8082311/ultrasonicfixes.zip)

**Comment by PhoebeWu21** [comment]
Got it! Really appreciate your reply.
