### ISSUE TITLE
How can I reset the scene and the seed?

### ISSUE THREAD

**Issue by rogeherlor** [lgsvl/simulator#1866]
I need to change the random seed of the simulation every time I reset the scene with the python API. 
I think the seed is random by default but it is set with the command:
sim.load("...")
In version 2020.06 I could load again the scene so the seed changed every time, but in version 2021.3 I can't load a scene that is alredy loaded, I can only reset it, but the seed is the same.

**Comment by EricBoiseLGSVL** [comment]
That sounds like a bug.  Thanks for posting.  We will look into this.
