### ISSUE TITLE
Cannot upload new map to the cloud

### ISSUE THREAD

**Issue by gizem-buss** [lgsvl/simulator#1876]
I am getting the following error while uploading the map I created to the cloud. Can u help me?

![image](https://user-images.githubusercontent.com/71923140/142206337-f96e0ed4-c7b2-460a-9f5c-54b9b8a23c78.png)

**Comment by ertauren** [comment]
Try opening the file as zip file (you can use 7z) and see if there are files inside it ending with "_environment_maix_linux and _environment_main_windows". If they are missing, it means the map is not correctly built.
It should look like this:
![image](https://user-images.githubusercontent.com/40769329/142223772-784c2965-14d9-41a4-b032-5923229384b4.png)

**Comment by EricBoiseLGSVL** [comment]
The reason it is failing is the fact you have scripts in the environment folders.  Please remove from the environment folders before building.  If you want custom scripts, you need to make custom simulator binaries or move to sensors that support dlls
![image](https://user-images.githubusercontent.com/45106230/142263485-3c6e0db1-9ad6-4bff-bd99-555652b5f208.png)

**Comment by EricBoiseLGSVL** [comment]
@gizem-buss @ertauren  is right, the required files are missing from the bundle.  Please include more information so we can solve the issue.
- What version are you on?
- What errors do you have?
- Can you show screen shots of the hierarchy panel and scene view panel of the map to see how you built it?

**Comment by gizem-buss** [comment]
Hello @EricBoiseLGSVL  @ertauren , when I open the map, there are no files ending with "_environment_main_linux" and "_environment_main_windows" in the file. There are no errors or warnings in the log. It finishes building extremely quickly for me as well.
![hata1](https://user-images.githubusercontent.com/71923140/142358936-d91ce96c-7046-4847-a0a1-b2fd150631d7.PNG)
![içerik](https://user-images.githubusercontent.com/71923140/142358945-1e66e369-e533-4b66-af91-96ff35bb9102.PNG)

- 2021.2.2
- I am not getting any error.
- hierarchy panel and scene view panel :
![image](https://user-images.githubusercontent.com/71923140/142359133-bf4c277d-68f1-47b6-8226-af30737ce5ac.png)

**Comment by ertauren** [comment]
This case can be recreated when prefab file is missing. Can you check if it has prefab?
It is 4th picture under "Creating a new map" title in the link below.
https://www.svlsimulator.com/docs/simulation-content/map-annotation/#creating-a-new-map

**Comment by gizem-buss** [comment]
Yes, it worked as you said. Thank you so much @ertauren

**Comment by EricBoiseLGSVL** [comment]
Thanks @ertauren .  Maps still should build without a prefab, we will look into a fix for this.  Thanks for posting all.
