### ISSUE TITLE
How to add objects to the scenario?

### ISSUE THREAD

**Issue by tianyunzhe** [lgsvl/simulator#1881]
Hi Team,

I want to add some obstacles (e.g., traffic corn, box, big rock ...) to the map. Could you provide me some relevant tutorial to achieve this goal?

The effect is as follows.

![图片](https://user-images.githubusercontent.com/49242689/142584559-b5437b0c-4596-4daf-919b-ed46d62e4788.png)

Many thanks!

**Comment by kamkolak-lge** [comment]
Depending on the exact use case, you have multiple options:
1. Use one of the existing maps and spawn obstacles using [Controllable Plugins](https://www.svlsimulator.com/docs/plugins/controllable-plugins/). This would have to be done using [Python API](https://www.svlsimulator.com/docs/python-api/python-api/), and one of the examples with traffic cones can be found in the [quickstart script](https://github.com/lgsvl/PythonAPI/blob/master/quickstart/28-control-traffic-cone.py) in Python API repository. This approach will probably be the best if you want to test multiple different obstacle setups easily.
2. Clone repository with the map you're interested in and modify it according to your needs in Unity editor. [SingleLaneRoad](https://github.com/lgsvl/SingleLaneRoad) repository is publicly available. You can learn more on how to edit (or create new) maps [here](https://www.svlsimulator.com/docs/simulation-content/add-new-map/). Environment on the image that you posted was most likely created this way.
3. You could look into [Visual Scenario Editor](https://www.svlsimulator.com/docs/visual-scenario-editor/about-vse/) if you're considering using Controllable Plugins, but don't want to use Python API.
