### ISSUE TITLE
How to change Python API's port No

### ISSUE THREAD

**Issue by atsuko-kobajp** [lgsvl/simulator#1883]
My computer's 8181 port has already occupied by another service.
So, I'd like to change port No for Python API (default :8181)  ,  could you tell me how to change it ?

**Comment by ertauren** [comment]
@atsuko-kobajp There is "config.yml" file in same directory with simulator excutable. You can change "api_port" variable inside it.

**Comment by atsuko-kobajp** [comment]
Thank you very much. I found it.
