### ISSUE TITLE
Can we use scripts to control the start and end of the simulation (created by VSE)?

### ISSUE THREAD

**Issue by GabrielZZZ** [lgsvl/simulator#1884]
Hello. 

I wonder can we use scripts (e.g. python or bash) to control the start and end of the simulation on a Linux machine, when running with the Apollo system? Thanks!

P.S. What I mean is not using the API Only template, since I have built the simulation via the VSE.

**Comment by EricBoiseLGSVL** [comment]
Sorry, no this is not supported.  We are working on supporting this but it is still a work in progress.
