### ISSUE TITLE
Question: Did anyone manage to build using the Editor than cmd line?

### ISSUE THREAD

**Issue by MithunKinarullathil** [lgsvl/simulator#189]
I have tried it but apparently Unity doesn't seem to create the files/folders of which the names has been hard coded in to the scrips.  For example: The **scenes list in the menu will be blank** because the **MenuManager script** has reference to a folder named **AssetBundles** which was not created when using the build inside the Editor, even though the build was successful.

**Comment by martins-mozeiko** [comment]
You cannot use Unity default build menu with our simulator. You need to invoke "BuildScript.Build" method that you can currently only do with command-line.

**Comment by MithunKinarullathil** [comment]
@martins-mozeiko Thanks for the reply.
