### ISSUE TITLE
Failed to import openDRIVE map error

### ISSUE THREAD

**Issue by diane416** [lgsvl/simulator#1893]
Hi I'm a newbie in LGSVL and having some issues about importing HD Map in unity.

I'm using Unity version 2020.3.3f - Windows.

I followed this youtube video to do a tutorial on importing hd maps.
And while following this tutorial, I downloaded the LGSVL Single Lane Road and Cube Town Opendrive file(.xodr), 
and clicked the "Import HD Map" button.
>> https://www.youtube.com/watch?v=bZk5kY-YgEM
![2](https://user-images.githubusercontent.com/72661224/143815693-2238dc4f-3ed2-4d2a-b304-8530cf97ca45.PNG)

but I'm having this issue.
![1](https://user-images.githubusercontent.com/72661224/143815391-c47bc1b0-f3c9-4502-970f-bfe5237fc7a0.PNG)

Is there any way to solve this problem?

Thanks.

**Comment by EricBoiseLGSVL** [comment]
![image](https://user-images.githubusercontent.com/45106230/143969219-5682b830-6f74-46df-92cc-4bfd62429db9.png)

These are only for 2020.06 release.  Unity 2020.3.3f1 is for our latest release, 2021.3.  We have all the maps and hdmaps available in the webUI

**Comment by diane416** [comment]
Thanks for your help :)

**Comment by EricBoiseLGSVL** [comment]
Glad to help :)

**Comment by diane416** [comment]
> Glad to help :)

Thanks for you, I successfully uploaded the provided Cubetown hdmap in unity.
I could create hdmap mesh, and this warning popped out.
Does this matter, or can I go forward steps?

![image](https://user-images.githubusercontent.com/72661224/144170533-410651a6-4297-47ad-bb17-f0a8adb55e62.png)

Thanks.

**Comment by EricBoiseLGSVL** [comment]
It prevents you from importing new annotation on top of existing annotation.  Be sure to not have existing MapHolders in scene when importing hdmaps.

The key is that it is a log error.  By order of severity:
Null error/crash - must fix something went really wrong
Exception - the ones we catch, must fix
LogError - Something went wrong and we stopped execution or skipped the logic and it needs resolved
LogWarning - Something didn't work as intended but it's fine
Log - general info
