### ISSUE TITLE
SanFrancisco Map does not match

### ISSUE THREAD

**Issue by AIasd** [lgsvl/simulator#1909]
As mentioned in @1754, it seems that the map mismatch issue still exist for 2021.3.

![image](https://user-images.githubusercontent.com/12670254/145325625-50aad66b-f4fd-4bdc-8253-d7bf6f21b706.png)

Can you confirm this? Or did I miss something?

**Comment by ntutangyun** [comment]
Yeah this is to confirm that I'm facing the same issue..

**Comment by revati-naik** [comment]
We have a fix for San Francisco map coming up soon.

**Comment by daohu527** [comment]
@revati-naik I know LGSVL is out of maintenance now, but pls can you tell me the specific cause of this problem and I will try to fix it
