### ISSUE TITLE
3D Ground Truth Sensor can detect vehicles but not pedestrians (2021.3)

### ISSUE THREAD

**Issue by AIasd** [lgsvl/simulator#1915]
Hi,

I am using 2021.3 and Apollo6.0(modular testing) and encounter an issue of 3D Ground Truth Sensor only being able to detect vehicles but not pedestrians. (I followed the suggestion in #1886 and already set the position of the sensor to (0,0,10).)

![Screenshot from 2021-12-10 23-42-54](https://user-images.githubusercontent.com/12670254/145685378-f09bb391-5d76-4108-9ff2-f3319bd0cedb.png)

**Comment by AIasd** [comment]
The pedestrian is generated through Python API so I guess the cause might be similar to #1797 except this is for 3D Ground Truth Sensor rather than 2D Ground Truth Sensor

**Comment by JasonBourne1998** [comment]
> The pedestrian is generated through Python API so I guess the cause might be similar to #1797 except this is for 3D Ground Truth Sensor rather than 2D Ground Truth Sensor

Hi @AIasd , I have also encountered this problem but this is a sunset simulator so it could not be solved by official, do you have a corresponding solution to this problem?
