### ISSUE TITLE
odometry data 

### ISSUE THREAD

**Issue by ErijBNT** [lgsvl/simulator#192]
I am using the LGSVL vehicle. I am trying to do a SLAM and in order to localize the car, I need the odometry data. how can I get it?

**Comment by martins-mozeiko** [comment]
You will need to edit code to publish necessary information.
I suggest to look at existing implementations of IMU or GPS sensors. They are used to collect and publish velocity & acceleration information which probably is very similar to data you need.

**Comment by ErijBNT** [comment]
Where to find this implementation ?

**Comment by martins-mozeiko** [comment]
GPS is in [GpsDevice.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/GpsDevice.cs) file and IMU is in [ImuSensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/ImuSensor.cs) file.
