### ISSUE TITLE
Unable to open Windows link: https://unity3d.com/get-unity/download/archive

### ISSUE THREAD

**Issue by LG-yzz** [lgsvl/simulator#193]
I want to install Unity 2018.2.4. But cannot open Windows link: https://unity3d.com/get-unity/download/archive.
I don't know why .

**Comment by martins-mozeiko** [comment]
That sounds like some network issue. Maybe firewall is blocking this address? Check if you are running any firewall applications, or your home/school/work is using any firewall to block websites.

You can try following direct link to Windows installer: https://download.unity3d.com/download_unity/cb262d9ddeaf/Windows64EditorInstaller/UnitySetup64-2018.2.4f1.exe
