### ISSUE TITLE
Can't start simulator.

### ISSUE THREAD

**Issue by Tengyun-Mo** [lgsvl/simulator#1938]
When I start the simulator, nothing can be downloaded in the simulator window.

**Comment by Tengyun-Mo** [comment]
![Screenshot from 2022-01-06 16-47-29](https://user-images.githubusercontent.com/26378175/148357502-7ae5b614-9e60-43fa-9302-2493c6623b57.png)

**Comment by ntutangyun** [comment]
same here [https://github.com/lgsvl/simulator/issues/1937](https://github.com/lgsvl/simulator/issues/1937)

**Comment by EricBoiseLGSVL** [comment]
I'll check with backend to see if there is an issue. @eagafonovlge ?

**Comment by EricBoiseLGSVL** [comment]
Fixed, thanks for posting
