### ISSUE TITLE
Unable to upload new ego vehicle

### ISSUE THREAD

**Issue by FiIipe** [lgsvl/simulator#1939]
Hi, 

I'm trying to upload a new ego vehicle but I'm getting this error: 

![image](https://user-images.githubusercontent.com/65399295/148381043-8605bc95-9a41-45f6-b2be-48ff6ad69b1c.png)

In the past I was able to upload new vehicles without any problems. 
I tried on firefox and on chrome. 

Cheers, Filipe

**Comment by FiIipe** [comment]
First I tried to update the previous vehicle, it did not work. Then I tried to upload a new vehicle and it also did not work. 

Cheers, 
Filipe

**Comment by EricBoiseLGSVL** [comment]
This was a crash on the backend, fixed and should be working now.  Thanks for posting and reopen if issues persist
