### ISSUE TITLE
 Download LGSVL Simulator based on Windows

### ISSUE THREAD

**Issue by LG-yzz** [lgsvl/simulator#194]
First of all, let me talk about the current basic situation, I am a Chinese users.  I want to do simulation based on apollo and LGSVL Simulator under Windows. At present, I use the version of apollo3.0, check the version information released by LGSVL Simulator, and find that it is matched with apollo3.0 before 2019.3. The new version of the latter Simulator is based on apollo-3.5.
The embarrassing thing is that I found that the official website gave "For Chinese users, you can also view our latest videos here and download our simulator releases here (code: 6k91)." This version only provides the version after Simalato2019.3.
I downloaded the historical 201.03 version link https://github.com/lgsvl/lanefollowing via the release of lgsvl simulator, but the download will fail soon. 
    I would like to ask who can provide the 2019.03 version of the lgsvl simulator or the previous version through the Baidu network disk. Thank you

**Comment by luqiang21** [comment]
@LG-yzz Thank you for using our simulator. Our latest version is supporting both Apollo 3.0 and Apollo 3.5. You just need to select different vehicles inside the simulator to connect with different versions of Apollo. Let me know if you have any other questions.
