### ISSUE TITLE
Map Asset Bundle Import

### ISSUE THREAD

**Issue by JordanCrawfordx** [lgsvl/simulator#1948]
Hello, I'm trying to import a map asset bundle from the LGSVL website, specifically the AutonomousStuff Parking Lot. I attempt to download and install the environment, but it's only a single file, and not the complete asset bundle. Maybe I'm doing it wrong? Thanks.

**Comment by EricBoiseLGSVL** [comment]
Please look to our documentation on how to use map assets.  This link is for the older version of simulator 2020.06 that didn't support cloud assets.  AutonomouStuff map is not open source so the assets themselves are not available.

**Comment by JordanCrawfordx** [comment]
Alright, thanks.
