### ISSUE TITLE
Apollo clustered simulation immediately exits when run: "Simulation skipped running phase"

### ISSUE THREAD

**Issue by josh-wende** [lgsvl/simulator#1949]
Hi,

I'm trying to run a sim with Apollo autopilot distributed over two machines. When I run it, it immediately stops and exits and says "Error on latest run: simulation skipped running phase". The exact same simulation worked before on just my local machine. What might the problem be?

Edit: Looks like the issue might not be Apollo or the cluster. Even when running non-Apollo simulations only on my local machine, some are failing. CubeTown seems to work fine, but trying to run a BorregasAve simulation fails and says "Failed to load environment from 'BorregasAve' asset bundle". These issues are new, I haven't had them before (I have run plenty of sims on BorregasAve without trouble before).

Thanks for any help.

**Comment by josh-wende** [comment]
I don't think I changed anything, but the problem seems to have disappeared today. I would still like to understand why it happened in the first place though, in case it happens again.

**Comment by EricBoiseLGSVL** [comment]
It might have been a back-end failure.  Please open this again if you find more details.
