### ISSUE TITLE
How to watch the parameters of the vehicle?

### ISSUE THREAD

**Issue by GooVincent** [lgsvl/simulator#1951]
Hello guys,

Please anyone know how to watch the parameters of the vehicle like LinkonMkz2017, I mean those params like length, width, height, 
max_rpm, mass, etc.

I tried to import the simulator source code in unity but did not find any responsible info of the vehicle kinetics params

Thanks.

**Comment by JeyP4** [comment]
Clone the [Jaguar](https://github.com/lgsvl/Jaguar2015XE) repo and look at the prefab.

**Comment by EricBoiseLGSVL** [comment]
The components you need are the RigidBody and the VehicleSMI.cs class
