### ISSUE TITLE
How to place visual markers on map ? ROS | python | ubuntu

### ISSUE THREAD

**Issue by JeyP4** [lgsvl/simulator#1952]
Hello I am using LGSVL binary file on Linux with ros1bridge.

I am curious to know if there is any way to place waypoint markers on roads. Of course with no collision effect.
Markers can be discrete or continuous. E,g Chain of objects on the road or lane marking printed on the road.

I mostly use Cubetown map.

**Comment by EricBoiseLGSVL** [comment]
You can create a controllable in the unity editor and use it as a marker

**Comment by JeyP4** [comment]
I used Bézier Path Creator + Line renderer in unity source code, issue solved.
