### ISSUE TITLE
Perception in rainy scenario

### ISSUE THREAD

**Issue by dongyy1148** [lgsvl/simulator#196]
System information
    OS Platform and Distribution (Ubuntu 16.04):
    Connected with Apollo 3.5:

I try to change the weather to be rainy and dark to do the simulation, but the Lidar pointcloud is the same as in the no rainy scenario. It seems that rain doesn't influence the perception and path planning.

![](https://user-images.githubusercontent.com/43221681/59163062-90911e80-8ac9-11e9-9e2f-4ec24512de82.png)

**Comment by martins-mozeiko** [comment]
That is right. In current implementation lidar is not affected by rain. Currently rain is purely visual effect for cameras.

**Comment by dongyy1148** [comment]
Got it. Thanks!

**Comment by berkerlogoglu** [comment]
do you plan to add the effect of rain on lidar returns in the upcoming releases?

**Comment by martins-mozeiko** [comment]
We would like to have it, but currently we do not have plans for it.
