### ISSUE TITLE
How to run Jaguar vehicle in unity scene with arrow keys?

### ISSUE THREAD

**Issue by JeyP4** [lgsvl/simulator#1967]
Hello
I am trying to customize vehicle dynamics with the help of my previous following post.
[Vehicle physics pro (VPP) vehicle import?
](https://github.com/lgsvl/simulator/issues/1959)
It will be useful if I can run the vehicle on a simple plane in a unity scene with arrow keys for debugging.
Is it possible, how?

![image](https://user-images.githubusercontent.com/44414900/150636495-ca49341f-2c1f-410c-8fc9-fcb57875abd3.png)

**Comment by EricBoiseLGSVL** [comment]
Create a new simple map in external and use development settings option in Simulator -> DevelopmentSettings
This will load a vehicle from the cloud or locally and you can assign the keyboard control sensor
