### ISSUE TITLE
Simulation spawn error/Runtime error 

### ISSUE THREAD

**Issue by JordanCrawfordx** [lgsvl/simulator#1975]
For some reason, the console prints out _"No valid spawn points were found on the Winding_Pond_Straightaway map."_, although I do have a spawn point. Also, the simulation lacks any form of lighting while running as shown in this picture: 

![55054691b6491c3738c0f445a9d41bg7](https://user-images.githubusercontent.com/94921943/151881544-878f7933-7cdc-44fe-a3ab-1ffcf0d7d6b0.jpg)

This is after I made changes to the map annotation, and nothing else was modified.

**Comment by EricBoiseLGSVL** [comment]
Do you have a spawn info class on the spawn point game object? Did you leave a directional light in the scene?  Did you keep all assets in the Environment folder for that scene?  What errors do you have?  Have the console panel docked to the right of the project panel so you can see all logs while running.
