### ISSUE TITLE
Some element in the map are not loaded by Python API 

### ISSUE THREAD

**Issue by momala** [lgsvl/simulator#1977]
I am trying to load a pre-built map into the simulations. While I am using the Wise to create a simulation, It runs and shows the map without a problem But when I use the python API to select that map as the environment, it doesn't show the terrains (vegetation and other objects). [NB: We have a ground mesh but the details are off ground and utilizes the builtin point cloud renderer of svl simulator]
Picture : scene loaded with Wise
![Screenshot from 2022-02-01 14-13-57](https://user-images.githubusercontent.com/57801641/151967720-41a81ab2-e6f7-443d-9d48-6caa7949cee0.png)
Picture: Scene loaded by API
![Screenshot from 2022-02-01 14-16-38](https://user-images.githubusercontent.com/57801641/151967727-b7bd8a22-2ba1-4382-9d58-f686340f6c3f.png)

I am using these line to load the map.
`if sim.current_scene == lgsvl.wise.DefaultAssets.map_taltech:
    sim.reset()
else:
    sim.load(lgsvl.wise.DefaultAssets.map_taltech)`
Do you have any Ideas?

**Comment by EricBoiseLGSVL** [comment]
That seems to be a bug.  It looks like the api code is not loading the pointcloud data.  Look to the loading code for wise in loader and grep the difference in the api command load()

**Comment by momala** [comment]
> Look to the loading code for wise in loader

Thanks for the reply. I couldn't find exactly where the scene loading happens in wise. I am looking this two file:
Web: simulator/Assets/Scripts/Web/Loader.cs
API: simulator/Assets/Scripts/Api/Commands/LoadScene.cs

But I couldn't find where exactly it loads the scene in the web. Could you please give me some clue?

**Comment by EricBoiseLGSVL** [comment]
Loader.cs has the method StartAsync(SimulationData simulation).  This is the way random traffic maps are loaded.
LoadScene.cs is where API maps are loaded.

Internally we moved all loading to API commands but we weren't able to release before sunsetting simulator, sorry.

**Comment by momala** [comment]
> Loader.cs has the method StartAsync(SimulationData simulation). This is the way random traffic maps are loaded. LoadScene.cs is where API maps are loaded.
> 
> Internally we moved all loading to API commands but we weren't able to release before sunsetting simulator, sorry.

Thanks again Eric for your help.
