### ISSUE TITLE
Is it possible to use the SVL generated assets after the sunset?

### ISSUE THREAD

**Issue by sisaha9** [lgsvl/simulator#1978]
I am referring to all the current sensor plugins, racing track maps and the racing vehicles like Dallara IL15 that are currently accessed using WISE

**Comment by EricBoiseLGSVL** [comment]
No those will no longer be available.  You could possibly use cached data but you need to remove WISE dependencies.

**Comment by klaus99815** [comment]
> 这些将不再可用。您可以使用缓存的数据，但需要删除 WISE 依赖项。

Hi,@EricBoiseLGSVL 
Could you provide some suggestions on how to delete wise dependencies?
For example, which script should I focus on?
Thanks in advance!

**Comment by EricBoiseLGSVL** [comment]
Hello, please see here #1994
