### ISSUE TITLE
A little question about Excavator

### ISSUE THREAD

**Issue by Alparslan-Tamer** [lgsvl/simulator#1980]
Hi, I have a question about Excavator. Can I use this simülation for the excavator (I have an excavator with urdf format) because I need pallets and I need to use these pallets for control (Differential Drive). Does this simulation only support the kinematic bicycle model?

Thanks in advance for the answers.

**Comment by EricBoiseLGSVL** [comment]
Yes but you will need to create a new dynamics class.  Just look to VehicleSMI but create what you need for your vehicle and make the bundle with this SMI instead.

**Comment by Alparslan-Tamer** [comment]
thank you for your answer, i will try this.
