### ISSUE TITLE
New ego vehicle not moving

### ISSUE THREAD

**Issue by StepTurtle** [lgsvl/simulator#1982]
Hello, I uploaded my own vehicle model to SVL but I can't control it, it is not moving. When I press the back button, the brake light turns on, so there is no problem with the keyboard layout. Is there any solution for this.
![Screenshot_from_2022-02-09_18-33-17](https://user-images.githubusercontent.com/76053179/153263979-990cf8a5-5f7e-4679-a0f1-02cbed6b4be0.png)

**Comment by EricBoiseLGSVL** [comment]
did you add a keyboard control sensor to the vehicle config?

**Comment by StepTurtle** [comment]
Yes, i did. When i press the back button, i can see red light (break light), so i think keyboard control sensor is ok. Do you have any more idea?

**Comment by EricBoiseLGSVL** [comment]
Can you show how the vehicle is setup in unity?  It might be the VehicleSMI settings or wheel colliders.  I can tell wheel colliders are wrong from the wheels sinking into the ground.

**Comment by StepTurtle** [comment]
![WhatsApp Image 2022-02-10 at 13 41 01](https://user-images.githubusercontent.com/76053179/153392941-471e5ba3-b063-4b1e-8c37-352fb73060ef.jpeg)
![WhatsApp Image 2022-02-10 at 13 41 00](https://user-images.githubusercontent.com/76053179/153392945-ac449269-9464-4d7e-9c4f-16bcdc2ed0ed.jpeg)
![WhatsApp Image 2022-02-10 at 13 40 59](https://user-images.githubusercontent.com/76053179/153392957-677fb0af-d2d3-4f73-9ac4-de4de5909929.jpeg)


Are the pictures I sent enough?

**Comment by EricBoiseLGSVL** [comment]
Yes I can see that in the last image the wheel collider is not aligned with the wheel, it looks good for FL but did you check all of them?  RL looks wrong.  Also make sure all Axles public refs link to the prefab and not a copy.  Other settings look good, Another thing.  Do you have enough room for the wheel in the wheel well?  If the wheel collider is on the wheel well, it may prevent rotation.

**Comment by StepTurtle** [comment]
Sorry for my late feedback, some ill problems. I changed the aligning. I assign the correct colliders to the wheels. My car is moving. Thanks to you. Have a good day.
