### ISSUE TITLE
Is there any plan to publish web-independent version of simulator?

### ISSUE THREAD

**Issue by KOREAN139** [lgsvl/simulator#1984]
As mentioned in this [article](https://www.svlsimulator.com/news/2022-01-20-svl-simulator-sunset), `It may be possible to remove this dependency (e.g. in a fork; see below) and then build and launch a local simulator instance.`, is there any guides to remove dependency of WISE?

**Comment by EricBoiseLGSVL** [comment]
Sorry, no changes will be pushed but, if users look to development settings, the code to run locally is there.  It will need migrated to the other simulator loader classes.
