### ISSUE TITLE
can we upload point cloud (.pcd )file of base_map.bin filereated by Unity  to LGSVL simulator ?

### ISSUE THREAD

**Issue by Addi2020** [lgsvl/simulator#1985]
instead of using builtin maps, can we use our own map that is created by UNITY like base_map.bin file or can we upload point cloud (.pcd )file directly to LGSVL simulator and test it?
If yes, then how can I start it, please help.

**Comment by EricBoiseLGSVL** [comment]
Please see documentation [here](https://www.svlsimulator.com/docs/simulation-content/pointcloud-import/).
