### ISSUE TITLE
The navmesh of sanFrancisco

### ISSUE THREAD

**Issue by JasonBourne1998** [lgsvl/simulator#1986]
We imported sanfrancisco map in unity, but now we can't use the navmesh of the map. Is this the problem of the map itself? And do we need to design that navmesh by ourselves?

**Comment by EricBoiseLGSVL** [comment]
What do you mean imported?  Did you clone the repo?

**Comment by JasonBourne1998** [comment]
Thanks for your reply, we have solved this problem. The reason we could not see it is that we did not turn on the gizmos
mode. 
By the way, could you also explain how to realize **walk_random()** function in the **pythonAPI/Quickstart/15-pedestrian-walk-randomly.py**. We have seen into the code and it uses the **remote.command**:
    _def walk_randomly(self, enable):
        self.remote.command(
            "pedestrian/walk_randomly", {"uid": self.uid, "enable": enable}
        )_
But we don't know the underlying mechanism behind it. For example, which command is this function calling since we can not dig any deeper into this code anymore after this line. In my guessing, is this commands are encapsulated in the .cs script in the unity building process? If not, could you please explain the underlying mechanism?

> What do you mean imported? Did you clone the repo?

**Comment by EricBoiseLGSVL** [comment]
Walk randomly is a api command for pedestrian waypoint mode behavior.  Open the Unity editor and run an api sim with this command.  Then select and pedestrian and look to the behavior assigned at runtime.  The api command classes have this information on the method called.

**Comment by xli149** [comment]
> Walk randomly is a api command for pedestrian waypoint mode behavior. Open the Unity editor and run an api sim with this command. Then select and pedestrian and look to the behavior assigned at runtime. The api command classes have this information on the method called.

Hi Eric. I'm facing the same problem of tracing the way points of pedestrians with running walk_random api in simulator. The problem is that I need to collect the way points from the simulator directly since I have to connect the simulator to Dreamview and need to record the trajectories of each pedestrians in real time. Do you know if there is a way that I can achieve this from the simulator api?

Best Regards
