### ISSUE TITLE
visual editor win32exception

### ISSUE THREAD

**Issue by wannastar** [lgsvl/simulator#1992]
i used svl2021.03 simulator visual editor to create my own scenario, but when i finished my scenario and to simulator, i cannot run my own scenerio. informed win32exception(0x80004005):系统找不到指定文件
![image](https://user-images.githubusercontent.com/42711319/154883322-bc130abb-fb5a-4bca-9e0a-cb89edd865bf.png)

**Comment by EricBoiseLGSVL** [comment]
Do you have docker for windows installed as per our docs [here](https://www.svlsimulator.com/docs/installation-guide/installing-simulator/#docker)?

**Comment by wannastar** [comment]
oh, sorry, i forget this... but after i installed docker desktop and wsl，when i run my own scenariro created by VSE, it started downloading svklcontent/runner/vse and then informed  Error unaothorized authentication required. i wanna ask where to input the sign in info or how to resolve this question
![image](https://user-images.githubusercontent.com/42711319/155692487-d3e16130-302a-4dfe-9fce-7933f30d015b.png)

**Comment by EricBoiseLGSVL** [comment]
are you authenticated on docker for windows?

**Comment by wannastar** [comment]
yeah. Thanks for your advice. I had resolved my problems.
