### ISSUE TITLE
Segmentation shader in the HD/URP rendering

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#1993]
Hello!
In the LG simulator, is there a shader suitable for semantic segmentation in the HD/URP rendering mode？
Thank you!

**Comment by EricBoiseLGSVL** [comment]
HDRP and URP are very different shader wise.  We provide segmentation sensor using edits to HDRP for the Lit shader in Unity [here](https://www.svlsimulator.com/docs/simulation-content/sensors-list/#segmentation-camera).  Is this what you mean?

**Comment by yumianhuli2** [comment]
> 

Yes, Could you plz share all the relative code about semantic segmentation in lgsvl?
Thank you!

**Comment by EricBoiseLGSVL** [comment]
Sensor [here](https://github.com/lgsvl/SegmentationCameraSensor)
Simulator has code to work with the sensor in HDRP and shaders [here](https://github.com/lgsvl/simulator)

**Comment by yumianhuli2** [comment]
> Sensor [here](https://github.com/lgsvl/SegmentationCameraSensor) Simulator has code to work with the sensor in HDRP and shaders [here](https://github.com/lgsvl/simulator)

Thank U！
