### ISSUE TITLE
About suspension of SVL development

### ISSUE THREAD

**Issue by s-tk0524** [lgsvl/simulator#1995]
Hi,
I saw the contents of this URL.（https://www.svlsimulator.com/news/2022-01-20-svl-simulator-sunset/）

・Will we not be able to see this document either?（https://www.svlsimulator.com/docs/）
・Is there any way to run the SVL simulator locally?
Is there any document that can be used as a reference?

Thanks

**Comment by lemketron** [comment]
The documentation web site itself is a github project which you can find (and fork) at https://github.com/lgsvl/svlsimulator.com, and also at [archive.org](https://web.archive.org/web/20220223020915/svlsimulator.com/docs).

Regarding running the simulator locally, you should check out [OSSDC SVL based simulator which doesn't require SVL cloud](https://github.com/lgsvl/simulator/issues/1994).
