### ISSUE TITLE
Unable to run simulation on point cloud file.

### ISSUE THREAD

**Issue by Albertj546** [lgsvl/simulator#1998]
I'm trying to run a simulation on a point cloud as shown in this video
https://www.youtube.com/watch?v=6r7K3-dV1iM
![1](https://user-images.githubusercontent.com/100382759/155611399-47026d03-49c1-401b-9543-810a2c2e17a2.png)
![2](https://user-images.githubusercontent.com/100382759/155611419-14978525-0828-4e00-b994-28ce6a687f36.png)

I followed every step in the video but when I click the play button nothing shows up and it looks like I'm also missing some objects in the hierarchy (Loader, SimulatorManager, Sun, etc)
How do I go about fixing this? 
I'm running this on release-2021.3

**Comment by EricBoiseLGSVL** [comment]
You cannot just hit the play button in the editor in the point cloud scene.  You must create the map and upload to WISE and run from the loader scene or open development settings and connect to the cloud so a vehicle with sensors can spawn.
