### ISSUE TITLE
Can not run rosbridge

### ISSUE THREAD

**Issue by lesun90** [lgsvl/simulator#20]
I follow the steps, but could not run the rosbridge script

```
[rosbridge_websocket.launch] is neither a launch file in package [rosbridge_server] nor is [rosbridge_server] a launch file name
The traceback for the exception was written to the log file
```

**Comment by martins-mozeiko** [comment]
Are you trying to run Apollo?
Please make sure you cloned submodule in ros_pkgs folder correctly.

This is done by using `--recursive` argument to git clone.
If you have cloned without this argument, then you can update submodule with following commands:

```
git submodule init
git submodule update
```

**Comment by lesun90** [comment]
Solved.
Thank you.

**Comment by yangydavid** [comment]
@martins-mozeiko  Hi, I am having the same issue here and I tried the command you gave above but a new error comes up as follows: 
```
fatal: reference is not a tree: 0f70cefca2d517539b0ffbee8524761649c0220b
Unable to checkout '0f70cefca2d517539b0ffbee8524761649c0220b' in submodule path 'ros_pkgs/src/rosbridge_suite'
```
This error also comes out when I tried to clone the submodule given in the instruction.

Thanks!

**Comment by martins-mozeiko** [comment]
It seems we forgot to push update to rosbridge repo. Please try it again, now it is up to date.

**Comment by yangydavid** [comment]
@martins-mozeiko  it works now! thanks!
