### ISSUE TITLE
No SpawnInfo generated when I enter a new Scene 

### ISSUE THREAD

**Issue by llu0120** [lgsvl/simulator#2006]
Hi, 
I confront a problem for no SpawnInfo automatically generated when I open a new scene. 
This is how I open a new scene.
![Screenshot from 2022-03-01 12-16-24](https://user-images.githubusercontent.com/41609738/156216684-30481e1c-d8e2-4ee7-8e38-54f3d08848d2.png)

and I choose the Basic (Built-in) one 
![Screenshot from 2022-03-01 12-16-34](https://user-images.githubusercontent.com/41609738/156216649-a59c4127-a3d8-452e-9a50-7327d85b05a1.png)

And no SpawnInfo is included. Did anyone confront this before? Or maybe how can I add this manually? 

Thanks in advance.

**Comment by jim18324** [comment]
I think you should choose Simulator Environment. Or simply copy and paste from an existing scene and modify it by yourself.

**Comment by llu0120** [comment]
Thanks @jim18324 !
