### ISSUE TITLE
Docker API responded with status code=NotFound

### ISSUE THREAD

**Issue by hailonghu** [lgsvl/simulator#2018]
Running VSE simulation failed, Docker API responded with status code=NotFound, response={"message":"No such image: wise.svlsimulator.com/svlcontent/runner/vse:latest"}
![image](https://user-images.githubusercontent.com/47657410/157200626-0a98e0f3-eb66-4786-ad92-a43410107a83.png)

**Comment by wannastar** [comment]
you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email 18811123155@163.com.

**Comment by hailonghu** [comment]
> you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email [18811123155@163.com](mailto:18811123155@163.com).

Thank you very much, LGSVL is working fine with the docker image you provided now.

**Comment by yangjiale1995** [comment]
> > you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email [18811123155@163.com](mailto:18811123155@163.com).
> 
> Thank you very much, LGSVL is working fine with the docker image you provided now.

I have encountered the same problem. How can I solve it ?  My email is 13324520153@163.com,  ths .

**Comment by abeer93m** [comment]
> python-api docker

Hello, I am facing the same issue. Could you please tell me how you solved it? I would really appreciate that. Thank you!

**Comment by abeer93m** [comment]
> > > you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email [18811123155@163.com](mailto:18811123155@163.com).
> > 
> > 
> > Thank you very much, LGSVL is working fine with the docker image you provided now.
> 
> I have encountered the same problem. How can I solve it ? My email is [13324520153@163.com](mailto:13324520153@163.com), ths .

Hello, did you manage to solve it? Thank you.

**Comment by abeer93m** [comment]
> you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email [18811123155@163.com](mailto:18811123155@163.com).

Hello, I am facing the same issue, could you please provide me with the solution? Thank you so much.

**Comment by wannastar** [comment]
At 2022-05-05 17:12:29, "abeer93m" ***@***.***> wrote:

you failed to download the resources of vse or python-api docker. you can use your hotspot to do this again. if your failed again, your can contact me with my email ***@***.***

Hello, I am facing the same issue, could you please provide me with the solution? Thank you so much.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
vse.tar (274.76M, 2022年5月26日 15:10 到期)
下载
python-api.tar (274.69M, 2022年5月26日 15:16 到期)
下载
