### ISSUE TITLE
Sensor position

### ISSUE THREAD

**Issue by s-tk0524** [lgsvl/simulator#2026]
Hi,
I set the position of Lidar.（picture1）
I'm working in Unity.
However, when I check the position of Lidar in Unity, it is in a different position from the vehicle.(picture2)
Please help me solve the problem.
![図2](https://user-images.githubusercontent.com/82795532/157594336-b06f7e9b-1be3-4eb8-ac60-2830e6ea752c.png)

![図1](https://user-images.githubusercontent.com/82795532/157594299-a308f438-6faa-4ce4-a152-cc2a3d7970e4.png)

**Comment by carTloyal123** [comment]
If I recall correctly, the orientation of the sensors is not computed until startup of the simulation. That being said, you will not be able to see the correct transform in the Unity Editor. Have you checked the actual output of the lidar while running a simulation normally?
