### ISSUE TITLE
cannot open the simulator software

### ISSUE THREAD

**Issue by wannastar** [lgsvl/simulator#2028]
![image](https://user-images.githubusercontent.com/42711319/157795106-44b824f1-7e2d-4bd2-b73f-16c985001f73.png)
who kowns how to solve this problem ? 
this problem happened on 1060 gpu, i don't find this on 2080ti gpu

**Comment by jim18324** [comment]
try this

$ sudo apt remove mesa-vulkan-drivers

**Comment by wannastar** [comment]
I don't had this installed. Maybe the GPU drive was not installed correctly.  Now I changed the GPU  to 2080Ti and installed the driver again can solve this problem.
