### ISSUE TITLE
Map export error

### ISSUE THREAD

**Issue by JordanCrawfordx** [lgsvl/simulator#2038]
I'm trying to create some map annotations upon geometry that I've created, and when I attempt to export it, it prints out this error: _Lanelet2 HD Map export unexpected error: The given key was not present in the dictionary._ I have no other errors, and all lanes have their corresponding boundary lines and parents. Thanks in advance. :)

![image](https://user-images.githubusercontent.com/94921943/159016724-72d999b1-1677-4b24-8123-7827a60fe4c2.png)

**Comment by luqiang21** [comment]
It may because you placed the boundary lines outside of the MapLaneSection. MapLine and corresponding MapLane should be in same location.

**Comment by JordanCrawfordx** [comment]
I fixed it, thanks. :)
