### ISSUE TITLE
Cannot run VSE .json

### ISSUE THREAD

**Issue by ghost** [lgsvl/simulator#2039]
Hello,

I am trying to run simulation using VSE, but I get below error.
![WhatsApp Image 2022-03-14 at 4 00 10 PM](https://user-images.githubusercontent.com/102040839/159311771-b7e73048-86c4-4d9e-86e5-6a21165f2cbe.jpeg)

Could anyone please tell me a solution?
I am using apollo 5.0 it works fine for random traffic.

**Comment by wannastar** [comment]
you need to download the vse docker image firstly. it's a automatic process but you failed because the network problem.

**Comment by ghost** [comment]
So how can I resolve it?

**Comment by wannastar** [comment]
use your hotpots to download it

**Comment by Jorge2091** [comment]
i get the same exact problem. i am using linux, is that a command line, what is hotpots. is there a link to it?

edit: I'm using Ethernet and i would consider my network stable. i am in the uk if that changes anything. how can i download the vse docker image?

**Comment by ghost** [comment]
I think it was hotspot. Just try using your mobile hotspot so as to download vse docker. It downloads automatically as soon as you run vse simulation.
Please do tell me if it works.
As I have computer setup with no wifi, I was not able to apply this solution.
Maybe you can also try using VPN.

**Comment by Jorge2091** [comment]
i also dont have that solution, but i will try by using wire conenction through my phone and see. but i was able to get it working by going into older version of lgsvl. for example the 21.1 is working. i will try newer once i get back.

edit: didnt work, but as i said, previous version did work. 2021.2.2 also works

**Comment by ghost** [comment]
Okay I will check it
