### ISSUE TITLE
Reference for camera distortion.

### ISSUE THREAD

**Issue by peter0617ku** [lgsvl/simulator#2041]
Hi, LGSVL team.

In the simulator's source code, there is a section describing camera distortion. Because part of the code cannot be understood, it is impossible to obtain all the parameters of the camera, including the camera's internal parameters, external parameters, and distortion parameters. The comments in the program contain a URL that appears to describe information about camera distortion or fisheye lenses. Unfortunately, the link has expired. The URL is https://wiki.lgsvl.com/display/AUT/Lens+Distortion. I would like to ask if the LGSVL team can provide this document for my reference.

Thanks in advance to your team.

---

![image](https://user-images.githubusercontent.com/43951316/159838480-27ea99f0-52f4-4bde-8457-98311f657c0a.png)

**Comment by rongguodong** [comment]
You can refer to this paper for meanings of a1-4 and b1-4:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4934233/

**Comment by peter0617ku** [comment]
Wow! Thank you so much. 
Having this paper gave me a better understanding of how camera distortion works in the simulator.

By the way, another issue #1625 explains the calculation of the effective FOV of a "fisheye" camera. May I know the origin of this formula?

`f' = f + 2 * asin(Xi * sin(0.5 * f))`

Thank you for taking the time out of your busy schedule to help!

**Comment by rongguodong** [comment]
I don't know. You can ask the one who provide that formula.

**Comment by peter0617ku** [comment]
OK, thanks for your help!
