### ISSUE TITLE
How to get CAN sensor data from LGSVL and send using CAN hardware

### ISSUE THREAD

**Issue by ghost** [lgsvl/simulator#2048]
Hello,

How can I process CAN data, especially Vehicle speed from CAN sensor and send it through CAN hardware?
Are there any examples available on how to access sensor data from LGSVL?

**Comment by carTloyal123** [comment]
The CAN bus sensor is not a true CAN device but rather a way to get vehicle data through the simulator to your bridge of some kind. You can post process the "CAN" data from the simulator into actual CAN signals, but it does not appear to be made for actual CAN hardware to interact with. For example, if you use a ROS2 bridge then the CAN sensor just publishes normal data to a ROS2 topic which has nothing to do with actual CAN protocol.

**Comment by ghost** [comment]
So, how can I enable the CAN bus sensor? I am using Apollo 5.0 where I tried to enable CAN, but it does not work.
