### ISSUE TITLE
Installing LGSVL on existing Apollo

### ISSUE THREAD

**Issue by Prj1508** [lgsvl/simulator#205]
Hi,

I am trying to launch LGSVL with Apollo, but cannot find bridge.sh file in my system. I have been running Apollo 3.5 already and now want to run bridge.sh file to launch LGSVL with it. The steps outlined here(https://github.com/lgsvl/apollo)  is pulling and cloning apollo fork again. How can I lanuch LGSVL without disturbing my current Apollo setup? In other words, would following the steps in the link overwrite my existing apollo which is on home/apollo? Please let me know

I am using UBUNTU 16.04 on a GPU1070 laptop

Thank you

**Comment by martins-mozeiko** [comment]
To get our CyberBridge working in your custom Apollo, you'll need following at least following commits:
https://github.com/lgsvl/apollo-3.5/commit/faa50665409286db82f0e8f3ed7dd24cf5e1ab7b
https://github.com/lgsvl/apollo-3.5/commit/38c6fad44222ca1cdcdd67676ce30bad4fd331d1
https://github.com/lgsvl/apollo-3.5/commit/a99da75c659fc7aa2bca40c826f6532d02d500ee
https://github.com/lgsvl/apollo-3.5/commit/4bbe29914f79d1c24cc1413bda0313f83663cd74
https://github.com/lgsvl/apollo-3.5/commit/1e9dc5fb2bc01e1b9550af5977d3f07c0fcb1ac8

Not that we did some other changes, some bugfixes and new calibration files for our simulator vehicle. You'll need to check in history what else you need to take: https://github.com/lgsvl/apollo-3.5/commits/simulator
