### ISSUE TITLE
Do I have to use Apollo to use the ros2 bridge?

### ISSUE THREAD

**Issue by SanghyunPark01** [lgsvl/simulator#2060]
Do I have to use Apollo to use the ros2 bridge?

**Comment by carTloyal123** [comment]
No, you can use the ROS2 bridge with any ROS2 autonomous driving stack.

**Comment by SanghyunPark01** [comment]
Oh, I asked the wrong question. Is it possible to use it only by installing the ROS2 Bridge without using the ROS2 autonomous driving stack?

**Comment by carTloyal123** [comment]
Yes you can use the ROS2 bridge without any autonomous driving stack

**Comment by SanghyunPark01** [comment]
Thank you!
