### ISSUE TITLE
How lgsvl generate Pedestrains/NPC in own Environment?

### ISSUE THREAD

**Issue by Fin-Del-Mundo** [lgsvl/simulator#2077]
I can't generate Pedestrains in my own environment now, although use lgsvl github repo's pedestrain component, please send me some solution.

**Comment by alperenbayraktar** [comment]
Make sure you have a NavMesh in your built environment, you could read the docs about creating environments.
Then check if your environment has some pedestrian vector map inside it so they will appear near those places.
Check if your config.yml directs the executable to the right folder where the AssetBundles are.
