### ISSUE TITLE
wise.svlsimulator.com is down

### ISSUE THREAD

**Issue by torgeros** [lgsvl/simulator#2091]
The WISE web user interface is not available right now. While <https://wise.svlsimulator.com/> itself is still up, the login page for example returns `502` or `504` responses, making SVL essentially unusable.

WISE sadly was only supposed to be working until at least 2022-06-30:
https://github.com/lgsvl/simulator/blob/4c342fd39c5eca6ce6538a144f51d5929812e417/README.md?plain=1#L28

The last time I successfully used SVL and WISE was on 2022-08-10 (yesterday).

This Issue can be used to discuss updates on this topic.

**Comment by sixiaixixiya** [comment]
I can't use lgsvl anymore. Is there any way to use it offline. Such good software shouldn't just disappear.

**Comment by H0xC0000005** [comment]
While I understand the decision that LG doesn't maintain this anymore, I would rather say LGSVL already has a community and it is such a legacy that many people use. This down actually at least affects me very much to run simulations and let's trace this more.

**Comment by PamLiam** [comment]
I just know SVL and use it for one week. Please make it WISE online again.

**Comment by eagafonovlge** [comment]
Hey! It's up and running again.

**Comment by sixiaixixiya** [comment]
Hey! Is anybody else met the LGSVL frequently lost links? I guess the server of LGSVL is till not stable!
