### ISSUE TITLE
Unable to sign into SVL Simulator

### ISSUE THREAD

**Issue by PamLiam** [lgsvl/simulator#2093]
Hi
It gives an error at the right bottom of the page saying something is wrong please try later!
this happen couple of days to me. is this just for me or anybody?
here (https://wise.svlsimulator.com/sign-in)

**Comment by sixiaixixiya** [comment]
lgsvl has been down. maybe we cannot use it anymore.

**Comment by PamLiam** [comment]
> lgsvl has been down. maybe we cannot use it anymore.

Please run the server just for 1 month

**Comment by eagafonovlge** [comment]
Hey! It's up and running again.

**Comment by sixiaixixiya** [comment]
yeah! the wise can be used now. who did this for us? it's an excellent job!

**Comment by PamLiam** [comment]
I can Sign in again. Thanks a lot LG
