### ISSUE TITLE
Vehicle automaticly run forward error

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#210]
First I lauched bridge.sh in docker ,then I started the client. The car(apollo3.5) in unity will run forward directly!!! This is amazing, what is the matter?Thanks!

**Comment by martins-mozeiko** [comment]
This is probably same issue as #195. We are still investigating why Apollo 3.5 does this.
Currently it is best to use Apollo 3.0 until this will be fixed.

**Comment by yumianhuli2** [comment]
ok,waiting for you!Thanks!

**Comment by luqiang21** [comment]
Hi @yumianhuli2, we rebased our apollo-3.5 fork with official apollo repo. The control problem is not happening in our team. Please update with our latest [apollo-3.5](https://github.com/lgsvl/apollo-3.5) and pull our latest docker image as well.
