### ISSUE TITLE
Question: Does the simulator support building by Il2cpp instead of mono?

### ISSUE THREAD

**Issue by Balussery** [lgsvl/simulator#212]
Hi,

I have tried this but the executable is not being generated at the end. I want to know if I messed up or you had successfully build the simulator using Il2cpp before.

Thank you.

**Comment by martins-mozeiko** [comment]
We have not tried using IL2CPP backend, but I don't see any reason for it not to work.

If there are no executable at end of the build, can you check output/logfile to see if there are any useful error messages?

**Comment by Balussery** [comment]
Thanks for the replay. I will check and post here.

**Comment by Balussery** [comment]
Apparently IL2CPP is not yet supported in Ubuntu.
