### ISSUE TITLE
Exception: Object reference not set to an instance of an object at @0

### ISSUE THREAD

**Issue by Vourhey** [lgsvl/simulator#213]
I try to launch Duckietown + duckiebot-autoware by my own, but no luck.
The script I use:
```
#!/usr/bin/env python3

import os
import lgsvl

sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)

print("Current Scene = {}".format(sim.current_scene))

# Loads the named map in the connected simulator. The available maps can be found in the Free Roam map selection drop down
if sim.current_scene == "Duckietown":
    sim.reset()
else:
    sim.load("Duckietown")

state = lgsvl.AgentState()
state.velocity = lgsvl.Vector(0, 0, 0)

a = sim.add_agent("duckiebot-autoware", lgsvl.AgentType.EGO, state)

sim.run()
```
That's what I see. But all the examples work perfectly. And I'm able to launch the simulator, choose duckietown and pick duckiebot, but not via the script.
![Screenshot_2019-06-22_18-44-44](https://user-images.githubusercontent.com/709124/59965958-d4e6da80-951d-11e9-9025-28bb1ed98a74.png)

Ubuntu 18.04

Could you help me with it?

**Comment by martins-mozeiko** [comment]
Seems our duckiebot prefab is a bit out of date for using with Api.

You can fix this by adding following fragment of code after line 59 in [AddAgent.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Api/Commands/AddAgent.cs#L59)
```
                if (!body)
                {
                    body = connector.Agent.GetComponentInChildren<Rigidbody>();
                }
```
