### ISSUE TITLE
Cannot connect http://www.svlsimulator.com/ and cannot go online

### ISSUE THREAD

**Issue by betulbayram** [lgsvl/simulator#2130]
Cannot connect http://www.svlsimulator.com/ and  go online so we cannot add new map or assets

**Comment by AlexandrZabolotny** [comment]
I have a similar problem.
![Screenshot from 2023-02-17 12-42-45](https://user-images.githubusercontent.com/61351599/219610192-e96b9b3c-f61a-4a81-af7b-343269de643d.png)
![Screenshot from 2023-02-17 12-45-23](https://user-images.githubusercontent.com/61351599/219610220-29053a11-dca1-45ff-a6da-4a1b05f65f69.png)

**Comment by YuqiHuai** [comment]
https://github.com/lgsvl/simulator/issues/1994
https://github.com/lgsvl/simulator/issues/2071
https://github.com/lgsvl/simulator/issues/2127#issuecomment-1420114500

**Comment by jackdongy** [comment]
I have a similar problem too, Can anyone tell me how to solve this problem, thank you..
