### ISSUE TITLE
How can I editor the source of lgsvl?

### ISSUE THREAD

**Issue by yanbgyukuan** [lgsvl/simulator#215]
My Unity is 2018.2.4f1(Windows 10),My lg-simulator is 2019.05.When I load the scence or prefebs,there is nothing display in Unity Editor。Did I have a Wrong version with Unity Or lgsvl-simulator.

**Comment by martins-mozeiko** [comment]
What do you mean with "nothing" ? Can you show a screenshot?
Maybe camera is pointing wrong direction, can you rotate it?
