### ISSUE TITLE
is there a way to start multi scene within one simulator server ? 

### ISSUE THREAD

**Issue by ZJLi2013** [lgsvl/simulator#216]
there is an issue about [running multi robot](https://github.com/lgsvl/simulator/issues/35), ma maybe similar

**Comment by martins-mozeiko** [comment]
I'm not sure what you mean by "start multi scene". But if you want to add multiple vehicles in same simulation environment - you can do that right now. Just click + button in menu screen where you add vehicles and choose each vehicle & its connection to bridge. Simulator will create all of them once the map loads.

**Comment by ZJLi2013** [comment]
I actually want to make a parallel running of LG simulator.  so one  way, I suppose, is to start one LG simulator server, and connect a few clients(on each client node), and each client to load one scene. 

is it possible ? 

Thanks

**Comment by martins-mozeiko** [comment]
This is currently not possible. Also it would require at lot of resources. Loading scene and simulating multiple clients costs a lot of performance/memory on one machine. It is better to run separate simulations on different machines.

But we are working on new simulator version that later will allow launching simulator instances on different clusters. Basically you will be able to invoke multiple simulations on different machines from one central control page.
