### ISSUE TITLE
ModuleNotFoundError: No module named 'lgsvl'

### ISSUE THREAD

**Issue by dongyy1148** [lgsvl/simulator#220]
Hi LGSVL team,

I used to use python file to do the simulation connected with Apollo, and it works well. However, my system got down a few days ago, and I believe some setting may change. Now, when I run python files again it returns that ModuleNotFoundError: No module named 'lgsvl' even though I did source command. Could you help look at it? Thanks!
![image](https://user-images.githubusercontent.com/43221681/60363523-cb43f380-99b1-11e9-9ff9-b1f7a48a9ce5.png)
![image](https://user-images.githubusercontent.com/43221681/60363541-d72fb580-99b1-11e9-9180-6840dfa86369.png)
And I do have lgsvl package in the folder:
![image](https://user-images.githubusercontent.com/43221681/60363586-f3cbed80-99b1-11e9-9dff-3022ad1ae66f.png)

**Comment by luqiang21** [comment]
@dongyy1148 You can try to reinstall the package again following instructions [here](https://github.com/lgsvl/simulator/tree/master/Api)

**Comment by dongyy1148** [comment]
@luqiang21 Thanks! It works!
