### ISSUE TITLE
Publish traffic lights information

### ISSUE THREAD

**Issue by n1try** [lgsvl/simulator#226]
Is there any plans to implement publishing of ground truth traffic lights information, i.e. position and state (red, yellow, green) to Rosbridge?

**Comment by daviduhm** [comment]
Yes, we are planning to support this feature that will publish ground truth information for traffic lights. At the moment, we are preparing to release a new version of our simulator and all of new features will most likely be added to the new one, which will come later. Please stay tuned!

**Comment by ninjacoder0** [comment]
Do you have any rough dates on new releases?

**Comment by daviduhm** [comment]
We are targeting to release by the *end of July*, but that could possibly be changed. We'll officially announce the exact release date later on soon.
