### ISSUE TITLE
Plans for asynchronous Python API?

### ISSUE THREAD

**Issue by n1try** [lgsvl/simulator#228]
I'd like to know if there is plans to change or extend the current Python API in a way that it becomes asynchronous. What I mean by this is to have – similar to what CARLA does – something like a `tick()` function or a game loop, that gets invoked as a callback every time the simulator renders a new frame. 
This would be helpful to retrieve continuous streams of data from the simulation without having to stop and start it all repeatedly and without having to take the indirection through the rosbridge.

**Comment by martins-mozeiko** [comment]
Yes, in later version we will have ability to advance simulation time only for specific frame count.

Although it will be very slow though, if all you want is to update only one frame. Current API is meant to be synchronous to guarantee determinism. Its main use case will be writing test scenerious which should execute in exactly same way.
