### ISSUE TITLE
MapOrigin coordinate transformation?

### ISSUE THREAD

**Issue by daohu527** [lgsvl/simulator#233]
I have some doubts about MapOrigin. We know that HD maps use the UTM coordinate system. If we want to put the map in Unity, we need to do some processing. For example, if the UTM coordinates (552792, 4182385) are placed directly into the game, then the offset game center is too far away. In fact, I will use (552792, 4182385) as the origin. 
```
(the coordinates in the game) = (the UTM coordinates of the road) - (552792, 4182385)
```
This looks great.
Another process is to convert the UTM's Y axis to the Z axis because the plane coordinate system in the game is X-Z.

Now that we have converted, and the "position" is the car's position in Unity, I have 2 questions about MapOrigin:
1. What does the angle mean?
```
position = Quaternion.Euler(0f, Angle, 0f) * position;
```
2. Why do you need to subtract 50000, will it be added back when calculating?
```
easting = position.x + OriginEasting - 500000;
```

The whole code is below in "MapOrigin.cs":
```
    public void GetNorthingEasting(Vector3 position, out double northing, out double easting)
    {
        position = Quaternion.Euler(0f, Angle, 0f) * position;
        easting = position.x + OriginEasting - 500000;
        northing = position.z + OriginNorthing;
    }
```

**Comment by martins-mozeiko** [comment]
Angle is just an extra thing you an use to rotate map around vertical axis. Sometime maps are created incorrectly aligned to real map. This angle allows to fix this misalignment. If map is created correctly the angle will be 0. In next version of simulator we are removing this angle and requiring map to be rotate correctly.

500000 is subtracted to get false-easting: https://en.wiktionary.org/wiki/false_easting
I think it was needed somewhere at some point. But maybe now we can remove it. I'll check if we can do that later.
