### ISSUE TITLE
Autoware and LGSVL starting 

### ISSUE THREAD

**Issue by HartlD2** [lgsvl/simulator#235]
I will see no map in rViz if I load the example:

started roslaunch server http://localhost:34811/

SUMMARY
========

PARAMETERS
* /rosdistro: kinetic
* /rosversion: 1.12.14

NODES
/
map_to_mobility (tf/static_transform_publisher)
points_map_loader (map_file/points_map_loader)
vector_map_loader (map_file/vector_map_loader)
world_to_map (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00000.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00001.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00002.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00003.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00004.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00005.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00006.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00007.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00008.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00009.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00010.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00011.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00012.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00013.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00014.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00015.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00016.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00017.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00018.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00019.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00020.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00021.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00022.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00023.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00024.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00025.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00026.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00027.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00028.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00029.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00030.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00031.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00032.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00033.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00034.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00035.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00036.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00037.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00038.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00039.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00040.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00041.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00042.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00043.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00044.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00045.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_Environment_00046.pcd
load /home/autoware/shared_dir/autoware-data/data/map/pointcloud_map_sf_portion/DuckieSimulator_SF_ParkedCarHolder_00000.pcd
[ERROR] [1563088897.814781628]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.815366607]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.815736495]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.816075080]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.816392095]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.816704199]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.817023930]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.817336241]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.817666639]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.818002487]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.818333179]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4
[ERROR] [1563088897.818649009]: [createSignalMarkerArray] failed createPoleMarker: 123,123,6.75,0.4

['sh', '-c', '$(rospack find runtime_manager)/../../../.config/rviz/cmd.sh']
pid=712
sched policy=OTHER prio=0
pid=715
sched policy=OTHER prio=0
[ INFO] [1563088960.103131807]: rviz version 1.12.16
[ INFO] [1563088960.103155580]: compiled against Qt version 5.5.1
[ INFO] [1563088960.103160981]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1563088960.855660735]: Stereo is NOT SUPPORTED
[ INFO] [1563088960.855711754]: OpenGl version: 4.6 (GLSL 4.6).

**Comment by martins-mozeiko** [comment]
I think this is same issue as #131. Please try older commits of autoware-data repository to see if smaller map loads in rviz.

**Comment by yangjiongfeng** [comment]
I made the same mistake as you.
How did you solve it?
Where can I download your autoware-data files?

**Comment by martins-mozeiko** [comment]
Did you try 983372cbeb107ea1201509e36c commit? Autoware-data repository is here: https://github.com/lgsvl/autoware-data

**Comment by yangjiongfeng** [comment]
where and How to check commit?

**Comment by martins-mozeiko** [comment]
`git rev-parse HEAD` will show current commit. To get different commit use `git checkout COMMIT_ID` command.
