### ISSUE TITLE
velodyne point is strange.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#25]
![image](https://user-images.githubusercontent.com/10348912/47845632-e5203d00-de08-11e8-92b5-3801e0ebbc35.png)

I tested your simulator and visualize pointcloud from Velodyne Simulation.
I think this pointcloud height is too low.

**Comment by hakuturu583** [comment]
Please watchi this video.
https://www.youtube.com/watch?v=FvqGzCRTpSE

**Comment by hakuturu583** [comment]
I tested your simulator with Autoware and I found that the pointcloud is height is too low, so Autoware's localization algorithm fails.

**Comment by hadiTab** [comment]
I'm closing this issue as it is related to the old LiDAR implementation which has been replaced. To avoid confusion, please open a new issue if similar problems occur with the current implementation of the LiDAR. Thanks.
