### ISSUE TITLE
About creating a new map

### ISSUE THREAD

**Issue by liiiu** [lgsvl/simulator#251]
Hello, LG team
I am currently working on a tool that wants to automate the generation of objects to build new map scenes.
I am very curious about how your map (eg SanFrancisco) was created. Resources, buildings, roads, road boundaries in these scenes.
Are professional artists made through 3d modeling software?
Thank you, look forward to reply

**Comment by daohu527** [comment]
It seems that there is currently no good way to generate maps, thinking that you need maps first, then you can add roads, buildings, traffic lights, etc. I tried to generate maps and models with CityEngine and it looks pretty good.
If you want to generate a hd-map to Apollo / autoware. There is a related discussion here, the general process is
1. Generate a map model and import into Unity
2. Label hdmap with tools
3. Export hdmap

#60 #198
