### ISSUE TITLE
Parking slot for apollo open space planner

### ISSUE THREAD

**Issue by Andrea2202** [lgsvl/simulator#252]
Hi All,
there is a way to add in the map Annotation tool the possibility to create the parking slots for apollo open space planner?

Thanks in advance

**Comment by cyberphysicalrobotics** [comment]
Hi Andrea,

Next version LGSVL Simulator will be released on next week. It includes parking space annotation. Then you can use apollo open space planner after annotating parking space. 

Best

**Comment by Fibonacci43** [comment]
@cyberphysicalrobotics  Hi, Will LGSVL fully support apollo 5.0 in the next version? Is there a adapted apollo 5.0 repository provided with the next simulator?
Thanks in advance for your reply.

**Comment by martins-mozeiko** [comment]
Yes, we will be pushing our modified Apollo 5.0 repository shortly. I believe there were not many changes and 3.5 and 5.0 codebase works exactly same with our simulator.

**Comment by martins-mozeiko** [comment]
New simulator [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) release includes necessary annotations to run Apollo 5.0 open space planner. We've also pushed [Apollo 5.0](https://github.com/lgsvl/apollo-5.0) repository with our modifications.
