### ISSUE TITLE
Why is my car model not on the ground?

### ISSUE THREAD

**Issue by yangjiongfeng** [lgsvl/simulator#253]
Hello Author
I've run   ./simulator and roslaunch rosbridge_server rosbridge_websocket.launch
and then Select “XE_Rigged-autoware”
![选区_055](https://user-images.githubusercontent.com/27730697/61919932-4e913e80-af8a-11e9-9d6d-dc6849e8e8d5.png)
my car model not on the ground.why?
![选区_056](https://user-images.githubusercontent.com/27730697/61919968-72548480-af8a-11e9-8cf1-35df98375ddf.png)

**Comment by martins-mozeiko** [comment]
DuckieDowntown map is meant for small robots - like duckiebot. If you want to use this map please select duckiebot vehicle.

For real car choose a different map, for example, SanFrancisco.

**Comment by yangjiongfeng** [comment]
ok 
Thank you very much.
