### ISSUE TITLE
Apollo fork reinstall error

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/simulator#255]
Due to a problem on my Desktop, I had to remove and reinstall Apollo (LGSVL fork). The simulator establishes connection with rosbridge, given that it runs. I can add waypoints on Dreamview and the simulator follows them. There are two issues, however. 

First, LG SVL 1080 seems to be missing from Dreamview > Tasks. Only EP Rigged, MKZ, SF rigged, and XW rigged are available in the dropdown. 

Second, under Dreamview > Module Controller, Perception toggles off itself. apollo/data/perception.out outputs `apollo/bazel-bin/modules/perception/perception: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`. Something must have gone wrong when reinstalling, even though everything seemed to run fine when reinstalling. 

I'm not sure what libcuda.so.1 is, or how to fix this issue. These all worked fine before removing reinstalling Apollo. I followed the steps in LG SVL Apollo fork github page. 

I'm on Ubuntu 16.04.5 LTS and  GeForce GTX 1080. Thank you!

**Comment by martins-mozeiko** [comment]
I assume you are running apollo inside docker we provide (dev_start/dev_into.sh scripts), right?

Did you install nvidia drivers on your host? You can check if GPU name is printed when you run `nvidia-smi`.

**Comment by hyunjaecho94** [comment]
@martins-mozeiko Yes, I am running apollo inside the docker. Here's the output of` nvidia-smi`, which prints the name of the GPU. 

![nvidia-smi](https://user-images.githubusercontent.com/10676339/62144905-91238580-b2c0-11e9-9426-fff83c69c305.png)
