### ISSUE TITLE
Car crashes into sidewalk

### ISSUE THREAD

**Issue by Prj1508** [lgsvl/simulator#257]
I am simulating the car following a route request. The car drives fine up to some time and later crashes into sidewalk. Here is the snapshot

![Screenshot from 2019-07-30 21-35-48](https://user-images.githubusercontent.com/48227055/62177443-ee482700-b312-11e9-81bc-746321ab635e.png)
I would like to know,
1. How to debug what went wrong exactly at the instant the car went off course
2. I am trying to recreate this scenario, but dont want to do from scratchHow can I reinitialize the car to initial position and let Apollo drive from the beginning. 

thanks

**Comment by martins-mozeiko** [comment]
One issue could be that the framerate of simulator is very low. In such case Apollo won't receive information frequently enough. We have seen that Apollo stops driving straight if framerate is around 20 or lower.

If you are using Apollo 3.5 make sure you have updated it to latest code we have on our github. Initial Apollo 3.5 code had some bugs where control module stopped sending correct data. This was fixed later on Apollo side and we rebased our fork to include this fix.

In simulator you can press F5 to save current vehicle position, then F9 to reset to last saved position.
