### ISSUE TITLE
Where to Set up Keyboard to Control car ？

### ISSUE THREAD

**Issue by yangjiongfeng** [lgsvl/simulator#260]
Hello Author.
Why can you control the car by pressing the keyboard forward?
Where to Set up Keyboard to Control car ？
![选区_026](https://user-images.githubusercontent.com/27730697/62339193-b822c700-b50d-11e9-832e-12a6abe0ced3.png)

**Comment by daohu527** [comment]
You can follow [keyboard-shortcuts](https://www.lgsvlsimulator.com/docs/keyboard-shortcuts/) to control the car with keyboard.
Hope that helps.

**Comment by martins-mozeiko** [comment]
If you are creating custom vehicle, then make sure you have `VehicleController`, `CarInputController` and `VehicleInputController` components added to it. Check how default vehicle prefabs have their components set up.
