### ISSUE TITLE
Apollo 3.5 fail to run with LGSVL Simulator 

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#261]
I refer to [Running Apollo 3.5 with LGSVL Simulator](https://www.lgsvlsimulator.com/docs/apollo3-5-instructions/)，Most of them passed.

This is the case：
**1.Used ----./docker/scripts/dev_start.sh**：
..........
ERROR: ld.so: object 'libcaffe2_gpu.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libopencv_core.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Adding group `apollo' (GID 1000) ...
Done.
Adding user `inwinic' ...
Adding new user `inwinic' (1000) with group `apollo' ...
The home directory `/home/inwinic' already exists.  Not copying from `/etc/skel'.
[ OK ] Finished setting up Apollo docker environment. Now you can enter with: 
bash docker/scripts/dev_into.sh
[ OK ] Enjoy!
**2../docker/scripts/dev_into.sh**:
inwinic@in_dev_docker:/apollo$ 
**3. ./apollo.sh build_gpu -j 4**(If I don't add -j 4, I'll get stuck.)
..........
[INFO] Building on x86_64...
[INFO] Building with --jobs=16 --ram_utilization_factor 80 for x86_64
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
INFO: (08-04 14:07:26.998) Found 3690 targets...
INFO: (08-04 14:07:55.458) Elapsed time: 33.656s, Critical Path: 1.82s
modules/perception/proto/perception_camera.proto: warning: Import modules/common/proto/error_code.proto but not used.
INFO: Reading 'startup' options from /apollo/tools/bazel.rc: --batch_cpu_scheduling --host_jvm_args=-XX:-UseParallelGC
WARNING: ignoring LD_PRELOAD in environment.
INFO: (08-04 14:08:03.498) Found 3690 targets...
INFO: (08-04 14:08:03.605) Elapsed time: 2.453s, Critical Path: 0.00s
1============================
[ OK ] Build passed!
[INFO] Took 53 seconds
**4.bootstrap.sh**：
nohup: appending output to 'nohup.out'
nohup: appending output to 'nohup.out'
Launched module monitor.
nohup: appending output to 'nohup.out'
Launched module dreamview.
Dreamview is running at http://localhost:8888
**5.open LGSVL and Start-up simulation**
![2019-08-04 22-13-46 的屏幕截图](https://user-images.githubusercontent.com/37427124/62424715-3dbc9780-b705-11e9-9025-8494fb06a3e1.png)
![2019-08-04 22-17-34 的屏幕截图](https://user-images.githubusercontent.com/37427124/62424748-b28fd180-b705-11e9-98aa-8c1bb05b3322.png)
![2019-08-04 22-17-59 的屏幕截图](https://user-images.githubusercontent.com/37427124/62424753-bd4a6680-b705-11e9-9a7b-3e1437433f92.png)
**6.open Dreamview**
First I did（
Select the XE_Rigged_Apollo3.5 vehicle and San Francisco map in the top right corner.
Open the Module Controller tap (on the left bar).
Enable Localization, Transform, Perception, Traffic Light, Planning, Prediction, Routing, and Control.）, and then I didn't respond.（There's only one big Apollo logo on the screen.，Route Editing Can't Choose）

So I can only click **sim control**
![2019-08-04 22-19-13 的屏幕截图](https://user-images.githubusercontent.com/37427124/62424822-e0c1e100-b706-11e9-8707-68c39fdb3fcd.png)
What's wrong with this? My Bridge are connected.

**Comment by jinxinyang** [comment]
I used A, and then：
![2019-08-05 09-44-26 的屏幕截图](https://user-images.githubusercontent.com/37427124/62433128-bce1b800-b765-11e9-90b3-57b38c3d4249.png)

**Comment by jinxinyang** [comment]
I used ./apollo.sh test, and then：
![2019-08-05 09-44-26 的屏幕截图](https://user-images.githubusercontent.com/37427124/62433147-d1be4b80-b765-11e9-9d47-ceffdb07805b.png)

**Comment by daohu527** [comment]
1. You don't need to open "sim_control", it is used for apollo's own simulation test.
2. I suggest you turn off "sim_control" and confirm that each module is working properly. You can refer to the [picture](https://www.lgsvlsimulator.com/docs/images/full_size_images/apollo3-5.png). If the **localization** module is working, you should be able to see the map and the car display normally.
3. Then we will look at other issues next.

**Comment by jinxinyang** [comment]
I didn't choose  "sim_control", and then enabled  localization, and then（Nothing there?）
![2019-08-05 10-32-24 的屏幕截图](https://user-images.githubusercontent.com/37427124/62434846-a5f29400-b76c-11e9-91f3-b4e7c14ecee7.png)
![2019-08-05 10-34-53 的屏幕截图](https://user-images.githubusercontent.com/37427124/62434857-b0ad2900-b76c-11e9-81d0-d42c5442d4da.png)

**Comment by jinxinyang** [comment]
@daohu527

**Comment by jinxinyang** [comment]
>     1. You don't need to open "sim_control", it is used for apollo's own simulation test.
> 
>     2. I suggest you turn off "sim_control" and confirm that each module is working properly. You can refer to the [picture](https://www.lgsvlsimulator.com/docs/images/full_size_images/apollo3-5.png). If the **localization** module is working, you should be able to see the map and the car display normally.
> 
>     3. Then we will look at other issues next.

Can you help me remotely?
![2019-08-05 10-54-28 的屏幕截图](https://user-images.githubusercontent.com/37427124/62435615-69746780-b76f-11e9-900b-bb3ea13f4756.png)

**Comment by daohu527** [comment]
The localization module is ERROR. Could you check the log in "apollo/data/log" and find the error message?

**Comment by jinxinyang** [comment]
> The localization module is ERROR. Could you check the log in "apollo/data/log" and find the error message?

![2019-08-05 17-25-50 的屏幕截图](https://user-images.githubusercontent.com/37427124/62454052-284b7a00-b7a6-11e9-87ec-8581a258854e.png)
Running build under CPU mode. No GPU is required to run the build.------Is this a mistake?

**Comment by daohu527** [comment]
The GPU currently seems to have no effect on localialtion and may have an impact on perception. You can first look at the log in the "apollo/data/log" directory to confirm the error message of the localialtion module.

**Comment by jinxinyang** [comment]
> The GPU currently seems to have no effect on localialtion and may have an impact on perception. You can first look at the log in the "apollo/data/log" directory to confirm the error message of the localialtion module.
![2019-08-05 19-51-57 的屏幕截图](https://user-images.githubusercontent.com/37427124/62462809-e7119500-b7ba-11e9-9611-18b83e0d96c2.png)

If I don't select "sim_control", nothing will happen when I select "Modules" (and there are no error hints, of course), especially when I select "planning", "Routing" will be cancelled.（Others are mutually exclusive）

**Comment by jinxinyang** [comment]
> The GPU currently seems to have no effect on localialtion and may have an impact on perception. You can first look at the log in the "apollo/data/log" directory to confirm the error message of the localialtion module.

    2019-08-05 19-51-57 的屏幕截图

If I don't select "sim_control", nothing will happen when I select "Modules" (and there are no error hints, of course), especially when I select "planning", "Routing" will be cancelled.（Others are mutually exclusive）

**Comment by jinxinyang** [comment]
> The GPU currently seems to have no effect on localialtion and may have an impact on perception. You can first look at the log in the "apollo/data/log" directory to confirm the error message of the localialtion module.



No problem. I don't know what log to read.

**Comment by daohu527** [comment]
You can use cmd "cd apollo-3.5/data/log" to enter the directory, log files are placed in this directory.

**Comment by jinxinyang** [comment]
> You can use cmd "cd apollo-3.5/data/log" to enter the directory, log files are placed in this directory.
Why did I close the problem... I didn't do anything.

**Comment by jinxinyang** [comment]
> You can use cmd "cd apollo-3.5/data/log" to enter the directory, log files are placed in this directory.

This is the case with log files.

![2019-08-05 20-07-56 的屏幕截图](https://user-images.githubusercontent.com/37427124/62463506-c6e2d580-b7bc-11e9-8dc6-d4190dc7a930.png)

**Comment by martins-mozeiko** [comment]
@jinxinyang 

Velodyne module does not matter. You should NOT enable it. It is used to receive data from real hardware sensor. Which is irrelevant to our simulator. Our simulator published lidar data directly on topic other nodes are listening.

1) do NOT enable SimControl. This is not related to our simulator and is used to generate fake input data.

2) do ENABLE all required modules - **Localization, Perception, Planning, Prediction, Routing, Traffic Light, Transform**. do NOT enable other modules.

3) If any module turns off automatically, check `data/log/MODULE*.log` file. It should contain some kind of error message.

**Comment by martins-mozeiko** [comment]
@jinxinyang what address do you use in Simulator for connecting to Apollo? It should be `localhost:9090` Please check this.

**Comment by jinxinyang** [comment]
> @jinxinyang what address do you use in Simulator for connecting to Apollo? It should be `localhost:9090` Please check this.



According to your help to modify the simulation connection address, I appeared in  “Dreamview”  screen, and according to the tutorial selected “Localization, Transform, Perception, Traffic Light, Planning, Prediction, Routing, and Control.” (click Traffic Light and Perception, automatically cancel)。and “send routing request”（It has a red-line path.）. 
![2019-08-08 10-04-11 的屏幕截图](https://user-images.githubusercontent.com/37427124/62670268-36c3ac80-b9c5-11e9-8e31-2c8eafe01710.png)
![2019-08-08 10-04-17 的屏幕截图](https://user-images.githubusercontent.com/37427124/62670309-607cd380-b9c5-11e9-9b5a-d7f71d49bc69.png)
But there is another problem: after planning the path, the car will not move.
（These things are different from official tutorials.）
![火狐截图_2019-08-08T02-07-27 707Z](https://user-images.githubusercontent.com/37427124/62670354-8904cd80-b9c5-11e9-9b52-95259d1c1676.png)
![火狐截图_2019-08-08T02-07-12 194Z](https://user-images.githubusercontent.com/37427124/62670356-8ace9100-b9c5-11e9-9755-cce3f5366b3a.png)
I also used some detection commands, which turned out to be the case.
![2019-08-08 09-06-55 的屏幕截图](https://user-images.githubusercontent.com/37427124/62670397-ab96e680-b9c5-11e9-914f-0c53dbcbfd8f.png)
Is there anything I lack? Or did I do something wrong?

**Comment by jinxinyang** [comment]
> @jinxinyang what address do you use in Simulator for connecting to Apollo? It should be `localhost:9090` Please check this.

I also looked at "planning.log.....", indicating “Routing is not ready”.（But I'm already “send routing request”.）
![2019-08-08 10-04-25 的屏幕截图](https://user-images.githubusercontent.com/37427124/62670599-60310800-b9c6-11e9-8041-3708b41a6bdc.png)

**Comment by daohu527** [comment]
You need to send a padmessge in apollo. When control module receive the message it will work. You can use "scripts/pad.sh" to send the message, besure to run in the apollo docker.

**Comment by jinxinyang** [comment]
> You need to send a padmessge in apollo. When control module receive the message it will work. You can use "scripts/pad.sh" to send the message, besure to run in the apollo docker.

What padmessge to send, I tried. Then I started “module” first, then used “1 auto drive mode”（at pad_terminal）,Finally, I did “send routing request”.，and the result was still only red line.
![2019-08-08 13-07-20 的屏幕截图](https://user-images.githubusercontent.com/37427124/62676560-ed338b80-b9dd-11e9-9e7a-9d53064a6f58.png)
![2019-08-08 13-07-28 的屏幕截图](https://user-images.githubusercontent.com/37427124/62676562-ee64b880-b9dd-11e9-8071-bb627d95fc37.png)
![2019-08-08 13-11-02 的屏幕截图](https://user-images.githubusercontent.com/37427124/62676609-03414c00-b9de-11e9-91ee-20710189d65b.png)

![2019-08-08 13-07-31 的屏幕截图](https://user-images.githubusercontent.com/37427124/62676566-f02e7c00-b9dd-11e9-969e-2c3e1954f75e.png)

**Comment by jinxinyang** [comment]
I tried, too. First I did “send routing request”., then I did ‘1 auto drive mode’.
. This method is not good either.

**Comment by jinxinyang** [comment]
But there's log information that didn't exist before.（IMU Related Errors,AND，Information after “I0808 13:21:45.543577 18020 class_loader_utility.h:78]registerclass:TrafficLightsPerceptionComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/perception/onboard/component/libperception_component_camera.so”）
![2019-08-08 13-30-24 的屏幕截图](https://user-images.githubusercontent.com/37427124/62677477-0d187e80-b9e1-11e9-9ee7-cc93edab4eb0.png)
![2019-08-08 13-30-44 的屏幕截图](https://user-images.githubusercontent.com/37427124/62677478-0db11500-b9e1-11e9-9a8f-8ab9c4983e3b.png)

**Comment by daohu527** [comment]
Your statement is very contradictory. I have seen the planned path you showed in the picture. I also saw the obstacle informations. But the cyber_monitor does not show the topics as you show in the pic.
The pad message is only valid when the planned path appears (blue wide line). If you don't have a planned path, first make sure there is "/apollo/perception/obstacles" topic receive. If the perception module and the routing module can't work, the planning module can't.
So I suggest that you sort out these ideas, not just try them, which will reduce some errors.

**Comment by jinxinyang** [comment]
> Your statement is very contradictory. I have seen the planned path you showed in the picture. I also saw the obstacle informations. But the cyber_monitor does not show the topics as you show in the pic.
> The pad message is only valid when the planned path appears (blue wide line). If you don't have a planned path, first make sure there is "/apollo/perception/obstacles" topic receive. If the perception module and the routing module can't work, the planning module can't.
> So I suggest that you sort out these ideas, not just try them, which will reduce some errors.

But there is another problem: after planning the path, the car will not move.
（These things are different from official tutorials.）：
There are official tutorials, but I don't have one.
![火狐截图_2019-08-08T02-07-27 707Z](https://user-images.githubusercontent.com/37427124/62680025-d6defd00-b9e8-11e9-9b96-fe1ade957dcd.png)
![火狐截图_2019-08-08T02-07-12 194Z](https://user-images.githubusercontent.com/37427124/62680028-d8a8c080-b9e8-11e9-9cb5-11cc0672f84f.png)

**Comment by jinxinyang** [comment]
This is my picture.
![2019-08-08 10-04-11 的屏幕截图](https://user-images.githubusercontent.com/37427124/62680082-f70ebc00-b9e8-11e9-884b-464d4f2041f9.png)

**Comment by jinxinyang** [comment]
> Your statement is very contradictory. I have seen the planned path you showed in the picture. I also saw the obstacle informations. But the cyber_monitor does not show the topics as you show in the pic.
> The pad message is only valid when the planned path appears (blue wide line). If you don't have a planned path, first make sure there is "/apollo/perception/obstacles" topic receive. If the perception module and the routing module can't work, the planning module can't.
> So I suggest that you sort out these ideas, not just try them, which will reduce some errors.
(I can't have a blue-wide line right now)

First of all, there are problems with module A and module B: but now there are no errors in their logs.
![2019-08-08 14-46-01 的屏幕截图](https://user-images.githubusercontent.com/37427124/62681278-e875d400-b9eb-11e9-8df4-86ff711883ee.png)
![2019-08-08 14-49-31 的屏幕截图](https://user-images.githubusercontent.com/37427124/62681280-e90e6a80-b9eb-11e9-85a0-d3c03380686f.png)
”traffic light“ There must be some problems, but I don't know where I can see the log of ”traffic light“.

**Comment by martins-mozeiko** [comment]
@daohu527 This is first time I hear that you need to run `pad.sh` script to work with LGSVL simulator.
For us it works without running pad.sh script.

@jinxinyang If you are using RTX 2080 then perception and trafficlight modules won't work. Apollo only supports GTX 1080 (or similar GPUs). See my response in #269.
Car will not move because it won't be able to tell detect traffic light color (is it green or red).

**Comment by jinxinyang** [comment]
Thank you. I changed the gtx1070.. I can do it,

**Comment by daohu527** [comment]
I may confuse the pictures, I think he has a planned road.

**Comment by luqiang21** [comment]
@jinxinyang For apollo 3.5, `planning` won't work if `perception`/`prediction` is not working. You can run apollo without `perception` by running fake prediction:

`mainboard -d modules/tools/prediction/fake_prediction/fake_prediction.dag`

With fake prediction, your planning will work, then after you enable control, the car should move.
