### ISSUE TITLE
npc control with random/user-defined speed profile

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/simulator#263]
hey, lg team,

I am trying to simulate npc's abnormal speed behaviour, e.g  define a speed profile with time/location as the variable,  any suggestions ?

**Comment by daohu527** [comment]
Your needs are achieved through "Scenarios". [Here](https://www.lgsvlsimulator.com/docs/api-example-descriptions/) is the documentation for python api, you can use "DriveWaypoint" to define npc tracks. 
Hope this will help.
