### ISSUE TITLE
Which branch should I choose for my git code?

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#264]
![2019-08-05 18-38-06 的屏幕截图](https://user-images.githubusercontent.com/37427124/62458962-ce03e680-b7b0-11e9-81a4-5895bf335e3a.png)

I downloaded master-----  no bridge.sh.

Downloaded  #simulator - - ---- #261 appeared.

**Comment by daohu527** [comment]
Should be the **simulator** branch, this information can be added to the "readme.md"

**Comment by jinxinyang** [comment]
I should run     **./docker/scripts/dev_into.sh**     in Apollo-3.5 in home.
Or you should run **./docker/scripts/dev_into.sh**   in Apollo in /.
![2019-08-05 19-17-03 的屏幕截图](https://user-images.githubusercontent.com/37427124/62460836-a4998980-b7b5-11e9-84f0-d731ec6a9045.png)

**Comment by jinxinyang** [comment]
> Should be the **simulator** branch, this information can be added to the "readme.md"

？？？？Below

**Comment by jinxinyang** [comment]
> Should be the **simulator** branch, this information can be added to the "readme.md"

Below

**Comment by jinxinyang** [comment]
> Should be the **simulator** branch, this information can be added to the "readme.md"

Above

**Comment by daohu527** [comment]
Assuming your code directory is “Apollo-3.5”, execute the command in Apollo-3.5.

**Comment by jinxinyang** [comment]
> Assuming your code directory is “Apollo-3.5”, execute the command in Apollo-3.5.

![2019-08-05 19-33-43 的屏幕截图](https://user-images.githubusercontent.com/37427124/62461699-11ae1e80-b7b8-11e9-876c-4eb5972af4b2.png)
![2019-08-05 19-34-08 的屏幕截图](https://user-images.githubusercontent.com/37427124/62461704-1377e200-b7b8-11e9-81f3-f6e26b30179e.png)
Both places have it.

**Comment by jinxinyang** [comment]
> > Assuming your code directory is “Apollo-3.5”, execute the command in Apollo-3.5.
> 
> ![2019-08-05 19-33-43 的屏幕截图](https://user-images.githubusercontent.com/37427124/62461699-11ae1e80-b7b8-11e9-876c-4eb5972af4b2.png)
> ![2019-08-05 19-34-08 的屏幕截图](https://user-images.githubusercontent.com/37427124/62461704-1377e200-b7b8-11e9-81f3-f6e26b30179e.png)
> Both places have it.


/apollo seems to be generated automatically. (When running ./docker/scripts/dev_start.sh)

**Comment by daohu527** [comment]
Yes, you are right, they are soft links. You can view it by "ls -l"

**Comment by jinxinyang** [comment]
> Yes, you are right, they are soft links. You can view it by "ls -l"

Thanks for your help
