### ISSUE TITLE
Apollo can't connect properly

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#265]
> You can use cmd "cd apollo-3.5/data/log" to enter the directory, log files are placed in this directory.

This is the case with log files.

![2019-08-05 20-07-56 的屏幕截图](https://user-images.githubusercontent.com/37427124/62463506-c6e2d580-b7bc-11e9-8dc6-d4190dc7a930.png)

_Originally posted by @jinxinyang in https://github.com/lgsvl/simulator/issues/261#issuecomment-518207854_

**Comment by jinxinyang** [comment]
Which one do I want to see?（These are all after opening “bridge.sh”.）
![2019-08-05 20-28-29 的屏幕截图](https://user-images.githubusercontent.com/37427124/62464650-c1d35580-b7bf-11e9-8651-4557d1eab159.png)

**Comment by martins-mozeiko** [comment]
Please do not open issues with same question. Let's continue discussion in #261
