### ISSUE TITLE
dreamview.INFO have fail

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#266]
![2019-08-06 13-42-51 的屏幕截图](https://user-images.githubusercontent.com/37427124/62513926-263df580-b850-11e9-9baa-8d0578e4ec1e.png)
![2019-08-06 13-43-50 的屏幕截图](https://user-images.githubusercontent.com/37427124/62513966-440b5a80-b850-11e9-9f6a-87610a14efa5.png)
![2019-08-06 13-43-58 的屏幕截图](https://user-images.githubusercontent.com/37427124/62513968-453c8780-b850-11e9-9db4-b57ff428bfb4.png)
What happened?

**Comment by jinxinyang** [comment]
localization log is:
![2019-08-06 13-45-57 的屏幕截图](https://user-images.githubusercontent.com/37427124/62514094-a6645b00-b850-11e9-885f-48794c886131.png)
![2019-08-06 13-45-43 的屏幕截图](https://user-images.githubusercontent.com/37427124/62514096-a8c6b500-b850-11e9-8823-a1f3b380d92b.png)

**Comment by luqiang21** [comment]
@jinxinyang Can you elaborate more on what is your question? The fail log in dreamview.INFO might not have any effect on your simulation. As long as you can open dreamview in your browser, typically we don't have problems with dreamview. You can follow our README and enable corresponding sensors/modules on simulator/dreamview to do the simulation.

**Comment by jinxinyang** [comment]
> @jinxinyang Can you elaborate more on what is your question? The fail log in dreamview.INFO might not have any effect on your simulation. As long as you can open dreamview in your browser, typically we don't have problems with dreamview. You can follow our README and enable corresponding sensors/modules on simulator/dreamview to do the simulation.

![2019-08-07 08-09-31 的屏幕截图](https://user-images.githubusercontent.com/37427124/62585318-d3fde280-b8ea-11e9-8c0a-b1c4cdcdd5c1.png)
![Uploading 2019-08-07 08-09-35 的屏幕截图.png…]()
![Uploading 2019-08-07 08-09-59 的屏幕截图.png…]()
Nothing will happen.Not on the left.

**Comment by jinxinyang** [comment]
> @jinxinyang Can you elaborate more on what is your question? The fail log in dreamview.INFO might not have any effect on your simulation. As long as you can open dreamview in your browser, typically we don't have problems with dreamview. You can follow our README and enable corresponding sensors/modules on simulator/dreamview to do the simulation.

![2019-08-07 08-09-31 的屏幕截图](https://user-images.githubusercontent.com/37427124/62585406-2f2fd500-b8eb-11e9-8dc4-f46ac1be0b80.png)
![2019-08-07 08-09-35 的屏幕截图](https://user-images.githubusercontent.com/37427124/62585409-30610200-b8eb-11e9-8e73-11386df2b7e1.png)
![2019-08-07 08-09-59 的屏幕截图](https://user-images.githubusercontent.com/37427124/62585411-322ac580-b8eb-11e9-9be6-bea2819ab7f2.png)
Nothing will happen.Not on the left.

**Comment by jinxinyang** [comment]
> @jinxinyang Can you elaborate more on what is your question? The fail log in dreamview.INFO might not have any effect on your simulation. As long as you can open dreamview in your browser, typically we don't have problems with dreamview. You can follow our README and enable corresponding sensors/modules on simulator/dreamview to do the simulation.



1. I did it according to “https://www.lgsvlsimulator.com/docs/apollo3-5-instructions/”. Using “Nvidia Docker”, the graphics card driver is normal.

2."https://github.com/jinxinyang/my_apollo_log" This is my log information.

**Comment by martins-mozeiko** [comment]
Please continue discussion in #261
