### ISSUE TITLE
synchronize agents state between server and client (e.g. get_velocity during sim.run()) 

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/simulator#267]
## to get agent velocity in Python API

```shell 

def set_velocity(npc, speed):
      state = npc.state 
      state.velocity.x =  speed
      npc.state = state 

def get_velocity():
      npcs = sim.get_agents()
      return npcs[0].state.velocity.x  

while True:
    sim.run(0.5)
    set_velocity(npc, -10)
    print("get velocity %4.2f"  % get_velocity())
 
```
while the print output is always 0, looks get_velocity() will only works during sim.run(),

to get npc velocity, has to define a callback funtion during sim.run() ? 

is it works in this way?

**Comment by daohu527** [comment]
1. What is the actual application scenario? Some methods can be asynchronous, but most methods can only be synchronized. For example, NPC travels according to the path.
2. It's like a delay trigger, I don't think it is asynchronous. 
3. In fact, you can get the time of the simulator and then process it on the client. It may only handle the delay. If the server is faster, it may not be able to make up. 

This should be discussed in the scene, but the synchronization function I think is still necessary, long-term operation will inevitably lead to out of sync.

**Comment by david-gwa** [comment]
![iamge](https://www.lgsvlsimulator.com/docs/images/python-api-callbacks.png)

thanks for replying   @daohu527 
I found from python API doc,  looks all run in sequential.  when I asked this issue, I thought there was a way to run python and sim server in parallel, so there is a need to make sure the timestep  is consistent on both python client and sim server side.

**Comment by david-gwa** [comment]
@EricBoiseLGSVL  and @martins-mozeiko   thanks for helping
