### ISSUE TITLE
Apollo.sh test error

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#268]
//modules/dreamview/backend/data_collection_monitor:data_collection_monitor_test FAILED in 36.3s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/dreamview/backend/data_collection_monitor/data_collection_monitor_test/test.log
//modules/dreamview/backend/simulation_world:simulation_world_service_test FAILED in 37.6s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/dreamview/backend/simulation_world/simulation_world_service_test/test.log
//modules/map/pnc_map:cuda_util_test                                     FAILED in 35.6s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/map/pnc_map/cuda_util_test/test.log*************
//modules/map/pnc_map:pnc_map_test                                       FAILED in 0.5s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/map/pnc_map/pnc_map_test/test.log****************
//modules/map/pnc_map:route_segments_test                                FAILED in 0.3s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/map/pnc_map/route_segments_test/test.log****************
//modules/perception/camera/test:camera_app_obstacle_camera_perception_test FAILED in 41.4s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_app_obstacle_camera_perception_test/test.log
***********************
//modules/perception/camera/test:camera_lib_lane_detector_darkscnn_lane_detector_test FAILED in 50.1s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_lane_detector_darkscnn_lane_detector_test/test.log
//modules/perception/camera/test:camera_lib_lane_detector_denseline_lane_detector_test FAILED in 46.2s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_lane_detector_denseline_lane_detector_test/test.log
//modules/perception/camera/test:camera_lib_lane_postprocessor_darkscnn_lane_postprocessor_test FAILED in 136.4s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_lane_postprocessor_darkscnn_lane_postprocessor_test/test.log
//modules/perception/camera/test:camera_lib_lane_postprocessor_denseline_lane_postprocessor_test FAILED in 34.9s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_lane_postprocessor_denseline_lane_postprocessor_test/test.log
//modules/perception/camera/test:camera_lib_obstacle_detector_yolo_yolo_obstacle_detector_test FAILED in 36.0s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_obstacle_detector_yolo_yolo_obstacle_detector_test/test.log
//modules/perception/camera/test:camera_lib_obstacle_transformer_multicue_multicue_obstacle_transformer_test FAILED in 38.8s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/perception/camera/test/camera_lib_obstacle_transformer_multicue_multicue_obstacle_transformer_test/test.log
//modules/planning/integration_tests:garage_test                         FAILED in 2.7s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/planning/integration_tests/garage_test/test.log
//modules/planning/integration_tests:sunnyvale_big_loop_test             FAILED in 2.1s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/planning/integration_tests/sunnyvale_big_loop_test/test.log
//modules/planning/integration_tests:sunnyvale_loop_test                 FAILED in 37.2s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/planning/integration_tests/sunnyvale_loop_test/test.log
//modules/planning/navi/decider:navi_decider_test                        FAILED in 36.0s
  /home/inwinic/.cache/bazel/_bazel_inwinic/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/modules/planning/navi/decider/navi_decider_test/test.log

###############1##################
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DataCollectionMonitorTest
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 05:44:33.220937  8459 global_data.cc:150] [] host ip: 192.168.1.138
W0807 05:44:33.221225  8459 environment.h:33] [] Environment variable [CYBER_PATH] not set, fallback to 
[ RUN      ] DataCollectionMonitorTest.UpdateCollectionProgress
modules/dreamview/backend/data_collection_monitor/data_collection_monitor_test.cc:149: Failure
      Expected: 30.0
      Which is: 30
To be equal to: value
      Which is: 0
[  FAILED  ] DataCollectionMonitorTest.UpdateCollectionProgress (8 ms)
[----------] 1 test from DataCollectionMonitorTest (8 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (10 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DataCollectionMonitorTest.UpdateCollectionProgress

 1 FAILED TEST
**********************************************
**********************************************
#################2###############
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 15 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 15 tests from SimulationWorldServiceTest
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 05:44:33.683285  8489 global_data.cc:150] [] host ip: 192.168.1.138
W0807 05:44:33.683734  8489 environment.h:33] [] Environment variable [CYBER_PATH] not set, fallback to 
[ RUN      ] SimulationWorldServiceTest.UpdateMonitorSuccess
I0807 05:44:33.691051  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.691068  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateMonitorSuccess (39 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateMonitorRemove
I0807 05:44:33.730032  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.730046  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateMonitorRemove (16 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateMonitorTruncate
I0807 05:44:33.746592  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.746603  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateMonitorTruncate (16 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateChassisInfo
I0807 05:44:33.762567  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.762580  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
modules/dreamview/backend/simulation_world/simulation_world_service_test.cc:177: Failure
      Expected: 4.933
      Which is: 4.9329999999999998
To be equal to: car.length()
      Which is: 4.7000000000000002
modules/dreamview/backend/simulation_world/simulation_world_service_test.cc:178: Failure
      Expected: 2.11
      Which is: 2.1099999999999999
To be equal to: car.width()
      Which is: 2.0600000000000001
modules/dreamview/backend/simulation_world/simulation_world_service_test.cc:179: Failure
      Expected: 1.48
To be equal to: car.height()
      Which is: 2.0499999999999998
[  FAILED  ] SimulationWorldServiceTest.UpdateChassisInfo (17 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateLocalization
I0807 05:44:33.779266  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.779279  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateLocalization (16 ms)
[ RUN      ] SimulationWorldServiceTest.UpdatePerceptionObstacles
I0807 05:44:33.795119  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.795130  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdatePerceptionObstacles (13 ms)
[ RUN      ] SimulationWorldServiceTest.UpdatePlanningTrajectory
I0807 05:44:33.808398  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.808408  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdatePlanningTrajectory (13 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateDecision
I0807 05:44:33.821933  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.821949  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateDecision (14 ms)
[ RUN      ] SimulationWorldServiceTest.UpdatePrediction
I0807 05:44:33.835978  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.835992  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdatePrediction (21 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateRouting
I0807 05:44:33.856967  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:33.856986  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
I0807 05:44:33.897414  8489 simulation_world_service.cc:1077] [dreamview] Loaded routing from modules/dreamview/backend/testdata/routing.pb.txt
I0807 05:44:34.897572  8489 simulation_world_service.cc:1082] [dreamview] Published RoutingResponse read from file.
I0807 05:44:34.897794  8489 hdmap.cc:24] [] Loading HDMap: modules/dreamview/backend/testdata/garage.bin ...
I0807 05:44:34.902634  8489 hdmap_util.cc:77] [] Load HDMap success: modules/dreamview/backend/testdata/garage.bin
[       OK ] SimulationWorldServiceTest.UpdateRouting (1048 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateGps
I0807 05:44:34.904433  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:34.904440  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateGps (18 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateControlCommandWithSimpleLonLat
I0807 05:44:34.922821  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:34.922830  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateControlCommandWithSimpleLonLat (19 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateControlCommandWithSimpleMpc
I0807 05:44:34.941126  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:34.941135  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateControlCommandWithSimpleMpc (19 ms)
[ RUN      ] SimulationWorldServiceTest.DownsampleSpeedPointsByInterval
I0807 05:44:34.960424  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:34.960433  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.DownsampleSpeedPointsByInterval (16 ms)
[ RUN      ] SimulationWorldServiceTest.UpdateLatency
I0807 05:44:34.977027  8489 map_service.cc:107] [] Failed to open map meta file: /metaInfo.json
I0807 05:44:34.977035  8489 map_service.cc:144] [] Updated with map: x_offset 0, y_offset 0
[       OK ] SimulationWorldServiceTest.UpdateLatency (12 ms)
[----------] 15 tests from SimulationWorldServiceTest (1299 ms total)

[----------] Global test environment tear-down
[==========] 15 tests from 1 test case ran. (1307 ms total)
[  PASSED  ] 14 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SimulationWorldServiceTest.UpdateChassisInfo

 1 FAILED TEST
**********************************************
**********************************************
#################3###############
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from CudaUtil
[ RUN      ] CudaUtil.CudaNearestSegment
external/bazel_tools/tools/test/test-setup.sh: line 169:  8279 Killed                  "${TEST_PATH}" "$@"

**********************************************
**********************************************
#################4###############
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 9 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 9 tests from PncMapTest
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 05:43:57.340986  8246 pnc_map_test.cc:44] [] map file: modules/map/data/sunnyvale_loop/base_map_test.bin
I0807 05:43:57.341202  8246 hdmap.cc:24] [] Loading HDMap: modules/map/data/sunnyvale_loop/base_map_test.bin ...
E0807 05:43:57.341279  8246 file.cc:90] [] Failed to open file modules/map/data/sunnyvale_loop/base_map_test.bin in binary mode.
E0807 05:43:57.341297  8246 file.cc:64] [] Failed to open file modules/map/data/sunnyvale_loop/base_map_test.bin in text mode.
E0807 05:43:57.341301  8246 pnc_map_test.cc:46] [] Failed to load map: modules/map/data/sunnyvale_loop/base_map_test.bin
F0807 05:43:57.341308  8246 pnc_map_test.cc:47] Check failed: false 
*** Check failure stack trace: ***
external/bazel_tools/tools/test/test-setup.sh: line 169:  8246 Aborted                 (core dumped) "${TEST_PATH}" "$@"
**********************************************
**********************************************
#################5###############
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from RouteSegmentsTest
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 05:43:57.105581  8232 route_segments_test.cc:38] [] map file: modules/map/data/sunnyvale_loop/base_map_test.bin
I0807 05:43:57.105769  8232 hdmap.cc:24] [] Loading HDMap: modules/map/data/sunnyvale_loop/base_map_test.bin ...
E0807 05:43:57.105840  8232 file.cc:90] [] Failed to open file modules/map/data/sunnyvale_loop/base_map_test.bin in binary mode.
E0807 05:43:57.105856  8232 file.cc:64] [] Failed to open file modules/map/data/sunnyvale_loop/base_map_test.bin in text mode.
E0807 05:43:57.105860  8232 route_segments_test.cc:40] [] Failed to load map: modules/map/data/sunnyvale_loop/base_map_test.bin
F0807 05:43:57.105865  8232 route_segments_test.cc:41] Check failed: false 
*** Check failure stack trace: ***
external/bazel_tools/tools/test/test-setup.sh: line 169:  8232 Aborted                 (core dumped) "${TEST_PATH}" "$@"
**********************************************
**********************************************
#################6###############
**********************************************
**********************************************
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
[NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
[NVBLAS] Cannot open default config file 'nvblas.conf'
[NVBLAS] Config parsed
[NVBLAS] CPU Blas library need to be provided
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0807 05:43:57.829054  8223 object_pool_types.cc:33] [] Initialize base object pool (malloc).
Running main() from gmock_main.cc
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from ObstacleCameraPerceptionTest
[ RUN      ] ObstacleCameraPerceptionTest.init_all_test
W0807 05:43:57.848356  8223 environment.h:33] [] Environment variable [MODULE_PATH] not set, fallback to 
W0807 05:43:57.848387  8223 environment.h:33] [] Environment variable [CYBER_PATH] not set, fallback to 
I0807 05:43:57.864781  8223 sensor_manager.cc:97] [] Init sensor_manager success.
I0807 05:43:58.535324  8223 yolo_obstacle_detector.cc:52] [] image_height=1080, image_width=1920, roi_ratio=0.4
I0807 05:43:58.535610  8223 yolo_obstacle_detector.cc:55] [] offset_y=312, height=576, width=1440
I0807 05:43:58.535919  8223 util.cc:60] [] Supported types: 
I0807 05:43:58.536010  8223 util.cc:67] [] 		CAR
I0807 05:43:58.536015  8223 util.cc:67] [] 		VAN
I0807 05:43:58.536017  8223 util.cc:67] [] 		BUS
I0807 05:43:58.536021  8223 util.cc:67] [] 		TRUCK
I0807 05:43:58.536025  8223 util.cc:67] [] 		CYCLIST
I0807 05:43:58.536027  8223 util.cc:67] [] 		TRICYCLIST
I0807 05:43:58.536029  8223 util.cc:67] [] 		PEDESTRIAN
I0807 05:43:58.536031  8223 util.cc:67] [] 		TRAFFICCONE
I0807 05:43:58.536033  8223 util.cc:69] [] 		8 in total.
I0807 05:43:58.536041  8223 util.cc:80] [] Expand nums: 
I0807 05:43:58.536289  8223 util.cc:83] [] 		0
I0807 05:43:58.536295  8223 util.cc:83] [] 		0
I0807 05:43:58.536298  8223 util.cc:83] [] 		0
I0807 05:43:58.536301  8223 util.cc:83] [] 		0
I0807 05:43:58.536304  8223 util.cc:83] [] 		0
I0807 05:43:58.536307  8223 util.cc:83] [] 		0
I0807 05:43:58.536310  8223 util.cc:83] [] 		0.00416667
I0807 05:43:58.536314  8223 util.cc:83] [] 		0.00416667
I0807 05:43:58.536346  8223 yolo_obstacle_detector.cc:127] [] model_type=RTNetInt8
I0807 05:43:58.686946  8223 rt_net.cc:708] [] Erase output: detect1_ori_conf_pred
I0807 05:43:58.686980  8223 rt_net.cc:708] [] Erase output: detect2_cls_pred
I0807 05:43:58.686985  8223 rt_net.cc:708] [] Erase output: detect2_dim_pred
I0807 05:43:58.686990  8223 rt_net.cc:708] [] Erase output: detect2_loc_pred
I0807 05:43:58.686995  8223 rt_net.cc:708] [] Erase output: detect2_obj_pred
I0807 05:43:58.687000  8223 rt_net.cc:708] [] Erase output: detect2_ori_conf_pred
I0807 05:43:58.687005  8223 rt_net.cc:708] [] Erase output: detect2_ori_pred
I0807 05:43:58.687008  8223 rt_net.cc:708] [] Erase output: detect3_cls_pred
I0807 05:43:58.687013  8223 rt_net.cc:708] [] Erase output: detect3_dim_pred
I0807 05:43:58.687018  8223 rt_net.cc:708] [] Erase output: detect3_loc_pred
I0807 05:43:58.687022  8223 rt_net.cc:708] [] Erase output: detect3_obj_pred
I0807 05:43:58.687027  8223 rt_net.cc:708] [] Erase output: detect3_ori_conf_pred
I0807 05:43:58.687031  8223 rt_net.cc:708] [] Erase output: detect3_ori_pred
I0807 05:43:58.687036  8223 rt_net.cc:708] [] Erase output: lof_pred
I0807 05:43:58.687041  8223 rt_net.cc:708] [] Erase output: lor_pred
W0807 05:43:58.687319  8223 rt_net.cc:652] [] Device Not Supports Int8 Mode. Use FP32 Mode.
I0807 05:44:34.522891  8223 rt_net.cc:30] [] cudnnConvolutionLayer.cpp (254) - Cuda Error in execute: 7
I0807 05:44:34.526206  8223 rt_net.cc:30] [] cudnnConvolutionLayer.cpp (254) - Cuda Error in execute: 7
external/bazel_tools/tools/test/test-setup.sh: line 169:  8223 Segmentation fault      (core dumped) "${TEST_PATH}" "$@"

**Comment by jinxinyang** [comment]
I only listed the first six questions.

**Comment by jinxinyang** [comment]
#261 #266 Because of these problems, I will do this test.

**Comment by martins-mozeiko** [comment]
What are the six questions?

If this is about cuda error and you are using RTX 2070 (from #269) then this is not supported by Apollo. It requires GTX 1080 (or different GPU from same generation).

**Comment by jinxinyang** [comment]
> What are the six questions?
> 
> If this is about cuda error and you are using RTX 2070 (from #269) then this is not supported by Apollo. It requires GTX 1080 (or different GPU from same generation).

The above questions were all tested with "./apollo.sh test" . Now I follow Step https://www.lgsvlsimulator.com/docs/apollo3-5-instructions/#launching-apollo-alongside-the-simulator and there is still no map in it.

**Comment by martins-mozeiko** [comment]
Please continue discussion in #261
