### ISSUE TITLE
Is RTX2070 suitable for use?

### ISSUE THREAD

**Issue by jinxinyang** [lgsvl/simulator#269]
![2019-08-07 14-43-47 的屏幕截图](https://user-images.githubusercontent.com/37427124/62600574-cfa0ec00-b921-11e9-8180-61e0137f7225.png)

**Comment by martins-mozeiko** [comment]
This is limitation of Apollo AD stack. They officially support only GTX 1080 generation cards.

You can check issues in Apollo repository where some people claim that they got working RTX cards: https://github.com/ApolloAuto/apollo/issues/6916 and https://github.com/ApolloAuto/apollo/issues/9085

But it is not clear how exactly how to get it working...
You can try asking on their [issue tracker](https://github.com/ApolloAuto/apollo/issues/) for instructions.
