### ISSUE TITLE
[Apollo 3.5] Maximal speed 

### ISSUE THREAD

**Issue by faabdal** [lgsvl/simulator#274]
Is there any way to increase maximal driving speed of Apollo 3.5 ? I have tried some modification of annotations, as well as to modify Apollo 3.5 code but it keeps maximal speed 32 km/h (even on long straight road without intersection and traffic).

Thank you in advance for any suggestion.

**Comment by luqiang21** [comment]
@faabdal, the speed is constrained by both the annotation and the configuration in apollo planning module. You should check planning module and increase the maximum speed there. Currently it is set as 9 m/s.
