### ISSUE TITLE
How to Control ego car through Ros 

### ISSUE THREAD

**Issue by JIXIMD** [lgsvl/simulator#275]
Hi, lg team
  Now, I want to control the  throttle and brake of the ego car through my ros node without the simulator connecting Apollo or autoware.But when the simulator connects to rosbrige, all I see is that rosbrige subscribes to steer_command and publishes control_command, not that it subscribes to control_command(as below).So I would like to ask how my ros node should control the ego car.

![image](https://user-images.githubusercontent.com/38455693/62946453-4bfc6900-be13-11e9-88a8-67e2674f1ff5.png)

Thank you for your help!

**Comment by martins-mozeiko** [comment]
`/simulator/control/command` is used in lanefollowing example to gather training data. Simulator publishes current steering angle and acceleration which is set from steering wheel (we use Logitech G920).

`/lanefollowing/steering_cmd` is topic what simulator listens for getting only steering angle. Lanefollowing example is set up only to accept steering angle, not full control of car.

If you don't want to use Apollo or Autoware you'll need to adjust code to receive steering command in format you want.

**Comment by JIXIMD** [comment]
Thank you for your reply.yeah, I don't want to use Apollo or Autoware  and I just want to implement longitudinal controls (throttle and brake) for the ego car by Ros, but I don't see a simulator subscribes to the corresponding topic.How do I do that?

**Comment by martins-mozeiko** [comment]
You'll need to modify `VehicleController.cs` file to process input from ROS message you have. Check existing code to see how it processes Autoware and Apollo message types.

**Comment by alexkutsan** [comment]
@JIXIMD  did you succeed within this control. I would like to do the same

**Comment by nachoSO** [comment]
I'm also interested in this. Could you please shed light on this?

**Comment by EricBoiseLGSVL** [comment]
@JIXIMD @alexkutsan @nachoSO We now support custom msg types.  We are also updating our Lane Following Tutorial for a future release
