### ISSUE TITLE
Camera sim window doesnt open

### ISSUE THREAD

**Issue by Prj1508** [lgsvl/simulator#277]
I am running LGSLV with Apollo-3.5. In few instances, the camera aspects of LGSLV  that pops up as  a seperate window doesnt come up resulting in not recognizing the traffic signs and hence car gets stuck in traffic lights. Here is a snapshot

![Screenshot from 2019-08-13 17-51-08](https://user-images.githubusercontent.com/48227055/62980314-36c41200-bdf4-11e9-96cb-4c219710287e.png)
Please let me know the resolution

**Comment by martins-mozeiko** [comment]
Window with camera view only opens in perception is working - if it is detecting traffic light.
Please check log file of perception module to see if there are any error messages.
