### ISSUE TITLE
How to change the parameters of the vehicle

### ISSUE THREAD

**Issue by Chizhang1** [lgsvl/simulator#28]
Hi, 
Thanks for your great job. I want to config the vehicle to match the MKZ example in Apollo. In #14 it is mentioned that the configuration of vehicle can be modified in Prefabs/RobotCandidates/XE_Rigged-apollo.prefab, but I did not figure it out. Could you help me figure it out? Thanks in advance.

**Comment by hadiTab** [comment]
@Chizhang1 what exactly do you mean by vehicle configuration? In [#14](https://github.com/lgsvl/simulator/issues/14) @martins-mozeiko explains how to change sensor configurations. Are you looking to modify the sensor configurations to match the MKZ?
The vehicle in the simulator is a model based on a Jaguar XE and you won't be able to easily modify the model to match an MKZ in terms of dimensions, wheel separation, etc.

At the moment we do not have an MKZ model that you would be able to simply switch to. If you need an MKZ the best approach would probably be to find a model online (probably would need to purchase it) and import it into Unity.

**Comment by Chizhang1** [comment]
@hadiTab I am looking for a MKZ model in the simulator. Thanks for your response.

**Comment by martins-mozeiko** [comment]
With new simulator [2019.07-rc1](https://github.com/lgsvl/simulator/releases/tag/2019.07-rc1) release you are able to modify vehicle sensor configuration in WebUI. See documentation [here](https://www.lgsvlsimulator.com/docs/vehicles-tab/#how-to-change-the-configuration-of-a-vehicle) and [here](https://www.lgsvlsimulator.com/docs/sensor-json-options/). If you have any more questions please open new issue.
