### ISSUE TITLE
How do I translate speed and acceleration into throttle and brake to control ego car?

### ISSUE THREAD

**Issue by JIXIMD** [lgsvl/simulator#280]
Hi, lg team
   Is there an API interface to support this transformation?
   If not, what should I do? 
Thank you for your help

**Comment by daohu527** [comment]
What is the application scenario? There is currently no such API available. It seems that PID control can be used. If the speed is lower than expected, the throttle will be added. If it is higher than expected, the throttle will be reduced.

**Comment by JIXIMD** [comment]
yes, it is a PID control。I calculate my pid output, which is an acceleration compensation.But I don't know how to map it to the accelerator and brake of the ego car

**Comment by JIXIMD** [comment]
yes, it is a PID control. I calculate my pid output, which is an acceleration compensation.But I don't know how to map it to the throttle and brake of the ego car

**Comment by JIXIMD** [comment]
Their mapping relationship is nonlinear, can you help to provide their mapping relationship

**Comment by daohu527** [comment]
I don't know about this piece and see if others can help you.

**Comment by cyberphysicalrobotics** [comment]
In apollo control module, there is control calibration table and other compensations by control options.
You can refer this fact to the following files:
/apollo/modules/control/conf/control_conf.pb.txt
/apollo/modules/control/controller/lon_controller.cc
