### ISSUE TITLE
Vector Map Coordinate and Frame

### ISSUE THREAD

**Issue by Felixlxc** [lgsvl/simulator#283]
Hi,

   I'm now using the vector map tool to create a new vector map from a newly created scene. And I would like to use it with Autoware's function. I wonder what is the coordinate of the vector map. How can I change the coordinate of it when generating in the simulator?

**Comment by martins-mozeiko** [comment]
Autoware does not really work with latitude/longitude coordinates outside of Japan.

In our Autoware repository we did quick patch to allow it working with coordinates (0,0). When our simulator exports hd map to Autoware format or provides GPS location to Autoware ROS it always uses (0,0) as origin of map in Unity.
