### ISSUE TITLE
2019-07 version can't be used in ubuntu

### ISSUE THREAD

**Issue by yzl96** [lgsvl/simulator#286]
Hi, I follow your tutorial in https://www.lgsvlsimulator.com/docs/build-instructions.
I'm in step 13: In the Projects tab, verify that the Simulator is using Unity Version 2019.1.10f1 from the dropdown

![Screenshot from 2019-08-20 16-49-38](https://user-images.githubusercontent.com/31734981/63332973-27e8dc80-c36b-11e9-9808-9c8569395322.png)

then I follow step 14 : Double-click the name of the project to launch Unity Editor
but nothing happens.I don't know why, I just follow your step , change nothing.

the gpu is titan x.

**Comment by EricBoiseLGSVL** [comment]
@yzl96 

Hello, let me see if I can help.  I see that you are using Unity Hub 1.4.0.  The current Hub is at 2.1.0.  I'd update that first.  If you have issues after first opening the project, just close Unity and open the project a second time.  Let me know if that helps.

**Comment by martins-mozeiko** [comment]
@yzl96 Please check that you have vulkan libraries installed on your Linux: `sudo apt install libvulkan1`

If that does not help, check the Editor log file at `~/.config/unity3d/Unity/Editor/Editor.log` location for any errors.

**Comment by yzl96** [comment]
@EricBoiseLGSVL ,  I follow the document page's hub download url: https://forum.unity.com/threads/unity-hub-v2-0-0-release.677485/, I use ubuntu16.04, so I download linux version, but it's very strange, the downloaded hub version is 1.4, have try to use the simulator in ubuntu16.04.

**Comment by yzl96** [comment]
![Screenshot from 2019-08-21 12-04-14](https://user-images.githubusercontent.com/31734981/63401955-d3496e00-c40b-11e9-8757-d9d33ded9265.png)

Hi , @EricBoiseLGSVL  I update the hub, but when I press the Add button, and choose the project, then nothing happens?....

**Comment by yzl96** [comment]
@martins-mozeiko , I'm in step 24 https://www.lgsvlsimulator.com/docs/build-instructions.: Open Build... in Unity: Simulator -> Build...
my build.. page is empty:

![Screenshot from 2019-08-21 14-52-54](https://user-images.githubusercontent.com/31734981/63409286-722d9480-c423-11e9-87b4-b8cc4d869eb4.png)

**Comment by EricBoiseLGSVL** [comment]
@yzl96 
You need to clone the Environments and Vehicles repos into the External folder.  This is missing in our documentation and we are updating it soon.

![ExternalFolders](https://user-images.githubusercontent.com/45106230/63455922-99c03500-c402-11e9-9921-4eb4a4c590dc.PNG)

**Comment by martins-mozeiko** [comment]
@yzl96 We do not put environments and vehicles in our main simulator repository to save size. Maps and vehicles can get pretty big in size because of 3d assets and texture.

We have example environments available on our github: [CubeTown](https://github.com/lgsvl/CubeTown) and [ SingleLaneRoad](https://github.com/lgsvl/SingleLaneRoad). And example vehicle [Jaguar2015XE](https://github.com/lgsvl/Jaguar2015XE). We'll be updating these with more eventually.

**Comment by yzl96** [comment]
@martins-mozeiko ， I put the environment as EricBoiseLGSVL, I download CubeTown  SingleLandRoad Jaguar2015XE in github by clone and download.the error is below:
Could not create asset from Assets/External/Vehicles/Jaguar2015XE/Models/Materials/Jaguar2015XETireAlbedo.png: File could not be read
Could not create asset from Assets/External/Environments/CubeTown/Materials/TiledWoodAlbedo.png: File could not be read
Could not create asset from Assets/External/Vehicles/Jaguar2015XE/Models/Materials/Jaguar2015XETireEmissive.png: File could not be read
Could not create asset from Assets/External/Environments/CubeTown/Materials/TiledWoodNormal.png: File could not be read
Could not create asset from Assets/External/Environments/SingleLaneRoad/Models/SingleLaneRoad/Materials/ShalunWhiteSolidFiveDiffuse.png: File could not be read
Could not create asset from Assets/External/Vehicles/Jaguar2015XE/Models/Materials/Jaguar2015XETireNormal.png: File could not be read
Could not create asset from Assets/External/Environments/CubeTown/Materials/HazardStripesAlbedo.jpg: File could not be read
Could not create asset from Assets/External/Vehicles/Jaguar2015XE/Models/Materials/Jaguar2015XETireMask.png: File could not be read
Could not create asset from Assets/External/Vehicles/Jaguar2015XE/Models/Materials/Jaguar2015XEHeadLightLowCookie.png: File could not be read
Attempting to draw without an active shader program?
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
Vulkan: trying to draw without an active vertex or fragment program.
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
Attempting to draw with missing bindings
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
ImportFBX Errors:
Couldn't read file /home/sti/2019-07-simulator/Assets/External/Environments/SingleLaneRoad/Models/SingleLaneRoad/SingleLaneRoad.fbx.
Unexpected file type
ImportFBX Errors:
Couldn't read file /home/sti/2019-07-simulator/Assets/External/Vehicles/Jaguar2015XE/Models/Jaguar2015XEModel.fbx.
Unexpected file type

**Comment by martins-mozeiko** [comment]
Do you have git-lfs installed? We use Git LFS for large binary files to save size when cloning repository.

**Comment by yzl96** [comment]
It works, must git clone ranther than download zip/

**Comment by peter-popov** [comment]
> Hi , @EricBoiseLGSVL I update the hub, but when I press the Add button, and choose the project, then nothing happens?....

Hi, @yzl96. I have the same issue. How did you solve it above?

**Comment by gaohongfein** [comment]
Have you solve these problem？

**Comment by EricBoiseLGSVL** [comment]
Anyone still having issues adding the project to Unity Hub, updating will solve it.

https://unity3d.com/hub/whats-new
