### ISSUE TITLE
Cannot Start Dreamview

### ISSUE THREAD

**Issue by yoyouwen** [lgsvl/simulator#295]
I have downloaded the LGSVL Branch of Apollo 3.0 and build it. Then when I try bash scripts/bootstrap.sh, it gave me feedback:
 
![image](https://user-images.githubusercontent.com/43387865/63455358-a3559700-c41a-11e9-9a0d-5fc5640cc90a.png)

And when I open browser for http://localhost:8888/, I get refuse to connect. 

I get dreamview log as:
![image](https://user-images.githubusercontent.com/43387865/63455891-af8e2400-c41b-11e9-94bf-8a8869b4dfa5.png)

And docker ps as:

![image](https://user-images.githubusercontent.com/43387865/63455949-d2203d00-c41b-11e9-9ddb-c13b80a6df4d.png)

**Comment by martins-mozeiko** [comment]
Can you please check dreamview log file fully - does it have any error messages at bottom of file?

**Comment by yoyouwen** [comment]
Here is the bottom of file:
![image](https://user-images.githubusercontent.com/43387865/63467332-35699980-c433-11e9-8729-41a351b4f1d2.png)
 I think there is no error messages.

**Comment by yoyouwen** [comment]
> Can you please check dreamview log file fully - does it have any error messages at bottom of file?

Here is the bottom of file:
![image](https://user-images.githubusercontent.com/43387865/63467363-487c6980-c433-11e9-81a7-a7d2a50ac3fc.png)

I think there is no error messages.

**Comment by martins-mozeiko** [comment]
This error probably means that there is something else running on port 8888. Check what other processes you have listening on port 8888.
