### ISSUE TITLE
Starting Autoware with LGSVL

### ISSUE THREAD

**Issue by Felixlxc** [lgsvl/simulator#296]
Hi,

   I'm trying to make Autoware work with LGSVL. And I want to load in the my_localization.launch file. And the error in the figure occurs. 
![Screenshot from 2019-08-21 20-28-37](https://user-images.githubusercontent.com/19694699/63477305-8b016e80-c452-11e9-8859-04c05696266d.png)
I wonder if the Autoware has to be the version for LGVSL and use it in docker or is it the issue of GPU? I'm using Autoware v1.12 and build from source.

   Thanks for the help!

**Comment by martins-mozeiko** [comment]
If you are using latest simulator version (2019.07) then it works with Autoware 1.12 official docker without any changes. We have documentation how to run it here: https://www.lgsvlsimulator.com/docs/autoware-instructions/

Error message you have says that this launch file does not exist. Check that it really exists. For Autoware configuration/installation issues I suggest asking questions on their gitlab/forum, as we are no longer maintaining our fork of Autoware - our simulator works with Autoware code without modifications.

**Comment by Felixlxc** [comment]
@martins-mozeiko Thanks for the reply! I find that the simulator has been updated, does it matter if I'm still using an earlier version? 
   And thanks for noticing about gitlab.

**Comment by martins-mozeiko** [comment]
We have not tried earlier simulator version with 1.12. It probably works, but I'm not 100% sure.
Earlier versions we were testing only with out own fork of earlier Autoware version.

**Comment by Felixlxc** [comment]
@martins-mozeiko  Thanks for the information!
