### ISSUE TITLE
Can't start 2019.07

### ISSUE THREAD

**Issue by vatna** [lgsvl/simulator#301]
I've tried to run the Linux binary on Ubuntu 18.04 and I get the screen to select resolution & graphics quality but after clicking ok, I get nothing. It was complaining that I didn't have canberra-gtk-module, so have installed that. Now I don't get any error message. Is there anything else that I need to install?
![Screenshot from 2019-08-23 15-31-57](https://user-images.githubusercontent.com/3112421/63600284-2d3c6600-c5bb-11e9-9d15-696f3de3c295.png)

**Comment by shalinmehtalgsvl** [comment]
Hi @vatna ,

Do you have vulkan installed? These libraries are required on Linux.

`sudo apt install libvulkan1`

**Comment by martins-mozeiko** [comment]
And if that does not help check the log file at `~/.config/unity3d/Editor/Player.log` location for any error messages.

canberra-gtk-module is not needed, this is some internal GTK dependency which is optional. We do not directly use it.

**Comment by vatna** [comment]
Thanks @shalinmehtalgsvl and @martins-mozeiko. It works now that I have vulkan installed.

**Comment by Kailiangdong** [comment]
@vatna What version of nvidia driver you use? I install lastest driver and always black screen after that

**Comment by vatna** [comment]
@Kailiangdong I used the latest 430.26. My issue was resolved by installing vulkan.

**Comment by Kailiangdong** [comment]
Thank you. You install driver with  .run file or install from ppa?

**Comment by vatna** [comment]
@Kailiangdong I use `sudo ubuntu-drivers autoinstall`

**Comment by martins-mozeiko** [comment]
We usually install nvidia drivers on ubuntu from https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa

**Comment by Kailiangdong** [comment]
@vatna @martins-mozeiko  Thank you. Yesterday, when I run lgsvl. The computer always crashes and frozen.  I search it is nvidia driver is not stable on linux.
Do you blacklist nouveau before installing nvidia-drivers？

**Comment by martins-mozeiko** [comment]
I believe you don't need to do that. Installing binary nvidia driver will automatically blacklist nouveau driver by creating blacklist entry in `/etc/modprobe.d` folder.
