### ISSUE TITLE
Go straight into the scene

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#303]
How to skip opening the browser and go straight into the scene to drive the car in apollo5.0  simulator.Because in version 3.5 I was able to directly select various scenarios and enjony driving without connecting apollo algorithm.

**Comment by zelenkovsky** [comment]
You can drive without any AD stack connected. Select any car provided by default and change Bridge Type to __No Bridge__ in Settings. [https://www.lgsvlsimulator.com/docs/vehicles-tab/#how-to-change-the-configuration-of-a-vehicle](https://www.lgsvlsimulator.com/docs/vehicles-tab/#how-to-change-the-configuration-of-a-vehicle)

Make sure that JSON configuration includes [Manual Control](https://www.lgsvlsimulator.com/docs/vehicles-tab/#example-json) sensor attached to the car.

Now you can create a simulation and drive this car around manually.
