### ISSUE TITLE
hdrp issue in ubuntu

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#307]
I found Render pipeline menu in win10, but not in ubuntu.
The HDRP plug-in is also not found in the package manager in ubuntu，but in win10

**Comment by martins-mozeiko** [comment]
What do you mean by "Render pipeline menu" ?
And what do mean when saying "HDRP plug-in"? Do you mean Unity's HDRP package? It is in our github repository: [com.unity.render-pipelines.high-definition](https://github.com/lgsvl/simulator/tree/master/Packages/com.unity.render-pipelines.high-definition) We don't use upstream package as we needed to extend it to work better with our simulator.

**Comment by yumianhuli2** [comment]
> What do you mean by "Render pipeline menu" ?
> And what do mean when saying "HDRP plug-in"? Do you mean Unity's HDRP package? It is in our github repository: [com.unity.render-pipelines.high-definition](https://github.com/lgsvl/simulator/tree/master/Packages/com.unity.render-pipelines.high-definition) We don't use upstream package as we needed to extend it to work better with our simulator.

Thanks! Then how can I use this com.unity.render-pipelines.high-definition  package?

**Comment by martins-mozeiko** [comment]
I'm not sure I understand what are you asking. What do you mean by "use"? Unity uses this package automatically to render everything you see. You can read about HDRP rendering in Unity here: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@5.6/manual/index.html

**Comment by yumianhuli2** [comment]
> I'm not sure I understand what are you asking. What do you mean by "use"? Unity uses this package automatically to render everything you see. You can read about HDRP rendering in Unity here: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@5.6/manual/index.html

Because I did find this package in ubuntu,but found it in WIN10
