### ISSUE TITLE
Video Demo/tutorial on Youtube

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#315]
I downloaded the lastest version of the lgsvl and it seems quite different from the earlier version I had. In particular, I couldn't find the sensor effects and also I find the web interface not so easy to use. Please, would you guys be kind enough to provide a sort of youtube tutorial on getting started, that will be helpful.

**Comment by yumianhuli2** [comment]
Yes,Plz  provide a sort of youtube tutorial on getting started!

**Comment by tolee2019** [comment]
I downloaded the demo of your Python API and ran demo "" 06-save-camera-image ", but I couldn't see the camera on the car. Is this normal or is there a problem?

**Comment by martins-mozeiko** [comment]
Image by default should be saved in image file next to simulator binary. If you did not see it, did you get any errors in python output or simulator log file?

**Comment by tolee2019** [comment]
> Image by default should be saved in image file next to simulator binary. If you did not see it, did you get any errors in python output or simulator log file?

thanks for your reply， I have found the image file.
