### ISSUE TITLE
Enviroments and Vehicles are empty

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#318]
when I Open Build... in Unity: Simulator -> Build... the enviroments and vehicles are empty.And I also can not see BorregasAve.unity scene.
Just download SingleLaneRoad, CubeTown and Jaguar2015XE and put them into unity is enough for this question?But I still can not find something call BorregasAveXX.

**Comment by martins-mozeiko** [comment]
We are not distributing BorregaAve assets as unity scene, it is not open-source. We are currently only providing SingleLaneRoad and CubeTown maps as open-source. But we are considering to add more.

Simulator->Build menu looks for maps in `Assets/External/Environments` folder. So, for example, for CubeTown the build menu will look for `Assets/External/Environments/CubeTown/CubeTown.unity` scene file. You need to place these scenes in specific folder structure for build to work. Basically if you nave NAME map, put it into `Assets/External/Environments/NAME/NAME.unity` location.
