### ISSUE TITLE
Is it possible to use the 3'th party's Vehicle dynamics model - like CarSim ?

### ISSUE THREAD

**Issue by johnny77lee** [lgsvl/simulator#32]
Hi ,

As the title say , Could I use another Vehicle dynamics model it create by 3'th party's tool(ex. CarSim , because the CarSim seems have more accurate model and it has worked on car simulation for many years.) to do simulation ?
If the answer is "No" for now , would you have the plan to add it in the feature?

Thanks

**Comment by hadiTab** [comment]
@johnny77lee at the moment we do not support importing vehicle dynamics models created by 3rd party tools such as CarSim. However, considering that the source is available it should be possible to make modifications for this to happen.
We are considering adding functionality for importing external models. I don't have a timeline on it though, and we may not necessarily support CarSim in particular.
