### ISSUE TITLE
How to Make Maps？

### ISSUE THREAD

**Issue by ax7476** [lgsvl/simulator#322]
I want to make my own maps. What should I do?

**Comment by daohu527** [comment]
Currently only HD map annotation tools, this is the [document](https://www.lgsvlsimulator.com/docs/map-annotation/). If you want to create a map: 
1. Create a game model in Unity (buildings, streets, trees, etc.)
2. Mark the map with HD map annotation tools, generate and export the HD map.

**Comment by EricBoiseLGSVL** [comment]
@ax7476 we will be releasing a step by step tutorial very soon
