### ISSUE TITLE
keyboard can no control the vehicle in version 2019.07

### ISSUE THREAD

**Issue by askariz** [lgsvl/simulator#323]
I refer the instruction from [docs](https://www.lgsvlsimulator.com/docs/) and I can't control the vehicle throught keyboard and can't find the Api both in the source code and release zip file ?

**Comment by daohu527** [comment]
There is a doc about Keyboard shortcuts, [Here](https://www.lgsvlsimulator.com/docs/keyboard-shortcuts/).
Also API is support. [Python API](https://www.lgsvlsimulator.com/docs/python-api/)

**Comment by askariz** [comment]
@daohu527 
yes I following the keyboard shortcuts and ok except vehicle control.

**Comment by daohu527** [comment]
What do you mean the vehicle control?  You can control the car by
```
← ↑ ↓ → - Drive vehicle forward/brake, turn
```
I have tried this is ok.

**Comment by askariz** [comment]
@daohu527 
OK. I Have found out the problem is that I don't add the sensors json format of the vehicle . after that I can control the vehicle now . thx!

**Comment by Francisobiagwu** [comment]
Please where is the python API located? After the new update, the documentation/instruction have some outdated information. It will be nice if someone can follow the instruction provided on the website/github and try to reproduce to fix the errors.
Thanks
