### ISSUE TITLE
No texture in pedestrian

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#33]
In your movie, pedestrian models has textures.
But, in my case, pedestrian models have no textures.
![screenshot from 2018-11-16 16-30-46](https://user-images.githubusercontent.com/10348912/48605171-60fcb680-e9bf-11e8-9c9b-e3c077283e31.png)
![screenshot from 2018-11-16 16-31-10](https://user-images.githubusercontent.com/10348912/48605172-61954d00-e9bf-11e8-85fb-fa0a37c10d0b.png)
![screenshot from 2018-11-16 16-31-32](https://user-images.githubusercontent.com/10348912/48605173-61954d00-e9bf-11e8-82d9-581a572b0022.png)

**Comment by hadiTab** [comment]
@hakuturu583 the pedestrians are still under development and not yet complete. We have released these "skinless" pedestrians as a first step as they may still be useful to some. The pedestrians will be updated in the future with appropriate textures.

**Comment by hadiTab** [comment]
@hakuturu583 we added textures to the pedestrians in the latest release.
I'm closing this issue. Feel free to re-open it if you still have issues. Thanks.
