### ISSUE TITLE
Where is the url to download the map

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#330]
Hello!
    Where is the url to download the map? If I download a map locally, how can I reference it? Can you give me an example?Thanks!

**Comment by martins-mozeiko** [comment]
If you launch simulator binary first time then it will download maps and vehicles automatically. If you want to add maps to when you launch simulator in Editor then you need to get map URL from https://content.lgsvlsimulator.com You do **not** need to download it. Just copy & paste URL when you are adding map. It will download it automatically.

**Comment by shalinmehtalgsvl** [comment]
If you do download it locally (or make your own map) you just need to enter the file path into the URL box.

e.g. `C:\Users\XXX\Desktop\environment_mars`
