### ISSUE TITLE
rosbridge

### ISSUE THREAD

**Issue by SeongHyunBae** [lgsvl/simulator#331]
I execute "roslaunch rosbridge_server rosbridge_websocket.launch" on terminal.

But, rostopic list

/client_count
/connected_clients
/rosout
/rosout_agg

How can I get sensor msgs????

Please help me

**Comment by SeongHyunBae** [comment]
[INFO] [1567268491.573642]: Client connected.  1 clients total.
[INFO] [1567268491.575438]: Client disconnected. 0 clients total.
[INFO] [1567268491.582334]: Client connected.  1 clients total.
[INFO] [1567268491.584277]: Client disconnected. 0 clients total.
[INFO] [1567268491.601169]: Client connected.  1 clients total.
[INFO] [1567268491.603581]: Client disconnected. 0 clients total.
[INFO] [1567268491.606162]: Client connected.  1 clients total.
[INFO] [1567268491.608288]: Client disconnected. 0 clients total.
[INFO] [1567268491.612239]: Client connected.  1 clients total.


connected and disconnected are repeated continuously

**Comment by martins-mozeiko** [comment]
What rosbridge are you running? Is it upstream version or from our fork?
What version of simulator are you connecting to it? What vehicle are you connecting? Does it have correct bridge type set?

**Comment by askariz** [comment]
@SeongHyunBae first you need to correctly setup sensors parameters . please refer [Sensor JSON](https://www.lgsvlsimulator.com/docs/sensor-json-options/)

**Comment by SeongHyunBae** [comment]
It is solved thanks.
