### ISSUE TITLE
Json config of vehicle for Apollo3.0/5.0

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#332]
Hello!Where can I find  json config of vehicle for Apollo3.0/5.0 ?Thanks!

**Comment by daohu527** [comment]
You can find "Sensor JSON Options" json examples here. [Examples ](https://www.lgsvlsimulator.com/docs/sensor-json-options/#examples)

**Comment by martins-mozeiko** [comment]
All necessary sensors for autoware/apollo are shown in our documentation.
For example:
* Apollo 3.0: https://www.lgsvlsimulator.com/docs/apollo-json-example/
* Apollo 5.0: https://www.lgsvlsimulator.com/docs/apollo5-0-json-example/
