### ISSUE TITLE
Error running lgsvl with apollo 5.0 

### ISSUE THREAD

**Issue by chenghanzh** [lgsvl/simulator#334]
Hi, when I start the simulator on the web page, I get the following error message:
![Screen Shot 2019-09-01 at 3 35 01 PM](https://user-images.githubusercontent.com/50680244/64081399-49808700-ccce-11e9-8642-bb2f96837730.png)
And the lgsvl window closes automatically. Does anyone have any idea how to deal with it? Thank you!

**Comment by martins-mozeiko** [comment]
Check the log file in `~/.config/unity3d/Editor/Player.log`. If at the end you see something similar to `Receiving unhandled NULL exception` (and ~ten (Unknown) locations), then this means simulator runs out of memory.

What GPU do you have? For BorregaAve or AutonomouStuff maps we have very high quality textures, so it might happen your GPU runs out of memory. We strongly recommend to run these maps on GPU with at least 8GB of memory. If you are running Apollo on same machine it might require 10GB or more.
