### ISSUE TITLE
[2019.07] any plan for developping a large-scale map like previous san francisco?

### ISSUE THREAD

**Issue by bigsheep2012** [lgsvl/simulator#336]
as the title mentioned. 
The newly released version do have large improvements on various aspects of simulation performance. But the map is relatively small which limit its general practicality.

May I know if there is any plan to release large-scale map? If yes, do we have a time schedule?

Thanks in advance.

**Comment by martins-mozeiko** [comment]
There will be more, larger maps coming. Probably end of this month, maybe next.
