### ISSUE TITLE
About simulator5.0 XXX graph

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#338]
1 How to view the previous depth graph, semantic segmentation graph.. in the simulator5.0 without XX bridge?Thanks!
2 How do I dynamically change the weather, traffic flow,vehicle headlights intensity, etc.in the simulator5.0?

**Comment by martins-mozeiko** [comment]
1. Current binary release does not have this functionality.
But we will be pushing new code this week & RC release that will have functionality to see visualizations dynamically:

![image](https://user-images.githubusercontent.com/39178216/64201531-ca14c400-ce43-11e9-999a-80dbbfb7e8fc.png)

2. To change weather, you need to enable "interactive" checkbox for simulation. Then you'll have sliders to change these settings interactively during simulation.
Changing traffic flow will require editing C# to adjust behaviour of NPCs.
Vehicle headlights can be toggled with H button.

**Comment by yumianhuli2** [comment]
Waiting for update

**Comment by zelenkovsky** [comment]
Update is live. You can download that now.
