### ISSUE TITLE
Customize cyber_bridge

### ISSUE THREAD

**Issue by chenghanzh** [lgsvl/simulator#339]
Hi! I want to pass on customized data via cyber_bridge. Do you know how to do that? Do I need to write a client and send data to the server? Thank you!

**Comment by martins-mozeiko** [comment]
To add new message for CyberRT you'll need to do multiple things in simulator.

1) create .proto file with message description
2) compile .proto file to C# code, instructions are [here](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Cyber/CyberBridge.Initialize.cs#L14).
3) create "Data" class that represents contents of protobuf message - this is abstraction we use to support ROS and Cyber at same time. Example: [CanBusData.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Data/CanBusData.cs)
4) write C# conversion code from this Data class to actual protobuf message. Example in [CyberConversions.cs#L229](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Cyber/CyberConversions.cs#L229)
5) in code where you want to publish message, create IWriter instance for Data class. Example: [CanBusSensor.cs#L28](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Sensors/CanBusSensor.cs#L28)
6) optionally, if you are creating new sensor, add prefab to it to [RuntimeSettings asset](https://github.com/lgsvl/simulator/blob/master/Assets/Resources/RuntimeSettings.asset#L24) to have ability to instantiate this sensor from WebUI
