### ISSUE TITLE
Traffic Simulation Vehicle Suddenly Stops on the road.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#34]
Some Vehicle in your traffic simulation suddenly stops on the Load.
It seems the wheel is still rolling.

![screenshot from 2018-11-16 16-29-43](https://user-images.githubusercontent.com/10348912/48605273-a7521580-e9bf-11e8-8730-9ff70090cc8e.png)

**Comment by moenasrallah** [comment]
This is explained in this closed issue:

https://github.com/lgsvl/simulator/issues/29

**Comment by hadiTab** [comment]
@hakuturu583 we are aware of this issue and are looking into it. It should be resolved in the near future.
As for the invisible stops, they are at the boundary of the map as @moenasrallah mentioned.

**Comment by hadiTab** [comment]
This issue should be fixed with the latest simulator. Closing the issue. Feel free to re-open if the issue persists. Thanks.
