### ISSUE TITLE
ROStopic for control the ego vehicle through autoware

### ISSUE THREAD

**Issue by Felixlxc** [lgsvl/simulator#340]
Hi,
    I'd like to run the waypoint following demo with Autoware. And I noticed that the topic that autoware publish is "/twist_cmd". Is this the topic that simulator listen to so that the vehicle can follow the command?

**Comment by martins-mozeiko** [comment]
Simulator uses `/vehicle_cmd` topic to get control command from Autoware. We do not use /twist_cmd, but same data on /twist_cmd is published to "twist_cmd" member of `/vehicle_cmd` topic.
