### ISSUE TITLE
Have the rosbag package?

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#341]
Is there a rosbag interpretation in your ros release version?
And where is it?Thanks!

**Comment by martins-mozeiko** [comment]
Could you clarify what do you mean by "rosbag interpretation" ? And is "ros release version" you are refering to?

**Comment by yumianhuli2** [comment]
> Could you clarify what do you mean by "rosbag interpretation" ? And is "ros release version" you are refering to?

yes,I mean ros release version including rosbag package?

**Comment by martins-mozeiko** [comment]
We do not have our own ros. You can use whatever ROS version you want as long as you run rosbridge in your ROS environment.
