### ISSUE TITLE
Version correspondence

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#343]
Apollo - 3.0 corresponding ros1.0?
Apollo - 3.5 and Apollo - 5.0 corresponding cyberRT?
what about ros2.0?

**Comment by martins-mozeiko** [comment]
Apollo does not support ROS2, they switched completely to CyberRT.

**Comment by yumianhuli2** [comment]
> Apollo does not support ROS2, they switched completely to CyberRT.

ROS2 just for Autoware?

**Comment by martins-mozeiko** [comment]
Current version of [Autoware](https://gitlab.com/autowarefoundation/autoware.ai) is ROS1.
There is new version in progress called [Autoware.auto](https://gitlab.com/autowarefoundation/autoware.auto) and it will be ROS2 based.
