### ISSUE TITLE
  How to write C #（Script） to get the wheel angle

### ISSUE THREAD

**Issue by yangjiongfeng** [lgsvl/simulator#344]
hello 
![选区_082](https://user-images.githubusercontent.com/27730697/64318945-d5a3ee80-cfed-11e9-95bb-903009a22f5c.png)
I can control the car with vehicle_cmd topic.
now,I want to know the angle of the wheel by rosbridge_server.
  How to write C #（Script） to get the wheel angle in the unity.
like the GpsDevice.cs

![选区_083](https://user-images.githubusercontent.com/27730697/64319314-9e820d00-cfee-11e9-9add-e1a5fcba50e8.png)

**Comment by martins-mozeiko** [comment]
See the following comment that explains what steps you need to do publish extra data: https://github.com/lgsvl/simulator/issues/339#issuecomment-527590350
For ROS it is a bit simpler - in step 2 you should simply write C# class representing your new ROS message. For example check [Ros.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Ros/Messages/Ros.cs) file.

**Comment by yangjiongfeng** [comment]
I didn't find the Ros.cs document.
I want to create a new data type to be transmitted through rosbridge_server.

**Comment by martins-mozeiko** [comment]
If you click on [Ros.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Ros/Messages/Ros.cs) link it will open the file and you'll see the full path to it.
