### ISSUE TITLE
Autoware install documentation

### ISSUE THREAD

**Issue by jonwetherall** [lgsvl/simulator#348]
Does not tell the user to get the shared_dir files

**Comment by hadiTab** [comment]
Thanks, I guess we missed that.
The files are here: https://github.com/lgsvl/autoware-data

Just clone the repo into shared_dir.

**Comment by jonwetherall** [comment]
Hi,

Thanks i worked it out but good to point out as it was confusing.

I still can't get the Autoware to work, not really sure why will have a deeper look at some ponit but had more joy with Apollo 5.0 in the end.

Jon

**Comment by martins-mozeiko** [comment]
We've updated the doc to include this information: https://www.lgsvlsimulator.com/docs/autoware-instructions/#launching-autoware-alongside-lgsvl-simulator
