### ISSUE TITLE
Intersection selection

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#349]
Please, is there any way I can select an intersection of interest, and have camera view of it similar to this?
![intersection1](https://user-images.githubusercontent.com/19335305/64454844-05b8c380-d0ba-11e9-9b2b-ad610c2fce75.jpg)

**Comment by martins-mozeiko** [comment]
If you are using simulator inside Unity Editor then you can select object and press F to focus on it.

In binary build we don't have such functionality, but you can switch camera to "free mode" so it is not attached to car and then position it manually to look at intersection. You do this by pressing `~` key and then use WASD keys for movement while holding down mouse right button. Additionally press `shift` to move faster.
