### ISSUE TITLE
get forward direction of agents

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/simulator#351]
wonder is there an easy way to get the driving forward direction of agents  in Python ?

**Comment by martins-mozeiko** [comment]
`agent.state.transform.rotation` will give you euler angles that represents 3d orientation of agent. You can use it to create 3d transformation matrix - and third row in matrix will be forward vector. There is `helper.transform_to_matrix` function that will calculate this matrix from `agent.state.transform` value.
