### ISSUE TITLE
Web-page Formatting Issue

### ISSUE THREAD

**Issue by moenasrallah** [lgsvl/simulator#352]
**Version**: 2019.09 RC1 Release

The landing page for the simulator and it's other web-pages are stuck like the image attached:

![image](https://user-images.githubusercontent.com/23708715/64623698-6cd6c080-d3b7-11e9-8890-1cd14857d929.png)

**Comment by moenasrallah** [comment]
Issue resolved by clearing my browser cookies.

**Comment by moenasrallah** [comment]
Reopened. Issue is consistent and always needs to have the cookies cleared. Seems to be an issue with the whole logging in process. Before, in 2019.07, it would prompt a proper re-login. With the new version, it shows the above image instead

**Comment by martins-mozeiko** [comment]
Can you try pressing Ctrl+Shift+R to really reload page? This will ignore all cached files from current page (compared to just Ctrl+R refresh).

**Comment by moenasrallah** [comment]
@martins-mozeiko that works as a temporary fix for now. Thank you.
