### ISSUE TITLE
UI Button Causes Temporary Freeze

### ISSUE THREAD

**Issue by moenasrallah** [lgsvl/simulator#353]
The information "i" button on the bottom of a simulation causes the simulator to freeze/crash

Version: 2019.09 RC1

![Screenshot from 2019-09-10 14-58-57](https://user-images.githubusercontent.com/23708715/64642093-90136700-d3db-11e9-93e3-631cbca665e8.png)

**Comment by martins-mozeiko** [comment]
Can you post logfile after this freeze happen?

Depending on what you run, file is in following locations:
For Windows binary: `%APPDATA%\..\LocalLow\LG Silicon Valley Lab\LGSVL Simulator\Player.log`
For Windows Unity Editor: `%APPDATA%\..\Local\Unity\Editor\Editor.log`
For Linux binary: `~/.config/unity3d/Unity/Editor/Editor.log`
for Linux Unity Editor: `~/.config/unity3d/Editor/Player.log`

**Comment by moenasrallah** [comment]
[Editor.log](https://github.com/lgsvl/simulator/files/3597392/Editor.log)

**Comment by moenasrallah** [comment]
It unfroze for a quick second then refroze after a button click.

See image about "Failed to read GPU texture":
![Screenshot from 2019-09-10 15-29-47](https://user-images.githubusercontent.com/23708715/64644134-f13d3980-d3df-11e9-8281-7131d6f2be0c.png)

**Comment by EricBoiseLGSVL** [comment]
@moenasrallah We are looking into this bug and hope to have a fix soon

**Comment by EricBoiseLGSVL** [comment]
@moenasrallah we have a fix for this issue in next release
