### ISSUE TITLE
[2019.07]　　Key Bindings

### ISSUE THREAD

**Issue by obi56** [lgsvl/simulator#357]
Camera Controls and For developer use will work, but Officially supported and Miscellaneous will not work.

The keyboard is not broken, it will work normally with other operations.

Is there a solution to the problem?

Help me

**Comment by obi56** [comment]
I solved it on my own.

**Comment by tecniuf** [comment]
How did you solved it?

**Comment by obi56** [comment]
When I was investigating, I realized that I hadn't tried number 10.In the text box insert in the test simulator in the Instructions to build standalone executable.
