### ISSUE TITLE
Can't simulate some LiDARs which have non linear distributed vertical resolution

### ISSUE THREAD

**Issue by Tomoya-Sato** [lgsvl/simulator#36]
Hi,
I recognize that we can set the vertical angular resolution of upper and lower half of lasers individually.  However, there are some LiDARs which have non linear distributed vertical resolution, for example VLP-32c. With the implementation in LidarSensor.cs, they can't be simulated by simply change public variables (upperFOV, lowerFOV, upperNormal etc.). Thanks.

**Comment by hadiTab** [comment]
@Tomoya-Sato you are correct. At the moment it is not easily possible to provide non-linear ray spacing. Although it would be useful to add this feature, we are in the process of replacing our the current Lidar implementation with a more efficient one. We will add this feature to the new implementation.

**Comment by EricBoiseLGSVL** [comment]
@Tomoya-Sato we are currently working on finalizing this feature and will release it soon
