### ISSUE TITLE
run new simulator behind proxy

### ISSUE THREAD

**Issue by Kailiangdong** [lgsvl/simulator#360]
Hello. When I run new simulator , I find a problem. I have a proxy locally.
After I enter the user name and password, the page will keep in "loading" but not go into normal UI. If I don't use proxy, everythings go fine. But using proxy is necessary.
I think there is somethings in web missing the proxy  when try to check password and username in the backend online.
Thank you in advanced for help.

**Comment by Roman-jj** [comment]
Hello, I have the same problem.

I tried to run the WebUI using "npm run serve" and it produces the same error. When trying to access localhost:8081 in Firefox, I get this web console output:
`Navigated to http://localhost:8081/
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:21258
Token detected:  null App.js:35
Checkhing current user... App.js:47
another error happened:Request failed with status code 500 APIs.js:26
Getting the user:  
Object { data: "Proxy error: Could not proxy request /users from localhost:8081 to http://localhost:8080 (ECONNREFUSED).", status: 500, statusText: "Internal Server Error", headers: {…}, config: {…}, request: XMLHttpRequest }
App.js:50
Require authentication in the cloud 
Object { data: "Proxy error: Could not proxy request /users from localhost:8081 to http://localhost:8080 (ECONNREFUSED).", status: 500, statusText: "Internal Server Error", headers: {…}, config: {…}, request: XMLHttpRequest }
App.js:55
Failed to get user information App.js:62
XML Parsing Error: syntax error
Location: http://localhost:8081/users
Line Number 1, Column 1: users:1:1
./src/components/SimulationManager/FormMapVehicles.js
  Line 126:  'vehicleList' is already declared in the upper scope  no-shadow webpackHotDevClient.js:138
The development server has disconnected.
Refresh the page if necessary. webpackHotDevClient.js:76`

The terminal running the server shows this:
`Compiled with warnings.

./src/components/SimulationManager/FormMapVehicles.js
  Line 126:  'vehicleList' is already declared in the upper scope  no-shadow

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

Proxy error: Could not proxy request /users from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

Proxy error: Could not proxy request /sockjs-node/153/0wgqg4el/websocket from localhost:8081 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).`

Building the WebUI in Unity makes no difference. I also tried defining a constant token directly in app.js, this makes the page reload all the time.
Is there a way to run the simulator without user authentification?

**Comment by martins-mozeiko** [comment]
Do you need to run WebUI through npm? Because that is needed only when you do development on UI. Normally you just run Simulator from unity and it will serve WebUI directly - there is no need to run npm serve.

Do you get same error when access WebUI directly on 8080 port?

**Comment by Roman-jj** [comment]
Oh yeah, I forgot to mention, the same happens when running it the normal way, through Unity or from the standalone version, on different machines.
Only used npm for testing.

Sometimes after clearing cookies I get through to the login page somehow, get the token but then the same error happens

Am 13. September 2019 20:04:45 MESZ schrieb Martins Mozeiko <notifications@github.com>:

**Comment by martins-mozeiko** [comment]
Ok, we'll look into this.

**Comment by Kailiangdong** [comment]
@martins-mozeiko Excuse me, are there current way to solve proxy problem or  run the simulator without user authentification? I check for a while. May be it is problem of axios in react.  https://github.com/axios/axios/issues/1679
I will continue to figure out this problem .Thank you

**Comment by martins-mozeiko** [comment]
We do not have solution for this now, but we are aware of issue and it is in our backlog to fix it.

**Comment by zelenkovsky** [comment]
@Roman-jj @Kailiangdong I believe I know what is your problem. Find config.yml file next to simulator.exe or in your source tree if you are building simulator from source and make sure, hostname is set to "*", not localhost.  `npm run serve` does not listen on localhost.

```
hostname: "*"
port: 8080
headless: false
read_only: false
api_hostname: "localhost"
api_port: 8181
```

Could you please confirm that this solved your problem.

**Comment by Roman-jj** [comment]
Hi, thanks for your suggestion, unfortunately it didn't solve the issue.

We're using a workaround through mobile network atm

**Comment by adas-dev** [comment]
I am also facing exactly the same problem when I start LGSVL simulator under proxy. I would appreciate if you find the solution to the problem.

**Comment by Kailiangdong** [comment]
Dear all,
Use Proxifier app on your computer will solve this problem.

**Comment by habermayr** [comment]
Any update on this proxy issue? I have the same proplem and cannot avoid the proxy...

**Comment by Ace-Xu** [comment]
Please help me, I also have to use the simulator behind proxy and I am facing the same question.

**Comment by Kailiangdong** [comment]
> Please help me, I also have to use the simulator behind proxy and I am facing the same question.

Do you try "Proxifier "  this software?

**Comment by Ace-Xu** [comment]
> > Please help me, I also have to use the simulator behind proxy and I am facing the same question.
> 
> Do you try "Proxifier " this software?

Yes I just downloaded it, can you tell me how to use it? And my mail address is xuzhejun@sjtu.edu.cn , thanks a lot!!

**Comment by Carlos-Loera** [comment]
Hi, I am running into this LGSVL limitation with Proxy. I am unable to use Proxfier or any other alternative tool. I would like to be able to run the simulator without user authentication or for this proxy issue to be fixed. Do you have plans to permanently fix this issue?

**Comment by GrayHHHH** [comment]
Hi guys, have you gotten the solution for working behind proxy on linux?

**Comment by DrShIkIgAmy** [comment]
> Dear all,
> Use Proxifier app on your computer will solve this problem.

It doesn't work... Personally for me... I use privoxy, 'cause I have to run lgsvl on Ubuntu.

**Comment by DrShIkIgAmy** [comment]
> Hi guys, have you gotten the solution for working behind proxy on linux?

Is current thread dead or there's something new?
