### ISSUE TITLE
Dont see the simulator option in unity 

### ISSUE THREAD

**Issue by Iqbalparvi** [lgsvl/simulator#361]
hi,
 is there any one who help me to install lgsvl properly on my ubuntu 16.04, i follow the instruction on 
https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md 
but in step 14 its seems the simulator option here for further process .my unity window not shows the simulator option i am stuck here last three days ,i want to merged lgsvl with apollo 5.0 kindly any help
regards

**Comment by Iqbalparvi** [comment]
@martins-mozeiko No there is no error in console  and all others buttons like File,Edit,Asses,GameObjects,Components.........,are there but the only simulator option not found

**Comment by Iqbalparvi** [comment]
if the simulator is not found then we cant make any progress on further step like step 14,15 by following this official instructions 
https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md
kindly check it
regards

**Comment by martins-mozeiko** [comment]
Please show screenshot how your Unity project looks like when you have opened it. Including Project window & console window.

**Comment by Iqbalparvi** [comment]
its looks like as:--
![70154483_2512604002119676_8442325177445908480_n](https://user-images.githubusercontent.com/47267894/64846852-f81eb300-d650-11e9-9468-ee954bc51e80.jpg)

**Comment by martins-mozeiko** [comment]
Please show screenshot of Project window: https://docs.unity3d.com/Manual/ProjectView.html
And Console window: https://docs.unity3d.com/Manual/Console.html

If you can, please use screenshot functionality in ubuntu, and not mobile phone camera. Otherwise quality is quite bad, it is hard to see what is written on screen.

**Comment by Iqbalparvi** [comment]
Project window:
![Screenshot from 2019-09-13 18-13-21](https://user-images.githubusercontent.com/47267894/64847567-a414ce00-d652-11e9-829e-c8bcc9ddbbc5.png)
Console:
![console](https://user-images.githubusercontent.com/47267894/64847588-abd47280-d652-11e9-87fe-1fd27237b390.png)

**Comment by Iqbalparvi** [comment]
i think you have a look ist this one its the step 14 from lgsvl github installation guide that i give link above .in my case i dont see the simulator option as it seems here in this guideline:
![Screenshot from 2019-09-13 18-25-35](https://user-images.githubusercontent.com/47267894/64848145-f1456f80-d653-11e9-86ea-26e47a832080.png)

**Comment by martins-mozeiko** [comment]
I understand that you don't have this menu item. I want to understand how does project look like inside Unity Editor. Please show the screenshot of **Project Window** - that will help me understand why this menu item is not present.

**Comment by Iqbalparvi** [comment]
sure here it is :
![Screenshot from 2019-09-13 18-31-30](https://user-images.githubusercontent.com/47267894/64848530-c14a9c00-d654-11e9-9087-1340e3da60ec.png)

**Comment by martins-mozeiko** [comment]
This does not seem to be Simulator project. I think you have opened newly created empty project. You need to choose **File->Open Project...** and select folder where you have cloned Simulator github repository (step 7 & 10 in build instructions).

**Comment by Iqbalparvi** [comment]
@martins-mozeiko thanks for your cooperation but i follow all these steps , still i dont solve my problem and try to solve asap ......
Regards

**Comment by martins-mozeiko** [comment]
Please use Unity Hub to open project.

First step is to click **Add** button to add Simulator project:

![image](https://user-images.githubusercontent.com/39178216/64886437-0c47bd80-d61b-11e9-8a9e-f63d97c6316b.png)

Then you browse to where you have cloned **Simulator** github repository and click **OK**:

![image](https://user-images.githubusercontent.com/39178216/64886539-4749f100-d61b-11e9-9f27-7f2b25f2d7f3.png)

After that you'll see **Simulator** entry in Unity Hub (just like in first image). Click on it to open it.

**Comment by daohu527** [comment]
I also had this problem before, after I deleted the project, re-clone the code, and then add the project.
I still don't know the cause of the problem, I guess it may be that some files are missing.

**Comment by martins-mozeiko** [comment]
What happens when you add project to Hub? Does it show up in project list? What happens when you click on it and Unity opens project? Project list is also empty?

**Comment by Iqbalparvi** [comment]
@martins-mozeiko thank you so much now I have seen that Option but can you please guide about  step 20 :
![Screenshot from 2019-09-14 12-10-55](https://user-images.githubusercontent.com/47267894/64902369-3071d000-d6e9-11e9-88a3-e6444328fd9f.png)
Which folder I have to select tocomplete this step and there I cant see the folders like AssetBundles,Obj,AutowareVectorMap as shown below:
![Screenshot from 2019-09-13 18-25-35](https://user-images.githubusercontent.com/47267894/64902387-847cb480-d6e9-11e9-90bc-e6b4d50af86f.png)

**Comment by Iqbalparvi** [comment]
Solve this probelm thanks @martins-mozeiko for giude towards this setup 
closing this issue now

**Comment by pedroexenberger** [comment]
I now this is a closed issue, but I'm facing the same problem. I'm trying to build the simulator from scratch to try solve issue #653. Had the same problem at step 14 of the [instructions](https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md)
I followed the steps suggested by @martins-mozeiko (entering the simulator folder to press Ok when selecting the project in Unity Hub), but still, neither the simulator tab nor the internal tab appears when Unity Editor starts the project.

I've attached two screenshots above if it helps:

Unity hub display:
![Screenshot from 2020-03-04 17-27-13](https://user-images.githubusercontent.com/8921809/75900593-6e041a00-5e3d-11ea-82b0-35611b09b09b.png)

The view when opening the project from within Unity hub:
![Screenshot from 2020-03-04 17-26-48](https://user-images.githubusercontent.com/8921809/75900600-6fcddd80-5e3d-11ea-82c6-71bd85a17674.png)

Just as a sanity check I ran the following commands:
```
~/Projects/simulator$ ls -a
.           Docker          .gitignore  LICENSE-3RD-PARTY  README.md
..          Docs            Jenkins     Packages           Temp
Assets      .git            Library     PRIVACY            WebUI
config.yml  .gitattributes  LICENSE     ProjectSettings
```

```
~/Projects/simulator$ pwd
/home/pedro/Projects/simulator
```
Do anyone what can be the problem here? Thank you very much for your support!
Cheers.

**Comment by ntutangyun** [comment]
hi, @Iqbalparvi ,  after you opened up the Unity editor, try to open the default loader scene at `Assets/Scenes/LoaderScene` by double-clicking it.

**Comment by pedroexenberger** [comment]
Hi @ntutangyun, I'm assuming your message was for me (since this issue has been closed for a few months before my comment). 

I double-clicked the LoaderScene, but it does not change the Unity Ui, especially the Simulator tab on the top bar menu.

![Screenshot from 2020-03-05 11-48-06](https://user-images.githubusercontent.com/8921809/75974525-377add80-5ed7-11ea-944a-2857e5cda938.png)

Any advice? Thank you!

**Comment by ntutangyun** [comment]
@pedroexenberger I've never seen the errors without any information in Unity like that in your screenshot. Are you able to actually run the editor ?

**Comment by pedroexenberger** [comment]
@ntutangyun Sorry, I've never used Unity before. What do you mean by running the editor?
Thank you.

**Comment by pedroexenberger** [comment]
@ntutangyun  In time, when I proceeded with the installation of Unity 2019.1.10f1 there was no 'support for linux' option (as suggested in the [build instructions](https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md) (step 2). I checked Unity, Windows, and WebGL in this case..



![Screenshot from 2020-03-05 14-53-40](https://user-images.githubusercontent.com/8921809/75988039-42426c00-5ef1-11ea-904f-f89e327ab3d8.png)

**Comment by pedroexenberger** [comment]
I tried following the same steps in a Ubuntu 16.04 machine that I have access too (I was running on my Ubuntu 19.10 machine previously). In the ubuntu 16, the simulator tab appeared. 
Given that, I'm using this Ubuntu 16 machine to build the simulator as I can't afford much time to debug this problem on Ubuntu 19.10 in-depth right now.

Thank you for your help @ntutangyun·

**Comment by ntutangyun** [comment]
> What do you mean by running the editor?
just click the arrow button to the left of the pause button, on top of the unity editor.

> In the ubuntu 16, the simulator tab appeared.
sounds good.

**Comment by david-gwa** [comment]
I faced the same issues, when to loading a half-year old version of lgsvl, it reports errors as following, and there is no `simulator` option in menu.

```sh
PrecompiledAssemblyException: Multiple precompiled assemblies with the same name ICSharpCode.NRefactory.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
/home//gitlab_/simulator-202001/Library/PackageCache/com.unity.render-pipelines.core@7.3.1/Editor/ShaderGenerator/ICSharpCode.NRefactory.dll
/home//gitlab_/simulator-202001/Packages/com.unity.render-pipelines.high-definition/Editor/Core/ShaderGenerator/ICSharpCode.NRefactory.dll
``` 

and the fix is pretty simple, just delete the `Library` and reload in Unity Editor

**Comment by asfandyarorakzai** [comment]
Hello,

I know the issue is closed but they don't have the WebUI file in the updated repository.

**Comment by JishithaJK** [comment]
It's the same issue with me. There is no WebUI file, is there any solution?
