### ISSUE TITLE
Occlusion modeling for lidar

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#364]
Are there occlusion modeling for lidar?Thank you！

**Comment by martins-mozeiko** [comment]
I'm not sure what is occlusion modeling.
Current implementation of lidar is implemented through rendering depth buffer of virtual camera. Then lidar samples rendered depth at directions where lidar rays are going. Basically you can think of it as simple raytracing where each rays return closes depth (+intensity) on first hit.

**Comment by yumianhuli2** [comment]
> I'm not sure what is occlusion modeling.
> Current implementation of lidar is implemented through rendering depth buffer of virtual camera. Then lidar samples rendered depth at directions where lidar rays are going. Basically you can think of it as simple raytracing where each rays return closes depth (+intensity) on first hit.

Spherical ray tracker sampling mesh?

**Comment by martins-mozeiko** [comment]
We do not use Unity DXR ray tracing API (yet). Lidar ray distance calculations are done from rendering depth with virtual camera.

**Comment by yumianhuli2** [comment]
> We do not use Unity DXR ray tracing API (yet). Lidar ray distance calculations are done from rendering depth with virtual camera.

Have a plan for using Unity DXR ray tracing API ？Such lidar point clouds would be more realistic, allowing for true reflection and refraction.

**Comment by martins-mozeiko** [comment]
Yes, we have plans to use it. Once this Unity version will be out as stable (not alpha/beta), and we'll upgrade project to it, then we'll improve the lidar sensor. Unfortunately Unity supports this feature only on Windows. It is not clear when it will be available on Linux.

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 we are currently working on this feature but Unity RTX support is not quite ready for production.  We will have more news once the feature is ready
