### ISSUE TITLE
How to connect Autoware and lgsvl simulator

### ISSUE THREAD

**Issue by obi5656** [lgsvl/simulator#368]
I want to know how to connect Autoware and lgsvl simulator.

Look at the image, you need to connect / websocket_bridge and / runlme_manager_2251_1568602169589?
![Screenshot from 2019-09-16 11-58-27](https://user-images.githubusercontent.com/55091660/64936392-a8c6c580-d890-11e9-9a40-b85e8cbd54b0.png)

Or can I just start rosbridge?

**Comment by martins-mozeiko** [comment]
Please follow documentation here: https://www.lgsvlsimulator.com/docs/autoware-instructions/#launching-autoware-alongside-lgsvl-simulator

When you will select `my_sensing_simulation.launch` file and run it, it will automatically start ROS bridge node.

**Comment by obi56** [comment]
There is no need to run roslaunch rosbridge_server rosbridge_websocket.launch.

Does that mean you can connect Autoware and lgsvl simulator just by clicking “Sensing”?

**Comment by martins-mozeiko** [comment]
Yes. Sensing will launch all necessary modules for simulator to connect to Autoware ROS environment.

**Comment by obi56** [comment]
Thank you.

Clicking "Localization" does not display the time to the right of "Ref".

And even if "Rviz" is started, it is displayed like this, and the position of the vehicle is not displayed as explained.

![Screenshot from 2019-09-16 19-45-01](https://user-images.githubusercontent.com/55091660/64952218-b8f39a80-d8ba-11e9-9d3f-3f7bb34e62a8.png)

**Comment by martins-mozeiko** [comment]
You need to click "2D Pose Estimate" button and manually specify position. This operation does not always succeed on first time. You need to repeat it until it succeeds.

**Comment by obi56** [comment]
Thank you for your reply.

I won't succeed if I do it more than 10 times.

Is there any part other than 'Quick Start' in runtime manager?

Or is it because the time is not displayed to the right of "Ref" after clicking "Localization"?

**Comment by EricBoiseLGSVL** [comment]
@obi5656 we are not sure why this happens but we are glad you are getting Rviz to work with Simulator
