### ISSUE TITLE
Can you briefly introduce your odometer simulation?

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#369]
Can you briefly introduce your odometer simulation? Such as input and output and simulation fundamentals.Thank you!

**Comment by martins-mozeiko** [comment]
Odometry sensor implementation is available in [GpsOdometrySensor.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Sensors/GpsOdometrySensor.cs#L108) file.

It gets position of sensor in world space with `transform.position`. This position is converted to latitude/longitude and easting/northing coordinates by calling `MapOrigin.GetGpsLocation`. Then thes values are put into GpsOdometryData object. This class represents ROS or Cyber message that is sent to bridge when `Writer.Write(data)` is called.
