### ISSUE TITLE
 simulator/Docs/docs/map-annotation.md 

### ISSUE THREAD

**Issue by jonwetherall** [lgsvl/simulator#370]
The system is managable ish but a bit clunky.  I have attempted to export a map and in Apollo it come up blank.  Also it only makes the .bin not the routing_map etc.
When I export the single_land_road I get only the base_map.bin regenerated.  If I copy across the other files routing_map etc. it works in apollo.  This leads me to thinking there is a missing step to making the other files from base_map?

**Comment by martins-mozeiko** [comment]
Te create other files, run `generate_map.sh MAPNAME` script in Apollo docker. This will create all other files from base_map.bin automatically. `MAPNAME` here is folder name under `modules/map/data` folder.
