### ISSUE TITLE
Perception works but traffic light not

### ISSUE THREAD

**Issue by Kailiangdong** [lgsvl/simulator#371]
Hi. 
I successfully build apollo, make it connect with lgsvl. And according to the following picture, the perception module works , it can recognize car and people. But when I set a point for ego car, it will always stop in front of traffic light. It seems that the traffic light module not works. And when I find detail in the log of traffic light. It seems that the reason is from not-working camera.
Can anyone give me the advises? Thank you in advanced.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/38508002/64974635-7bd4db80-d8ad-11e9-9a8a-c64e4c8ba4d7.jpg)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/38508002/64974703-9f982180-d8ad-11e9-8c00-bef80820a1cf.jpg)
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/38508002/64974749-b9d1ff80-d8ad-11e9-82c9-ff2c99378dd7.jpg)

**Comment by martins-mozeiko** [comment]
What simulator and Apollo version are you using?

If vehicle does not cross intersection that usually means it does not "see" traffic light color - so it does not know if it is green. This can happen if vehicle does not have correct sensor calibration loaded.

Can you try selecting vehicle in `-- vehicle --` combobox at top right?

**Comment by Kailiangdong** [comment]
@martins-mozeiko  
Thank you for your reply. I use simulator2019.05 and apollo 3.5. (Sorry , but will switch to latest simulator and 5.0 next month)
I select vehicle. Only "Mkz example" and "XE Rigged",I try both but not works. I thought I should use "XE Rigged3.5" but there is no such choice?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/38508002/64985373-007f2400-d8c5-11e9-9770-db94c190ad89.jpg)

**Comment by Kailiangdong** [comment]
I run "./perception.sh startre" . Got following log. I wonder whether problem is from is yaml files?. Because I don't find the same name of file in such forder.
![Capture20-min](https://user-images.githubusercontent.com/38508002/65031212-2518e180-d941-11e9-9568-2c85a09c1f94.PNG)
![Capture19-min](https://user-images.githubusercontent.com/38508002/65031358-6c06d700-d941-11e9-88f3-8a04fcff5a90.PNG)

**Comment by Kailiangdong** [comment]
And also run the "./apollo.sh test". It seems that the unit test can be passed. But Intergration test not. 
The yolo_yolo_obstacle_detector_test not work. I thought maybe camera's problem?
**Thank you in advanced for someone's help.**
(My host is 18.04, nvidia tesla p100, compute capability 6.0, driver 390.116, I use docker lgsvl/apollo3.5 and simulator 2019.05 release.
![Capture21-min](https://user-images.githubusercontent.com/38508002/65031485-a2445680-d941-11e9-99ae-870c0f9f0655.PNG)
![Capture22-min](https://user-images.githubusercontent.com/38508002/65031486-a2445680-d941-11e9-92e0-3c6e8ef48799.PNG)

**Comment by EricBoiseLGSVL** [comment]
@Kailiangdong please update to latest simulator and let us know if you are still having issues

**Comment by Martin20** [comment]
I updated and still have the problem.

**Comment by EricBoiseLGSVL** [comment]
@Martin20 This issue is closed.  Please create a new issue so we can be sure to assign someone
