### ISSUE TITLE
Could you update the launch files in autoware-data?

### ISSUE THREAD

**Issue by yfshe** [lgsvl/simulator#374]
When I used LGSVL with Autoware 1.12.0, I found that the launch files in autoware-data are out of date.

Specifically, the **range_fusion**, **vision_dummy_track**, **obj_reproj** and **obj_fusion** in the [my_detection.launch](https://github.com/lgsvl/autoware-data/blob/master/BorregasAve/my_launch/my_detection.launch) and the **astar_planner** in the [my_motion_planning.launch](https://github.com/lgsvl/autoware-data/blob/master/BorregasAve/my_launch/my_motion_planning.launch) are no longer exist in the Autoware 1.12.0. Maybe they are renamed or discarded, I am not very clear.

In order to test the complete Autoware ability in LGSVL, could you update these files for Autoware 1.12.0?

**Comment by hadiTab** [comment]
@yfshe you are right, some of the launch files include out of date nodes in them. We will update them soon. The detection launch file is also a bit out-dated.
I would suggest you consult the official Autoware repos for more information on how to run Autoware. The launch files are provided as examples to get Autoware up and running quickly with some basic functionality, but they may not be using the latest Autoware features and there may be better ways to run Autoware for certain tasks.
