### ISSUE TITLE
2019.09, when I build the simulator in Unity, there are no environments and vehicles? and when i open the browser there are no maps vehicles and simulations?

### ISSUE THREAD

**Issue by gaohongfein** [lgsvl/simulator#379]

**Comment by gaohongfein** [comment]
![Screenshot from 2019-09-19 15-55-45](https://user-images.githubusercontent.com/26884060/65224717-4f5fd000-daf6-11e9-9be4-abbf57b5482b.png)
![Screenshot from 2019-09-19 15-57-53](https://user-images.githubusercontent.com/26884060/65224721-51299380-daf6-11e9-9c6a-10bb75bde7e9.png)

**Comment by srirambadri** [comment]
Same error. Missing assets

**Comment by srirambadri** [comment]
@gaohongfein try downloading it from here https://content.lgsvlsimulator.com/

**Comment by srirambadri** [comment]
But unity is not able to detect them
![image](https://user-images.githubusercontent.com/8626656/65232878-31807400-dad2-11e9-9a72-ed7b2476382a.png)

**Comment by gaohongfein** [comment]
> @gaohongfein try downloading it from here https://content.lgsvlsimulator.com/

Have you solve this problem? I can not run the Unity without root. This can result in this problem?

**Comment by srirambadri** [comment]
Even without root unity still doesn't recognize the files. I'm having the same problem as you

**Comment by srirambadri** [comment]
Look at this issue 
https://github.com/lgsvl/simulator/issues/318?_pjax=%23js-repo-pjax-container

**Comment by gaohongfein** [comment]
I can't also recognize these files。。。

**Comment by gaohongfein** [comment]
I can't open the browser after I click button“open browser"
![Screenshot from 2019-09-19 21-49-47](https://user-images.githubusercontent.com/26884060/65250000-6cf95d80-db27-11e9-9fb4-2620c61ffbf5.png)

**Comment by martins-mozeiko** [comment]
The maps and vehicles under Build menu needs to be added manually to project. You need to build them only if you are modifying environment or vehicle. If you are modifying only simulator you can use binary map and vehicle bundles that you can get on our content website. Binary build of simulator will automatically download these maps and vehicles.

Read more information on asset building in our documentation: https://www.lgsvlsimulator.com/docs/assets/

**Comment by srirambadri** [comment]
@martins-mozeiko hi thanks for the info. I got the binaries from the https://content.lgsvlsimulator.com/, and put them in the folders as specified in the link you had suggested. But I still get an error saying the ".scenefile" are missing. Do you know where to download the correct binaries from?
![image](https://user-images.githubusercontent.com/8626656/65307550-4e777e80-db88-11e9-8c41-20534197649f.png)

**Comment by martins-mozeiko** [comment]
I think you misunderstood me.
You need to put git cloned folders in `External/{Environments,Vehicles}` folder. For example, SingleLaneRoad repository from https://github.com/lgsvl/SingleLaneRoad/

You do that only when you are modifying map or vehicle. If you are not then, there is no need to build anything. Asset bundles from content website are already built by us. These are final binaries. You need to add them in web interface directly:
https://www.lgsvlsimulator.com/docs/maps-tab/#how-to-add-a-map
https://www.lgsvlsimulator.com/docs/vehicles-tab/#how-to-add-a-vehicle

**Comment by srirambadri** [comment]
That's exactly what I was looking for, thanks.
