### ISSUE TITLE
windows standalone build 

### ISSUE THREAD

**Issue by david-gwa** [lgsvl/simulator#383]
hey, lg-team,

 we have a little problem with lg-sim windows build.

 option 1), build the project  in Unity Editor env directly, it won't generate the AssetBundle folder

option 2), build with the [command line](https://github.com/lgsvl/simulator/blob/master-obsolete/Docs/docs/build-instructions.md), it generates the AssetBundle folder, but it's empty inside.

we had Ubuntu command line built, works well.

**Comment by martins-mozeiko** [comment]
Hi.
Does the Build window show any environments or vehicles and you have selected them?
If it does not show any environments there, then please make sure you have put them in correct locations. Read about asset building in our documentation: https://www.lgsvlsimulator.com/docs/assets/

**Comment by david-gwa** [comment]
sorry, need to clarify, we are still in the old version, and prefer the command line build, and during run the build commands, there is no Build windows showup.  

after built, the folder looks like: 

![build](https://user-images.githubusercontent.com/52392538/65296389-db293900-db96-11e9-9d6a-08c0355f2236.PNG)

`simulator.exe` binary is working, but `AssetBundles` folder is empty, which gives null list of map:

![build2](https://user-images.githubusercontent.com/52392538/65296474-27747900-db97-11e9-8912-648fbfe52439.PNG)

**Comment by martins-mozeiko** [comment]
For old simulator version see comments in following issue: https://github.com/lgsvl/simulator/issues/41

**Comment by david-gwa** [comment]
checked issue: #41,  and my built actually also work well in Editor Run:

![editor](https://user-images.githubusercontent.com/52392538/65304274-ce1a4300-dbb2-11e9-83bb-f38f327264ba.PNG)

while the standalone binary in non Editor env, doesn't have AssetBundle.  looks like AssetBundleManager.prefab is not triggered when `build in command line`

**Comment by EricBoiseLGSVL** [comment]
@david-gwa yes, Editor loads from scene file while build loads from asset bundle.  Please update to latest simulator for latest features and fixes
