### ISSUE TITLE
No sensor data visualised by dreamviewer

### ISSUE THREAD

**Issue by srirambadri** [lgsvl/simulator#399]
Hi,

I followed the instructions [here](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/) to connect the simulator with apollo 5.0

I'm able to launch the simulator and connect it to apollo. When I manually move the vehicle in the simulation environment I see the model in the dreamviewer moving as well. So the connection seems to be working. 
But the problem is I don't see any of the information (sensor data) captured in the simulation environment in the dreamviewer screen. I've activated the necessary modules in the module controller tab but after few seconds they turn themselves off. 
![image](https://user-images.githubusercontent.com/8626656/65855968-a8cec700-e360-11e9-8939-c236328df51b.png)

Any idea as to what the problem could be?

**Comment by martins-mozeiko** [comment]
Please check the logfiles of modules that turn off (Perception). It should contain more detailed error message.
Note that you do not need to enable Camera module in dreamview.

**Comment by srirambadri** [comment]
I checked the apollo/data/log folder, there were no logfiles created by the perception module.Do you know where they're saved otherwise

**Comment by martins-mozeiko** [comment]
They should be in this log folder. Check the permissions of folder, maybe it does not have permissions to write.

Alternative is to run perception in foreground, so all output shows up in terminal:
```
perception.sh start_fe
```
