### ISSUE TITLE
ROSAgentManager doesn't exist.

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#401]
Hello everyone,<br>
I want to add a new vehicle, so I tried to follow the instructions on [this doc](https://www.lgsvlsimulator.com/docs/add-new-ego-vehicle/). However source code of the simulator doesn't have ROSAgentManager to add sensors in project. I've searched it everywhere.<br>
What did I wrong?

**Comment by hadiTab** [comment]
What version of the simulator are you using?

**Comment by clepz** [comment]
v2019.09 <br>
I cloned the source code 4 or 5 days ago.

**Comment by EricBoiseLGSVL** [comment]
@clepz 

We are in the process of updating our tutorials to the new HDRP simulator and they will release soon.

In the meantime, here are the steps.

1) Create a folder with the vehicle name in Assets/External/Vehicles/YourNewVehicle
2) Place create Models folder inside YourNewVehicle folder.  Import .fbx into Models folder, it should make a Materials folder inside Models folder.  If not, make one.  All materials and textures go in this folder.
3) Drag the Jaguar2015XE prefab that we provide into an empty scene.  This is for reference
4) Create a empty game object, name it YourNewVehicle and reset it's transform. Pos (0,0,0) Rot (0,0,0)
5) Drag the vehicle fbx as a child of this game object.
6) Right Click on the Jaguar2015XE object and choose Unpack Prefab.
7) Select the WheelColliderHolder, HeadLights, BrakeLights, IndicatorsLeft, IndicatorsRight, IndicatorsReverse, InteriorLight and Reflection Probe.
8) Drag these selected objects to YourNewVehicle so they are children of the root object.
9) Delete broken Jaguar2015XE prefab from scene and add a new one for reference.
10) Select root object of Jaguar2015XE.
11) Right click Copy Component in the Inspector panel on the RigidBody component
12) Select the YourNewVehicle root object and in the inspector panel, right click and Paste Component as New
13) Repeat for VehicleDynamics, VehicleController, and VehicleActions.
14) On the VehicleDynamics component, open Axles array.  Inside assign the FL FR RL RR wheel colliders and Left, Right, Front and Rear wheel meshes from your model.  See the Jaguar2015XE prefab for help.
15) Assign Tag "Player" and Layer "Agent" (All child objects)
16) Move lights and wheel colliders to match YourNewVehicle wheels and light positions.
17) Drag the root YourNewVehicle into the Project Panel in the Assets/External/Vehicles/YourNewVehicle folder.
18) At the top menu, Simulator -> Build... and make an asset bundle for that vehicle.  It places it in the repo AssetBundles folder.
19) Run the WebUI to then add a new vehicle and point it to the new vehicle. Boom, YourNewVehicle.

**Comment by BatuhanUlucay** [comment]
Hi @EricBoiseLGSVL , I did all the steps you have mentioned, but when the simulation begins, the car does not stand still, it starts flying and falls down from the map as you can see below. I've added the logfile screenshot.


![Screenshot from 2019-10-03 11-03-36](https://user-images.githubusercontent.com/43452015/66109858-3b27d280-e5ce-11e9-8dac-33667567d866.png)
![my_unity_editor](https://user-images.githubusercontent.com/43452015/66109869-42e77700-e5ce-11e9-9862-432e82fb9c8f.png)
![log_error](https://user-images.githubusercontent.com/43452015/66109887-4aa71b80-e5ce-11e9-8f2c-b6e18d9a1f1e.png)

**Comment by EricBoiseLGSVL** [comment]
@BatuhanUlucay 

I can tell immediately that the transforms are not reset.  Set the root prefab at position/rotation (0,0,0), scale (1,1,1) from step 4.  Left click the transform component top right gear and choose Reset.

![WrongTransforms](https://user-images.githubusercontent.com/45106230/66150326-c5ba0300-e5c9-11e9-831d-3179a7a1b201.PNG)

Reset all child holder object as well.  Reposition the children of the child holders, e.g. the lights and wheel colliders.

![CorrectTransforms](https://user-images.githubusercontent.com/45106230/66150352-d23e5b80-e5c9-11e9-8f6d-bec6567692a3.PNG)

Add a mesh collider to the body of the vehicle.

![CorrectMeshCollider](https://user-images.githubusercontent.com/45106230/66150361-d79ba600-e5c9-11e9-9aae-5aa58b61256d.PNG)

I have updated the 1-20 steps above to be more clear

**Comment by BatuhanUlucay** [comment]
@EricBoiseLGSVL Thank you, adding the mesh collider to body did work.
