### ISSUE TITLE
Main loop in simulator

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#402]
I would like to implement my algorithm based on imu and gps , but I have found only the sensors part , like ImuData.cs and so on.. Where is the main loop that calls all algorithms and all other meaty functions that run the whole simulator. I just got lost in Unity files.

**Comment by martins-mozeiko** [comment]
Simulator heavily depends on how Unity works with different objects. Main loop is implemented internally inside Unity engine. For sensors main methods are Update and FixedUpdate which are called from inside Unity. You can learn more about Unity object life-cycle in Unity documentation: https://docs.unity3d.com/Manual/ExecutionOrder.html
