### ISSUE TITLE
Cannot find NPCs in point clouds

### ISSUE THREAD

**Issue by huantc3033** [lgsvl/simulator#403]
Version: 2019.07

Description: When adding LiDAR sensor to ego vehicle, if set visible we can see LiDAR points marked red in the environment, except the NPC vehicles. When subscribing to the topic of LiDAR sensor and visualize it with pcl visualizer, we cannot see any of them shaped like it is a vehicle.

Reproduction: Build the simulator and load the vehicles and maps as usual. Launch rosbrige_server and start running a simulation. Using a point cloud visualizer like rviz or others and subscribe to the topic of LiDAR. See the result displayed in rviz.

**Comment by martins-mozeiko** [comment]
Can you please show screenshot of simulator where lidar points does not hit NPC vehicles?

**Comment by huantc3033** [comment]
![圖片](https://user-images.githubusercontent.com/21102957/67752352-cbdabc80-fa6d-11e9-9004-be801d24982a.png)
As the picture, there are no lidar points on the surface of NPCs, and as I open the pcl viewer, there seems no vehicles to be displayed.

**Comment by martins-mozeiko** [comment]
This is very unusual. I'm not sure what is wrong here.

Which version are you using exactly? In first post you said 2019.07, but this version did not have sensor-view button (eye icon on the bottom) or the car selection on the bottom-right.

You mentioned that you have built simulator? Can you try running prebuilt binary form our official releases to see if it also happens?
