### ISSUE TITLE
Error building WebUI 

### ISSUE THREAD

**Issue by MithunKinarullathil** [lgsvl/simulator#404]
Followed the [build instructions step by step](https://www.lgsvlsimulator.com/docs/build-instructions/). Getting this error below on step 23 on the latest sim.

ERROR: 

**Error building WebUI
UnityEngine.Debug:LogError(Object)
Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:64)**

System:
OS: Ubuntu 16.04 LTS
CPU: Intel® Core™ i9-9900K CPU @ 3.60GHz × 16 
GPU: GeForce RTX 2080 Ti/PCIe/SSE2
Memory: 32 GB

**Comment by MithunKinarullathil** [comment]
Partial solution: 

`sudo ln -s /usr/bin/nodejs /usr/bin/node`

Cause: [Issue](https://github.com/nodejs/node-v0.x-archive/issues/3911)

New Problem:

- You are running Node v4.2.6, but @enact/cli requires Node >=6.4.0.

Solution: [Node Js Upgrade](https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version)

- `sudo npm install n -g`

- `sudo n stable`

**Comment by MithunKinarullathil** [comment]
Please mark this as solved. Build is complete now.

LOG: 

**WebUI build is completed
UnityEngine.Debug:Log(Object)
Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:60)**

**Comment by twuser666** [comment]
> Followed the [build instructions step by step](https://www.lgsvlsimulator.com/docs/build-instructions/). Getting this error below on step 23 on the latest sim.
> 
> ERROR:
> 
> **Error building WebUI UnityEngine.Debug:LogError(Object) Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:64)**
> 
> System:
> OS: Ubuntu 16.04 LTS
> CPU: Intel® Core™ i9-9900K CPU @ 3.60GHz × 16
> GPU: GeForce RTX 2080 Ti/PCIe/SSE2
> Memory: 32 GB

Hi, I have the same problem.
Can you teach me how to solve this problem?
Thank for your help.
