### ISSUE TITLE
About point cloud info

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#405]
How to get real-time point cloud data and store them, and then import them into third-party software such as matlab for analysis,Thanks!

**Comment by martins-mozeiko** [comment]
You can either collect point cloud over ROS Bridge as ROS PointCloud2 message. Or you can use PythonAPI to set up scene and save lidar point cloud to disk as pcd file. Check Python examples - `07-save-lidar-point-cloud.py` example shows how to do this.
