### ISSUE TITLE
No input from steering wheel in windows

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#409]
Hello,

I am trying to setup lgsvl on a windows machine and I like to use a steering wheel with force feedback. I have the Logitech MOMO steering wheel, it seems to be detected by unity but I can't get any input from it.

Do you know what I have to do to configure it correctly ?

I have tried to use SDL2 Gamepad Tool on windows without success
In the input tab of the unity launcher the joystick axis are working

Thanks a lot

**Comment by EricBoiseLGSVL** [comment]
@MaxandreOgeret 

We are currently working on wheel support and will be releasing it soon.  It is for the Logitect G920 wheel but if Unity detects your controller then it will be easy to switch over.  The force feedback functionality is not going to be supported on this release but will be supported in the future.

To configure any input use the new input system [[here](https://docs.unity3d.com/Packages/com.unity.inputsystem@1.0/manual/index.html)] and look at Assets/Scripts/Controllers/SimulatorControls.inputactions. Create a new sensor prefab, Add it to RuntimeSettings.asset SensorPrefabs array. Then add InputActions to the Vehicle mapping.  Unity detects the device and lists possible input from it.  Hopefully the new Input system will support generic wheels and force feedback in future releases.
