### ISSUE TITLE
how to add new scenes??

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#41]
I built new simulation environment and I want to add my environment to the menu.

![image](https://user-images.githubusercontent.com/10348912/49069019-93ce6680-f26b-11e8-8ee8-5d906863f973.png)

How can I add my environment to the menu??

**Comment by ruudyLiu** [comment]
1. Go to find and select a scriptableobject type project asset file in the path of "Assets/ScriptableObjects/DefaultAssetBundleSettings.asset"
2. Add one more element and drag your new scene(.unity file) into the Scene Asset field of the new element(another sprite field can be left empty) and save the change
![01](https://user-images.githubusercontent.com/8633842/49115134-bf8f2380-f24e-11e8-953a-9446023b76bd.JPG)

3. open unity Build Settings dialog, add your new scene there as well. This step is only required if you want to test your scene through editor. When you want to test your scene in standalone this step is not required.
![02](https://user-images.githubusercontent.com/8633842/49115148-c9b12200-f24e-11e8-84c9-c5823a82e6c3.JPG)

Let me know if that works

**Comment by hakuturu583** [comment]
I tested as you said, but new map was not appeared....
![screenshot from 2018-11-28 13-38-44](https://user-images.githubusercontent.com/10348912/49129458-473e6600-f313-11e8-9e97-598913fd228f.png)

![screenshot from 2018-11-28 13-40-18](https://user-images.githubusercontent.com/10348912/49129457-473e6600-f313-11e8-805a-4d45ad82c92d.png)

**Comment by ruudyLiu** [comment]
Did you change the DefaultAssetBundleSettings.asset map list? As I don't see you post any picture showing this step. Both DefaultAssetBundleSettings.asset and the Build Settings need to be changed in order to make this work.

**Comment by hakuturu583** [comment]
I succeed. Thanks!!

**Comment by martins-mozeiko** [comment]
Can you please confirm that you did following steps Ruudy explained above?

1. Select `Assets/ScriptableObjects/DefaultAssetBundleSettings.asset` in project panel.
2. In inspector panel increment `Size` for `Maps` array.
3. Set `Scene Asset` property for new element to the new `.scene` file you want.
4. Save the project, close Editor and then run the build on command-line with ` -executeMethod BuildScript.Build` argument.

See the following screenshot for how it should look like:

![image](https://user-images.githubusercontent.com/39178216/51494800-df365a00-1d6e-11e9-8da5-0ee7bb495653.png)

**Comment by hakuturu583** [comment]
I succeed Thanks!!
