### ISSUE TITLE
Multiple Cars in one scene

### ISSUE THREAD

**Issue by Andy823** [lgsvl/simulator#412]
Is it possible to simulate the situation that there are several, say 10 or 15 autonomous cars in one scene?

**Comment by martins-mozeiko** [comment]
It depends on performance of your computer and needed sensors. If every car needs lidar and cameras - then no, single CPU/GPU is not enough to do 10 cars. If you need only basic sensors (GPS, IMU) or no sensors at all, then 10 cars probably would work fine.

**Comment by EricBoiseLGSVL** [comment]
@Andy823 We are releasing distributed simulation soon that will support this functionality.
