### ISSUE TITLE
Building & Compiling Error

### ISSUE THREAD

**Issue by srirambadri** [lgsvl/simulator#416]
Hi,

I'm having an issue when I try to build Apollo 5.0.
![image](https://user-images.githubusercontent.com/8626656/66291446-2d31c480-e8e2-11e9-81de-f9ba0baa3e70.png)

I'm using Ubuntu 16.04 and I've tried to build the original fork of the apollo platform and it builds successfully.

**Comment by martins-mozeiko** [comment]
How are you compiling Apollo? Inside docker or outside?

**Comment by srirambadri** [comment]
Inside
I followed the instruction: https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/

**Comment by srirambadri** [comment]
I looked at the apollo.sh file and this is where the build fails ("at 2. build failed")
![image](https://user-images.githubusercontent.com/8626656/66316872-b7951b00-e918-11e9-8511-169e0b964876.png)

**Comment by srirambadri** [comment]
I managed to build 100% but I commented some lines in the apollo.sh file
![image](https://user-images.githubusercontent.com/8626656/66327207-b967da00-e92a-11e9-8539-ced9e160cce3.png)

the problem is that I'm not able to see and sensor data on the dream viewer 
![image](https://user-images.githubusercontent.com/8626656/66327307-eae0a580-e92a-11e9-8d72-26cd5ef9d62a.png)

**Comment by lemketron** [comment]
Is this still an issue? Might try apollo master as the lgsvl changes have been migrated upstream, though the lgsvl fork of apollo 5.0 seems to be building and working fine for most folks lately...
