### ISSUE TITLE
number restriction on count of targetLocalPositions

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#419]
Hey , I found that there are several c# scripts that deal with map annotations require count of targetLocalPositions to be more than 2. 
1. If a lane has only two points, when there is a stop lane at the end of this lane , I found that NPCs will not respond to traffic lights. But everything is fine when there are at least 3 points for lanes with stoplines.
2. at lane merge areas, if two lanes have only two points, these two lanes will have one overlapped end point, sometimes it will not be able to calculate the right neighbouring relationship of adjacent lanes and memory overflow errors may occur. But when I more points to these lanes, everything goes well. 
So is there a rule that all lane segments must have more than 2 points to describe their geometry? Or can we fix this issue by changing related code?
Because now lg simulator can support hdmap import, but if there are lanes with only two points, lg simulator will not be able to import the hdmap successfully.

**Comment by EricBoiseLGSVL** [comment]
@kissofwind 

Yes, we require 3 points for an lane annotation.  That is why the annotation tool creates lanes with  >= 3 points.  After we finish importer/exporter tools (which automatically create the missing points needed) we plan on revising NPCs to work with < 3 points.
