### ISSUE TITLE
installation issue with Unity Hub

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/simulator#423]
I have the same problem as thread 293 (https://github.com/lgsvl/simulator/issues/293), which is that Unity Hub fails to add the Simulator folder in its Projects tab (step 9 in the installation page). Just thought I would create a new issue because thread 293 has been dormant for a while. Tried the recommendations there, like logging out/in from Unity Hub, creating a new empty project,  removing UnityHub folder at ~/.config/UnityHub, but still cannot resolve the problem. When I try to open the project directly with Unity, it automatically opens Unity Hub, so I could not proceed with the installation.

**Comment by EricBoiseLGSVL** [comment]
@hyunjaecho94 
Have you updated Unity Hub?  This issue was fixed by updating.  What version are you using / OS?

**Comment by Iqbalparvi** [comment]
i also facing issue in step 12 in the installation link https://www.lgsvlsimulator.com/docs/build-instructions/
here when i click to INSTALL--->LOCATE--->no UNity folder found here as u can see below:
![no unity](https://user-images.githubusercontent.com/47267894/66538201-13f17800-eb6f-11e9-8bca-b0e1035ec0bf.png)
whats wrong with my installation to unity 2019.1.10f1, why the UNITY---> unity 2019.1.10f1 folder not generate here
thanks

**Comment by martins-mozeiko** [comment]
@Iqbalparvi Unity folder is here:

![image](https://user-images.githubusercontent.com/39178216/66576128-bdedf600-eba9-11e9-9ed1-a5191123b957.png)

**Comment by Iqbalparvi** [comment]
@martins-mozeiko thanks ,thats right so the instruction 12 select the launcher from unity folder means is this ....
![12](https://user-images.githubusercontent.com/47267894/66607543-32ec1a80-ec00-11e9-8c73-fb4c0ef5f75f.png)
if it is the right option then why the simulator cannot change the day time scene (always remains on night mode although i set daytime 12:00,2:30 3:00 etc ) and why the simulator runtime window  automaically trun off(close/disable). 
 
![black scene](https://user-images.githubusercontent.com/47267894/66607998-24eac980-ec01-11e9-9789-525225e09544.png)

**Comment by hyunjaecho94** [comment]
upgrading Unity Hub solved the problem. Thank you.
