### ISSUE TITLE
About ray tracing support

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#424]
Unity has released a version of ray tracing,Has ray tracing been supported?Thank U!

**Comment by martins-mozeiko** [comment]
If I'm not mistaken, the DXR support in Unity is still in preview, not in stable version. So nothing has changed from situation mentioned in #364.

That said, if you are interested in working on this, we would gladly accept pull request.

Closing issue, as it is duplicate of #364. Please continue discussion in one place.

**Comment by yumianhuli2** [comment]
> If I'm not mistaken, the DXR support in Unity is still in preview, not in stable version. So nothing has changed from situation mentioned in #364.
> 
> That said, if you are interested in working on this, we would gladly accept pull request.
> 
> Closing issue, as it is duplicate of #364. Please continue discussion in one place.

ok thanks!
