### ISSUE TITLE
.Json import/file converter & lane creation help

### ISSUE THREAD

**Issue by ninjacoder0** [lgsvl/simulator#426]
Hi I have 2 questions:

1. I have a .json tile map and would like to import it into the simulator, how can I do this? Any software you would recommend etc?

2. I have a map as shown in the image 2, although the map annotations are wrong, they dont appear on Apollo and I dont get any NPC running in Apollo or the simulator.  Can you please explain the organisation of this and what I am doing wrong, Thank you. 
Also as image 1 shows, I cant read the comments when hovering above a button, what can I do to see them/do you have any documentation to say what the buttons do. Thank you  for your great work! 

![Github2](https://user-images.githubusercontent.com/44463247/66582929-6c7a4280-eb7a-11e9-97f7-e597696d7c18.png)
![Github1](https://user-images.githubusercontent.com/44463247/66582930-6c7a4280-eb7a-11e9-9cff-08e23ba8a9b0.png)

**Comment by EricBoiseLGSVL** [comment]
@ninjacoder0 

1) I'd look at [this](https://docs.unity3d.com/Manual/JSONSerialization.html) for Json serialization. It's somewhat limited so you might want to get an asset from the Unity asset store if you need more options, like [this](https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347).  I would parse the json file and write editor code to create the tile map objects.  Look at MapAnnotations.cs to see how we created an EditorWindow to create scene objects.

2) Please look at [this](https://www.lgsvlsimulator.com/docs/map-annotation/) documentation to create an HDMap.  For NPCs to understand your annotation they need to be grouped into traffic lanes and intersections with holder objects and classes.

Look for other tilemap json importer examples on the web that will help.  Glad you like the simulator and let us know if you have issues.

**Comment by ninjacoder0** [comment]
1. seems quite difficult but will continue looking into it.

What about .xml  files. Would you know how to import .xml files into unity/LG sim?

**Comment by martins-mozeiko** [comment]
Unity has xml parser because it is part of .NET Framework libraries. But it will not know what to do with the data. Same situation as with json. You will need to write code that takes output of xml parser and produces meaningful results in the Unity scene.
