### ISSUE TITLE
lgsvl /apollo fork clone error

### ISSUE THREAD

**Issue by Iqbalparvi** [lgsvl/simulator#427]
hi all;
i try to clone the lgsvl/apollo fork 5.0 using git lfs clone --recurse-submodules https://github.com/lgsvl/apollo-5.0.git
 then the error occurrs : 
![p1](https://user-images.githubusercontent.com/47267894/66695155-bb0a1700-ed09-11e9-850d-3cfb28b3144b.png)
and 
git clone --recurse-submodules https://github.com/lgsvl/apollo-5.0.git gives error:
![p2](https://user-images.githubusercontent.com/47267894/66695187-2358f880-ed0a-11e9-933a-79f98f425c53.png)
anyone knows whats going wrong here
thanks

**Comment by martins-mozeiko** [comment]
That sounds like issue with your network. Not being able to resolve github.com hostname can be fixed only on your side.
