### ISSUE TITLE
LGSVL simulator runtime disappear suddently 

### ISSUE THREAD

**Issue by Iqbalparvi** [lgsvl/simulator#428]
Hi LG;
After build succes the standalone it show two differnt error for me:
1. the simulator run but it shows the dark enviroment only although i canhge gthe build time to 12:00 ,1:30 etc and there is no play button  found in the simulator:
![sim1](https://user-images.githubusercontent.com/47267894/66711492-b3fe0a00-edd8-11e9-9e12-5141c720b6df.png)
2. when connect the bridge and run apollo -5.0 fork then open the modules transform the running simulator suddently disappear 
i s there any problem in the unity loader/launcher to load the scene ,,, need sugestions to solve this problem asap
thanks

**Comment by martins-mozeiko** [comment]
1.

Play button is visible only to interactive simulation. For non-interactive time will always be running forwards.

Are you saying environment is always black regardless of what time you set? 01:00, 12:00, 18:00, 23:00?

2.

This could be related to running out of GPU memory issue. Check the log file. If at the end it has similar call stack to log file in #326 then your machine does not have enough memory to run BorregasAve together with Apollo. Read my reply on that issue.

**Comment by Iqbalparvi** [comment]
thanks @martins-mozeiko  
![6](https://user-images.githubusercontent.com/47267894/66791318-74056700-ef3f-11e9-9a8c-710911a6bdcc.png)
yes i change the time in localhost :8080 during the simulation setting but there is no option to change the time in runtime simulation and no play button : 
![7](https://user-images.githubusercontent.com/47267894/66791390-c8a8e200-ef3f-11e9-85b3-dea098c7218c.png)
and for GPU memory when we run nvidia-smi we see that volatile  GPU util is 0% so it means it is out of memory 
![8](https://user-images.githubusercontent.com/47267894/66791665-e0cd3100-ef40-11e9-9fdc-ab975073d25e.png)

**Comment by martins-mozeiko** [comment]
Play button and time changing functionality is enabled only for **interactive** simulation. Put checkbox next to interactive setting: https://www.lgsvlsimulator.com/docs/images/full_size_images/web-simulation-mapVehicle.png

**Comment by Iqbalparvi** [comment]
@martins-mozeiko  ,the play button and time changing functionality found but the darkness remains same and not change by changing the time .....
2ndly the runtime simulator suddently disappear ....? when i  check the gpu consemption using 
sudo watch nvidia-smi  then its shows the GPU consumtion increase slowly from 0 to 100
![9](https://user-images.githubusercontent.com/47267894/66802896-b774cb00-ef69-11e9-8d51-eaaeb7154569.png)

 and as it reach 100 % the simulator disappear ...how to fixed this issue without losing the previous works ..
thanks

**Comment by martins-mozeiko** [comment]
Because your GPU has only 6GB of memory I'm pretty sure this is because of running out of memory.

We recommend using GPU with 8GB or more if you want to load high quality maps such as BorregasAve or AutonomouStuff. These maps uses high detail textures that uses a lot of memory. Especially when you want to run simulator together with Apollo on same machine.

**Comment by Iqbalparvi** [comment]
@martins-mozeiko Shocking ...I recently purchased this system  for my experiment purpose and at the initial stage only apollo run very good in this system but when we combine  LG then at the ist time it work good but bit slow  at low graphic mode ....as we make some progress it suddenly shows this termination problem and my RAM is 16 GB as per my understanding NVIDIA GFORCE GTX 1060 : 
![10](https://user-images.githubusercontent.com/47267894/66877503-6c0dfb80-f001-11e9-8264-e1afb088ff0f.png)
but when the command lspci -v -s 00:02.0 it gives 
![11](https://user-images.githubusercontent.com/47267894/66877534-8c3dba80-f001-11e9-96c7-ba15aaa9748d.png)
is there any proper way to confirm the GPU information ...really shocking at this stage

**Comment by martins-mozeiko** [comment]
16GB is your regular memory amount, not GPU memory amount. nvidia-smi shows amount of GPU memory you have: 

![image](https://user-images.githubusercontent.com/39178216/66877794-d07e7b80-ef6b-11e9-9859-6a4b6f48a1b0.png)

Simulator itself should be fine with 6GB of memory, but if you run something else, like Apollo or Web browser with a lot of tabs, then that uses more memory, so simulator will run out of memory. Apollo itself uses significant amount of memory for its GPU perception (DNN networks).
