### ISSUE TITLE
rostopics and ros messages used by autoware for sensor data

### ISSUE THREAD

**Issue by Aquarian-source** [lgsvl/simulator#429]
hey i have basic question. i have to develop an app based on autoware based model. what are the rostopics and ros messages used for sensor data(camera, lidar and imu also) and also for vehicle control. any guidance would be a huge help

**Comment by martins-mozeiko** [comment]
When you run Autoware together with simulator you can use `rostopic` command to examine topics and their message types. Run `rostopic list` to see list of topics, and `rostopic info TOPIC` to see what message type it uses. Alternatively use Bridge UI panel to see what topics simulator is publishing or subscribing: https://www.lgsvlsimulator.com/docs/bridge-connection-ui/
