### ISSUE TITLE
AssetBundles(BorregasAve)not found in unity  

### ISSUE THREAD

**Issue by Iqbalparvi** [lgsvl/simulator#431]
Hello I want to draw my own Map using Map Annotation using unity and import to apollo through lg ....but when i follow the instruction of MAp annotation i dont see the Assetsbundles(BorregasAve) as see here in the instructions: 
![12](https://user-images.githubusercontent.com/47267894/66880277-f0ff1200-f00d-11e9-8403-a2e63faa7cee.png)
and i dont understand the steps 25,26,27 ..as my unity screen looks like as : 
![14](https://user-images.githubusercontent.com/47267894/66880320-1f7ced00-f00e-11e9-9c5f-6ebbff560350.png)
then  can i simply go to the contents website to manually download and copy the folder into Assets/external/environments ? or any other way to to  got the same assets bundles and draw  a simple map in unity

**Comment by daohu527** [comment]
The "BorregasAve" map is not opensource. You can use another sample map [SingleLaneRoad](https://github.com/lgsvl/SingleLaneRoad).
1. download the SingleLaneRoad
2. put in into "simulator/Assets/External"
3. open the "SingleLaneRoad" scene

You can refer to this example to create your own map. Hope this will help!
