### ISSUE TITLE
Build Maps&Vehicles

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#436]
Hello!I downloaded CubeTown  SingleLaneRoad and Jaguar2015XE  and put them into External/Environments and Vehicles folders , then I clicked Build button there is  no reaction from unity.How about this?
![Screenshot from 2019-10-17 17-50-52](https://user-images.githubusercontent.com/39210837/66998440-d8265780-f106-11e9-898e-c67981506b32.png)

**Comment by martins-mozeiko** [comment]
Is there nothing printed out in console? Error or warning message?

Try providing path where to build simulator. Currently you have this field completely empty.

**Comment by daohu527** [comment]
You should choose a folder to save the build files. This option is located in the "Build Simulator" of the image.
