### ISSUE TITLE
AssetBundles (step 16 of installation) missing

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/simulator#439]
I'm following installation instructions (https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md), but when I do Simulator > Build in Unity, I have blank Environments and Vehicles. AssetBundles does not seem to exits within the clone. Is my installation incomplete? I installed git lfs before cloning the repository.

![build](https://user-images.githubusercontent.com/10676339/67042263-86290600-f0f5-11e9-9ff2-da8c94c946be.png)

![assets](https://user-images.githubusercontent.com/10676339/67042270-8923f680-f0f5-11e9-8cc5-6b8d17f2c13d.png)

**Comment by martins-mozeiko** [comment]
Please check answers in following issues - #379 #318 #320 #316
