### ISSUE TITLE
Missing Simulator.exe

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/simulator#440]
In step 2 of testing simulator after installation, it says to double-click Simulator.exe. However, I cannot find the file. Which step in my installation could have gone wrong?

**Comment by martins-mozeiko** [comment]
What installation steps are you referencing?
Simulator.exe is inside release zip file that you can download from [Release](https://github.com/lgsvl/simulator/releases) tab in GitHub.

**Comment by hyunjaecho94** [comment]
I was referencing https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md. Step 2 under Test Simulator (Double-click the Simulator.exe that was built).

**Comment by hyunjaecho94** [comment]
So I downloaded the zip file and was able to get Simulator.exe. However, I'm not sure what step 3 of the installation page (under Test Simulator) means by "Select graphics options then press Ok". Here's what I get from Simulator.exe.

![simulatorexe](https://user-images.githubusercontent.com/10676339/67149889-e26b6180-f27e-11e9-97c8-74fd7ac1b770.png)

**Comment by martins-mozeiko** [comment]
simulator.exe file is from zip file for Windows. You need to download Linux zip file if you want to run Simulator on Ubuntu.
