### ISSUE TITLE
Simulations Failed

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#442]
Hello!
Map is ok!
![Screenshot from 2019-10-20 17-42-21](https://user-images.githubusercontent.com/39210837/67157609-01422480-f361-11e9-962e-bd5507dc6123.png)
Vehicle is ok!
![Screenshot from 2019-10-20 17-43-12](https://user-images.githubusercontent.com/39210837/67157624-246cd400-f361-11e9-983c-93d7c5cb3134.png)
But can not select bridge!
![Screenshot from 2019-10-20 17-44-05](https://user-images.githubusercontent.com/39210837/67157638-5120eb80-f361-11e9-94d7-6b60070df5cf.png)
Finally,Simulation mode test invaild!
![Screenshot from 2019-10-20 17-47-02](https://user-images.githubusercontent.com/39210837/67157655-a78e2a00-f361-11e9-9ce2-c96ebd31eba2.png)
And I built AssetBundle successed!
![Screenshot from 2019-10-20 17-49-22](https://user-images.githubusercontent.com/39210837/67157680-fb007800-f361-11e9-8ec8-26488163d39e.png)

How can I run simulation sucessful?thank you!

**Comment by martins-mozeiko** [comment]
Please check the [log file](https://www.lgsvlsimulator.com/docs/faq/#where-are-unity-log-files-located) for more detailed error message.

**Comment by yumianhuli2** [comment]
> Please check the [log file](https://www.lgsvlsimulator.com/docs/faq/#where-are-unity-log-files-located) for more detailed error message.

![Screenshot from 2019-10-21 11-21-01](https://user-images.githubusercontent.com/39210837/67174526-e8834e80-f3f4-11e9-9e4f-344f7b219be6.png)

**Comment by martins-mozeiko** [comment]
You should start simulation from Web interface and when it fails, look at bottom of file for any error messages. Without out more detailed error message it is very hard to guess what could be wrong.

**Comment by yumianhuli2** [comment]
> You should start simulation from Web interface and when it fails, look at bottom of file for any error messages. Without out more detailed error message it is very hard to guess what could be wrong.
just say this..without more detailed error message 
error message just :+1: System.ArgumentException: Kernel 'KSampleCopy4_1_x_8' not found.

![Screenshot from 2019-10-23 17-17-25](https://user-images.githubusercontent.com/39210837/67378283-9e979580-f5b9-11e9-8ef4-2cdf7638d29c.png)
