### ISSUE TITLE
Driving from point A to B by giving waypoints in dreamview 

### ISSUE THREAD

**Issue by hyunjaecho94** [lgsvl/simulator#448]
Inside the simulator, when I manually move the vehicle, the vehicle in the simulator also moves, suggesting the simulator is connected to dreamview. However, when enabling Localization, Transform, Traffic Line, Planning, Prediction, Routing, and Control, Perception and Traffic Line  automatically get switched off. When I give waypoints under Route Editing, the vehicle in the simulator does not move. No NPC vehicles or sensor data are visible. Here are some information that may be helpful. Related: @399
`git lfs install` > `Git LFS initialized.`
`nvidia-smi`
![nvidia-smi](https://user-images.githubusercontent.com/10676339/67601073-7fc40b00-f741-11e9-9274-8f00247b1e02.png)

Result from running ` perception.sh start_fe`

![2](https://user-images.githubusercontent.com/10676339/67639327-cdb54c00-f8c4-11e9-9950-c656126d81a1.png)
![3](https://user-images.githubusercontent.com/10676339/67639328-cdb54c00-f8c4-11e9-8aa3-93fbb22f9d04.png)

**Comment by martins-mozeiko** [comment]
Permission denied errors probably comes from a fact that you have run dev_start.sh with sudo previously. This means Apollo created folders with root user. And now your user cannot write to these folders or files. Try running `chown` on all apollo files & folders to reset owner to your user/group.

Is first screenshot of nvidia-smi from inside of docker container or on host? Verify that nvidia-smi works also inside container.

**Comment by hyunjaecho94** [comment]
@martins-mozeiko 
`nvidia-smi` does not work inside the container..

**Comment by martins-mozeiko** [comment]
Please check output of `docker info | grep Runtimes` command on your host. It should show:

    Runtimes: nvidia runc

Also you should have `nvidia-docker` executable available (Apollo will try to use it). If you don't have these two conditions, then something is not installed correctly with nvidia docker. If I remember correctly you need to install nvidia-docker2 package.

Make sure docker correctly works with nvidia runtime before continuing with building Apollo & using Simulator.

**Comment by hyunjaecho94** [comment]
Progress: `docker info | grep Runtimes` worked, `nvidia-docker` was giving command not found. Followed instructions here https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0) to get `nvidia-docker` working and perception is now working on Dreamview. Dreamview detects other NPC vehicles. 

However, when given a waypoint on Dreamview, a route is generated, but EGO does not move. Also, before perception worked, when EGO was in the way of other NPC vehicles, they would crash into EGO, but now NPC stops if EGO is in the way. Does enabling perception also allow perception for NPC vehicles?

**Comment by martins-mozeiko** [comment]
NPC crashing into EGO or not is just a random behavior. Apollo perception does not affect NPC vehicles.

We sometimes see that Apollo vehicle does not start driving automatically. If it has path set and Control module is enabled, try helping it a bit - press Arrow up key to manually move car for short amount of time. After that Apollo should automatically take control.

**Comment by hyunjaecho94** [comment]
@martins-mozeiko I tried that, but EGO just moves straight. 

[dreamview.tar.gz](https://github.com/lgsvl/simulator/files/3780921/dreamview.tar.gz)

**Comment by hyunjaecho94** [comment]
works perfectly now. Very much appreciate it!
