### ISSUE TITLE
Why I can't control the vehicle in simulator by using arrow?

### ISSUE THREAD

**Issue by simon13579** [lgsvl/simulator#454]
Hello,

I download the Windows64 simulator 2019.09, run .exe file and setup a new simulations as below:
![Edit](https://user-images.githubusercontent.com/38149116/67767817-37338700-fa8c-11e9-840a-1de6a3f50204.png)
![Map](https://user-images.githubusercontent.com/38149116/67767820-3864b400-fa8c-11e9-8141-3c2b2ad7976f.png)

Then simulation run and the vehicle shows, but I can't use arrow to manually control the vehicle, only WASD key works.

Thanks,
Simon

**Comment by martins-mozeiko** [comment]
To be able to control vehicle with keyboard you need to add [Keyboard Control](https://www.lgsvlsimulator.com/docs/sensor-json-options/#keyboard-control) sensor to vehicle.
