### ISSUE TITLE
Separate simulation

### ISSUE THREAD

**Issue by mkhayatian** [lgsvl/simulator#456]
Can I run the LG simulator on one machine and autoware/apollo on another machine that are connected through LAN?
If yes, how?

**Comment by martins-mozeiko** [comment]
Yes, you can. 
You do it exactly same way how you would run everything on same machine, except when you are adding vehicle to simulation in WebUI - there you would put IP address of machine which runs AD stack (rosbridge/cyberbridge) instead of 127.0.0.1.

**Comment by mkhayatian** [comment]
Thanks!
