### ISSUE TITLE
LGSVL build from source issue

### ISSUE THREAD

**Issue by ningfeiwang** [lgsvl/simulator#457]
Hello,

I am working on build the newest version LGSVL from source following the instruction https://www.lgsvlsimulator.com/docs/build-instructions/

When I go into step 23 (Build WebUi... in Unity: Simulator -> Build WebUI...), I found out 
![image](https://user-images.githubusercontent.com/31480587/67819049-dba7d000-fa70-11e9-9650-5677ac1f7b0b.png)

Could you please help me to handle such problems? Thank you

My system is Ubuntu 18.04.

**Comment by martins-mozeiko** [comment]
This is harmless error message. It comes from some internal components of Unity and we cannot do much about it. But it does not prevent anything to work. Simulator will run just fine. Press `Clear` button in corner to get rid of this error message.

**Comment by ningfeiwang** [comment]
Thank you. I just clear it and continue building it after clone the maps and vehicles. But I met this problem. Could you please help me again?

![image](https://user-images.githubusercontent.com/31480587/67823532-b6bb5900-fa80-11e9-8756-140e81a0e21f.png)

**Comment by martins-mozeiko** [comment]
You need to install Windows support when you are installing Unity. When Simulator builds assets we build "universal bundle" - one file that works both on Windows and on Linux. For this to work you need to have installed both - Windows and Linux support when installing Unity.

**Comment by KrzysztofDabek** [comment]
I have coped with that kSampleCopy problem just as in this topic on unity:
https://forum.unity.com/threads/kernel-ksamplecopy4_1_x_8-not-found-under-unity-2018-3.597463/

Reimporting HDRP worked. Also please make sure you have vulkan libs installed as in the building from source tutorial
