### ISSUE TITLE
HD Map Annotation cannot view waypoint

### ISSUE THREAD

**Issue by liiiu** [lgsvl/simulator#458]
hi, lg
i loaded the SingleLaneRoad scene, i want to use the hd map annotation tool to cerate waypoint.

but when i click "view all", i cannot see the waypoints or segment ...

what's the problem? thx
![image](https://user-images.githubusercontent.com/49083466/67847257-7ec61b80-fb3d-11e9-9b08-4dbae4c48be9.png)

**Comment by daohu527** [comment]
Could you pls confirm that the files in "SingleLaneRoad" is complete? There is no error message in console?

**Comment by martins-mozeiko** [comment]
Please verify that you have not turned off Gizmo rendering for MapLane & other map annotation objects. Click "Gizmos" button at top of scene view and check that all checkboxes are enabled.

**Comment by liiiu** [comment]
Thank you very much, it turned out that I accidentally turned off gizmos.
