### ISSUE TITLE
How to build a road to export to .xodr ?

### ISSUE THREAD

**Issue by ninjacoder0** [lgsvl/simulator#460]
Hi

I managed to export the "Straight Road" no problem as an .xodr although using EasyRoad3D, im not able to create a road which I can export to .xodr.

Could you please suggest how I could create a road which can be exported as .xodr format. Thank you

**Comment by luqiang21** [comment]
@ninjacoder0 Can you let me know what errors or problems you are having to generate `.xodr` file? Maybe this video tutorial can help you https://www.youtube.com/watch?v=MT7F5fPfM90&feature=youtu.be
