### ISSUE TITLE
maporigin data type issue

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#463]
in mapOrigin class  the coordinates of maporigin in utm map are stored in the two member variables 
```
    public partial class MapOrigin : MonoBehaviour
    {
        public float OriginEasting;
        public float OriginNorthing;
```
The data type of the two variables are both float, this could cause precision problems. E.g. in Baoding(China), the Northing coordinate is over 4 200 000 meters, float type is not able to store the fractional part precisly, so the maporigin could have up to 0.5 meter error. which could cause ads stack fail if the relys on hd map.

**Comment by martins-mozeiko** [comment]
You're right, we should change it to double.
