### ISSUE TITLE
MapOrigin Editor Rounding Issue

### ISSUE THREAD

**Issue by moenasrallah** [lgsvl/simulator#466]
When Origin Easting and Northing are entered in the editor for MapOrigin, it is converting from string (values entered in the editor) to float (values in the maporigin script).

This is rounding the UTM coordinates to inaccurate values, causing bad and unnecessary offsets. I believe the solution for this is to take in the input from the editor as a string, and then do proper conversion to float so no rounding happens.

This is especially true with Northing (larger value)

**Comment by moenasrallah** [comment]
Example: Entering 4321398.52 for either Easting or Northing will appear as 4321399

**Comment by martins-mozeiko** [comment]
I think you mean that it is rounded to float, not double. as OriginEasting and OriginNorthing is floats inside MapOrigin component.

This is already reported in #463. We'll change it to double.

**Comment by moenasrallah** [comment]
Yes, sorry, I edited it. Sorry for posting a duplicate issue. I will move comments onto there and close this
