### ISSUE TITLE
HD Map Export Does Not Work

### ISSUE THREAD

**Issue by taylorsrichard** [lgsvl/simulator#47]
Hi, I am using the project as is without any changes from the latest merge and I am having an issue exporting the SanFrancisco HD map. Whenever I click "Export HD Map", I get a console error saying that "Some lane segments neighbor relationships are wrong, map generation aborts", followed by "One problematic lane was detected". Can you explain what is causing this issue and suggest a solution? 
Thank you.

**Comment by hadiTab** [comment]
@taylorsrichard we seem to have made some mistakes in the HD map annotation we pushed to github. We are working on resolving it. Thanks for pointing it out.

**Comment by taylorsrichard** [comment]
@hadiTab Thanks for the prompt response. Glad to know you're working on it.
