### ISSUE TITLE
How to get speed from Apollo?

### ISSUE THREAD

**Issue by lethaimai** [lgsvl/simulator#470]
Hi everyone,
i am trying to get the the speed of the car in real time. I have found another question from the topics #355 , but when i tried to get the message from topic, it showed me an error like in the picture.
****
![Selection_001](https://user-images.githubusercontent.com/53815302/68283039-12867300-007b-11ea-82c6-3d1b0f323036.png)

How can i solve this problem?

**Comment by martins-mozeiko** [comment]
pb_msgs is customized ROS message type from Apollo which is available only inside Apollo ROS environment. You need to run rosmsg/rostopic and other ros commands inside Apollo Docker environment.
