### ISSUE TITLE
SocketException Error

### ISSUE THREAD

**Issue by srirambadri** [lgsvl/simulator#471]
Hi,

I'm getting a SocketException: Connection refused error. Does anyone have some idea as to why I'm getting this error and how I can about solving this?

I'm running the simulator executable version [from here](https://github.com/lgsvl/simulator/releases/tag/2019.10), on Ubuntu 16.04 with a RTX208TI GPU  

![error](https://user-images.githubusercontent.com/8626656/68293354-0eb01c00-008e-11ea-87e3-0e25f890ed78.png)

**Comment by Kailiangdong** [comment]
Same problem. Do you solve it?

**Comment by martins-mozeiko** [comment]
@Kailiangdong you need to make sure you run rosbridge or cyberbridge, and put in correct IP address & port in simulation configuration.
