### ISSUE TITLE
Environment Source Code

### ISSUE THREAD

**Issue by KrzysztofDabek** [lgsvl/simulator#481]
Hi,

I have been working on modifications to LGSVL simulator and I see that the source for SingleLaneRoad, Shalun and CubeTown are available on github. Would you by any chance upload AutonomouStuff and BoregasAve too?

**Comment by martins-mozeiko** [comment]
AutonomouStuff and BoregasAve maps uses assets under license that does not permit distributing them in source form. We can release these maps only as compiled binary assets.

That said, we will be releasing SanFrancisco map from old simulator (we are currently in process of upgrading it to HDRP materials). And we will be working on plugin mechanism to extend map with custom objects and behaviors at runtime.

**Comment by KrzysztofDabek** [comment]
Okay. Thank you for that information.
