### ISSUE TITLE
NPCController control algorithm questions

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#482]
Hi, when reviewing the NPCController code and using lg sim for ads testing,  I found a few questions about NPCController module.
* Lane following algorithm, according to  my understanding of the `SetTargetTurn()` , the way NPC follows the target lane is like in the following figure:
![image](https://user-images.githubusercontent.com/26409968/68731510-4af1f800-060b-11ea-8202-2c09addef8c5.png)

which is actually a p controller plus a 1st order low pass filter, It can have a quite stable performance in lanekeeping scenario, but when I control the npc to do a lane change using python api, the the npc will have a stability issue after lane change, which looks like the red curve inthe following figure:
![image](https://user-images.githubusercontent.com/26409968/68678139-5bb55600-0598-11ea-978c-fbb8ab8f9062.png)
I am not sure if it is because of the map annotation or I need to tune the parameters in the controller. So I am asking if you have met with such behavior before. and any suggestions how to fix this.
* Target Point Calculation, in ` EvaluateTarget()`, the way to update the target point is 
```
Vector3.Dot(frontCenter.forward, (currentTarget - frontCenter.position).normalized) < 0 || distanceToCurrentTarget < 1f
```
but I think there is an edge case when npc is performing an lane change:
![image](https://user-images.githubusercontent.com/26409968/68678938-e6e31b80-0599-11ea-887d-3b95d9249c6c.png)

the longitudinal distance is less than 1 meter but the lateral distance is still over 1 meter, so the the above algo, it will not update the target point while it should. So I am thinking maybe 
```
Vector3.Dot(frontCenter.forward, (currentTarget - frontCenter.position)) < 1f || distanceToCurrentTarget < 1f
```
is better
* Lane Change completion judgement missing, in my understanding the way how npc make a lane chage is like just change the target adjacent lane as current lane, so npc will try to follow the new target lane.  but seems there is no judgement on when the lanechange operation is over, which makes it difficult for python api side to get the info of lane change completion. so I want to know do you have any plan on adding this feature? This feature is very useful when we try to make some complicated scenario.
Thanks.

**Comment by EricBoiseLGSVL** [comment]
@Vincent-Tsui-GWM 

Nice breakdown of the NPC change lane logic and finding this edge case.  We will look into solutions to enhancing NPC lane change behavior.
