### ISSUE TITLE
Set time of day during simulation.

### ISSUE THREAD

**Issue by liiiu** [lgsvl/simulator#487]
hi，lg team

I tried to run the SingleLaneRoad map. I set the weather parameters "Time of Day" in the web page, but it doesn't seem to change. My simulation scene has been dark night. 

Please tell me how to solve. thanks

**Comment by david-gwa** [comment]
there is an issue mentioned [#428](https://github.com/lgsvl/simulator/issues/428),

looks the most recent release 2019.10 has fixed it, check  [changelog](https://www.lgsvlsimulator.com/docs/changelog/)
