### ISSUE TITLE
BorregasAve is not available

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#490]
I am currenty following the instruction outlined in the getting started with the pythonAPI. When I tried to run the sample code 05-ego-drive-in-circle, I get the following errors:

PythonAPI-2019.10-rc1/quickstart$ python3 05-ego-drive-in-circle.py 
Traceback (most recent call last):
  File "05-ego-drive-in-circle.py", line 15, in <module>
    sim.load("BorregasAve")
  File "/PythonAPI-2019.10-rc1/lgsvl/utils.py", line 21, in new_f
    return f(*args, **kwargs)
  File "/PythonAPI-2019.10-rc1/lgsvl/simulator.py", line 36, in load
    self.remote.command("simulator/load_scene", {"scene": scene, "seed": seed})
  File "/PythonAPI-2019.10-rc1/lgsvl/remote.py", line 68, in command
    raise Exception(data["error"])
Exception: Environment 'BorregasAve' is not available

Please, what does this error mean?

**Comment by martins-mozeiko** [comment]
You need to first add it to the simulator. In the webui go to Maps section: https://www.lgsvlsimulator.com/docs/maps-tab/#how-to-add-a-map
And add the BorregasAve there. You can get link to map file from content website: https://content.lgsvlsimulator.com/

**Comment by Francisobiagwu** [comment]
![bg](https://user-images.githubusercontent.com/19335305/68795396-dcb73080-061e-11ea-92fe-25ca1561b8ae.png)

it is already there. but the error persists

**Comment by martins-mozeiko** [comment]
The name is different. Python script looks up maps by name. You have added "Borregas Avenue", but Python script is asking for "BorregasAve".

**Comment by Francisobiagwu** [comment]
Thanks. That fixed it.
