### ISSUE TITLE
Vehicle not navigating to destination

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#494]
These are the instruction under running he simulator with Apollo 5.0:
Navigate to the Route Editing tab.
Select a destination by clicking on a lane line and clicking Submit Route.
Watch the vehicle navigate to the destination.

However, when I select the destination as shown. After clicking on the 'send routinng request', the vehicle doesn't move. 

![routingng _eidit](https://user-images.githubusercontent.com/19335305/68868469-95d04600-06c5-11ea-8371-531988480e53.png)
![no_play_button](https://user-images.githubusercontent.com/19335305/68868476-98cb3680-06c5-11ea-86e2-601c6a24d37e.png)
![no_Play_button2](https://user-images.githubusercontent.com/19335305/68868482-9b2d9080-06c5-11ea-8e9d-74b03ee5ea8b.png)

**Comment by martins-mozeiko** [comment]
I think your EGO vehicle hit other vehicles, that's why it cannot move along the planned path.

**Comment by Francisobiagwu** [comment]
I did a reset but the issue persists.


![navigation_not_working_2](https://user-images.githubusercontent.com/19335305/68889647-4e5cb080-06eb-11ea-9a86-625fbdadcd45.png)

**Comment by Francisobiagwu** [comment]
it works now.

**Comment by khsrhhh** [comment]
> it works now. However the vehicle is not always smart. Sometimes, it keeps crashing into the woods.

Hi.
Now I'm facing same issue on Apollo 5.0.

Instruction sequence:
1. Set referenced ego car (Lincoln2017MKZ) and referenced map (Borregas Ave) in Dreamview
2. Turn all modules on except control module in Dreamview
3. Select end point (check the red line appears) and click 'Send Routing Request' button
4. Turn control module on in Dreamview
5. Noting happen (the green area does not appear)

Could you tell me how did you control car?

Thanks.

**Comment by khsrhhh** [comment]
> > it works now. However the vehicle is not always smart. Sometimes, it keeps crashing into the woods.
> 
> Hi.
> Now I'm facing same issue on Apollo 5.0.
> 
> Instruction sequence:
> 
> 1. Set referenced ego car (Lincoln2017MKZ) and referenced map (Borregas Ave) in Dreamview
> 2. Turn all modules on except control module in Dreamview
> 3. Select end point (check the red line appears) and click 'Send Routing Request' button
> 4. Turn control module on in Dreamview
> 5. Noting happen (the green area does not appear)
> 
> Could you tell me how did you control car?
> 
> Thanks.

Just enter up key in keyboard clears the issue.
