### ISSUE TITLE
Controlling different Ego vehicles with python

### ISSUE THREAD

**Issue by Francisobiagwu** [lgsvl/simulator#495]
The WebUI allows the addition of multiple Ego vehicles to the scene. Please, is there a way for me to use for example 2 different python scripts to control the behavior of the vehicles simultaneously? As shown below:

 
![controlling_multiple_vehicles](https://user-images.githubusercontent.com/19335305/68871313-3cb6e100-06ca-11ea-8d85-50f3218801af.png)

**Comment by martins-mozeiko** [comment]
You don't really need two Python scripts. You can create multiple EGO vehicles from same script. Just add more calls to `sim.add_agent` method. You can position them wherever you want and connect to different bridge instances - that will be controlled by different AD stacks.

**Comment by daohu527** [comment]
Additionally, if I add two ego cars in the web UI. They cannot be reused and the names of the two cars must be different.

**Comment by Francisobiagwu** [comment]
Thanks. Please, can you explain further how to connect to them using different bridge instances

**Comment by martins-mozeiko** [comment]
Simply call `connect_bridge` on separate agent instances:

    agent1 = sim.add_agent("vehicle name 1", lgsvl.AgentType.EGO, state1)
    agent2 = sim.add_agent("vehicle name 2", lgsvl.AgentType.EGO, state2)

    agent1.connect_bridge("bridge address 1", 9090)
    agent2.connect_bridge("bridge address 2", 9090)
