### ISSUE TITLE
error display about localhost:8080

### ISSUE THREAD

**Issue by clouddd9** [lgsvl/simulator#499]
when I build the lgsvl simulator using Unity3D and open the simulator, the localhost:8080 showed as follows:
![2019-11-16 18-06-42屏幕截图](https://user-images.githubusercontent.com/34005180/68991677-337d6e00-089c-11ea-98e8-d516d49cabb3.png)
 what's wrong with it? how can I fix it?

**Comment by daohu527** [comment]
There may be several reasons for this:
1. Did you run “npm install“ in the WebUI and compile the WebUI in Unity?
2. In browser debug mode, check the console for error messages?

**Comment by martins-mozeiko** [comment]
Try clearing browser cache, or doing full referesh - `Ctrl + Shift + R`. It might be that your browser cached some css files from previous versions for WebUI.
