### ISSUE TITLE
About Apollo HD map import 

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#500]
Has been directly supported for Apollo HD map(xodr format) import？

**Comment by martins-mozeiko** [comment]
Yes, we support importing Apollo HD map. We support importing Apollo 5.0 map, Autoware map, Lanelet2 and OpenDrive 1.4 formats.

**Comment by duong-pa** [comment]
how to import opendrive map? 
more specific: how to convert openddrive map to apollo map?

Thank you

**Comment by martins-mozeiko** [comment]
`Simulator -> Import HD Map` menu time will allow you to import various formats of HD maps, including OpenDrive.

As to how convert OpenDrive to Apollo map, I don't know. You should ask that to Apollo developers - what is their suggested workflow for converting hd maps to Apollo format.
