### ISSUE TITLE
Autoware and LGSVL

### ISSUE THREAD

**Issue by ningfeiwang** [lgsvl/simulator#501]
Hello,

I follow the instruction here https://www.lgsvlsimulator.com/docs/autoware-instructions/ to build the LGSVL and Autoware together. When I go to step Click "Map" to load the launch file pertaining to the HD maps,  only Borregas shows 'OK'. I wonder whether I can use other maps like Shalun.

When I try to load Shalun, it seems the HD map is loaded. But I cannot find the car and cannot initialize the position. Could you please help me to handle such problems? Thank you very much.
![image](https://user-images.githubusercontent.com/31480587/69029414-b29ca000-0989-11ea-8e9c-9a5c0c6aa0ca.png)

**Comment by martins-mozeiko** [comment]
Just to clarify - you are setting initial position of vehicle in rviz on this map? This is required for NDT localization, you need to provide EGO vehicle position. Sometimes it does not work on first try, so you need to repeat this process few times until it localizes.

**Comment by ningfeiwang** [comment]
Thank you and sorry for the late reply. I tried it for several times but it still does not work (does not appear any car information in the above map). Do I need to open some computing component in that case like NDT mapping? Thanks.
