### ISSUE TITLE
png files throw error in  Unity build - "File could not be read"

### ISSUE THREAD

**Issue by tkbala** [lgsvl/simulator#502]
Hi,

I am trying to build the SingleLaneRoad scene from the unity editor. However, upon trying to build using "Simulator"->"Build"-"Build", I get the following error

![image](https://user-images.githubusercontent.com/4410442/69095280-d4883800-0a06-11ea-9eb3-fc73b18d809d.png)

**Comment by martins-mozeiko** [comment]
Can you check if these files exist in Assets folder? And that they are reasonable - for example, png file should be an image.

**Comment by tkbala** [comment]
Yes, the files exist. Here is a screenshot of the Jaguar2015XE folder containing the png files.

**Comment by martins-mozeiko** [comment]
Where is screenshot?
And those files are real files? Can you open them to see image?

**Comment by tkbala** [comment]
Ah! Here's the screenshot
![image](https://user-images.githubusercontent.com/4410442/69100743-aa3c7780-0a12-11ea-9e4e-ddac6a5732c4.png)

The filesizes for images are low and the images do not open. Looks like it was a git lfs issue. I had downloaded the .zip of the git repo. I tried to git clone with git lfs enabled, and it seems to download the png files properly

**Comment by martins-mozeiko** [comment]
Yeah, unfortunately GitHub does not package lfs files inside zip downloads.

**Comment by dganzella** [comment]
IF anyone in the future has this same problem, which solved for me, on MacOS was:

brew update
$ brew install git-lfs

then, in the repo folder
git lfs install
