### ISSUE TITLE
Unity Build Error : Trying to reload asset from disk that is not stored on disk

### ISSUE THREAD

**Issue by tkbala** [lgsvl/simulator#503]
I get the following error on running build from "Simulator"->"Build"->"Build" when following the build instructions [here](https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md). Any ideas on what I might be doing wrong?

![image](https://user-images.githubusercontent.com/4410442/69103630-c04e3600-0a1a-11ea-95b9-f40b70b9729f.png)

**Comment by martins-mozeiko** [comment]
These are not real errors, they are harmless. They come from some internal components of Unity. As you can see on first line in output - Build succeeded. Simply ignore everything that comes afterwards.
