### ISSUE TITLE
3d bounding boxes not working

### ISSUE THREAD

**Issue by Aquarian-source** [lgsvl/simulator#505]
my scenario: made my own map, connecting AD functions through ROSbridge following autoware specific message types. using lgsvl msgs as shown in pic to subscribe the to 3d bounding boxes messages. but in lgsimulator i am unable to see the bounding boxes and subsequently the list is empty in ROStopics as well. tried to change EGO JSON configuration of 3d ground truth but could not solve the issue. 
![3d bounding boxes](https://user-images.githubusercontent.com/45082425/69135206-078b0400-0ab9-11ea-847c-1223bc0f9cd5.PNG)

one interesting thing: NPC vehicle is controlled through way points, when we remove those, that is NPC vehicles dont move, than it detects objects 

Please let me know how can i solve the problem

**Comment by EricBoiseLGSVL** [comment]
@Aquarian-source 

I think we fixed this issue in the latest release but we are still looking into this.  If you have any more information, it would help to reproduce this.
