### ISSUE TITLE
Setting up lanes error...

### ISSUE THREAD

**Issue by ninjacoder0** [lgsvl/simulator#506]
I am attempting to create a basic lane as the images shows but I keep getting am error message. could you please help me understand why? 

Thank you

![image](https://user-images.githubusercontent.com/44463247/69185172-223b9800-0b0e-11ea-95c2-533e91321656.png)

**Comment by EricBoiseLGSVL** [comment]
@ninjacoder0 

Be sure to have your TrafficLanes and Intersection holder objects as children of map holder.  MapHolder.cs also needs the references to these holder objects.

![Annotation](https://user-images.githubusercontent.com/45106230/69190870-2cda3b00-0ad6-11ea-915f-86e62c474da5.jpg)

**Comment by ninjacoder0** [comment]
Perfect, thank you!
