### ISSUE TITLE
Couldn't find the button to import the apollo5 map

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#509]
Couldn't find the button to import the apollo5 map，plz see the picture below.
![Screenshot from 2019-11-20 10-43-06](https://user-images.githubusercontent.com/39210837/69204710-b1829300-0b82-11ea-97c9-4428cf3d8167.png)

**Comment by zelenkovsky** [comment]
Does the button "Import" on this screenshot opens "Open File" dialog?

**Comment by yumianhuli2** [comment]
No, no dialog for "Open File"

**Comment by martins-mozeiko** [comment]
We had a bug in code that prevented you to choose which file to import. This is fixed in latest release. Please pull latest code, then the import should work.

**Comment by yumianhuli2** [comment]
> We had a bug in code that prevented you to choose which file to import. This is fixed in latest release. Please pull latest code, then the import should work.

Hello!
I have pulled newest version ,but I have not seen 
"Choose file where is your map (typically in base_map.bin file)"

**Comment by martins-mozeiko** [comment]
Make sure you have pulled latest source code.
The file input choosing button/field is there:

![image](https://user-images.githubusercontent.com/39178216/69451059-5af88e80-0d13-11ea-8c32-52914da7acb3.png)
