### ISSUE TITLE
Communication Tutorial

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#510]
For example, if I want to communicate with cyber messages, can I have a simple example or an internal program to illustrate how to deliver messages and publish/subscribe topics from scratch?

**Comment by daohu527** [comment]
You can refer to any sensor like "CanBusSensor.cs". Below is the approximate process:
```
1. Add a sensor in "Assets/Scripts/Sensors"
2. Add Dataformat in "Assets/Scripts/Bridge/Data"
3. Add code in "Assets/Scripts/Bridge/Cyber"
4. Add sensor in webUI with json
```

**Comment by martins-mozeiko** [comment]
See following issue with more information how to publish new information from sensor: https://github.com/lgsvl/simulator/issues/339

And here is Python example code that shows how to subscribe to data in CyberRT: https://github.com/lgsvl/simulator/issues/493#issuecomment-554142705
