### ISSUE TITLE
[Question] can LGSIM public ground truth of lane/road info

### ISSUE THREAD

**Issue by duong-pa** [lgsvl/simulator#516]
I want to get the lane/road info(boundary, center line...) from the simulation, not from the map data (similar to the ground truth message). Is there already an implementation for it? or can you show me how to do it?

Thank you.

**Comment by martins-mozeiko** [comment]
Currently simulator does not provide information about lane positions. We are planning to add it at some point.

**Comment by EricBoiseLGSVL** [comment]
@duong-pa We have not started work but in the meantime you could create a custom sensor that reads data from MapManager.
