### ISSUE TITLE
Question: Does the "connect" curl button work? 

### ISSUE THREAD

**Issue by ninjacoder0** [lgsvl/simulator#518]
I would like to have a slight curve in the road and when I press the straight "connect" button it works fine. Although when I press the curve button it does not work.

Is there special requirements for it to work? 

Thank you.

**Comment by shalinmehtalgsvl** [comment]
The curve button creates a [Bezier curve](https://en.wikipedia.org/wiki/B%C3%A9zier_curve) and can only be used with 3 `TEMP_WAYPOINT`: the start point, the control point, and the end point. 

For the straight button, if there are 2 `TEMP_WAYPOINT`, then the button will create a straight lane with a number of waypoints specified in the `Waypoint Count` field. If there are 3+ `TEMP_WAYPOINT`, the button will connect them in the order that the `TEMP_WAYPOINT` were created.

See the Make Lanes section of the [Map Annotation](https://www.lgsvlsimulator.com/docs/map-annotation/#annotate-lanes) doc for more information.

When annotating, I use the curve button when annotating intersection turns and the straight button for everything else.
