### ISSUE TITLE
Lidar doesn't pick intensity from some road markings

### ISSUE THREAD

**Issue by andytolst** [lgsvl/simulator#52]
road markings (arrows) are displayed as white rectangles on Lidar
![lidar_intensity_road_marks](https://user-images.githubusercontent.com/1422400/50357079-883c2b80-0509-11e9-93d0-eae8953a1adc.png)

**Comment by moenasrallah** [comment]
Any updates on this issue?

**Comment by martins-mozeiko** [comment]
@moenasrallah Sorry, we've bee very busy with [CES2019](https://www.lgsvlsimulator.com/2019/01/08/ces-kickoff/). We will be working on this issue very soon.

**Comment by martins-mozeiko** [comment]
This is now fixed. Here's how it looks like now:
![2019-01-14-180146_1920x1200_scrot](https://user-images.githubusercontent.com/39178216/51421548-3d3b2580-1b54-11e9-9997-46e6a7951350.png)
