### ISSUE TITLE
lgsvlsimulator-windows64-2019.10 memory leak

### ISSUE THREAD

**Issue by chenzhiwo** [lgsvl/simulator#520]
![image](https://user-images.githubusercontent.com/4759360/69531954-c8c0e680-0faf-11ea-9c02-f0c7eea234bc.png)
- Windows 10.0.18362.
- Ryzen 1700X
- 16GB RAM
- GTX760 4GB VRAM
- Map:Shalun
- Vehicle:Jaguar2015XE
- API only simulation
Restart simulation in WebUI not release memory at all.

**Comment by martins-mozeiko** [comment]
Does the memory increase more if you start and stop again, start and stop again, ... (repeat multiple times)?
I'm guessing that Unity simply keeps memory allocated because it can be reused for later operations.

**Comment by chenzhiwo** [comment]
Memory increase over time till it run out of 16GB of memory.
In the log file I found ton's of following  message:
```
ShaderProgram is unsupported, but because jobified rendering is enabled the ShaderProgram can not be removed.
(Filename: C:\buildslave\unity\build\Runtime/Shaders/ShaderImpl/ShaderState.cpp Line: 443)
```
Maybe unity add a ShaderProgram every loop?
By the way, it work perfectly in my 9th gen Intel platoform.

**Comment by martins-mozeiko** [comment]
I'm not sure what could be issue.

I have not seen before error about "ShaderProgram is unsupported" and jobified rendering. You could try open project in Unity Editor and disable "Graphics Jobs" under project settings. But that will probably affect performance negatively.

Have you tried updating nvidia driver to latest? Maybe that would help.

DXR passes in HDRP/Lit shader are not an issue. These are used only for DXR RayTracing features which are not enabled in our project. So it is ok they they are not supported (DXR anyways works only with d3d12, not d3d11 which we use).

**Comment by chenzhiwo** [comment]
Thanks for your help. The latest windows nvidia driver dosen't help, but it works well on linux. Upgrade GPU solve the problem.
