### ISSUE TITLE
Building WebUI

### ISSUE THREAD

**Issue by RamoramaInteractive** [lgsvl/simulator#522]
My colleague has a similar problem with the Building WebUI like in issue https://github.com/lgsvl/simulator/issues/404 , but he is using Windows 7 and not Linux. The issue was not so helpful.

If he starts to build the WebUI, he receives an output like this:

![npm-file not found](https://user-images.githubusercontent.com/6389713/69658883-5ddde100-107d-11ea-8edb-157f549a5cad.jpeg)

The path of Node.js is already set.
What could be the source of the npm problem?

**Comment by martins-mozeiko** [comment]
Can you try running `npm run pack-p` in commandline from simulator folder? Does it work then?

**Comment by RamoramaInteractive** [comment]
> 
> 
> Can you try running `npm run pack-p` in commandline from simulator folder? Does it work then?

Sorry, this neither works. :(
Here is the output:
![index](https://user-images.githubusercontent.com/6389713/69665971-bfa54780-108b-11ea-8f6c-135ba90c3ca1.jpg)

**Comment by martins-mozeiko** [comment]
These seem to be only warnings. If this is all you see, then everything is OK.
You can check output files (main.css and main.js) generated in `dist` folder - if they are there, then the build succeeded.

**Comment by Gxer** [comment]
i have the same issue. 

> > Can you try running `npm run pack-p` in commandline from simulator folder? Does it work then?
> 
> Sorry, this neither works. :(
> Here is the output:
> ![index](https://user-images.githubusercontent.com/6389713/69665971-bfa54780-108b-11ea-8f6c-135ba90c3ca1.jpg)

Hi
i have the same issue exactly the same as yours.
Do you solve the problem?

**Comment by EricBoiseLGSVL** [comment]
@Gxer In the log you posted it says Compiled with warnings.  This should be fine.  Does the Simulator run after the install? Do you have the dist folder described above?

**Comment by twuser666** [comment]
> i have the same issue.
> 
> > > Can you try running `npm run pack-p` in commandline from simulator folder? Does it work then?
> > 
> > 
> > Sorry, this neither works. :(
> > Here is the output:
> > ![index](https://user-images.githubusercontent.com/6389713/69665971-bfa54780-108b-11ea-8f6c-135ba90c3ca1.jpg)
> 
> Hi
> i have the same issue exactly the same as yours.
> Do you solve the problem?

Hi, I have the same problem.
Do you solve the problem?

**Comment by EricBoiseLGSVL** [comment]
It says compiled with warnings.  This is fine

**Comment by twuser666** [comment]
> It says compiled with warnings. This is fine

Thanks a lot!
