### ISSUE TITLE
About OPENDRIVE and APOLLO5MAP

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#529]
Hello，Does the current map have slope information? Is it now supported to make rolling roads based on maps?Thank you！

**Comment by martins-mozeiko** [comment]
OpenDrive supports height information in hdmap. In current simulator version Apollo does not export height data.

**Comment by ntutangyun** [comment]
@martins-mozeiko since the format actually supports height information, does it mean that we could build the map ourselves and manually add in the height information for Apollo to consume ? thanks

**Comment by luqiang21** [comment]
@ntutangyun Yes, you can add height information yourself to the map by modifying map exporting tools in our simulator. It depends on whether Apollo will parse height information from the map or not.

**Comment by ntutangyun** [comment]
@luqiang21 alright. thank your for your prompt reply.
