### ISSUE TITLE
IMU and GPS Message delay 

### ISSUE THREAD

**Issue by clouddd9** [lgsvl/simulator#530]
When I make the co-simulation, the apollo Dreamview shows messages as follows

Raw IMU Message Delay. IMU message is 178 cycle 1.78812 sec behind current time.09:52:11
Raw GPS Message Delay. GPS message is 178 cycle 1.78797 sec behind current time.09:52:11
Raw IMU Message Delay. IMU message is 178 cycle 1.78818 sec behind current time.09:52:11
Raw GPS Message Delay. GPS message is 179 cycle 1.79801 sec behind current time.09:52:11
Raw IMU Message Delay. IMU message is 178 cycle 1.78838 sec behind current time.09:52:11
![2019-12-02 09-51-30屏幕截图](https://user-images.githubusercontent.com/34005180/69925326-808f5000-14ea-11ea-9215-14534c8d3b71.png)

And I locate the problem in the rtk_localization.cc from apollo-5.0/modules/localization/rtk/
![2019-12-02 10-05-26屏幕截图](https://user-images.githubusercontent.com/34005180/69925471-4f634f80-14eb-11ea-946b-63a62b635fe1.png)

What's wrong with the GPS and IMU timestamps? How to solve it? Could you give me some advice? :)

**Comment by yumianhuli2** [comment]
> When I make the co-simulation, the apollo Dreamview shows messages as follows
> 
> Raw IMU Message Delay. IMU message is 178 cycle 1.78812 sec behind current time.09:52:11
> Raw GPS Message Delay. GPS message is 178 cycle 1.78797 sec behind current time.09:52:11
> Raw IMU Message Delay. IMU message is 178 cycle 1.78818 sec behind current time.09:52:11
> Raw GPS Message Delay. GPS message is 179 cycle 1.79801 sec behind current time.09:52:11
> Raw IMU Message Delay. IMU message is 178 cycle 1.78838 sec behind current time.09:52:11
> ![2019-12-02 09-51-30屏幕截图](https://user-images.githubusercontent.com/34005180/69925326-808f5000-14ea-11ea-9215-14534c8d3b71.png)
> 
> And I locate the problem in the rtk_localization.cc from apollo-5.0/modules/localization/rtk/
> ![2019-12-02 10-05-26屏幕截图](https://user-images.githubusercontent.com/34005180/69925471-4f634f80-14eb-11ea-946b-63a62b635fe1.png)
> 
> What's wrong with the GPS and IMU timestamps? How to solve it? Could you give me some advice? :)

Perhaps because the imu is updated too infrequently

**Comment by martins-mozeiko** [comment]
Is something not working? We see these kind of messages from time to time, but everything else works.

**Comment by Martin20** [comment]
Could you solve this error?
In front of GPS in the module controller, it is written FATAL ERROR.

How can I fix those issues?

**Comment by askariz** [comment]
I have also come across this problem . 
enviroment :
simulator pc :  run simulator 192.168.1.114
apollo pc : run apollo code stack .192.168.1.117
![image](https://user-images.githubusercontent.com/39890252/79412256-9c961880-7fd7-11ea-9246-f983a1ff16f9.png)

**Comment by 373432156** [comment]
same issue！！

**Comment by rongguodong** [comment]
This is because our timestamp is simulation time, not real time.
We have added sim_time support to latest Apollo. If you add a ClockSensor to ego, and set CyberRT's `clock_mode` to `MODE_MOCK`, you should not see these errors. For more details, please refer to [our document about ClockSensor](https://www.lgsvlsimulator.com/docs/sensor-json-options/#clock).
