### ISSUE TITLE
import hd map

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#532]
I downloaded the CrossingComplex8Course map from the opendrive website and clicked the import hd map button, but nothing came back. Is this function valid only if you enter the simulator state?

**Comment by martins-mozeiko** [comment]
I've tried importing this map and it worked fine.
Make sure you turn on annotations in "Simulator -> Annotate HD Map" menu, click "View All" button to see all the annotations. Note that they might be behind, above or below you. You'll need to rotate camera, or focus on annotations in scene view.

**Comment by yumianhuli2** [comment]
> I've tried importing this map and it worked fine.
> Make sure you turn on annotations in "Simulator -> Annotate HD Map" menu, click "View All" button to see all the annotations. Note that they might be behind, above or below you. You'll need to rotate camera, or focus on annotations in scene view.

Yes,it works.But the scene view is black in unity2019.1.10f1, other version supports?
Have you ever been in this situation？

**Comment by martins-mozeiko** [comment]
Can you show screenshot - what exactly is black?

If you are working on creating map, then 3d models will be dark because there are not lights in scene. You need to turn off "Scene lighting" - lightbulb icon in Scene view. Or temporarily add Sun prefab to scene hierarchy.

**Comment by yumianhuli2** [comment]
> lightbulb icon

The windows version is fine,I can see the map and light is on.
But In linux version I mean black is like below:
![Screenshot from 2019-12-04 10-11-03](https://user-images.githubusercontent.com/39210837/70106369-6f774800-167e-11ea-9758-5dc879575a9c.png)

**Comment by martins-mozeiko** [comment]
This map does not seem to have any 3d objects in scene hierarchy. Only annotations. To see annotations you need to click "View All" button in "Simulator -> Annotate HD Map" tool window.

**Comment by yumianhuli2** [comment]
> This map does not seem to have any 3d objects in scene hierarchy. Only annotations. To see annotations you need to click "View All" button in "Simulator -> Annotate HD Map" tool window.

I tried,And I created cube/sphere int the Hierarchy,still can not see anything in this project!But another project is fine.
![Screenshot from 2019-12-04 14-26-30](https://user-images.githubusercontent.com/39210837/70118244-7912a700-16a2-11ea-95e6-faf23d714be6.png)

**Comment by martins-mozeiko** [comment]
The annotations are not always centered around origin of game object. You might need to look behind you or above you. Select one specific lane or lane segment and double click it, to focus on that. Make sure console does not have any errors after import.

From screenshot it seems that you have two map annotation holders - `MapHolder`, and `MapCrossingComplex8Course`. That may lead to some issues. Delete one that is not used.

Also in this screenshot I do not see that you have added any sphere or cube in hierarchy. Simply clicking right click and choosing "3D Object -> Plane" should be enough for ground. As long as you position it correctly car will be able to drive on it.

**Comment by yumianhuli2** [comment]
> The annotations are not always centered around origin of game object. You might need to look behind you or above you. Select one specific lane or lane segment and double click it, to focus on that. Make sure console does not have any errors after import.
> 
> From screenshot it seems that you have two map annotation holders - `MapHolder`, and `MapCrossingComplex8Course`. That may lead to some issues. Delete one that is not used.
> 
> Also in this screenshot I do not see that you have added any sphere or cube in hierarchy. Simply clicking right click and choosing "3D Object -> Plane" should be enough for ground. As long as you position it correctly car will be able to drive on it.

![Screenshot from 2019-12-05 09-39-19](https://user-images.githubusercontent.com/39210837/70196280-30f79100-1743-11ea-9073-e4570a3f49fc.png)
Hello! I did everything you said, but I still can't see anything. But I do the same thing on Windows that is fine.

**Comment by martins-mozeiko** [comment]
Can you check if you have map annotation Gizmos enabled? The Gizmos button should be also pressed.
Map annotations are drawn in Editor as Gizmos which can be hidden.

![image](https://user-images.githubusercontent.com/39178216/70198742-893b7e00-16c4-11ea-8b75-8a5c0c13b659.png)

**Comment by yumianhuli2** [comment]
> Can you check if you have map annotation Gizmos enabled? The Gizmos button should be also pressed.
> Map annotations are drawn in Editor as Gizmos which can be hidden.
> 
> ![image](https://user-images.githubusercontent.com/39178216/70198742-893b7e00-16c4-11ea-8b75-8a5c0c13b659.png)

Thank you for your reply！
![Screenshot from 2019-12-05 15-22-07](https://user-images.githubusercontent.com/39210837/70212875-15a47a00-1773-11ea-8bf3-92744296c90f.png)
I have pressed the map annotation！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 You are in ortho view mode, I suggest perspective.  Select an annotation object in the Hierarchy panel and press 'F' to focus on that object in Scene view.  Last thing, look at annotation objects transforms in Inspector panel.  If there are floating point errors messages and the values are extremely high, then you have issues importing the HDMap and MapOrigin settings.
