### ISSUE TITLE
Apollo MapImport Simple Fix

### ISSUE THREAD

**Issue by moenasrallah** [lgsvl/simulator#533]
Changed **line 25** in **MapImport.cs** to "Apollo HD Map" instead of "Apollo **5** HD Map".

**Line 69** reads as:
"if (importFormats[Selected] == "Apollo HD Map")", 
so the "**5**" in line 25 is not necessary and breaks functionality

**Comment by martins-mozeiko** [comment]
You're right.
This was fixed in latest code, but I forgot to push to github. Check out latest code now - it is fixed there.
