### ISSUE TITLE
Simulator subscribe topic

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#539]
I want our car to subscribe our controller ( different ros workspace ) . How can I manage to subscribe its topic from simulator. I know how to publish things in simulator via rosbridge  but not subscribing . 

Is there any way to do that ?

**Comment by martins-mozeiko** [comment]
If you are talking about vehicle control subscribing to messages from AD stack then [VehicleControl](https://www.lgsvlsimulator.com/docs/sensor-json-options/#vehicle-control) sensor is doing that. You just put topic name there and it will subscribe. It will expect Autoware control message in case of ROS or Apollo control message in case of CyberRT bridge.

If you need to send custom information that will require creating custom sensor in C# code.
