### ISSUE TITLE
Building asset bundles not working for vehicles [Ubuntu build]

### ISSUE THREAD

**Issue by MithunKinarullathil** [lgsvl/simulator#542]
**Description:**
-  Jaguar2015XE not building as AssetBundle in Ubuntu
-  Unity is installed as per instructions in [here](https://www.lgsvlsimulator.com/docs/build-instructions/)

**How to reproduce:**
- Fresh clone the sim
- Download CubeTown and Jaguar2015XE to the Environments and Vehicles directories
- Build using the Editor tool without the Build Simulator checked
- Confirm that the AssetBundles directory does not contain Jaguar2015XE

**Refs:**

![github](https://user-images.githubusercontent.com/51120171/70224244-dc551580-1744-11ea-93d1-7b1e24c62048.png)

Errors are as shown in the figure.

**Comment by MithunKinarullathil** [comment]
It's building after a few trials.

**Comment by martins-mozeiko** [comment]
The actual error is in second message from bottom - it says that you did not have Windows support installed for your Unity. When we build asset bundles for maps and vehicles we build it for two platforms - Linux and Windows, so result can be used on any supported OS.

**Comment by MithunKinarullathil** [comment]
@martins-mozeiko  It would be a good idea to add this here, https://www.lgsvlsimulator.com/docs/build-instructions/. Is the documentation open for public contribution?

**Comment by MithunKinarullathil** [comment]
@martins-mozeiko Thanks.
