### ISSUE TITLE
EKF localization

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#543]
Hi, I wonder is there any localization module based on kalman filtering. I saw ndt matching and so on for localization. But I am looking for imu and gps fusion for localization specifically. I couldn't see any module that uses kalman filter for localization. By the way I don't want it for object tracking and so on. I just want it for localization.

**Comment by martins-mozeiko** [comment]
Are you talking about Apollo ndt localization? We have not tried that as it was added much later than when we started using Apollo.
See #476 issue about this.
