### ISSUE TITLE
Where can I download apollo3.5 simulator

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#545]
Hello!
Where can I download apollo3.5 simulator source code of unity？

**Comment by martins-mozeiko** [comment]
There is no special version for Apollo 3.5. All available simulator versions support Apollo 3.0, 3.5 and 5.0 version. Just download latest code, it will work with Apollo 3.5.

**Comment by yumianhuli2** [comment]
> There is no special version for Apollo 3.5. All available simulator versions support Apollo 3.0, 3.5 and 5.0 version. Just download latest code, it will work with Apollo 3.5.
Thank you！I mean where I can download the old simulator version .

**Comment by martins-mozeiko** [comment]
Old simulator code is available in separate repository: https://github.com/lgsvl/simulator-2019.05-obsolete

**Comment by yumianhuli2** [comment]
> Old simulator code is available in separate repository: https://github.com/lgsvl/simulator-2019.05-obsolete

very nice!
