### ISSUE TITLE
opendrive code generation

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#546]
Hello!I saw this from the source code.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
So
what about MonoXSD?where can I download this tool?
What exactly are the inputs and outputs of this tool?
Thank you！

**Comment by martins-mozeiko** [comment]
This file is generated with xsd tool. xsd is available by default either as part of .NET SDK installation on Windows, or as part of [mono](https://www.mono-project.com/). Read documentation on MSDN website: [XML Schema Definition Tool](https://docs.microsoft.com/en-us/dotnet/standard/serialization/xml-schema-definition-tool-xsd-exe)

**Comment by yumianhuli2** [comment]
![image](https://user-images.githubusercontent.com/39210837/70391597-d5aef280-1a11-11ea-954c-0dfc5dd9ba76.png)
So 
step 1 I should use XML to XSD
step 2 I should use XSD to classes?
Can you show me the command for converting the opendrive XML file to C# class. Thank U！

**Comment by martins-mozeiko** [comment]
We use xsd to generate xml parser from xsd schema. OpenDrive provides xsd schema files here: http://www.opendrive.org/download.html

To generate xml parser code, run `xsd file.xsd /classes`

**Comment by yumianhuli2** [comment]
> We use xsd to generate xml parser from xsd schema. OpenDrive provides xsd schema files here: http://www.opendrive.org/download.html
> 
> To generate xml parser code, run `xsd file.xsd /classes`

Hi！
1 You mean if I use  xsd OpenDRIVE_1.4H.xsd  /opendrive(class name),then I can get a opendrive class(a mapping file of opendrive xml)?
2 where can I download the Xsd.exe?May you provide me with the download address? Or installation steps？
Thank U very much！

**Comment by martins-mozeiko** [comment]
1. Yes
2. If you are on Windows you need to install .NET SDK. On Linux you need to install mono. EIther of these options will provide `xsd` executable.
