### ISSUE TITLE
LGSVL + Autoware GPU recommendation

### ISSUE THREAD

**Issue by hcv1027** [lgsvl/simulator#548]
I currently is choosing my new graphics cards and found that from this [recommended system specs link](https://www.lgsvlsimulator.com/docs/faq/), Apollo does not support RTX series gpu currently. But I can't find relative discuss about Autoware. So I want to ask if LGSVL + Autoware can work find with RTX series gpu (ex: RTX 2080 or RTX 2070)?

**Comment by martins-mozeiko** [comment]
Simulator will work fine with RTX GPU. In fact it will work fine with any GPU, including from Intel. It just question of performance how fast it will run.

For Autoware GPU requirements you should probably ask that on Autoware issues: https://github.com/autowarefoundation/autoware/issues
They will know better what are hardware requirements as we are not really developing Autoware.
