### ISSUE TITLE
Tool does not run on ubuntu 16.04

### ISSUE THREAD

**Issue by arufoOptimus** [lgsvl/simulator#557]
When I run the executable in Ubuntu 16.04 the tool closes and nothing happens. This occurs if i double click the icon or if I run the code from the command line. Help would be most appreciated.

**Comment by martins-mozeiko** [comment]
Have you installed libvulkan1?
https://www.lgsvlsimulator.com/docs/faq/#why-does-the-simulator-not-open-on-linux

**Comment by arufoOptimus** [comment]
I will try that shortly and see what happens

> Have you installed libvulkan1?
> https://www.lgsvlsimulator.com/docs/faq/#why-does-the-simulator-not-open-on-linux

**Comment by Fred159** [comment]
> Have you installed libvulkan1?
> https://www.lgsvlsimulator.com/docs/faq/#why-does-the-simulator-not-open-on-linux

It works for my situation. 
Thanks you ~
