### ISSUE TITLE
cannot duplicate a sensor in lgsvl simulator

### ISSUE THREAD

**Issue by weiyinxie** [lgsvl/simulator#558]
i need a second sensor in lgsvl, so i choose  the option of duplicating a sensor from a existing one. so i get a new sensor that duplicated from Lidar name Lidar(1). But it seems that this new sensor dosent generate any data......
![Screenshot from 2019-12-12 15-39-05](https://user-images.githubusercontent.com/44968424/70692265-ebfccd00-1cf5-11ea-9915-b9df622826f0.png)

**Comment by martins-mozeiko** [comment]
I'm not sure how are you duplicating this sensor, but all sensor configuration is done through JSON setting on vehicle in the WebUI: https://www.lgsvlsimulator.com/docs/sensor-json-options/
If you need extra lidar, you just add one more "type: "Lidar" object to json array in WebUI.
