### ISSUE TITLE
failed to connect to Windows Simulation machine.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#56]
I tested your simulator in Windows and run ROS in Linux.
I checked communication confirmation was succeed, and try to run rosbridge_server.
But it was failed and I faced error logs below.

![image](https://user-images.githubusercontent.com/10348912/50505993-e5ac1b80-0ab9-11e9-8253-4596b6e94aba.png)

**Comment by hadiTab** [comment]
@hakuturu583 can you provide more details on what steps you are going through? Thanks.

**Comment by hakuturu583** [comment]
@zelenkovsky @hadiTab I setted IP v4 adress like below, but the rosbridge was failed to connect.
![image](https://user-images.githubusercontent.com/10348912/50744234-96f24480-1264-11e9-915b-3a9957919d47.png)

**Comment by hakuturu583** [comment]
I succeed to connect now.
