### ISSUE TITLE
About KeyboardControlSensor.cs when you have both steering and accel input from keyboard

### ISSUE THREAD

**Issue by mehmetdogru** [lgsvl/simulator#560]
Hi,

I just realize if you are controlling the vehicle with keyboard, in "KeyboardControlSensor" class, "keyboardInput" is reading the value when you press LeftArrow, RightArrow, UpArrow or DownArrow.
If you are pressing one at a time, all inputs listed above gives you 1 or -1.

Lets say, you are pressing the  LeftArrow and UpArrow at the same time to give acceleration and steer input to the vehicle. In that case the input for acc and steer will be [-0.707 and 0.707] , in other words [-1/sqrt(2) and 1/sqrt(2)]. I guess it is because vector2 should be a unit vector for the input, idk.

What i wanna say is idk if it is an error or you designed it that way but from keyboard you cant accelerate or brake the vehicle with full throttle. I just wanted to report just in case it is a bug.

Thank you.

**Comment by EricBoiseLGSVL** [comment]
@mehmetdogru 

Yes, KeyboardControlSensor is very simple and not designed to handle multiple key presses.  We plan on improving VehicleDynamics soon and will probably refactor this sensor as well.  Thanks for the help.
