### ISSUE TITLE
Jaguar2015XE Vehicle Dimensions

### ISSUE THREAD

**Issue by srirambadri** [lgsvl/simulator#562]
Hi,

I am trying to get the raw sensor information into ROS and I've been successful in doing that.  

My question is, how do I find the dimensions of the vehicle? I tried to build the Jaguar2015XE Vehicle in Unity but I'm not able to find the dimensions. 

I basically want to fit many sensors eg. 4 lidar sensors instead of one placed at all four corners of the vehicle. I can add the sensors and with the transform option place them relative to each other using the configure option in the Web UI but where is the "base_frame" i.e 0,0,0 of the vehicle. Is the center of mass the origin?

![image](https://user-images.githubusercontent.com/8626656/70709218-b0093e00-1cdc-11ea-88b3-ef5677611737.png)

**Comment by martins-mozeiko** [comment]
To get dimensions for Jaguar do the following:

1) Select `Body` game object (under Jaguar2015XEModel) in Hierarchy panel

2) In Inspector click `Add Component` button and choose `Box Collider`

3) This will add box collider that will encompass whole mesh of vehicle and also it will show sizes of box collider which you can use - (2.07, 1.27, 4.67).

4) Don't forget to remove this collider when you are done.

**Comment by srirambadri** [comment]
@martins-mozeiko  thanks. I'm not able to figure out where the origin of the car. 
![image](https://user-images.githubusercontent.com/8626656/70750215-4154d080-1d2e-11ea-9c09-901392be7aa4.png)

For example the camera sensor is placed at "x": 0, "y": 1.7, "z": -0.2, relative to what position?

**Comment by martins-mozeiko** [comment]
It is in middle of car, at the bottom where ground is.

You can open car prefab and see its origin in Editor:
![image](https://user-images.githubusercontent.com/39178216/70752395-5e19e580-1ce7-11ea-8da3-6a4227b990db.png)

**Comment by srirambadri** [comment]
perfect thanks
