### ISSUE TITLE
win10 build from source  HDRenderPipeline error 

### ISSUE THREAD

**Issue by muzi2045** [lgsvl/simulator#563]
I an trying to build the lastest simulator code in unity 2019.1.10f1, this HDRenderPipeline error occur to me, hopefully for any advice.

![{25020C64-FC7A-418A-B4EA-781531843C93} png](https://user-images.githubusercontent.com/12984898/70787460-aa3d5680-1dc9-11ea-93de-ee4f24134a2b.jpg)

**Comment by martins-mozeiko** [comment]
These are not real errors, you can ignore them. Simply press "Clear" button and they will go away.

Sometimes Unity likes to complain about some kind of errors or warnings from their internal code. But everything still works just fine.

**Comment by muzi2045** [comment]
after git lfs checkout, the whole repo are completed download, but still error occured, and it looks like can't running before resolve those compile errors(clear button help nothing )
![{707D77EE-4E62-430D-9B28-4A023FBC1B1A} png](https://user-images.githubusercontent.com/12984898/70842487-45344000-1e5f-11ea-8a3f-d99422ce9afa.jpg)

**Comment by muzi2045** [comment]
OK , By the way , I check the download files one by one , and find git lfs clone the repo can't clone complete files, After merge the git lfs file into git clone repo file,  it has no error occur to me.
