### ISSUE TITLE
can't run newest version on ubuntu 16.04

### ISSUE THREAD

**Issue by Allenhe123** [lgsvl/simulator#564]
The newest version:lgsvlsimulator-linux64-2019.11.zip was launched by Web UI, but when i opened the UI on web, i can't run it.
1. The state of the resources such as  Maps and Vehicles are always downloading ... how to fix it?
2. And when i removed some maps or vehicles on the web UI, i can't find them back. I pressed the Add New button but how to know the name and URLs of the resources i want to add. So is there a easy way to do this?
3.  I can download the assets(Maps, Vehicles ..) manually, the problem is where to put the downloaded resources? 

Thanks.

**Comment by martins-mozeiko** [comment]
1. If it is downloading then everything work as intended. You need to wait until download finishes to be able to use maps and vehicles.

2. You get URLs from our content website: https://content.lgsvlsimulator.com/

3. You can put path to file in place of address when adding map or vehicle. Alternatively you don't need to download anything manually, simply copy & paste address of asset bundle from content website into address field when adding new map or vehicle. Simulator will download it automatically.

Alternatively you can remove Simulator data folder created in your home folder and then Simulator will recreate default configuration that includes default maps/vehciles. Simulator data folder is inside `AppData\LocalLow\LG Silicon Valley Lab` on Windows or in `~/.config/unity3d/LG Silicon Valley Lab` on Linux.
