### ISSUE TITLE
What is the value of one degree for steering wheel? 

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#566]
Hello,
I want to control the steering wheel using angle. Simulator uses values between - 1 and 1 to control the steering wheel. 
How can I control the steering wheel using angle. What is the max and min value of steering wheel angle for a car in simulator?
OR
steerInput that is the lateral control for a car in simulator controls the wheel, not the steering wheel?
Would you explain all the controlling terms (steerangle, steerrate ...) to me please ?
Thanks in advance.

**Comment by martins-mozeiko** [comment]
The input value -1..+1 interval is mapped to -maxSteeringAngle..+maxSteeringAngle, where maxSteeringAngle is property of vehicle. By default it is 39.4 degrees as seen here: [VehicleDynamics.cs#L53](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Components/VehicleDynamics.cs#L53)

This angle is desired rotation angle around vertical axes for wheels. Wheels are controlled by builtin Unity [WheelCollider](https://docs.unity3d.com/2017.3/Documentation/ScriptReference/WheelCollider.html) component. Wheels rotate smoothly towards set angle.
