### ISSUE TITLE
NPCs only spawn in build but not in editor

### ISSUE THREAD

**Issue by HDSFaust** [lgsvl/simulator#569]
NPCs dont spawn in editor play mode. Im using the example assetbundles and unity 2019.01.10f1. also pressing 'n' does nothing inside the editor. when i build the project everything works fine.

maybe it has something to do with the loading scene, which instantly shows "api ready" inside the editor but correctly works in the build, showing "open in browser"

**Comment by martins-mozeiko** [comment]
If you see "API ready" in loading screen that means you either have started API simulation from web interface, or you have checked "Enable API" checkbox in "Simulator -> Development Settings" menu inside Editor. Not sure how you expect NPCs to spawn here, as it is loader screen, not actual environment. You need to have full environment loaded for NPCs to spawn.
