### ISSUE TITLE
Any plan to run in linux?

### ISSUE THREAD

**Issue by daohu527** [lgsvl/simulator#57]
I see the recommended system is just WIN10,Any plan to run it in linux?

**Comment by hadiTab** [comment]
@daohu527 the simulator runs and is fully supported in linux as well as windows. The only reason Windows 10 is recommended is that it will have a slightly better frame rate.

**Comment by daohu527** [comment]
> @daohu527 the simulator runs and is fully supported in linux as well as windows. The only reason Windows 10 is recommended is that it will have a slightly better frame rate.

great!

**Comment by hadiTab** [comment]
Closing this as it seems like the issue is solved.
