### ISSUE TITLE
Radar not detecting vehicles

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#577]
Hello,

Radar is detecting objects in lgsvl map (shalun,singlelane, exc.. ) . However, in our custom map, when I add some vehicles on map, it isn't detecting them. I assume it might be the collider issue but I have already added collider mesh. The car can't pass through the vehicles. 

![radarDetected](https://user-images.githubusercontent.com/33527769/71338294-587e9400-2560-11ea-9082-e085f123af6a.png)
![radarnotDetected](https://user-images.githubusercontent.com/33527769/71338299-5c121b00-2560-11ea-91ff-39452feab88b.png)

**Comment by martins-mozeiko** [comment]
How are you adding vehicles to map? If this is your own custom code or you are simply drag&drop'ing them on the scene, then this is expected. When NPC's are added to scene, there is an extra setup required for ground truth sensors to work. Relevant code is here: https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Managers/NPCManager.cs#L117

**Comment by arslansarp** [comment]
Thanks for your answer martin. As you said, I just drag&drop them. Is there any shortcut for this setup?
I mean can I handle it in Unity Editor, if so , I will be pleased if you help me with a clear guidance.

**Comment by arslansarp** [comment]
Hey Martin , I just solved the issue. Thank you again..

![radarmartinDetected](https://user-images.githubusercontent.com/33527769/71414630-dded6b80-2668-11ea-8d9b-f515797096c1.png)

**Comment by pushkar4501** [comment]
@arslansarp Hi, can you help me through the process of adding traffic in the customized map?
thanks
