### ISSUE TITLE
lgsvl suddenly closed when run apollo 5.0 in dreamviewer. 

### ISSUE THREAD

**Issue by Fred159** [lgsvl/simulator#578]
I tried to co-simulate the lgsvl with apollo 5.0. However, when dreamviewer start, lgsvl simulator close suddenly. I don't know the reason. How to solve this ? 
Is this because of hardware? 
My hardware is 8th i7, 12GB memory, gtx1060.
The problem is recorded in below link.
https://www.youtube.com/watch?v=4zIcKuwbLmY&feature=youtu.be

**Comment by cyberphysicalrobotics** [comment]
Try nvtop to check gpu memory usage. When simulator crash happens, please check the gpu memory usage. Let me know the result.

https://github.com/Syllo/nvtop

**Comment by martins-mozeiko** [comment]
@Fred159 If this happens on BorregasAve map, then try updating to latest 2019.12-rc1 version. It has new map that significantly reduces required memory.

**Comment by Fred159** [comment]
> @Fred159 If this happens on BorregasAve map, then try updating to latest 2019.12-rc1 version. It has new map that significantly reduces required memory.

Thank you . I am tring to use better computer. I will try it and update .
