### ISSUE TITLE
Radar not detect npc in Waypoints Control.

### ISSUE THREAD

**Issue by OutOfCage** [lgsvl/simulator#581]
Hi, LG Team.
I find an issue that radar can not detect npc when npc is under Waypoints control. I think [this](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Controllers/NPCController.cs#L269) may cause the issue.
I use Python API to add npc on scene. In Unity Editor, I choose `isTrigger` of npc meshcollider and `isKinematic` of npc rigidbody. Then this issue arises.

**Comment by OutOfCage** [comment]
Also, when I use Python API to add npc on scene without waypoints, the radar can detect the npc. But after I add waypoints to follow, the radar does not detect the npc.

**Comment by EricBoiseLGSVL** [comment]
For triggers to work, isKinematic must be false, this will not work
