### ISSUE TITLE
cannot find "simulation" menu button

### ISSUE THREAD

**Issue by yanglijay** [lgsvl/simulator#582]
After I open LGSVL simulator by Unity 2019.1.10f on UnithHub 2.2.2(Ubuntu 18.04),  I cannot find the "simulation" button, as shown below .Need for help! Thanks.
![2019-12-27_17-28-40](https://user-images.githubusercontent.com/56535943/71511784-7fc1c200-28ce-11ea-8aad-b12a6c3d9196.png)

**Comment by martins-mozeiko** [comment]
Please check Console window for any error messages. Unity does not fully load whole project if there are any errors during load time.
