### ISSUE TITLE
Assets's colors are black and pink

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#584]
![IMG_20191227_195851](https://user-images.githubusercontent.com/23841025/71525606-7e4ec480-28e3-11ea-8c49-484997bb53be.jpg)

I was working on Linux. Then I have decided to continue on windows. But assets are broken. Lgsvl version is 4 or 5 version old. 
 The unity version is 2019.1.10f which is exactly the version that lgsvl version wants. What do you suggest to me? (I had to work on the old version.).
Note: assets were build on Linux. It can be the problem?

**Comment by martins-mozeiko** [comment]
If this is older Simulator version, then back then we did not have cross-platform asset files (maps and vehicles). We had separate windows-only maps/vehicles and Linux-only maps/vehicles. You need to use correct AssetBundle for your OS.

Alternatively upgrade to latest version of Simulator. Few versions back we implemented cross-platform asset bundles - now each map/vehicle asset bundle works the same on Windows and on Linux.
