### ISSUE TITLE
how to get ros node list

### ISSUE THREAD

**Issue by ArthasChen** [lgsvl/simulator#587]
I have connected LG Simulator and Apollo5.0, and now I want to know how can I view the ros node list.Because I want to publish data to Apollo through my own publisher

**Comment by martins-mozeiko** [comment]
Apollo 5.0 does not use ROS. It uses CyberRT as replacement for ROS. You can see currently running Cyber nodes with `cyber_node list` command. And you can use either `cyber_channel` or `cyber_monitor`  tool to monitor topics & published messages.
