### ISSUE TITLE
Setting custom robotCandidate in RosRobots.cs

### ISSUE THREAD

**Issue by ajithkrishnan** [lgsvl/simulator#59]
Hi,
I have created a custom vehicle based on the XE-Rigged-Apollo vehicle which runs with the apollo stack. Until now i have built the repo using Unity and run the simulation after adding my vehicle to the robotCandidates list in Menu.unity directly in the editor.

![screenshot from 2019-01-02 16-53-29](https://user-images.githubusercontent.com/30627046/50599760-40c18200-0eaf-11e9-9832-0d371ddd2c2d.png)

However i would like to build using the following command -
"/opt/Unity/Editor/Unity \
    -batchmode \
    -nographics \
    -silent-crashes \
    -quit \
    -buildDestination ./build/simulator \
    -buildTarget Linux64 \
    -executeMethod BuildScript.Build \
    -projectPath . \
    -logFile /dev/stdout
"

which runs the simulation directly (bypassing the Editor). Due to this i am not able to add the said vehicle to the list of robots in the drop down menu. Is there a way to add my vehicle in RosRobots.cs so that it appears along with the other bots?

![screenshot from 2019-01-02 16-52-18](https://user-images.githubusercontent.com/30627046/50599785-559e1580-0eaf-11e9-99ac-919d4c1e5922.png)

I have already copied my vehicle prefab to the Assets/Prefabs/RobotCandidates folder.

Thank you.

**Comment by ajithkrishnan** [comment]
Solved this. I added the vehicle prefab to the robotCandidates list and saved Menu.unity scene. Then rebuilt the simulation using 
"/opt/Unity/Editor/Unity
-batchmode
-nographics
-silent-crashes
-quit
-buildDestination ./build/simulator
-buildTarget Linux64
-executeMethod BuildScript.Build
-projectPath .
-logFile /dev/stdout
"
And now it shows up.

**Comment by EricBoiseLGSVL** [comment]
Glad you were able to add the prefab.  Since MenuScript.cs is not attached to a prefab in Menu.scene, it requires you to save the scene to serialize changes.

**Comment by ajithkrishnan** [comment]
@EricBoiseLGSVL Thanks
