### ISSUE TITLE
Ground Truth of the Map

### ISSUE THREAD

**Issue by alexsimon1** [lgsvl/simulator#592]
Hello,

I currently want to evaluate a SLAM approach I implemented. For this purpose i want to compare 
the map (created by the SLAM algorithm) against a ground truth map of the enviroment. 

So my question is, is there an easy way to obtain a ground truth map from the Simulator?

Thanks

**Comment by martins-mozeiko** [comment]
Hello.

What kind of data do you mean when you say "ground truth map"? Is it localization on hdmap? Or actual geometry from real-world?

For hdmap/localization you can get ground truth data from GPS sensor. It will provide exact location of vehicle on map. As for actual geometry of map - we don't provide such data. But for some of maps (BorregasAve or AutonomouStuff) which are based on real-world locations, you might find real 3d elevation scan data in some GIS geography/map scan data. For BorregasAve you can get lidar scans from Apollo 2.5 demo rosbag: https://github.com/ApolloAuto/apollo/releases/tag/v2.5.0
