### ISSUE TITLE
cannot exit the python api properly

### ISSUE THREAD

**Issue by weiyinxie** [lgsvl/simulator#593]
hi, i'm using python api to do the simulation. Everything went wells until i add a bridge connection between python script and simulator. Each time i exit the python script i cannot restart the simulator properly anymore unless i shut down all the grafic ui and restart it on the desktop. So one idea to solve this issue is to disconnect the bridge each time when exits the python script. But unfortunately i cannt find a function with which i can disconnect the bridge

**Comment by shalinmehtalgsvl** [comment]
Hi @weiyinxie ,

There is no function to disconnect a bridge once it's been connected, but if the vehicle is deleted, then the bridge will automatically disconnect. You can delete a vehicle with `sim.remove_agent()` or when you do a `sim.reset()`, the vehicle will also be deleted.

If you are trying to reconnect to the API Only simulation with another python script, you can try putting a `sim.close()` at the end of the 1st script. The simulator allows only 1 python connection at a time.
