### ISSUE TITLE
why add restriction of apollo platform when dealing with  DetectedRadarObjectData in RosBridge

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#594]
I want to use ros bridge to connect lg sim with my ads stack , and I want to use radar info for my ads stack. but I found that in 
RosBridge.cs line 227
```c#
            else if (type == typeof(DetectedRadarObjectData) && Apollo)
            {
                type = typeof(Apollo.Drivers.ContiRadar);
                writer = new Writer<DetectedRadarObjectData, Apollo.Drivers.ContiRadar>(this, topic, Conversions.ConvertFrom) as IWriter<T>;
            }
```
it has the restriction of apollo platform, so it is not able to send radar info to rosbridge. I noticed that there is only this `DetectedRadarObjectData` type that has the restriction of apollo from the context. So I guess there must be some particular reason why you guys add this restriction. I can modify 
```
            else if (type == typeof(DetectedRadarObjectData) && Apollo)
```
to 
```
            else if (type == typeof(DetectedRadarObjectData))
```
and I can get the topic published in ros side. But i am afraid there may be some side effect of doing this.

**Comment by martins-mozeiko** [comment]
The condition includes Apollo there because we have not need to publish radar message to ROS bridge. There is nothing else that would prevent publishing radar data to ROS environment.
