### ISSUE TITLE
Failed to build Sensor plugin on linux

### ISSUE THREAD

**Issue by HansRobo** [lgsvl/simulator#598]
build fails with below error.
```
Failed to find Windows asset bundle of ComfortSensor. Please correct other errors and try again.
```

it seems that environment check of windows is executed in linux build.

**Comment by martins-mozeiko** [comment]
Do you see any other error messages above this?
Usually this error means that you did not choose Windows support for Unity during installation, so build cannot produce Windows targeted files.

**Comment by HansRobo** [comment]
Certainly I did not select Windows support when installing. 
However, it is strange that the environment check of windows is performed when the build target is linux.

**Comment by HansRobo** [comment]
Please wait a little longer for error confirmation

**Comment by HansRobo** [comment]
Other errors are below
```
Building an AssetBundle for target 'WindowsStandaloneSupport' is not allowed because the required module is not installed.
```
![Screenshot from 2020-01-15 12-04-28](https://user-images.githubusercontent.com/12395284/72401451-60aca680-378f-11ea-9de0-65fb0df0a4bb.png)

**Comment by martins-mozeiko** [comment]
The platform selection in Build dialog is only used when building simulator executable binary.

Assets - maps, vehicles and sensor plugins - are always built for both platforms: Windows and Linux. This is because when these plugins are shared with other users, they might run it on different platform than where they are built.

**Comment by HansRobo** [comment]
Oh, I see.
But, I want documentation that describes it.
Then, number of people who falls into the same situation as me will decrease.

**Comment by shalinmehtalgsvl** [comment]
Hi @HansRobo ,

Our build instructions do say to install Windows and Linux support. We'll update the docs to clarify the platform selection in the dialog.

https://www.lgsvlsimulator.com/docs/build-instructions/

**Comment by HansRobo** [comment]
Thank you for your replay
> Our build instructions do say to install Windows and Linux support.  

Oh, I overlooked it !
I'll install windows support later.
> We'll update the docs to clarify the platform selection in the dialog.  

That's great.
