### ISSUE TITLE
rviz cannot show vehicle pose in the instruction lgsvl with autoware.ai 1.12

### ISSUE THREAD

**Issue by DarrenWong** [lgsvl/simulator#599]
Hey,

I am trying to setup the simulator with autoware.ai following below instruction, https://www.lgsvlsimulator.com/docs/autoware-instructions/

operation system: ubuntu16.04 with GTX1070
Autoware version: 1.12.0
simulator version: lgsvlsimulator-linux64-2019.11

I think i stuck in the below procedure and try many times and cannot get localization. Thanks a lot.
```
Then click "Rviz" to launch Rviz - the vector map and location of the vehicle in the map should show.

The vehicle may be mis-localized as the initial pose is important for NDT matching. To fix this, click "2D Pose Estimate" in Rviz, then click an approximate position for the vehicle on the map and drag in the direction it is facing before releasing the mouse button. This should allow NDT matching to find the vehicle pose (it may take a few tries). Note that the point cloud will not show up in rviz until ndt matching starts publishing a pose.
```
screenshot of current steps
0. autoware.ai version
![Screenshot from 2020-01-15 13-07-10](https://user-images.githubusercontent.com/5771106/72407794-a3747b80-379b-11ea-8a6d-fa0f578e0bc9.png)

1. lgsvl is connected and publish msg
![Screenshot from 2020-01-15 13-17-56](https://user-images.githubusercontent.com/5771106/72407548-de29e400-379a-11ea-8d77-e0b46ec6db49.png)
2. autoware runtime manager setting with map and sense only
![Screenshot from 2020-01-15 13-11-10](https://user-images.githubusercontent.com/5771106/72408154-f26ee080-379c-11ea-946c-0b0f5ceb6fb0.png)

autoware runtime manager with localization and rviz together
![Screenshot from 2020-01-15 13-16-12](https://user-images.githubusercontent.com/5771106/72408061-94da9400-379c-11ea-8318-5e2d6bfedc8c.png)

3. ros rviz only see map, i use defalut rviz config
![Screenshot from 2020-01-15 13-13-48](https://user-images.githubusercontent.com/5771106/72407608-0fa2af80-379b-11ea-8bbb-7cc37971c786.png)

4. wait some times and try many times 2D pose estimate, the status still not change
![image](https://user-images.githubusercontent.com/5771106/72407654-3f51b780-379b-11ea-8143-da030910c808.png)

**Comment by martins-mozeiko** [comment]
Are you setting initial position in middle of two yellow lines? Because that's not correct car position. In Simulator you can see that car is to the right of both yellow lines. Try setting initial position in second line from left side, not in middle of yellow lines.

**Comment by DarrenWong** [comment]
thanks for your replay @martins-mozeiko , it seems my mistake for the wrong init pose

With your suggestion with a few try(in second lane, in lane boundary, or first lane, or some places up and down) still cannot get the init pose, would you mind giving a example screenshot for the correct  pose estimate?  And if the map have a marker(such as direction signal) for the init pose it would be very helpful for the quickstart example

Some init pose i tried,  and i noticed the point_raw in rviz status error but i can receive the point_raw msg by __rostopic echo /points_raw__
![Screenshot from 2020-01-17 11-09-31](https://user-images.githubusercontent.com/5771106/72581655-0fc9b900-391b-11ea-8032-82c7726d4d28.png)
![Screenshot from 2020-01-17 11-12-41](https://user-images.githubusercontent.com/5771106/72581660-13f5d680-391b-11ea-8c6a-d7c755f1d7c1.png)
![Screenshot from 2020-01-17 11-12-17](https://user-images.githubusercontent.com/5771106/72581663-15270380-391b-11ea-9abe-ab46dc887e88.png)
.

**Comment by DarrenWong** [comment]
BTW when i start simulation it says my map out-of-date, so i update the map assets here, did it have any effects? actually i try latest 2019.12-rc1(with below content updated) also similar problems...
https://content.lgsvlsimulator.com/maps/borregasave/

https://assets.lgsvlsimulator.com/513316ab0ed5896f91cf7e6ff4e138b068993626/environment_BorregasAve

**Comment by DarrenWong** [comment]
closed as no further response...

**Comment by yugushihuang** [comment]
@DarrenWong 

I got exactly same problem as yours, did you get it resolved?

**Comment by DarrenWong** [comment]
@yugushihuang  no..  tries many many times...

**Comment by AIasd** [comment]
I encountered the same problem (system: ubuntu18.04 GPU: RTX2080TI). Does anyone solve it?

**Comment by JockTokk** [comment]
@AIasd try to run the simulation in simulator and try to init position
