### ISSUE TITLE
How to Enable GPS, IMU, LIDAR, Main Camera, and Telephoto Camera inside the simulator

### ISSUE THREAD

**Issue by YilmazOrkun** [lgsvl/simulator#601]
In the instructions it is said to follow these steps:

> Run the LG SVL Simulator outside of docker. See instructions in the simulator repository
> 
> Select the BorregasAve map and the Lincoln2017MKZ (Apollo 5.0) vehicle.
> Enable GPS, IMU, LIDAR, Main Camera, and Telephoto Camera.
> (optional) Enable Sensor Effects, Traffic and Pedestrian.

How do I enable gps, imu, lidar etc inside the simulator?

The bridge view only shows the messages, but there are no toggles to enable these.
I am using https://github.com/lgsvl/apollo-5.0

**Comment by shalinmehtalgsvl** [comment]
Hi @YilmazOrkun ,

The Apollo 5.0 Readme is out of date. If a vehicle has the sensors in it's [sensor configuration](https://www.lgsvlsimulator.com/docs/sensor-json-options/), then the sensors will be enabled automatically and will be publishing data to the bridge. The [default MKZ configuration](https://www.lgsvlsimulator.com/docs/apollo5-0-json-example/) contains all of those sensors

When [creating a simulation](https://www.lgsvlsimulator.com/docs/simulations-tab/), enable `Interactive Mode` to be able to enable Traffic and Pedestrians inside the simulator.

Sorry about the confusion, we'll update the docs in our next push.
