### ISSUE TITLE
NPC and Pedestrian IsVisible() check.

### ISSUE THREAD

**Issue by qmitw188** [lgsvl/simulator#602]
Hello there,

When spawning NPCs and Pedestrians, both SetNPCOnMap() and SetPedOnMap() have IsVisible() methods to check each EGO sensor.

Could you please tell me why it have to do this check ?

Thanks.

**Comment by daohu527** [comment]
@qmitw188 The area that NPCs can spawn in is limited for performance reasons.
You can refer to #600, There are some issues with the IsVisible method because the spawn point is on the lane point[0], which means you cannot get car spawn outside the camera. 
There will be some new solutions!

**Comment by qmitw188** [comment]
@daohu527 thanks.
