### ISSUE TITLE
Lidar topic not visible in cyber_monitor

### ISSUE THREAD

**Issue by YilmazOrkun** [lgsvl/simulator#606]
I would like to use the simulator to collect record files which contains lidar point cloud data.
When I run the simulator I can see that there are messages in /apollo/sensor/lidar128/compensator/PointCloud2 in the bridge view.

But when I launch cyber_monitor the pointcloud topic is not listed there.

**Comment by daohu527** [comment]
Do you run the bridge.sh in apollo. You can refer to https://github.com/lgsvl/apollo-5.0#launching-apollo-alongside-the-simulator

You should check the step"Launch bridge (inside docker container):"

**Comment by YilmazOrkun** [comment]
I have launched the bridge.
I can see topics from other sensors with cyber_monitor, but not the Pointcloud topic

**Comment by daohu527** [comment]
Does your car really have a lidar configuration? If so, you need to check the simulator or apollo to see if there are any errors. By the way do you modify the lidar proto file?

**Comment by YilmazOrkun** [comment]
Yes it has. In the simulator when I look to the bridge there is a pointcloud topic which is publishing messages. I can also visualize the pointcloud inside simulator. I did not modify any lidar proto file.

**Comment by martins-mozeiko** [comment]
Can you please show screenshot of bridge view in Simulator that shows lidar topic? And also screenshot of cyber_monitor.
