### ISSUE TITLE
How to use steering wheel controller.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#61]
![image](https://user-images.githubusercontent.com/10348912/50762606-c5960c80-12b0-11e9-81a2-d95153916ef1.png)
I found that the Steering Wheel Controller module is on the Unity Editor.
But my steering wheel controller does not work (Logicool G29).
Please tell me how to use Steering wheel controller.

**Comment by martins-mozeiko** [comment]
Did you install Logitech G29 driver? You can get it in "Logitech Gaming Software" download from https://support.logitech.com/en_us/product/g920-driving-force/downloads
Unity does not recognize wheel unless its driver is installed.

**Comment by hakuturu583** [comment]
@martins-mozeiko Thanks!!!
