### ISSUE TITLE
How to give each pedestrian a different color in Semantic Camera?

### ISSUE THREAD

**Issue by RamoramaInteractive** [lgsvl/simulator#610]
According to https://www.lgsvlsimulator.com/docs/sensor-visualizers/#semantic-camera pedestrians have the semantic color red. Is it possible to set up the semantic camera to give each single pedestrian a different color value? 

I want to use the pretrained ssd_mobilenet_v1_coco_2018_01_28 to draw on each pedestrian a rectangle and they should be seperated.

**Comment by martins-mozeiko** [comment]
Current code does not allow this.
But there is pull request that implemented such functionality: https://github.com/lgsvl/simulator/pull/453
Unfortunately it gives significant performance penalty. You should check if that is acceptable in your use case.

**Comment by RamoramaInteractive** [comment]
I changed the Script files but after starting the new compiled Simulator I received following error:

```
Traceback (most recent call last):
  File "run_sim.py", line 23, in <module>
    a = sim.add_agent("Lincoln2017MKZ (Apollo 5.0)", lgsvl.AgentType.EGO, state)
  File "c:\users\myComputer\desktop\pythonapi\lgsvl\utils.py", line 21, in new_f
    return f(*args, **kwargs)
  File "c:\users\myComputer\desktop\pythonapi\lgsvl\simulator.py", line 110, in add_agent
    uid = self.remote.command("simulator/add_agent", args)
  File "c:\users\myComputer\desktop\pythonapi\lgsvl\remote.py", line 68, in command
    raise Exception(data["error"])
Exception: Object reference not set to an instance of an object
```

**Comment by zelenkovsky** [comment]
Well, that's difficult to answer if we do not know what did you change in the script.

Do you still have "Lincoln2017MKZ (Apollo 5.0)" vehicle?

**Comment by RamoramaInteractive** [comment]
@zelenkovsky I've included all the commits from https://github.com/lgsvl/simulator/pull/453 to its appropiate cs-files and also included the missing files into my Unity simulator.

Yes, I'm still using the "Lincoln2017MKZ (Apollo 5.0)" vehicle.

**Comment by RamoramaInteractive** [comment]
After 2 months how can I find out if I included the right source Codes from https://github.com/lgsvl/simulator/pull/453 into my Unity Simulator?

Can I still use the Semantic Camera after enabling the Semantic Segmentation?

**Comment by EricBoiseLGSVL** [comment]
@RamoramaInteractive Yes, we have looked at the merge request and it should be fine.  We have implemented the same feature and will be releasing it soon.

**Comment by EricBoiseLGSVL** [comment]
@RamoramaInteractive we are releasing the instance semantic as a JSON setting in semantic camera sensors.  Thank you for your contribution.  The next public release should be in a few days
