### ISSUE TITLE
Increase the road length of SingleLaneRoad map

### ISSUE THREAD

**Issue by junjieshen** [lgsvl/simulator#611]
Hi,

Sorry if I post the question in the wrong place since I couldn't file an issue in the SingleLaneRoad repo. 

I was wondering if there is any way to increase the road length of the SingleLaneRoad map. Currently, it seems the length is around 200m. I would like to increase the length for testing the driving behavior in a long duration.

Thanks,
Junjie

**Comment by EricBoiseLGSVL** [comment]
@junjieshen 

We are looking to create a longer test map but we are not sure when we will be able to release it.  In the meantime, you can open SingleLaneRoad in Editor, duplicate the road mesh as many times as you need and build a new map.

**Comment by junjieshen** [comment]
@EricBoiseLGSVL 

Thank you for the suggestion. Duplicating the mesh did the trick for me!
