### ISSUE TITLE
Using three camera sensors at the same time

### ISSUE THREAD

**Issue by RamoramaInteractive** [lgsvl/simulator#612]
I want to capture an image and save it as Color image, semantic image and depth image as well.
Is it possible to declare three sensor objects of the sensor object and capture an image at the same time?

**Comment by mark-gerow-lge** [comment]
I am unsure of the exact question here, you can place a Color, Depth, and Semantic sensor on your vehicle at the same time.

**Comment by shalinmehtalgsvl** [comment]
Hi @RamoramaInteractive ,

You can use the Python API to save images from the cameras or you can subscribe to the ROS topics published by the sensors.

You would need to add all 3 cameras to a vehicle and make sure the parameters are all the same for you to get the same perspective in the images.
