### ISSUE TITLE
Simulator built from source crashing (Ubuntu 16.04)

### ISSUE THREAD

**Issue by DaPineappleDude** [lgsvl/simulator#615]
Following the [instructions](https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md) on building the simulator from source. The build proceeds without any error and Unity shows that build completes but I am running into these problems:

-  When I launch the simulator and selecting the graphics settings the unity window crashes after showing Unity logo and turning black. As a reference, I can run the pre-built simulator release with no problems.
![image](https://user-images.githubusercontent.com/11544638/73416040-8033eb00-42c8-11ea-8e86-2a1c2c6498c2.png)

- The `Web` folder in the final build is missing even though I do `npm install` and `npm run pack`
![image](https://user-images.githubusercontent.com/11544638/73415916-1fa4ae00-42c8-11ea-833f-3e501d8b28c0.png)

The reason I am rebuilding the simulator is because I wanted to use a G29 steering wheel and had to modify the Controller Inteactions related stuff.

**Comment by EricBoiseLGSVL** [comment]
@DaPineappleDude Do you have the Editor logs to see if there are any errors in the build process?

Did you set the OS to Linux?

**Comment by DaPineappleDude** [comment]
@EricBoiseLGSVL I didn't see any errors during the build and it showed `Player build successful` on Unity Editor. I will check if I have the logs and get back.

Yes, I did set the OS to Linux.

Also, after some digging I noticed a folder `~/simulator/` with `AssetBundles` and `Web` as sub folders inside my source code directory. I found that odd.

**Comment by EricBoiseLGSVL** [comment]
Ok, if no errors on build let's look at player.log to see what is happening.  AssetBundles and Web sub folders is expected.  AssetBundles folder holds built asset, e.g. environments, vehicles, etc. and Web folder holds WebUI assets for sign in and simulation settings.

Also, please see what nvidia drivers version you are on and did you build an environment bundle and vehicle bundle?  If there are no environments or vehicles to load it might be crashing.  The best way to quickly add the latest is to download latest binary release, run it and it will open WebUI that will download all public released assets.  If that fails then delete the LG Silicon Valley Lab folder in AppData folder in user files and run binary again.
