### ISSUE TITLE
Do you have a example of Re-simulation of Real world sensor data?

### ISSUE THREAD

**Issue by etendue** [lgsvl/simulator#616]
In the introduction video,
https://youtu.be/YOCCh10Mlvw?t=200
it is mentioned the Re-simulation of Real-world sensor data. What does it mean? Does it mean feeding the recorded sensor data and visually display the vehicle behavior in the simulation?

**Comment by EricBoiseLGSVL** [comment]
@etendue 

Yes, recorded sensor data and playback in the simulation.  We are still putting the final touches on this and should be ready soon
