### ISSUE TITLE
Cannot open lgsvl on google cloud

### ISSUE THREAD

**Issue by wangyixu14** [lgsvl/simulator#620]
Hi, all:

I am using google cloud compute engine on Ubuntu 18.04 and remote desktop with GPU Nvidia information shown as follows:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
+-----------------------------------------------------------------------------+
When I click ok, no windows show up for open the brower.
The ~/.config/unity3d/Editor/Player.log shows as:

**
Desktop is 1920 x 888 @ 0 Hz
[Vulkan init] extensions: count=15
[Vulkan init] extensions: name=VK_KHR_device_group_creation, enabled=0
[Vulkan init] extensions: name=VK_KHR_display, enabled=1
[Vulkan init] extensions: name=VK_KHR_external_fence_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_memory_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_external_semaphore_capabilities, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_physical_device_properties2, enabled=0
[Vulkan init] extensions: name=VK_KHR_get_surface_capabilities2, enabled=0
[Vulkan init] extensions: name=VK_KHR_surface, enabled=1
[Vulkan init] extensions: name=VK_KHR_xcb_surface, enabled=0
[Vulkan init] extensions: name=VK_KHR_xlib_surface, enabled=1
[Vulkan init] extensions: name=VK_EXT_acquire_xlib_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
[Vulkan init] extensions: name=VK_EXT_direct_mode_display, enabled=0
[Vulkan init] extensions: name=VK_EXT_display_surface_counter, enabled=0
Preloaded type GtkListStore
Preloaded type GtkWindow
Preloaded type GtkVBox
Preloaded type GtkImage
Preloaded type GtkNotebook
Preloaded type GtkHBox
Preloaded type GtkFrame
Preloaded type GtkAlignment
Preloaded type GtkTreeView
Preloaded type GtkLabel
Preloaded type GtkCheckButton
Preloaded type GtkScrolledWindow
Preloaded type GtkComboBox
Vulkan detection: 0
No supported renderers found, exiting

(Filename: ./PlatformDependent/LinuxStandalone/main.cpp Line: 639)
**
 
But I do have used the  'sudo apt-get install libvulkan1 ' and successfully executed. 

What's the problem here?

Thanks

**Comment by EricBoiseLGSVL** [comment]
Cloud is not technically supported at the moment but @herb-kuta-lge might be able help.

**Comment by wangyixu14** [comment]
> Cloud is not technically supported at the moment but @herb-kuta-lge might be able help.

**Comment by herb-kuta-lge** [comment]
Hi. I've found that an X server must be running on the same machine as the simulator and the `DISPLAY` environment variable set to the display it's serving in order for Unity to find a Vulkan renderer.

**Comment by QLV5645-QLJ** [comment]
Hi, thanks for your replying. But it still has the same problem.

I am able to get this window on my local computer. But when I click Ok, nothing happen, How do you run that?
![image](https://user-images.githubusercontent.com/43660446/73986754-0d4bf500-4904-11ea-9aa7-551495c7b23c.png)

**Comment by herb-kuta-lge** [comment]
Is Simulator running on your local computer? What is the value of `DISPLAY`? Remote rendering is not supported.

**Comment by QLV5645-QLJ** [comment]
The simulator is running on the Server. And I set the DISPLAY value to be can local computer IP and Port. The log says this:
![image](https://user-images.githubusercontent.com/43660446/73987313-90ba1600-4905-11ea-893c-6393abae203a.png)

**Comment by herb-kuta-lge** [comment]
>+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01 Driver Version: 440.33.01 CUDA Version: 10.2 |
+-----------------------------------------------------------------------------+

Are there really no GPUs listed by `nvidia-smi`? That would certainly be problem...

**Comment by QLV5645-QLJ** [comment]
Actually. I have GPU on my remote container.
![image](https://user-images.githubusercontent.com/43660446/73988316-f3141600-4907-11ea-9eb4-deb94323de20.png)

**Comment by wangyixu14** [comment]
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 440.33.01 Driver Version: 440.33.01 CUDA Version: 10.2 |
> > +-----------------------------------------------------------------------------+
> 
> Are there really no GPUs listed by `nvidia-smi`? That would certainly be a problem...

Oh, there are one gpu but I am using the remote desktop by google. 
So lgsvl doesn't support this?

Thanks

**Comment by herb-kuta-lge** [comment]
>  using the remote desktop by google.

**Comment by wangyixu14** [comment]
> > using the remote desktop by google.
> 
> Do you mean [Chrome Remote Desktop](https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp)?

Yes, right.

**Comment by herb-kuta-lge** [comment]
We have not tried to use Chrome Remote Desktop with the Simulator.

**Comment by herb-kuta-lge** [comment]
There's this note at the top of https://cloud.google.com/solutions/chrome-desktop-remote-on-compute-engine:

> Note: This solution is not suitable for graphically intensive applications, including playing videos, because those typically require hardware graphics acceleration as well as a network that has high bandwidth and low latency. If you want to run graphically intense applications remotely, see the [Creating a virtual GPU-accelerated Linux workstation](https://cloud.google.com/solutions/creating-a-virtual-linux-workstation) tutorial for an alternative solution.

Simulator is certainly a graphically intensive application, so your best bet would be to try the alternative solution the note mentions.

**Comment by wangyixu14** [comment]
Thanks for the reply.
