### ISSUE TITLE
Can not open simulator on cloud.

### ISSUE THREAD

**Issue by QLV5645-QLJ** [lgsvl/simulator#625]
hi, I have problem in opening simulator. Anyone can help me? Thanks!

I download the linux package and double click the simulator. I appear this.
![image](https://user-images.githubusercontent.com/43660446/73905137-f05fe500-4863-11ea-924a-7d29e524864e.png)

When I click ok button, it just close and nothing happen. Not open browser GUI shown.

I use VNC on cloud to visualize the container,

**Comment by EricBoiseLGSVL** [comment]
@QLV5645-QLJ Please see [this](https://github.com/lgsvl/simulator/issues/620) existing issue.
