### ISSUE TITLE
how can I get pointcloud ring

### ISSUE THREAD

**Issue by neophack** [lgsvl/simulator#630]
![2020-02-12 23-23-41 的屏幕截图](https://user-images.githubusercontent.com/12814250/74350700-097f0d80-4df1-11ea-9567-ed2992b105a5.png)
![2020-02-12 23-25-20 的屏幕截图](https://user-images.githubusercontent.com/12814250/74350713-0d129480-4df1-11ea-9454-590781f98636.png)
![2020-02-12 23-42-34 的屏幕截图](https://user-images.githubusercontent.com/12814250/74350917-637fd300-4df1-11ea-8c04-c610dfcff371.png)

lgsvl have no ring in data

**Comment by EricBoiseLGSVL** [comment]
@hadiTab is ring supported in our msg to rviz?

**Comment by soldierofhell** [comment]
@EricBoiseLGSVL, @hadiTab, I've inspected the ROS2 bridge code and indeed, there's no ring field in PointCloud2 message. Are there any plans to extend it? For Velodyne-type rotating lidars this is very important, e.g. some SLAM algorithms use it directly

**Comment by bahattinkoc** [comment]
Any progress? i still can't get the ring data?
