### ISSUE TITLE
Python API run() doesn't start the simulation

### ISSUE THREAD

**Issue by joshwapohlmann** [lgsvl/simulator#631]
Using 2020.01-rc1 the Python API function `run()` doesn't actually start the simulation. manual press on the "play" button is still required.

## Steps to reproduce
1. Start simulator
2. Run simulation in "API only" mode
3. Connect via python API
4. load a scene and issue `run()` command.

## Expected behavior
The simulator should start on it's own.

## Observed behavior
It doesn't

## Additional Notes
When `reset()`ing the scene, it will not pause the simulation and it works.

**Comment by EricBoiseLGSVL** [comment]
@shalinmehtalgsvl were you having this issue?

**Comment by EricBoiseLGSVL** [comment]
@joshwapohlmann this is a bug that we have on the list to fix.  Thanks for letting us know

**Comment by joshwapohlmann** [comment]
@EricBoiseLGSVL I just did some quick digging and checked the implementation of the run command against the actual button press. 
The difference I saw was the usage of some kind of `timeScaleLock`, which is not used in any way by the run() implementation. Just a quick guess/hint, maybe of help.

**Comment by EricBoiseLGSVL** [comment]
@joshwapohlmann excellent, that helps.
