### ISSUE TITLE
Simulator crashed from "LGSVL Simulator Configuration"

### ISSUE THREAD

**Issue by kanbei** [lgsvl/simulator#633]
Hello!
I press the OK button in "LGSVL Simulator Configuration", it suddenly crashed.
My graphics card is GeForce RTX 2070.
According to the Player.log, it seems to be the drive of graphics card is not be supported.
My driver version is  430.64, cuda version is 10.0, and I have tried different version of the drive and cuda, the simulator still crashed.
What's the reason of it?

--------------------------------------------------------------------------------
Desktop is 1920 x 1080 @ 60 Hz
[Vulkan init] extensions: count=2
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
[Vulkan init] extensions: name=VK_EXT_debug_utils, enabled=0
Vulkan error VK_ERROR_INCOMPATIBLE_DRIVER (-9) file: ./Runtime/GfxDevice/vulkan/VKContext.cpp, line: 333
Vulkan error./Runtime/GfxDevice/vulkan/VKContext.cpp:333
Vulkan detection: 0
No supported renderers found, exiting
 
(Filename: ./PlatformDependent/LinuxStandalone/main.cpp Line: 639)

Preloaded type GtkListStore
Preloaded type GtkWindow
Preloaded type GtkVBox
Preloaded type GtkImage
Preloaded type GtkNotebook
Preloaded type GtkHBox
Preloaded type GtkFrame
Preloaded type GtkAlignment
Preloaded type GtkTreeView
Preloaded type GtkLabel
Preloaded type GtkCheckButton
Preloaded type GtkScrolledWindow
Preloaded type GtkComboBox

![Screenshot from 2020-02-07 16-45-35](https://user-images.githubusercontent.com/14128881/74432834-959d3d80-4ea2-11ea-8126-6767a4a96717.png)

**Comment by EricBoiseLGSVL** [comment]
@kanbei Have you updated your driver?  Any other error logs you can post?

**Comment by EricBoiseLGSVL** [comment]
@kanbei Also, if you are running Apollo 5.0, it does not support Volta and Turing architecture GPUs (Titan V and RTX GPUs)  To run simulator our engineer that has a RTX 2080Ti and his driver is 440.59 and Cuda 10.2

**Comment by ck-leo** [comment]
@EricBoiseLGSVL I have the same issue, My graphics card is GeForce RTX 2060 6G

the error file is :
Desktop is 1920 x 1080 @ 144 Hz
[Vulkan init] extensions: count=1
[Vulkan init] extensions: name=VK_EXT_debug_report, enabled=0
Vulkan error VK_ERROR_INCOMPATIBLE_DRIVER (-9) file: ./Runtime/GfxDevice/vulkan/VKContext.cpp, line: 333
Vulkan error./Runtime/GfxDevice/vulkan/VKContext.cpp:333
Vulkan detection: 0
No supported renderers found, exiting
 
(Filename: ./PlatformDependent/LinuxStandalone/main.cpp Line: 639)

Preloaded type GtkListStore
Preloaded type GtkWindow
Preloaded type GtkVBox
Preloaded type GtkImage
Preloaded type GtkNotebook
Preloaded type GtkHBox
Preloaded type GtkFrame
Preloaded type GtkAlignment
Preloaded type GtkTreeView
Preloaded type GtkLabel
Preloaded type GtkCheckButton
Preloaded type GtkScrolledWindow
Preloaded type GtkComboBox

And my nvidia-smi result is :

![Screenshot from 2020-02-26 10-39-03](https://user-images.githubusercontent.com/48859422/75306493-3ff26900-5884-11ea-9a30-36c96229290b.png)

Is there some other suggestions?Thanks.

**Comment by EricBoiseLGSVL** [comment]
@ck-leo Please see if this [issue 287](https://github.com/lgsvl/simulator/issues/287) helps.

**Comment by ck-leo** [comment]
OK, Thanks.

——
------------------------------------------------------------------
发件人：Eric Boise <notifications@github.com>
发送时间：2020年2月27日(星期四) 07:09
收件人：lgsvl/simulator <simulator@noreply.github.com>
抄　送：ck-leo <ck_leo@aliyun.com>; Mention <mention@noreply.github.com>
主　题：Re: [lgsvl/simulator] Simulator crashed from "LGSVL Simulator Configuration" (#633)

@ck-leo Please see if this issue 287 helps.

**Comment by EricBoiseLGSVL** [comment]
@kanbei @ck-leo We have a new release using a newer version of Unity and should be out in a few days.  Unity update fixes many Vulkan issues but if not please re-open this issue
