### ISSUE TITLE
Make file issue

### ISSUE THREAD

**Issue by Martin20** [lgsvl/simulator#634]
Hello all,

Do you know where is the make file to compile the cc files in apollo?

I use Apollo 5.0,
ubuntu 16.04
and I built it.

**Comment by ntutangyun** [comment]
I'm quite new, but as far as I know, Apollo 5.0 uses bazel to build the project. 

You could look for the `BUILD` files under those source code folders as well as protobuf folders.

**Comment by Martin20** [comment]
Thank you so much. You are right.

**Comment by ntutangyun** [comment]
@Martin20 you're welcome. Kindly close the issue if no further questions. :)

**Comment by Martin20** [comment]
Thanks


best regards,

--
*Mohammadreza Mehrabian,*
Graduate Assistant/Associate
School of Computing, Informatics and Decision Systems Engineering
Ira A. Fulton Schools of Engineering
Arizona State University, Tempe, AZ 85281
