### ISSUE TITLE
Map Signal IDs doesn't match the Apollo 5.0 base_map

### ISSUE THREAD

**Issue by ntutangyun** [lgsvl/simulator#635]
Hi team,

I found that the signals in lgsvl simulator do not match those in Apollo 5.0 base_map in terms of IDs.

Take `borregas_ave` map for example:
below is the picture generated from Apollo 5.0 base_map file, where the traffic signals are drawn for the first junction:

<img width="878" alt="signal_location_from_base_map" src="https://user-images.githubusercontent.com/16061105/74511712-8faa6980-4f41-11ea-9442-976e555737ff.png">

Note that the traffic signal IDs are simplified, i.e. from `signal_2` to `s_2` etc. 

<img width="842" alt="game" src="https://user-images.githubusercontent.com/16061105/74511905-07789400-4f42-11ea-97d6-c383f4052290.png">

When the ego vehicle approaches as shown above, there are 4 signal associated.
According to Apollo 5.0 base map, they are `signal_2`, `signal_5`, `signal_6` and `signal_12`. This also matches the output taken from `/apollo/perception/traffic_light` default camera data are fed to Apollo 5.0.

However, when I was trying to get the signals from lgsvl scripts, with following code:
```c#
closestLane = SimulatorManager.Instance.MapManager.GetEgoCurrentLane(transform.parent.transform.position);
Debug.Log("====================================================");
Debug.Log("there are " + closestLane.stopLine.signals.Count + " signals");
foreach (MapSignal signal in closestLane.stopLine.signals)
{
       Debug.Log(signal.ID);
       Debug.Log("-----");
}
```
this is what I got:

<img width="462" alt="signal_debug_msg" src="https://user-images.githubusercontent.com/16061105/74512209-b917c500-4f42-11ea-82cd-756cc57c98ff.png">

<img width="675" alt="signal_objects" src="https://user-images.githubusercontent.com/16061105/74512235-d056b280-4f42-11ea-9145-71bb6a5c4f50.png">

I'm not sure why the IDs are set this way. But they don't match with Apollo 5.0 base_map in the latest release. 

Or is it matching those in Autoware maps ?

Thanks.

**Comment by EricBoiseLGSVL** [comment]
@luqiang21 or Tae know what is happening here?

**Comment by cyberphysicalrobotics** [comment]
@ntutangyun Which Simulator version are you using?

**Comment by cyberphysicalrobotics** [comment]
@ntutangyun There is id property, not ID. I think id property will have signal id. So please add checking id in your debug routine. Let me know your result.

**Comment by ntutangyun** [comment]
@cyberphysicalrobotics Thank you for reply. 
I'm using the latest version. pulled from master branch, quite recently (1 Feb).

```c#
closestLane = SimulatorManager.Instance.MapManager.GetEgoCurrentLane(transform.parent.transform.position);
            Debug.Log("====================================================");
Debug.Log("there are " + closestLane.stopLine.signals.Count + " signals");
foreach (MapSignal signal in closestLane.stopLine.signals)
{
      Debug.Log("ID: " + signal.ID + " id: " + signal.id + " UID: " + signal.UID);
      Debug.Log("-----");
}
```

Below is what I got:
![image](https://user-images.githubusercontent.com/16061105/74583019-c9d94100-4ffd-11ea-965b-3757c1e70946.png)

There are four related fields for `MapSignal` class, `string UID`, `uint ID`, `string id` and `string Key => UID`.  since Key is same as UID, so I just logged the other three. 

and Only `ID` is set, to a seemingly random number, the small `id` and `UID` are NULL.
