### ISSUE TITLE
Vehicle don't move in Apollo 3.5

### ISSUE THREAD

**Issue by simon13579** [lgsvl/simulator#636]
Hello,

I follow the instructions to build LGSVL Apollo 3.5 code and use the released simulator 2019.12, the route is generated but the vehicle don't move.
![lgsvl-fail](https://user-images.githubusercontent.com/38149116/74603440-84487100-50ee-11ea-9adb-4efd1485bfaf.png)

The error "RAW IMU message delay" and "RAW GPS message delay" displays in the dreamviewer, is it the root cause and how can I fix it? And sometimes the Perception in the module control tab is deselected but that doesn't happen every time . 
By the way, in the Routing Editing tab of the dreamviewer, I can't find the command "submit the routine", but only "send the routine request" can be found.

Thanks,
Simon

**Comment by ntutangyun** [comment]
@simon13579 try use keyboard to manually drive the vehicle a little bit forward and see if the vehicle starts moving ?

**Comment by simon13579** [comment]
By using keyboard, the vehicle starts moving, but it still can't follow the routine. It seems that the apollo software doesn't send control control command to simulator.

**Comment by ntutangyun** [comment]
@simon13579 the default mode should be correct.

By right after you drove the vehicle a little bit forward manually, Apollo should be able to take over and continue to drive it following the route. 

by your screenshot, there is a bus at the intersection, but in dreamview, Apollo's perception module is not capturing any obstacles. This is not right. 

1. Maybe you could give the system a little bit time to start up. And see if Apollo is able to start drawing those obstacles in the Dreamview page.

2. In Dreamview -> tasks page, there should be indicators of message delays of various topics. You could check if any module is not sending messages. 

3. you could get into the docker container, and use `cyber_monitor` to check if all the modules are working correctly. 

4. if some module is not working, you could get into the docker container, and try start the module manually. (note turn off the same module in Dreamview first). e.g. `cyber_launch start modules/perception/launch/percetion.launch` etc.   

Above is based on my understanding of Apollo 5.0. for Apollo 3.5 please adjust accordingly. 

Hope it helps.

**Comment by simon13579** [comment]
After I use cyber_monitor, it shows that the perception module is not working. Then I use the command cyber_launch start modules/perception/production/launch/perception.launch
![0217-01](https://user-images.githubusercontent.com/38149116/74651513-ef617880-51be-11ea-8fea-7366e8c06e78.png)
![1-t](https://user-images.githubusercontent.com/38149116/74651934-eae98f80-51bf-11ea-8920-e4de09169aa4.png)

Only perception/motion_service starts working. And I check the perception log file in the data/log folder, no error information is shown.
![0217-3](https://user-images.githubusercontent.com/38149116/74651700-5a12b400-51bf-11ea-8d30-d71f94f42d5e.png)

Where can I find the error information of perception module?
And I don't install opencv, caffe2 and CUDA on my host computer, is that OK?

Best Regards.

**Comment by ntutangyun** [comment]
@simon13579 could you check if the simulator is publishing any lidar sensor output. i.e. `point_cloud` related topics ?

Not sure about Apollo 3.5, but for Apollo 5.0, the perception module requires `point_cloud` data to output its own `/apollo/perception/obstacles` message.

**Comment by simon13579** [comment]
@ntutangyun could you please tell me how to check? Sorry, I just start to use LGSVL and Apollo. Thanks!

**Comment by simon13579** [comment]
There is no point_cloud topics inside cyber_monitor, only camera related topic. Is it correct that simulator only output the camera message?
![0222-01](https://user-images.githubusercontent.com/38149116/75083958-b9721a80-5557-11ea-812e-a1adedcaf074.png)

And I check some document of Apollo 3.5, it seems that its perception don't requires lidar data.
In dreamviewer the warning message "Raw IMU message delay" and "Raw GPS message delay“ are shown, could it be the root cause? How to fix this issue? My graphic card is GTX 1660ti that has 6G memory, could it be a problem?
![0222-02](https://user-images.githubusercontent.com/38149116/75084113-deb35880-5558-11ea-820f-e83d417cd3a9.png)


Finally how can I find the root cause why perception module is not working? Where to find the log message? I check the perception log file in the data/log folder, no error information is shown.

Best Regards

**Comment by ajay1606** [comment]
@simon13579 Did you fixed this issue? Am also getting the same warning message "Raw IMU message delay" and "Raw GPS message delay“ !

Could you please help me if you have already got fixed this issue?

Best Regards.

**Comment by simon13579** [comment]
@ajay1606 No, this issue is still here, please let me know if you have any solution, thanks!

Best Regards.

**Comment by EricBoiseLGSVL** [comment]
I'm guessing this issue is a 6gb GPU running simulator and Apollo.  This is not ideal.  I also recommend using Apollo 5.0 or current Apollo.  We have been working with the team to fix many issues with Apollo and LGSVL Simulator and we recommend using the latest version.
