### ISSUE TITLE
Gps outputs data with offset

### ISSUE THREAD

**Issue by SeymurSm** [lgsvl/simulator#641]
Hi Guys,

We are working with Gps sensor and Autoware to apply localization by means of Autoware. We noticed that the Gps sensor has returns longitude value with offset that is shown on below snapshot. I think both latitude and longitude should be values near to 0 if our map built near to Unity global origin. When I change 'IgnoreMapOrigin' flag to false on pre-built maps such as BorregasAvenue it also returns longitude value with offset which is problem for localization.

![GpsSensor](https://user-images.githubusercontent.com/8245619/74914530-a3d3e800-53d3-11ea-88ec-bf89e87c09cc.PNG)

Furthermore, I have checked the code below that returns latitude and longitude values and not understand if there is problem with the conversion.

![Code](https://user-images.githubusercontent.com/8245619/74914769-0f1dba00-53d4-11ea-96d0-6c8b930f8dfd.PNG)

Thanks in advance.

**Comment by hadiTab** [comment]
What versions of Autoware and the Simulator are you using?
GNSS localizer in Autoware only works in the Japanese coordinate system. There are also some issues related to working in coordinates near (0, 0).

**Comment by SeymurSm** [comment]
@hadiTab  sorry for late reply. 
We are using simulator version 2019 by using ignore map origin flag as true in our GPS configuration.
Changin  `double x = easting - 500000d;` to ` double x = easting;`     in  MapOrigin.Conversion.cs has solved our problem. 

![Screenshot from 2020-02-28 17-33-34](https://user-images.githubusercontent.com/8245619/75557098-7da3ed00-5a50-11ea-967c-2f7a2796451e.png)

**Comment by codezs09** [comment]
@SeymurSm I tried your solution and it works to correct GPS lat long. But it seems that the GPS_odometry sensor output also changes correspondingly. So if one is using the odometry information, it may not be a good idea to change that line.
