### ISSUE TITLE
Ubuntu 16.04 build failed

### ISSUE THREAD

**Issue by liiiu** [lgsvl/simulator#648]
hi, lg

I went to the last step according to your documentation, and I got an error when I built the simulator.

What's wrong? thx.

![2020-02-25 10-12-22屏幕截图](https://user-images.githubusercontent.com/49083466/75208842-b37a7480-57b7-11ea-98b0-0e8ac1ed7d2b.png)

**Comment by EricBoiseLGSVL** [comment]
@liiiu Can you post the editor logs please?

**Comment by liiiu** [comment]
I have solved the problem because of mu nvidia driver.
thx
