### ISSUE TITLE
How to find the ground truth of the point cloud?

### ISSUE THREAD

**Issue by daohu527** [lgsvl/simulator#649]
1. You can obtain the ground truth through the "GroundTruth3DSensor", but its frequency may not be the same as the "LidarSensor", so you cannot accurately obtain the ground truth of the current point cloud.
2. You can use lidar save api to get the pcd file of the point cloud. But cannot get the groud truth of the 3d objects. 

How to solve this ? I think maybe should add the ground truth to the lidar save api?

**Comment by EricBoiseLGSVL** [comment]
@daohu527 We are looking at ways to solve this, hopefully have a solution soon.

**Comment by daohu527** [comment]
Thanks, look forward to this feature coming online!

**Comment by cyberphysicalrobotics** [comment]
Two sensors frequency is set same. But ground truth 3D sensor is less frequency than 10 Hz. Lidar and ground truth 3D data is not synchronized each other. I'll share this with my team.

**Comment by ntutangyun** [comment]
hi, any update on this feature ? thanks

**Comment by EricBoiseLGSVL** [comment]
Sorry, with simulator being sunset, we will not be working on this feature request.

**Comment by daohu527** [comment]
what does "simulator is sunset" mean ? Does it mean that it will not be developed in the future?

**Comment by EricBoiseLGSVL** [comment]
yes, LG is no longer supporting simulator.  Please see [here](https://www.svlsimulator.com/news/2022-01-20-svl-simulator-sunset).

**Comment by daohu527** [comment]
This is sad news, open source brings benefits but leaves many questions, thanks for your contribution : )

I'm one of the first few people to follow this project, and it's a pity that this project is no longer maintained. This has also strengthened my determination to do something that requires **feelings**

**Comment by EricBoiseLGSVL** [comment]
Thanks for working with us for so long.  Yes, it is sad but projects move on and new opportunities arise.  Good luck to you and thanks for all the help here in the issues page :)
