### ISSUE TITLE
Will lgsvl / simulator whether support apollo 3.5 ?

### ISSUE THREAD

**Issue by johnny77lee** [lgsvl/simulator#65]
Hi ,

For the simulator test with Apollo , we use the lgsvl/apollo codebase .
But it seems forked from ApolloAuto/apollo before apollo 3.5 release .

So....If we want to use the lgsvl/simulator with apollo 3.5 , 
1. Is it supported to run with lgsvl/simulator together?
2. If the answer of 1. is "OK"，Could you provide the rule about " How to make apollo3.5 run with lgsvl/simulator together?" ?

Thanks

**Comment by martins-mozeiko** [comment]
Hello!

Our simulator currently does not support Apollo 3.5. It works only with Apollo 3.0.
We are looking into supporting 3.5, but there are no specific plans for that yet.
