### ISSUE TITLE
HDRP Issues

### ISSUE THREAD

**Issue by skycrawlers123** [lgsvl/simulator#650]
After I download the Windows source zip and open the project in Unity, I'm hit with 999+ errors. Most are related to the HDRP shaders, HDRP files not being able to be read, and namespaces not being found.

**Comment by EricBoiseLGSVL** [comment]
@skycrawlers123 We use gitlfs.  You need to clone with lfs enabled. See documentation [here](https://www.lgsvlsimulator.com/docs/build-instructions/).
