### ISSUE TITLE
I can't control the car in Lgsvl with Logitech G920 

### ISSUE THREAD

**Issue by ozguradas** [lgsvl/simulator#652]
Hello all,
I am currently using the lgsvl 2020.01 version. Before we add our map and car, we tried to control standard map (Single road or san fran.) and standard car (Jaguar with no bridge and bridge autoware). Anyway i'm new on this. Is there anything that i have to do before plug in the g920.

I can control the car with keyboard in Lgsvl.
I downloaded and installed Logitech G Hub and Logitech Gaming Software.

So what can i do now ?

Thanks for answers.

**Comment by EricBoiseLGSVL** [comment]
@ozguradas we have issues with Unity recognizing the Logitech drivers sometimes,  I usually just unplug and re-plug the usb ports.  You can check that Unity is reading the drivers correctly with the Input system debug panel.  Window -> Analysis -> Input Debugger
Also, be sure to add a [WheelControlSensor](https://www.lgsvlsimulator.com/docs/sensor-json-options/#wheel-control).

**Comment by ozguradas** [comment]
Well, thanks for the answer. I didn't know the input debugger section. Now i can control the car via g920.
