### ISSUE TITLE
Publishing to LGSVL from rosbridge

### ISSUE THREAD

**Issue by tgif73** [lgsvl/simulator#654]
Hello,

I'm trying to use LGSVL to send/receive data to/from our own AD stack, which will be ros based.
Currently, I'm evaluating/testing with 2020.01 version (binary) on windows 10 and running rosbridge (ros melodic) on windows WSL (linux). I'm trying to subscribe/publish simple data to/from LGSVL from terminal.
That being said, I can subscribe to sensor data coming from LGSVL ($rostopic echo /<topic name>). However, when I publish /vehicle_cmd from terminal (**$rostopic pub -r 10 /vehicle_cmd autoware_msgs/VehicleCmd "{header: auto, steer_cmd: {steer: 1}, accel_cmd: {accel: 0}, brake_cmd: {brake: 1}, lamp_cmd: {l: 10, r: 5}, gear: 3, mode: 1, twist_cmd: {twist: {linear: {x: 1.0, y: 2.0, z: 0.2}, angular: {x: 0.2, y: 0.3, z: 0.1}}}, ctrl_cmd: {linear_velocity: 1, linear_acceleration: 1, steering_angle: 0.1}}"**), I don't see LGSVL subscribing to my topic. I can see my messages with $rostopic echo /vehicle_cmd from the terminal. I'm not sure what I'm doing wrong. Any advise is appreciated.

![image](https://user-images.githubusercontent.com/20801061/75478670-397ef280-5953-11ea-9e4c-9e1425f3432c.png)

![image](https://user-images.githubusercontent.com/20801061/75478729-4c91c280-5953-11ea-9b6e-b2e97c3fc2fc.png)

**Comment by tgif73** [comment]
Problem solved. I needed to $source devel/setup.bash before starting the roslaunch.

**Comment by Deepak3994** [comment]
@tgif73  How to setup those subscriber endpoints in lgsvl?
