### ISSUE TITLE
Setting default follow camera location

### ISSUE THREAD

**Issue by ozguradas** [lgsvl/simulator#655]
Hey again,

I want to change default follow camera location. Is it possible ? I am currently using a truck on LGSVL . So, when i locked the follow camera, i can only see back window of the truck which is not cool for driver. 

Let me know if there is a script about that topic. 
simualtor ver: 2020.01

**Comment by EricBoiseLGSVL** [comment]
@ozguradas CameraManager and SimulatorCamera.cs is what you need to edit.  You can also use the WASD keys to move the camera. This works if free and follow mode
