### ISSUE TITLE
GPS data error

### ISSUE THREAD

**Issue by chronofei** [lgsvl/simulator#657]
The GPS data in simulator is different from the one in the nmea_sentence msgs? I don't know where is wrong.

**Comment by EricBoiseLGSVL** [comment]
@hadiTab Do you know what could be the issue?

**Comment by EricBoiseLGSVL** [comment]
@chronofei we have fixes for the nmea in the latest release.  Are you still having this issue

**Comment by JM998** [comment]
I have the same problem with the latest version, how to deal with it? 
the version is 2020.06 for windows, is this problem fixed in the latest version of windows?

**Comment by JM998** [comment]
@EricBoiseLGSVL  I have the same problem with the latest version, how to deal with it?
the version is 2020.06 for windows, is this problem fixed in the latest version of windows?

**Comment by EricBoiseLGSVL** [comment]
Please look at this issue, we are currently investigating.  #1077

**Comment by JM998** [comment]
I don't know
