### ISSUE TITLE
Error message while running lgsvl : ''Invalid: Out of date Vehicle AssetBundle''

### ISSUE THREAD

**Issue by Avps1** [lgsvl/simulator#659]
Hi, 
I got this message : `Invalid: Out of date Vehicle AssetBundle. Please check content website for updated bundle or rebuild the bundle.` while trying to run the lgsvl simulation (See attached screenshot). So I reinstalled lgsvl (linux 2020.01 version) from the latest repo [(https://github.com/lgsvl/simulator/releases/latest)] and ran it again, but with no luck. The same error message appears. I thought my lgsvl was outdated, but as I said, the error persisted despite reinstalling lgsvl . 

System specs : Ubuntu 18.04 
Nvidia-Driver Version: 440.59       CUDA Version: 10.2 
GTX 1080 GRaphics Card. 
Please help. LGSVL was running perfectly in my machine even 2 days ago. 
![lgsvl_invalid_error](https://user-images.githubusercontent.com/50120641/75614230-009f7300-5b37-11ea-9865-86e059ceba26.png)

**Comment by ntutangyun** [comment]
please download the latest vehicle assetBundle from [here](https://content.lgsvlsimulator.com/vehicles/)

**Comment by Avps1** [comment]
Many thanks for your response.
