### ISSUE TITLE
Define Apollo route programmatically

### ISSUE THREAD

**Issue by vatna** [lgsvl/simulator#662]
I am using Apollo 5.0 with the Python API and would like to be able to define the route in Apollo programmatically instead of having to do this manually. This was requested before in issue #449 and I was wondering if there was any further news on this? Also, #449 mentioned that LG do this with some Python code over websocket. Would you be able to publish the code to do this?

**Comment by EricBoiseLGSVL** [comment]
@vatna We are looking into solutions for this level of control but we do not have it in our current roadmap.

**Comment by vatna** [comment]
Thanks for the update @EricBoiseLGSVL. Would you be able to publish the code mentioned in #449, or give some tips as to how to do it?

**Comment by EricBoiseLGSVL** [comment]
@vatna here is our code that we use to set EGO from python api
[dreamview-cyber-master.zip](https://github.com/lgsvl/simulator/files/4330725/dreamview-cyber-master.zip)

**Comment by vatna** [comment]
Thanks @EricBoiseLGSVL ! That also contains some other code that will be extremely useful for what we're doing.

**Comment by fabriquant** [comment]
Hello @EricBoiseLGSVL ,

I am looking at doing the same thing but with Autoware.AI.
Would you have some pointers on how to get started ?
For example, should I publish some ROS messages to do it and would I be constrained by the Autoware GUI (so much is done in the dialog box)?

Many thanks

**Comment by EricBoiseLGSVL** [comment]
@fabriquant You will need to publish a ROS message.  We have not done this yet sorry
