### ISSUE TITLE
How to restore default setting

### ISSUE THREAD

**Issue by atinfinity** [lgsvl/simulator#664]
I tried to use LGSVL Simulator 2020.01 on Ubuntu 18.04.
But, I accidentally deleted the setting of Map and Vehicle using Web UI.
Is there a way to restore default setting?

**Comment by EricBoiseLGSVL** [comment]
@atinfinity Navigate to the project persistent data path and just delete the data.db and backup.db.  Download the latest exe and run it.  It will re-download all settings and maps/vehicles.

This is my windows path
![DataPath](https://user-images.githubusercontent.com/45106230/75707966-b9b79780-5c74-11ea-886b-548c44048f11.PNG)

**Comment by atinfinity** [comment]
@EricBoiseLGSVL Thank you for your reply. It's usefull information!

> I tried to use LGSVL Simulator 2020.01 on Ubuntu 18.04.

I found setting file in `${HOME}/.config/unity3d/LG Silicon Valley Lab`.
So, I removed this directory. As a result, I could restore default setting.
