### ISSUE TITLE
LGSVL LIDAR signal modification

### ISSUE THREAD

**Issue by TNAV1** [lgsvl/simulator#665]
I would like to modify the LIDAR signal before LGSVL sends it out as /points_raw.  I am new to LGSVL and having trouble finding the proper file to modify.  
Any help is appreciated.

**Comment by EricBoiseLGSVL** [comment]
@TNAV1 Look into the LidarSensor.cs file in Assets -> Scripts -> Sensors folder.  I recommend creating a new sensor so you don't have conflicts when you pull changes
