### ISSUE TITLE
Custom or Unity assets work in a Unity project but not in the simulator project

### ISSUE THREAD

**Issue by asgardus** [lgsvl/simulator#666]
I am trying to create custom scenarios with externally created assets and also assets from the Unity store. The custom assets like vehicle body, traffic signs, trees etc are mostly in the .fbx format while some tree assets I imported from Unity Store are .spm format.

The external or store assets imported and work fine in a normal Unity project, but when imported into the simulator project they become pink. The shaders are assigned and the materials and textures are present, they are just pink in the simulator project but work well in a normal project.

I have tried extracting and regenerating textures and materials but without success. I am attaching pictures to help explain the situation better.

<img width="258" alt="Simulator_1" src="https://user-images.githubusercontent.com/20223787/75766423-6a8b6880-5d41-11ea-9544-4ecc54966fa2.PNG">
<img width="258" alt="Unity_1" src="https://user-images.githubusercontent.com/20223787/75767607-62342d00-5d43-11ea-9fa8-bbd87bb6c618.PNG">
<img width="1311" alt="Simulator" src="https://user-images.githubusercontent.com/20223787/75766430-6c552c00-5d41-11ea-88e0-49d7a159f1fd.PNG">
<img width="1311" alt="Unity" src="https://user-images.githubusercontent.com/20223787/75767457-2731f980-5d43-11ea-92ab-cd8e51110204.PNG">

Any tips or help on this would be great, Thanks!

**Comment by MikeLGSVL** [comment]
@asgardus The SPM file, is a Speedtree file. Change the shader type to HDRP/Lit and on the BroadLeaf tree object, change the Fade Mode to Cross Fade or None. Whichever better suites your project.

**Comment by EricBoiseLGSVL** [comment]
@asgardus Simulator is an HDRP project.  You will need to convert any assets to HDRP materials.
Edit -> Render Pipeline -> Upgrade project materials to High Definition materials.
Most purchased assets with work fine once updated except custom shaders.  Those will need to be rewritten or use an equivalent HDRP shader and settings.

**Comment by asgardus** [comment]
Thanks for the help!
