### ISSUE TITLE
cannot open web browser localhost:8080 after launching LGSVL simulator

### ISSUE THREAD

**Issue by ck-leo** [lgsvl/simulator#669]
I have encountered the problem that I cannot open browser when I click the button "open browser ..." in the LGSVL simulator window.
![image](https://user-images.githubusercontent.com/48859422/75936676-c8dd5600-5ebd-11ea-868b-323df32cddf2.png)
![image](https://user-images.githubusercontent.com/48859422/75936688-d561ae80-5ebd-11ea-94f1-802425ab67ae.png)
And in the website https://account.lgsvlsimulator.com, I have signed up my account. But I cannot help.
![image](https://user-images.githubusercontent.com/48859422/75936759-0a6e0100-5ebe-11ea-85be-0965b902b262.png)
My error log is :
[Player.log](https://github.com/lgsvl/simulator/files/4290376/Player.log)

My platform is as following:
Windows10
i7 9750H @2.60GHz
16G DDR4
GTX 2060 6G
lgsvlsimulator-windows64-2020.01
@EricBoiseLGSVL 
What do mean when you say "please post what you are on Linux/Windows/ReleaseBuild/Editor/CreatedBuild"? I'm sorry I can't follow.
I havenot installed the related components of unity, it that the problem? Or is there some other suggestings?
Thanks.

**Comment by ntutangyun** [comment]
@ck-leo Ali-ren ?  you need to build the frontend before opening it in browser.

try:
```bash
#make sure you have node and npm installed
cd simulator_project_root/WebUI/
npm install
npm run pack
```

**Comment by ck-leo** [comment]
@ntutangyun because I use ali source, then I registered an ali-email.
I have installed node and npm, and then run the command: 
cd simulator_project_root/WebUI/
npm install
npm run pack
But I still could not open the browser .

**Comment by EricBoiseLGSVL** [comment]
@ck-leo this is an issue with mono.  See [here](https://github.com/mono/mono/issues/7117)

**Comment by ck-leo** [comment]
@EricBoiseLGSVL Yeah, that works , thank you so much.
And @ntutangyun thank you all the same.

**Comment by EricBoiseLGSVL** [comment]
@ck-leo You are welcome.

**Comment by hiber-wang** [comment]
@ck-leo 
Hello, I have encountered the same problem, how did you solve it?
