### ISSUE TITLE
[SOLVED] How can I create my own map?

### ISSUE THREAD

**Issue by ctgloglu** [lgsvl/simulator#671]
How do I create my own map in unity

**Comment by ntutangyun** [comment]
how about starting with loading one of the existing maps and messing things around ?

**Comment by ctgloglu** [comment]
First of all thank you for your answer.As far as I can see on the internet, maps are loaded from the simulator menu.I don't have that menu either.How do I install the simulator menu unity.

**Comment by ntutangyun** [comment]
@ctgloglu welcome. 
the maps are usually loaded from AssetBundles, which are available at [lgsvl Content website](https://content.lgsvlsimulator.com/maps/).  You could download existing maps and vehicles there.

Once you've downloaded the maps, you could 
1. start simulator in Unity Engine, 
2. add new map entries in simulator webUI, with the address to the downloaded map assetbundle files.
3. run the simulator with one of the maps. 
4. in Unity Editor, once the map is loaded, everything that the map contains will be available in the `Hierarchy` tab.

**Comment by ctgloglu** [comment]
<a href="https://ibb.co/McbqfsT"><img src="https://i.ibb.co/2vwXSy2/resim.jpg" alt="resim" border="0" /></a>

There is no simulator menu. How can I install

**Comment by ctgloglu** [comment]
https://github.com/lgsvl/simulator
I get an error when integrating the files in unity
<a href="https://ibb.co/6yw60wF"><img src="https://i.ibb.co/kGBY2BX/error.jpg" alt="error" border="0"></a>

**Comment by luqiang21** [comment]
@ctgloglu Did you install git lfs?

**Comment by ctgloglu** [comment]
I tried to install according to the instructions written here: https://www.lgsvlsimulator.com/docs/build-instructions/

* git lfs install  output: 
Git LFS initialized.

*Window ex. C:\Users\XXX\Documents\Simulator\WebUI 

* npm install output:

audited 885770 packages in 12.523s
found 15999 vulnerabilities (3 moderate, 15995 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by ctgloglu** [comment]
I solved problem. https://www.lgsvlsimulator.com/docs/build-instructions/ I was trying to do my step manually in the 5th instruction here.Fixed the problem when doing it with cmd screen.Thank you to friends who are interested in my problem.
