### ISSUE TITLE
error response from daemon when bash ./docker/scripts/dev_into.sh

### ISSUE THREAD

**Issue by ck-leo** [lgsvl/simulator#672]
I followed the instruction in the website https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/, and got an error when  running bash ./docker/scripts/dev_into.sh. Details are as following :
![image](https://user-images.githubusercontent.com/48859422/75990788-5a85ab80-5f30-11ea-8aad-03251ecf8cc5.png)
And my platform is :
Ubuntu 16.04
i3 8100 @3.60GHzX4
16G DDR4
Intel® HD Graphics (Coffeelake 3x8 GT2) (Yes , I donot have a Nvidia graphics)
I want to know if I there are some methods to run apollo 5.0-lgsvl without Nvidia graphics? Thanks.

**Comment by EricBoiseLGSVL** [comment]
@ck-leo I don't think non Nvidia is supported. @hadiTab ?

**Comment by lemketron** [comment]
Apollo may or may not require an Nvidia GPU (e.g. if you don't need perception, for example) but our setup instructions assume nvidia-docker. Could you try installing nvidia-docker to see if that gets you past this particular error? If so, you'll then need to avoid enabling Apollo perception (which does require GPU).

**Comment by lemketron** [comment]
We have confirmed that with Apollo 5.0, docker has to have nvidia-docker. So it is not possible to run with Intel/AMD GPU. A CPU-only version Apollo is not under maintenance any more.

**Comment by ck-leo** [comment]
@lemketron Thank you very much, then I should get an Nvidia GPU.

**Comment by ck-leo** [comment]
@lemketron @EricBoiseLGSVL  Thanks very much, then I should get an Nvidia GPU.
