### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ctgloglu** [lgsvl/simulator#674]
I get an error when I install npm.

![2](https://user-images.githubusercontent.com/54224494/76086077-66bb4880-5fc4-11ea-9953-fe88fd6414f3.jpg)

**Comment by EricBoiseLGSVL** [comment]
@ctgloglu What platform are you on?

**Comment by ctgloglu** [comment]
Windows 10

**Comment by EricBoiseLGSVL** [comment]
What version of Node.js do you have?
Can you run the executable release build?

**Comment by ctgloglu** [comment]
node.js version v12.16.1

**Comment by EricBoiseLGSVL** [comment]
I think those are just warnings.  Can you run> npm run pack
What output do you get?

**Comment by ctgloglu** [comment]
> simulator-web-app@1.0.0 pack C:\Users\Can\Desktop\deneme-github\simulator\WebUI
> enact pack

Creating a development build...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
        5.21 MB         dist\main.js
        35.92 KB        dist\main.css

Compiled with warnings:

./src/components/SimulationManager/FormTraffic.js
  Line 18:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 27:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 28:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 29:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps

./src/components/SimulationManager/FormGeneral.js
  Line 23:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 24:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 25:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 26:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 30:  Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps

./src/components/SimulationManager/FormMapVehicles.js
  Line 26:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 27:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 28:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 46:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 126:  'vehicleList' is already declared in the upper scope                                                                      no-shadow

./src/components/SimulationManager/FormWeather.js
  Line 27:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 32:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 41:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 50:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps
  Line 59:  React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?  react-hooks/exhaustive-deps

./src/components/MapManager/MapManager.js
  Line 33:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 34:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 61:   Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps
  Line 81:    React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array                                                                                                                                                                                react-hooks/exhaustive-deps
  Line 222:  Expected '===' and instead saw '=='                                                                                                                                                                                                                                                         eqeqeq

./src/components/VehicleManager/VehicleManager.js
  Line 47:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 48:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 49:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 50:   React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies?                                                                                                                                                                    react-hooks/exhaustive-deps
  Line 75:   Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps
  Line 95:    React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array                                                                                                                                                                                react-hooks/exhaustive-deps
  Line 282:  Expected '===' and instead saw '=='                                                                                                                                                                                                                                                         eqeqeq

./src/components/SimulationsTable/SimulationsTable.js
  Line 62:  Expected '===' and instead saw '=='  eqeqeq

./src/components/SimulationManager/SimulationManager.js
  Line 63:  Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps

NOTICE: This build contains debugging functionality and may run slower than in production mode.

**Comment by Julyers** [comment]
Same, how did you solve it?

**Comment by EricBoiseLGSVL** [comment]
Did you run npm update?

**Comment by Julyers** [comment]
> Did you run npm update?

Yes, I run. But when I build WebUI in unity, it still show erros as follow.
**Failed to build WebUI. Please make sure npm is installed. Check README.md file
UnityEngine.Debug:LogError(Object)
Simulator.Editor.BuildWebUI:Build() (at Assets/Scripts/Editor/BuildWebUI.cs:40)**

**Comment by Julyers** [comment]
Who can help me? 
![微信图片_20200324125040](https://user-images.githubusercontent.com/59331333/77389522-6d242f80-6dce-11ea-9991-905d0316737e.png)

**Comment by ntutangyun** [comment]
@Julyers  Please refere to [a possible solution here](https://github.com/lgsvl/simulator/issues/388#issuecomment-536516345)

**Comment by Julyers** [comment]
> > simulator-web-app@1.0.0 pack C:\Users\Can\Desktop\deneme-github\simulator\WebUI
> > enact pack
> 
> Creating a development build...
> Browserslist: caniuse-lite is outdated. Please run next command `npm update`
> 5.21 MB dist\main.js
> 35.92 KB dist\main.css
> 
> Compiled with warnings:
> 
> ./src/components/SimulationManager/FormTraffic.js
> Line 18: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 27: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 28: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 29: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> 
> ./src/components/SimulationManager/FormGeneral.js
> Line 23: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 24: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 25: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 26: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 30: Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect react-hooks/exhaustive-deps
> 
> ./src/components/SimulationManager/FormMapVehicles.js
> Line 26: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 27: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 28: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 46: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 126: 'vehicleList' is already declared in the upper scope no-shadow
> 
> ./src/components/SimulationManager/FormWeather.js
> Line 27: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 32: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 41: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 50: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 59: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> 
> ./src/components/MapManager/MapManager.js
> Line 33: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 34: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 61: Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect react-hooks/exhaustive-deps
> Line 81: React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array react-hooks/exhaustive-deps
> Line 222: Expected '===' and instead saw '==' eqeqeq
> 
> ./src/components/VehicleManager/VehicleManager.js
> Line 47: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 48: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 49: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 50: React Hook useCallback does nothing when called with only one argument. Did you forget to pass an array of dependencies? react-hooks/exhaustive-deps
> Line 75: Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect react-hooks/exhaustive-deps
> Line 95: React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array react-hooks/exhaustive-deps
> Line 282: Expected '===' and instead saw '==' eqeqeq
> 
> ./src/components/SimulationsTable/SimulationsTable.js
> Line 62: Expected '===' and instead saw '==' eqeqeq
> 
> ./src/components/SimulationManager/SimulationManager.js
> Line 63: Assignments to the 'unmounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect react-hooks/exhaustive-deps
> 
> NOTICE: This build contains debugging functionality and may run slower than in production mode.
Hello, how did you solve this problem in the end? My mistake is exactly the same as yours. I've been stuck in this place for a long time. I hope you can tell me how you solved it, thank you!

**Comment by Julyers** [comment]
> @Julyers Please refere to [a possible solution here](https://github.com/lgsvl/simulator/issues/388#issuecomment-536516345)

I tried it but it didn't work. And same problem still exists. Thank you！

**Comment by martins-mozeiko** [comment]
Try running npm manually in command line inside WebUI folder: `npm run pack-p` This will show more detailed error message.
