### ISSUE TITLE
Map error

### ISSUE THREAD

**Issue by ctgloglu** [lgsvl/simulator#676]
I can't see objects, it gives an error

![error-3](https://user-images.githubusercontent.com/54224494/76144179-eb729900-608e-11ea-8382-4b8fe8ec4318.jpg)

- Shader error in 'Shader Graphs/EnvironmentSimulation': 'NewGradient': no matching 0 parameter function at line 4839 (on d3d11)

Compiling Fragment program with INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

- Shader error in 'Shader Graphs/EnvironmentSimulation': syntax error: unexpected integer constant at line 4839 (on d3d11)

Compiling Fragment program with INSTANCING_ON
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

- Shader error in 'Shader Graphs/EnvironmentSimulation': 'NewGradient': no matching 0 parameter function at line 7359 (on d3d11)

Compiling Vertex program with INSTANCING_ON DECALS_3RT LIGHT_LAYERS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

- Shader error in 'Shader Graphs/EnvironmentSimulation': syntax error: unexpected integer constant at line 7359 (on d3d11)

Compiling Vertex program with INSTANCING_ON DECALS_3RT LIGHT_LAYERS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by shalinmehtalgsvl** [comment]
Hi @ctgloglu ,

It looks like you are missing the materials or textures. In the Project Panel, in SingleLaneRoad>Models>SingleLaneRoad>Materials, there should be a SingleLaneRoadDiffuse.png. Can you see the image?

If not, did you have git lfs installed before you cloned the repo? You'll need to do `git lfs install` and then `git pull` to get the missing files.

**Comment by JockTokk** [comment]
Hello, I have the same problem with SanFrancisco
![Безымянный](https://user-images.githubusercontent.com/61880851/77166610-9b9bc500-6ac5-11ea-84bb-47eef2bba7aa.png)
