### ISSUE TITLE
can't run Rviz with autoware

### ISSUE THREAD

**Issue by Amina88** [lgsvl/simulator#679]
$rosrun rviz rviz
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-sneibus'
[ INFO] [1583843544.906934800]: rviz version 1.13.7
[ INFO] [1583843544.907294400]: compiled against Qt version 5.9.5
[ INFO] [1583843544.907930200]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1583843544.914675100]: Forcing OpenGl version 0.
Segmentation fault (core dumped)

**Comment by EricBoiseLGSVL** [comment]
@Amina88 duplicate
