### ISSUE TITLE
how to define a stereo camera for Autoware?

### ISSUE THREAD

**Issue by asimonov-hitachi** [lgsvl/simulator#68]
hi!
Great job with the simulator and integration with Autoware!

I can successfully build the simulator in Unity. I can change Lidar settings and see the changes in simulator.

What I am struggling with is how to define a stereo camera and then have it appear in autoware/ROS.
Can you point me in the right direction?
I do not have any experience with Unity, but can follow instructions :)

Also, is there a high level overview of how data gets from the simulator to ROS1 container? Is there ROS2 involved? This links to previous question as I basically wanna modify different parts to do what I need.

**Comment by martins-mozeiko** [comment]
Hello!

If you want an extra camera on Autoware vehicle you need to do following steps:

1) Open SanFrancisco scene
2) Drag in Autoware prefab into scene: 
![image](https://user-images.githubusercontent.com/39178216/51137159-13e86580-17f3-11e9-8890-24de342d9bcc.png)

3) Duplicate (copy & paste) CaptureCamera object inside XE_Rigged-autoware scene object:
![image](https://user-images.githubusercontent.com/39178216/51137247-44300400-17f3-11e9-98ca-4ad3754bf701.png)

4) Select new "Capture Camera (1)" object and adjust its position/orientation in 3d view:

![image](https://user-images.githubusercontent.com/39178216/51142712-8bbd8c80-1801-11e9-8843-e4676ceb27cf.png)

5) Change properties of new "CaptureCamera (1)" object - change `TopicName` to different topic, and `Sensor Name` for UI.

![image](https://user-images.githubusercontent.com/39178216/51137283-5611a700-17f3-11e9-9d90-bba79958c33a.png)

6) Open new Inspector tab (1), in one inspector select XE_Rigged-autoware game object (2) and press lock icon to lock it (2), then select new "CaptureCamera (1)" game object in second inspector (3). Now increase number for `NeedsBridge` property in XE_Rigged-autoware component and drag & drop (4) `Video To Ros` script from camera into `Needs Bridge` list.

![image](https://user-images.githubusercontent.com/39178216/51141704-de497980-17fe-11e9-95d6-8bf39265bcac.png)

7) Press "Apply" at top of inspector of XE_Rigged-autoware game object to save it.

Do not save the SanFrancisco scene, as you don't want autoware game object there. It will be added dynamically.

Now if you run simulator from Main Menu, the autoware vehicle should publish to camera topics.

Let me know if you have more questions on this.

**Comment by asimonov-hitachi** [comment]
thank you! i will try this later

**Comment by asimonov-hitachi** [comment]
That worked! Thanks a lot!

**Comment by asimonov-hitachi** [comment]
actually, if I keep using the config.yaml (even if I delete     enable_main_camera : true from XE_Rigged-autoware) the simulator does not start - i just see black screen forever.
Can it work with config.yaml?

**Comment by martins-mozeiko** [comment]
This probably means that there is some exception happening that prevents simulator for running. 

You can check what exception is happening inside log file in `/.config/unity3d/LG Silicon Valley Lab/Automotive Simulator/Player.log` location on Linux, or `%APPDATA%\..\LocalLow\LG Silicon Valley Lab\Automotive Simulator\output_log.txt` location on Windows.
