### ISSUE TITLE
Can I add a vehicle with a local path?

### ISSUE THREAD

**Issue by mamemo888** [lgsvl/simulator#681]
Hello,
I tried to add the vehicle AssetBundle modified by UnityEditer in WebUI.
However, despite entering the local path to the binary, the message "Failed to add vehicle: You must specify a non-empty name" is displayed.

![Screenshot from 2020-03-12 09-50-11](https://user-images.githubusercontent.com/62067993/76437702-4b55a080-63fd-11ea-9645-547c664472d7.png)

The documentation states:
"When adding a vehicle, the link to the appropriate assetbundle can be entered as the URL or the assetbundle can be downloaded manually and the local path can be entered."

I have just started using this simulator.
Am I misunderstanding something?
Thank you.

**Comment by EricBoiseLGSVL** [comment]
@mamemo888 yes you can add a vehicle from a local path but it looks like you didn't build bundle with our editor tool or you renamed.  Please see [this](https://www.lgsvlsimulator.com/docs/assets/)

**Comment by mamemo888** [comment]
@EricBoiseLGSVL 
Thank you for your reply.
However, I think the bundle was built. A zip file is created in the AssetBundle folder. The asset and folder names also match.

By the way, I have two new questions.
Is the location to extract the zip of the asset bundle specified?
Is the local path I need to enter in “Add new” the path to the unpacked binaries? Or something else?

**Comment by EricBoiseLGSVL** [comment]
@mamemo888 
1) Asset bundle file name should be vehicle_NewVehicle if successful.
2) The folder that contains the assets that you build in editor should be Assets/External/Vehicles/NewVehicle
3) The name of the vehicle prefab should be NewVehicle.

Does your project match this naming convention before you build?
This is required because Unity needs filenames when dealing with asset bundle loading.

**Comment by mamemo888** [comment]
@EricBoiseLGSVL 
The build may not have been completed correctly, so I tried again and confirmed your point.
Look at the image below for point 1.
![Screenshot from 2020-03-13 22-33-48](https://user-images.githubusercontent.com/62067993/76590710-632e4100-6531-11ea-8e97-0b20ca67cab3.png)
The file name of AseetBundle is “vehicle_new_vehicle”.

See the image below for the contents of this zip file. Are these correct?
![Screenshot from 2020-03-13 22-24-06](https://user-images.githubusercontent.com/62067993/76590742-81943c80-6531-11ea-83e3-cb8ec56414a8.png)


For points 2 and 3, see this image.
![Screenshot from 2020-03-13 22-24-29](https://user-images.githubusercontent.com/62067993/76590719-6d503f80-6531-11ea-8b00-0ad87474413f.png)
The asset folder is “Assets / External / Vehicles / new_vehicle”.
The name of the prefab is “new_vehicle.prefab”.

There were no errors when building with UnityEditer. Are these not built correctly?

**Comment by EricBoiseLGSVL** [comment]
@mamemo888 That looks exactly right.  Now when you link the bundle in the webUI, does it give you an error?

**Comment by mamemo888** [comment]
@EricBoiseLGSVL 
I entered the file name of the bundle, but unfortunately the error did not go away.
![Screenshot from 2020-03-16 21-03-37](https://user-images.githubusercontent.com/62067993/76720317-d62cf700-677f-11ea-8ea7-6ab5fb4d38c0.png)

**Comment by mamemo888** [comment]
@EricBoiseLGSVL 
By the way, I also tried the asset bundle downloaded from the official website.
https://content.lgsvlsimulator.com/vehicles/lincolnmkz2017/

However, this also showed the same error.
![Screenshot from 2020-03-17 01-33-34](https://user-images.githubusercontent.com/62067993/76733292-dc34cf00-67a3-11ea-9e17-98e76c625a05.png)

I feel like I'm making a fundamental mistake.

**Comment by mamemo888** [comment]
@EricBoiseLGSVL 
After all I did not know the underlying mechanism.
I learned from another person that I had to build an http server. I did this and solved the problem.

I am very grateful for your response so far.

**Comment by martins-mozeiko** [comment]
The problem is that you are unzipping and providing `XXX_vehilce_main_linux` file to simulator. You should provide path to whole "zip archive" file.
