### ISSUE TITLE
Integrating UnityCloud and AWS 

### ISSUE THREAD

**Issue by RanjaniN-10** [lgsvl/simulator#682]
Hi LG team,
I am  working with LGSVL Simulator.
I would like to modify this simulation, but it requires high-end hardware. So I prefer to use UnityCloud along with AWS.

Is it possible to integrate UnityCloud and  AWS for LGSVL Simulator training? If so can you help me with that.

Thanks
Ranjani

**Comment by EricBoiseLGSVL** [comment]
@RanjaniN-10 This is not supported at this time.  We are currently developing these features.

**Comment by guruvishnuvardan** [comment]
Hi, 
Can I train LGSVL Simulator using Unity and Standalone windows GPU system?

**Comment by EricBoiseLGSVL** [comment]
@guruvishnuvardan @daviduhm do we have documentation for training with simulator?

**Comment by guruvishnuvardan** [comment]
@EricBoiseLGSVL - No. I don't have. I am new to LGSVL Simulator. Can you please share me the links to get the documentation for training with LGSVL Simulator

**Comment by lemketron** [comment]
> @EricBoiseLGSVL - I am new to LGSVL Simulator. Can you please share me the links to get the documentation for training with LGSVL Simulator

If you're looking for general documentation on setting up and using LGSVL Simulator, you can find it here:
https://www.lgsvlsimulator.com/docs/
https://www.lgsvlsimulator.com/docs/getting-started/

**Comment by guruvishnuvardan** [comment]
@lemketron - Thanks a ton :)

One other question - Can I use Microsoft Azure Virtual Machine and Install LGSVL Simulator for Training?

Since, We were trying to Use Unity Cloud Beta - AWS - LGSVL for training our own simulation, but I heard, We can't use AWS to train LGSVL Simulator.

Can you please suggest us a cloud platform(Virtual Machine with GPU) to install Unity -LGSVL and start training.

Thanks
Guru

**Comment by EricBoiseLGSVL** [comment]
@guruvishnuvardan Cloud is not supported at this time.  We are working on this feature.

**Comment by martins-mozeiko** [comment]
If you can access Remote Desktop on machine with GPU the simulator will run just fine. Exactly same as on local machine. See following issue where running in Azure was discussed: #236
