### ISSUE TITLE
Invalid: Value cannot be null. Parameter name: entry

### ISSUE THREAD

**Issue by weiyinxie** [lgsvl/simulator#686]
hey as i add my own vehicle to the simulation and try get the simulation to run. i get this issue.
![捕获](https://user-images.githubusercontent.com/44968424/76758082-ea92e300-67c3-11ea-8f6f-159c5fb1fdc2.PNG)
i don't quiet understand where this issue come from... could it happen because of the following definition in my script "agent manager"? because the defintion of parameter can only be found in this script among all the script belongs to my own customized vehicle....
![捕获1](https://user-images.githubusercontent.com/44968424/76758364-8290cc80-67c4-11ea-8ebc-9863b8952564.PNG)

**Comment by EricBoiseLGSVL** [comment]
@weiyinxie It might be an issue with asset bundle creation.  Can you show your folder structure in Assets/External/Vehicles/NewVehicle so I can see how you placed files and named them?
