### ISSUE TITLE
Can i get path information to drive?

### ISSUE THREAD

**Issue by smileybin** [lgsvl/simulator#69]
I study about the simulator and have a question.
I want to get the path what I drive in simulation. Also can I make a simulation? For example, can I make a car that follows my car or make a collision what i want.
Thank you =)

**Comment by EricBoiseLGSVL** [comment]
Hello @smileybin 

I'm not sure what you mean by "get the path" but you can alter the simulation if you want.  For a car that follows, you could write a script and attach it to an NPC prefab to create this behavior.  You could also make a script that overrides input and creates the collision that you want.  TrafAIMotor.cs even has a force collision flag called forceToCollideMode that changes behavior in Update() and could be modified to achieve what you are trying to accomplish.  We will continue to work to make the simulator easier to edit and create custom behavior.

-Eric

**Comment by EricBoiseLGSVL** [comment]
No problem and glad to help!
