### ISSUE TITLE
Looping through waypoints

### ISSUE THREAD

**Issue by vatna** [lgsvl/simulator#690]
I have given a NPC a list of waypoints, and all waypoints are set to the same speed. I am using `npc.follow(waypoints, loop=True)` to loop through them continuously. When it reaches the last waypoint, the vehicle goes back to the first waypoint at the same speed.

But what I'd like is that when it reaches the last waypoint, it teleports instantly back to the first waypoint and then goes through all the waypoints as normal until it reaches the last one, then teleports back, etc. Could you let me know how to do this?

**Comment by vatna** [comment]
I've also tried to teleport the NPC by setting the state property of the NPC but it goes to the position at the same speed as it was moving instead of being instantly teleported there.

**Comment by EricBoiseLGSVL** [comment]
@vatna This might require a few changes in Simulator and API.  I'll get back to you on this soon.
