### ISSUE TITLE
Sensors cannot be enabled once disabled from PythonAPI

### ISSUE THREAD

**Issue by mmatthe** [lgsvl/simulator#692]
When creating an egoAgent with 

```
spawns = self._simulator.get_spawn()
self._initialState = state = lgsvl.AgentState()
self._initialState.transform = spawns[0]
egoAgent = self._simulator.add_agent(vehicle_name, lgsvl.AgentType.EGO, self._initialState)
```

All calls to 

```
for s in egoAgent.get_sensors():
    s.enabled = True
```

are received by the Simulator (checked by putting a break point to [SensorEnabledSet.cs](https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Api/Commands/SensorEnabledSet.cs#L22) )

Calling 
```
for s in egoAgent.get_sensors():
    s.enabled = False
```

the mentioned breakpoint is reached, and sensors are disabled.

Any subsequent call to 
```
for s in egoAgent.get_sensors():
    s.enabled = True  # or False, it doesn't matter
```

is not triggering the breakpoint and hence not able to enable the sensors back. 

This is not a PythonAPI issue (the code there is very basic), but it seems a bug within the simulator itself.

**Comment by EricBoiseLGSVL** [comment]
@mmatthe Thanks for finding this bug.  We will look into this.

**Comment by EricBoiseLGSVL** [comment]
This is still not supported and probably will not in the foreseeable future.  This is an issue with the sensor framework and Unity and is too costly to remedy at this time
