### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by JockTokk** [lgsvl/simulator#693]
Hi, LG Team, I have a problem with shader in SanFrancisco map. I've used `git lfs install`. (Windows 10)

![image](https://user-images.githubusercontent.com/61880851/77226030-07456700-6b86-11ea-9dc8-22c4befd697d.png)

Shader error in 'Shader Graphs/EnvironmentSimulation': 'NewGradient': no matching 0 parameter function at line 1537 (on d3d11)

Compiling Vertex program with UNITY_PASS_META
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

Shader error in 'Shader Graphs/EnvironmentSimulation': syntax error: unexpected integer constant at line 1537 (on d3d11)

Compiling Vertex program with UNITY_PASS_META
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

Shader error in 'Shader Graphs/EnvironmentSimulation': 'NewGradient': no matching 0 parameter function at line 4839 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

Shader error in 'Shader Graphs/EnvironmentSimulation': syntax error: unexpected integer constant at line 4839 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

Shader error in 'Shader Graphs/EnvironmentSimulation': 'NewGradient': no matching 0 parameter function at line 7359 (on d3d11)

Compiling Fragment program with DECALS_3RT LIGHT_LAYERS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

Shader error in 'Shader Graphs/EnvironmentSimulation': syntax error: unexpected integer constant at line 7359 (on d3d11)

Compiling Fragment program with DECALS_3RT LIGHT_LAYERS
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_FULL_HDR

**Comment by EricBoiseLGSVL** [comment]
@JockTokk Unity shadergraph is still has some bugs.  Navigate to the shader and double click it.  This will open shadergraph editor.  In the top left, click Save Asset...  This will recompile the shader.  Let me know if this fixes the issue.

**Comment by JockTokk** [comment]
Thank you! I will try it and I will report the result.

**Comment by JockTokk** [comment]
@EricBoiseLGSVL, thank you! I will try it and I will report the result.

**Comment by JockTokk** [comment]
@EricBoiseLGSVL, unfortunatelly, there are new errors.

![image](https://user-images.githubusercontent.com/61880851/77409086-c342a400-6dc9-11ea-8f48-7435239d4150.png)

**Comment by EricBoiseLGSVL** [comment]
@JockTokk Ok, in project root, while Unity is closed, delete Library folder.  Then open Unity and it will rebuild this folder.  Let me know if this fixes the issues

**Comment by JockTokk** [comment]
@EricBoiseLGSVL, I've done this instruction, but it hasn't helped.

![image](https://user-images.githubusercontent.com/61880851/77508835-adda8200-6e7c-11ea-9132-d15e4d9a7915.png)

**Comment by EricBoiseLGSVL** [comment]
Can you please double click on shader graph EnvironmentSimulation, click on Save Asset... in the top left.  This will recompile the shader.  The other errors are fine.  You may need to run the HDRP wizard also but try recompiling

**Comment by JockTokk** [comment]
I'am on Windows.
Unfortunatelly, all is the same

![image](https://user-images.githubusercontent.com/61880851/77615871-6f5acb00-6f41-11ea-8d2f-22822edf41f4.png)

**Comment by EricBoiseLGSVL** [comment]
@JockTokk This seems like code in the shader is not supported by your GPU or driver issues.  What GPU are you using and what driver version are you on?

**Comment by martins-mozeiko** [comment]
This would be really strange if this would be GPU bug. My guess is on Unity messing up generated shader graph code.

@JockTokk Can you do following, please?

1) Double click EnvironmentSimulation shader (or click `Open Shader Editor` button from your last screenshot)
2) On the rightmost node called `Lit Master` click right mouse button and select `Show Generated Code`
3) Now scroll to line 1937 or 4839 or 7359 and copy & paste it here (maybe one extra line above and below too)

It could be this bug: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5424
If locale settings are messing up float conversion and instead 1.0 you get 1,0 - that's a syntax error. @JockTokk what system locale you have? Do you use , or . for decimal point? Can you try changing that in your system locale settings? When you change it, restart Unity to see if this gets fixed.

**Comment by JockTokk** [comment]
@EricBoiseLGSVL, NVIDIA GeForce GT 720M. Driver version: 391.35.

**Comment by EricBoiseLGSVL** [comment]
@martins-mozeiko thanks, yes this has been an issue before.
@JockTokk Is your GPU 2gb?  If so, you will have many issues running simulator.  We recommend at least 8gb.

**Comment by JockTokk** [comment]
@martins-mozeiko, you are right. It's related with system locale.
Line number 9759:
`Gradient _Gradient_AFE042FB_Out_0 = NewGradient(0, 5, 2, float4(0, 0, 0, 0,08529793),float4(0,8490566, 0,8490566, 0,8490566, 0,6470588),float4(1, 1, 1, 0,7617609),float4(0,1037736, 0,1027946, 0,1027946, 0,9264668),float4(0, 0, 0, 1),float4(0, 0, 0, 0),float4(0, 0, 0, 0),float4(0, 0, 0, 0), float2(1, 0),float2(1, 1),float2(0, 0),float2(0, 0),float2(0, 0),float2(0, 0),float2(0, 0),float2(0, 0));`

I changed the comma to the dot, but it hasn't helped. I've tried to remove folder Library in project root. It also hasn't helped.

@EricBoiseLGSVL, yes. It's just test.

**Comment by martins-mozeiko** [comment]
You changed it here? To dot?
![image](https://user-images.githubusercontent.com/39178216/77689278-a5f30e80-6f5e-11ea-862e-ecb79628134f.png)

And then closed Unity fully, including Unity Hub, and then reopened project again?

**Comment by JockTokk** [comment]
> You changed it here? To dot?'

@martins-mozeiko, yes. 


> And then closed Unity fully, including Unity Hub, and then reopened project again?

Yes.

**Comment by martins-mozeiko** [comment]
Maybe try logging out from your user and logging back on Windows. I don't remember how regional settings were applied in Windows.

**Comment by JockTokk** [comment]
@martins-mozeiko I've already tried that. I've also tried to reboot system.

**Comment by martins-mozeiko** [comment]
Alternative would be to open `GradientShaderProperty.cs` file and apply these changes manually: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5424/files#diff-c233a20539fb47175c19f9a89d09837c

This file is inside `Library/PackageCache/com.unity.shadergraph@5.16.1/Editor/Data/Graphs` folder. 

After that try reimporting the shader again.

**Comment by JockTokk** [comment]
@martins-mozeiko I've just reinstalled project. Errors have disappeared. But...

![image](https://user-images.githubusercontent.com/61880851/77697652-4e858a80-6fc0-11ea-8304-0b31a51c0bb6.png)

In play mode

![image](https://user-images.githubusercontent.com/61880851/77697886-b6d46c00-6fc0-11ea-8b9f-1b0813beb3e1.png)

**Comment by EricBoiseLGSVL** [comment]
@JockTokk Yes, in editor there is no light source.  In play mode we add the directional light.  To have lighting in scene view press the button top left of scene view panel.

![image](https://user-images.githubusercontent.com/45106230/77700048-b613e980-6f70-11ea-93b3-c2e3d3562e5c.png)

**Comment by JockTokk** [comment]
@EricBoiseLGSVL yes exactly.

**Comment by JockTokk** [comment]
@EricBoiseLGSVL @martins-mozeiko thank you very much for the help!

For anyone, who will face this problem.

1. You need to change the decimal point in the system from the comma to the point.

![image](https://user-images.githubusercontent.com/61880851/77726868-068b5580-700a-11ea-8431-3951ea0d398c.png)

2. Reboot your computer.

3. In project right click on EnvironmentSimulation shader and choose Reimport. It's in `Assets/Shaders/EnvironmentShaders`.

4. If it won't work, you need to again create new project.

5. If it won't work, you need to 

> Alternative would be to open `GradientShaderProperty.cs` file and apply these changes manually: https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/5424/files#diff-c233a20539fb47175c19f9a89d09837c
> 
> This file is inside `Library/PackageCache/com.unity.shadergraph@5.16.1/Editor/Data/Graphs` folder.
> Note that changes will disappear, if Library folder gets removed.
> 
> After that try reimporting the shader again.

6. At the end if you want to see city in scene, you need to toggled off this button

![image](https://user-images.githubusercontent.com/61880851/77727713-f83e3900-700b-11ea-9273-8a7de7525bba.png)
