### ISSUE TITLE
LGSVL's nmea_sentence doesn't change

### ISSUE THREAD

**Issue by eungh1** [lgsvl/simulator#696]
Hello guys, I'm a student working with LGSVL wit Autoware.
I want to use LGSVL's nmea_sentence topic for localization.
So I change Map origin's parameter using Unity. But, it doesn't change.

I attach pictures.

![Screenshot from 2020-03-24 12-20-10](https://user-images.githubusercontent.com/59676885/77388883-bd05f500-6dd4-11ea-9fd3-bfb80d1687c8.png)
![Screenshot from 2020-03-24 12-20-33](https://user-images.githubusercontent.com/59676885/77388892-c2633f80-6dd4-11ea-8b06-f1d6b0d304ed.png)
![Screenshot from 2020-03-24 12-42-40](https://user-images.githubusercontent.com/59676885/77388894-c55e3000-6dd4-11ea-9c43-07072ff20c0f.png)
These are information from the CubeTown map provided by LGSVL.

![Screenshot from 2020-03-24 12-17-26](https://user-images.githubusercontent.com/59676885/77388932-e757b280-6dd4-11ea-8b84-950ea3649109.png)
![Screenshot from 2020-03-24 12-17-59](https://user-images.githubusercontent.com/59676885/77388936-ea52a300-6dd4-11ea-9d1a-f0ef397db3d6.png)  
![Screenshot from 2020-03-24 12-40-56](https://user-images.githubusercontent.com/59676885/77388938-ec1c6680-6dd4-11ea-8d69-94ee1c006eb1.png)
And these are information from the CubeTown map, which has modified the Map origin parameter.

As you can see, Map origin was modified through Unity, but the information of nmea_sentence has not changed.
How can I change nmea_sentence?

Thanks.

**Comment by EricBoiseLGSVL** [comment]
@eungh1 We have recently updated this sensor but not released the changes.  Let me see if @rongguodong can help

**Comment by rongguodong** [comment]
@eungh1 Are you using Autowware.AI or Autoware.Auto? How do you display the nmea_sentence topic?
Can you open the GPS visualizer (by click the "eye" icon) to see if Longitude/Latitude there change when you change the map origin?

**Comment by rongguodong** [comment]
@eungh1 I think I know why. If you are using our default vehicle setup for Autoware, the GPS sensor has: "IgnoreMapOrigin": true. Just change that to false to have map origin NOT ignored. :)

**Comment by eungh1** [comment]
@EricBoiseLGSVL Thank you for kindness. :)

@rongguodong I'm using Autoware.AI and I display the nmea_sentence topic using just rostopic echo.
I changed the "IgonoreMapOrigin" to false as you told me and it solved the problem. Thank you so much!

**Comment by eungh1** [comment]
It is different from the issue, but can I get information on the condition of the vehicle(not cmd, for example, steering angle)? It is okay to think that the vehicle moves immediately according to the cmd value?

**Comment by EricBoiseLGSVL** [comment]
@eungh1 yes.  You can get data from CanBus sensor or create your own sensor that sends what data you need.  Look at canbus as an example on how to create.  Note, if you plan on making a new sensor that is built in simulator, be sure to add prefab to RuntimeSettings.asset sensor list

**Comment by eungh1** [comment]
@EricBoiseLGSVL I know your default vehicle for Autoware.ai does not support CanBus sensor. If you support CanBus sensors for Autoware.ai, how can I use that?
Or do you mean to create a sensor that publishes the desired data? I don't know what example about canbus you are talking about. Is it found in the LGSVL document?

**Comment by EricBoiseLGSVL** [comment]
@eungh1 any vehicle can support any sensor.  You just need to alter the JSON sensor configuration in the Simulator WebUI.  You can also build Simulator with a new sensor or build a sensor plugin to send the data you need.  This is in our documentation on our website and in the repo.
