### ISSUE TITLE
How to modify the speed of NPC vehicles during simulator running 

### ISSUE THREAD

**Issue by zhwmonkey** [lgsvl/simulator#700]
Hi, I want to create a scene which the speed of NPC can change suddenly. Is there any way to do it?
Thanks

**Comment by EricBoiseLGSVL** [comment]
@zhwmonkey How do you plan on sending the command to change speed?

**Comment by zhwmonkey** [comment]
I'm so sorry for replying so late. I'm going to write a python script to create a scenario that contains the initial and triggered behavior of the ego vehicle and NPC.For example, when the distance between the ego vehicle and the NPC is less than 100m, the NPC slows down to the specified speed.
Thanks a lot.

**Comment by EricBoiseLGSVL** [comment]
@zhwmonkey No worries.  I think this will be easier by creating custom behaviors for NPC's.  We are currently refactoring and making extensional the NPC behavior class, NPCController.cs.  This should release in April.

In the meantime, I suggest creating a custom sensor with a callback for all NPC's that are within range.  Then the python api cycles through this list and sets the NPC speed.  NPCManager.cs has all active npc's in a list to iterate through in the new sensor.
