### ISSUE TITLE
Rebase Apollo fork?

### ISSUE THREAD

**Issue by Autofoxsys** [lgsvl/simulator#701]
I've found the LG simulator to be a great way to test Apollo 5.0
Unfortunately, LG's fork of Apollo is now quite outdated and posing compatibility problems.  While the linux kernel is up to date, the same can't be said for the version of Ubuntu used, nor the Apollo code-base, where bug fixes aren't carried over.
I tried to use some profiling tools to profile Apollo (LG container and codebase) but experienced crashes (Thread Local Storage exceeded), while the same tools work fine with the official Apollo code.

Have you and tips to port over your changes to the current Apollo codebase? 
Thanks.

**Comment by EricBoiseLGSVL** [comment]
@Autofoxsys This is on our roadmap and plan to release support for latest Apollo as soon as possible.
