### ISSUE TITLE
Using meshes and urdf files for Simulation of an environment and truck

### ISSUE THREAD

**Issue by Adel-kn** [lgsvl/simulator#702]
Hello everybody,
I am completely new with LGSVL simulator and have some questions:
1- I have meshes for a real environment (file.3d), can  I use them to generate a simulated environment?
2- Also I have the URDF file and meshes for my truck, can I use them to generate simulated truck? 
3- The truck is equipped with particulars radars, how can one model these particular sensors in LG simulator?
Note: I have the log data from the radars and IMU sensor stored from the measurements in the real environment.
Thanks in advance.

**Comment by EricBoiseLGSVL** [comment]
@Adel-kn Hello and welcome to LGSVL Simulator.
1 - Yes, Unity supports file.3d but I recommend using file.fbx if you can export.
2 - URDF files are not supported.  I did find a converter for Unity [here](https://assetstore.unity.com/packages/tools/modeling/urdf-importer-99316), we have not used this asset before.
3 - You can create custom sensors in simulator or as plugin sensors as bundles.  These are then loaded at runtime.  You will need to write the logic if it is different than the radar sensor provided.  You can use the provided radar sensor as a template to help with development.
