### ISSUE TITLE
Can I use custom agent callbacks for my simulation?

### ISSUE THREAD

**Issue by RamoramaInteractive** [lgsvl/simulator#704]
After my simulation is finished, I want to execute another Python (after sim.run()).
I used Python threads, but they cause many errors. The documentary says you can use agent callbacks, but there is only a callback for the collision with a second agent. 

Is it possible to write for my own agent a custom agent callback function? For example: I want to start another function, after the simulation is finished. Otherwise, I also need a callback function which execution will be repeated every 5 seconds. Is this possible?

**Comment by EricBoiseLGSVL** [comment]
@RamoramaInteractive 

If you want a new callback, you will need to create a new sensor in simulator and add to Assets/Resources/RuntimeSettings.asset or create a sensor plugin.  This will be the what the api calls to get data.  Then, you will create a new Assets/Scripts/Api/Commands c# file.  This will tell the simulator what call back you need and prepare the data.  Finally, you will need to alter the PythonAPI/lgsvl/sensor.py file to include the new sensor.  Follow the CanBus sensor to see how it works.

I'm not sure what you are asking for with regards to start another function after simulation is finished.  Why not set a time to run in api? sim.run(time) and loop?
