### ISSUE TITLE
Kernel 'KSampleCopy4_1_x_8' not found while trying to build standalone executable

### ISSUE THREAD

**Issue by tleyden** [lgsvl/simulator#705]
I've tried to follow the [Instructions to build standalone executable](https://www.lgsvlsimulator.com/docs/build-instructions/), but running into errors in the Unity Editor:

![Screen Shot 2020-03-29 at 5 39 08 PM](https://user-images.githubusercontent.com/296876/77865935-a8b36500-71e5-11ea-81d7-fcc05c17f57d.png)

I did make sure to use the version of Unity mentioned in the docs:

![Screen Shot 2020-03-29 at 5 32 49 PM](https://user-images.githubusercontent.com/296876/77865956-bff25280-71e5-11ea-8961-7f7c6ff493e7.png)

with Windows support:

![Screen Shot 2020-03-29 at 5 32 39 PM](https://user-images.githubusercontent.com/296876/77866158-b4ebf200-71e6-11ea-8f7f-52f11edc5e61.png)

I tried clearing the errors, but they re-appeared after running the git clone commands to pull in the vehicle and environment assets:

```
$ git clone https://github.com/lgsvl/CubeTown.git
$ git clone https://github.com/lgsvl/Jaguar2015XE.git
```

![Screen Shot 2020-03-29 at 5 46 09 PM](https://user-images.githubusercontent.com/296876/77866025-0fd11980-71e6-11ea-86a0-0177cf5e8138.png)

I also tried to run Simulator/Check, which gave me these errors:

![Screen Shot 2020-03-29 at 5 46 22 PM](https://user-images.githubusercontent.com/296876/77866043-27100700-71e6-11ea-9c6e-0cb729c1a1ba.png)

In the `~/.config/unity3d/Editor/Player.log file`, I see:

```
Vulkan detection: 0
```

## System details

* System76 Oryx Pro with Geforce 1070 (8 GB GPU RAM)
* Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* nvidia-smi output

```
# nvidia-smi
Sun Mar 29 09:45:54 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   43C    P2    30W /  N/A |    136MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     11110      C   /usr/NX/bin/nxnode.bin                       126MiB |
+-----------------------------------------------------------------------------+
```

**Comment by tleyden** [comment]
After re-installing the nvidia drivers to:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.59       Driver Version: 440.59       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
```

based on the advice in https://github.com/lgsvl/simulator/issues/287#issuecomment-524404393, it's getting past the KSampleCopy4_1_x_8 errors, and in fact I haven't seen any errors so far while opening the project in the Unity Editor.

![Screen Shot 2020-03-29 at 7 14 33 PM](https://user-images.githubusercontent.com/296876/77869004-e8804980-71f1-11ea-8609-6c648d789a4f.png)

**Comment by ChaoqinRobotics** [comment]
I follow this video https://www.youtube.com/watch?v=VqDFFyQRj8E and solve the problem.
