### ISSUE TITLE
how to get ego car bridge type info in python api side?

### ISSUE THREAD

**Issue by Vincent-Tsui-GWM** [lgsvl/simulator#706]
Hi, 
how to get ego car bridge type info in python api side. I am writing a python script test case, and sometimes I may set ego car bridge type to no bridge just for debug of test case. So I need to some way to know the bridge type in python api side  before I run 
```
ego.connect_bridge("localhost", 9090)
```
when there is no bridge in lg sim server side, the above cmd will cause exception error.

**Comment by EricBoiseLGSVL** [comment]
@Vincent-Tsui-GWM You can add a new Api command in simulator, Assets/Scripts/Api/Command/AgentBridgeGet.cs.  Then, you need to add PythonAPI/lgsvl/agent.py logic to get the data.
