### ISSUE TITLE
unity package manager error

### ISSUE THREAD

**Issue by yujie181152** [lgsvl/simulator#707]
![image](https://user-images.githubusercontent.com/4832525/78006288-6027b300-736f-11ea-9096-30053e2738cf.png)

hi,could some one can help me?
when i open the project with unity,an error occured,like the image i posted.
i don't know why this happend,i am sure i can search and load normal package with packagemanager,it's worked.
i wanne ask if your packages in project need to connected some special network address?.

**Comment by EricBoiseLGSVL** [comment]
@yujie181152 Unity needs to connect to it's servers to download the correct packages.
