### ISSUE TITLE
Impressive performance - LIDAR Realism

### ISSUE THREAD

**Issue by rukie** [lgsvl/simulator#71]
I'm thoroughly impressed by your GPU accelerated LIDAR sensor! Great work!

I do like that you provide a ROS PointCloud2, but at high speed this setup doesn't easily allow for fixing point cloud distortion, in a manner that roles back to a real vehicle.

It looks like your distortion is limited to the azimuth change of the sensor over a fixedUpdate(). Adding an estimated vehicle distance traveled to each point could smooth that out. 

It would be nice to recreate some real hardware with ethernet traffic, similar to https://github.com/vwaurich/VelodyneLidarUnitySimulation with your GPU setup. 

The messages could then be read into ROS with the Velodyne driver: 
https://github.com/ros-drivers/velodyne

Again, incredible work!

**Comment by martins-mozeiko** [comment]
Hi.

Thanks for the information. We are working on fixing the distortion and improving its performance, this is definitely high on our to-do list.

**Comment by asimonov-hitachi** [comment]
I agree that pushing simulated UDP velodyne packets seem to be a better solution. 
Unless you try to limit the interfacing to rosbridge_suite only.

**Comment by rukie** [comment]
By modifying this guy's UDP send script with some parallelization, performance significantly increases. Off the bat, its kind of slow.
https://github.com/vwaurich/VelodyneLidarUnitySimulation

**Comment by atyshka** [comment]
How does the bandwidth work with LIDAR and rosbridge? I would think that translating from JSON would be a relatively inefficient and create some performance bottlenecks but maybe not.

**Comment by EricBoiseLGSVL** [comment]
@rukie @atyshka We are finalizing a UDP solution and will be releasing soon

**Comment by rukie** [comment]
Exciting news! Thanks for the update.
