### ISSUE TITLE
imu data not publishing

### ISSUE THREAD

**Issue by ajay1606** [lgsvl/simulator#710]
Thanks to LGSVL for an updated version of the simulator package.
I have a few quick questions regarding simulator sensor data output to verify with the Autoware.

Working environment:
Linux 16.04 (ROS Kinetic)
LGSVL 2020.01 (released version)

1. command rostopic list output following topics:
/client_count
/connected_clients
/imu_raw
/nmea_sentence
/odom
/points_raw
/rosout
/rosout_agg
/simulator/camera_node/image/compressed
But there are no any data publishing in the topic /imu_raw

2. Raw points data are getting at /points_raw topic, but the output rate of is less than 5hz.

Could you please help me to figure out how to get imu_raw data and points_raw at 10 hz frequency.

Kind regards,

**Comment by EricBoiseLGSVL** [comment]
@hadiTab isn't this an issue with ROS?

**Comment by hadiTab** [comment]
@ajay1606 what sensors do you have on the vehicle? Is it the default Autoware car?
Also what are the specs of the computer you are running it on?

Do you get any errors when you try to echo imu_raw?

**Comment by ajay1606** [comment]
@EricBoiseLGSVL & @hadiTab Thanks for your quick response. Currently am running LGSVL with Autoware with following specifications

OS: Ubuntu 16.04 (32GB RAM, Graphics card Titan Xp)
ROS: kinetic

Simulation setup:
![Screenshot from 2020-04-07 15-02-16](https://user-images.githubusercontent.com/29722843/78635271-cf0d8a80-78e0-11ea-8fc2-2a5d714ee04c.png)
Vehicle and map setup:
![Screenshot from 2020-04-07 14-59-32](https://user-images.githubusercontent.com/29722843/78635219-aab1ae00-78e0-11ea-906d-0eb0f77b8166.png)
Rosbridge connection status:
![Screenshot from 2020-04-07 14-53-46](https://user-images.githubusercontent.com/29722843/78635421-227fd880-78e1-11ea-88fe-dadba1e407fc.png)
$rostopic list output:
![Screenshot from 2020-04-07 15-04-13](https://user-images.githubusercontent.com/29722843/78635441-3297b800-78e1-11ea-90f2-df58f45d1b24.png)
$rostopic echo /poinst_raw output:
![Screenshot from 2020-04-07 14-56-47](https://user-images.githubusercontent.com/29722843/78635461-3f1c1080-78e1-11ea-8049-0286e2a985a8.png)
$rostopic echo /imu_raw output:
![Screenshot from 2020-04-07 14-56-57](https://user-images.githubusercontent.com/29722843/78635488-51964a00-78e1-11ea-86f6-f590022cb1cb.png)
$rostopic hz /points_raw
![Screenshot from 2020-04-07 14-57-29](https://user-images.githubusercontent.com/29722843/78635561-7985ad80-78e1-11ea-875e-8d3c69a02bbf.png)
$rostopic hz /imu_raw
![Screenshot from 2020-04-07 14-57-55](https://user-images.githubusercontent.com/29722843/78635520-6246c000-78e1-11ea-913b-4d68e16d7cad.png)

Kind Regards
Ajay

**Comment by EricBoiseLGSVL** [comment]
@ajay1606 Can you post player.log as well as any error msg from imu_raw please

**Comment by ajay1606** [comment]
@EricBoiseLGSVL I could not find the player.log file in the  location: /.config/unity3d/LG Silicon Valley Lab/ 
Also, sometimes I observe very strangely /imu_raw publish and pause as shown in the shared [video](https://drive.google.com/open?id=1PUvsUuWL9sQnF07EZjB7xd4ubLs6QMfw)

**Comment by hadiTab** [comment]
@ajay1606 the rosbridge for ros kinetic has a lot of performance issues. Ros melodic's rosbridge does a much better job, but you can't install it on your host machine because it requires ubuntu 18.04. You can run it through docker though. I would suggest testing it out on ros melodic through a docker container to see if that improves things.

For example if you have docker installed:
1. `docker pull ros:melodic-ros-core`
2. run container: `docker run -it --net host ros:melodic-ros-core`
3. inside container install rosbridge and run it:
```
apt update
apt install ros-melodic-rosbridge-suite
roslaunch rosbridge_server rosbridge_websocket.launch
```
4. listen to topics on your host machine and see if things improve

**Comment by ajay1606** [comment]
@hadiTab , thanks for your efforts, I will check with ubuntu 18.04 and get back to you.

**Comment by ajay1606** [comment]
@hadiTab actually I have setup ubuntu 18.04 with ROS melodic in a separate machine. But I am getting an error while starting the simulation environment. 

1. Test with lgsvlsimulator-linux64-2020.03-rc1 (release version)
![Screenshot from 2020-04-09 11-18-02](https://user-images.githubusercontent.com/29722843/78851181-208a5680-7a54-11ea-9764-7434f01cbba9.png)

2. lgsvlsimulator-linux64-2020.01 (release version)
![Screenshot from 2020-04-09 11-17-21](https://user-images.githubusercontent.com/29722843/78851228-3c8df800-7a54-11ea-860b-3657f1db33f5.png)

Sorry for bothering you again, but could you please help me to fix this issue.

kind regards,

**Comment by hadiTab** [comment]
It seems like you had an old simulator installation on that machine.

Close the simulator and delete the folder called "LG Silicon Valley Lab" located in ~/.config/unity3d.

Launching the simulator again now should redownload all the maps and vehicles and the error should be resolved.

**Comment by ajay1606** [comment]
Excellent, billion thanks to you.

1. getting data imu_raw @ 90 hz
2. getting points_raw @10 hz

Really appreciate your help.
