### ISSUE TITLE
Folder name of release 2020.03-rc1 doesn't contain `-rc1`

### ISSUE THREAD

**Issue by left4taco** [lgsvl/simulator#716]
Hi there,

We have set up CI to create volume of lgsvl simulator used by docker container. However, the job failed for release 2020.03-rc1. https://gitlab.com/ApexAI/ade-lgsvl/-/jobs/504659281

In the error trace it shows that the folder name within the zip file is `lgsvlsimulator-linux64-2020.03`. However, the job is looking for a folder called `lgsvlsimulator-linux64-2020.03-rc1`.

The behavior was correct in release  2020.01-rc1, though. https://gitlab.com/ApexAI/ade-lgsvl/-/jobs/429907461

**Comment by EricBoiseLGSVL** [comment]
@left4taco we will look into this, thanks

**Comment by eagafonovlge** [comment]
@left4taco Thanks for the reporting!
We have updated zip files, folder name matches to the archive name.
Please restart CI pipeline to verify.
