### ISSUE TITLE
How to use Unity scene for LGSVL simulation

### ISSUE THREAD

**Issue by bage131** [lgsvl/simulator#723]
I imported "QA Modular Parking 1.01.unitypackage"  to Unity3D,Then I created AssetBundles with Demo scene.There was an error "Failed to add map: You must specify a valid AssetBundle" when I added new map with Demo scene in LGSVL.But It was OK when I added new map with environment_CubeTown.Could you tell me how to solve this problem? Are there any more details about how to use the scene in Unity for LGSVL simulation? Thank you.
![Failed to add map](https://user-images.githubusercontent.com/56905005/79298595-254b8080-7f14-11ea-9bbc-8dac08eeb6e8.PNG)

**Comment by Erdemhan** [comment]
I dont know what's inside your scene but if you want to do something like building a new map with unity and adding it to simulator you should build it with unity from simulator tab but there are more details about it. You can find all steps at #699

**Comment by EricBoiseLGSVL** [comment]
@bage131 yes, @Erdemhan is correct.  If you correctly created a map, it will be named "environment_YourMap".  YourMap will match folder in External/Environments and also match YourMap.scene file in that folder.  Then Simulator -> Build... will list the map and create an Asset Bundle, not a unity package.  unity package is for creating assets to distribute internally or to sell on Unity Asset Store.

We just released yesterday a tutorial video to help explain environment creation! [Here](https://youtu.be/S0w2ahhEPbE)

**Comment by bage131** [comment]
Thank you very much.But I have a new problem.I have created a  parking map in the Unity.The car is far from the ground when I  run the simulator.As shown in the picture.How to set the position on the map.Thank you.
![Car](https://user-images.githubusercontent.com/56905005/80111329-567e1d80-85b2-11ea-8d2d-0f329625e516.PNG)

**Comment by Erdemhan** [comment]
> Thank you very much.But I have a new problem.I have created a parking map in the Unity.The car is far from the ground when I run the simulator.As shown in the picture.How to set the position on the map.Thank you.
> ![Car](https://user-images.githubusercontent.com/56905005/80111329-567e1d80-85b2-11ea-8d2d-0f329625e516.PNG)

You should set SpawnInfo's position.

**Comment by bage131** [comment]
I got it.Thank you very much.
