### ISSUE TITLE
2019.1.10f1 load new assetbundle error

### ISSUE THREAD

**Issue by yujie181152** [lgsvl/simulator#729]
hi there, i wanne know that if i can use old released simulator source to load new assetbundle which from website downloaded ,for example,i use 2019.10f1 version to load the latest assetbundle ,is it ok?

i have tried to use 2019.10f1 build assetbundle  it shows "ouf of data ",and after that i  also have tried to load latest assetbundle from website but shows "Invalid: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization".  do i have to update 2019.10f1 to 2019.3.3f1?

**Comment by EricBoiseLGSVL** [comment]
@yujie181152 Sorry, Unity does not support asset bundles from older versions of Unity.  You will need to update.

**Comment by yujie181152** [comment]
can you provide the old assetbundle which compatiable with 2019.10f1,
or the asset file i can build myself,because old assetbundle cache was deleted by mistake,now i'm stuck with this issue,thank you very much

**Comment by EricBoiseLGSVL** [comment]
@yujie181152 You can just delete data.db and backup.db from the persistent data path [here](https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html)
On windows it is C:\Users\[YOU]\AppData\LocalLow\LG Silicon Valley Lab\LGSVL Simulator\
Once you delete these files, run the 2019.10 build and all assets will download again

**Comment by EricBoiseLGSVL** [comment]
@yujie181152 Did this solve your issue?
