### ISSUE TITLE
How to add new script.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#73]
I want to use /clock topic in ROS, so I try to add C# script to your simulator.
I added script like below and attach this script to the XE-Riddged Autoware/Appolo.

```
/**
 * Copyright (c) 2019 Tier IV, Inc.
 *
 * This software contains code licensed as described in LICENSE.
 *
 */

using UnityEngine;

public class RosClock : MonoBehaviour, Ros.IRosClient
{
    Ros.Bridge Bridge;
    public string SimulatorTopic = "/clock";
    private volatile bool is_connected = false;

    public void OnRosBridgeAvailable(Ros.Bridge bridge)
    {
        Debug.Log("rosbridge for /clock available");
        Bridge = bridge;
        Bridge.AddPublisher(this);
    }

    // Use this for initialization
    void Start ()
    {

    }
	
    // Update is called once per frame
    void Update ()
    {
        Debug.Log("/clock");
        if (is_connected)
        {
            var clock_msg = new Ros.Clock();
            clock_msg.clock = Ros.Time.Now();
            Bridge.Publish(SimulatorTopic, clock_msg);
        }
    }

    public void OnRosConnected()
    {
        Bridge.AddPublisher<Ros.Clock>(SimulatorTopic);
        is_connected = true;
    }
}

```

However, OnRosConnected() and OnRosBridgeAvailable(Ros.Bridge bridge) was not called and it does not publish any topics.
Please tell me how to solve this problem.

**Comment by martins-mozeiko** [comment]
Components that inherits from IRosClient and wants to use ROS also need to be added to `Needs Bridge` property on vehicle game object. See the instructions how to do here: https://github.com/lgsvl/simulator/issues/42#issuecomment-443299456

Increase count to add new element at bottom of array, and drag new component into last element.

**Comment by hakuturu583** [comment]
I succeed to publish ROS topics.
However, /clock topics was set always 0, even though the clock_msg.clock property set correctly.

**Comment by hakuturu583** [comment]
by using Visual Studio Debuuger, it shows that the topic was serialized correctly.

![image](https://user-images.githubusercontent.com/10348912/51311038-562bd400-1a8b-11e9-94c2-2b21a808a615.png)

**Comment by hakuturu583** [comment]
![image](https://user-images.githubusercontent.com/10348912/51311088-765b9300-1a8b-11e9-9fb1-f35840318397.png)

But the /clock topic always shows zero.

**Comment by hakuturu583** [comment]
Thank you!!
