### ISSUE TITLE
Apollo 5.0 Canbus is not working 

### ISSUE THREAD

**Issue by Martin20** [lgsvl/simulator#732]
Hello all,

I use apollo 5.0 and the Canbus module is not working. When I run it by its launch file, receive the following error:

![image](https://user-images.githubusercontent.com/24797708/80051436-ff524d00-84cc-11ea-8363-f24dd8d73d0e.png)

**Comment by luqiang21** [comment]
@Martin20 Our simulator is providing canbus data which is the output of Canbus driver. So you don't need to run Canbus module.
