### ISSUE TITLE
doesn't pick intensity from road marking except "BorregasAve".

### ISSUE THREAD

**Issue by msc9533** [lgsvl/simulator#738]
Hi, thanks for making this awesome simulator!
I tried to record lidar data. but some problem with getting intensity.
I modified [this](https://github.com/lgsvl/PythonAPI/blob/master/quickstart/07-save-lidar-point-cloud.py) code and visualized recorded lidar data on Rviz.
When I using `current_scene` as `BorregasAve`  looks no problem with getting intensity.
![Imgur](https://i.imgur.com/pT6uBhX.png)
but scene from `SanFrancisco`, has no difference with road surface and road marking surface.
I already tried update my enviroments from [this page](https://content.lgsvlsimulator.com/)..
![Imgur](https://i.imgur.com/RYxhPwm.png)

Are there any solutions for this?

**Comment by rongguodong** [comment]
Lidar intensity is set here (https://github.com/lgsvl/simulator/blob/master/Assets/Shaders/LidarPass.hlsl#L48).

For road surface, we defined "_MASKMAP", so intensity value is get from the metallic value, which is from an intensity texture. The intensity texture is created by artist matching the road surface. Currently, only Borregas map has this texture set. If you want to do this for other scenes, you have to generate such an intensity texture yourself.

**Comment by rongguodong** [comment]
Just double checked SF scene, and found it does have an intensity texture. There is a bug making intensity not working for SF. We are working on it and will fix it soon.

**Comment by msc9533** [comment]
Thanks for answer!

So, if I disable that `_MASKMAP`, then is it returned value from unity model's RGB or rendered RGB value include its lighting condition like camera?

**Comment by rongguodong** [comment]
> Thanks for answer!
> 
> So, if I disable that `_MASKMAP`, then is it returned value from unity model's RGB or rendered RGB value include its lighting condition like camera?

It would be the average of RGB channels of albedo color, which is calculated in the [environment shadergraph](https://github.com/lgsvl/simulator/blob/master/Assets/Shaders/EnvironmentShaders/EnvironmentSimulation.shadergraph).

**Comment by msc9533** [comment]
Thank you so much!
