### ISSUE TITLE
where to get LG sim older version

### ISSUE THREAD

**Issue by duong-pa** [lgsvl/simulator#739]
I have limited hardware which can not run current version of LG simulator which require 8GB GPU memory.
I used LG sim in the past when it required less . But now i could not find that version here. Wonder why you get rid of it? and where to get that version.

Thank you.

**Comment by luqiang21** [comment]
Hi @duong-pa, you can find our releases here https://github.com/lgsvl/simulator/releases

**Comment by dr563105** [comment]
Are you looking for these? https://github.com/lgsvl/simulator-2019.05-obsolete/releases

**Comment by duong-pa** [comment]
> Are you looking for these? https://github.com/lgsvl/simulator-2019.05-obsolete/releases

that im looking for. thank you
