### ISSUE TITLE
Weird behavior of Apollo control module in non real-time simulation

### ISSUE THREAD

**Issue by ZiwenWan** [lgsvl/simulator#740]
Hi, thanks for making this awesome simulator!
I tried to run Apollo 5.0 with LGSVL in a non-real-time simulation mode. I found that the control module can not correctly control the car to follow the trajectory. I want to know what changes needed if I want to run Apollo along with a non-real-time simulation?

Here is some basic information:
Software version: Apollo 5.0 + LGSVL
Map: Single-lane road
The factor of non-real-time simulation: 10 times slower
Modifications I made in Apollo:
(1) Change the clock in all modules to be MOCK
(2) Update the time based on the localization or GPS timestamp for all the modules
(3) Change the related configuration in the control module: e.g., control period.
Observation: The planning result is correct based on the dreamview's visualization result. The control module can not follow the planning trajectory, especially the steering control is wrong.
Thanks for your time!

**Comment by EricBoiseLGSVL** [comment]
@ZiwenWan Thanks, we are glad you like the simulator.  Apollo doesn't support running slower than real time.  You should contact Apollo support to see how to support this feature.
