### ISSUE TITLE
export simulation/car/maps setup

### ISSUE THREAD

**Issue by fgrzeszc** [lgsvl/simulator#742]
Hello LGSVL Team,

We are working in bigger group with LGSVL and the problem we are facing is that we don't know a way to share efficiently setup of maps/vehicles/simulations across different machines.
Is there any way to do that, eg. loading dump of database?

Thank you,
Filip

**Comment by lemketron** [comment]
We'd love to hear more about your specific needs in this area since we are looking into options to facilitate workgroup sharing. Could you email us offline at contact@lgsvlsimulator.com to discuss further?  Thanks!
