### ISSUE TITLE
API usage problems

### ISSUE THREAD

**Issue by Vicky-Raymond** [lgsvl/simulator#743]
Hello，LGSVL Team，
         When I ran the fifth example Python API script(05-ego-drive-in-circle.py), I only changed the vehicle name, but It was prompted with an error as shown in Figure 1 .The vehicle setting in the WebOS shows normal.
Thank you very much!

fig.1
<img width="547" alt="128c6fa3690af342dd385fb5aa5f289" src="https://user-images.githubusercontent.com/52964775/80783761-5501b600-8bad-11ea-9349-f9431847a571.png">
fig.2
<img width="784" alt="f76c450b2ef863987f6286e0ce0359b" src="https://user-images.githubusercontent.com/52964775/80783955-0bfe3180-8bae-11ea-89bc-2de7828acc47.png">

fig.3
<img width="877" alt="1d96876ba976a1cc739f7d9ac9a2593" src="https://user-images.githubusercontent.com/52964775/80783771-621ea500-8bad-11ea-8f14-c4a63a93ffc7.png">

**Comment by dr563105** [comment]
Can you try "Jaguar2015XE" instead and see if it works?

**Comment by Vicky-Raymond** [comment]
> Can you try "Jaguar2015XE" instead and see if it works?

It doesn't work.

**Comment by dr563105** [comment]
Try with "Jaguar2015XE (Autoware)". It works but not with Apollo 3.0 or 5.0.

**Comment by hadiTab** [comment]
@Vicky-Raymond Can you make sure you don't have a whitespace after '2015' in the name in the web UI?

**Comment by Vicky-Raymond** [comment]
> @Vicky-Raymond Can you make sure you don't have a whitespace after '2015' in the name in the web UI?
I rechecked it. Both names in the webUI and in code are followed by the same whitespace . According to my understanding, as long as two names are the same(consider the whitespace ), it should be OK, but it doesn't seem to be.have you got any other suggestions?

**Comment by Vicky-Raymond** [comment]
> Try with "Jaguar2015XE (Autoware)". It works also with Apollo 3.0 but not with Apollo 5.0.
The "Jaguar2015XE (Autoware)" doesn't appear in my web UI. This method doesn't work [/sad]

**Comment by Vicky-Raymond** [comment]
Solution：
delete data.db and backup.db here, C:\Users[YOU]\AppData\LocalLow\LG Silicon Valley Lab\LGSVL Simulator on windows.
