### ISSUE TITLE
Is it possible to model a truck+trailer in LGSVL?

### ISSUE THREAD

**Issue by zzangupenn** [lgsvl/simulator#745]
I did some searching for Carla and AirSim. They are both not supporting articulated models.
We are trying to study interactions of the truck+trailer setup. Just want to know if it's possible to implement in LGSVL?

Thank you very much!

**Comment by EricBoiseLGSVL** [comment]
@zzangupenn We are currently working on this feature.  It will be possible with Unity joint classes and custom joint classes
