### ISSUE TITLE
Unable to get can bus info in ROS 1

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#747]
Hello, I am trying to get the can bus info from ROS 1 using the websocket_bridge.

I added the sersors according to this piece of documentation : [can-bus](https://www.lgsvlsimulator.com/docs/sensor-json-options/#can-bus)

I started LGSVL from the docker dontainer.

And I get this error message from the ROS websocket bridge : 

```
2020-05-06 05:32:52+0300 [-] [ERROR] [1588732372.757863]: [Client 0] publish: Cannot infer topic type for topic /canbus as it is not yet advertised
```

Do you know how to solve this ? Thanks !

**Comment by MaxandreOgeret** [comment]
Works when setting the topic to `/can_info`.

These sensor setting works : 

```json
{
    "type": "CAN-Bus",
    "name": "CAN Bus",
    "params": {
      "Frequency": 10,
      "Topic": "/can_info"
    },
    "transform": {
      "x": 0,
      "y": 0,
      "z": 0,
      "pitch": 0,
      "yaw": 0,
      "roll": 0
    }
}
```

Its odd though.

**Comment by EricBoiseLGSVL** [comment]
@hadiTab Any idea on this issue?

**Comment by hadiTab** [comment]
@MaxandreOgeret it looks like we haven't actually defined the CanBus message for ROS 1. We should have mentioned this in the documentation. As it is though, the CanBus sensor only works for ROS-Apollo and CyberRT.

**Comment by MaxandreOgeret** [comment]
Ok thanks ! Any idea how to deal with this problem in an elegant way as I need the can bus data ?

**Comment by tajinder96** [comment]
Any updates on this issue?

**Comment by EricBoiseLGSVL** [comment]
@MaxandreOgeret You can define the CanBus in the bridge in Simulator source right @hadiTab ?

**Comment by tajinder96** [comment]
@EricBoiseLGSVL I was trying this just now and I simply used the same conversion for ROS1 as defined for ROS2, and it works fine. I still need to check if any modifications to the conversion for ROS1 are required, but is there something to be particularly careful about when converting to ROS1 vs ROS2 (specifically for the can bus data message)?

**Comment by EricBoiseLGSVL** [comment]
@tajinder96 Nice!  I'm not the expert on ROS, @hadiTab can let you know

**Comment by hadiTab** [comment]
@tajinder96 the LGSVL message definitions are the same for ROS1 and ROS2 so message conversions will also be the same. Nothing to watch out for. Using the same conversion for ROS1 should work fine.

**Comment by tajinder96** [comment]
@EricBoiseLGSVL @hadiTab Great, thanks a lot!

**Comment by rudolfkrecht** [comment]
Hello, could you please give more details about how it is possible to get Can Bus info with ROS 1? I was trying to modify the simulator source based on the code written for the ROS 2 bridge, without any luck. Thank you!

**Comment by hadiTab** [comment]
@rudolfkrecht in `RosBridgeFactory.cs` paste the following at line 119:
```
RegPublisher<CanBusData, Lgsvl.CanBusDataRos>(plugin, Conversions.RosConvertFrom);
```

in `RosConversions.cs` add the following method to the `Conversions` class:
```
public static Lgsvl.CanBusDataRos RosConvertFrom(CanBusData data)
        {
            return new Lgsvl.CanBusDataRos()
            {
                header = new Ros.Header()
                {
                    stamp = ConvertTime(data.Time),
                    frame_id = data.Frame,
                },
                speed_mps = data.Speed,
                throttle_pct = data.Throttle,
                brake_pct = data.Braking,
                steer_pct = data.Steering,
                parking_brake_active = false,   // parking brake is not supported in Simulator side
                high_beams_active = data.HighBeamSignal,
                low_beams_active = data.LowBeamSignal,
                hazard_lights_active = data.HazardLights,
                fog_lights_active = data.FogLights,
                left_turn_signal_active = data.LeftTurnSignal,
                right_turn_signal_active = data.RightTurnSignal,
                wipers_active = data.Wipers,
                reverse_gear_active = data.InReverse,
                selected_gear = (data.InReverse ? Lgsvl.Gear.GEAR_REVERSE : Lgsvl.Gear.GEAR_DRIVE),
                engine_active = data.EngineOn,
                engine_rpm = data.EngineRPM,
                gps_latitude = data.Latitude,
                gps_longitude = data.Longitude,
                gps_altitude = data.Altitude,
                orientation = Convert(data.Orientation),
                linear_velocities = ConvertToVector(data.Velocity),
            };
        }
```

That should do it.

**Comment by rudolfkrecht** [comment]
@hadiTab Thank you a lot for the detailed answer, now it works perfectly.
