### ISSUE TITLE
How to generate my own protofuf message

### ISSUE THREAD

**Issue by duong-pa** [lgsvl/simulator#750]
Hi,

I see you are using some form of protobuf for message format, for example Assets/Scripts/Cyber/Protobuf/localization/proto/gps.cs 
That file is auto-generated (in the comment section), let say I already have a protobuf, how can I do the same?

And how can I use that protobuf on the other side of bridge (not simulation side)?

Thank you.

**Comment by ntutangyun** [comment]
you could define the `xxx.proto` files and use google's `protobuf` binary to generate c# code.

**Comment by martins-mozeiko** [comment]
There are some instructions here: https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Cyber/CyberBridge.Initialize.cs#L14
