### ISSUE TITLE
Cluster simulation

### ISSUE THREAD

**Issue by barnaa** [lgsvl/simulator#751]
Greetings,

I'm trying to start a distributed simulation on multiple computers in the local network. So far I've been following the [Cluster Simulation Quickstart](https://www.lgsvlsimulator.com/docs/cluster-simulation-quickstart/) section in the docs, but to no avail. I've noticed the simulation runs in master mode, regardless of provided commandline arguments -- both on Linux and Windows (I've tried even some older versions); I've even built it from source on Windows but nothing changed. Then, after reading some issues here, I've checked the Player.log file and noticed this line:
`Unknown argument -c, skipping it`
Argument `--client` behaved the same. Did configuration of clusters change in the meantime since the docs were written? How can I setup the multi-computer cluster simulation on the current release?

Thank you

**Comment by EricBoiseLGSVL** [comment]
@barnaa This is not a released feature.  We will be updating docs and Cluster Simulation in a future release.
