### ISSUE TITLE
Lincoln MKZ 2017 asset bundle download issue

### ISSUE THREAD

**Issue by ozangerger** [lgsvl/simulator#752]
Hi,

I am trying to download Lincoln MKZ 2017 asset bundle from this link: https://content.lgsvlsimulator.com/vehicles/lincolnmkz2017/. However, I got an error saying "access denied" in an xml format. Please have a look at it when you have the chance. Links for other vehicles are working fine btw.

EDIT:
I've found the issue. The link needs to be updated as:

https://assets.lgsvlsimulator.com/ecd8f9818da753d4213bfca4bcaf9e55b822c223/vehicle_Lincoln2017MKZ

Best regards,
Ozan

**Comment by EricBoiseLGSVL** [comment]
@ozangerger thanks.  Sorry about the mistake. Issue has been fixed
