### ISSUE TITLE
How can I can get the camera internal parameters like focus?

### ISSUE THREAD

**Issue by chen1qy** [lgsvl/simulator#757]
I want to get the camera internal parameters of Color Camera, but I can only find the distortion parameter in JSON. Are there any default internal parameters？

**Comment by rongguodong** [comment]
The distortion parameters come from calibration of real camera. We do not provide any `default` parameters.

**Comment by chen1qy** [comment]
What about the internal parameters of real camera?

**Comment by rongguodong** [comment]
We just provide reference implementation of camera (as well as other sensors). Users can implement their own sensor plugin matching specific real sensors they are using. We implemented a sample sensor plugin for Velodyne Lidar. More details of sensor plugin can be found at: https://www.lgsvlsimulator.com/docs/sensor-plugins/.

**Comment by EricBoiseLGSVL** [comment]
@chen1qy Yes, @rongguodong is right.  If you want different camera settings, you will need to create your own camera sensor.  You can create a plugin that can be loaded without changing simulator source, or you can add to the simulator source code/sensor list and re-compile simulator.
