### ISSUE TITLE
QUESTION on LGSVL documentation with Autoware.AI

### ISSUE THREAD

**Issue by SenRamakri** [lgsvl/simulator#758]
Hello,

Im trying to get Autoware.AI(version 1.13.0) running with LGSVL. To do that, I was trying to follow the documentation here - https://www.lgsvlsimulator.com/docs/autoware-instructions/
And part of the documentation provides a sample json file at - https://www.lgsvlsimulator.com/docs/autoware-json-example/

But when I look at autoware.ai repo it has sample.json for "LGSVL Simulator" at - https://gitlab.com/autowarefoundation/autoware.ai/simulation/-/blob/master/lgsvl_simulator_bridge/config/sample.json

Why is the sample.json in Autoware.AI repo looks so different from what is mentioned in - https://www.lgsvlsimulator.com/docs/autoware-json-example/

Are these JSON files used for different purposes? How and Where are they used? Please share if you have more info on these.

Thanks in advance.

**Comment by EricBoiseLGSVL** [comment]
@SenRamakri The Autoware.AI configuration looks outdated.  @hadiTab ?

**Comment by SenRamakri** [comment]
> @SenRamakri The Autoware.AI configuration looks outdated. @hadiTab ?

Thanks for your quick reply @EricBoiseLGSVL. I will wait for @hadiTab to respond as well.

**Comment by dr563105** [comment]
The example in autoware.ai is outdated and for the older Simulator version. 

I have tried using the ones in the lgsvl documentation site, they work(don’t know if they need to be updated). You can compare them with the json already included in the vehicles tabs with autoware in web ui.

**Comment by hadiTab** [comment]
Yup, the autoware.ai JSON is outdated. Please use the one in our documentation.

**Comment by SenRamakri** [comment]
Thanks for the answers everyone, I'll use the one from LGSVL documentation.
