### ISSUE TITLE
Unable to start binary executable on linux...

### ISSUE THREAD

**Issue by jonndoe** [lgsvl/simulator#760]
(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ ./simulator
Set current directory to /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03
Found path: /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03/simulator
(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ 

So current directory is correct as I see...Could you advice??

**Comment by jonndoe** [comment]
`(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ ./simulatorSet current directory to /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03
Found path: /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03/simulator
(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ 
`

**Comment by jonndoe** [comment]
`(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ ./simulator
Set current directory to /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03
Found path: /home/latin/PycharmProjects/lgsvlsimulator-linux64-2020.03/simulator
(base) latin@latin:~/PycharmProjects/lgsvlsimulator-linux64-2020.03$ 
`

**Comment by EricBoiseLGSVL** [comment]
@jonndoe Please post player.log / system specs and any other info you can.  This is very difficult to understand what you are asking.  Can you not find the installed executable? Does it crash on start?  More information will help us see what the issue is and will help others that might have the same problem.

**Comment by jonndoe** [comment]
Thanks for your reply, after Ive downloaded the binary for linux [https://github.com/lgsvl/simulator/releases/tag/2020.03](url), I unziped it to the download folder and cd to it and run ./simulator . After this I have issue in my shell: Set current directory to /home/latin/downloads/lgsvlsimulator-linux64-2020.03 Found path: /home/latin/downloads/lgsvlsimulator-linux64-2020.03/simulator

**Comment by jonndoe** [comment]
Should I make any extra commands to run executable?

**Comment by EricBoiseLGSVL** [comment]
@jonndoe Thanks for clarifying.  Have you looked through the documentation on getting started yet?  You can find it [here](https://www.lgsvlsimulator.com/docs/getting-started/).  @luqiang21 is jon missing any steps for running the executable?

**Comment by jonndoe** [comment]
Thank you! Works now!
