### ISSUE TITLE
Under Ubuntu 18.04, drag to change the size of the client window. After starting the simulations, ubuntu os will crash

### ISSUE THREAD

**Issue by radiateboy** [lgsvl/simulator#761]
Local environment:
Ubuntu 18.04   GTX 1080ti   i9-9900k  128G .
Nvidia Driver Version:440.59    CUDA Version: 10.2

**Comment by EricBoiseLGSVL** [comment]
@radiateboy What version of simulator are you using?

**Comment by radiateboy** [comment]
@EricBoiseLGSVL  
I use version 2020.03 release

**Comment by EricBoiseLGSVL** [comment]
@radiateboy Thanks.  This is a known issue with Unity at the moment but we will look into some possible solutions.

**Comment by EricBoiseLGSVL** [comment]
This is still an issue with Unity and a fix won't be until we can move off 2019
