### ISSUE TITLE
About Cyberlog Parsing

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#762]
Is there a cyberlog parsing feature or script in this project？Thank you！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 Is [this](https://github.com/ApolloAuto/apollo/issues/8388) what you are asking about?

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Is [this](https://github.com/ApolloAuto/apollo/issues/8388) what you are asking about?

Yes similar to ros record for playback log, does cyberlog have such a playback tool in this proj?Thank you!

**Comment by lemketron** [comment]
> does cyberlog have such a playback tool in this proj?Thank you!

@yumianhuli2 Yes, Apollo has [Cyber RT Developer Tools](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md) including cyber_recorder:

> cyber_recorder is a record/playback tool provided by Apollo Cyber RT. It provides many useful functions, including recording a record file, playing back a record file, splitting a record file, checking the information of record file and etc.

**Comment by yumianhuli2** [comment]
> > does cyberlog have such a playback tool in this proj?Thank you!
> 
> @yumianhuli2 Yes, Apollo has [Cyber RT Developer Tools](https://github.com/ApolloAuto/apollo/blob/master/docs/cyber/CyberRT_Developer_Tools.md) including cyber_recorder:
> 
> > cyber_recorder is a record/playback tool provided by Apollo Cyber RT. It provides many useful functions, including recording a record file, playing back a record file, splitting a record file, checking the information of record file and etc.

Hi! how can I use it in this simulator in unity?

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 It's not used in Simulator but in Cyber
