### ISSUE TITLE
How to annotate map Shalun

### ISSUE THREAD

**Issue by miluit01** [lgsvl/simulator#766]
Hey guys,

I am following the doc try to annotate Shalun map.

When I am opening Assets/External/Environment/Shalun/Pretabs/MapShalun and just see a map without road only the traffic lights and signs show up in the gui.

![Screenshot from 2020-05-18 12-15-40](https://user-images.githubusercontent.com/1423938/82173888-6cf16d80-9901-11ea-8ba4-b1b0e9862da9.png)

Many thanks for any help!

**Comment by EricBoiseLGSVL** [comment]
@miluit01 You are in Prefab view in Editor.  Go back to scene view to edit annotation.  Also be sure to enable gizmos in Editor to see the annotation.

![annotation-help](https://user-images.githubusercontent.com/45106230/82241575-3dd30000-98f1-11ea-9cd5-58db48e8b039.png)

**Comment by miluit01** [comment]
Hi Eric,

perfect. It works! You save my day!

p.s.: some how my git lfs worked not correctly. I re-git lfs clone everything. Then activate Gizmos and annotation is show up.

Many thanks!
