### ISSUE TITLE
Data gathering -- Images and control topic frame receiving rate bottleneck

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#768]
Hello!

I don't know if this is LGSVL or ROS problem. I'd like to try to seek help here. 

In my data collection node, I use [approx time sync](https://github.com/ros2/message_filters/blob/master/src/message_filters/__init__.py#L242) class from the [ros2_message_filters](https://github.com/ros2/message_filters). In its argument I adjusted the queue size to 70 (as mentioned here in step [1.4](http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers)). And use the same `message_filters` to setup the subscriber nodes too. 

`ts = message_filters.ApproximateTimeSynchronizer([sub_center_camera, sub_left_camera, sub_right_camera, sub_control], 40, 0.02)`

`ts.registerCallback(self.callback)`

This change made a big difference making the data appear in the terminal a second or two after pressing `play` in the simulator. As far as I looked, I couldn't find a buffer size argument for message_filters; only cache. But cache has own callback function. Are buffer size and queue size from subscriber POV, same? 

My target is 100,000 data entries. I get about 5 entries per second. Taking it close to 6 hours to reach my target. In the Simulator, I can see the camera nodes transmit something close to 10Hz and the control topic 10 times that at 100Hz. How to find a compromise between these two ? Will shared memory(shm) help?

Thank you.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 we will need to look into this.

**Comment by dr563105** [comment]
Thanks Eric. You can use the latest Lanefollowing tutorial, Collect script. Just adjust the value of queue size and slop as I did. Though I expanded the control topic to include more info, it shouldn't be a problem to verify.

**Comment by dr563105** [comment]
One thing I did was increase the queue size to 100 and slop to 2.5 seconds. In the CSV file, about 10 entries per second. So it reduces the time to my data target to 2 hrs 35 mins driving time.

**Comment by rongguodong** [comment]
There are some factors limited the cap of rate you can achieve: Each camera sensor has a `Frequency` which is set to 15 by default; But even if you raise it, it also depends on how many frames your machine can render for three cameras. Furthermore, even if your machine is powerful enough to generate many frames per second, it is still limited by how much data you can send out via bridge.

We currently have a bandwidth limit of the ROS bridge. I believe 10Hz is already the max rate you can get for three cameras. We are looking into workaround to send out camera images without bridge. If we have a better way to do that, it may be included in the future release of the simulator.

With that, if the sending rate is 10Hz, no matter what you change on the receiving side, the rate will be capped at 10Hz.

**Comment by dr563105** [comment]
Thank you @rongguodong.  

Do you mean to say since I use three camera sensors, it is slowing down my machine capability to process faster? What performance impact would I have if I add LIDAR into the mix? 

I tried to change the buffer size of the web socket in Rosbridge.cs. It didn’t seem to have helped. 

> We are looking into workaround to send out camera images without bridge.

Is this something I can accomplish in a short time say a week or two? Just a small addition to help me make progress in the short term? 
Where can I look?

**Comment by rongguodong** [comment]
@dr563105 If you add a Lidar, it definitely affect the performance. However, if your machine is powerful enough, most probably the bottleneck is the bridge bandwidth. So the publishing rate may not be very different with and without Lidar.

BTW: We have implemented the work around for Lidar sensor. The newly introduced [VelodyneLidarSensor plug-in](https://www.lgsvlsimulator.com/docs/lidar-plugin/) uses UDP to directly send Lidar data to the server (where AV stack is running), and does not use the bridge at all. You may try VelodyneLidarSensor plub-in, or build your own Lidar Sensor plug-in if you are using other Lidar models.

We are looking into similar workaround for camera sensor as well. If you come with a good solution, you are welcome to create a pull request to contribute to our simulator.

**Comment by dr563105** [comment]
Incidentally I even increased the UDP limit of Ubuntu to a higher number 5228220(not sure on the exact number). I already use the Lanefollowingsensor plugin. I will look into VelodyneLidarSensor plug-in. 

Thanks again. This is really encouraging that I can reduce the data gathering time.

**Comment by dr563105** [comment]
Closing this issue for now as I couldn’t solve it before my data collection task. I reckon I had to drive around for more than four hours.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 sorry we could not resolve this
