### ISSUE TITLE
how to make waypoint.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#77]
I read this document(https://www.lgsvlsimulator.com/docs/map-annotation/, https://github.com/lgsvl/simulator/issues/60#issuecomment-451261249) and try map annotation.
But it was failed when I click create tmp waypoint.
No waypoint was shown in the scene view.

![image](https://user-images.githubusercontent.com/10348912/51524974-9e276e00-1e72-11e9-8651-295d7be40c1c.png)

**Comment by hakuturu583** [comment]
No error log appears in the console.

**Comment by luqiang21** [comment]
> No error log appears in the console.

The waypoint should be shown in the center of the scene. You can try to zoom in since the waypoint may be hard to find and create a temp waypoint again.

**Comment by luqiang21** [comment]
> No error log appears in the console.

Please make sure your road belongs to the layer of `Ground and Road`. Waypoint is only created on this layer.

**Comment by hakuturu583** [comment]
Thanks!! I succeed!!
