### ISSUE TITLE
PID controller frequency

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#773]
Hello everyone, 

I would like to know if it is possible to tune the PID controller, especially the rate .

I believe the PID controller in nested in the "Vehicle Control" sensor : 
```json
  {
    "type": "Vehicle Control",
    "name": "Autoware Car Control",
    "params": {
      "Topic": "/vehicle_cmd"
    }
  }
```

But I couldnt find anything. In carla it would be the https://github.com/carla-simulator/ros-bridge/tree/master/carla_ackermann_control package.

Thanks for your help !

**Comment by hadiTab** [comment]
@MaxandreOgeret there is no PID controller for vehicle control in the simulator. People use many different types of closed loop control algorithms and we don't think it makes sense for us to implement one in the simulator and force everyone to use it.

We do provide feedback for the steering and acceleration commands which you can use to write your own controller.
