### ISSUE TITLE
Adding or Findung new Maps to simulate

### ISSUE THREAD

**Issue by David-Sola** [lgsvl/simulator#774]
Hello all together,

Is there a place where further Maps are available, e.g. for a German Autobahn or longer country roads?
Thank you,

David

**Comment by EricBoiseLGSVL** [comment]
@David-Sola We are working on creating more maps and making it easier for users to share.  We hope to release these features soon.  In the meantime, Unity has many assets to create maps in their asset store.  We have a tutorial [here](https://youtu.be/S0w2ahhEPbE) that will help you create maps that fit your needs.
