### ISSUE TITLE
Windows or Ubuntu? 

### ISSUE THREAD

**Issue by eniseiskaya** [lgsvl/simulator#777]
Hello,

Sorry I'm beginner and I really need your help.
I have a task to add a car or robot with lidar and mono camera to San Francisco. I installed the simulator on Windows. Can I do my task on Windows or I must do it on Ubuntu?

Thank you for your answers!

**Comment by ntutangyun** [comment]
you could use the PythonAPI as documented [here](https://www.lgsvlsimulator.com/docs/python-api/).

**Comment by eniseiskaya** [comment]
@ntutangyun  Thank you!
