### ISSUE TITLE
Apollo building error

### ISSUE THREAD

**Issue by huyichen19950417** [lgsvl/simulator#78]
I have git clone the lgsvl/apollo folders and try to build apollo in docker. But when I build it in docker, using `bash apollo.sh build`, there is a building failure saying: 

"ERROR: /apollo/modules/perception/obstacle/onboard/BUILD:296:1: C++ compilation of rule '//modules/perception/obstacle/onboard:ultrasonic_obstacle_subnode' failed (Exit 4).
gcc: internal compiler error: Killed (program cc1plus)"

shown in picture as below:
![lgsvl_apollo_builderror](https://user-images.githubusercontent.com/42275638/51684336-1e251380-1fec-11e9-983b-ec13c57ead20.png)

 I've also download the original apollo (version 3.0), and have built it in docker successfully.

Is there any idea about solving this problem?

**Comment by martins-mozeiko** [comment]
Can you check if you are not running out of memory when building Apollo? Gcc often shows this error when it runs out of memory. If this is the error, then reduce parallel compilation jobs. Open `apollo.sh` script in editor and change number after `--jobs` argument. Try something like `--jobs=2`

**Comment by huyichen19950417** [comment]
Thanks! I've changed the argument in apollo.sh build function to `JOB_ARG= "--jobs=4"`, and built successfully :+1:
