### ISSUE TITLE
Unable to setup radar with ROS1

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#781]
Hello, 

I am trying to setup the radar with LGSVL in Docker and I can't manage to make the Radar work, I get this error in the web interface : 

![image](https://user-images.githubusercontent.com/22786578/83380589-f10a2180-a3e6-11ea-9859-49f230590d5f.png)

Thanks for your help

PS : Right now I can't manage to get working : 

 - Radar
 - [GPS](https://github.com/lgsvl/simulator/issues/767)
 - [CAN Bus](https://github.com/lgsvl/simulator/issues/747)

**Comment by EricBoiseLGSVL** [comment]
@daviduhm Do know why the docker sensor is failing?  @MaxandreOgeret What version of simulator are you using?

**Comment by rongguodong** [comment]
@MaxandreOgeret Could you please provide more details of how to reproduce this? What docker are you using? Which version of simulator are you using? Are you following our instructions here: https://www.lgsvlsimulator.com/docs/autoware-instructions/?

**Comment by martins-mozeiko** [comment]
Radar implementation in Simulator supports only Apollo. To work with Autoware/ROS you'd need to add extra code to convert data produced by Radar sensor into whatever message ROS expects. You can see example, how this data is converted for Apollo here: https://github.com/lgsvl/simulator/blob/master/Assets/Scripts/Bridge/Ros/RosConversions.cs#L151

**Comment by EricBoiseLGSVL** [comment]
@MaxandreOgeret Same with your CanBus issue.  Look how the other sensors are supported and add the converting code to simulator source. #747
