### ISSUE TITLE
Install Unity 2019.3.3f1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by AlexandrZabolotny** [lgsvl/simulator#785]
Hello, i try to install Unity Editor in Unity Hub, but i can not select Unity 2019.3.3f.
Can i install latest version of Unity? How can i install Unity 2019.3.3f?

**Comment by rongguodong** [comment]
Can you try Step 2 [here](https://www.lgsvlsimulator.com/docs/build-instructions/)?

**Comment by ntutangyun** [comment]
Try this:
1. open a new terminal
2. `/path/to/UnityHub.AppImage unityhub://2019.3.3f1/7ceaae5f7503`

**Comment by lemketron** [comment]
It should be possible to just click the 2019.3.3f1 button in the browser and have the UnityHub launch automatically but it’s not; apparently that’s a known issue with UnityHub on Linux.

To help users in the future, I’ve updated the documentation to make this more clear by including the actual command line text that works.

Sorry for the inconvenience. (I ran into this same issue myself!)

**Comment by AlexandrZabolotny** [comment]
@ntutangyun, thank you
