### ISSUE TITLE
Load Autoware Format

### ISSUE THREAD

**Issue by AlexandrZabolotny** [lgsvl/simulator#789]
Can i load to scene HD map in Autoware csv format?

**Comment by EricBoiseLGSVL** [comment]
@AlexandrZabolotny We support Lanelet2 and OpenDRIVE HD map import.  Is this what you mean?

**Comment by luqiang21** [comment]
@AlexandrZabolotny Since Autoware is changing to use Lanelet2 map format, so we implemented importer and exporter for Lanelet2. If you are asking about previous Autoware Vector Map, our simulator only support exporting it.

**Comment by AlexandrZabolotny** [comment]
@EricBoiseLGSVL, yes, thank you
