### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by AlexandrZabolotny** [lgsvl/simulator#790]
Hello!
How can i get and build lidar, radar, camera and GPS?

![image](https://user-images.githubusercontent.com/61351599/83847544-1bc0e680-a715-11ea-8c65-519567c5a1ab.png)

**Comment by ntutangyun** [comment]
You can check out the codes for those sensors at `Assets/Scripts/Sensors/`.

Customized sensors placed at `Assets/External/Sensors` will be listed in the **Sensors** section in your screenshot. Check out docs [here](https://www.lgsvlsimulator.com/docs/sensor-plugins/)

**Comment by rongguodong** [comment]
This build dialogue only lists "Sensor Plugins". Those you mentioned are build-in sensors which are built with the simulator itself.

**Comment by EricBoiseLGSVL** [comment]
@AlexandrZabolotny @ntutangyun and @rongguodong are right.  There are two types of sensors in the simulator.

1) Built-in sensors that we provide with the source code, e.g., LiDAR, GPS, etc..  These are in Assets/Scripts/Sensors, Assets/Prefabs/Sensor and finally added to Assets/Resources/RuntimeSettings in SensorPrefabs Array. You can directly edit or duplicate these sensors to your needs. *NOTE* This can cause issues if you pull our latest release so we created Sensor Plugins to mitigate.

2) Sensor Plugins are what you see in Build... windows.  Like @ntutangyun pointed out, these need to be in the External folder to show up to build.  This helps keep your new sensors separated from source code.  We have [ComfortSensor](https://github.com/lgsvl/ComfortSensor) as an example.
