### ISSUE TITLE
White screen whith LGSVL simulator

### ISSUE THREAD

**Issue by Eolion** [lgsvl/simulator#795]
Hello, I'm currently discovering the software and I want to install it with apollo5.0. To be able to launch the apollo docker I must have the nvidia 440 driver because with the 390 it doesn't work. My problem is that :  with this driver when I launch a simulation with LGSVL the screen displays the environment during one frame and becomes completely white.
Do you have any solution ?

**Comment by dsaraf-hub** [comment]
@Eolion what was the fix?
