### ISSUE TITLE
Failed to angular control of the car.

### ISSUE THREAD

**Issue by hakuturu583** [lgsvl/simulator#8]
I tested your sim with autoware and send autoware_msgs/VehicleCmd topic to your sim.
But, the car move forward when I send linear_velocity command, but it was not moved when I send angular_velocity.

Please watch [this video](https://www.youtube.com/watch?v=HheYsBvUsEE).

**Comment by hakuturu583** [comment]
I can control steer angles using keyboard....

**Comment by hadiTab** [comment]
@hakuturu583 we've pushed an update that should fix this issue. I tested the fix and it works on my setup. 

Thanks for finding this issue. I will close the issue. Feel free to reopen it if you still have this issue.
