### ISSUE TITLE
[Apollo & Simulator] Cannot choose vehicle and load maps in apollo

### ISSUE THREAD

**Issue by huyichen19950417** [lgsvl/simulator#80]
I have tried with the instructions from your website[https://www.lgsvlsimulator.com/docs/apollo-instructions/](url). I've built up Apollo successfully and try to launch apollo alongside the simulator. Here are several problems I have met with:

- No `HD Mode` in the simulator:
![lgsvl_problem1](https://user-images.githubusercontent.com/42275638/51751496-49c00080-20b5-11e9-8d75-026b03642583.png)

- Cannot select vehicle in Dreamview: 
![lgsvl_problem2](https://user-images.githubusercontent.com/42275638/51751693-c3f08500-20b5-11e9-82e9-2bc4514849fa.png)
According to the documents, the vehicle `LG SCL 1080` should be selected

- Although the map SanFrancisco is selected, it is not loaded in Dreamview.

Is there any idea to solve these problems?

**Comment by martins-mozeiko** [comment]
When you cloned Apollo repository did you clone with `--recursive` argument to have all the submodules inside?

Can you please check `modules/map/data/san_francisco` and `modules/calibration/data` folders to see if they are empty or not.

If they are empty, first update submodules with `git submodule update --init` then restart Apollo, no need to rebuild it.

**Comment by alchemz** [comment]
Hi Martins, thank you for the reply, I tried to update the module by git submodule update --init, but I got the error message 
``
> Unable to checkout '21edeb97e353acaf613b111d25e2c72320395f84' in submodule path 'modules/calibration/data'

**Comment by martins-mozeiko** [comment]
Oops, that's our mistake. Forgot to push latest commits in lgsvl/apollo-vehicle repository. I've updated it now, please try again.

**Comment by alchemz** [comment]
![lg_apollo](https://user-images.githubusercontent.com/10191088/51995384-771afe80-2467-11e9-8f7c-7a46330859cc.png)

**Comment by alchemz** [comment]
It is working  now! @martins-mozeiko 🍕 for you on my treat.
