### ISSUE TITLE
Problem about building and running from source

### ISSUE THREAD

**Issue by chen1qy** [lgsvl/simulator#800]
Hi, I have some problem when building from source. 
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/41505923/84334002-d7759080-abc3-11ea-8bee-6bf7edef6eb3.png)

And the simulator doesn't work:
![Kazam_screenshot_00003](https://user-images.githubusercontent.com/41505923/84334190-579bf600-abc4-11ea-9dd7-5e640d1e322c.png)

the OS is Ubuntu16.04, and the project shows as
![Kazam_screenshot_00004](https://user-images.githubusercontent.com/41505923/84334483-0b04ea80-abc5-11ea-9ec8-f56798d994f9.png)

**Comment by chen1qy** [comment]
Is the Unity ok?
![Kazam_screenshot_00005](https://user-images.githubusercontent.com/41505923/84335173-da25b500-abc6-11ea-9ff8-1fb99713663c.png)

**Comment by EricBoiseLGSVL** [comment]
@chen1qy First off you only need Linux and Windows Support.  No WebGL and no need for documentation.  Check is fine, it is more for internal development anyway.
You need to post player log so we can see errors.  Also, what environment are you trying to build?

**Comment by chen1qy** [comment]
I choose the SanFrancisco and Jaguar2015XE to play the simulator. The environment built is as follows:
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/41505923/84381919-526a9580-ac1c-11ea-9bd6-8f193f0255b4.png)

Sorry, I don't find the player log. Maybe I should learn about unity first.

**Comment by EricBoiseLGSVL** [comment]
@chen1qy Ok, thanks.  Yes, player log from binary or editor can be found from every run and is very helpful to find errors or issues.  Still, I think the issue you have is not installing git LFS before you cloned the scenes.  Please use git lfs install (download if you haven't first), if you have downloaded it then git lfs pull.  You should be able to see the files are textures/meshes etc not text files pointing to urls.  Also, try building one asset at a time, not all at once.  This can help narrow the issue maps/vehicles.

**Comment by chen1qy** [comment]
Thanks very much for your reply. I will try it.

**Comment by devynliu** [comment]
hello,i also meet this question.How can you resolve it? thanks!

**Comment by ntutangyun** [comment]
@devynliu have you used git lfs ?
