### ISSUE TITLE
Multiple Lidar data collection synchronization 

### ISSUE THREAD

**Issue by SeymurSm** [lgsvl/simulator#803]
Hi All,
We are using 4 lidars on ego vehicle. To collect data by using PythonAPI I have use 4 different threads to collect each lidar data. The problem is there is no synchronization between output data and it is being a problem when we try to merge data of lidars on a single point cloud. This difference diverges 100 , 150 ms on some lidars. I think it is because of both capture and save latency. Some threads runs slower than others. Is there any way to collect each lidar on the same time frame? It is also possible to solve this problem by stopping ego vehicle movement on ever capture. Is it possible by means of PythonAPI? 

Thanks!

**Comment by rongguodong** [comment]
Currently we do not have any synchronization between sensors -- each Lidar sensor generates and publish points independently. If you use [Velodyne Lidar Sensor](https://www.lgsvlsimulator.com/docs/lidar-plugin/#velodyne-lidar-sensor-plugins), you will have timestamp for every point, which may be used to match points from different Lidar sensors.

**Comment by EricBoiseLGSVL** [comment]
@SeymurSm It would be better to process the point cloud data from timestamps after collection like @rongguodong posted.  Velodyne Lidar Sensor would be best for this

**Comment by SeymurSm** [comment]
Hi @EricBoiseLGSVL . I have changed some parts of simulator and PythonApi to collect merged lidar data at once. It is working but it is slow as expected. Below snapshot is from visualization of merged data.
![Screenshot from 2020-06-15 10-29-27](https://user-images.githubusercontent.com/8245619/84629536-263c6680-aef3-11ea-8263-0c3f896cab21.png)
. 
Could you please share the link that @rongguodong  posted this process.

**Comment by EricBoiseLGSVL** [comment]
@SeymurSm Yes, we are saying that it would be better to do this after a simulation has run.  We can't share the code at this time but I'll see if we can point you in the right direction

**Comment by EricBoiseLGSVL** [comment]
@daviduhm any pointers to merge multiple point clouds?
