### ISSUE TITLE
Bridge does not connect correctly.

### ISSUE THREAD

**Issue by SungYinYang** [lgsvl/simulator#809]
Hi, I got a problem similar to #804.

My bridge did not connect correctly.
I have followed the latest tutorial and build Apollo successfully today.
My apollo did not connect in the following step. 

Launch bridge (inside docker container):
./scripts/bridge.sh

I would need to add sudo in order to start my bridge.sh.
After adding that, there was no information print out from the terminal.
My dreamland's localization is always having an error.

![Problem with bridge](https://user-images.githubusercontent.com/54567577/84910926-1175f380-b0ea-11ea-9a49-7a40f8e2928e.png)

Also, my cyber_launch start also has error messages.
![Screenshot from 2020-06-17 22-31-22](https://user-images.githubusercontent.com/54567577/84911169-66b20500-b0ea-11ea-9c89-c111651569b5.png)

Any help would be appreciated!

**Comment by EricBoiseLGSVL** [comment]
@luqiang21 Any idea why this is happening?

**Comment by rongguodong** [comment]
Are you using our fork of Apollo 5.0 or latest Apollo master (5.5)?
If later, please select the correct setup mode "Mkz Lgsvl".

**Comment by rongguodong** [comment]
From the screenshot of Dreamview, I believe you are using Apollo master, but with a wrong setup mode. :)

**Comment by SungYinYang** [comment]
Thanks! I would try it out.

**Comment by lemketron** [comment]
Here's a screen shot that demonstrates the proper settings for Dreamview when using apollo-master...
![apollo-master-dreamview](https://user-images.githubusercontent.com/96521/84945986-d6010800-b09c-11ea-816b-8482f4b1a5bc.png)

**Comment by SungYinYang** [comment]
@lemketron @rongguodong Thanks for your clarification!
I am able to see my Dreamview when using apollo master.

However, after I click Submit ROUTE in Dreamview, the car in the LGSVL did not move.
Any help would be appreciated.

Here are some settings of my Dreamview.

Layer Menu:
![layer menu](https://user-images.githubusercontent.com/54567577/84985077-b0dcca00-b16e-11ea-8494-6dcf8c0c3b20.png)

Module Controller:
![module controller](https://user-images.githubusercontent.com/54567577/84985123-c225d680-b16e-11ea-9d87-4f5a232b54e9.png)

**Comment by lemketron** [comment]
The hourglass in the fence indicates that Apollo auto mode is "not ready" according to the [Dreamview documentation](https://github.com/ApolloAuto/apollo/blob/master/docs/specs/dreamview_usage_table.md).

Sometimes it helps to "nudge" the car a little by hitting the up-arrow on the keyboard, but in general Apollo should start driving if everything is ready and it is communicating with the simulator (and the fact that localization has placed the ego vehicle properly on the Borregas map is a good sign).

**Comment by SungYinYang** [comment]
@lemketron Thanks for your fast reply.
I would try it now!

**Comment by SungYinYang** [comment]
@lemketron 
I have tried multiple times in running the same routes.
I succeeded to make the car move in auto mode by nudging the car a little bit by hitting the up array for the first time. 
However, all of my attempts failed after the first time.
It seems pretty not stable for me.

I notice that the "not ready" sign exists in my scenario forever.
May I know what apollo version you are using?
Do you recommend me to download the apollo 5.0 instead of the latest master?

Thanks again for all your reply.
I really appreciate your time in answering my new baby questions.

**Comment by lemketron** [comment]
On what hardware are you running the Simulator and Apollo on and with which GPU?

If your system supports Apollo 5.0 I would recommend trying that instead, from the [LGSVL fork](https://github.com/lgsvl/apollo-5.0) as documented [here](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/).

In addition, if you are trying to run both apollo and simulator on a single machine that can sometimes be too demanding and it may help to run apollo on a separate machine (but then be sure to change the bridge address in the vehicle configuration from localhost to the IP address of the apollo machine where the CyberRT bridge is running).

**Comment by SungYinYang** [comment]
I am running it with the Ubuntu system and with an RTX 2080S GPU.
Oh, I see that the requirement for Apollo 5.0 do not support my GPU.
Does my GPU support the latest Apollo (in the master)?

Currently, I am running both of them on the same machine.
Yeah, I notice that sometimes my machine would get overheated by using them together.
I would definitely put them separately later on.

Thanks again!

**Comment by lemketron** [comment]
I have run apollo-master on a RTX-2070 (Razer Blade) laptop with the simulator running on the same machine (with Ubuntu 18.04) but it is definitely challenging. In particular, I usually close Chrome and anything else that might be using the gpu (see `nvidia-smi` tool for GPU memory usage). 

Otherwise, one of the apollo modules that use GPU (usually perception) can crash, which would definitely prevent the car from moving (but you would know as the switch will move back to "off" in dreamview modules view). 

Running dreamview in Firefox will use less GPU (than Chrome), and running it on a separate computer altogether will free up GPU and CPU resources.

If there isn't enough CPU performance available (see `top` tool), then it's possible that apollo may not reach the "ready" state to be able to drive. That said, I have run the simulator and apollo on a single machine with an 8GB GPU. Just don't leave anything else running that isn't needed. I do get better results running apollo 5.0 on a separate machine with a GTX-1080.

**Comment by SungYinYang** [comment]
Thank you so much for all your help!
Your advice is very valuable to me!

**Comment by SungYinYang** [comment]
@lemketron 

Hey, I got a follow-up question.
Currently, I am requesting another GPU machine so I am not able to put the two programs in two computers yet.

Recently, I have tried to build Apollo 5.0 on my RTX2080S GPU machine.
I found out that I was able to build it.
However, the result is quite similar to my Apollo5.5 one.
Both of them would not start driving after I click "submit route".
I have tried to nudge them a little bit.
The car would move, but the car did not follow the correct route.
The car would just go straight.

Is this a CPU resources problem?
Or is this a GPU problem that why RTX GPU card is not suitable for Apollo 5.0 as stated in LGSVL documentation?
![Apollo5 0](https://user-images.githubusercontent.com/54567577/85284672-28d62780-b4c2-11ea-9c6d-c3d5bc9a9a00.png)
I notice that I am not able to see the block of information in front of my ego vehicle in Apollo 5.0.

Thanks again for your time in answering all my previous questions!

**Comment by luqiang21** [comment]
@SungYinYang Looks like your planning module is not working. The car is not getting control messages from Apollo. I think the car moves because you moved it a bit, then it continues. You need to check the module status on `Module Controller` tab to see if other modules are working correctly.

**Comment by lemketron** [comment]
The RTX is not supported by Apollo 5.0.  If you want to run on RTX you should [build apollo master](https://www.lgsvlsimulator.com/docs/apollo-master-instructions/).

**Comment by SungYinYang** [comment]
Thanks for all of the answers!

**Comment by SungYinYang** [comment]
@lemketron 

Thanks for your previous advice!
I have successfully connected two machines for Apollo5.5 (master) and LGSVL simulator.
Both machines used RTX 2080 GPU card.
The location on the dreamland would change when I move the car in the LGSVL simulator.

However, I am still not able to send a request route to run the EGO vehicle from point A to point B.
I notice that the auto mode is still not working.
![image](https://user-images.githubusercontent.com/54567577/86732791-44fdcb00-c063-11ea-8051-a2cf9df7c678.png)

I also notice that a few weeks ago, the picture that you send in this issue has the same problem.
![image](https://user-images.githubusercontent.com/54567577/86733191-927a3800-c063-11ea-8180-bd756538c4ed.png)
(There is a white stop sign indicate that auto mode is not working.)

I am wondering that is there any other problem that would affect the auto mode status?
Since I have used two machines, I am pretty sure that it is not the problem of demanding CPU resources.

I have tried to use a "cyber monitor" to monitor my module.
I also try to execute every possible module in the apollo/scrips file.
The following is my cyber monitor.
![image](https://user-images.githubusercontent.com/54567577/86733822-18967e80-c064-11ea-8314-104ea7042d26.png)

I notice that there is a script "pad.sh", which is related to the auto-drive mode.
![image](https://user-images.githubusercontent.com/54567577/86734212-5f847400-c064-11ea-9b26-091e110a758d.png)

It asks me to enter 0 or 1 to either "reset to manually drive mode" or "auto-drive mode".
I tried to enter 1, but it does not help.

Any help would be appreciated!
Thanks!

**Comment by rongguodong** [comment]
It seems your traffic light module is not running.

**Comment by rongguodong** [comment]
What is that "pad_terminal"? Where do you enter 0 or 1?

**Comment by SungYinYang** [comment]
@rongguodong 

Yes, I notice that my traffic light module cannot turn on. 

"pad.sh" is a script inside apollo/scripts. I think these scripts are related to the apollo module that is in the screenshot.
![image](https://user-images.githubusercontent.com/54567577/86809765-caf33380-c0ae-11ea-837c-4ce03d74b6c9.png)

I enter 0 or 1 in the apollo container after I run the script.

**Comment by rongguodong** [comment]
Do you see any errors in the log of traffic light module? Why cannot it run?
Do you use "bootstarp_lgsvl.sh" to start the dreamview? Do you have decompressed images in cyber_monitor?

What is "pad.sh"? Do you run it manually? I never used it before.

**Comment by SungYinYang** [comment]
@rongguodong 

Do you see any errors in the log of traffic light module? Why cannot it run?
**1. I am not able to see traffic light log. May you tell me the file name of the log?
When I click the traffic light module in Apollo Dreamland, it would turn blue for 1 second and then turn off again.
** 

Do you use "bootstarp_lgsvl.sh" to start the dreamview? Do you have decompressed images in cyber_monitor?
**Yes, I did use "bootstarp_lgsvl.sh". I do not know that I have decompressed images in cyber_monitor or not.**

What is "pad.sh"? Do you run it manually? I never used it before.B
**I run it manually to see if this is the problem for my automode.
The problem that I encounter is that I am not able to start the automode to let my car to drive to a destination. 
The car never move by itself.**
**Is it possible for you to give us a demo video on how apollo drive automatically from point A to the selected destination? I think I have strictly followed the guideline on https://www.lgsvlsimulator.com/docs/apollo-master-instructions/ but we have not successfully run a single demo for weeks.  **
Thanks for your help again!

**Comment by rongguodong** [comment]
1. All logs can be found in /apollo/data/log.
2. You should see channels like "/apollo/sensor/camera/front_6mm/image/compressed" which is compressed image published by the simulator, and "/apollo/sensor/camera/front_6mm/image" which is decompressed image published by Apollo's decompressing module. Traffic light perception needs decompressed images to work.

**Comment by SungYinYang** [comment]
Hi rongguodong,

Thanks again for your answers.

I am not able to find logs related to what you mention.
I have searched both inside the container and outside the container.
(outside)
![image](https://user-images.githubusercontent.com/54567577/86997896-c9765800-c1e1-11ea-9094-255468c7fe91.png)
(inside)
![image](https://user-images.githubusercontent.com/54567577/86997962-edd23480-c1e1-11ea-988b-6e7dd6688593.png)

I am not able to find channels like you mentions "/apollo/sensor/camera/front_6mm/image/compressed".
![image](https://user-images.githubusercontent.com/54567577/86998184-6a651300-c1e2-11ea-851a-55267308ca47.png)

Is it possible for you to provide more details? A screenshot would be even better.

Also, do you know what modules are required to open for the automode?
The following images show that traffic light is not working.
![image](https://user-images.githubusercontent.com/54567577/86998374-d778a880-c1e2-11ea-81a7-2cde696cf2bc.png)

Thanks again for all your help!

**Comment by rongguodong** [comment]
@SungYinYang 

For perception log, you should have a "perception.INFO" under /apollo/data/log. Both obstacle and traffic light detection should write logs into it. Another way is to manually start traffic light perception by calling:
"cyber_launch start /apollo/modules/perception/production/launch/perception_trafficlight.launch"
You should see its log in the console.

To see Cyber channels, you need to run "cyber_monitor", instead of searching it in folders. Attached is a screenshot showing both "/apollo/sensor/camera/front_6mm/image/compressed" and "/apollo/sensor/camera/front_6mm/image" as green (i.e. published).
![Screenshot from 2020-07-08 22-15-38](https://user-images.githubusercontent.com/11858549/87000342-b627a600-c169-11ea-8348-9a03d2696743.png)

The required modules are clearly listed in [our instructions](https://www.lgsvlsimulator.com/docs/apollo-master-instructions/#launching-apollo-alongide-the-simulator):
"Enable Localization, Transform, Perception, Traffic Light, Planning, Prediction, Routing, and Control"
