### ISSUE TITLE
How to setup the initial position?

### ISSUE THREAD

**Issue by wsp50317** [lgsvl/simulator#81]
I tried to setup the candidated vehicle's position and rotation, but it didn't work.
So I tried to find which process clone the vehicle and give it the initial position value, but I couldn't find it out.
Thanks in advance.

**Comment by martins-mozeiko** [comment]
If you are running simulator directly in Unity editor by opening SF scene, then starting position is set by `XE_rRgged-apollo` game object. Just move/rotate to place where you want it to start.

If you are running simulator from main menu then start position in SF scene is determined by position of `spawn_transform (1)` game object. Find it in the scene hierarchy and move to place where you want car to spawn. Then save the scene. Now if you will run simulator from main menu, car should be placed in new position.

**Comment by wsp50317** [comment]
Thanks! It works.
