### ISSUE TITLE
"Ego vehicle" callback

### ISSUE THREAD

**Issue by xiao-hua-sheng** [lgsvl/simulator#815]
API has "on"_ Collision "as a collision callback," ego vehicle "ran out of the map without callback? If so, where can I find it?

**Comment by EricBoiseLGSVL** [comment]
@xiao-hua-sheng we are currently creating analysis for EGO leaving the environment mesh.  It won't release for a bit so you could make a custom sensor that raycasts down on the default physics layer and if no hit then report fall off the map.
