### ISSUE TITLE
Unable to reach localhost:8080 -- asking for login

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#826]
Hey all,

I cleared data and cache of Mozilla firefox today. Since then, I'm not able to get into the WebUI. When I click 'open browser' in the simulator, I'm asked for a login. Usually I think this gets automatically rerouted to localhost but not happening now. Giving `localhost:8080` gets me to the login landing page. I have already tried deleting the `.config` and restarting the machine. Issue still present. 
Should I have to sign up an account? or is there anyother way? 
![image](https://user-images.githubusercontent.com/12048684/85881100-ba170800-b7fa-11ea-8fec-2cc52865d277.png)

Thanks.

**Comment by lemketron** [comment]
Yes, you need to register for an account to use the simulator, but it's fast and easy to do so... thanks!

**Comment by dr563105** [comment]
Thanks. I think I registered and forgot to note down the credentials. I tried to use the forgot password feature but I don’t seem to receive any mail. It’s been about two hours.

**Comment by lemketron** [comment]
Often when a "forgot password" email is requested, it gets rejected with an error message such as (in this case):
> Delivery has failed to these recipients or groups:
> dr******@r***-a*****.**
> A problem occurred while delivering this message to this email address. Try sending this message again. If the problem continues, please contact your helpdesk.
> The following organization rejected your message: mx1.**.****-******.**.

**Comment by dr563105** [comment]
hah. I understand. I used a different domain now. All good.
