### ISSUE TITLE
Cloning project has errors 

### ISSUE THREAD

**Issue by TalhaDX** [lgsvl/simulator#83]
Hi, after cloning the project. I came across these errors. I have reimported all as well. But still stays.

Screenshot: http://prntscr.com/mfjr5c

**Comment by martins-mozeiko** [comment]
Make sure you have [Git LFS](https://git-lfs.github.com/) installed properly. We keep large files and binary files (such as WebSockerSharp.dll) in LFS storage. Git will download them automatically if you have Git LFS installed in your user.

After you install Git LFS there's no need to reclone project. Simply run `git lfs pull` and it will download missing files.
