### ISSUE TITLE
Noisy point cloud recovered from depth image?

### ISSUE THREAD

**Issue by Doodle1106** [lgsvl/simulator#839]
Hi,

I tried to recover the point cloud from the depth camera and the result is noisy along the object edges.

Below is the depth image and recovered point cloud:

![depth](https://user-images.githubusercontent.com/26222197/86562381-31842e80-bf95-11ea-8fcb-5c470d6188bc.png)
![p3d](https://user-images.githubusercontent.com/26222197/86562402-38ab3c80-bf95-11ea-8c29-8f89929919c7.png)

following is a side view of the point cloud:
![p3d_@](https://user-images.githubusercontent.com/26222197/86562467-5082c080-bf95-11ea-974e-5b19c4041f8f.png)

code to reproduce the result:
```

import cv2 as cv
import numpy as np
import open3d as o3d

def depth_to_p3ds(depth_img, fx, fy, cx, cy):
  assert(depth_img.size)
  
  h = depth_img.shape[0]
  w = depth_img.shape[1]
   
  p3ds = []
  for v in range(h):
    for u in range(w):
      z = depth_img[v][u]
      
      if z==0:
        continue
      
      x = z * (u - cx) / fx
      y = z * (v - cy) / fy

       # open3d and opencv has opposite Y direction
      y = - y 
      
      p3ds.append([x, y, z])

  return p3ds

def visualize_pointcloud(p3ds):
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(p3ds)
    o3d.visualization.draw_geometries([pcd])

depth_img = cv.imread("depth.png")
depth_img = cv.cvtColor(depth_img, cv.COLOR_BGR2GRAY)
pc = depth_to_p3ds_open3d(depth_img, 550.0394833255903, 550.0394833255903, 376, 240)
visualize_pointcloud(pc)
```

My implementation is in accordance with the result of Open3d, so I think the problem is with the image?

Any help would be appreciated!
Thanks
Joey

**Comment by EricBoiseLGSVL** [comment]
@rongguodong Any idea what could be the issue?

**Comment by Rwik2000** [comment]
Anyone has any idea? I am facing the same problem. @EricBoiseLGSVL have you resolved it?
