### ISSUE TITLE
Unable to drive with autoware lgsvl in autonomous maps using vector maps

### ISSUE THREAD

**Issue by tekrajchhetri** [lgsvl/simulator#842]
Hi,

I am trying to drive autonomous mode using vector maps and lgsvl simulator following the instructions from https://www.lgsvlsimulator.com/docs/autoware-instructions/#driving-by-following-vector-map. I drove a little with keyboard but still I cannot see vehicle moving and driving autonomously.

Where I want to drive, path.
![image](https://user-images.githubusercontent.com/52251022/86604904-a7e15a80-bfae-11ea-984f-d80e439f45c1.png)

I see vechile_cmd acceleration to zero.
![image](https://user-images.githubusercontent.com/52251022/86605098-f0991380-bfae-11ea-8ef7-330e674d3205.png)

Everything is setup correctly. From the issue https://github.com/lgsvl/simulator/issues/420
Any help would be helpful.

Software:
Autoware 1.12
LGSVL using Docker

Thanks.

**Comment by EricBoiseLGSVL** [comment]
@hadiTab @luqiang21 Any ideas?

**Comment by tekrajchhetri** [comment]
@hadiTab I was able to drive and control the vehicle using autoware. Any one wishing to achieve the same should launch the launch files provided by lgsv for simulation and launch the nodes shown in the video [https://www.youtube.com/watch?v=UaVHyV3pPSM&feature=youtu.be](https://www.youtube.com/watch?v=UaVHyV3pPSM&feature=youtu.be).

One thing to make sure is that you should be able to see blue lines and waypoints generated automatically, no need to load any waypoints.

Hope this helps!
