### ISSUE TITLE
Have some confusions about how to create stop line.

### ISSUE THREAD

**Issue by wangludong** [lgsvl/simulator#848]
Hi,
My map is left-hand drive, so how to select the "Forward" direction like the image below.
I do not quite understand the description from the doc quotes
"Example: In a right-hand drive map (cars are on the right side of the road), if the waypoints are created from the outside of the road inwards, then Forward Right should be selected."
Could you give me some more hints?
![4](https://user-images.githubusercontent.com/167162/87015143-98a51b80-c1ff-11ea-8685-7b6560ae9e57.PNG)

**Comment by EricBoiseLGSVL** [comment]
@wangludong The instructions are for the way the stopline object transform is rotated.  When sim runs, it uses these transforms to determine the intersection setup.  Please look at CubeTown annotation to see how a simple intersection is created.

This image shows the selected stopline and the z forward transform, relative to the intersection.
![AnnotationHelp8](https://user-images.githubusercontent.com/45106230/87082918-8bc4ff80-c1e0-11ea-8e9b-7b6d47d6f7ce.png)
