### ISSUE TITLE
VR Cameras with LGSVL

### ISSUE THREAD

**Issue by ElliotDickman** [lgsvl/simulator#851]
I'm looking to use LGSVL with a first-person VR camera. Is there an existing workflow to implement something like this?

**Comment by rongguodong** [comment]
What do you mean by "VR camera"? Do you mean using VR headset like HTC Vive with our simulator? Or implement a 360 camera sensor attached to ego car?

**Comment by ElliotDickman** [comment]
Using an HTC Vive with the simulator. Haven't found any resources regarding how to implement that so far.

**Comment by EricBoiseLGSVL** [comment]
@ElliotDickman We don't have any documentation outlining this, you will need to look at Unity documentation, like [this](https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@0.9/manual/index.html), to see how to implement.  As for the Simulator, make a VR camera rig sensor and add to the vehicle sensor parameters.
