### ISSUE TITLE
Simulators associated with ROS1

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#852]
Hello！
What are the LGSVL simulators currently connected to ROS1?

Where are the links to the relevant simulators and ROS1 documentation?

Thanks!

**Comment by rongguodong** [comment]
Autoware.ai and Apollo 3.0 are based on ROS1. You may refer to our instructions about them:
https://www.lgsvlsimulator.com/docs/autoware-instructions/
https://www.lgsvlsimulator.com/docs/apollo-instructions/

**Comment by Eolion** [comment]
If you use Windows you can refer to this issue : https://github.com/lgsvl/simulator/issues/754

**Comment by yumianhuli2** [comment]
OK thanks!
