### ISSUE TITLE
Modify the CubeTown environment but couldn't play the scene

### ISSUE THREAD

**Issue by duongtran11** [lgsvl/simulator#857]
Hi, I just cloned the CubeTown environment into Unity as described in the Build Instructions (https://www.lgsvlsimulator.com/docs/build-instructions/) to add some 3d objects. 

![asghdfg](https://user-images.githubusercontent.com/67900559/87503664-01244a80-c68f-11ea-9dd3-ad8f66d4ab18.png)

When I hit the play button the game display appears like this
![asdf](https://user-images.githubusercontent.com/67900559/87503634-ed78e400-c68e-11ea-9f09-285836f52c08.png)
I couldn't rotate and pan the game scene, the car didn't appears
When I build the simulator, the environment_CubeTown file has 0Kb data as show below
![Untitled](https://user-images.githubusercontent.com/67900559/87504114-151c7c00-c690-11ea-8329-5f331c8f9abc.png)
My goal is to modify the CubeTown environment then build a simulator from it.
Any help would be appreciated!

**Comment by EricBoiseLGSVL** [comment]
@duongtran11 Did you clone a vehicle?  You will need a vehicle to run a simulation

**Comment by duongtran11** [comment]
Hi Eric, I did clone a vehicle

![eynryberve](https://user-images.githubusercontent.com/67900559/87626036-ba4d5800-c755-11ea-8b2d-44747bbd34ad.png)

I just found out the problem with the environment_CubeTown has 0kb data is because I didn't install Linux Support Build (I'm running Unity on Windows so I thought Windows support build would be enough). Now when I hit play the scene it came out like this

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/67900559/87626872-9be85c00-c757-11ea-8de4-741e4075cd72.gif)

Still couldn't see the car and as you can see the road is disappeared

**Comment by EricBoiseLGSVL** [comment]
@duongtran11  Again you need to run the simulator in Editor from Loader.scene.  We are working on developer settings to run a sim from the environment scene you have open but that will not release for a bit.

**Comment by duongtran11** [comment]
I think I misunderstood something here. 
- Do I need to build the simulator first (by Simulator -> Build) in order to run it from LoaderScene. Because when you open LoaderScene and hit the play button, you got to open browser and then add map and vehicles meaning that the map need to be build in your local
- In this video https://www.youtube.com/watch?v=S0w2ahhEPbE (at 5:17) the simulator runs right from the scene with out LoaderScene

**Comment by EricBoiseLGSVL** [comment]
Yes, in 2020.05 development settings is in flux.  Simulator -> Development Settings.  You needs a built vehicle to run it.  If you don't have a asset bundle for the vehicle selected it will not work.  We are working on development settings updates and will release soon

**Comment by duongtran11** [comment]
I made it, thank you!
