### ISSUE TITLE
Creating an AssetBundle after importing an HD Map

### ISSUE THREAD

**Issue by vatanaksoytezer** [lgsvl/simulator#858]
Hello,

I am trying to create and AssetBundles (similar to one in [here)](https://content.lgsvlsimulator.com/maps/autonomoustuff/) with a freshly imported HD map (from lanelet2 style). The map seems to be imported fine (in fact I am using the same lanelet2 map downloaded from the same link for testing purposes) without any errors on console and I can visually confirm in annotate HD map view. Although, I cannot seem to find a way to make it an AssetBundle and add this map as a "new map" from the web view (the view in localhost). Any instructions regarding this issue?

Thanks a lot!

**Comment by lemketron** [comment]
This new environment tutorial video might help, especially starting at 5:40:
https://youtu.be/S0w2ahhEPbE
