### ISSUE TITLE
Apollo5.5 is support for Volta and Turing NOW?

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#861]
https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/
The current version of Apollo does not support Volta and Turing architectures (this includes Titan V and RTX 2080 GPUs).
So Apollo5.5 is support for Volta and Turing NOW?

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 yes. We are working on Apollo 5.5 support currently.  @rongguodong is the documentation released yet for 5.5?

**Comment by rongguodong** [comment]
@yumianhuli2 Please refer to this instruction for Apollo 5.5: https://www.lgsvlsimulator.com/docs/apollo-master-instructions/

**Comment by yumianhuli2** [comment]
> @yumianhuli2 yes. We are working on Apollo 5.5 support currently. @rongguodong is the documentation released yet for 5.5?

Thank you I will try！And I hope run the simulator and algorithm on one PC with 6 gigabytes of video memory：）

**Comment by rongguodong** [comment]
@yumianhuli2 Note that the latest master has bugs for perception (see https://github.com/ApolloAuto/apollo/issues/11818). You may want to test "pre6" branch instead of "master" branch.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Note that the latest master has bugs for perception (see [ApolloAuto/apollo#11818](https://github.com/ApolloAuto/apollo/issues/11818)). You may want to test "pre6" branch instead of "master" branch.
Hello！
whether the master branch has fixed this bug or not, Github cannot clone it. There is no pre6 branch on gitee!

**Comment by lemketron** [comment]
You can find the "pre6" branch here: https://github.com/ApolloAuto/apollo/tree/pre6

**Comment by yumianhuli2** [comment]
> You can find the "pre6" branch here: https://github.com/ApolloAuto/apollo/tree/pre6
> Of course you should be able to clone the project and just `git checkout pre6` to switch to this branch.

can not clone so big repo:)

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Please refer to this instruction for Apollo 5.5: https://www.lgsvlsimulator.com/docs/apollo-master-instructions/

I can not open this page https://www.lgsvlsimulator.com/docs/apollo-master-instructions/

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 You can't open our LGSVL documentation?
