### ISSUE TITLE
Can apollo-5.0 from here https://github.com/lgsvl/apollo-5.0.git work well with Ubuntu 18.04?

### ISSUE THREAD

**Issue by ForresterLu** [lgsvl/simulator#869]
I am trying to run apollo-5.0 with LGSVL, and I see the prerequisites [here](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/) and the screenshot is as followed:
![image](https://user-images.githubusercontent.com/26716009/87937484-6b8e1e00-cac7-11ea-9b74-d1da8ab89f24.png)

I saw it requires the system version of Ubuntu is 14.04 or later, did anyone try with Ubuntu 18.04 and how is it going?

**Comment by luqiang21** [comment]
@ForresterLu Yes, it works with Ubuntu 18.04. My system is 18.04 and are running apollo without problems.

**Comment by ForresterLu** [comment]
Ok, thanks.
