### ISSUE TITLE
Bulid LGSVL: how to include Mono support for Windows when installing Unity?

### ISSUE THREAD

**Issue by ForresterLu** [lgsvl/simulator#870]
When I build LGSVL with Unity, I saw in the bulid document [here](https://www.lgsvlsimulator.com/docs/build-instructions/), one step is `**IMPORTANT** include Mono support for both Windows and Linux when installing Unity`. But I cannot find where to select **Mono** in Unity Hub on Windows when insstall **Unity 2019.3.3f1**, the screenshot is shown here:
![QQ截图20200721110618](https://user-images.githubusercontent.com/26716009/88008656-61116a00-cb43-11ea-8aa1-43fd0816399a.png)

Can anyone know how to include Mono support for both Windows when installing Unity?

**Comment by lemketron** [comment]
![image](https://user-images.githubusercontent.com/96521/88009698-f707af00-cac7-11ea-9766-d8b2df6c2feb.png)
It's actually called "Linux Build Support (Mono)".

**Comment by ForresterLu** [comment]
OK, Thank you!
