### ISSUE TITLE
Invalid : Unknown Sensor type VelodyLidar in Source Code

### ISSUE THREAD

**Issue by arslansarp** [lgsvl/simulator#874]
Hi, I am trying to use LGSVL from source file. 

I tried to add VLC32 Lidar but It didn't work. 

https://www.lgsvlsimulator.com/docs/lidar-plugin/#velodyne-lidar-sensor-plugins . I took the exact sample json here.

![1](https://user-images.githubusercontent.com/33527769/88289396-00e90800-ccaa-11ea-8257-8305c590152a.PNG)
![2](https://user-images.githubusercontent.com/33527769/88289401-034b6200-ccaa-11ea-8268-bbf8a3108520.png)

However, If I download the build from github, it works with the same json.

**Comment by dr563105** [comment]
Yes this behaviour is because there is no compiled velodyne sensor inside asset bundles folder of your custom build. In the build from github, you can inside asset bundles, there will be a velodyne sensor zip file. Copy that and put it into your custom build's asset bundle. Then try. It will work.

**Comment by arslansarp** [comment]
Thanks it worked. But is there any possibility of using it in Unity Editor instead of build version ?

**Comment by arslansarp** [comment]
Thanks.

**Comment by rongguodong** [comment]
To use it in Editor, you can create a folder named "AssetBundles" at the same level of "Assets", and a sub-folder named "Sensors" inside it. Put the asset bundle "sensor_VelodyneLidarSensor" in it. (Basically having the same folder structure as for the built binary)
