### ISSUE TITLE
Can I get the reference points on the map?

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#875]
Can I get the reference points on the map directly or indirectly？And How can I DO this？

**Comment by ntutangyun** [comment]
what do you mean by reference points?

**Comment by EricBoiseLGSVL** [comment]
Yes, what do you mean "reference points"?  HDMap? What do you plan on doing with these points?

**Comment by yumianhuli2** [comment]
> what do you mean by reference points?
The scene looks like this：
https://www.bilibili.com/video/BV1ob411g7k8?from=search&seid=12094902156495632642
There are two inputs:

One: Perceived lane lines

Two: The waypoint on the lane line：like the purple dots shown below
![carsim](https://user-images.githubusercontent.com/39210837/88446842-08521200-ce60-11ea-8483-16d18d1d2e28.jpg)

The purple dot on the driveway, could the LGSVL simulator give me that?
Or can I get it from the simulator in some other indirect way?

Thank you so much！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 we are working on a lane line detection sensor and hope to release it soon.  In the meantime you can write logic that parses the closest MapLanes in simulator and create geometry or some type of UI elements in world space.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 we are working on a lane line detection sensor and hope to release it soon. In the meantime you can write logic that parses the closest MapLanes in simulator and create geometry or some type of UI elements in world space.

May I understand that this sensor can output the purple points in the figure above and convert them to the algorithm module in the local coordinate system? 
Thank you！

**Comment by yumianhuli2** [comment]
> > @yumianhuli2 we are working on a lane line detection sensor and hope to release it soon. In the meantime you can write logic that parses the closest MapLanes in simulator and create geometry or some type of UI elements in world space.
> 
> May I understand that this sensor can output the purple points in the figure above and convert them to the algorithm module in the local coordinate system?And this module is based on visual or map?
> Thank you！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 Yes, something very similar to this but it won't release for a bit.  You can create a custom sensor in the meantime and pull map data from MapManager.cs.  Yes, you can get local and world coordinates from mapLanes and mapLines.  It is based on both, they should be the same thing.
