### ISSUE TITLE
How To Run a Scenario or Test Case with Apollo

### ISSUE THREAD

**Issue by ForresterLu** [lgsvl/simulator#876]
Hello everyone, I have deployed apollo-5.0 and LGSVL on my Ubuntu 18.04, then I try to use PythonAPI to do some experiment, when I want to run a scenario or test case with apollo following the instruction [here](https://www.lgsvlsimulator.com/docs/api-how-to-run-scenario/), some error occurred and the screenshot is below:

![Screenshot 2020-07-24 23:18:01](https://user-images.githubusercontent.com/26716009/88407039-1a05cc00-ce04-11ea-950e-127f73f83054.png)

And the docker terminal error message is as followed:
![Screenshot 2020-07-24 23:32:41](https://user-images.githubusercontent.com/26716009/88408332-0196b100-ce06-11ea-84ed-ed3dd33910aa.png)

The python script I ran is [VF_S_25_Slow.py](https://github.com/lgsvl/PythonAPI/blob/master/examples/NHTSA-sample-tests/Vehicle-Following/VF_S_25_Slow.py)

It seems the question is the bridge connection, but I don't konw how to solve it, anyone know how to solve it?

**Comment by EricBoiseLGSVL** [comment]
@rongguodong Do you know what could be the issue?  Port? Dreamview not initialized right?

**Comment by lemketron** [comment]
It looks like Dreamview is working but you could load localhost:8888 in your browser to confirm. The error message is actually from the cyber bridge, not from Dreamview, and indicates a bad request sent to the cyber bridge. This can happen if the Simulator connects to the bridge thinking it is a ROS bridge instead of a Cyber bridge.

What have you selected (and entered) in the Simulations, Maps & Vehicles tab for the vehicle and bridge info?
Is Apollo running on the same host as the Simulator?

**Comment by rongguodong** [comment]
I will run this script locally to see if I can reproduce the issue.

**Comment by ForresterLu** [comment]
> It looks like Dreamview is working but you could load localhost:8888 in your browser to confirm.
> 
> The error message is actually from the cyber_bridge, not from Dreamview, and indicates a bad request sent to the cyber_bridge. This can happen if the Simulator thinks it is connecting to a ROS bridge instead of a Cyber bridge.
> 
> What have you selected (and entered) in the Simulations, Maps & Vehicles tab for the vehicle and bridge info?
> Is Apollo running on the same host as the Simulator?

Hey @lemketron , my dreamviewer is working and you can see below.
![Screenshot 2020-07-25 08:32:19](https://user-images.githubusercontent.com/26716009/88444774-66c3c400-ce51-11ea-984a-709a5e1f09ec.png)

The simulator setting is:
![bridge](https://user-images.githubusercontent.com/26716009/88444908-1dc03f80-ce52-11ea-997d-54578d406202.png)
![general](https://user-images.githubusercontent.com/26716009/88444844-de91ee80-ce51-11ea-8c21-745dd83f4f63.png)
![map vehicle](https://user-images.githubusercontent.com/26716009/88444808-9d014380-ce51-11ea-8109-aa40ecfc872e.png)

**Comment by rongguodong** [comment]
It seems you are using simulator with Python API, right? Then you need select "API Only" in the 3rd image.

**Comment by ForresterLu** [comment]
> It seems you are using simulator with Python API, right? Then you need select "API Only" in the 3rd image.

Hey @rongguodong , I selected "API Only" model and modified the connection port from `9090` to `8181` for API connection in `VF_S_25_Slow.py`:
`sim = lgsvl.Simulator(os.environ.get("SIMULATOR_HOST", "127.0.0.1"), 8181)`
And the script ran without error! Thanks for your advice!

**Comment by lemketron** [comment]
Right, sorry for the confusion with all these ports! 

As you discovered, port 9090 is where the simulator sends sensor data to the Cyber Bridge in Apollo, but the python script needs to talk to the simulator on port 8181 (or whatever port is specified in the config.yml file). 

So it makes sense if the python script was sending API commands to port 9090 then the Cyber bridge would not understand them.
