### ISSUE TITLE
About lanelet2 map

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#878]
Hello! Is OSM a Lanelet2 map? When I import the map. osm generated from the official osM website and enter the simulator, the Console  prompted "Successfully imported Lanelet2 HD Map!" But I can not see any result:)???

**Comment by luqiang21** [comment]
@yumianhuli2 Lanelet2 is a format based on OSM. It has added more tags. If no error, check `View All` in `Map Annotation` window. Defaultly, map annotation is not shown.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Lanelet2 is a format based on OSM. It has added more tags. If no error, check `View All` in `Map Annotation` window. Defaultly, map annotation is not shown.

HI！Importing Opendrive and using View All is correct, OSM is wrong

**Comment by luqiang21** [comment]
@yumianhuli2 That's expected. We only support importing lanelet2 not OSM.
