### ISSUE TITLE
Turn off default setting

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#880]
Entering the scene will generate the following elements by default

![Screenshot from 2020-07-27 11-20-00](https://user-images.githubusercontent.com/39210837/88500640-d675b280-cffb-11ea-8064-8c7f62b7e9a5.png)

How can I turn this setting off?Thank you！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 This is functionality that is needed for the simulation to run, this cannot be turned off.  What are you trying to do?

**Comment by yumianhuli2** [comment]
> @yumianhuli2 This is functionality that is needed for the simulation to run, this cannot be turned off. What are you trying to do?

Hello,I want to use the resources of the simulator to create a scene that meets my personal needs.So please tell me how to turn off these defaults, thank you！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 Again, these are required to run the simulator.  HDRP requires PostProcessing, Lights.  Managers are required for the functionality.  You can create your own scene but there are required objects that need to be added or created at runtime.  Are you just asking how to make your own environment?  If so, please see [this](https://youtu.be/S0w2ahhEPbE).

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Again, these are required to run the simulator. HDRP requires PostProcessing, Lights. Managers are required for the functionality. You can create your own scene but there are required objects that need to be added or created at runtime. Are you just asking how to make your own environment? If so, please see [this](https://youtu.be/S0w2ahhEPbE).

Hi！In short, I just want an empty scenario that contains the necessary elements of the HDRP.
Thanks for reply!
