### ISSUE TITLE
Is it possible to add different kinds of vehicles (such as bicycles) into the simulator scene?

### ISSUE THREAD

**Issue by deepaktalwardt** [lgsvl/simulator#89]
Hi, I am absolutely loving playing with the simulator. I'm wondering if it is possible to define our own 3D models and add them to the simulator in any way? If not now, is that something that would be allowed later? What would be the timeline? Thank you.

**Comment by martins-mozeiko** [comment]
Hello.

Currently to add custom models you will need to open project in Unity Editor and do any modification inside Unity Editor. You can customize anything you want there - we are providing full source code and all assets on our github. Adding bicycles will probably require writing extra code - to do custom movement behavior.

We have plans to add more detailed documentation on customizing environment a bit later.
