### ISSUE TITLE
About build-instructions.md

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#893]
This page seems to be out of order：）
https://github.com/lgsvl/simulator/blob/master/Docs/docs/build-instructions.md

**Comment by ntutangyun** [comment]
check out https://www.lgsvlsimulator.com/docs/build-instructions/

**Comment by yumianhuli2** [comment]
> check out https://www.lgsvlsimulator.com/docs/build-instructions/

Thanks！
