### ISSUE TITLE
Still needs put  assets in Assets/External/Environments？

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#897]
Still needs put  assets(Vehicle/map) in Assets/External/Environments？And where is the download-urls now?
And how are these external assets(Vehicle/map) related to and different from assetBundle assets(Vehicle/map) downloaded from the browser？
Thanks！

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 Yes, External assets are for asset creation in the source. AssetBundles and AppData are for loading a simulation at runtime and if running Loader.scene in Unity Editor

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Yes, External assets are for asset creation in the source. AssetBundles and AppData are for loading a simulation at runtime and if running Loader.scene in Unity Editor

Thanks! But what's the difference between  two assets？

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 
- Simulator/Assets/External/ is cloned repos source files for building your own asset bundles
- Simulator/AssetBundles/ are the built asset bundles
- AppData/ is the downloaded asset bundles

- This is environments/vehicles/npcs/controllables/sensors not just mesh data
- Delete your data.db and backup.db in AppData LG Simulator folder and run the 05 release build.  Then open browser and WebUI will download all default assets.  You will need to clone the repos into External yourself
