### ISSUE TITLE
can not run in apollo mode

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#90]
Hello!
     My question is how to run the simulator with apollo?
     The unity client is ok and the apollo docker was installed,the rosbridge is also ok! I mean how to make a start signal(routing cmd) for the self-driving car,then it can move by apollo algorithm in San Francisco?

**Comment by martins-mozeiko** [comment]
To start moving car follow these teps:

* Open Apollo dreamview in a browser by navigating to: `localhost:8888`
    - Select the `XE_Rigged` vehicle and `San Francisco` map in the top right corner.
    - Open the **Module Controller** tap (on the left bar).
    - Enable **Localization**, **Perception**, **Planning**, **Prediction**, **Routing**, and **Control**.
    - Navigate to the **Route Editing** tab.
    - Select a destination by clicking on a lane line and clicking **Submit Route**.

Please check the full instructions in [readme](https://github.com/lgsvl/apollo) file in our Apollo repository.
