### ISSUE TITLE
The question about lidar data for Apollo 5.0

### ISSUE THREAD

**Issue by AlexandrZabolotny** [lgsvl/simulator#902]
Hi team!
I was trying to create a local map for Apollo using the script [msf_simple_map_creator.sh](https://github.com/ApolloAuto/apollo/blob/master/scripts/msf_simple_map_creator.sh).  
I am using recorded data from the simulator for create a map. 
But I had a error  which is described [here](https://github.com/ApolloAuto/apollo/issues/11936). 

**Do you have any idea why this error occurs?**

**Comment by rongguodong** [comment]
It seems you have resolved this problem. It is a known issue and we will fix it soon.
