### ISSUE TITLE
apollo5.5+lgsvl,Run perception  module problem

### ISSUE THREAD

**Issue by GuoliangPeng** [lgsvl/simulator#903]
![12](https://user-images.githubusercontent.com/7499423/89482073-b5674b80-d7cb-11ea-9b1e-15ca4a28edae.png)
![13](https://user-images.githubusercontent.com/7499423/89482083-bac49600-d7cb-11ea-9ef3-13c5a11b04b7.png)

**Comment by ntutangyun** [comment]
these are just warnings. I'm getting similar stuff. but perception works fine.
