### ISSUE TITLE
About Cyber

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#907]
Hello! LGSVL team!
There are some questions about Cyber：
1. I have a custom data structure. How to use Cyber to create and use it?

2. If it is an empty scenario and I need to use Cyber to communicate with an external program, what is the least script I need to have?

3. Is there a simplest example scenario for teaching? Where is the relevant introduction document?

Please list the detailed steps！Thanks!

**Comment by ntutangyun** [comment]
You could ask this question in [Apollo github](https://github.com/ApolloAuto/apollo).

> I have a custom data structure. How to use Cyber to create and use it?

I think the basic steps are
* create a `*.proto` file for your custom data structure under Apollo's build directory
* compile the proto file with `protoc`, target language is c#. i.e. csharp.
* copy the compiled the file into corresponding directory inside the simulator:  `simulator/Assets/Scripts/Bridge/Cyber/`
* then you should be able to use the compiled class in your unity script. 

> If it is an empty scenario and I need to use Cyber to communicate with an external program, what is the least script I need to have?

As far as I know, LGSVL uses WebSocket to communicate with outside programs. e.g. the API endpoint and the cyber bridge. 
You could either make use of the existing API endpoint, or create new websocket classes for your self. 

> Is there a simplest example scenario for teaching? Where is the relevant introduction document?

What do you mean by example scenario?

**Comment by EricBoiseLGSVL** [comment]
@yumianhuli2 Yes, @ntutangyun pretty much covered everything.  For 3.) we have created detailed video tutorials for Autoware and Apollo and hope to release them soon.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 Yes, @ntutangyun pretty much covered everything. For 3.) we have created detailed video tutorials for Autoware and Apollo and hope to release them soon.

I'm really looking forward to this！
