### ISSUE TITLE
map annotation

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#908]
Hello！Lgsvl Team!
Using the map annotation can produce xodr and basemap. bin. Then xodr for simulation visualization, basemap. bin into the specified folder（https://github.com/ApolloAuto/apollo/tree/master/modules/map/data),So I can change the map for simulation. Do I understand that right?

**Comment by luqiang21** [comment]
@yumianhuli2 xodr is openDrive format, I am not sure what do you mean by simulation visualization. To run apollo, yes, you need Apollo map: basemap.bin and place it in corresponding folder inside Apollo.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 xodr is openDrive format, I am not sure what do you mean by simulation visualization. To run apollo, yes, you need Apollo map: basemap.bin and place it in corresponding folder inside Apollo.

After the map annotation process can I export basemap.bin and XXX.xodr at the same time？

**Comment by yumianhuli2** [comment]
> > @yumianhuli2 xodr is openDrive format, I am not sure what do you mean by simulation visualization. To run apollo, yes, you need Apollo map: basemap.bin and place it in corresponding folder inside Apollo.
> 
> After the map annotation process can I export both basemap.bin and XXX.xodr？
