### ISSUE TITLE
Custom Pedestrian Path

### ISSUE THREAD

**Issue by gizegizem** [lgsvl/simulator#910]
Hello, I am trying to make my own pedestrian path. I have followed the instructions at website. I just created the path. But it didn't work.  How can I make a connection between the path and the pedestrian itself. 

Can you help me? Thanks.

**Comment by ntutangyun** [comment]
Have you tried this script ?

https://github.com/lgsvl/PythonAPI/blob/master/quickstart/16-pedestrian-follow-waypoints.py

**Comment by EricBoiseLGSVL** [comment]
@gizegizem yes, to have a specific pedestrian walk a specific path, you should use the API.  If you want random pedestrians to walk paths then you will need to annotate the paths and make sure it is a child object of the MapAnnotation for the map.  You also need a map Nav Mesh.

- Create an empty game object and put all ped annotation under it like so.
![PedHelp0](https://user-images.githubusercontent.com/45106230/89805602-be695d00-daea-11ea-8830-df3c13de8631.png)

- Then you need a Unity Nav mesh for the meshes in the scene.  Select Window -> AI -> Navigation
- Select meshes and mark them Navigation Static like so
![PedHelp3](https://user-images.githubusercontent.com/45106230/89805893-27e96b80-daeb-11ea-8610-75340eaac0aa.png)

- Then mark the types of nav mesh for each mesh like so
![PedHelp2](https://user-images.githubusercontent.com/45106230/89806808-751a0d00-daec-11ea-8cb8-20d202b13ff2.png)

- Then bake the nav mesh and save the scene like so.  This will create a nav mesh object
![PedHelp1](https://user-images.githubusercontent.com/45106230/89806918-9aa71680-daec-11ea-9f50-49dd1150cfff.png)

Make sure the nav mesh covers the entire ground, we do a check at the spawn info object to make sure there is one present in the map and if it fails to raycast to it, it will disable the pedestrian feature.

**Comment by gizegizem** [comment]
Thank you so much @EricBoiseLGSVL 🥇  , it did work.
