### ISSUE TITLE
Is there a big map similar to SF?

### ISSUE THREAD

**Issue by dr563105** [lgsvl/simulator#916]
Hello!
Do you have a big map similar to SF? I would like to train in an another map other than SF and eventually test the robustness of the model. My requirement is to collect more than 100k data points. Therefore using cubetown or Shalun becomes so tedious. GoMentum is good but it lacks lane markings. 

I will really appreciate if there is any. Thank you.

**Comment by EricBoiseLGSVL** [comment]
@dr563105 We do not have a large map like SF planned right now sorry.  We will be releasing tools to create meshes for HDmaps for roads soon.  This might be an easy way to create a simple but larger map.

**Comment by dr563105** [comment]
No problem. Thanks Eric.
