### ISSUE TITLE
About elevationProfile and superelevation

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#917]
Hello LgsvlTeam!
I have some questions in this post.
1 In the OpenDriveMapImporter script,CalculateLinePoints(..)、 CalculateArcPoints(..)、CalculateParamPoly3Points(..) have coordinates y that compute the elevation, but why does CalculateSpiralPoints(..) and CalculatePoly3Points(..)not compute the coordinate y of this elevation?

2 Superelevation - I have not found the code to calculate the tilt Angle of the cross section. Do you know the formula and method for calculating it?

3 pos = Quaternion.Euler(0f, -(float)(geometry.hdg * 180f / Math.PI), 0f) * pos;
Why do point(pos)  have to do with angles/direction?I think calculating the pose point has nothing to do with rotation.

Thanks！

**Comment by luqiang21** [comment]
@yumianhuli2 
1. This is a known bug, `CalculateSpiralPoints(..)` and `CalculatePoly3Points(..)` also need to compute elevation. We have fixed it internally, you will see it in next release.
2. You can refer opendrive definition document for the formula of calculating it.
3. All points are computed assuming `0` angle. Finally we need to rotate them by the given heading.

**Comment by yumianhuli2** [comment]
CalculateLinePoints()--This is probably not the right function, it doesn't use angles to compute the coordinates，Especially the Z is always Zero.

**Comment by luqiang21** [comment]
@yumianhuli2 As you can in this [line](https://github.com/lgsvl/simulator/blob/8b02c852c0642347f0b05125c726ceb09bfa0b26/Assets/Scripts/Editor/OpenDriveMapImporter.cs#L277), it is using `hdg` angle to compute the coordinates. `z` is 0 because it first computes without rotation along `x` direction, then rotates the coordinate to get correct result.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 As you can in this [line](https://github.com/lgsvl/simulator/blob/8b02c852c0642347f0b05125c726ceb09bfa0b26/Assets/Scripts/Editor/OpenDriveMapImporter.cs#L277), it is using `hdg` angle to compute the coordinates. `z` is 0 because it first computes without rotation along `x` direction, then rotates the coordinate to get correct result.

Hi! luqiang!
pos = Quaternion.Euler(0f, -(float)(geometry.hdg * 180f / Math.PI), 0f) * pos 
You can only change the rotation but you can't change the coordinates？？？

Thanks！

**Comment by luqiang21** [comment]
@yumianhuli2 

1. What do you mean by `can only change the rotation but can't change the coordinates`? There is no rotation for each `pos`, it is only a 3D coordinate with `x`, `y`, `z`.

2. In `CalculateParamPoly3Points()`, following two lines are converting from `UV` space to `XY` space.
```
                pos = Quaternion.Euler(0f, -(float)(geometry.hdg * 180f / Math.PI), 0f) * pos;
                points.Add(origin + pos);
```

**Comment by yumianhuli2** [comment]
> @yumianhuli2
> 
>     1. What do you mean by `can only change the rotation but can't change the coordinates`? There is no rotation for each `pos`, it is only a 3D coordinate with `x`, `y`, `z`.
> 
>     2. In `CalculateParamPoly3Points()`, following two lines are converting from `UV` space to `XY` space.
> 
> 
> ```
>                 pos = Quaternion.Euler(0f, -(float)(geometry.hdg * 180f / Math.PI), 0f) * pos;
>                 points.Add(origin + pos);
> ```

OK!Hope for updating elevation bug.Thanks

**Comment by luqiang21** [comment]
@yumianhuli2 You already asked this https://github.com/lgsvl/simulator/issues/931 right? I am checking it.
