### ISSUE TITLE
[cyber] protoc version for protobuf c# outputs

### ISSUE THREAD

**Issue by ntutangyun** [lgsvl/simulator#918]
Hi team,

I'd like to modify some of the `proto` definition from Apollo's side. And I need to update the `protobuf` C# compiled output for LGSVL as well. 

May I know what version of `protoc` and command you are using to compile the proto into the folder: 
`/Assets/Scripts/Bridge/Cyber/Protobuf`

thanks.

**Comment by ntutangyun** [comment]
@martins-mozeiko @daviduhm Please help. thanks.

**Comment by ntutangyun** [comment]
seems that you're using `protogen` by protobuf-net.Protogen.  May I know which version are you using ? thanks

**Comment by ntutangyun** [comment]
I tried to use `protogen` version `1.0.10`, but it shows `Cannot implicitly convert type double to float` as shown below:

![image](https://user-images.githubusercontent.com/16061105/90380124-4385e080-e0ae-11ea-9f20-200293099086.png)

**Comment by ntutangyun** [comment]
found similar [issue ](https://github.com/lgsvl/simulator/issues/207)

**Comment by ntutangyun** [comment]
I tried and failed to build the `protogen`... 
I've install all the required `.netframework` but the command `dotnet build` failed to find them

Could you provide the built version in the `lgsvl/protobuf-net` repo ? thanks.

**Comment by rongguodong** [comment]
https://protogen.marcgravell.com/protogen/protogen%202.3.16.zip
Please try this download link.

**Comment by ntutangyun** [comment]
@rongguodong thanks. seems to be working with the following command:

```bash
protogen.exe --proto_path=. --csharp_out=protobuf_out/ +names=original +langver=3 modules/perception/proto/perception_obstacle.proto
```

**Comment by ntutangyun** [comment]
@rongguodong Also, I noticed that the proto files have been updated in Apollo's `pre6` branch. Are there plans to compile the latest proto files?

**Comment by rongguodong** [comment]
Yes, our next release should be compatible with pre6
