### ISSUE TITLE
lgsvlsimulator Docker image not available on dockerhub anymore

### ISSUE THREAD

**Issue by MaxandreOgeret** [lgsvl/simulator#922]
lgsvlsimulator Docker image not available on dockerhub anymore.

**Comment by lemketron** [comment]
> lgsvlsimulator Docker image not available on dockerhub anymore.

Can you say more about exactly what you're looking for?

**Comment by MaxandreOgeret** [comment]
My bad, it was a nonsense question. I was expecting to find a lgsvl docker image on dockerhub but following the documentation [here](https://github.com/lgsvl/simulator/tree/master/Docker) is good. 

Thanks !
