### ISSUE TITLE
some NPC behaviors questions

### ISSUE THREAD

**Issue by qwetqwe** [lgsvl/simulator#924]
1. in 98-npc-behavior.py, I ues`behaviours = sim.available_npc_behaviours`, but only get 3 behaviors:
 0: NPCLaneFollowBehaviour
 1: NPCWaypointBehaviour
 2: NPCManualBehaviour
where is the NPCDrunkDriverBehaviour and NPCTrailerBehaviour mentioned in py?
2. How can I use these behaviors? It seems that NPCManualBehaviour can control the NPC by manual, how to do it

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe Manual behavior is just a stub.  It hasn't been implemented yet.  ExampleNPCs repo has the DrunkDriver class that needs to be built in Editor to be able to be used in 98-npc-behavior.py.  What version of Simulator are you using?  Did this repo get released to public yet @bshin-lge ?

**Comment by qwetqwe** [comment]
Hi,@EricBoiseLGSVL, I used lgsvlsimulator-linux64-2020.05 release version.

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe Yes, sorry for the confusion, we have not released this yet but we will soon.

**Comment by qwetqwe** [comment]
@EricBoiseLGSVL ,thanks for you reply.
Expecting...
