### ISSUE TITLE
the waypoint in HD Map Annotation is wrong？

### ISSUE THREAD

**Issue by wisdom-bob** [lgsvl/simulator#925]
I was nervous about the HD Map Annotation application. First, I can't find any video to get a tutorial. Second, When I did as documentation, the reply is different. I don't know whether I download the wrong version? I just downloaded the simulator-master!
However, the function of the application is missing. For example, when I did as documentation said, [documentation link](url: https://www.lgsvlsimulator.com/docs/map-annotation/), "Make Lanes", no target waypoint came out without any error or warning message. I hope someone can help me...

**Comment by wisdom-bob** [comment]
> @wisdom-bob ,
> 
> 1. import .pcd file
> 2. create 3D-plane object and adjust its coordinates according to your map background.
> 3. then you can create lanes, according to the document  https://www.lgsvlsimulator.com/docs/map-annotation/

sorry，I‘m new for unity，could you please give me o more detailed step to tell me how to generate the 3d-plane object？

**Comment by Addi2020** [comment]
goto the tab on the top
GameObject---3DObject----plane

then adjust the scale of the plane in the inspector menu.

**Comment by wisdom-bob** [comment]
> goto the tab on the top
> GameObject---3DObject----plane
> 
> then adjust the scale of the plane in the inspector menu.

Thanks a lot. However, I can find the plane, but how to adjst the inspector...

**Comment by wisdom-bob** [comment]
> > goto the tab on the top
> > GameObject---3DObject----plane
> > then adjust the scale of the plane in the inspector menu.
> 
Thanks a lot. However, I can find the plane, but how to adjst the inspector... 
Now, I have a PointCloudRender, under that is a CollidersRoot set with many MeshCollider. 
But I don't find methods to make them into the plane.

**Comment by Addi2020** [comment]
when you click on the plane object, the inspector menu will appear, in which under the transform tab there is an option (rotation and scale) change the values of X, Y, Z, according to your map that you have been imported (.pcd file). then go to (simulator--map-annotation) and start working on creating lanes, so it will appear the yellow point on the map, then you can make waypoint and connect them together to create a lane. 
It would be better if you can shear a screenshot for further explanation.

**Comment by wisdom-bob** [comment]
> when you click on the plane object, the inspector menu will appear, in which under the transform tab there is an option (rotation and scale) change the values of X, Y, Z, according to your map that you have been imported (.pcd file). then go to (simulator--map-annotation) and start working on creating lanes, so it will appear the yellow point on the map, then you can make waypoint and connect them together to create a lane.
> It would be better if you can shear a screenshot for further explanation.

Thanks a lot!! Now I can start annotation now.

**Comment by EricBoiseLGSVL** [comment]
Thanks @Addi2020 for the help.  @wisdom-bob did this solve your issue?

**Comment by wisdom-bob** [comment]
yes，it's covered！发自我的iPhone------------------ Original ------------------From: Eric Boise  <notifications@github.com>Date: Tue,Aug 25,2020 1:27 AMTo: lgsvl/simulator <simulator@noreply.github.com>Cc: wisdom bob <jzh6229@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [lgsvl/simulator] the waypoint in HD Map Annotation is wrong？ (#925)
Thanks @Addi2020 for the help.  @wisdom-bob did this solve your issue?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/lgsvl/simulator/issues/925#issuecomment-679262604",
"url": "https://github.com/lgsvl/simulator/issues/925#issuecomment-679262604",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
