### ISSUE TITLE
Lane width calculation difference

### ISSUE THREAD

**Issue by yumianhuli2** [lgsvl/simulator#931]
Hello LGsvl Team!

I used：
var ds = s - sOffset;
var widthValue = width.a + width.b * ds + width.c * ds * ds + width.d * ds * ds * ds;
var normalDir = GetNormalDir(curLeftBoundaryPoints, idx, isLeft);
var newPoint = point + (float)widthValue * normalDir;

To calculate the width of the reference line corresponding to lane
And I got this:
![Screenshot from 2020-08-24 17-10-51](https://user-images.githubusercontent.com/39210837/91026229-15178080-e62d-11ea-9486-9ee00de2f19b.png)
The point where 3lane becomes 2lane is
![Screenshot from 2020-08-24 17-15-31](https://user-images.githubusercontent.com/39210837/91026529-70e20980-e62d-11ea-84ab-d91da4dba1b7.png)

I also compared it with the odrViewer：
![Screenshot from 2020-08-24 17-19-25](https://user-images.githubusercontent.com/39210837/91026983-12695b00-e62e-11ea-9e38-269a79358ea6.png)
But the point where 3lane becomes 2lane is (40.5,-7.2)
The reference line and the other two lanes are all the right length and Postion.But there's a 7 meter difference in the X direction and a 30cm difference in the Y direction.

So is there a bug in the lgsvl source formula or is there a problem with my usage?

The xodr file is here ：
![sample](https://user-images.githubusercontent.com/39210837/91027688-029e4680-e62f-11ea-9c4d-d3eb48ce8f0e.jpg)
plz change the file suffix name to xodr
 
And you can also download the map from this repo: https://github.com/yumianhuli2/mapSample

**Comment by luqiang21** [comment]
@yumianhuli2 There was a bug in computing normal directions. We should always use reference line points not the nearest left boundary points. That might be the reason for this issue. We have fixed this internally and it will go public very soon.

**Comment by yumianhuli2** [comment]
> @yumianhuli2 There was a bug in computing normal directions. We should always use reference line points not the nearest left boundary points. That might be the reason for this issue. We have fixed this internally and it will go public very soon.

OK！I will test it in next release soon!:)

**Comment by yumianhuli2** [comment]
> @yumianhuli2 There was a bug in computing normal directions. We should always use reference line points not the nearest left boundary points. That might be the reason for this issue. We have fixed this internally and it will go public very soon.

I tried to always use the reference lines to calculate the normal direction, and then accumulated the widthValue last time, and the result was the same.Anyway, looking forward to the update and fix it these days！
