### ISSUE TITLE
lgsvl_msgs: Viewing Traffic light bounding boxes

### ISSUE THREAD

**Issue by ashwinsarvesh** [lgsvl/simulator#942]
Hello,

I am trying to view the bounding boxes for traffic light signals by subscribing to the ground truth data
I am using LGSVL fork of Apollo 5.0
But my _Apollo.5.0/lgsvl_pkgs/lgsvl_msgs_ folder is empty.
Can someone tell me what should I do next ?

**Comment by dr563105** [comment]
Have you already tried to follow these instructions? -- https://www.lgsvlsimulator.com/docs/lgsvl-msgs/

**Comment by ashwinsarvesh** [comment]
@dr563105 This can be also used for Apollo 5.0 which uses the CyberRT bridge?
I see only ROS/ROS2 mentioned in the link.

**Comment by rongguodong** [comment]
@ashwinsarvesh How do you clone our fork of Apollo 5.0? You should get proto files in lgsvl_msgs. It is a submodule pointing to another repo ("proto" branch). If you cannot get it for some reason, you can manually clone them from here:
https://github.com/lgsvl/lgsvl_msgs/tree/protobuf

**Comment by rongguodong** [comment]
If you follow our instruction [here](https://www.lgsvlsimulator.com/docs/apollo5-0-instructions/#cloning-the-repository), you should automatically get its contents in "lgsvl_msgs".

**Comment by ashwinsarvesh** [comment]
Forgot to reply.
Thank you all for your answers

**Comment by EricBoiseLGSVL** [comment]
@ashwinsarvesh no worries, glad to help :)
