### ISSUE TITLE
Fish_eye Camera too bright 

### ISSUE THREAD

**Issue by asifsid-32** [lgsvl/simulator#945]
Hii LGSVL Team, i used fish_eye camera mounted on my ego car and the output is too bright to see the scenario. Can we do anything in the json file config to reduce the brightness ?
![Screenshot (26)](https://user-images.githubusercontent.com/69885768/91381704-a8c39980-e845-11ea-89ac-26361f3c0940.png)

**Comment by rongguodong** [comment]
It is related to auto exposure feature in HDRP. We are investigating the solution for that.

**Comment by EricBoiseLGSVL** [comment]
In the meantime you can set Exposure to fixed and 0 in PostProcessingVolume.prefab to eliminate the issue. It's in Assets/Prefabs/

**Comment by asifsid-32** [comment]
> In the meantime you can set Exposure to fixed and 0 in PostProcessingVolume.prefab to eliminate the issue. It's in Assets/Prefabs/

@EricBoiseLGSVL sorry but i am not able to find Exposure in PostProcessingVolume.prefab in 2020.06 version. Is it somewhere else ?
