### ISSUE TITLE
Lidar sensor gives sigsegv

### ISSUE THREAD

**Issue by clepz** [lgsvl/simulator#947]
![error](https://user-images.githubusercontent.com/23841025/91494935-5d9b9c00-e8c2-11ea-8083-5700013959a1.PNG)

Hi,

I've created a custom map. The map includes these:
- Terrain (It has mountains and some texture layers),
- Roads (generated with easyroad)
- Trees (used terrain brush)
- Models (cars and houses from asset store. They are lod but i use only lod0)

Unity crashes if i use lidar sensor. The screenshot above shows error. 

I can't resolve this issue. Would someone give me an advice to handle this error?

LGSVL version: 2020.05

**Comment by clepz** [comment]
I found something. If I delete terrain, everything is working.
I tried that deleting my terrain and add new terrain with no changes. But I got the same error again.

I need to use this terrain, any advice?

**Comment by clepz** [comment]
I found an old issue about my problem and solved the problem.

**Comment by SeymurSm** [comment]
Hi @clepz . Could you please share the way you solved the problem? I have same issue and can not solve the problem.

**Comment by clepz** [comment]
Sorry @SeymurSm  i totally forgot to answer.
You need to convert terrain to obj. You can do it with http://wiki.unity3d.com/index.php/TerrainObjExporter.
