### ISSUE TITLE
Can not build rosbridge for Apollo

### ISSUE THREAD

**Issue by Felixgithub2017** [lgsvl/simulator#95]
I have strictly followed the instructions in the LG Silicon Valley Lab Apollo Fork, however I am not able to build the rosbrige, it always tell me: bash: catkin_make: command not found
![image](https://user-images.githubusercontent.com/26135691/53496583-4d440e80-3add-11e9-9212-c2f52f5cbbb7.png)

Then I tried this command: source /opt/ros/indigo/setup.bash
I got the following error:
![image](https://user-images.githubusercontent.com/26135691/53496726-94ca9a80-3add-11e9-814c-6762b3353199.png)

I don't know what happens, I just followed your instructions carefully.

**Comment by martins-mozeiko** [comment]
I do not think Apollo supports running dev_into.sh as root. It probably does not set up ROS environment correctly for root user, it is set up only for non-root user.

Please try running `./docker/scripts/dev_into.sh` script without sudo. Note that you might need to change owner for some files, as you already did build with root so non-root user will not have permissions to write/modify some files.

**Comment by Felixgithub2017** [comment]
> I do not think Apollo supports running dev_into.sh as root. It probably does not set up ROS environment correctly for root user, it is set up only for non-root user.
> 
> Please try running `./docker/scripts/dev_into.sh` script without sudo. Note that you might need to change owner for some files, as you already did build with root so non-root user will not have permissions to write/modify some files.

I tried one more time and I got the following results:
![image](https://user-images.githubusercontent.com/26135691/53618001-88048e80-3c24-11e9-90d7-1ed8d62e1577.png)

![image](https://user-images.githubusercontent.com/26135691/53618123-f8131480-3c24-11e9-958c-50cba350ae83.png)

Do you have any suggestions? Thank you in advance!

**Comment by martins-mozeiko** [comment]
This means that some files before were created as root user (because of sudo). And now normal user cannot write to these files or folders.

You need to find out which files or folders are owned by root and `chown` them to your own user.

Check ~/.cache folder and ~/.cache/bazel* folders. And also check any folder in ~/apollo. Try running `find ~/apollo -user root` which will list files owned by root.
