### ISSUE TITLE
Question: does lgsvl has things similar to CARLA scenario runner for easy scenario creation?

### ISSUE THREAD

**Issue by AIasd** [lgsvl/simulator#950]
Hi!
I am just wondering does lgsvl has things similar to CARLA scenario runner for easy scenario creation? For example, I may want to create a scenario where a leading car "gets triggered" to suddenly stop as my vehicle approaches it within a certain distance. If lgsvl supports such mechanism, could you point me to some reference on creating a scenario like this? Thank you!

**Comment by EricBoiseLGSVL** [comment]
@AIasd Yes, we are currently developing a Visual Scenario Editor within the Simulator that allows users to open existing scenes, add agents, set waypoints, set triggers and support playback.  This should be releasing soon.

**Comment by wisdom-bob** [comment]
> @AIasd Yes, we are currently developing a Visual Scenario Editor within the Simulator that allows users to open existing scenes, add agents, set waypoints, set triggers and support playback. This should be releasing soon.

Hello，the history of this issue is lost? Emm..... I want to ask when the curve annotation application will be published with matched map export function

**Comment by EricBoiseLGSVL** [comment]
@wisdom-bob this is not that issue.  We are releasing the curve annotation exporter functionality soon
