### ISSUE TITLE
share the steps for LGSVL simulator to work with Xbox-360 Racing wheel EX2

### ISSUE THREAD

**Issue by rrklearn2020** [lgsvl/simulator#952]
Please share the steps for interfacing the Xbox-360 Racing wheel EX2 with LGSVL simulator

**Comment by EricBoiseLGSVL** [comment]
@rrklearn2020 
- Please look at the WheelControlCensor already in project in Assets/Scripts/Sensors and Assets/Prefabs/Sensors
- Watch this [here](https://youtu.be/Pzd8NhcRzVo)
- Be aware that our input system package is a little old.  We plan on updating soon
- Open Assets/Scripts/Controllers/SimulatorControls.asset.  This is where you will add a set of controls for the wheel.  See the previous wheel that is setup already as an example
- Save and build the asset and it will update Assets/Scripts/Controllers/Generated/SimulatorControls.cs
- Create a new WheelControlSensor or edit the existing one to support the new hardware.
- Build new simulator binary to use your new controls
