### ISSUE TITLE
"Fixed 90 degree orientation offset" according to lgsvl 2020.06 vehicle gps data is Inconsistent with data in apollo master

### ISSUE THREAD

**Issue by devynliu** [lgsvl/simulator#961]
hello,
today,i try to run 2020.06 with Apollo master.i find a question,the gps data maybe is wrong in 2020.06.
my system :Ubuntu 18.04
NVIDIA:RTX 2080Ti,drive:440.36
apollo and lgsvl run with together in ubuntu.
i make compareness with 2020.05 and 2020.06.when i use 2020.05 simulator with same sensor configure,the data in apollo master  is right.you can see the picture below.can you help slove?
the first is running with 2020.05;
the second is running with 2020.06;
![Screenshot from 2020-09-04 16-34-37](https://user-images.githubusercontent.com/27505376/92220662-e4f29c00-eece-11ea-9ee1-d029624fe681.png)
![Screenshot from 2020-09-04 16-36-08](https://user-images.githubusercontent.com/27505376/92220684-eae87d00-eece-11ea-97cb-bcb231cf3cfb.png)

**Comment by devynliu** [comment]
because this "Fixed 90 degree orientation offset in GPS odometry sensor"? why make this change?

**Comment by rongguodong** [comment]
Please download the latest AssetBundle for 2020.06 [here](https://content.lgsvlsimulator.com/maps/borregasave/).

**Comment by EricBoiseLGSVL** [comment]
@devynliu We are very sorry for this but we had been putting off this correction for many months.  We plan on releasing a blog post very soon to explain the change and why it was necessary.

**Comment by rongguodong** [comment]
@devynliu If you have the correct AssetBundle using the link above, it should work well with the HD map in Apollo master.
If you still have problem after using the latest AssetBundle, please let us know.
