### ISSUE TITLE
Using linux system for editing of existing maps

### ISSUE THREAD

**Issue by Maddy2927** [lgsvl/simulator#962]
Hey LGSVL team, I wanted to edit already existing maps to use their parking lots for my framework codes. I am currently using a linux system. 
1.) Is it possible for me to install unity editor and edit maps.
2.) Also, please explain in brief how it can be done. I am new to both unity and simulator to be honest.
Thanks in advance :)

**Comment by EricBoiseLGSVL** [comment]
@Maddy2927 Welcome to LG SVL Simulator.
1) yes, please look at our documentation on how to get started and how to create content.  We have step by step guides and videos to follow.
2) I recommend watching some Unity tutorials to familiarize yourself with Unity before taking on the simulator content creation.  Download Unity 2019.3.15f1 and create a new HDRP project.  Then use the example scene unity provides to go through unity's tutorials.  Once you have some basics down, then clone Simulator.  Good luck and please post any issues you have
