### ISSUE TITLE
[question] is lgsvl/apollo-5.0 still under maintenance  

### ISSUE THREAD

**Issue by ntutangyun** [lgsvl/simulator#967]
Hi team,

I just noticed that there are still [recent updates](https://github.com/lgsvl/apollo-5.0/commit/666007b82ba40857677650bdbbe929a6e2fb41ef) on the [lgsvl/apollo-5.0](https://github.com/lgsvl/apollo-5.0) repository. 

I wonder if this means that the apollo 5.0 version is still under maintenance for some time, for example, being compatible with future LGSVL simulator releases? 

Thank you.

**Comment by EricBoiseLGSVL** [comment]
@ntutangyun This should be the last edit to Apollo 5.0 repo.  We had requests to fix an outstanding bug that maps needed to be rotated -90 degrees.  This has been an issue for a long time and we had to update.  We apologize for the confusion.
