### ISSUE TITLE
Linux build simulation error

### ISSUE THREAD

**Issue by kanakab** [lgsvl/simulator#970]
Hello Team,

I am trying to launch the simulation, but I am getting the following error. All the Assetbundles are latest from the LGSVL content site. Any help appreciated.
Invalid: Out of date AssetBundle, rebuild or download latest AssetBundle.
![Bildschirmfoto von 2020-09-09 09-59-57](https://user-images.githubusercontent.com/57012567/92571386-5a6dbc00-f283-11ea-915d-8a58228fc0c7.png)

**Comment by EricBoiseLGSVL** [comment]
@kanakab Did you change the maps and vehicles to point at the new map/vehicle?  You also can try deleting the AppData folder for LG Simulator here C:\Users\YOU\AppData\LocalLow\LG Silicon Valley Lab\LGSVL Simulator.  Then run the binary we released, open the WebUI, sign in and all default maps and vehicles will download.  Then make the new simulation.  Your database might have old references.

**Comment by DaPineappleDude** [comment]
> @kanakab Did you change the maps and vehicles to point at the new map/vehicle? You also can try deleting the AppData folder for LG Simulator here C:\Users\YOU\AppData\LocalLow\LG Silicon Valley Lab\LGSVL Simulator. Then run the binary we released, open the WebUI, sign in and all default maps and vehicles will download. Then make the new simulation. Your database might have old references.

Well, if you look closely OP is running it on Linux

**Comment by lemketron** [comment]
> Well, if you look closely OP is running it on Linux

... in which case they should delete the `~/.config/unity3d/LG Silicon Valley Lab/LGSVL Simulator/data.db` file (or that entire directory).
