### ISSUE TITLE
Localization is off, traffic light cannot be turned on, routing does not seem to work properly when running with Apollo

### ISSUE THREAD

**Issue by AIasd** [lgsvl/simulator#973]
Hi,

I am following the instruction on [Running latest Apollo with LGSVL Simulator](https://www.lgsvlsimulator.com/docs/apollo-master-instructions/) with Apollo master branch and LGSVL2020.06.

I encountered three issues:
1. localization seems off.
2. traffic light module seems to not be able to turn on.
3. the routing also does not seem to function properly. The car does not move when I set a point and submit route request.

They are shown in the following screenshot: 
![Screenshot from 2020-09-09 23-15-15](https://user-images.githubusercontent.com/12670254/92677767-85dbbf80-f2f2-11ea-9b07-c4d4af9dfdd1.png)

I tried both the Apollo master branch today's version and a version about three months ago but the same issues appear.

**Comment by rongguodong** [comment]
This is because of the rotation of the map. Please download the latest AssetBundle of Borregas. Or you can delete the database and re-run the simulator to have it automatically download the latest AssetBundle.

**Comment by AIasd** [comment]
Hi @rongguodong , thanks for your help. After I use the latest link of Borregas map and rerun the simulator, the localization issue is solved.

Also, when I switched to pre6 as you suggested the traffic light issue gets solved and the car can now follow the route successfully.
