### ISSUE TITLE
how to configure intrinsics parameters of camera?

### ISSUE THREAD

**Issue by qwetqwe** [lgsvl/simulator#974]
I see that sensor json only has DistortionParameters without  camera matrix parameter like
fx  0   cx
0   fy  cy
0    0  1
how to configure the camera matrix as my camera?

**Comment by rongguodong** [comment]
The camera sensor uses pin-hole camera model. So all those can be calculated from other parameters.
Particularly, we have `fx = fy = Height / 2 / Mathf.Tan(FieldOfView / 2 * Mathf.Deg2Rad)`, and `cx = Width / 2.0`, `cy = Height / 2.0`.

**Comment by qwetqwe** [comment]
I got it. 
Thanks!
