### ISSUE TITLE
Subscribing sensor topics on ROS

### ISSUE THREAD

**Issue by User-712** [lgsvl/simulator#975]
Hi Team,

I'm facing issue in listening sensors topics on ROS,

Currently am running LGSVL with following specifications:
OS:Linux 16.04 (memory: 31.3 GiB, processor: core i7, Graphics: GeForce GTX)
ROS: Kinetic
Simulator: LGSVL 2020.01 (released version)

I'm able to interface lgsvl simulator through kinetic rosbridge
1.roslaunch rosbridge_server rosbridge_websocket.launch
![3](https://user-images.githubusercontent.com/71029042/92693187-e4d91d00-f362-11ea-9e49-5809f1a47ff8.PNG)
bridge status is connected

2. rostopic list output following topics:
![4](https://user-images.githubusercontent.com/71029042/92693366-2c5fa900-f363-11ea-8d7d-fa0bca006ed1.PNG)
able to get the sensor topics( currently am using default autoware car sensors)

3.command rostopic hz /imu_raw
![6](https://user-images.githubusercontent.com/71029042/92693615-79437f80-f363-11ea-8332-d3a8de6da0ba.PNG)
but there is delay in between the topic data 

Could you please help me to figure out how to get sensor topics continuously

Is the issue is with kinetic rosbridge?

Simulator setup
![1](https://user-images.githubusercontent.com/71029042/92694009-02f34d00-f364-11ea-8a70-005bcc16c645.PNG)
![2](https://user-images.githubusercontent.com/71029042/92694112-2fa76480-f364-11ea-9ef5-f16d8703ab01.PNG)

json format of vehicle:
[{"type": "GPS Device", "name": "GPS",
            "params": {"Frequency": 12.5, "Topic": "/nmea_sentence", "Frame": "gps", "IgnoreMapOrigin": true},
            "transform": {"x": 0, "y": 0, "z": 0, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "GPS Odometry", "name": "GPS Odometry",
            "params": {"Frequency": 12.5, "Topic": "/odom", "Frame": "gps", "IgnoreMapOrigin": true},
            "transform": {"x": 0, "y": 0, "z": 0, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "IMU", "name": "IMU",
            "params": {"Topic": "/imu_raw", "Frame": "imu"},
            "transform": {"x": 0, "y": 0, "z": 0, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Lidar", "name": "Lidar",
            "params": {"LaserCount": 32, "MinDistance": 0.5, "MaxDistance": 100, "RotationFrequency": 10, "MeasurementsPerRotation": 360, "FieldOfView": 41.33, "CenterAngle": 10, "Compensated": true, "PointColor": "#ff000000", "Topic": "/points_raw", "Frame": "velodyne"},
            "transform": {"x": 0, "y": 2.312, "z": -0.3679201, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Color Camera", "name": "Main Camera",
            "params": {"Width": 1920, "Height": 1080, "Frequency": 15, "JpegQuality": 75, "FieldOfView": 50, "MinDistance": 0.1, "MaxDistance": 2000, "Topic": "/simulator/camera_node/image/compressed", "Frame": "camera"},
            "transform": {"x": 0, "y": 1.7, "z": -0.2, "pitch": 0, "yaw": 0, "roll": 0}},{"type": "Keyboard Control", "name": "Keyboard Car Control"},{"type": "Wheel Control", "name": "Wheel Car Control"},{"type": "Vehicle Control", "name": "Autoware Car Control",
            "params": {"Topic": "/vehicle_cmd"} }]

And also could you please suggest is there any other way to interface LGSVL simulator with ROS other than using  rosbridge

**Comment by hadiTab** [comment]
@User-712 the performance of the Kinetic rosbridge is pretty bad and I've seen similar issues with it. Are you running it with Autoware? Since Autoware doesn't really use the camera I would suggest removing that from your sensors. That might improve things.

Overall, my first suggestion would be to try it with the Melodic rosbridge which has much better performance. If you are using Autoware, I would suggest running Autoware from docker as described in the instructions [here](https://www.lgsvlsimulator.com/docs/autoware-instructions/). The docker container uses the Melodic rosbridge.

If you must use Kinetic you could try using our fork of rosbridge available [here](https://github.com/lgsvl/rosbridge_suite). This fork is intended for use with Apollo 3.0 though and was never intended for general ROS usage so it could cause other issues.

**Comment by User-712** [comment]
I removed camera and Lidar from the sensors, now am able to get imu and gps data continuously at proper rate.

thanks for your kindly help : )

**Comment by EricBoiseLGSVL** [comment]
Thanks @hadiTab
