### ISSUE TITLE
[Suggestion] add a function to pick coordinate point in simulator

### ISSUE THREAD

**Issue by qwetqwe** [lgsvl/simulator#982]
Hi team
I think picking coordinate point in map is really important. because we need absoulute coordinate to add NPCs and annotate map.It seems that lgsvl does not have this function. lgsvl can only get point by mouse in unity, but that is not convenient.Could team add a function to get point in simulator just like dreamview:
![Kazam_screenshot_00011](https://user-images.githubusercontent.com/30464144/93156370-92b94280-f73a-11ea-9684-f2eead7e0b5a.png)
Thanks a lot

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe This could be a good idea.  Can you describe a bit more about the feature?
- We do have sensors that output lat/long coordinates, what UX/UI change to make this better/easier to use?
- Is it just coordinates that match dreamview? How would this work for other AD stacks?

**Comment by qwetqwe** [comment]
@EricBoiseLGSVL 
We can add a button in the menu or keyboard shortcut. After pressed, the mouse pointer can select point in topview in simulator. Rightdown will show the point coordinate.UTM will be better. We can also select a list of points. the points' coordinates can be copied or export a file.
That is not related with dreamview. It is just what I want.

**Comment by qwetqwe** [comment]
like this:
![Kazam_screenshot_00012](https://user-images.githubusercontent.com/30464144/93168544-bd64c480-f755-11ea-98e9-50bae2005933.png)

**Comment by lemketron** [comment]
Like this? Just "visualize" the GPS Odometry sensor...
![GPSVisualization](https://user-images.githubusercontent.com/96521/93179209-33cbdd00-f6ea-11ea-8b24-e71253edb4b3.png)

**Comment by qwetqwe** [comment]
Yes, you have to "drive"  the car to the place and it is not accurate. I think it will be better to get point directly by mouse. 
I'm sorry that I can't see the youtube video. Could you describe it?

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe The video is showing our Visual Scenario Editor, where you can set NPC waypoints and replay the scenario simulation.  This has a top down view, with mouse clicked waypoints.  Is this what you are trying to do with the coordinate system?

**Comment by qwetqwe** [comment]
@EricBoiseLGSVL , 
It seems that is what I want. Is it in unity or simulator?

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe It is not officially released yet.  We are putting the final touches and should be done soon, sorry.  In the meantime you can write a class that takes mouse position, raycasts to ground to get positions that you want while in free cam mode.  This can be written to a UI element you add and or output to a file.
