### ISSUE TITLE
A map with same name exists, cancelling map importing.

### ISSUE THREAD

**Issue by ifond** [lgsvl/simulator#985]
I want to import high-precision map, but report the following error

A map with same name exists, cancelling map importing.
UnityEngine.Debug:LogError(Object)
Simulator.Editor.ApolloMapImporter:CreateMapHolders(String, String) (at Assets/Scripts/Editor/ApolloMapImporter.cs:113)
Simulator.Editor.ApolloMapImporter:ImportApolloMapCalculate(String) (at Assets/Scripts/Editor/ApolloMapImporter.cs:79)
Simulator.Editor.ApolloMapImporter:Import(String) (at Assets/Scripts/Editor/ApolloMapImporter.cs:58)
MapImport:OnGUI() (at Assets/Scripts/Editor/Map/MapImport.cs:108)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Failed to import Apollo HD Map.
UnityEngine.Debug:LogError(Object)
Simulator.Editor.ApolloMapImporter:Import(String) (at Assets/Scripts/Editor/ApolloMapImporter.cs:67)
MapImport:OnGUI() (at Assets/Scripts/Editor/Map/MapImport.cs:108)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by luqiang21** [comment]
@ifond This means you already have a map with same name in the scene. Please remove it or rename it so you can import your new map.
