### ISSUE TITLE
How can i match the agent car position with the real world car position  ?

### ISSUE THREAD

**Issue by madara0107** [lgsvl/simulator#992]

**Comment by alexiskovi** [comment]
You can use [map_to_gps](https://github.com/lgsvl/PythonAPI/blob/b8b4e6f1f9a726f3a802eb4cef87328b20e9a9dd/lgsvl/simulator.py#L176) method to get real world coordinates:
```
x = sim.map_to_gps(self.ego.state.transform).easting
y = sim.map_to_gps(self.ego.state.transform).northing
```
More examples in [LGSVL docs](https://www.lgsvlsimulator.com/docs/python-api/#helper-functions).
