### ISSUE TITLE
the pedestrain did not follow waypoint in 2020.06

### ISSUE THREAD

**Issue by qwetqwe** [lgsvl/simulator#996]
I run 16-pedestrian-follow-waypoints.py script, but pedestrian did not walk after spawned. I use 2020.05, it works well. Is it a bug?

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe This might be a bug, we will look at this, thanks

**Comment by EricBoiseLGSVL** [comment]
@qwetqwe Have you pulled the latest PythonApi source?  There were changes for this release

**Comment by qwetqwe** [comment]
@EricBoiseLGSVL ,I'm sorry that I didn't update the Python-api
thanks!
