### ISSUE TITLE
How can I create my own data set?

### ISSUE THREAD

**Issue by DokurOmkar** [lgsvl/simulator#999]
Hello Team,

How can I create my own data set (just like BorregasAve) so that I can run simulations with Autoware for my own street? What tools do I need to achieve this? 

Please advise! Thank you!

**Comment by rongguodong** [comment]
Please refer to our instructions:
https://www.lgsvlsimulator.com/docs/add-new-map/
https://www.lgsvlsimulator.com/docs/add-new-ego-vehicle/

**Comment by DokurOmkar** [comment]
Thank you @rongguodong
